### ISSUE TITLE
op-stop-host@.service has keyword in wrong section

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1002]
```Jan 20 22:11:30 zaius systemd[1]: [/lib/systemd/system/obmc-stop-host@0.target.wants/../op-stop-host@.service:9] Unknown lvalue 'Conflicts' in section 'Service'```

This happens because the Conflicts keyword is supposed to be in the [Unit] section.  The same problem as mboxd.service has in https://github.com/openbmc/openbmc/issues/999

@geissonator will fix

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/#/c/1974/
