### ISSUE TITLE
OpenFSI: I2C: Migrate from existing device driver architecture to Linux kernel I2C

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1004]
The existing Building Block's I2C device driver is 'home brewed' and doesn't follow the typical Linux kernel I2C architecture.   In order to make use of I2C on OpenFSI we'll need to migrate the existing code to using the Linux standard interfaces.   When complete all I2C driver code should be available in the LTC Linux kernel.

**Comment by eddiejames** [comment]
- [ ] Implement basic I2C ops over FSI (reads and writes)
- [ ] Test basic I2C ops
- [ ] Implement bus recovery algorithm
- [ ] Test bus recovery
- [ ] Write device tree entries
