### ISSUE TITLE
OpenFSI: Mailbox read and writes use sbefifo

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1009]
Mailbox read and write needs to use the sbefifo to send and receive data.
Exit Criteria: Be able to compile and call the sbefifo inside of mailbox

**Comment by williamspatrick** [comment]
Is this done?  @cbostic @amboar @bradbishop

**Comment by cbostic** [comment]
@williamspatrick @bradbishop @amboar 

No, this is not done.   Is mailbox device driver using sbe fifo interfaces still the plan?    Are there any mailbox user space requirements for this item to ensure a valid end to end test?
