### ISSUE TITLE
Candidate3 driver failing to create a network

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#101]
root@palmetto:~# uname -a
Linux palmetto 4.3.0-openbmc-20151123-1 #1 Mon Nov 23 13:03:15 CST 2015 armv5tejl GNU/Linux
root@palmetto:~# ifconfig eth0 9.3.164.147 netmask 255.255.255.128
root@palmetto:~# route add default gw 9.3.164.129
root@palmetto:~# cho "nameserver 9.3.1.200" >> /etc/resolv.conf
-sh: cho: command not found
root@palmetto:~# echo "nameserver 9.3.1.200" >> /etc/resolv.conf
root@palmetto:~# ping google.com
^C
root@palmetto:~# ping google.com^C
root@palmetto:~# dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.3.0-openbmc-20151123-1 (causten@causten-VirtualBox) (gcc version 4.9.3 (GCC) ) #1 Mon Nov 23 13:03:15 CST 2015
[    0.000000] CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
[    0.000000] CPU: VIVT data cache, VIVT instruction cache
[    0.000000] Machine model: Palmetto BMC
[    0.000000] Memory policy: Data cache writeback
[    0.000000] SOC Rev: 02010303
[    0.000000] On node 0 totalpages: 114176
[    0.000000] free_area_init_node: node 0, pgdat c05149e0, node_mem_map dba79000
[    0.000000]   Normal zone: 892 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 114176 pages, LIFO batch:31
[    0.000000] UART IO MUX...
[    0.000000] UART PIN MUX...
[    0.000000] SCU LOCK: 00000001
[    0.000000] DONE, MUX=cb000000 00fff0c0
[    0.000000] CLOCK_CTRL=00000001
[    0.000000] WDT0C=00000000
[    0.000000] WDT2C=00000092
[    0.000000] DLL=1
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 113284
[    0.000000] Kernel command line: console=ttyS4,38400
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 430316K/456704K available (3585K kernel code, 171K rwdata, 1268K rodata, 176K init, 109K bss, 26388K reserved, 0K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xdc000000 - 0xff000000   ( 560 MB)
                   lowmem  : 0xc0000000 - 0xdbe00000   ( 446 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0xc0008000 - 0xc04c593c   (4855 kB)
                     .init : 0xc04c6000 - 0xc04f2000   ( 176 kB)
                     .data : 0xc04f2000 - 0xc051ccb0   ( 172 kB)
                      .bss : 0xc051ccb0 - 0xc05380bc   ( 110 kB)
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] Aspeed VIC Initiallized
[    0.000000] clocksource: moxart_timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 39817925974 ns
[    0.000000] sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 21474836475000000ns
[    0.070000] Calibrating delay loop... 190.87 BogoMIPS (lpj=954368)
[    0.070000] pid_max: default: 32768 minimum: 301
[    0.070000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.070000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.070000] CPU: Testing write buffer coherency: ok
[    0.070000] Setting up static identity map for 0x40008400 - 0x40008458
[    0.080000] devtmpfs: initialized
[    0.080000] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.080000] pinctrl core: initialized pinctrl subsystem
[    0.090000] NET: Registered protocol family 16
[    0.090000] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.160000] SCSI subsystem initialized
[    0.160000] usbcore: registered new interface driver usbfs
[    0.160000] usbcore: registered new interface driver hub
[    0.160000] usbcore: registered new device driver usb
[    0.160000] clocksource: Switched to clocksource moxart_timer
[    0.180000] NET: Registered protocol family 2
[    0.180000] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.180000] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.180000] TCP: Hash tables configured (established 4096 bind 4096)
[    0.180000] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.180000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.180000] NET: Registered protocol family 1
[    0.190000] RPC: Registered named UNIX socket transport module.
[    0.190000] RPC: Registered udp transport module.
[    0.190000] RPC: Registered tcp transport module.
[    0.190000] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.190000] Trying to unpack rootfs image as initramfs...
[   57.230000] Freeing initrd memory: 16984K (d0200000 - d1296000)
[   57.230000] alarmtimer alarmtimer: no of_node; not parsing pinctrl DT
[   57.230000] futex hash table entries: 256 (order: -1, 3072 bytes)
[   57.240000] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[   57.240000] jffs2: version 2.2. (NAND) (SUMMARY)  \xffffffc2\xffffffa9 2001-2006 Red Hat, Inc.
[   57.250000] io scheduler noop registered (default)
[   57.270000] Serial: 8250/16550 driver, 6 ports, IRQ sharing disabled
[   57.280000] serial8250 serial8250: no of_node; not parsing pinctrl DT
[   57.280000] 1e783000.serial: ttyS0 at MMIO 0x1e783000 (irq = 23, base_baud = 115200) is a 16550A
[   57.280000] 1e78d000.serial: ttyS1 at MMIO 0x1e78d000 (irq = 24, base_baud = 115200) is a 16550A
[   57.280000] 1e78e000.serial: ttyS2 at MMIO 0x1e78e000 (irq = 25, base_baud = 115200) is a 16550A
[   57.290000] 1e78f000.serial: ttyS3 at MMIO 0x1e78f000 (irq = 26, base_baud = 115200) is a 16550A
[   57.290000] console [ttyS4] disabled
[   57.290000] 1e784000.serial: ttyS4 at MMIO 0x1e784000 (irq = 27, base_baud = 115200) is a 16550A
[   57.870000] console [ttyS4] enabled
[   57.880000] 1e787000.serial: ttyS5 at MMIO 0x1e787000 (irq = 27, base_baud = 115200) is a 16550A
[   57.910000] brd: module loaded
[   57.940000] loop: module loaded
[   57.950000] bt-host 1e789140.ibt: Found bt host device
[   57.960000] bt-host 1e789140.ibt: Using IRQ 18
[   57.980000] ftgmac100 1e660000.ethernet: Using NCSI interface
[   57.990000] ftgmac100 1e660000.ethernet: Read MAC address from chip a2:16:25:3f:42:a0
[   58.000000] ftmac100: Loading version 0.2 ...
[   58.010000] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[   58.020000] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[   58.030000] usbcore: registered new interface driver cdc_acm
[   58.040000] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[   58.050000] usbcore: registered new interface driver usb-storage
[   58.060000] usbcore: registered new interface driver usbserial
[   58.070000] usbcore: registered new interface driver usbserial_generic
[   58.080000] usbserial: USB Serial support registered for generic
[   58.100000] mousedev: PS/2 mouse device common for all mice
[   58.110000] aspeed-rtc 1e781000.rtc: rtc core: registered 1e781000.rtc as rtc0
[   58.120000] i2c /dev entries driver
[   58.120000] i2c_aspeed 1e78a000.i2c: i2c controller registered, irq 19
[   58.150000] at24 0-0050: 32768 byte 24c256 EEPROM, writable, 64 bytes/write
[   58.170000] rtc-ds1307 0-0068: rtc core: registered ds3231 as rtc1
[   58.180000] i2c_aspeed 1e78a040.i2c-bus: i2c bus 0 registered, irq 220
[   58.190000] i2c_aspeed 1e78a080.i2c-bus: i2c bus 1 registered, irq 221
[   58.200000] i2c_aspeed 1e78a0c0.i2c-bus: i2c bus 2 registered, irq 222
[   58.210000] i2c_aspeed 1e78a100.i2c-bus: i2c bus 3 registered, irq 223
[   58.220000] i2c_aspeed 1e78a140.i2c-bus: i2c bus 4 registered, irq 224
[   58.240000] i2c_aspeed 1e78a180.i2c-bus: i2c bus 5 registered, irq 225
[   58.260000] i2c_aspeed 1e78a1c0.i2c-bus: i2c bus 6 registered, irq 226
[   58.280000] i2c_aspeed 1e78a300.i2c-bus: i2c bus 7 registered, irq 227
[   58.300000] i2c_aspeed 1e78a340.i2c-bus: i2c bus 8 registered, irq 228
[   68.310000] tmp421 2-004c: Could not read configuration register (-5)
[   68.320000] tmp421: probe of 2-004c failed with error -5
[   68.330000] aspeed_wdt 1e785000.wdt: rate 48000000, max timeout 5, timeout 5
[   68.340000] usbcore: registered new interface driver usbhid
[   68.350000] usbhid: USB HID core driver
[   68.360000] ip_tables: (C) 2000-2006 Netfilter Core Team
[   68.370000] NET: Registered protocol family 17
[   68.390000] aspeed-rtc 1e781000.rtc: hctosys: unable to read the hardware clock
[   68.400000] Freeing unused kernel memory: 176K (c04c6000 - c04f2000)
[   68.480000] random: systemd urandom read with 107 bits of entropy available
[   68.490000] systemd[1]: systemd 225 running in system mode. (-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS +ACL -XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN)
[   68.500000] systemd[1]: Detected architecture arm.
[   68.510000] systemd[1]: Set hostname to <palmetto>.
[   68.520000] systemd[1]: Initializing machine ID from random generator.
[   69.270000] systemd[1]: Created slice Root Slice.
[   69.280000] systemd[1]: Listening on Journal Socket.
[   69.300000] systemd[1]: Listening on Syslog Socket.
[   69.310000] systemd[1]: Listening on udev Kernel Socket.
[   69.330000] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[   69.340000] systemd[1]: Listening on networkd rtnetlink socket.
[   69.350000] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[   69.360000] systemd[1]: Created slice System Slice.
[   69.370000] systemd[1]: Created slice system-serial\x2dgetty.slice.
[   69.390000] systemd[1]: Mounting Configuration File System...
[   69.410000] systemd[1]: Starting Apply Kernel Variables...
[   69.440000] systemd[1]: Mounting Debug File System...
[   69.480000] systemd[1]: 
Reached target Remote File Systems.
[   69.550000] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[   69.570000] systemd[1]: Reached target Paths.
[   69.580000] systemd[1]: Listening on udev Control Socket.
[   69.600000] systemd[1]: Starting (null)...
[   69.620000] systemd[1]: Created slice User and Session Slice.
[   69.640000] systemd[1]: Reached target Slices.
[   69.680000] systemd[1]: Listening on Journal Socket (/dev/log).
[   69.700000] systemd[1]: Reached target Swap.
[   69.720000] systemd[1]: Starting Remount Root and Kernel File Systems...
[   69.750000] systemd[1]: Starting Journal Service...
[   69.780000] systemd[1]: Created slice system-getty.slice.
[   69.820000] systemd[1]: Mounting Temporary Directory...
[   69.930000] systemd[1]: Mounted Configuration File System.
[   69.990000] systemd[1]: Mounted Debug File System.
[   70.030000] systemd[1]: Mounted Temporary Directory.
[   70.070000] systemd[1]: Started Apply Kernel Variables.
[   70.090000] systemd[1]: Started (null).
[   70.110000] systemd[1]: Started Remount Root and Kernel File Systems.
[   70.500000] systemd[1]: Started Journal Service.
[   71.090000] systemd-journald[424]: Received request to flush runtime journal from PID 1
[   79.480000] random: nonblocking pool is initialized
[   87.070000] ftgmac100: NCSI dev is down
root@palmetto:~# 
root@palmetto:~# 
root@palmetto:~# ifconfig eth0
eth0      Link encap:Ethernet  HWaddr A2:16:25:3F:42:A0  
          inet addr:9.3.164.147  Bcast:9.3.164.255  Mask:255.255.255.128
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:150 (150.0 B)  TX bytes:1819 (1.7 KiB)

root@palmetto:~# ifconfig eth0 up
root@palmetto:~# dmesg|tail
[   69.930000] systemd[1]: Mounted Configuration File System.
[   69.990000] systemd[1]: Mounted Debug File System.
[   70.030000] systemd[1]: Mounted Temporary Directory.
[   70.070000] systemd[1]: Started Apply Kernel Variables.
[   70.090000] systemd[1]: Started (null).
[   70.110000] systemd[1]: Started Remount Root and Kernel File Systems.
[   70.500000] systemd[1]: Started Journal Service.
[   71.090000] systemd-journald[424]: Received request to flush runtime journal from PID 1
[   79.480000] random: nonblocking pool is initialized
[   87.070000] ftgmac100: NCSI dev is down
root@palmetto:~# ifconfig eth0 down
ftgmac100: NCSI dev is down
root@palmetto:~# dmesg|tail
[   69.990000] systemd[1]: Mounted Debug File System.
[   70.030000] systemd[1]: Mounted Temporary Directory.
[   70.070000] systemd[1]: Started Apply Kernel Variables.
[   70.090000] systemd[1]: Started (null).
[   70.110000] systemd[1]: Started Remount Root and Kernel File Systems.
[   70.500000] systemd[1]: Started Journal Service.
[   71.090000] systemd-journald[424]: Received request to flush runtime journal from PID 1
[   79.480000] random: nonblocking pool is initialized
[   87.070000] ftgmac100: NCSI dev is down
[  206.070000] ftgmac100: NCSI dev is down
root@palmetto:~# ifconfig eth0 up  
root@palmetto:~# Unable to handle kernel paging request at virtual address dd10a000
pgd = c0004000
[dd10a000] *pgd=5a197811, *pte=00000000, *ppte=00000000
Internal error: Oops: 7 [#1] ARM
Modules linked in:
CPU: 0 PID: 454 Comm: kworker/0:3 Not tainted 4.3.0-openbmc-20151123-1 #1
Hardware name: ASpeed SoC
Workqueue: events ncsi_dev_work
task: db604180 ti: da3a8000 task.ti: da3a8000
PC is at ftgmac100_hard_start_xmit+0x178/0x25c
LR is at 0x1
pc : [<c02386d4>]    lr : [<00000001>]    psr: 20000013
sp : da3a9dc0  ip : 5a3cc000  fp : 00000008
r10: db603580  r9 : 00000000  r8 : 00000000
r7 : db6bb800  r6 : 5a3ccc02  r5 : da014020  r4 : db6bb800
r3 : dd10a000  r2 : 0000003e  r1 : 00000000  r0 : 00000000
Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
Control: 0005317f  Table: 5a388000  DAC: 00000053
Process kworker/0:3 (pid: 454, stack limit = 0xda3a8190)
Stack: (0xda3a9dc0 to 0xda3aa000)
9dc0: 00000001 00000000 db68fd00 da014020 db603580 c02d2b04 da014020 00000000
9de0: da3a9e24 00000000 da014020 00000000 00000000 db603580 00000000 db68fd00
9e00: da014020 db603580 db6bb800 db603580 00000000 00000000 00000008 c02e9dac
9e20: da014020 00000010 db6bb800 db68fd00 da014020 db6bb800 00000000 c02d2f14
9e40: db68fd68 00000001 00000000 fffffff4 c035aeb8 db6744b0 00000000 00000010
9e60: da3a9e94 c05147ec db6bb800 c035b3e0 0000001f db674000 00000000 c04f8490
9e80: 00000000 dba6cc00 00000000 c035cf6c db468e10 db674000 1f001802 00000000
9ea0: 00000000 c0238548 00000000 dba79000 db6bb800 00000000 db674030 db674000
9ec0: c04f8490 c035d978 db674030 db674000 db67400c c035d964 da3a9efc db674000
9ee0: 00000001 c04f8d98 00000000 c04f8d98 da3d0018 db58dac0 db677030 c04f8490
9f00: 00000000 c0027c2c db58dac0 db677030 dba6cc00 db58dac0 db58dad8 db58dad8
9f20: da3a8000 c04f84a0 c04f8490 00000000 00000008 c0027d8c db677034 db58dac0
9f40: c04f8490 c00282ec 00000000 db4593e0 00000000 db58dac0 c0028014 00000000
9f60: 00000000 00000000 00000000 c002bfb8 00000000 00000000 00000000 db58dac0
9f80: 00000000 da3a9f84 da3a9f84 00000000 da3a9f90 da3a9f90 da3a9fac db4593e0
9fa0: c002bef4 00000000 00000000 c000a330 00000000 00000000 00000000 00000000
9fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
9fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[<c02386d4>] (ftgmac100_hard_start_xmit) from [<c02d2b04>] (dev_hard_start_xmit+0x254/0x2ec)
[<c02d2b04>] (dev_hard_start_xmit) from [<c02e9dac>] (sch_direct_xmit+0x78/0x180)
[<c02e9dac>] (sch_direct_xmit) from [<c02d2f14>] (__dev_queue_xmit+0x288/0x4b0)
[<c02d2f14>] (__dev_queue_xmit) from [<c035b3e0>] (ncsi_xmit_cmd+0x1a8/0x204)
[<c035b3e0>] (ncsi_xmit_cmd) from [<c035cf6c>] (ncsi_dev_start+0x84/0x3a8)
[<c035cf6c>] (ncsi_dev_start) from [<c035d978>] (ncsi_dev_work+0x1a0/0x1ec)
[<c035d978>] (ncsi_dev_work) from [<c0027c2c>] (process_one_work+0x1bc/0x2f8)
[<c0027c2c>] (process_one_work) from [<c0027d8c>] (process_scheduled_works+0x24/0x2c)
[<c0027d8c>] (process_scheduled_works) from [<c00282ec>] (worker_thread+0x2d8/0x3ec)
[<c00282ec>] (worker_thread) from [<c002bfb8>] (kthread+0xc4/0xd8)
[<c002bfb8>] (kthread) from [<c000a330>] (ret_from_fork+0x14/0x24)
Code: e0833201 e1a0ebae e584e47c e2833a01 (e5931000) 
---[ end trace 82c55953c407c3da ]---
Kernel panic - not syncing: Fatal exception in interrupt
---[ end Kernel panic - not syncing: Fatal exception in interrupt

**Comment by gwshan** [comment]
I tried to load a private kernel built from mainline. Also I tried to load the kernel by uboot command "run netboot" for couple of times. The problem can't be reproduced. The root cause is the NCSI interface isn't up in time when hitting the kernel crash as below:

- Bring up eth0. NCSI interface isn't up.
- Bring down eth0 and causes kernel crash. It's a known issue I'm tracing currently.

**Comment by causten** [comment]
So what happens next?  
 
 Sent from my iPhone using IBM Verse
 
 On Nov 24, 2015, 7:06:06 PM, "Gavin Shan" <notifications@github.com> wrote:
 
   I tried to load a private kernel built from mainline. Also I tried to load the kernel by uboot command "run netboot" for couple of times. The problem can't be reproduced. The root cause is the NCSI interface isn't up in time when hitting the kernel crash as below:  Bring up eth0. NCSI interface isn't up. Bring down eth0 and causes kernel crash. It's a known issue I'm tracing currently.

**Comment by gwshan** [comment]
There're two issues here as mentioned: (1) NCSI interface isn't up in time (2) kernel crash

I'm working on a fix for (2). Hopefully I can get something for it. Next step is to recreate (1) then I jump in to debug...

**Comment by jk-ozlabs** [comment]
Looks very similar to https://github.com/openbmc/linux/issues/17

**Comment by shenki** [comment]
Gavin has posted patches that should resolve the kernel crash. I have merged these patches into the dev-4.3 branch, and tag a release COB today.

**Comment by causten** [comment]
I have tried to recreate and it appears the fix is holding.  Thank you
