### ISSUE TITLE
OpenFSI: AST2500 Performance Evaluation

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1019]
AST2500 contains a higher performance ARM core compared to the current AST2400 on BMC test systems currently being used.   It is hoped that this extra performance will improve soft FSI communications speed.   Very little documentation exists describing any improvements in I/O accesses or coldfire core improvements so the actual performance improvement cannot be accurately estimated.  Rough estimate is ~ 110% improvement just from instruction execution speeds.

Exit Criteria:
Measure the performance of soft FSI on AST2500 versus AST2400 and determine if it is worth pursuing further.   Document results here in this story.

**Comment by shenki** [comment]
What was the result of the performance evaluation? @cbostic?
