### ISSUE TITLE
ipmi-fru-parser : map custom IPMI properties

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1021]
Custom IPMI properties and their mappings would have to defined, to create core inventory objects, for example. FYI @ratagupt and @geissonator.

**Comment by dkodihal** [comment]
This should also handle core 'presence'.

**Comment by spinler** [comment]
I thought https://github.com/openbmc/openbmc/issues/781 should handle core presence...  Core presence gets sent down as sensor sets, not FRU writes.

**Comment by dkodihal** [comment]
Okay, do you know if host sends sensor information before IPMI FRU? Thanks for pointing this out, will discuss about this further and post updates here.

**Comment by dkodihal** [comment]
Map need to map processor EC level (a custom property).

**Comment by ratagupt** [comment]
Are we interested in EC property?if not then we can close this issue.

**Comment by ratagupt** [comment]
is CCIN equivalent to EC property?

**Comment by geissonator** [comment]
We can drop ECID, but we need EC for now and put in processor revision.

**Comment by ratagupt** [comment]
No,We do need to make the change in the code as custom property have differnrt format.
