### ISSUE TITLE
openpower-vpd-parser : call inventory-manager Notify()

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1023]
Call inventory-manager Notify() to construct d-bus objects. Also update recipe to pass right eeprom path.

**Comment by dkodihal** [comment]
- [ ] Make a call to inventory-manager notify() API to construct openpower format FRUs.
- [ ] Recipe changes are required to pass system specific FRU information to openpower vpd parser.

**Comment by geissonator** [comment]
Done @dkodihal ?
