### ISSUE TITLE
ipmi-fru-parser : redesign FRU vpd data file

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1024]
Current YAML data file assumes that host will send IPMI FRU information in the same structure always. For eg a membuff will always be a board. This need not be the case. Redesign to adjust to varying IPMI structures sent by host.

**Comment by dkodihal** [comment]
FYI @ratagupt, @geissonator.

**Comment by geissonator** [comment]
Nice to have or required @dkodihal ?

**Comment by dkodihal** [comment]
Nice to have @geissonator.
