### ISSUE TITLE
Package pflash

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#103]
Create a bitbake recipe and upstream it for building pflash for the BMC. Upstream it, and add it to our images.

As of https://github.com/open-power/skiboot/commit/ed7753c8e12fc3a17a7c32da5873ff1f830e2aa7 we have support for the 32MB flash as used by Barreleye.

**Comment by bradbishop** [comment]
I'll take this.

**Comment by shenki** [comment]
@bradbishop I've got a bitbake file in my repo https://github.com/shenki/poky/commit/1761d0bb88acfcd1e6db32a82087832c3c53a350. If you could ensure that it works and integrate it into our tree that would be great!

**Comment by williamspatrick** [comment]
We should use the real pflash for v1.0 instead of the skeleton one.
