### ISSUE TITLE
Ensure all tools are building with -Wall

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#104]
Most of our custom makefiles do not set -Wall. We found a few real bugs, and lots of warnings, in our ipmid by turning this on.

We should turn it on for all repos, and once the issues are cleaned up consider adding `-Werror` to ensure we don't regress.

Having CI builds for individual packages under Travis and/or Jenkins should be a prerequisite for turning on `-Werror`, to help developers diagnose errors they may not seen on their own system.

**Comment by williamspatrick** [comment]
Assign to Matt Barth.

**Comment by msbarth** [comment]
-Wall and -Werror have been added to all packages with resulting compiler errors fixed.
