### ISSUE TITLE
Use openbmc/qemu for qemu recipe

### ISSUE THREAD

**Issue by kc8apf** [openbmc/openbmc#1056]
When building an image or attempting to use runqemu, the upstream qemu is built by bitbake.  Since all of the Aspeed and machine-specific (palmetto, witherspoon) support is in openbmc/qemu, that repo should be used by the qemu recipe instead.

**Comment by amboar** [comment]
I had some patches for this a long time back. Probably worth starting afresh though.

**Comment by amboar** [comment]
Closing this as we have decent support upstream, and we should be working to upstream our patches.
