### ISSUE TITLE
OpenFSI: Verify fsi ops, i2c works

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1082]
As a developer I want to confirm FSI operations work with the i2c driver so that the interface can communicate to hardware.
Chris Bostic - 
This issue will also cover verification of the other FSI clients: mailbox access via ADAL/Cronus, SCOM driver access: Cronus get/putscoms

Effort includes: 
- [ ] Change to mailbox adal from Cronus 

Verify FSI clients:
- [ ]  mailbox access via ADAL/Cronus
- [ ] SCOM driver access: Cronus get/putscoms

**Comment by cbostic** [comment]
This issue would also cover verification of the other FSI clients:  mailbox access via ADAL/Cronus, SCOM driver access:  Cronus get/putscoms.

**Comment by shenki** [comment]
The driver is broken when probing a second time: https://github.com/openbmc/openbmc/issues/1083
