### ISSUE TITLE
Duplicate entries with FSI kernel driver

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#1086]
When I do a getcfam with `pdbg` see this:

```
# pdbg -p0 getcfam 0xc09
p0:0xc09: 0x00000000120d1049
p1:0xc09: 0x00000000120d1049
p2:0xc09: 0x00000000120d1049
p3:0xc09: 0x00000000120d1049
p4:0xc09: 0x00000000120d1049
```

Probing shows this:
```
# pdbg -p0 probe
Overall System Topology
=======================

Kernel FSI Backend@0
    MFSI Port@100000
        FSI2PIB@1000
    MFSI Port@200000
        FSI2PIB@1000
    MFSI Port@300000
        FSI2PIB@1000
    MFSI Port@400000
        FSI2PIB@1000
    FSI2PIB@1000

CFAMs Present
=============

0: Kernel FSI Backend@0
1: MFSI Port@100000
2: MFSI Port@200000
3: MFSI Port@300000
4: MFSI Port@400000

Processors/Chiplets Present
===========================

Processor-ID 0: FSI2PIB@1000
```

**Comment by apopple** [comment]
My guess is that 21-bit FSI addressing mode isn't enabled in the kernel driver, so when pdbg probes for devices the below hMFSI accesses all wrap to either 0x0 or 0x100000 as bit-21 is dropped from the address:

2: MFSI Port@200000
3: MFSI Port@300000
4: MFSI Port@400000

**Comment by cbostic** [comment]
Found an encoding error in the address field of the FSI command.   Still testing the fix but for reference this is what I have (patched on top of the wake_slave() ) addition I sent out Friday.

diff --git a/drivers/fsi/fsi-master-gpio.c b/drivers/fsi/fsi-master-gpio.c
index 49598c33..a5f5f47 100644
--- a/drivers/fsi/fsi-master-gpio.c
+++ b/drivers/fsi/fsi-master-gpio.c
@@ -29,8 +29,8 @@
 #define        FSI_GPIO_CMD_WRITE      0
 #define        FSI_GPIO_CMD_READ       0x0400000000000000ULL
 #define        FSI_GPIO_CMD_SLAVE_MASK 0xC000000000000000ULL
-#define        FSI_GPIO_CMD_ADDR_SHIFT 37
-#define        FSI_GPIO_CMD_ADDR_MASK  0x001FFFFF
+#define        FSI_GPIO_CMD_ADDR_SHIFT 36
+#define        FSI_GPIO_CMD_ADDR_MASK  0x003FFFF8
 #define        FSI_GPIO_CMD_SLV_SHIFT  62
 #define        FSI_GPIO_CMD_SIZE_16    0x0000001000000000ULL
 #define        FSI_GPIO_CMD_SIZE_32    0x0000003000000000ULL
@@ -312,15 +312,19 @@ static void build_abs_ar_command(struct fsi_gpio_msg *cmd, uint64_t mode,
                const void *data)
 {
        uint8_t crc;
+       uint32_t addr_mask, addr_shift;
+       uint8_t offset, offset_shift;
 
+       cmd->msg = 0;
        cmd->bits = FSI_GPIO_CMD_DFLT_LEN;
        cmd->msg = FSI_GPIO_CMD_DEFAULT;
        cmd->msg |= mode;
-       cmd->msg &= ~FSI_GPIO_CMD_SLAVE_MASK;
        cmd->msg |= (((uint64_t)slave) << FSI_GPIO_CMD_SLV_SHIFT);
-       addr &= FSI_GPIO_CMD_ADDR_MASK;
-       cmd->msg |= (((uint64_t)addr) << FSI_GPIO_CMD_ADDR_SHIFT);
+
        if (size == sizeof(uint8_t)) {
+               addr_mask = 0x003FFFF8;
+               addr_shift = 0;
+               offset_shift = 37;
                if (data) {
                        uint8_t cmd_data = *((uint8_t *)data);
@@ -328,6 +332,9 @@ static void build_abs_ar_command(struct fsi_gpio_msg *cmd, uint64_t mode,
                                ((uint64_t)cmd_data) << FSI_GPIO_CMD_DT8_SHIFT;
                }
        } else if (size == sizeof(uint16_t)) {
+               addr_mask = 0x003FFFF0;
+               addr_shift = 1;
+               offset_shift = 38;
                cmd->msg |= FSI_GPIO_CMD_SIZE_16;
                if (data) {
                        uint16_t cmd_data;
@@ -337,6 +344,9 @@ static void build_abs_ar_command(struct fsi_gpio_msg *cmd, uint64_t mode,
                                ((uint64_t)cmd_data) << FSI_GPIO_CMD_DT16_SHIFT;
                }
        } else {
+               addr_mask = 0x003FFFE0;
+               addr_shift = 2;
+               offset_shift = 39;
                cmd->msg |= FSI_GPIO_CMD_SIZE_32;
                if (data) {
                        uint32_t cmd_data;
@@ -346,6 +356,11 @@ static void build_abs_ar_command(struct fsi_gpio_msg *cmd, uint64_t mode,
                                ((uint64_t)cmd_data) << FSI_GPIO_CMD_DT32_SHIFT;
                }
        }
+       offset = (addr >> addr_shift) & 0x03;
+       cmd->msg |= ((uint64_t)offset) << offset_shift;
+
+       addr &= addr_mask;
+       cmd->msg |= (((uint64_t)addr) << FSI_GPIO_CMD_ADDR_SHIFT);
 
        if (mode == FSI_GPIO_CMD_WRITE)
                cmd->bits += (8 * size);
-- 
1.8.2.2

**Comment by cbostic** [comment]
[patch.txt](https://github.com/openbmc/openbmc/files/756069/patch.txt)

**Comment by cbostic** [comment]
The attached patch should fix the issue.  I'm in process of testing this out.

**Comment by cbostic** [comment]
Still dealing with addressing issues on anything greater than 0x1F FFFF on P8/P9 CFAMs.   Continuing debug.  Note that this should not impact accesses to the local P9, only hub links which is not part of the manufacturing stage 2 deliverables.

**Comment by cbostic** [comment]
There are a couple of ways to approach a fix for this.   I see that PDBG just infers the slave ID from the address instead of taking a slave ID parameter as the OpenFSI sysfs raw read/write utilities do.  The most straightforward solution would be to override the slave ID parameter passed in and just calculated it from the address.  That way PDBG doesn't have to change anything.

Slave ID:
0:  Address range 0x0000 0000 - 0x001F FFFF
1:   Address range 0x0020 0000 - 0x003F FFFF
2:  Address range 0x0040 0000 - 0x005F FFFF
3:  Address range 0x0060 0000 - 0x007F FFFF

Another alternative would be to add a new sysfs raw/read file that is on a per FSI link basis instead of per slave.   I'm in favor of the first option of modifying the slave ID.

First solution will also fix issue 1085.

**Comment by cbostic** [comment]
I've verified my  new patch fixes issue.   Just doing sanity checks on it now to make sure no build warnings, etc on various platforms.

**Comment by cbostic** [comment]
Patch submitted for review.

**Comment by shenki** [comment]
I have merged the fixes from @cbostic and @eddiejames and the situation is worse.

```
pdbg -p0 probe
pdbg: Failed to read from 0x00080c24 (0000000000080c09): Input/output error
pdbg: Failed to read from 0x00100c24 (0000000000100c09): Input/output error
pdbg: Failed to read from 0x00180c24 (0000000000180c09): Input/output error
pdbg: Failed to read from 0x00000c24 (0000000000200c09): Input/output error
pdbg: Failed to read from 0x00080c24 (0000000000280c09): Input/output error
pdbg: Failed to read from 0x00100c24 (0000000000300c09): Input/output error
pdbg: Failed to read from 0x00180c24 (0000000000380c09): Input/output error
pdbg: Failed to read from 0x00000c24 (0000000000400c09): Input/output error
Overall System Topology
=======================

Kernel FSI Backend@0
    FSI2PIB@1000

CFAMs Present
=============

0: Kernel FSI Backend@0

Processors/Chiplets Present
===========================

Processor-ID 0: FSI2PIB@1000
```

This is the same machine using the existing /dev/mem backend:
```
pdbg -b fsi -d p9z probe -a
Overall System Topology
=======================

BMC FSI Backend@0
    MFSI Port@100000
        FSI2PIB@1000
    FSI2PIB@1000

CFAMs Present
=============

0: BMC FSI Backend@0
1: MFSI Port@100000

Processors/Chiplets Present
===========================

Processor-ID 0: FSI2PIB@1000
Processor-ID 1: FSI2PIB@1000
```

**Comment by cbostic** [comment]
This is related to the discussion @apopple and I had in the #openfsi slack channel last Thursday.   The addresses that return error are MFSI address space.   Agreed the behavior is different than original pdbg but for mfg stage 2 this is not a requirement.   

Since MFSI isn't being used PDBG could either skip the probe of these lines or it sounds like the FSI driver may be able to deal with this by issuing a break after error.

The fix I put in place was to deal with CFAM ID.  Not the error recovery.

**Comment by cbostic** [comment]
Based on the discussion @apopple and I had in the #openfsi channel just now PDBG has some boot script that initializes hub link 1 at address base 0x100000.  The associated hub FSI link must be initialized via this script (and later automatically via openfsi driver). in order for addresses 0x100000 + to become a valid range.
