### ISSUE TITLE
Create dropbear key on boot.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#109]
First time you connect via SSH, connection is pretty slow.  We should create the dropbear key on boot.

See:

https://github.com/koenkooi/Angstrom-integration-layer/blob/master/meta-oe/recipes-core/dropbear/dropbear-systemd/dropbearkey.service

**Comment by shenki** [comment]
Is this asynchronous? We don't want to block booting for key generation.

How much does it slow down our boot time?

**Comment by bradbishop** [comment]
@shenki its async.  It won't slow the boot time down at all.

**Comment by bradbishop** [comment]
resolved here: https://github.com/openbmc/openbmc/pull/112
