### ISSUE TITLE
device callout - dbus error event to inventory association

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1093]

**Comment by dkodihal** [comment]
- [ ] Write python script to generate c++ code out of MRW callout generator output. This will be used by phosphor-logging.
- [ ] logging: map callout information in a committed error, via callout metadata, to a class of callouts, such as FSI or I2C.
- [ ] logging: Have the error d-bus objects implement the Association interface.
- [ ] logging: create associations between error and inventory objects to represent a callout.
- [ ] tool/test to create callouts
