### ISSUE TITLE
openpower-vpd-parser : add support for 'fieldReplaceable' and 'cacheable' 

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1099]
'cacheable' is not critical for mnfg stage 2.

'fieldReplaceable' will tell if the item is a FRU. Note that this property is a boolean, so far we assume properties are strings, so the property's type will have to expressed in the config yaml and used accordingly.

**Comment by dkodihal** [comment]
- [ ] Update FRU config YAML to incorporate "types" of properties.
- [ ] Have FRUs implement the FieldReplaceable interface.
- [ ] Fetch FieldReplaceable value from MRW and add it to the inventory object.

**Comment by geissonator** [comment]
Done!
