### ISSUE TITLE
net-ipmid/libapphandler.so.0: undefined symbol: _ZN9sdbusplus6server11transaction7details2idE

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1106]
Flashed an image off of https://github.com/bradbishop/openbmc/commits/deepak for some host IPMI bringup on witherspoon.  The netipmid app is hitting this on startup:

```
netipmid 
Registering handler: /usr/lib/net-ipmid/libapphandler.so.0
Error opening /usr/lib/net-ipmid/libapphandler.so.0/usr/lib/net-ipmid/libapphandler.so.0: undefined symbol: _ZN9sdbusplus6server11transaction7details2idE
```

**Comment by geissonator** [comment]
Probably has to do with pulling this batch of code in @anoo1? - https://github.com/bradbishop/openbmc/commit/81bebc0fc4d0551a5849ce2cc9d8deb2c83f7041

**Comment by williamspatrick** [comment]
The phosphor-logging repo might be missing an RDEPEND="libsdbusplus".  I think we have a number of those problems with the changes going in.

**Comment by williamspatrick** [comment]
@bradbishop - FYI.

**Comment by dkodihal** [comment]
I think phoshphor-host-ipmi also needs to link with libsdbusplus.

**Comment by williamspatrick** [comment]
That causes a serious issue... phosphor-host-ipmid doesn't itself even use any sdbusplus header files.  How is that repository (both at an autotools level and at a bitbake level) suppose to know that it should link against libsdbusplus?

**Comment by williamspatrick** [comment]
Since there is no `libphosphor-logging.so`, there isn't any direct way to get `libipmi.so -> libphosphor-logging.so -> libsdbusplus.so`.  I suspect the "solution" is to have phosphor-logging provide a package-config entry where the LDFLAGS and CFLAGS point, indirectly, at libsdbusplus.so.

**Comment by williamspatrick** [comment]
It does seem like pkgconfig 'Requires' statements are there to deal with this.  See "Metadata File Syntax" at https://linux.die.net/man/1/pkg-config.
