### ISSUE TITLE
ipmid fails to start

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1107]
It seems the ipmid fails to start on a witherspoon (w38).

root@witherspoon:/usr/sbin# Registering handler:[/usr/lib/host-ipmid/libsysintfcmds.so.0]
Registering NetFn:[0x6], Cmd:[0x35]
Registering NetFn:[0x6], Cmd:[0x2E]
Registering NetFn:[0x6], Cmd:[0x31]
Registering handler:[/usr/lib/host-ipmid/libstrgfnhandler.so.1]

[1]+  Segmentation fault      (core dumped) ./ipmid

**Comment by williamspatrick** [comment]
Can we get a core file and/or backtrace?

**Comment by dkodihal** [comment]
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.2-12"
VERSION_ID="v1.99.2-12-g3d4dc92-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.2-12"
BUILD_ID="v1.99.2"

**Comment by dkodihal** [comment]
I'll get a backtrace and upload here.

**Comment by dkodihal** [comment]
This will be fixed via https://gerrit.openbmc-project.xyz/#/c/2367/
