### ISSUE TITLE
ipmid terminates while trying to process esel

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1111]
On a patched Witherspoon (w37. multiple patches - all related to inventory), I observed this post successful inventory creation : the ipmid terminated with these messages -

Failed to call the method: send_esel_to_dbus Connection reset by peer
Failed to send esel to dbus
Failed to call the method: Transport endpoint is not connected
Dest: :1.1, Path: /org/openbmc/HostIpmi/1

Maybe a communication to a non-existent object? Could this be fixed by your current work related to host errors @anoo1 ?

**Comment by dkodihal** [comment]
Related information in https://gerrit.openbmc-project.xyz/#/c/2289/1/storageaddsel.cpp

**Comment by anoo1** [comment]
@tomjoseph83 Can you check this out? Seems the same as https://github.com/openbmc/openbmc/issues/996

**Comment by dkodihal** [comment]
Seeing this on w37.

**Comment by geissonator** [comment]
@anoo1 what was your quick fix for this one?

**Comment by anoo1** [comment]
Comment out the failing code. https://gerrit.openbmc-project.xyz/#/c/2464/

**Comment by williamspatrick** [comment]
Fixed by openbmc/phosphor-host-ipmid@513d68e
