### ISSUE TITLE
Zaius: OpenFSI master scan not working

### ISSUE THREAD

**Issue by cbostic** [openbmc/openbmc#1113]
Running echo 1 > scan  on the fsi-master on Zaius does not kick off a proper FSI device scan.   Based on the lack of output from that command this would be typical of a potential GPIO pin assignment problem.

Will need to identify the hardware source documentation and compare to the newly integrated Zaius dts gpio tree bindings.

**Comment by geissonator** [comment]
@amboar @spinler ?

**Comment by nkskjames** [comment]
I don't see any fsi things in zaius dts.    here is the assignment:
`		clock-gpios = <&gpio ASPEED_GPIO(C, 3) GPIO_ACTIVE_HIGH>;
		data-gpios = <&gpio ASPEED_GPIO(C, 2) GPIO_ACTIVE_HIGH>;
		mux-gpios = <&gpio ASPEED_GPIO(A, 6) GPIO_ACTIVE_HIGH>;
		enable-gpios = <&gpio ASPEED_GPIO(D, 0) GPIO_ACTIVE_HIGH>;
		trans-gpios = <&gpio ASPEED_GPIO(O, 6) GPIO_ACTIVE_HIGH>;`

**Comment by spinler** [comment]
I saw on the mailing list that @shenki was working on this.

**Comment by shenki** [comment]
There is a patch on the mailing list. I have an ack from @GHF so that will go in on Monday.
