### ISSUE TITLE
OpenFSI: Rescan of FSI buses increments the master ID each time

### ISSUE THREAD

**Issue by cbostic** [openbmc/openbmc#1138]
When running echo 1 > scan to find all FSI devices the FSI master ID is incremented.   If multiple scans are done without a system reset then the ID will continue to grow.  Should stay at master ID 1 for the GPIO based BMC FSI master.

**Comment by bradbishop** [comment]
https://gerrit.openbmc-project.xyz/#/c/3703/

**Comment by cbostic** [comment]
Resolved in OpenBMC kernel a while back.
