### ISSUE TITLE
openFSI: Define and implement power off requirements

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1151]
Per recent discussion, there may be things we need to do during the chassis power off to tell the openFSI drivers to shut things down properly.

**Comment by vishwabmc** [comment]
@geissonator Please tag enhancement

**Comment by geissonator** [comment]
Per an internal discussion, we think the goal here is to create a service that does an unscan of the fsi device so that services like hwmon will stop monitoring fsi based devices.

**Comment by geissonator** [comment]
Duplicate of #1698 ?

**Comment by geissonator** [comment]
@cbostic, anything we need to do here or are we good?

**Comment by cbostic** [comment]
I think this is a dup of #1698  (?)  @eajames do you know of any other requirements for power down / FSI besides that?

**Comment by rfrandse** [comment]
No other known requirements
