### ISSUE TITLE
OpenFSI: i-poll runs continuously, can be optimized.

### ISSUE THREAD

**Issue by cbostic** [openbmc/openbmc#1153]
Right now FSI i-poll checks for interrupts on a regular basis whether or not there are any client drivers looking for interrupts, for example I2C.   i-poll should be controlled such that a client can turn it off or on based on needs.

I2C transmit case:
send i2c bus command
start i-poll
receive all interrupts related to the i2c bus command
stop i-poll

**Comment by vishwabmc** [comment]
@geissonator Please tag enhancement

**Comment by geissonator** [comment]
@rfrandse is there an OpenFSI epic to get these under?
