### ISSUE TITLE
Cleanup old inventory related code

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1163]
Cleanup skeleton inventory code.

**Comment by ratagupt** [comment]
1) cleanup from system_manager.py
2) cleanup from inventory_manager.py
3) cleanup or config change for sync_inventory.py.

**Comment by ratagupt** [comment]
Clean up from configs/<machine>.py

**Comment by geissonator** [comment]
End result here is bitbake change that removes old inventory manager

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/#/c/8793/ gets a big chunk of this.
