### ISSUE TITLE
Build openpower-dbus-interfaces

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1167]
Need to build the openpower-dbus-interfaces as it's currently done for phosphor-dbus-interfaces.
Some options discussed were to have the openpower layer bbappend phophos-dbus-interfaces and copy the files in, take the makefile generation script from phosphor-dbus-interfaces and put it in sdbusplus for any repo to use, duplicate what phosphor-dbus-interfaces does,...,.

**Comment by dkodihal** [comment]
@rfrandse @geissonator I'm doing this with #1040.
