### ISSUE TITLE
OpenFSI: scom client driver does not support 64 bit scom addresses

### ISSUE THREAD

**Issue by eddiejames** [openbmc/openbmc#1175]
`static int put_scom(struct scom_device *scom_dev, uint64_t value,
			uint32_t addr)
`

`static int get_scom(struct scom_device *scom_dev, uint64_t *value,
			uint32_t addr)
`

**Comment by eddiejames** [comment]
Can be assigned to me, I can't assign to myself??

**Comment by rfrandse** [comment]
- 04/07 - Matt L tested and looks good, so pushed to cronus. Can be closed.
