### ISSUE TITLE
Add driver for IR35221

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1177]
Implement an hwmon driver for the IR35221

**Comment by geissonator** [comment]
We need an hwmon driver for this i2c device.  The main use case here is to read the temperature from the device.

**Comment by shenki** [comment]
What device are we referring to here?

**Comment by jk-ozlabs** [comment]
What's the actual sensor device?

**Comment by spinler** [comment]
It's an IR35221.  The temp is obtained with the 0x8D READ_TEMPERATURE_1 PMBUS command

**Comment by sammj** [comment]
I've coincidentally started writing the `IR35221` driver already (along with the `IR3806x`), I'll jump back on that and finish it up.

**Comment by sammj** [comment]
http://patchwork.ozlabs.org/patch/753119/

**Comment by shenki** [comment]
v2: http://patchwork.ozlabs.org/patch/756975/

**Comment by shenki** [comment]
This has been accepted by the upstream maintainer. I have merged it into the dev-4.10 tree.

Once the device tree and config changes are merged we can close this issue.

**Comment by bradbishop** [comment]
Moving to @cbostic to get the DT and kernel config updated.

**Comment by bradbishop** [comment]
Adding @cbostic task list from #1612:

- [x] Review device driver and understand all device tree requirements, bus type etc...
- [x] Obtain card schematics including details for IR35221.
- [ ] Identify i2c bus and address details for Witherspoon
- [ ] Code and integrate changes to dts file.
- [ ] Load kernel on test system and verify device is identified and probed

**Comment by cbostic** [comment]
Enabled the driver and the ir35221's are showing up as expected
```
root@witherspoon:/sys/bus/i2c/drivers/ir35221# ls
4-0070  4-0071  5-0070  5-0071  bind    uevent  unbind
```

**Comment by bradbishop** [comment]
The scope of this issue was (perhaps repurposed) only to make the DT and config updates, which is complete.   We have #1702 to track unbinding prior to use with i2cset.  Closing...
