### ISSUE TITLE
u-boot: NCSI stops working

### ISSUE THREAD

**Issue by cyrilbur-ibm** [openbmc/openbmc#118]
While fixing another networking issue I've noticed that if many tftpboot commands are run on the BMC eventually the NCSI layer stops initialising properly rendering the networking non-operational on the BMC.

It appears that nothing can be done to recover except reset which solves this problem (but it will return if too many tftp commands are run).

I was testing by downloading 16MB of firmware, I am unsure if this is related to the size of the download or simply the count.

**Comment by shenki** [comment]
I have not seen this issue for a long time. Please close
