### ISSUE TITLE
Need pdbg CFAM workaround for openFSI

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1180]
We've got a pretty little hack for a certain CFAM address in https://github.com/openbmc/openbmc/blob/d3661bd14892437925a09c37cf99393f97eaf0ad/meta-openbmc-machines/meta-openpower/common/recipes-bsp/pdbg/pdbg/0001-CFAM-reg-0x2918-access-hack.patch

After some discussion, we realized we can do this and it will work for all address's:

(X & 0xFC00) | ((X & 0x3FF) << 2)

Please update code in pdbg (https://github.com/open-power/pdbg/blob/master/libpdbg/kernel.c#L103) to use this logic for get and put cfams and do a pull request to get it merged.  Then update our pdbg recipe in openbmc to pick up the fix - meta-openbmc-machines/meta-openpower/common/recipes-bsp/pdbg/pdbg.bb

**Comment by apopple** [comment]
I think it would be best if we also added a warning when someone tries to do a get/putcfam 0x900 as there are currently scripts all over the place that need updating.

We can revert the warning later.

**Comment by chinaridinesh** [comment]
Updated pdbg.bb with latest commit ID and changed vcs_workaround.sh file  updating fsi slave address to 0x840.
https://gerrit.openbmc-project.xyz/#/c/3003/

**Comment by bradbishop** [comment]
I'm told this is fixed here (@chinaridinesh):

https://gerrit.openbmc-project.xyz/#/c/3049/
