### ISSUE TITLE
Power Measurements Working

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1184]
Temperatures are needed, but are somewhat meaningless unless fully exercising the components
- All from OCC via APSS
  - Similar story to OCC stuff #1183 (Temperatures from OCC)

**Comment by bradbishop** [comment]
Use this story to add phospor-hwmon config files for the OCC.

**Comment by bradbishop** [comment]
Using https://github.com/openbmc/openbmc/issues/1183 to track both temps and power.
