### ISSUE TITLE
Fixed Fan Speeds

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1185]
At the very least we have to be able to manually fix fan speeds for a test. If fan speed control isn't working and cannot set the fan speed, then there is very little that can be done. Getting the fan speed table working for both air and water is very important.
1. Stop the control object, then write the settings for manual override? 
   - Dbus object to set the fan speed needed
2. Next is fan control

**Comment by bradbishop** [comment]
This should be working with the current design and WIP stories.  Closing.
