### ISSUE TITLE
115C shutdown Capability

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1186]

**Comment by msbarth** [comment]
Tentative task list, second task dependent on results from design meeting discussion.
(Previous discussions noted having error logging perform the shutdown as a callout.)

- [ ] Discuss shutdown mechanism at design meeting
- [ ] Create necessary interfaces to perform shutdown(assuming using dbus objects to phosphor-logging)
- [ ] Add shutdown function to sensor monitor
- [ ] Enable shutdown action in sensor monitor YAML

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5016> Add Witherspoon thermal policy
Resolves:  #1186 115C shutdown Capability
