### ISSUE TITLE
Sense both Fan RPMS

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1188]
After the hwmon driver supports both rotors, update the MRW, YAML and applications to support it.

**Comment by geissonator** [comment]
Basically just a config file for the max chip here (make work with hard coded config file)
Need new story to do via MRW (2.1)

**Comment by bradbishop** [comment]
This is up for code review.

**Comment by bradbishop** [comment]
https://gerrit.openbmc-project.xyz/#/c/5205/

**Comment by zahrens** [comment]
@bradbishop Does this need some story points?

**Comment by bradbishop** [comment]
@zahrens I think this was sized this way intentionally.  It was less than a days worth of work.
