### ISSUE TITLE
net-ipmid: Implement RAII for openssl crypto init functions

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#1199]

**Comment by tomjoseph83** [comment]
# **STATUS**

7/31
Pushed a fix for issue no 1781

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5743> Implement RAII for openssl crypto function
Resolves  #1199 net-ipmid: Implement RAII for openssl crypto init functions
