### ISSUE TITLE
Refactor action target names

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1205]
See mailing list thread here for details - https://lists.ozlabs.org/pipermail/openbmc/2017-February/006768.html

We'll need to be careful when we rename them to also change the host and chassis state code at the same time (and any other code references to them).

**Comment by JoshDKing** [comment]
This is what I'll be changing:
obmc-power-chassis-on  ->  obmc-chassis-poweron
obmc-power-chassis-off  ->  obmc-chassis-poweroff

obmc-chassis-stop  ->  obmc-host-stop
obmc-chassis-start  ->  obmc-host-start
obmc-stop-host       ->  obmc-host-shutdown
Any comments let me know.
