### ISSUE TITLE
Copy PNOR squashfs image to the PNOR chip

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1206]
Copy the generated PNOR squashfs image (https://github.com/openbmc/openbmc/issues/1037) from the BMC to the read-only partition in the PNOR chip.

**Comment by saqibkh** [comment]
- [ ]  Perform a code update by copying the squashfs image to the pnor chip (mount point to be decided)

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/3744/
