### ISSUE TITLE
phosphor-fan-presence: Populate fan detection definitions from MRW

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1209]
Update phosphor-fan-presence to generate the fan detection definition yaml file from MRW data.
Along with this change, convert to the use of a mako template.

**Comment by spinler** [comment]
- [ ] generate .cpp from yaml using mako
- [ ] figure out what needs to go into the MRW to generate the YAML, and add it to the Witherspoon XML
- [ ] write a new perl script to generate yaml from the MRW XML
- [ ] update recipes so the perl runs during the build if the MRW is enabled
