### ISSUE TITLE
boot progress and inventory states  for cores

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1211]
Core state is done, just need to look at boot progress here

**Comment by williamspatrick** [comment]
@dhruvibm - Is this already done by the sensor implementation?

**Comment by geissonator** [comment]
ping @dhruvibm ^

**Comment by dhruvibm** [comment]
@williamspatrick @geissonator creating a boot progress xyz interface and setting it through IPMO is part of story #1608

**Comment by dkodihal** [comment]
Closing this one based on previous comment.
