### ISSUE TITLE
 occ active sensors

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1213]
This story is to track all sensors required by Host TMGT to get the OCC active.  Some are already in place and just need to be verified, some are new and will need to be supported.  This is the bare bones story to get the required responses in place.

- Power Cap Set and Enable/Disable - Should already be in place, just need to verify and work with automated test team to get tests in place.
- Power supply redundancy sensor - Hard code response to not redundant
- Turbo Allowed - Need a mechanism for this to be modified externally and reported to HTMGT via sensor
- OCC Active - HTMGT sets this sensor to indicate OCC is active, obmc code needs to support that
- Power supply derating factor - This should just be hard coded to 10.  Need follow up story to retrieve this from power supply.

**Comment by geissonator** [comment]
Some info from Chris:
Christopher Cain @spinler , the list of sensors used by HTMGT for Witherspoon / openbmc is:
OCC Active
Turbo Allowed
Current/Next PS Redundancy
PS derating factor
(user power limit/state)

**Comment by ojayanth** [comment]
Power Cap Set and Enable/Disable Support is not in place. 
"Mar 21 20:56:07 witherspoon sensor_manager2.py[752]: Set PowerCap Error 1/bin/sh: /sys/class/hwmon/hwmon3/user_powercap: Permission denied".

Discussed with Andrew short term plan ( To support OCC Bring-up )
  Default Behavior: No power capp enabled. and return error log for update action.
