### ISSUE TITLE
Remove or update /etc/version

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#1232]
I noticed we ship a file called `/etc/version` that contains a date string

```
root@zaius:~# cat /etc/version 
20170224224832
```

I've noticed users reporting this as the OpenBMC version. We really want them using the `VERSION_ID` string. Lets change the data in `/etc/version` to be the same string contained in `VERSION_ID`.

**Comment by sivassrr** [comment]
Is there a way to get the date of build as well, if we remove  /etc/version.

**Comment by shenki** [comment]
No, that would be gone.

What do we use the date for?

**Comment by williamspatrick** [comment]
The date the build was executed serves zero useful purpose. If I make a build now but base it on v1.99.1 the timestamp tells you nothing.
