### ISSUE TITLE
Built obmc-phosphor-image failed on VM with Fedora23 ppc64

### ISSUE THREAD

**Issue by zet809** [openbmc/openbmc#1235]
Hi, When I try to build openbmc project on a Fedora23 ppc64 VM, it failed after checking the free inodes of the /tmp directory as below. “WARNING: The free inode of /tmp (tmpfs) is running low (31.812K left) ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!”. Is there basic requirement for the performance of the disk?
 
$ bitbake obmc-phosphor-image
...
Build Configuration:
BB_VERSION        = "1.30.0"
BUILD_SYS         = "ppc64-linux"
NATIVELSBSTRING   = "Fedora-23"
TARGET_SYS        = "arm-openbmc-linux-gnueabi"
MACHINE           = "witherspoon"
DISTRO            = "openbmc-phosphor"
DISTRO_VERSION    = "0.1.0"
TUNE_FEATURES     = "arm armv6"
TARGET_FPU        = "soft"
meta
meta-poky
meta-oe
meta-networking
meta-perl
meta-python
meta-virtualization
meta-phosphor
meta-aspeed
meta-ast2500
meta-openpower
meta-ibm
meta-witherspoon  = "master:a981b106d6317580587597710aee220ce38cca54"

NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
**WARNING: The free inode of /tmp (tmpfs) is running low (31.812K left)
ERROR: No new tasks can be executed since the disk space monitor action is "STOPTASKS"!**
NOTE: Tasks Summary: Attempted 18 tasks of which 18 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

$ df -i
Filesystem               Inodes IUsed   IFree IUse% Mounted on
devtmpfs                  31849   361   31488    2% /dev
tmpfs                     32576     1   32575    1% /dev/shm
tmpfs                     32576   428   32148    2% /run
tmpfs                     32576    15   32561    1% /sys/fs/cgroup
/dev/mapper/system-root 1163264 96777 1066487    9% /
tmpfs                     32576     1   32575    1% /tmp
/dev/sda2                 65536   278   65258    1% /boot
tmpfs                     32576     4   32572    1% /run/user/0
tmpfs                     32576     4   32572    1% /run/user/1000

**Comment by williamspatrick** [comment]
By default, Yocto-Linux requires a minimum of 100K inodes at all times.  Any time the inodes drops below 100K the build is stopped.  See this line and the comment above it:

https://github.com/openbmc/openbmc/blob/master/import-layers/yocto-poky/meta-poky/conf/local.conf.sample#L195

(The build system and underlying Linux distribution used by openbmc is Yocto and this default value comes from them.)

I do not recommend it, but if you want to experiment with reducing the threshold on the inode limit you can edit `conf/local.conf` in your build directory after you run `. path/to/openbmc-env`.

Looking at a Witherspoon build that I have on my development system, the build directory is about 8.5G and 180k inodes.  I suspect you will not be able to fit this in /tmp.
