### ISSUE TITLE
Able to Configure invalid IP address on first octet

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#1248]
System is allowing to configure following IP address

First-Octet Rule:
First Octet can not be 0 and 127, but bmc is taking both.
We used rest interface to set this.

ifconfig
eth0      Link encap:Ethernet  HWaddr A0:42:3F:25:16:FE
          inet addr:0.6.6.23  Bcast:0.6.6.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:670803 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8806 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:37280797 (35.5 MiB)  TX bytes:593612 (579.6 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%984/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:23928 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23928 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:1818976 (1.7 MiB)  TX bytes:1818976 (1.7 MiB)

Version Info

ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.2-142"
VERSION_ID="v1.99.2-142-g2f30409-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.2-142"
BUILD_ID="v1.99.2"

**Comment by geissonator** [comment]
We're not going to do any validation of inputs to network programming.  Please stop opening issues in this area (this is like the 3rd one).
