### ISSUE TITLE
sbefifo in kernel api

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1258]
Add an in-kernel api for sbefifo.
Build on the base driver: https://github.com/openbmc/openbmc/issues/1257

Work with @apopple and @jk-ozlabs on a design
Work with @eddiejames as the first customer (p9-occ-hwmon).

**Comment by eddiejames** [comment]
- [ ] find a way to get an FSI/SBE device reference in the non-probed "client" driver. (Jeremy's new bindings?)
- [ ] write "sideways" calls for submitting a transfer to the SBE.
- [ ] test it.
