### ISSUE TITLE
Need 4.9 kernel commit for Zaius pmbus support

### ISSUE THREAD

**Issue by pahanson** [openbmc/openbmc#1260]
commit cc00decf0e280953e9067e938ad331f93bda8b40
aka https://patchwork.kernel.org/patch/9245427/

Tested with this patch: Zaius power brick can be probed as "dps800" at addess 0x61 on i2c-7

**Comment by williamspatrick** [comment]
@pahanson @shenki - Is this resolved?

**Comment by amboar** [comment]
I don't know if Zaius has moved to obmc/linux dev-4.10, but intuitively doing so should resolve it:

```
$ git branch -r --contains cc00decf0e280953e9067e938ad331f93bda8b40 | grep obmc/dev-4.10
  obmc/dev-4.10
```

**Comment by pahanson** [comment]
Obsolete with move to 4.10 and beyond
