### ISSUE TITLE
Generate bmc errors on host checkstop and host watchdog failures

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1266]
This story is on hold until we get host checkstop and watchdog refactored into sdbusplus so they will support the new error logging infrastructure.

**Comment by geissonator** [comment]
Per recent design meeting, can just create the new target and services for this function, no need to have the function refactored.

**Comment by vishwabmc** [comment]
I discussed this with @devenrao and here were my thoughts.

* Create the Error yaml files
* Create the tiny application that would consume the yaml and then log an error when called into
* Include this app as part of the new obmc-gpio-asserted@.target.wants

**Comment by devenrao** [comment]
- [ ] Create an error yaml and metadata file
- [ ] Create a service that consumes the error yaml file and log's an error when called into
- [ ] Link the service to obmc-gpio-asserted@.target.wants

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/3937 Add dependency for openpower-debug-collector
Resolves #1266 Generate bmc errors on host checkstop and host watchdog failures
