### ISSUE TITLE
Non FSI GPIO - ADALs - migration to openbmc kernel

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1268]

**Comment by williamspatrick** [comment]
@cbostic - Any idea what this is in reference to?  I don't understand the OpenFSI + "Non FSI" in the title.

**Comment by cbostic** [comment]
@rfrandse @williamspatrick  This isn't under the OpenFSI umbrella so the title should be updated.

There was some discussion several months back about using the existing ADAL layer for ASPEED direct connected GPIO's.   I don't know if this is still required or who needs this.  Only user of ADAL code right now is Cronus so assuming its for their use?

**Comment by geissonator** [comment]
Haven't heard anything on this one, reopen if someone still requesting this.
