### ISSUE TITLE
ImageManager: Initial creation and population of Software.Version properties

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1276]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

This story will create the __ImageManager__ application and the first interface which will be an internal one to populate the properties for xyz.openbmc_project.Software.Version.

**Comment by gtmills** [comment]
- [ ] Initial setup of file structure
- [ ] determine software id 
- [ ] set version properties
