### ISSUE TITLE
ItemUpdater: Create UBI volumes when RequestedActivation

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1278]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

When the Software.Activation ActivationRequested property is set, create a UBI volume for the requested image and point the 'active image' to it.

**Comment by anoo1** [comment]
- [ ] Create UBI volume when ActivationRequested property is set.
- [ ] Copy image to new UBI volume.
- [ ] Point active image to the new image.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/3755 Activation: Point active image to requested image
Closes: #1278 ItemUpdater: Create UBI volumes when RequestedActivation
