### ISSUE TITLE
palmetto build still tries to build qemu

### ISSUE THREAD

**Issue by jk-ozlabs** [openbmc/openbmc#128]
I've configured openbmc for the palmetto target:

```
$ TEMPLATECONF=meta-openbmc-machines/meta-openpower/meta-ibm/meta-palmetto/conf . oe-init-build-env
```

Resulting in:

```
$ grep -R ^MACHINE conf
conf/local.conf:MACHINE ??= "palmetto"
```

However, build is failing during qemu do_compile. While the actual build failure (of `qemu-native`) is a problem, can we just skip this step for non-qemu platforms?

**Comment by jk-ozlabs** [comment]
Also, qemu seems to be the package that is most sensitive to build-system differences, so this would prevent build problems on varied build systems...

**Comment by anoo1** [comment]
If you've built qemu before, you might need to delete the conf dir: rm -rf build/conf  ..  then try the export and bitbake commands once more.

**Comment by jk-ozlabs** [comment]
@anoo1: this is a fresh build

**Comment by williamspatrick** [comment]
Adding qemu for palmetto was being worked.  I think the real issue is that qemu-native should not fail to compile when the host machine does not have SDL.  It should detect this and degrade to an SDL-less compile.

**Comment by williamspatrick** [comment]
1. Need to ensure that qemu is not a dependency for all machine configurations.
2. Need to ensure that qemu-native compiles for qemuarm / qemux86 targets on something like Ubuntu Server Edition.
