### ISSUE TITLE
witherspoon:HIT - Remove 1.35V override for Vddr-A and Vddr-B

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1285]

**Comment by geissonator** [comment]
So to be clear, in https://github.com/openbmc/openbmc/blob/821d074359f9259bf8f1b6cf34fc81368f79611a/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/chassis/vrm-control/vrm-control%40.service  we should remove the vddra and vddrb parameters?

**Comment by geissonator** [comment]
Removing this will probably break DD1.0 modules but those are a small group that will just stay on older firmware once this goes in.  This is needed for the DD1.02 module testing.
