### ISSUE TITLE
Incorporate new soft power off function into host state

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1286]

**Comment by JoshDKing** [comment]
*   Move op-stop-host@.service under the obmc-chassis-stop@0.target
*   Make sure this service will hold off all other power off services until it’s done

**Comment by sivassrr** [comment]
@anoo1 @JoshDKing  Do FVT need to change any TCs related to Power off. Or it is internal change only?

**Comment by JoshDKing** [comment]
This change will just be updating the targets so the change is internal.

**Comment by geissonator** [comment]
Need to get this in first - https://gerrit.openbmc-project.xyz/#/c/4032/

Then just add the application to the shutdown target and update phosphor host state code to use the shutdown target but to monitor for the host-off target.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4224 Use shutdown target to stop the host
Resolves #1286 Incorporate new soft power off function into host state

**Comment by williamspatrick** [comment]
Code was reverted, reopening.
