### ISSUE TITLE
REST interface not getting network interfaces listed

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#1290]
We are not getting network interface info when we run curl command.

System Info
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.3-59"
VERSION_ID="v1.99.3-59-ga782550"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.3-59"
BUILD_ID="v1.99.3"

curl -c xxxx -b xxxx -k -H "Content-Type: application/json" -X GET -d '{"data": [eth0"] }'  https://x.x.x.x/org/openbmc/NetworkManager/Interface

{
  "data": [],
  "message": "200 OK",
  "status": "ok"

**Comment by gtmills** [comment]
This is an old build and the network is now under `/xyz/openbmc_project/network` so closing. Please reopen if still an issue. Thanks!
