### ISSUE TITLE
BMC staying in xyz.openbmc_project.State.BMC.BMCState.NotReady

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1291]
I flashed the recent build this morning:
```
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.3-67"
VERSION_ID="v1.99.3-67-gd11ed42"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.3-67"
BUILD_ID="v1.99.3"
```

I noticed the BMC state object was not getting to Ready state.  I poked around a bit and I believe it's this mapper call that's hanging us up.

  754 root       0:00 /usr/sbin/mapper wait /xyz/openbmc_project/led/groups/BmcBoot

Looks like https://github.com/openbmc/openbmc/commit/d11ed422f6cee0c4700d39a6885bdb988f4a887a may be the culprit.  Need to update the service file that's doing this mapper call.

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/#/c/2975/
