### ISSUE TITLE
Network Refactor:- Show all the IP addresses on the system

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1292]

**Comment by ratagupt** [comment]
- [ ] Implement the IPProtocol Interface.

- [ ] Get all the IP address from the system.

- [ ] Create the Dbus object for the ipadresess under ethernet interface object.

- [ ] Make necessary changes in makefile and configure.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/3828/
Resolves #1292 Network Refactor:- Show all the IP addresses on the system
