### ISSUE TITLE
Network Refactor:- Show all the network interfaces on the system.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1293]

**Comment by ratagupt** [comment]
- [ ] write the function to set the interface address.

- [ ] write the makefile and the configure script as it would be new c++ app.

- [ ] write the function to check the validity of the input parameters like (device,ipaddress,gatewayaddress).

**Comment by sivassrr** [comment]
@prkatti1  this is the story created  to address all IP validation. This is related to your issue what we had opened.

**Comment by ratagupt** [comment]
- [ ] Create the EthernetInterface.create interface.

- [ ] Create the Recpie and the unit file for new app.
