### ISSUE TITLE
NetworkRefactor:- Support for error handling and infra.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1294]

**Comment by williamspatrick** [comment]
I think this is technical debt from the existing implementation?

**Comment by geissonator** [comment]
@ratagupt to add some misc TODO's in here

**Comment by ratagupt** [comment]
@geissonator : we can close this one,This one was opened to add the error handling and phosphor logging.which is there in current code.

**Comment by dkodihal** [comment]
Closing since error logs are being reported.
