### ISSUE TITLE
Network Refactor:- Implement the system configuration object and  DHCP.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1295]

**Comment by ratagupt** [comment]
- [ ] Implement the system configuration object.
          Get/Set of the default gateway on the system.
          Get/Set of the hostname on the system.

- [ ] Enable the DHCP.
           Interface specific DHCP enablement
           Condition to check
           if DHCP is enabled then don't allow the static configuration.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4803> Refresh the interface objects if DHCP mode changes
Resolves  #1295 Network Refactor:- Implement the system configuration object and  DHCP.
