### ISSUE TITLE
log to journal when we retry UCD operations

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1298]
We're chasing a pgood issue ( #832).  One theory is that there's an underlying I2C or UCD issue and that when we hit the error, and do the retry operation, we end up programming invalid data to the UCD and the corresponding voltage rails.

https://gerrit.openbmc-project.xyz/#/c/2327/ was where we added the retries.  For this issue, we just want to add a echo to the journal when we hit the retry loop.

**Comment by geissonator** [comment]
Another question with ucd_disable_vcs.sh is what happens when the i2cset commands fail?  Does the whole script fail or do we just keep going?  Maybe we need some retries around those  as well?

**Comment by saqibkh** [comment]
when the i2cset fails we get the following error:

Error: Could not set address to 0x64: Device or resource busy

**Comment by geissonator** [comment]
ok cool, does it cause the whole script to fail?

**Comment by saqibkh** [comment]
yes
