### ISSUE TITLE
phosphor-fan-presence: Create and use internal exception class

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1300]
Create an exception class and use that within the entire package's set of applications.

- https://gerrit.openbmc-project.xyz/#/c/2622/8/fan_enclosure.cpp@83

**Comment by bradbishop** [comment]
- [ ] create the metadata YAML file with 'general logic error' error log
- [ ] run elog_gen.py on it and check it in
- [ ] throw runtimeerror with error exception
- [ ] catch and commit error exception instead of runtimerror

**Comment by bradbishop** [comment]
@spinler @msbarth I think the plan is now to let this error abort the application?  If it does not resolve itself after N restart attempts we allow the watchdog to trip?
