### ISSUE TITLE
Inventory Monitoring - Determine design and yaml input layout

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1303]
- [x] Propose the concept of an inventory monitoring app
- [x] Create inventory monitoring repository or place under inventory manager repo
- [x] Investigate inventory manager yaml input for similar use with this monitoring app
- [ ] Add support to PIM for groups
- [ ] Rework existing actions to operate on groups
- [ ] Construct an example yaml(fan based?)

**Comment by bradbishop** [comment]
moved a point from #1493

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4518> Add Witherspoon fan policy
Resolves:  #1303 Inventory Monitoring - Determine design and yaml input layout
