### ISSUE TITLE
Ensure uboot fw_env update script uses new inventory object.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#1315]
The inventory objects were changed from /org to /xyz namespace.  There is a script that updates the u-boot fw_env for the MAC address that needs to be updated to use the new inventory interfaces.

**Comment by chinaridinesh** [comment]
Changes pushed into repository via: https://gerrit.openbmc-project.xyz/#/c/3387/

**Comment by chinaridinesh** [comment]
Following changes pushed as part of this story:

https://gerrit.openbmc-project.xyz/#/c/3387/
https://gerrit.openbmc-project.xyz/#/c/4006/
https://gerrit.openbmc-project.xyz/#/c/4879/
https://gerrit.openbmc-project.xyz/#/c/4880/

**Comment by chinaridinesh** [comment]
Accessing the rick of updating chassis_control.py from old uuid object to new one, since chassis_control.py implements lot more than just uuid. This is part of implementing uuid with new inventory objects.

**Comment by chinaridinesh** [comment]
Working on testing the changes done for uuid and xyz name space.

**Comment by chinaridinesh** [comment]
Need some design inputs on UUID formats. Thats blocking now.

**Comment by mdmillerii** [comment]
systemd supports just hex digits or digits with hypens in "right" space.  Must be be (a uuid, not a half-le guid).

**Comment by chinaridinesh** [comment]
Pushed code for review.

**Comment by chinaridinesh** [comment]
Waiting on review comment from Deepak for https://gerrit.openbmc-project.xyz/#/c/5358/

**Comment by chinaridinesh** [comment]
Received review comments from @dkodihal . Implemented already as suggested. Not getting expected test result. Debugging

**Comment by chinaridinesh** [comment]
Test still not showing expected result. Need more time to debug.

**Comment by chinaridinesh** [comment]
Test of uuid via busctl tool works, but it shows empty due to no keyword defined for vpd parsing.

**Comment by chinaridinesh** [comment]
STATUS

7/25
Done with the changes. In final test with changed namespace from org.openbmc to xyz.openbmc_project .

**Comment by rfrandse** [comment]
Critical changes are in for phase 5 moving to phase 5.1

**Comment by chinaridinesh** [comment]
Closed.
