### ISSUE TITLE
Startup / Shutdown ordering on external interfaces.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#1316]
There was an issue raised recently because someone issued a BMC reset (indirectly through code update) and then immediately issued a REST operation.  The REST operation failed because mapper gave back a unique service name that was owned by a process being stopped.  (I suspect the service was stopped between the mapper call and the application call).

If any dbus process is stopped before the REST server, it is likely for a perfectly valid REST operation to give an error ("no such URL").  It seems that we should therefore shut the REST server down first.  This may extend to all external interfaces, like IPMI.

What is the mechanism in systemd to do that?  Would `After=multi-user.target` in rest-dbus.socket be sufficient?  

Looking for feedback from @bradbishop, but issue can be reassigned to someone else to complete the work.

**Comment by sivassrr** [comment]
Sorry, I didnt see your issue before I opened mine (#1317).
