### ISSUE TITLE
Fan Presence - Add gpio based presence detection

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1318]
Determine how pca9552 is accessed in user space and add an application within openbmc/phosphor-fan-presence that creates/updated inventory for fans defined to be gpio based presence detection.

**Comment by msbarth** [comment]
An additional bitbake argument is necessary to pass to the mrw parser to setup whether a fan should be tach or gpio based presence detection when creating the yaml file.
https://gerrit.openbmc-project.xyz/#/c/3122/1/gen_presence_yaml.pl@43

**Comment by bradbishop** [comment]
[ ] - build skeleton - create stubbed application with gpio and inventory parameters
[ ] - add template systemd unit
[ ] - add application package to existing phosphor-fans recipe
[ ] - add package to inventory packagegroup
[ ] - write error yaml and run elog-gen.py ( general logic failures, libevdev failures )
