### ISSUE TITLE
Fan Presence - Add gpio with fallback to tach feedback presence detection

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1319]
Add an application within openbmc/phosphor-fan-presence that creates/updated inventory for fans defined to be gpio w/ tach fallback based presence detection. This app will use the gpio presence of a fan as the primary presence detection method, but where the gpio shows a fan is not present, the tach feedback will then be checked where a valid tach speed (!= 0) marks the fan as present and logs an error noting the gpio is broken.

**Comment by williamspatrick** [comment]
@msbarth - Do we need this for Witherspoon or is it a nice to have?
