### ISSUE TITLE
power supply presence detection

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1329]
The Witherspoon power supplies have GPIOs for presence detects wired to the BMC.   We need to monitor those and add the PSs to the inventory when they are present.  If they are hot removed, we'd need to mark them as not present.

In addition the power supplies have serial numbers that should listed in the inventory, but we'd need device driver support to get them.  

#1782 for serial numbers, scope of this story is presence only.

**Comment by williamspatrick** [comment]
I'm estimating as 2 for both the presence and serial numbers, but that would include driver enhancements.

**Comment by bradbishop** [comment]
Moved a point to serial number story #1782.

**Comment by gtmills** [comment]
- [ ] Create phosphor-gpio-presence app in phosphor-gpio-monitor
- [ ] Have phosphor-gpio-presence determine presence and update inventory based on gpio presence line (passed in)
- [ ] Watches for gpio state changes and update inventory 
- [ ] Start 2 instances of phosphor-gpio-presence service, one for each power supply for Witherspoon

**Comment by gtmills** [comment]
Need https://github.com/openbmc/openbmc/issues/1783

**Comment by gtmills** [comment]
07/13 - Working on Recipe

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5190> Add GPIO Presence
Resolves  #1329 power supply presence detection
