### ISSUE TITLE
ImageManager: Implement interface to download image via TFTP

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1331]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

The ImageManager would provide and interface at /xyz/openbmc_project/software to allow additional images to be downloaded to the BMC via TFTP (DownloadViaTFTP())

**Comment by gtmills** [comment]
- [ ] Determine requirements
- [ ] Initial setup of file structure

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/#/c/3376/
