### ISSUE TITLE
Code update: implment image upload via REST

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1332]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

The ImageManager would provide and interface at /xyz/openbmc_project/software to allow additional images to be added to the BMC, such as Object.Add() for REST.

**Comment by dkodihal** [comment]
Tasks related to adding a potential code update image to the BMC. This will purely be a rest server change - 

- [ ] Accept content other than JSON.
- [ ] Implement UploadHandler : enable ability to upload a file via a PUT verb combined with a cURL --upload_file option.
- [ ] Implement UploadHandler : enable ability to upload a file via a `multipart/form-data` encoded POST or PUT request body (amounts to a cURL -F)
