### ISSUE TITLE
PNOR: Enable patching for lab/mfg

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1333]
Ability to copy a PNOR partition to a specific location in the BMC, and this partition will be loaded so that it'd take effect, allowing for developers and mfg to patch the PNOR image.

**Comment by anoo1** [comment]
- [ ] Create a tmpfs under /usr/local/ to be used at the 'patch' directory.

**Comment by geissonator** [comment]
Adriana to close, move over to mboxd story.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5257> openpower-software-manager: Create ubi volume for pnor patches
Resolves  #1333 PNOR: Enable patching for lab/mfg
