### ISSUE TITLE
DNS not configured on boot

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#134]
In our lab, we have DHCP configured. At boot my palmetto BMC gets an ip address, but does not come up with `/etc/resolv.conf` populated.

Running `udhcpc` manually does fix this, but it should be done at boot time.

**Comment by nkskjames** [comment]
Need to enable DNS setup via REST and IPMI or DHCP default

**Comment by vishwabmc** [comment]
I am working on making the .service file changes and testing it out on Palmetto box
