### ISSUE TITLE
Sensor groups

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1343]
Develop a general purpose application that does runtime monitoring of build time defined groups of sensors for a condition.  Asserts an action when the condition evaluates.

- [ ]  Define YAML format
- [ ]  Write application build skeleton (hwmon repository?)
- [ ]  Write parser with mako and generate runtime code / data model.
- [ ]  Implement 'if any in group > hardcoded number' condition.
- [ ]  Implement 'create error log' action.

**Comment by bradbishop** [comment]
@spinler @msbarth

**Comment by msbarth** [comment]
- [ ] Define YAML with group of sensors, sensor details, filters/triggers(algorithm), and actions
- [ ] Write application build skeleton (hwmon repository?)
- [ ] Write parser with mako and generate runtime code / data model.

Incremental testing will take into account the following specifics regarding thermal condition & action:
- Implement 'if any in group > hardcoded number' condition.
- Implement 'create error log' action.

**Comment by geissonator** [comment]
Brad/Matt to break down a bit more, need to be 3 or less points of work

**Comment by geissonator** [comment]
Reducing from 3->2 points.  Matt will create new story (1pt) to track the parser work.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/4116/
