### ISSUE TITLE
Block State Transitions during Image Activation

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1344]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

Under the `Blocking State Transitions` title.

**Comment by anoo1** [comment]
- [ ] Create a Software.ActivationBlocksTransition object when the Activation property is set to Activate.
- [ ] Remove the Software.ActivationBlocksTransition object when the Activation goes from Activating to Active.
- [ ] Block the host power on transition if ActivationBlocksTransition exists.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/3589 Block host power on when ActivationBlocksTransition exists
Closes: #1344 Block State Transitions during Image Activation
