### ISSUE TITLE
Handle application restarts where fan speeds should be set to max.

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1347]
When an application used in refreshing fan speed values (input or output) restarts, updating of the previous values need to be handled upon the application restarting. Ex.) In the case where a watchdog places the fans to max speed due to an application reset, the cached values in hwmon need to be updated for the related monitoring and control applications to use the latest fan speeds in their algorithms.

**Comment by rfrandse** [comment]
dup to #1342
