### ISSUE TITLE
OCC: force hwmon attribute numbering to conform to dts sensor definitions

### ISSUE THREAD

**Issue by eddiejames** [openbmc/openbmc#1348]
Currently there is no guarantee that hwmon attributes (e.g. temp1_input) are mapped to the same OCC sensor every boot. Need to create some dts entries to define a mapping between OCC sensor number and hwmon attributes, and modify the OCC driver to pick up those entries.

**Comment by eddiejames** [comment]
Please assign to me.

**Comment by geissonator** [comment]
Dup of #1043 ?

**Comment by eddiejames** [comment]
- [ ] read entries from device tree under the OCC bus device (i2c or sbe) in the driver
- [ ] hwmon entry number to sensor id when reading a sensor
- [ ] test it.

**Comment by eddiejames** [comment]
Yes I think this is a duplicate of 1043.

**Comment by geissonator** [comment]
Covered under #1330
