### ISSUE TITLE
REST server: Add ability to merge two copies of a single dbus object into a single REST object

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1349]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

For software updates, there will be two processes (download manager and activation manager) creating a dbus object with the same name (ex: "xyz/openbmc_project/software/123") but with different interfaces. Need the REST server to 'merge' them into a single REST object.

**Comment by geissonator** [comment]
Lots of discussion on this one in task review, seems like this mostly works(?).  Need to test it out and come back to team with observations to figure out what we need to change.  Could be 1 point of doing this validation and minor changes, could be 2 points if we find issues and need to make bigger changes.

**Comment by dkodihal** [comment]
- [ ] Write test app (python mostly) which can create d-bus objects. App takes as input object name and interface(s) to implement.
- [ ] Run two instances of above app which creates the same d-bus object implementing the same interfaces and verify behavior.
- [ ] Run two instances of above app which creates the same d-bus object implementing different interfaces and verify behavior.
- [ ] Fix issues found in rest server.

**Comment by dkodihal** [comment]
1. In case of the same d-bus object implementing the same interfaces across two services, the rest server reported the object and properties as expected (no dups).
2. In case of the same d-bus object implementing different interfaces across two services, the rest server reported the object and properties as expected, the properties were 'merged' from the two interfaces.

So I think there's nothing to fix here.
