### ISSUE TITLE
pflash: Add option to retrieve PNOR partition flags

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1351]
Follow-up for https://github.com/openbmc/openbmc/issues/1047 .

This story will track adding the enhancement to the pflash tool to provide an option to read the PNOR image partition flags.

**Comment by mtritz** [comment]
- [ ] add a function to pflash to read partition flags
- [ ] modify generate-squashfs to use the pflash tool in order to get partition flags

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/4120/
Resolves #1351 pflash: Add option to retrieve PNOR partition flags

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4120> Update generate-squashfs to use new pflash option
Resolves  #1351 pflash: Add option to retrieve PNOR partition flags

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4120> Update generate-squashfs to use new pflash option
Resolves  #1351 pflash: Add option to retrieve PNOR partition flags
