### ISSUE TITLE
ImageManager: Interface to save an image to the BMC and create a corresponding dbus object

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1352]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software

Create a function that the the download by TFTP and REST can call to save an image to the BMC flash. This function will save the image to flash, generate a unique ID (existing function), and create a software/<ID> dbus object. Then populate it by calling the already implemented Software.Version interface and a Common.FilePath interface.

**Comment by gtmills** [comment]
- [ ] Save image to BMC flash
- [ ] Make call to generate Software ID and create dbus object. 
- [ ] Populate Software.Version interface
- [ ] Populate Common.FilePath interface

**Comment by rfrandse** [comment]
added points from #1353

**Comment by rfrandse** [comment]
https://github.com/openbmc/openbmc/issues/1352

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/3967/
