### ISSUE TITLE
ImageManager: Implement Common.FilePath interface

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1353]
Reference: https://github.com/openbmc/openbmc/issues/1352

Implement the Common.FilePath interface so that it can be used by the Software dbus object.

**Comment by gtmills** [comment]
Common.FilePath interface is here https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Common/FilePath.interface.yaml

**Comment by gtmills** [comment]
- [ ] Implement the Common.FilePath interface

**Comment by gtmills** [comment]
Going to be handled in #1352
