### ISSUE TITLE
Fix GNU_HASH warnings in pflash

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#1361]
While creating a build using yocto2.2 we found the following error:
Error: pflash-5.4.0-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary

As a work around we have added LDFLAGS to TARGET_CC_ARCH in the pflash.bb file to fix the warning.
To resolve the issue, upstream code needs to fix their build. (github link: https://github.com/open-power/skiboot)

Once completed please remove the "TODO" from openbmc/openbmc/meta-openbmc-machines/meta-openpower/common/recipes-bsp/skiboot/pflash.bb

https://github.com/open-power/skiboot/issues/69

**Comment by williamspatrick** [comment]
Please open issue in open-power/skiboot for @stewart-ibm and reference that here.

**Comment by stewart-ibm** [comment]
We welcome patches
