### ISSUE TITLE
Request OCC reset when fail detected

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1363]
Per the OCC interface specification (we'll need to see what's applicable to open bmc with this story)

3.4.2	BMC-OCC Communication Failure
A communication failure is defined as one of the following:
•	Response Checksum failure
•	Sequence number mismatch after command timeout has been reached.
•	OCC Return Status still “In Progress” after command timeout has been reached.  See “Command Summary Table” section for recommended timeout by command.
•	Any non-successful Return Code
•	I2C Failure sending command or reading response

When any of the above communication failures occur the BMC should first verify that the “OCC Active” sensor is TRUE.  If the OCCs are not active the error should be ignored and communication with the OCC should not be retired until the “OCC Active” sensor is TRUE.  If the “OCC Active” sensor is TRUE the command should be retried twice.  If the command still fails after two retries and the “OCC Active” sensor is still “TRUE” and there is no checkstop the error is valid and a request to reset the OCCs should be sent.

3.2.1	BMC Detected Reasons for OCC Reset
The BMC must send a request to reset the OCCs when it detects one of the following and the “OCC Active” sensor is TRUE with no checkstop present:
➢	Communication failure to an OCC defined in BMC-OCC Communication Failure section.
➢	Number of bits set in “OCCs Present” from master poll response does not match the number of OCCs the BMC is communicating with.
➢	Current OCC State byte in poll response is “Safe” for one minute and the “OCC Active” sensor is TRUE.

**Comment by geissonator** [comment]
Probably should break into at least 2 stories
- Add support to ipmid host interfaces to request the OCC reset
-- https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Control/Host.interface.yaml
- Request reset when above conditions occur

**Comment by geissonator** [comment]
Need to involve fan control team in this design, here's a comment from @spinler :
```
my concern is that if fan control runs into hwmon errors enough then it will die and the watchdog will permanently kick in.  However, if fan control can tell the OCC is unhappy, then it can gracefully just set fans to full speed until the OCC is reset and everything comes back to life again
```

**Comment by geissonator** [comment]
Per the design meeting, we have 3 parts to this function (each getting 1 pt)
- #1802 
- #1698
- #1363 (this one)

**Comment by geissonator** [comment]
From the interface, here's the occ reset flow:
```
Any request for an OCC reset will be resetting the whole power management complex in the system.  When BMC determines that it needs to request a reset the following must be done:

1.  BMC generates an error log with the reason for reset to aid in debug.
2.  BMC updates “OCC Active” sensor to FALSE for all OCCs
3.  BMC sends SMS Attention for OCC reset to OPAL with sensor ID of failing OCC
4.  OPAL reads IPMI command buffer and translates sensor ID to a chip ID and calls HBRT Process OCC Error interface with the chip ID
5.  HBRT calls HTMGT OCC error handling function with the chip ID
6.  HTMGT runs OCC Reset Procedure.
```

**Comment by geissonator** [comment]
Some things to note with this story
- The occ reset goes through the SMS host ipmi path, but since this is openpower function, it will need a new interface into that function
- We need to pass the the sensor ID of the failing OCC up to the host, which means we'll need to enhance the host interface to take a parameter

**Comment by geissonator** [comment]
Needs some implementation discussion tomorrow

**Comment by geissonator** [comment]
Discussed technical details in interlock today, Vishwa ok with committing.

**Comment by vishwabmc** [comment]
OCC error detection code has been up for review since some days.
Interface yaml for open_power host interface is up for review for few days.
Queue Manager is now implemented and I plugged the old host command interface to use this new Manager and its working fine so far

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5475> Reset OCC on error condition
Fixes  #1363 Request OCC reset when fail detected

**Comment by dkodihal** [comment]
This commit chain is yet to be merged - https://gerrit.openbmc-project.xyz/#/c/5331/.

**Comment by vishwabmc** [comment]
@dkodihal This can now be closed since all the commits have been merged
