### ISSUE TITLE
Test procedure for OpenBMC GUI

### ISSUE THREAD

**Issue by iftekharuli** [openbmc/openbmc#1366]
We have hosted our app in Bluemix for now so that you guys can go ahead and test for this sprint. We are based the app for the server x.x.xxx.xxx for now. Which is palm303. Before testing, you can make sure if the server is up and running. Otherwise you can PDU it. 

We have made the login and power operations available for you to test. You can test our GUI in your browser. Here are the steps- 

1. Open the following link https://x.x.xxx.xxx/  in your browser and accept network security.  You will see a message like 
 {
     "data": {
   	 "description": "Login required"
      }, 
  "message": "401 Unauthorized", 
  "status": "error"
}

This way we bypass the default browser security that blocks our app to create connection to the server. 

2. https://openbmc-test.mybluemix.net/#/login is where the app is hosted right now. You can login with the server credential - root/0penBmc

If you get server unreachable error, make sure the server is pinging and you have completed the previous method mentioned here. 

3. You can click on Server power operations and try out different power operations. Please note that. right now warm reboot and cold reboot do the same thing- reboots host. Also Orderly Shutdown and Immediate shutdown do the same thing- shuts down host. 

The API is being worked on for Warm reboot and Orderly shutdown. We have created an issue on this here- https://github.com/openbmc/openbmc/issues/1310 

Note: to test out if the buttons are really working,  I used George Keishing’s tool here in GSA   /gsa/ausgsa/projects/i/indiateam04/gkeishin/public/REST_CMD/tools/obmc/

Once I make any power operations, I come back to this tool and check the state if it is really effected the host. 

Feel free to reach out to me on slack or via email if anything 
iislam@us.ibm.com

**Comment by rfrandse** [comment]
Issue moved to [openbmc/openbmc-test-automation #470](https://github.com/openbmc/openbmc-test-automation/issues/470) via [**ZenHub**](https://www.zenhub.com/)
