### ISSUE TITLE
Verify mac addresses are set correctly

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#137]
We currently rely on the uboot environment variable to store the mac address. Both uboot and Linux should use this information; verify that this is the case and ensure we can detect when it fails.

**Comment by jk-ozlabs** [comment]
.. also, this means that a system implementer will need to set per-machine u-boot variables during manufacturing. We'll need to ensure that this is acceptable, or find somewhere else (another EEPROM?) to store the MAC address.

**Comment by nkskjames** [comment]
The plan was for the manufactuer to use the IPMI set LAN from host to set MAC address.  This should set both MACs.  Once we have the fw flash tools in Linux, we can use to set uboot variables.

**Comment by agangidi** [comment]
I verified today on my 24 servers that the mac address you set via uboot is persistent in both uboot and linux. However as Norm said, setting it via linux / host OS is a better idea for future purposes.

**Comment by nkskjames** [comment]
Marking as an enhancement to store MAC in EEPROM and copy into uboot environment.

**Comment by anoo1** [comment]
Available in:
Master - https://github.com/openbmc/skeleton/commit/fb4d22587fdc46d64c253a1ab1b40b228a8c0887
Stable - https://github.com/openbmc/skeleton/commit/6019000c3cc52d33d85906c93ffd1b8614b65c59
