### ISSUE TITLE
Define DBus Interfaces for OpenBMC Dump

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1377]
Investigate OpenBMC Dump Requirements and define DBus Interfaces.

**Comment by ojayanth** [comment]
- [ ] Investigate Dump Requirements.

- [ ] Discussion with Stakeholders

- [ ] Prepare Design 

- [ ] Create DBus Interfaces

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/3513/
