### ISSUE TITLE
Define Tooling infrastructre for Dump Parsing

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1378]
Investigate industry Standard Dump Handling methods.

**Comment by ojayanth** [comment]
- [ ] Explore Open Source Dump Handling tools.

- [ ] Proposal for OpenBMC Dump Parser

**Comment by geissonator** [comment]
Jayanth to write up what he found with OS tools and why we decided to not use.

**Comment by ojayanth** [comment]
OpenBMCCommunity mail link 
https://lists.ozlabs.org/pipermail/openbmc/2017-April/007398.html

**Comment by ojayanth** [comment]
Community Link related BMC Dump High level design
https://lists.ozlabs.org/pipermail/openbmc/2017-May/007654.html
