### ISSUE TITLE
Create fan zone definition YAML

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1380]
The fan control code has a concept of zones, where certain fans have the same properties.  We'll need to define YAML to map fan inventory objects into zones/groups, along with the sensor objects to set the speeds on those fans.

Then we need a second YAML to define:
 - how many fans can be missing from a zone before all fans in the zone go to speed X
 - how many fans can be non functional from a zone before all fans in the zone go to speed Y

A future story may have a zone manager that makes all zones do something based on another zone

We also need to take into account the fact that the zone for a water cooled witherspoon has a fewer number of fans than an air cooled one.  Water cooled doesn't need the second fan present.  So, we will have a different zone definition based on some condition.

The MRW will specify which zone a fan is in, as well as a way to specify air vs water vs both

- [ ] Write fan zone YAML that defines the zones and speed setting rules, based on a condition (air vs water property set)
- [ ] Write MRW script to read the config YAML and output a new YAML with the actual fan inventory paths and sensor names including along with the zone information
- [ ] Make a recipe to install these from the witherspoon tree into the fakeroot for use by a later story.

**Comment by rfrandse** [comment]
Merged
