### ISSUE TITLE
Switching to DHCP mode causes broken networkd config file

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1386]

**Comment by williamspatrick** [comment]
Running `busctl call org.openbmc.NetworkManager /org/openbmc/NetworkManager/Interface org.openbmc.NetworkManager EnableDHCP s eth0` results in:

```
root@witherspoon:/etc/systemd/network# cat /etc/systemd/network/00-bmc-eth0.network
ork /etc/systemd/network/00-bmc-eth0.netw
[Match]
Name=eth0
[Network]
DHCP=yes[DHCP]
ClientIdentifier=mac
```

Somehow the new line between `DHCP=yes` and `[DHCP]` was garbled.
