### ISSUE TITLE
Enable /dev/input in openbmc Kernel

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/openbmc#1387]
Story openbmc/openbmc#766 needs to access /dev/input/event for GPIO device and hence it needs to be enabled.

**Comment by vishwabmc** [comment]
@bradbishop

**Comment by bjwyman** [comment]
I think this should be closed now. The GPIO monitor and the setting of Air vs Water cooling type (openbmc/openbmc#370) both depended on this being in the kernel.

**Comment by bjwyman** [comment]
This commit?
https://github.com/openbmc/openbmc/commit/683ea6d09860fcfabed1030389fb577795b0fdfa

**Comment by rfrandse** [comment]
Brandon indicates this is resolved with commit:
https://gerrit.openbmc-project.xyz/#/c/3600/
