### ISSUE TITLE
master fails to build on Ubuntu 16.10

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#1392]
My build machine runs Ubuntu 16.10. The compiler it ships with is:
```
$ gcc --version
gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
```
Current master fails to build glib and pkgconfig (amoung others).

**Comment by amboar** [comment]
Duplicates #963

**Comment by williamspatrick** [comment]
Duplicate
