### ISSUE TITLE
Factory reset through dbus IPMI not working

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#1394]
Trying to do factory reset using following dbus command, it is not resetting the system.
Run Dbus IPMI Raw Command  0x32 0xBA 00 00
Run Dbus IPMI Raw Command  0x32 0x66

**Comment by williamspatrick** [comment]
Is this an openpower ipmi command or something in ipmi 2.0?  If this is openpower specific we do not plan to support.

**Comment by prkatti1** [comment]
@williamspatrick Thanks for the confirmation, could you Pls provide the command which works for openbmc. I tried this also
Run Dbus IPMI Raw Command  0x3c 0x40

**Comment by williamspatrick** [comment]
I don't know what these ipmi commands are. We do not currently have any support for a factory reset. That will come after the code update work being done by @anoo.

**Comment by williamspatrick** [comment]
These netfun are in the IPMI OEM range. There does not appear to be anything in IPMI 2.0 for factory reset, so we have no plans to support over IPMI. There will be a REST API when function is complete.
