### ISSUE TITLE
Switch back to synchronous FSI clocks after unbinding the FSI driver

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1397]
We have a service fsi-disable.service that can be started to unbind the FSI driver so that people can use external cronus (from an FSP).  Before the unbind, it should also switch the FSI clocks back to synchronous mode, away from asynchronous mode which OpenFSI uses.

I'll have to make a new procedure in openpower-proc-control to clear bit 31 in CFAM register 0x840, and then call it in the service.

**Comment by rfrandse** [comment]
No points needed.

**Comment by spinler** [comment]
Resolved with https://gerrit.openbmc-project.xyz/#/c/3562/
