### ISSUE TITLE
witherspoon: power button LED should blink at standby

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1399]

**Comment by williamspatrick** [comment]
I believe this requires a new feature in the LED group manager to allow, in some cases, 'on' to take precedence over 'blink'.

**Comment by vishwabmc** [comment]
I am hoping this could all be managed by putting appropriate groups into certain systemd targets instead of putting a system specific thing onto the code ?

**Comment by vishwabmc** [comment]
This is my current thought.
```
* Have BmcStandby group that is specific for Witherspoon and assert that group ( update bbappend ) on way to bmc_ready 

* When the Power is applied, same LED gets to Solid-On as part of `PowerOn` group

* As part of power-off, `PowerOn` group gets de-asserted and hence it results in LEDs to behave as part of `BmcStandby`
```

**Comment by williamspatrick** [comment]
@vishwabmc - As discussed earlier today, the big gap I see here is that this blink vs on is opposite our current policy.  (Blink always takes priority).  Need to understand how you are going to solve that.  Otherwise, what you described is effectively what is already implemented.

**Comment by vishwabmc** [comment]
Oh.. Please help close this one. I had put the `Fixes` on a open-power pull request that I ended up cancelling and hence this is open.

@williamspatrick Please ?.
