### ISSUE TITLE
ItemUpdater: Implement Software.ExtendedVersion

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1401]
Reference:
https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Software/ExtendedVersion.interface.yaml

**Comment by saqibkh** [comment]
- [ ]  Read the pnor.toc for extended version
- [ ]  Create an extended version interface on the Software.Activation object
- [ ]  Populate the Activation interface with the extended version from pnor.toc
