### ISSUE TITLE
Collect FFDC on Hostboot and SBE errors

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1405]
With #1266 we will create new targets and a service for these error paths.  Initially they will just create an error with basic failure information.  

This story is to track gathering additional debug data on these fails that would aid in debug (like CFAM registers and other hardware debug information).

Be nice to have in 2.1 but not required, can move to 3.0.

**Comment by dkodihal** [comment]
This would just be a new type of dump - #1511.
