### ISSUE TITLE
Re-enable UCD hwmon driver

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#1415]
The UCD hwmon driver was disabled in the device tree in order to work around the PGOOD failure in #832. 

Once the root cause is fixed, we should re-enable it.

**Comment by bjwyman** [comment]
Was this re-enabled/fixed?
I have see hwmon processes running for the UCD device on Witherspoon systems.

**Comment by shenki** [comment]
This has been enabled for a number of months now
