### ISSUE TITLE
Update journal entry in host state code to indicate we may have hit reboot count

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1424]
https://github.com/openbmc/phosphor-state-manager/blob/master/host_state_manager.cpp#L267

This journal entry is a bit mis-leading now that we've incorporated the reboot count into isAutoReboot().

In fact, it confused me this morning :)

We should probably just make it more generic to indicate auto reboot is disabled OR we've hit our reboot count.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/3499/
