### ISSUE TITLE
witherspoon - current divisor not needed in vrm-control.sh

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1427]

**Comment by paulgrobertson** [comment]
current divisor not needed in vrm-control.sh  per Jordan K.  modify 1 line needed.

root@r4:~# diff /tmp/vrm-control.sh /usr/bin/vrm-control.sh    
--- /tmp/vrm-control.sh
+++ /usr/bin/vrm-control.sh
@@ -42,7 +42,7 @@
   let e=(e^0x1F)+1
   e="-$e"
 fi
-printf "    %0.3fA\n" `echo $m $e $2 | awk '{print ($1 * 2^$2) / $3}'`
+printf "    %0.3fA\n" `echo $m $e $2 | awk '{print ($1 * 2^$2)}'`
 }

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4029 witherspoon - current divisor not needed in vrm-control.sh
Resolves #1427 witherspoon - current divisor not needed in vrm-control.sh
