### ISSUE TITLE
Implement the OCC pass-though

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1428]
The pass-through command should be sent to the SBE FIFO via an appropriate chip-op, and the response read back by another chip-op.

**Comment by vishwabmc** [comment]
- [ ] Understand the SBE spec for OCC commands
- [ ] Understand the protocol and data structure needed to be pumped into FIFO
- [ ] Understand current OCC code that implements passthrough
- [ ] Code the changes
- [ ] Test the changes
