### ISSUE TITLE
Add rngd from rng-tools.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#1430]
@kc8apf is working on a driver for the aspeed H-RNG.  In order to make this useful we need rng-tools installed.

Tasks:
- [ ] Create systemd service for rngd.
- [ ] Improve rng-tools_5.bb so that rngd can be installed separate from rngtest.
- [ ] Add PACKAGECONFIG to compile --without-gcrypt.
- [ ] Submit the above 3 changes upstream to Yocto / OE.

Depends on @shenki taking driver from @kc8apf and likely adding device tree entries for the H-RNG.

**Comment by bjwyman** [comment]
Is this related to openbmc/openbmc#1367 ?

**Comment by williamspatrick** [comment]
This was already implemented.
