### ISSUE TITLE
mboxd: Populate windows from pnor partition files

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1440]
Populate the memory windows from the squashfs files, each file is a pnor partition. This story is the ability to copy the pnor partitions to the virtual pnor (memory), a separate story will add the change to call this new function when there's a request from hostboot.
When copying files to memory, use mmap.

**Comment by amboar** [comment]
> When copying files to memory, use mmap.

Can you expand on this? We can mmap the physical memory needed by the LPC bus into the process, and we can mmap the file from the PNOR, but we still need to copy between the two. We can't redirect LPC FW cycle accesses directly to the file on flash if that's what you were hoping for.

**Comment by williamspatrick** [comment]
@amboar - Yeah the recommendation for mmap was so that we can do memcpy between the reserved memory region and the files.  Not that we were magically going to be able to mmap files into the reserved region.

Now that I think of it, this might be a good use of the 'splice' system call instead of 'mmap'.  We can probably splice the file into the reserved region and let the kernel do all the copying operation.

The reason for mmap vs read is just to let the VMM/VFS cache do their thing rather than having even more blobs of memory sitting around in the mailbox process.

**Comment by amboar** [comment]
> @amboar - Yeah the recommendation for mmap was so that we can do memcpy between the reserved memory region and the files. Not that we were magically going to be able to mmap files into the reserved region.

Right, thanks for clarifying.

> Now that I think of it, this might be a good use of the 'splice' system call instead of 'mmap'. We can probably splice the file into the reserved region and let the kernel do all the copying operation.

We would need to hook up support in the aspeed-lpc-ctrl driver. Currently it doesn't populate the `splice_read()` or `splice_write()` callbacks, and neither does `drivers/mtd/mtdchar.c` (I think that's the right place?). There are generic implementations of the callbacks that will probably work, but this needs more investigation. We also still have the issue of doing this in "small" chunks so as not to stall all other processes. But I agree in general, I think it's feasible to reimplement `copy_flash()` and `write_flash()` in terms of `splice()`. It would also require some tinkering with the test cases to implement the libc wrapper for `splice()`.

> The reason for mmap vs read is just to let the VMM/VFS cache do their thing rather than having even more blobs of memory sitting around in the mailbox process.

Yep.

**Comment by williamspatrick** [comment]
Memcpy via mmap solves the small chunk problem, right?  Maybe we just stick with that over splice for now. 

Why do we have this performance issue?  Do we not have full preemption enabled?

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/4087/

**Comment by mdmillerii** [comment]
I started this reply some time ago:

> Why do we have this performance issue? Do we not have full preemption enabled?

The mtd layer is implemented via synchronous calls, except for erase.  The driver has a yield in the wait loop but fundamentally will only issue one thread at a time.  This also prevents the SPI layer from interrupting a write to perform a read (erase is also not interruptible in the current code) even though the flash chips support it.  The mtd layer actually has better support for directly addressed windows than asynchronous transfers (eg the offload engine).

**Comment by amboar** [comment]
Sorry, had been meaning to leave a reply along the lines of @mdmillerii's, but never got around to it.
