### ISSUE TITLE
Create fan control app and set initial fan speeds

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1445]
- [ ] Create mako YAML parser for existing fan zone YAML to generate C++ structures
- [ ] Create new fan control app to load in structures with fan zone information
- [ ] set initial fan speed (value from YAML) on the zones loaded in

follow ons:
* zones will depend on conditions, like water vs air cooled dbus properties (not ready at this time)
* setting fan speeds to high speed when fans are missing or not operational

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/3772 Install phosphor-fan-control app and service
Resolves #1445 Create fan control app and set initial fan speeds
