### ISSUE TITLE
[Enhancement] wget to access https site

### ISSUE THREAD

**Issue by swe12345** [openbmc/openbmc#1447]
Referring to openbmc/openbmc-test-automation#467

@mdmillerii  - Based on this link http://askubuntu.com/questions/338869/error-while-downloading-https-files-using-wget adding --secure-protocol option might help https to work

```
root@palmetto:~# wget --secure-protocol=protocol https://openpower.xyz
wget: unrecognized option '--secure-protocol=protocol'
BusyBox v1.24.1 (2017-04-05 12:03:34 CDT) multi-call binary.

Usage: wget [-c|--continue] [-s|--spider] [-q|--quiet] [-O|--output-document FILE]
        [--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
        [-U|--user-agent AGENT] [-T SEC] URL...
```

**Comment by williamspatrick** [comment]
Busybox wget does not have that option and the "real" wget is much bigger. What is it you are trying to accomplish?

**Comment by sivassrr** [comment]
@williamspatrick we would like to get the BMC / PNOR image directly from https://openpower.xyz/ and onto BMC

**Comment by rfrandse** [comment]
Contact Deepak, he is implementing rest interface to upload image to bmc.

**Comment by sivassrr** [comment]
@rfrandse, @dkodihal is using rest interface to upload the image to BMC. This enhancement is to get image using wget from external world.

**Comment by dkodihal** [comment]
Why does the external world have to login to the BMC and use wget, when REST is their interface?

**Comment by rfrandse** [comment]
Use rest api

**Comment by williamspatrick** [comment]
We have no plans to use anything other than busybox wget and will not be enhancing busybox wget to support a "real" wget parameter like this.  Please find some other mechanism to get images onto the BMC in your environment.
