### ISSUE TITLE
Fan speeds return 65535(-1) as tach feedback during poweroff

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1456]
HWMON reports a tach sensor value of 65535(-1) during poweroff which will eventually cause problems for the fan control & monitoring applications. This was seen on a system with the MAX31785 fan control chip.

ex.)
/xyz/openbmc_project/sensors/fan_tach/fan0:65535
/xyz/openbmc_project/sensors/fan_tach/fan1:65535
/xyz/openbmc_project/sensors/fan_tach/fan2:0
/xyz/openbmc_project/sensors/fan_tach/fan3:0

/xyz/openbmc_project/sensors/fan_tach/fan0:65535
/xyz/openbmc_project/sensors/fan_tach/fan1:65535
/xyz/openbmc_project/sensors/fan_tach/fan2:65535
/xyz/openbmc_project/sensors/fan_tach/fan3:0

/xyz/openbmc_project/sensors/fan_tach/fan0:65535
/xyz/openbmc_project/sensors/fan_tach/fan1:65535
/xyz/openbmc_project/sensors/fan_tach/fan2:65535
/xyz/openbmc_project/sensors/fan_tach/fan3:65535

/xyz/openbmc_project/sensors/fan_tach/fan0:65535
/xyz/openbmc_project/sensors/fan_tach/fan1:0
/xyz/openbmc_project/sensors/fan_tach/fan2:65535
/xyz/openbmc_project/sensors/fan_tach/fan3:65535

**Comment by msbarth** [comment]
This has not been seen since an updated MAX31785 driver was introduced in the 4.10 kernel.

**Comment by amboar** [comment]
Right, I was going to say, this is a driver bug, not something userspace should be handling. Good to hear that it hasn't been seen with the new driver.
