### ISSUE TITLE
Network Refactor:Write the in memory objects into the network file

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1462]
Objects are ethernet Interfaces and the ipaddresses.

**Comment by ratagupt** [comment]
I can see the two task here.

1) Write the validator function for ipaddress , macaddress,prefix.
2) Write the in memory objects into the network file.

**Comment by ratagupt** [comment]
3) Add the unit test cases here.
4) Add the error logging here.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4386 test: Add test cases for network manager
Resolves #1462 Network Refactor:Write the in memory objects into the network file
