### ISSUE TITLE
Sensor for host TPM requirement policy

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1463]
Need to implement a sensor that will store a systems host TPM policy (whether it's required or not for boot).  Ideally the new sensor design is in place before implementing ( #778 ).  The hostboot team is looking for this ASAP though.

**Comment by sivassrr** [comment]
@geissonator Hope we will get an option in openbmc gui as well, right.

**Comment by mabaiocchi** [comment]
@geissonator who is assigned this work item so that I can keep him/her in-sync with the system owners adding this support?

**Comment by geissonator** [comment]
@mabaiocchi - No assignee yet, the team decided we really needed to get the sensor refactor stories ( #778 epic) done prior to adding any new sensor functions.

Specifically we've got @dhruvibm looking into a sub-epic, #798 this sprint.

**Comment by geissonator** [comment]
Per design meeting, this will come under the new settings design from @dkodihal #1465

**Comment by geissonator** [comment]
Create the new dbus property like so - https://gerrit.openbmc-project.xyz/#/c/5033/
Then add in like so - https://gerrit.openbmc-project.xyz/#/c/4875/

**Comment by devenrao** [comment]
- [ ] Create YAML interface file for TPM policy 
1. /xyz/openbmc_project/Control/Tpm/TpmPolicy.interface.yaml

- [ ] Specify the default value for the TPM policy at  meta-phosphor/common/recipes-phosphor/settings/phosphor-settings-defaults/defaults.yaml

**Comment by devenrao** [comment]
Figured out the changes to be done. Plan to start coding. 14/07/2017

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5378> Add in default for TPM enable/disable
Resolves  #1463 Sensor for host TPM requirement policy

**Comment by mabaiocchi** [comment]
Hostboot is still looking for this support (3+ months now). Please let me know as soon as we can get this support on a Witherspoon BMC that we can use to test this functionality.  Thank you - Mike
