### ISSUE TITLE
discover-system-state: Accept a node parameter

### ISSUE THREAD

**Issue by mtritz** [openbmc/openbmc#1466]
Currently, https://github.com/openbmc/phosphor-state-manager/blob/master/discover_system_state.cpp assumes the use of node 0. It should be re-written to handle templates, so that the system states of other nodes can be discovered.

**Comment by mtritz** [comment]
- [ ] Modify the service file so it's a template rather than hardcoded for node 0
- [ ] Modify discover_system_state.cpp so it accepts the node ID as a parameter and returns the system state accordingly

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6424> discover_system_state: Accept a node parameter
Resolves  #1466 discover-system-state: Accept a node parameter
