### ISSUE TITLE
code-update : refactor

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1468]
Mainly address the comments here -

https://gerrit.openbmc-project.xyz/#/c/3647/2/version_image_manager.hpp@21

Talk to Gunnar because he may to get to some of this in the 04.05 sprint.

**Comment by williamspatrick** [comment]
This sounds like a code review issue.  I don't think we should be opening a story to refactor brand new code.

**Comment by anoo1** [comment]
Let's also address as part of this story that the openpower-version-host-software-manager core dumps if there's not a pnor image on the bmc.

**Comment by dkodihal** [comment]
I don't have a better place to put this right away, but the image update location (/tmp/images or any other), should be created via a service I think. Right now I am doing that in the rest server, but it should be done via a service.

**Comment by dkodihal** [comment]
Looks like Gunanr has most of this covered via review rework. Will keep this open but will un-assign Ratan.

**Comment by dkodihal** [comment]
Closing this because the comments were addressed by Gunnar.
