### ISSUE TITLE
Ethtool support in openbmc.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1484]
ethtool is used to query and control network device driver and hardware settings.
It is useful to get the link statistics of a link.
eg:- speed,autoneg,Duplex.
Even in the dump which is ongoing activity we can take a network dump from ethtool.

**Comment by gwshan** [comment]
I also found same issue - ethtool is missed in openBMC build. Yes, It's
very useful to know the PHY layer's statistic and working mode. It's worthy
to be included when we have attached PHY. For NCSI, I'm pushing another set
the patches to dump statistics from debugfs and it can be ported to openBMC
branches when it reaches upstream.

2017-04-20 18:54 GMT+10:00 ratagupt <notifications@github.com>:
