### ISSUE TITLE
phosphor-settingsd : move to new d-bus interfaces

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1486]
Write phosphor d-bus interfaces for settings, in YAML.

**Comment by dkodihal** [comment]
- [ ] Write YAML files to indicate various settings. Prefer grouping by setting, such as xyz/openbmc_project/BMC/Time, xyz/openbmc_project/Host/BootDevice.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4205 Add d-bus interfaces for Settings.
Resolves #1486 phosphor-settingsd : move to new d-bus interfaces

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6424> discover_system_state: Accept a node parameter
Resolves  #1486 phosphor-settingsd : move to new d-bus interfaces
