### ISSUE TITLE
phosphor-settingsd : implement d-bus interfaces

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1487]
Implement settings d-bus interfaces.

**Comment by dkodihal** [comment]
- [ ] Implement all settings d-bus interfaces.
- [ ] create app that puts settings objects onto the d-bus.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/4244/
Resolves openbmc/openbmc#1487.
