### ISSUE TITLE
Test and integrate 4.10 kernel into openbmc

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1492]
This is all the work to get the 4.10 kernel merged into openbmc.  Need to make sure all systems still boot (work with automated test team to run regression tests) and all lab/cronus tools still work as expected plus any miscellaneous tasks needed to get it through (patch updates and such).

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/4175/
Resolves #1492
