### ISSUE TITLE
Sensor monitoring parser

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1493]
Write parser with mako and generate runtime code / data model of events from YAML to input into the sensor monitoring app

- [x] Parse groups from YAML and create associated list of group info
- [ ] Parse start event structure from YAML and add to event mako data struct
- [ ] Parse signal event structure from YAML and add to event mako data struct
- [x] Parse actions from YAML for a supported action function call on an event
- [ ] Update recipe(s) to install sensor monitor application

**Comment by bradbishop** [comment]
just going to track this with #1303.  moving points there.
