### ISSUE TITLE
Create d-bus interfaces for non-sensor sensors

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1499]
Create d-bus interfaces for non-sensor sensors under the xyz/openbmc_project namespace.

**Comment by dhruvibm** [comment]
- [ ] Create Yaml files for non-sensor sensors to move to xyz namespace

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/#/c/4216/
https://gerrit.openbmc-project.xyz/#/c/4216/
