### ISSUE TITLE
[Witherspoon] Power supply derating value can be changed to any value

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#1502]
Power supply derating value is suppose to be unchangeable. And it should be a constant value for 10. But we are able to change the value using REST. 

Step to recreate
1. Check the Power supply derating value using below. It is correctly set to 10 which is it contant value.
```
bash-4.1$ curl -c cjar -b cjar -khttps://xx.xx.xx.xx/org/openbmc/sensors/host/PowerSupplyDerating                                                          {
  "data": {
    "error": 0,
    "units": "",
    "value": "10"
  },
  "message": "200 OK",
  "status": "ok"
}
```

2. Now changed the value to 50 using REST
```
bash-4.1$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\": \"50\"}" -X PUT  https://xx.xx.xx.xx/org/openbmc/sensors/host/PowerSuplyDerating/attr/value
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}
```

3. Here we will see that power supply derating value is getting changed to 50. 
```
bash-4.1$ curl -c cjar -b cjar -khttps://xx.xx.xx.xx/org/openbmc/sensors/host/PowerSupplyDerating                                                          {
  "data": {
    "error": 0,
    "units": "",
    "value": "50"
  },
  "message": "200 OK",
  "status": "ok"
}bash-4.1$
```

FFDC : 
[Journal_Power_supply_20170425061246211272_BMC_journalctl.txt](https://github.com/openbmc/openbmc/files/954839/Journal_Power_supply_20170425061246211272_BMC_journalctl.txt)

BMC Fw : 
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.4-55"
VERSION_ID="v1.99.4-55-g432188b"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.4-55"
BUILD_ID="v1.99.4"
root@witherspoon:~# cat /etc/timestamp
20170425032433
```

**Comment by williamspatrick** [comment]
I'm not interested in solving this defect with the current code.  Anything in the /org/openbmc namespace will be going away.  This item shouldn't even be classified as a "sensor".

@dhruvibm is already working on a larger story to refactor the old /org/openbmc/sensors code into something more manageable.  With this he will ensure that elements that are suppose to be read-only are not update-able.
