### ISSUE TITLE
BMC Dump: Create inotify daemon

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1504]
Create inotify daemon to notify about coredump file additions.
One known use is the notifying the Dump Manager for new coredump

**Comment by ojayanth** [comment]
- [ ] Add inotify watch on a specified location to know about new core file generated.

- [ ] invoke internal d-bus "create"  interface to create Dump.

- [ ] Add function to handle coredumps , which are created prior to this daemon starts.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4342> Initial commit for the Dump core file monitor infrastructure.
Resolves  #1504 BMC Dump: Create inotify daemon
