### ISSUE TITLE
Dump Packaging script

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1507]
Create Dump packaging script which includes the following activities.
       — Packaging dump content.
       — File Compression, and saving into FFDC partition.

**Comment by ojayanth** [comment]
- [ ] Move the Dump contents from temporary location  to permanent location.

- [ ] Packaging dump using gzip.

- [ ] Add recipe to install  bash file in /usr/bin

**Comment by dkodihal** [comment]
I thought @williamspatrick had a suggestion to use xz?

**Comment by geissonator** [comment]
Patrick says use xz

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5543> dreport: Add packaging support
Resolves:  #1507 Dump Packaging script
