### ISSUE TITLE
REST-API: Add File read command.

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1508]
Develop REST API for File read .This can be used for reading  Dump File from BMC remotely.

**Comment by ojayanth** [comment]
Assumption : where user will give the Path of the Dump.

- [ ] Implement the route handler for  the read request.

- [ ] Copy the Dump file .

**Comment by dkodihal** [comment]
- [ ] Define a rest route for downloading a dump. The route would look like "download/dump/<dump_id>".

- [ ] Map the dump id to the dump file. This can be done for example if the dump file is placed under foo/dumps/<dump_id>/<dump_file>.

- [ ] Serve the dump file using the Bottle's static_file method. This, given a file path, prepares an HTTP response with details such as size, mime type and transfers the file.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5023> rest_dbus: allow route 'download/dump/<dumpid>;
Resolves  #1508 REST-API: Add File read command.
