### ISSUE TITLE
BMC Dump: Add support for Application Core

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1509]
— Identify the dump contents and  add support required Bash commands specific to application core
  - Enable this support in Dump Service

**Comment by dkodihal** [comment]
I think this should be covered with #1506 .

**Comment by ojayanth** [comment]
#1506 only only covers generic bash script based infrastructure work.  This is to enable Application core based dump enablement.

**Comment by ojayanth** [comment]
- [ ]   Define Core Dump Pattern

- [ ]    Add support to Initialize the core pattern during boot.

- [ ]    Identify the dump contents and add support required Bash commands specific to application core.

- [ ] Create dump entry incase for unprocessed core during last boot.
