### ISSUE TITLE
BMC Dump: Add infrasture support for User initiated Dump

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1510]
- Add required Bash script for user use initiated dump.
  - Enable this support in Dump Service

**Comment by dkodihal** [comment]
This story will cover enabling a user initiated dump via appropriate interface - internally just call the FFDC script for now, which can be later changed to suit whatever dump content is needed. Reducing to 1 point.

**Comment by ojayanth** [comment]
- [ ] Add yaml support for create() and reporDump() interfaces.

- [ ] Implementation of create() and reporDump() d-bus interfaces

- [ ] Add infrastructure code support  to enable  manager class  for initiating existing FFDC bash script for user-inited dump use case

- [ ] Add infrastructure  code support  to enable  create class .

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4787> Add support for user initated BMC Dump
Resolves  #1510 BMC Dump: Add infrasture support for User initiated Dump
