### ISSUE TITLE
SEL: Generate mapping between Inventory and Sensor Number

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#1514]

**Comment by tomjoseph83** [comment]
- [ ] Add script to generate the inventory object and the corresponding sensor number, sensor type
- [ ]  Write Mako template code too process the generated YAML.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4122 Add virtual/phosphor-ipmi-inventory-sel
Resolves #1514 SEL: Generate mapping between Inventory and Sensor Number
