### ISSUE TITLE
SEL: Implement the mandatory SEL commands

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#1515]

**Comment by tomjoseph83** [comment]
- [ ] Get SEL Info
- [ ] Get SEL Entry
- [ ] Delete SEL Entry
- [ ] Clear SEL

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5048> Add Clear SEL command
Resolves  #1515 SEL: Implement the mandatory SEL commands
