### ISSUE TITLE
SEL: Write infrastructure code to convert a Error Log Entry to SEL

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#1516]

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4270 Convert error log to SEL record
Resolves #1516 SEL: Write infrastructure code to convert a Error Log Entry to SEL

**Comment by tomjoseph83** [comment]
- [ ] Mapping Error log into SEL Entry record

**Comment by geissonator** [comment]
Do this one first, then #1515
