### ISSUE TITLE
Create BMC Item Updater and implement BMC image manager

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1532]
As part of the new code update design implementation, there's now a common image manager for BMC and PNOR.
Need to split the current BMC version manager implementation into the common image manager and a new item updater.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4073 Create activation interface on BMC version dbus creation
Resolves #1532 Create BMC Item Updater and implement BMC image manager

**Comment by agangidi53** [comment]
Hi @anoo1 Is the new process of updating BMC / Host flash documented in the docs repository ? I still seem to be looking at the old process in docs .

**Comment by anoo1** [comment]
> Is the new process of updating BMC / Host flash documented in the docs repository ?

Hi @agangidi53 , Just uploade the first round of updates to gerrit: https://gerrit.openbmc-project.xyz/#/c/4756/

**Comment by agangidi53** [comment]
Thanks @anoo1  I will test this!
