### ISSUE TITLE
Create error log for failures to determine cooling type

### ISSUE THREAD

**Issue by bjwyman** [openbmc/openbmc#1542]
When the phosphor-cooling-type application encounters an problem with determining the cooling type (such as a GPIO read failure), or updating the inventory properties (AirCooled and/or WaterCooled), it should create an error log for such failures.

**Comment by bjwyman** [comment]
# Task List
- [ ] Update phosphor-cooling-type app to create error entry on ReadFailed.

**Comment by bjwyman** [comment]
# **STATUS**
**09/28**
- Tomorrow: Start looking into working on this.
- Blockers: None.

**Comment by bjwyman** [comment]
I am not sure which issue this was apparently a duplicate of, but I believe this was fixed up under https://github.com/openbmc/phosphor-fan-presence/commit/618027abcf491b0b58f71bfe2b48c55dfb86462e#diff-abf909e2802d61aa26666950017a137c.

**Comment by spinler** [comment]
Closing
