### ISSUE TITLE
board names in uri path

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#1543]
/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc

What is 'boxelder'?  Is it a code name for an IO card?  Is the OpenBMC architecture requesting that  just for the IO card its name be used?  I don't see the name of each type of 'motherboard' or 'zaius/witherspoon' for the 'system'.   I get that the URI could really be anything seeing how the properties should be describing what it is but everything else is generic hardware names like DIMM, Fan, Motherboard, BMC, etc  

--- Steps to recreate ---
Version: v1.99.4-82-g874f12e
Powered on the hardware.  Issued this command... 
curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET   https://x.x.x.x/xyz/openbmc_project/enumerate

**Comment by gkeishin** [comment]
As per previous discussion with folks on `boxelder`, looks like it depends on whether the BMC eeprom has VPD programmed or not and not all boxes have it today, and none of them have the MAC address programmed..
