### ISSUE TITLE
Inventory URIs missing

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#1544]
Missing URIs
I found... "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc":
but walking up the parents I noticed there is no... 
"/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder":
"/xyz/openbmc_project/inventory/system/chassis/motherboard/":
"/xyz/openbmc_project/inventory/system/chassis/":

This seems wrong.  Each node is suppose to have properties to indicate what the thing is

--- Steps to recreate ---
Version: v1.99.4-82-g874f12e
Powered on the hardware.  Issue this command... 
curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET   https://x.x.x.x/xyz/openbmc_project/enumerate

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4932> server: fix unexpected GetSubTreePaths behavior
Resolves:  #1544 Inventory URIs missing
