### ISSUE TITLE
Implement Software Object.Delete for pnor updater and image manager

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1550]
Add Object.Delete to the Software dbus objects to be able to remove images.
This would be added to the Version dbus object for the image manager and the item updaters.
A Delete action on the image manager would delete the image from /tmp and its corresponding image in the item updater if the Action property is not set to Active.
A Delete action on the item updater would remove the partition.

The currently active version in the item updater would hide the Delete action to prevent the user from deleting it.

**Comment by gtmills** [comment]
- [ ] Remove activation object
- [ ] Remove verision and file name objects
- [ ] Delete the image from /tmp

**Comment by lgon** [comment]
Status Update
July 13, 2017
--------------------
Changed Version into a template class to avoid component dependency per Adriana's code review comment, and pushed change out to Gerrit.  Today, will test new openpower-update-manager binary on Witherspoon system and test Object.Delete.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5363> item_updater: Implement erase method
Resolves  #1550 Implement Software Object.Delete for pnor updater and image manager

**Comment by lgon** [comment]
GitHub Comment
++++++++++++++++++++++++++++++++++++++
TASK LIST

- [ ]     Remove activation object
- [ ]     Remove verision and file name objects
- [ ]     Delete the image from /tmp


#**STATUS**

July 19, 2017
Made changes according to code review, and fixed issue with unit test that was causing Jenking build to fail. 
Waiting for reviewers to review latest changes. https://gerrit.openbmc-project.xyz/#/c/5242/
No Blockers

++++++++++++++++++++++++++++++++++++++
