### ISSUE TITLE
mboxd: Use tmp location for pnor patches

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1551]
If a pnor partition file is located in a pre-defined tmp location for patches, use that file to populate the window. This allows for users to be able to patch pnor partitions.

**Comment by anoo1** [comment]
- [ ] The mboxd already looks at specific locations in order (first read-write or preserved, then read-only) for the partition files, add the patch dir to the beginning of the list.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5432> vpnor: Add patch location
Resolves  #1551 mboxd: Use tmp location for pnor patches
