### ISSUE TITLE
PNOR: Implement Software RedundancyPriority.interface

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1553]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Software/RedundancyPriority.interface.yaml

During activation, set the Priority of the requested version to 0.
When the Priority property is changed, and if there are other activated versions, increment their priority, so that the previous version with priority 0 now it's set to 1 etc.

**Comment by saqibkh** [comment]
- [ ]  Add Redundancy Priority interface to Activation class
- [ ]  Set Redundancy to 0 once the activation is successful.
- [ ]  Increment priority of other activated versions by 1.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4675> PNOR: implement Software RedundancyPriority interface.
Resolves  #1553 PNOR: Implement Software RedundancyPriority.interface
