### ISSUE TITLE
PNOR: Implement Software ActivationProgress.interface

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1554]
Reference: https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Software/ActivationProgress.interface.yaml

Once #1716 is implemented, time how long the service units take, the longest would be the one that loads the squashfs image.
Start an sdevent timer to wake every x amount of time, and update the progress.
Create a match for when the update is complete (service file exits), then delete the match afterwards.
Future enhancement: figure out a way to get progress out of ubiupdatevol, maybe there's some indication in /proc.

**Comment by mtritz** [comment]
- [ ] implement redundancy priority interface - appears during activation and disappears afterwards
- [ ] implement activation progress interface
- [ ] implement Set method - how should this work?
    - [ ] call Set in between steps of activation?
    - [ ] separate process in the background that fills in the values? like a timer?

**Comment by mtritz** [comment]
This has prerequisite https://github.com/openbmc/openbmc/issues/1716

**Comment by mtritz** [comment]
Reworking this - instead of a timer, will arbitrarily set and get an integer property so as to better reflect both the duration and state of the activation process.

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/#/c/5018/
