### ISSUE TITLE
The fan Timer class should throw elogs

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1555]
Right now it throws runtime_errors, but it should do the whole elog thing specified by yaml inside the phosphor-fan repository.

**Comment by bradbishop** [comment]
- [ ] define elog yaml (general logic failure)
- [ ] run elog-gen.py on yaml to generate error header
- [ ] replace runtime error with exception class in generated header

**Comment by chinaridinesh** [comment]
Implemented the story in https://gerrit.openbmc-project.xyz/#/c/4984/ . This can be closed.

**Comment by geissonator** [comment]
Per above comment
