### ISSUE TITLE
Non-sensor refactor : MRW parser and yaml design

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1558]
Come up with a YAML based structure and MRW parser to map a software sensor (typically pulled from the MRW), to which d-bus object will consume it.

**Comment by dhruvibm** [comment]
- [ ] Create structure for YAML

- [ ] Create an MRW Parser for software sensors to create an application specific yaml

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5234> Non-sensor sensor support in host ipmid
Resolves  #1558 Non-sensor refactor : MRW parser and yaml design

**Comment by dhruvibm** [comment]
In merge review

**Comment by dhruvibm** [comment]
# **STATUS**
07/24 - Doing a reword on 1558 and 1608
