### ISSUE TITLE
IPMI FRU commands : MRW parser

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1559]
Write new (or tweak existing IPMI inventory parser) MRW parser to help map IPMI FRU sensor record to a d-bus object path and d-bus properties. Output of the parser should be in YAML format.

**Comment by devenrao** [comment]
- [ ]  Modify MRW parse script to generate YAML containing information about the
   IPMI Fru sensor record

- [ ] Map IPMI Fru sensor record to a d-bus object path and d-bus properties

**Comment by devenrao** [comment]
- [ ]  Modify MRW parse script to generate YAML containing information about the
   IPMI Fru sensor record

- [ ] Map IPMI Fru sensor record to a d-bus object path and d-bus properties

**Comment by devenrao** [comment]
- [ ] Consume the YAML file which has the IPMI mapping from FRU sensor record to dbus-object path and dbus-properties and generate C++ code.

- C++ code generated will aid in responding to IPMI FRU related commands.

**Comment by geissonator** [comment]
Need task for recipe updates

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4472> cater for generting fru inventory yaml file
Resolves  #1559 IPMI FRU commands : MRW parser

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4657> Add native recipe to generate inventory map from MRW
Resolves  #1559 IPMI FRU commands : MRW parser
