### ISSUE TITLE
[System] System is unable to recover from Quiesced state after first host off request.

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#1571]
Witherspoon system is unable to recover from Quiesce state after first host off request. This issue is an inconsistent one.

Step to reproduce
1. Get system is quiesced state. 
2. Now send REST request to power off the host to recover from Quiesced state. Here you will see that system will not able to recover from Quiesced state.  Waited for almost 15 mins.

```
curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\": \"xyz.openbmc_project.State.Host.Transition.Off\"}" -X PUT  https://xx.xx.xx.xx/xyz/openbmc_project/state/host0/attr/RequestedHostTransition
```
3. Send REST Request to power off host again. Here we will see that host will go into off state now.

FFDC Logs:
[20170508050119030013_VerifyHostQuiesceStateWithoutAutoReboot.zip](https://github.com/openbmc/openbmc/files/983189/20170508050119030013_VerifyHostQuiesceStateWithoutAutoReboot.zip)

BMC Fw : 
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.5-15"
VERSION_ID="v1.99.5-15-gc4c2bed"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.5-15"
BUILD_ID="v1.99.5"
root@witherspoon:~# cat /etc/timestamp
20170508022654
root@witherspoon:~#
```

**Comment by gkeishin** [comment]
Couple of things we need to ensure for this @rahulmah 
 
- [x]  Which PNOR are you using . PNOR level please ?
- [x]  Did you mean we can't poweroff once quisece ? what was the auto boot policy at that time..

**Comment by rahulmah** [comment]
Closing this issue as we dint observe the problem later on.
