### ISSUE TITLE
Define factory reset dbus interface

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1573]
This will be a generic "factory reset" dbus interface that will be implemented by different areas of software in bmc.

**Comment by mtritz** [comment]
- [ ] Define the generic factory reset dbus interface in phosphor-dbus-interfaces/xyz/openbmc_project/Common

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4141 Dbus interface for "factory reset"
Resolves #1573 Define factory reset dbus interface
