### ISSUE TITLE
Implement network factory reset

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1575]
Implement factory reset dbus interface in network object.  The interface should reset all network interfaces to defaults (i.e. dhcp)

**Comment by mtritz** [comment]
- [ ] Figure out where to put the new object
- [ ] Create a skeleton to implement the dbus interface

- [ ] TODO: Identify what exactly a "network factory reset" encompasses and how to do it. (Design meeting)

- [ ] Add to skeleton - when dbus interface is called, reset network interfaces

**Comment by ratagupt** [comment]
we just  need to delete the /etc/systemd/network/*.network file.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4321 Implement network factory reset in network_manager
Resolves #1575 Implement network factory reset
