### ISSUE TITLE
Unable to read any sensor value using IPMI [Witherspoon]

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#1580]
Unable to read any sensor value using IPMI. This issue is open as https://github.com/openbmc/openbmc/issues/1530  does not addresed this part of problem.

Read Turbo allowed value
```
bash-4.1$ ipmitool -I lanplus -C 3 -P 0penBmc -H xx.xx.xx.xx raw 0x04 0x2d 0xda
Unable to send RAW command (channel=0x0 netfn=0x4 lun=0x0 cmd=0x2d rsp=0xcb): Requested sensor, data, or record not found
```

Read Power cap value
```
bash-4.1$ ipmitool -I lanplus -C 3 -P 0penBmc -H xx.xx.xx.xx raw 0x04 0x2d 0xc2
Unable to send RAW command (channel=0x0 netfn=0x4 lun=0x0 cmd=0x2d rsp=0xcb): Requested sensor, data, or record not found
```

FFDC : 
[Journal log for sensor read fail.txt](https://github.com/openbmc/openbmc/files/986461/Journal.log.for.sensor.read.fail.txt)

BMC fw : 
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.5-19"
VERSION_ID="v1.99.5-19-g02406c9"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.5-19"
BUILD_ID="v1.99.5"
```

**Comment by williamspatrick** [comment]
@tomjoseph83 - I do not believe this is supported yet, but is planned to be done in the future.  Please reference the existing feature issue.
