### ISSUE TITLE
Network:- Support for interface specific gateway.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1590]
When the network manager comes up and gets the ipaddress from the kernel then it needs to show the gateway for that network.

**Comment by ratagupt** [comment]
- [ ] Read the kernel Routing table through netlink sockets.

- [ ] Parse the routes.

- [ ] Get the route detail from the above parsed routes once network manager comes up to get the network routes.

- [ ] Write the test cases for the routes that it fetches all the routes.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4446 Implement the ipaddress origin and gateway property
Resolves #1590 Network:- Support for interface specific gateway.
