### ISSUE TITLE
OpenFSI performance improvements

### ISSUE THREAD

**Issue by cbostic** [openbmc/openbmc#1599]
Task list

- [x] Probe up a test system and capture waveforms for clock and data during FSI operations
- [ ] Review clock and data for any unexpected noise and slow rise/fall times
- [ ] Identify any marginal timing between clock and data that could potentially lead to protocol errors.
- [ ] Resolve any marginal timing issues and remove as much of the inserted delay as possible running hostboot FSI access tests.

Due to occasional FSI protocol stability issues when running hostboot, larger delays were added between clock and data transitions.  Total delay now per FSI clock cycle is 6 microseconds.   Need to understand root cause of this issue and remove as much delay as possible to improve performance.

I've been talking to David Green in Card I/O about probing up these I/O lines to see what may be up.
Tuesday he was able to provide some scope dumps for an FSI transaction.  Nothing unusual was seen from a rise/fall time perspective and no noise was noted.   The timing between when data changes state and when the clock transitions from 0 to 1 is fairly long though and could potentially result in issues when data direction changes to slave -> master mode.

![witherspoon fsi pv_fsp2_p_cp0_fsp0_fsi_dat cp0 levels bmc driving](https://cloud.githubusercontent.com/assets/18150797/25958462/3c978510-3636-11e7-9b43-57aac3c5f61b.gif)

**Comment by cbostic** [comment]
![witherspoon fsi pv_fsp2_p_cp0_fsp0_fsi_dat cp0 waveform1 bmc driving](https://cloud.githubusercontent.com/assets/18150797/26005134/c51aba66-36fd-11e7-8c15-366b1f6813ad.gif)
![witherspoon last measurement](https://cloud.githubusercontent.com/assets/18150797/26005135/c53b66b2-36fd-11e7-88d9-3a00106a0a99.gif)

**Comment by cbostic** [comment]
Accidentally closed this out.  Needs to remain open.

**Comment by cbostic** [comment]
I've received a large csv formatted data dump of the waveforms which can be shared.  Too large to attach here.

**Comment by cbostic** [comment]
Marking as 'Phase 7'

**Comment by amboar** [comment]
> Due to occasional FSI protocol stability issues when running hostboot
This is the limit of the justification for the artificial delays. I'd like to see a greater exposition of the issue(s) to argue against why we can't just remove them.
