### ISSUE TITLE
Non-sensor refactor : implementation

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1608]
Based on the output of #1558, implement placing non-sensor sensors into appropriate d-bus objects.

**Comment by dhruvibm** [comment]
[] linking sensor to dBus interface/property

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4861> Implementation of Operating System status and boot progress
Resolves  #1608 Non-sensor refactor : implementation

**Comment by dhruvibm** [comment]
Review rework and testing

**Comment by dhruvibm** [comment]
# **STATUS**
07/24 - Doing a reword on 1558 and 1608

**Comment by dkodihal** [comment]
Need changes to get this working for non-MRW systems.

**Comment by dkodihal** [comment]
Dhruv fixed the build issue with non-MRW systems here - https://gerrit.openbmc-project.xyz/#/c/5819/.
