### ISSUE TITLE
Non-sensor refactor : remove legacy code

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1609]
Switch existing code to new software sensor d-bus interfaces.

**Comment by geissonator** [comment]
Dhruv, can you confirm this is a dup of your other work in this area?

**Comment by dhruvibm** [comment]
All changes for non-sensors will be implemented with 1608, but is there any cleanup needed for old interfaces?

**Comment by geissonator** [comment]
I'll retitle this to removing the old code and taking out of beta/phase 5.

**Comment by bradbishop** [comment]
https://gerrit.openbmc-project.xyz/#/c/6782/1/sensorhandler.cpp:

```Tom Joseph
Sep 20 9:28 AM
Please add a note in #1609, in an earlier review i had commented that #2154 is last legacy sensor and the case statement can be removed after that.```

@tomjoseph83 @dhruvibm ^

**Comment by anoo1** [comment]
Removing the legacy functions with https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-host-ipmid/+/12759/

**Comment by geissonator** [comment]
Looks done to me
