### ISSUE TITLE
Remove legacy fan control apps/services/targets from Witherspoon

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1610]
I see this running:
```/usr/sbin/fan_control.exe -f 6```

and the following in /lib/systemd/system/:
* `fan-default-speed@.service`
* `obmc-fans-ready.target`
* `obmc-fan-control.target`
* `obmc-max-fans.service`

None of these will be used with the new fan control code, and will confuse things if people look at them.

**Comment by gtmills** [comment]
- [ ] remove fan_control.exe
- [ ] remove services
- [ ] remove targets

**Comment by geissonator** [comment]
Only do on system(s) with new fan control.

**Comment by gtmills** [comment]
fan-default-speed@.service was removed here https://github.com/openbmc/openbmc/commit/baf766c5f5ab67d1b3f1b58887b70bbc904612a7
