### ISSUE TITLE
OCC HWMON refactoring

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1611]
The OCC HWMON driver needs fairly decent amount of rework based on the SBEFIFO/OCCFIFO drivers.  This story tracks hwmon attributes only - for non hwmon OCC attributes see #1619.

**Comment by eddiejames** [comment]
- [ ] write in-kernel api for occfifo
- [ ] write code to send cmd and get response in the hwmon driver
- [ ] test it end-to-end

**Comment by rfrandse** [comment]
Code done. 
Track upstreaming with https://github.com/openbmc/openbmc/issues/1694
