### ISSUE TITLE
Add IR35221 instances to Witherspoon device tree

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1612]
Need Witherspoon device tree update for this pmbus device.

Driver work tracked here: #1177

**Comment by cbostic** [comment]
- [ ] Review device driver and understand all device tree requirements, bus type etc...
- [ ] Obtain card schematics including details for IR35221.
- [ ] Identify i2c bus and address details for Witherspoon
- [ ] Code and integrate changes to dts file.
- [ ] Load kernel on test system and verify device is identified and probed

**Comment by bradbishop** [comment]
This is dup - tracking with #1177.
