### ISSUE TITLE
Remove org.openbmc.control.Flash and pflash once the new code update interfaces are implemented

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1614]
Remove the bios and bmc old code update interfaces.

For PNOR:
meta-phosphor/common/recipes-phosphor/flash/obmc-flash-bios.bb
meta-phosphor/common/recipes-phosphor/flash/obmc-flash-bios/obmc-flash-init.service
meta-phosphor/common/recipes-phosphor/flash/obmc-flash-bios/org.openbmc.control.Flash.service

**Comment by anoo1** [comment]
Also remove the org.openbmc.managers.Download .

**Comment by gtmills** [comment]
org.openbmc.managers.Download is removed here https://gerrit.openbmc-project.xyz/#/c/6420/

**Comment by anoo1** [comment]
We should also make any changes needed to support the current code update implementations with the new xyz download method before removing.
