### ISSUE TITLE
Create systemd service file to remove ubi partitions

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1615]
The systemd service file would remove the requested ubi partition and corresponding files and directories.
This would be used by the Software Object.Delete implementation and the Factory Reset method.

**Comment by anoo1** [comment]
- [ ] Create new service file that does the opposite of the ubimount service: unmount the requested ubi volume and remove it.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4318 Create service files to remove read-write UBI volumes
Closes #1615 Create systemd service file to remove ubi partitions
