### ISSUE TITLE
Add onfailure to ubi systemd service files

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1616]
Handle failures to the ubi service files, like calling the service to clean up the volume and files/directories.
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#OnFailure=

**Comment by anoo1** [comment]
- [ ] Call the ubi unmount service if the ubi mount service fails.
- [ ] Create a squashfs unmount service to do the opposite of the squashfs mount service: unmount the ro mount and remove the volume.
- [ ] Call the squashfs unmount service if the mount service fails.

**Comment by saqibkh** [comment]
PNOR:
- [ ]  Combine the services that creates pnor-ro<versionId> and pnor-rw<versionId>
- [ ]  Add OnFailure to the obmc-flash-bios-ubimount@.service to call ubi delete services (umount ubi volumes, delete mountpoint under /media and then delete the ubi volumes)

BMC:
- [ ]  Add OnFailure=obmc-flash-bmc-ubiro-remove@%i.service to the obmc-flash-bmc-ubiro@.service.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6348> Handle the case where obmc-flash-bmc-ubimount@.service fails
Resolves  #1616 Add onfailure to ubi systemd service files
