### ISSUE TITLE
OCC HWMON support for non-hwmon sysfs attributes

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1619]
Need to expose:

dvfs due to overtemp
dvfs due to power
mem throttle overtemp
n power

booleans from the OCC as non-hwmon sysfs attributes.

**Comment by eddiejames** [comment]
- [ ] export sysfs attributes from platform driver device, not hwmon device
- [ ] test it

**Comment by geissonator** [comment]
Create follow on story to use non-sensor sensors implementation to expose these?

**Comment by eddiejames** [comment]
There is no "n power" (which is redundant power supply present) sensor on P9 occ. We have "quick power drop" instead.

**Comment by geissonator** [comment]
This includes providing hwmon entry on which occ is the master

**Comment by geissonator** [comment]
Opened #1821 to track the use of these new hwmon sensors.

**Comment by rfrandse** [comment]
This is done. Eddie sent patch via mailing list  for openbmc linux
