### ISSUE TITLE
BMC Dump: Add Bash script support for User initiated Dump

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1622]
Add required Bash script infrastructure support for user imitated Dump

**Comment by ojayanth** [comment]
Dreport already have supported this feature .
 Remaining work , related new infrastructre is  contained as part of  https://github.com/openbmc/openbmc/issues/2351

**Comment by ojayanth** [comment]
@dkodihal please close this , support is already in place.

**Comment by dkodihal** [comment]
Implemented via #2351.
