### ISSUE TITLE
Enable FFDC Partition in Flash.

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1624]

**Comment by williamspatrick** [comment]
Do we need a separate partition for this or can we just put this in a specific location in the RW FS?

@anoo1

**Comment by mdmillerii** [comment]
do we want to separate ffdc and logging to ensure the base rwfs does not fill up?

**Comment by geissonator** [comment]
Will just use a shared r/w partition for the bmc dumps in /var/
