### ISSUE TITLE
Fan Control: Calculate speed change request

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1626]
Each sensor involved with fan target speed changes, a T-control(temperature) high and T-control(temperature) low value needs to be defined to determine the net speed change request for each sensor by some increase RPM delta and decrease RPM delta. A copy of the new target speed value should be stored on each zone containing the latest net target speed based on the temperature sensor readings.

~~- [ ] Create a "sensors" yaml file containing the TctrlHigh, TctrlLow, increase delta(per degree), and decrease delta(per degree) for a list of sensors and the zone(s) they are associated with~~
~~- [ ] Parse "sensors" yaml file into a "SensorDefinition" for each zone~~
- [x] Add a net increase delta action based on a defined property value(TctrlHigh) and the increase delta(per degree)
- [x] Add a net decrease delta action based on a defined property value(TctrlLow) and a decrease delta(per degree)
- [x] Add saving last known target speed set(handle application restarts, i.e. fullspeed)
- [x] Create a function within the zone that calculates the new target speed based on the property value stored for each sensor and the defined property value threshold and RPM increase delta.
- [x] Create a function within the zone that calculates the new target speed based on the property value stored for each sensor and the defined property value threshold and RPM decrease delta.

**Comment by bradbishop** [comment]
This was not meant to be in 6.14 committed.  I'm not sure why it got added.  Removed.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4925> Support speed decrease events
Resolves  #1626 Fan Control: Calculate speed change request
