### ISSUE TITLE
Fan Control: Setting/adjusting fan ceiling

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1628]
The fan ceiling is the highest allowed speed for fans within a zone based on an ambient temperature. Given a list of speeds to ambient temperatures for a zone, this is set that at anytime the ambient sensor temperature value is at or below the given value, the fan speeds should not go above that speed.
(*Verify use with thermal team)

- [x] Add/parse a list of temperature-to-RPM within the zone yaml for each zone
- [x] Include a default fan ceiling speed that is used when no list is provided or when the ambient temp sensor reading is above the highest temperature given
- [x] Add the ambient sensors to a group for an event handler to update each property value
- [x] Add an event action function that calculates & sets the fan ceiling RPM attribute on the zone
- [x] Each time a new target speed is to be set, the zone's fan ceiling RPM attribute value should be checked and the speed updated accordingly

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4767> Enable setting/adjusting fan ceiling speed
Resolves  #1628 Fan Control: Setting/adjusting fan ceiling

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4767> Enable setting/adjusting fan ceiling speed
Resolves  #1628 Fan Control: Setting/adjusting fan ceiling
