### ISSUE TITLE
BMC: Updater: Implementation of Software.Activation interface

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1629]
Implement the Software.Activation interface as it's been implemented in the openpower-pnor-code-mgmt to override the property Set functions to trigger the update. Also currently all the images are set to Active, need to set Active only the current image and subsequent uploaded images need to be set to Ready/Invalid.

**Comment by saqibkh** [comment]
- [ ] Implement Software Activation and Requested Activation objects (does this include creating a block transition state and mounting the squashfs image like we did for pnor?)
- [ ] Implement image validation for BMC images
- [ ] Set Activation to Ready/Invalid based on image validation

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4310|https://gerrit.openbmc-project.xyz/4310> ItemUpdater: Validate BMC squashfs image
Resolves <https://github.com/openbmc/openbmc/issues/1629|#1629> BMC: Updater: Implementation of Software.Activation interface
