### ISSUE TITLE
Update led fault monitor to check for existing callouts while starting the app and assert leds.

### ISSUE THREAD

**Issue by dhruvibm** [openbmc/openbmc#1631]

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5674> Assert LEDs for existing callouts while service start
Resolves  #1631 Update led fault monitor to check for existing callouts while starting the app and assert leds.

**Comment by dhruvibm** [comment]
# **STATUS**
08/01: Pushed code for review
