### ISSUE TITLE
Generate error log on Host Watchdog timeout

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/openbmc#1634]
When Host Watchdog expires,  we need to create an errorlog indicating that.

**Comment by vishwabmc** [comment]
- [ ] Create a new systemd.target that can be called by anyone ( ex: Host watchdog app )
- [ ] Create error YAML files
- [ ] Make changes to openpower-debug-collector to add new error definitions
- [ ] Associate openpower-debug-collector with the newly created systemd.target

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4746> openpower-debug-collector: Define checkstop and watchdog services
Fixes  #1634 Generate error log on Host Watchdog timeout
