### ISSUE TITLE
Expose extra aspeed2[45]xx watchdog configurations

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1636]
sysfs attributes are desired for switching WDT_CTRL_RESET_SYSTEM off and WDT_CTRL_WDT_EXT on.

**Comment by cbostic** [comment]
Task list:

- [ ] Identify proper struct device to attach sysfs file to

- [ ] Implement change

- [ ] Determine a test plan and verify function

- [ ] Put up on mailing list for review

**Comment by rfrandse** [comment]
Done. Tracking community with https://github.com/openbmc/openbmc/issues/1906

**Comment by cbostic** [comment]
Status Update
July 14, 2017
-----------------------------------------------------------------------
Yesterday
* No time spent on this item
Today
* Implement v5 changes per community feedback and send up for review.
