### ISSUE TITLE
PNOR: Support for migration to ubifs

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1637]
If the PNOR has been previously flashed with pflash, and a code update is requested with the new squashfs image, save off the preserved partition (nvram), re-format the chip to ubi, and perform the activation.
Without this support, the user would need to manually erase the chip prior to performing the update, and would loose their host bios data.

**Comment by anoo1** [comment]
During activation, service file would:
- [ ] Check if PNOR chip is formatted as UBI or can be formatted as UBI (chip is blank)
If chip can't be formatted as UBI because it's been flashed with a PNOR image:
- [ ] Read the nvram partition and save it in the BMC
- [ ] Reformat the chip, this may require a chip flash erase
The activation process creates the ubi volumes, afterwards:
- [ ] Move the nvram partition to the preserved ubi volume

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4400 openpower-software-manager: Support migration to ubifs
Closes #1637 PNOR: Support for migration to ubifs
