### ISSUE TITLE
Use phosphor-gpio-monitor for checkstop monitor

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/openbmc#1647]
Need to remove the old `org.openbmc.control.Checkstop@.service` and then put phosphor-gpio-monitor in appropriate target

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4644> Add openpower-debug-collector as part of host-crash target
Fixes  #1647 Use phosphor-gpio-monitor for checkstop monitor
