### ISSUE TITLE
Move contents from /var/lib/obmc to /var/persist

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1650]
Openwrt based off buildroot have an implementation to have a single jffs2 read-write partition in /var (/persist).
Yocto provides a root distro feature, we'd want something similar to buildroot using the yoco distro feature to create a read-write partition to store the contents of /var/lib/obmc.

**Comment by saqibkh** [comment]
- [ ] Modify fstab file under openbmc repo to change /var/volatile dir from tmpfs to persistent file system.

**Comment by geissonator** [comment]
Needs more team discussion before we can commit

**Comment by anoo1** [comment]
Per review discussion with Patrick, all the contents of /var/lib/obmc/ need to be persisted, and since the plan is to have /var as a read-write partition, there's no need to move anything out of /var/lib/obmc/ into a tmpfs like /var/volatile/. Therefore this issue can be closed.

There could be a better structure to /var/lib/obmc/ but that can be done with issue https://github.com/openbmc/openbmc/issues/1980
