### ISSUE TITLE
Implement Field Mode

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1653]
Provide a way to set the BMC into Field Mode which would clear the contents of /usr/local/ (where patches can be located) for example.

**Comment by mtritz** [comment]
- [ ] Create a new dbus object for setting the BMC into field mode
- [ ] When the object is called, clear the contents of /usr/local/

**Comment by mtritz** [comment]
Looks like a duplicate of https://github.com/openbmc/openbmc/issues/1350 - putting task list over there.

**Comment by bradbishop** [comment]
closed.  dup of #1350.
