### ISSUE TITLE
Investigate providing the kernel drivers as modules

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1654]
Work with Joel regarding changing the kernel so that most drivers are modules to make the kernel smaller.

**Comment by mdmillerii** [comment]
To what purpose?  Each module text and data has to be a rounded up to the page size.  Neither are compressed during runtime, and both can be stored compressed and uncompressed by u-boot.  We build a custom configured kernel for each system so we don't need to load modules to reduce size or features for different machines for used / not used i2c peripherals, etcetera.

**Comment by anoo1** [comment]
Discussed with Joel, and as Milton mentions, this wouldn't make a difference in space. For example, Joel tried it with the usb drivers and the space was reduced by 100 bytes. Closing.
