### ISSUE TITLE
Reduce the size of the read-only rootfs

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1655]
Currently the size of the read-only rootfs is ~15MB, the ideal target would be ~10MB.
Potential size savers:
* Remove gdbus
* python .py files, can we use the build .pyc
* perl
* Upgrade systemd

**Comment by amboar** [comment]
Why 10MB?

**Comment by anoo1** [comment]
> Why 10MB?

It's a number that @williamspatrick mentioned, maybe based on the current flash size that'd allow for 2 images to be saved in one chip, or maybe it's how much realistic we could shed off.

**Comment by anoo1** [comment]
Per team discussion, and after packages like the Web UI are making the image bigger, it was concluded that fitting 2 images in one 32MB chip is not realistic, so if somebody has that requirement they can remove packages to make it fit. Closing.
