### ISSUE TITLE
Refactor mapper to be c++ application

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1661]
Mapper is currently written in python, ideally it would be rewritten in c++ for code maintenance, performance, size, and service reasons.

**Comment by geissonator** [comment]
Included in this is a rewrite of the command line tool used by the services.  See the review comments here for a proposal from Brad. https://gerrit.openbmc-project.xyz/#/c/2864/7/meta-phosphor/common/recipes-phosphor/chassis/obmc-op-control-power/op-reset-pgood-check%2540.service@12

**Comment by gtmills** [comment]
@edtanous Has a C++ mapper rewrite. @geissonator Can we close?

**Comment by bjwyman** [comment]
ibm-openbmc/dev#153 seems to imply that we now have a C++ mapper.

**Comment by bjwyman** [comment]
Start: https://github.com/openbmc/phosphor-objmgr/commit/605206314f23710ef8a429745f139c891630588f

End: https://github.com/openbmc/meta-phosphor/commit/940ede4c9ababd85d5b766c3758439a00bb922b2

???

**Comment by bjwyman** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/16321

**Comment by anoo1** [comment]
Closing since it's resolved.
