### ISSUE TITLE
Move MANIFEST file over to use correct purpose. 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#1668]
The MANIFEST file should use the correct purpose. 
(i.e. xyz.openbmc_project.Software.Version.VersionPurpose.BMC)
image_manager.cpp should be updated as well to accept this purpose.

**Comment by gtmills** [comment]
- [ ] Change to generate-squashfs to set the purpose to xyz.openbmc_project.Software.Version.VersionPurpose.Host
- [ ] Change image_manager.cpp to accept the correct purpose

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4922> Change purpose set in generate-squashfs
Resolves  #1668 Move MANIFEST file over to use correct purpose.
