### ISSUE TITLE
Phosphor-networkd:- Use case validation.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1671]
ip address Create should return error(if dhcp is enabled )

ip address Delete should return error (user should not be allowed to delete the link local or dhcp ip address).

when users creates the ip it may happen that ipaddress and prefix is same but gatway is changed so we need to change the gateway accordingly.

ipaddress/gateway/subnet mask(v4/v6) validation.

Need to write a utility which test that the given gateway is reachable/not.User should add the gateway which is reachable.

**Comment by ratagupt** [comment]
We should only validate that the IP/gatway is in ithe inet_pton format http://man7.org/linux/man-pages/man3/inet_pton.3.html

**Comment by ngorugan** [comment]
- [ ] Update ip address Create to 

     1. return error,if dhcp is enabled
     2. change the gateway if ipaddress and prefix is same but gatway is changed while user creating ip.

- [ ] ip address Delete should return error for link local and dhcp ip addresses

- [ ] Write test cases to Validate ipaddress/gateway/subnet mask(v4/v6).

- [ ] Write a utility which tests that the given gateway is reachable/not.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7048> IP Address use case validation
Resolves  #1671 Phosphor-networkd:- Use case validation.
