### ISSUE TITLE
MFG:Witherspoon, toolkit logging unrecoverable "VDN_PGOOD OFF, CBS_ENVSTAT BIT 2 NOT SET" error as informational

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1672]
The request is to make all host eSEL based errors default to "Error"

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4437|https://gerrit.openbmc-project.xyz/4437> Modify log level to ERR for host event in yaml file
Resolves <https://github.com/openbmc/openbmc/issues/1672|#1672> MFG:Witherspoon, toolkit logging unrecoverable "VDN_PGOOD OFF, CBS_ENVSTAT BIT 2 NOT SET" error as informational
