### ISSUE TITLE
Refactor ubi service files into shell scripts

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1673]
Reference: https://gerrit.openbmc-project.xyz/#/c/4008/

The service files that create the ubi volumes and mount points are starting to get too much logic in them. Create shell scripts instead of having all the commands and logic in the service files.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4792> openpower-software-manager: Move the logic in the service files to scripts
Closes  #1673 Refactor ubi service files into shell scripts

**Comment by anoo1** [comment]
- [ ] Move the script logic from the service systemd files to (single?) script file.
