### ISSUE TITLE
Networkd:-Define the DBUS interface for DHCP option configuration.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1685]
Support for configuration of DHCP Option. we need to support NTP as DHCP Option,We need to support clientIdentifier which could be MAC/DUID.

Other option could be hostname,domainname from DHCP.

**Comment by ratagupt** [comment]
- [ ] Define the dbus interface for DHCP option.
        options can be following.
          - NTP
          - Hostname
          - Domain Name
          - ClientIdentifier

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4774> Define interface for DHCP options
Resolves  #1685 Networkd:-Define the DBUS interface for DHCP option configuration.
