### ISSUE TITLE
[Witherspoon]:REST Logging attribute "Resolved" can't be set from external

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1689]

**Comment by gkeishin** [comment]
Original defect https://github.com/openbmc/openbmc/issues/1640

**Comment by ojayanth** [comment]
It is working good in the latest build , also noticed the curl command was wrong.

jayanths-MacBook-Pro:~ ojayanth$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\":1}" -X PUT https:/9.3.185.33/xyz/openbmc_project/logging/entry/43/attr/Resolved

{
 "data": null,
 "message": "200 OK",
 "status": "ok"


}jayanths-MacBook-Pro:~ ojayanth$ curl -c cjar -b cjar -k https://9.3.185.33/xyz/openbmc_project/logging/entry/43
{
 "data": {
    "AdditionalData": [],
    "Id": 43,
    "Message": "xyz.openbmc_project.Common.Error.InternalFailure",
    "Resolved": 1,   -----------> setting to 1
    "Severity": "xyz.openbmc_project.Logging.Entry.Level.Error",
    "Timestamp": 1501775038378,
    "associations": []
 },
 "message": "200 OK",
 "status": "ok"

**Comment by gkeishin** [comment]
working good on latest master.. will close up CQ once in GHE
