### ISSUE TITLE
OCC hwmon driver requires manual OCB setup

### ISSUE THREAD

**Issue by eddiejames** [openbmc/openbmc#1697]
Hostboot will not setup the OCB channels like in P8. Need to switch the OCC "fifo" driver to use getsram/putsram instead of getscom/putscom through SBE. SBE will automatically setup channels with sram access.

**Comment by eddiejames** [comment]
- [ ] Write getsram/putsram functions in the OCC FIFO driver
- [ ] Re-write worker function to write the command direct to sram and read the response
- [ ] Test it.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4565 linux: bump version
Resolves openbmc/openbmc#1697
