### ISSUE TITLE
OCC bind and unbind as occ sensor goes active and non-active

### ISSUE THREAD

**Issue by eddiejames** [openbmc/openbmc#1698]
Driver is probed via FSI, but FSI starts up long before the OCC goes active. Need a service to automatically rescan FSI once the OCC is active.

**Comment by eddiejames** [comment]
- [ ] Create systemd service files to bind and unbind occ-hwmon driver
- [ ] Create yaml for phosphor-dbus-monitor to watch OccStatus sensor for change in state and start appropriate service file.
- [ ] Install in OpenBmc and test it.

**Comment by geissonator** [comment]
Per design discussion this morning, Vishwa will take this story and will implement the occ active sensor dbus interfaces to handle this function.

The services should basically do this I believe:
echo occ1-dev0 > /sys/bus/platform/drivers/occ-hwmon/bind
echo occ2-dev0 > /sys/bus/platform/drivers/occ-hwmon/bind

echo occ1-dev0 > /sys/bus/platform/drivers/occ-hwmon/unbind
echo occ2-dev0 > /sys/bus/platform/drivers/occ-hwmon/unbind

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/#/c/4862/

**Comment by vishwabmc** [comment]
- [ ] Implement OCC Status sensor dbus objects
- [ ] Implement sd_event loop for handling user requests
- [ ] Define a class that is responsible for bind and unbind
- [ ] Define the relation between the sensor class and this bind class
- [ ] Watch for occ-error indication in the /sysfs entry
- [ ] Use Sensor class and Bind class to do the right thing when Status is set to Active and making it Inactive

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5040> Add support to watch for OCC errors
Fixes  #1698 OCC bind and unbind as occ sensor goes active and non-active

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5040> Add support to watch for OCC errors
Fixes  #1698 OCC bind and unbind as occ sensor goes active and non-active
