### ISSUE TITLE
Write a bbclass to simplify copying of error yaml files in native recipes

### ISSUE THREAD

**Issue by devenrao** [openbmc/openbmc#1704]
At present error yaml files are copied manually in the do_install method of error-native recipes. As there are many native recipes expected for the applications it is better to create a bbclass that takes in parameters and automates the copying of error yaml files.

Refer to openpower-debug-collector-error-native.bb how it is done manually.

**Comment by devenrao** [comment]
Also need to consider the review comment proposed by Brad at the below link
https://gerrit.openbmc-project.xyz/#/c/4209/15/meta-phosphor/common/recipes-phosphor/logging/phosphor-logging-error-logs-native.bb

**Comment by devenrao** [comment]
# **STATUS**
03/08
Working on moving the copy function to base class, no success so far

**Comment by devenrao** [comment]
No longer valid as we are using nativesdk class to upload the error yaml files through makefile changes and using BBCLASSEXTEND += native nativesdk

This story can be invalidated

**Comment by gkeishin** [comment]
Closing this as request @tomjoseph83
