### ISSUE TITLE
REST API to set a user login password

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1714]
Implement a REST API to set a user login password.

**Comment by vishwabmc** [comment]
# **TASK**
- [ ]

**Comment by vishwabmc** [comment]
# **STATUS**

**Comment by vishwabmc** [comment]
We talked in today's task review meeting and the decision was that its not needed for EarlyShip and hence this can be taken in Phase:6 since its a lower priority.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6438> Throw exceptions on password update failure
Fixes  #1714 REST API to set a user login password
