### ISSUE TITLE
BMC: Implement Common.FilePath interface 

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#1715]
Implement the Common.FilePath interface for BMC images, so that it can be used by the Software dbus object.

Common.FilePath interface is here https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Common/FilePath.interface.yaml

**Comment by saqibkh** [comment]
- [ ]  Move Active BMC version object to Image Manager.
- [ ]  Use Common.FilePath to find the image files.
- [ ]  Check Common.filePath to determine active image.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4636> item_updater: Use Common.FilePath to locate images
Resolves  #1715 BMC: Implement Common.FilePath interface
