### ISSUE TITLE
PNOR: Wait for Activation service files to finish

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1716]
1. Move the call to the systemd service file that loads the squashfs image to the RO volume to the Activation process instead of during the upload of the image.
2. Use systemd to subscribe to the 2 services that are called during Activation (the one that loads the squashfs image from step1, and the one that creates the RW volumes) to determine when they're done before claiming the activation was successful.
The reason is that the dbus method StartUnit starts a service in the background.
For reference, use the phosphor-state-manager implementation on how to subscribe to service files.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4795> Activation: Wait for service files to complete
Resolves  #1716 PNOR: Wait for Activation service files to finish
