### ISSUE TITLE
Factory reset: Define a generic ResetFailed error

### ISSUE THREAD

**Issue by mtritz** [openbmc/openbmc#1721]
- [x] Define a generic error that can be returned in the event of failure during any of the various factory reset procedures. 
- [x] Create an elog<> at all points of failure in those procedures.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6343> Define a generic ResetFailed error for all factory reset functions
Resolves  #1721 Factory reset: Define a generic ResetFailed error
