### ISSUE TITLE
add GPUs to inventory

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1725]
<cde:info> SW395438 </cde:info>
GPUs need to be added to the inventory so we can call them out if they caused a power fault.

**Comment by spinler** [comment]
So far, the only way we can tell which nvlink GPUs are present is by seeing that the OCC is sending down temperatures for them.   We'd have to do more negotiating with the OCC team to get them to send us their present status, which they keep internally.

**Comment by geissonator** [comment]
Patrick is driving this

**Comment by spinler** [comment]
For power sequencer faults, I have plans to just add the failing GPU to the error log metadata, and will work with the RAS team on the documentation to go along with it.  So I don't need the GPUs in the inventory for those.

That being said, there are new plans for hostboot to send down GPU functional sensors so they can be added to the inventory so the OCC can call them out.

**Comment by geissonator** [comment]
Host is sending this down, we just need a yaml file update for it.  Functional sensor (like cores).

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7108> Add GPU to inventory
Resolves  #1725 add GPUs to inventory
