### ISSUE TITLE
Do GPU fault analysis to callout a GPU

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1726]
If the UCD chip indicates the fault came from a GPU, we need to read an IO expander to tell which GPU it was, and create an error log with that GPU as a callout.

**Comment by spinler** [comment]
I'm thinking we'll define the map of GPIOs to inventory objects in the same YAML that has the rest of the UCD analysis configuration.   Still need to investigate what all needs to happen to add an inventory object to an error.

**Comment by spinler** [comment]
- [ ] If the UCD chip says the GPU_PGOOD or GPU_OVERTEMP summary faults are on (already being checked for), go read the 9552 that has the fault line for each specific GPU
- [ ] If a GPIO on the 9552 says a GPU is faulted, created a GPU-PGood-Fault or GPU-OverTemp error log
- [ ] Put the failing GPU in the metadata.  In the future, if GPUs are in inventory, can do a regular callout
- [ ] Only create an error for each type once for each GPU, not repeatedly
- [ ] If an OverTemp is found, shutdown the system after the error is logged (will use the existing function that also generates a SystemShutdown due to Power Fault  error log

**Comment by spinler** [comment]
# **STATUS**
*

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6768> Shutdown system on GPU over-temps
Resolves  #1726 Do GPU fault analysis to callout a GPU
