### ISSUE TITLE
UCD device driver to expose registers for fault analysis

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1727]
We need the following registers/commands for the UCD90160

- CLEAR_FAULTS  - command 0x03
- clear logged faults - write 0x00 to register 0xEA
- STATUS_WORD - 0x79
- STATUS_VOUT  - 0x7A - all pages
- NUM_PAGES - 0xD6
- MFR_STATUS - 0xF3 - page 0 - for reading the GPI bits

Also:

Write, 0xFA 0x08
Read, 0xFB
Write, 0xFA 0x09
Read, 0xFB
Write, 0xFA 0x0A
Read, 0xFB
Write, 0xFA 0x0E
Read, 0xFB
Write, 0xFA 0x11
Read, 0xFB
Write, 0xFA 0x0B
Read, 0xFB

**Comment by spinler** [comment]
The chip's command reference: http://www.ti.com/lit/ug/slvu352f/slvu352f.pdf

**Comment by cbostic** [comment]
Status:
Coded for ucd driver most of day and ran some limited unit tests.

**Comment by cbostic** [comment]
Task list

- [ ] Identify all required sysfs files and create a directory structure
- [ ] Create a method that checks for ucd91060 and only creates files/accesses for this type only
- [ ] Code
- [ ] Unit test all files for correct I2C access of ucd90160

**Comment by cbostic** [comment]
Status Update
July 14, 2017
--------------------------------------------------------------------
Yesterday
* No time spent on this story, focus was on 1783.

Today
* Not planning on working this today.  Focus is on 1636 and 1783

**Comment by rfrandse** [comment]
will track this getting in upstream with 
https://github.com/openbmc/openbmc/issues/2306
