### ISSUE TITLE
Send Clear Faults command to power supplies on a power on

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1736]

**Comment by bjwyman** [comment]
Is this going to have a similar result as the UCD device driver did?
openbmc/openbmc#1722
https://github.com/openbmc/openbmc/issues/1722#event-1215975776

**Comment by spinler** [comment]
Turns out the power supply device driver will send a clear faults every time status_word is read, which will be once per second, so no need to clear faults manually.
