### ISSUE TITLE
Send SYNC commands to power supplies on a power on

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1737]
Need this to line up the PSs timers when providing trending data.

The requirements doc also mentions an enhancement would be to send this every hour as well.  Can look into this.

**Comment by spinler** [comment]
This is for syncing up trending data between the 2 devices, so moving to phase 6 along with that function.

**Comment by bjwyman** [comment]
This is in the #2310 Squad 2 list under my name. Was I supposed to have it assigned to me?

**Comment by bjwyman** [comment]
Tried a manual test on a system in Rochester.
Odd results, packets seem to update faster than 30 seconds, among other odd results.

**Comment by bjwyman** [comment]
# Task List
- [ ] Add service file to toggle "SYNC" line for power supplies at/around power on.
- [ ] Update recipe file(s) to include new service file.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6996> Create recipe to add service for power supply SYNC
Resolves:  #1737 Send SYNC commands to power supplies on a power on
