### ISSUE TITLE
Do System-specific bitbake recipes in a non-System-specific way

### ISSUE THREAD

**Issue by bjwyman** [openbmc/openbmc#1739]
Much discussion on best, more appropriate way to do some Witherspoon-specific changes in recipe file updates:

https://gerrit.openbmc-project.xyz/#/c/3991/29/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan%25.bbappend

@bradbishop

**Comment by bjwyman** [comment]
Original link does not appear to work anymore. Gerrit server change? I think this is pointing to the same spot as the original comment:
https://gerrit.openbmc-project.xyz/#/c/3991/29/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan%2525.bbappend

**Comment by gtmills** [comment]
@bradbishop @bjwyman  What is wrong with how we do System-specific bitbake recipes in Witherspoon?

**Comment by bjwyman** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/3991/29/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan%2525.bbappend#1
