### ISSUE TITLE
BMC: Implement Software RedundancyPriority.interface

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1755]
Same objective as #1553 "PNOR: Implement Software RedundancyPriority.interface" but in the BMC updater.

**Comment by saqibkh** [comment]
- [ ]  Add Redundancy Priority interface to Activation class
--> shows up only for active images.
--> Disappears if the activation property is set to something other than "Active"
- [ ] Set Redundancy to 0 once the activation is successful.
- [ ] Increment priority of other activated versions by 1.

**Comment by geissonator** [comment]
Pending approval by Patrick on PNOR implementation of this, we can move into committed.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5126> BMC: Implement Software RedundancyPriority.interface
Resolves  #1755 BMC: Implement Software RedundancyPriority.interface
