### ISSUE TITLE
BMC: Implement the Activation flow (write/update files)

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1756]
When the RequestedActivation property is set to Active, similar to the PNOR flow, need to load the image files to the corresponding destinations / ubi volumes, and the the version to Active.

**Comment by mtritz** [comment]
- [ ] Identify or create service files to load images
- [ ] Implement the flow as in https://github.com/openbmc/openbmc/issues/1716 - when service files complete, continue with activation process
- [ ] Add any necessary filesystem operations, equivalent to those found in PNOR activation, after completion of service files
- [ ] Add conditions to reach Active/Activating/Failed states

**Comment by mtritz** [comment]
Daily status:
7/12: Created task list.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5393> Activation: Start service files and wait for completion
Resolves  #1756 BMC: Implement the Activation flow (write/update files)
