### ISSUE TITLE
PNOR: On BMC boot, create the Software version that points to the current PNOR image

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1762]
When the BMC boots and the pnor updater is started, create the software version of the pnor image currently loaded on memory.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4714> Add version class to repository.
Resolves  #1762 PNOR: On BMC boot, create the Software version that points to the current PNOR image

**Comment by saqibkh** [comment]
- [ ] Create functions under version class in openpower-pnor-code-mgmt to read the current pnor version.
- [ ] Call pnor version set function inside item_updater class constructor.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4854> Create Version and Activation objects for current PNOR image
Resolves  #1762 PNOR: On BMC boot, create the Software version that points to the current PNOR image
