### ISSUE TITLE
Phosphor-inventory-manager failure to create interface objects

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1763]

**Comment by dkodihal** [comment]
From the CQ defect that @devenrao opened : Recent changes has been done as part of 1499 to copy all the interface and yaml files from the applications and dbus-interfaces to a common location.

Phosphor-inventory-manger is pointing to the older location to pick the interface yaml files which no longer exist.


Also seen failure when phosphor-inventory-manager parses openpower interface yaml files.

**Comment by devenrao** [comment]
This has been fixed and can be closed

**Comment by dkodihal** [comment]
Closing based on comment above.
