### ISSUE TITLE
Mapper ignores non-xyz interfaces

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1767]
signal time=1496968226.917636 sender=:1.313 -> destination=(null destination) serial=63 path=/xyz/openbmc_project/occ/pass_through; interface=org.freedesktop.DBus.ObjectManager; member=InterfacesAdded
   object path "/xyz/openbmc_project/occ/pass_through/occ1"

The occ-control app creates the object above which is introspectable via busctl but not REST, because REST talks to the mapper and mapper ignores non-xyz interfaces. This object implements an org.open_power interface. @bradbishop thinks the supported interfaces should be configurable.

**Comment by bradbishop** [comment]
up for review: https://gerrit.openbmc-project.xyz/#/c/5176/
