### ISSUE TITLE
Cors issue for uploading images via GUI

### ISSUE THREAD

**Issue by iftekharuli** [openbmc/openbmc#1768]
We are working on firmware update in this sprint and ran into some issues on host/image upload.

We are running the following curl command to upload.

curl -c cjar -b cjar -k -H "Content-Type: application/octet-stream" -X PUT -T /Users/iislam/sites/w37.pnor.squashfs.tar https://9.3.185.173/upload/image/

Via command line it works fine. But I am getting the following error if I want to do the same thing via browser.

XMLHttpRequest cannot load https://9.3.185.173/upload/image/. Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.

We might need to fix CORS headers for this route.

**Comment by gtmills** [comment]
Uploading an image works from the GUI. closing this issue.
