### ISSUE TITLE
phosphor-settingsd : implement settings validation

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1771]
Implement methods to validate various settings. The validation must take place when a user changes a setting from the default to a new value.

**Comment by dkodihal** [comment]
- [ ] Specify that a setting needs validation in the settings yaml, specify the "type" of validation required. Currently we would need a "range" based validation and a "custom" validation (for network settings).
- [ ] Generate code such that when a "set" operation happens on a setting, the corresponding validator is invoked.
- [ ] Implement the range based validation method. Throw an exception back over the bus when an invalid value is provided by a setting.

**Comment by dhruvibm** [comment]
Started working from today

**Comment by dhruvibm** [comment]
# **STATUS**
07/24 - Started word from today.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5491> Validation for settings while setting values.
Resolves  #1771 phosphor-settingsd : implement settings validation
