### ISSUE TITLE
add power supply serial number to inventory

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1782]
Add power supply serial number to power supply inventory objects.  Device driver support is missing.

**Comment by bjwyman** [comment]
MFR_SERIAL (9Eh) needs to get exposed in sysfs.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8421> Fill in PowerSupply::updateInventory()
Resolves  #1782 add power supply serial number to inventory
