### ISSUE TITLE
Witherspoon gpio-keys additions

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1783]
Add gpio keys to the witherspoon DT for:

fan presence
power supply presence
UCD alert

**Comment by cbostic** [comment]
Task list:

- [ ]  Identify Port and pin number for each of the new keys

- [ ]  Identify signal polarity for each of the new keys (ACTIVE_HIGH, ... )

- [ ]  Code, test and submit for review

**Comment by cbostic** [comment]
Status:
Yesterday - No time spent on this story, focus was on 1727
Today - Will shift focus back to this story and implement polling function.

**Comment by geissonator** [comment]
Need to update task list to include new poll function

**Comment by cbostic** [comment]
Status Update
July 14, 2017
-------------------------------------------------------
Yesterday
* Worked with Gunnar to test the direct gpio portion of this story.   This is functional and I've sent this up for review to OpenBMC.
* Started work on polling GPIO.  Design complete and coding mostly done.
Today
* Finish up coding for polling GPIO and unit test

**Comment by mdmillerii** [comment]
Are you using gpio-keys-polled ?   from `Documentation/gpio/drivers-on-gpio.txt`
```
- gpio-keys-polled: drivers/input/keyboard/gpio_keys_polled.c is used when your
  GPIO line cannot generate interrupts, so it needs to be periodically polled
  by a timer.
```

**Comment by cbostic** [comment]
On 7/14/17 9:05 AM, Milton D. Miller II wrote:
>
> Are you using gpio-keys-polled ? from 
> |Documentation/gpio/drivers-on-gpio.txt|
>
> |- gpio-keys-polled: drivers/input/keyboard/gpio_keys_polled.c is used 
> when your GPIO line cannot generate interrupts, so it needs to be 
> periodically polled by a timer.|

|Hi Milton,

gpio-keys-polled isn't part of this submission - that will come next.  
The particular GPIOs here are direct connected to the AST2400/2500 only.
|

**Comment by bjwyman** [comment]
->  ARM: dts: aspeed: witherspoon: Add gpio-keys-polled for fan presence 
--> https://github.com/openbmc/linux/commit/5ea0608616b939bee5f0856a4227efedcc774249
->  kernel: fsi fixes for r/r 
--> https://github.com/openbmc/openbmc/commit/3f6eb4cf07f1ca218dcc8189726f4aaecc7cec13

**Comment by geissonator** [comment]
Done
