### ISSUE TITLE
Persist host and chassis state requests

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1785]
Persist host and chassis state requests, so that they can be restored on BMC reset.

**Comment by dkodihal** [comment]
- [ ] Persist the value of the request host state transition using Cereal.
- [ ] When the host state manager starts up, if there is a persistent request host state value, deserialize that using Cereal and execute a state transition based on that request.
- [ ] State recipe : add a depends on Cereal.

**Comment by geissonator** [comment]
Some notes from review:
- 2nd task should look at settings for boot policy
- Need to update state services to show dependency on new settingsd application

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5223> Add support for host state persistency
Resolves  #1785 Persist host and chassis state requests

**Comment by dhruvibm** [comment]
Got 2 +1s, need merge review

**Comment by dhruvibm** [comment]
# **STATUS**
07/24 - Planning to push a rework today.
