### ISSUE TITLE
Define object specific inventory interfaces

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1786]
Most of the inventory objects today implement a generic inventory Asset interface. We may need specific interfaces (just empty ones?) to let user code (such as UI code) distinguish inventory objects based on interface (instead of having to do it based on object paths).

**Comment by dkodihal** [comment]
This story can also cover changes to the occ-control-app, which for the lack of this, was dealing with object paths to figure out that CPU inventory has been added. Instead, use InterfacesAdded.

**Comment by dkodihal** [comment]
PIM has some code to ignore empty interfaces, would need some changes there.

**Comment by dkodihal** [comment]
- [ ] Define empty interfaces for inventory items - for eg a CPU interface, a DIMM interface etc.
- [ ] Change pimgen.py to accept empty inventory interfaces.
- [ ] Change the vpd parser apps to denote that inventory items must implement these interfaces.
- [ ] Fix occ control app which figures out CPUs by path to instead watch for a CPU interface being added.

**Comment by devenrao** [comment]
# **STATUS**
12/08
Understanding existing parser code
14/08
Analyzing the changes to be done

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6380> inventory - Allow empty interfaces in creation of inventory objects
Resolves  #1786 Define object specific inventory interfaces
