### ISSUE TITLE
BMC Dump todos.

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1795]
- [x] Update BMC Dump Path to FFDC Partition : Define Persistent dump location and make required updates in the code.

- [ ] Enable Coredump in BMC.
          - Define Core Dump Pattern
          - Add support to Initialize the  core pattern during boot.
          - Implement the Internal Create function - used by core dump to start dump collection.
          - Enable the bash script to support core dump file in FFDC script.

- [x] Define Dump File name , Which includes  Serial Number+Dump ID + Time stamp. tar. 
             - Add support in Dump File monitoring function  to  get Dump ID based on Dump file name.

- [ ] Rebuild Dump Entry D-bus objects based on Dump Files in the flash during reboot.
         Open Issue : Initializing Dump Entry id.

**Comment by geissonator** [comment]
Potentially break this one up a bit, merge with others.

**Comment by ojayanth** [comment]
Code review is in progress for  task 1,2,3

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5446> Include -e option in the ffdc during the dump collection
Resolves  #1795 BMC Dump todos.
