### ISSUE TITLE
u-boot fixes for palmetto

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#18]
- set the kernel command line to output on ttyS4
- enable DHCP

**Comment by jk-ozlabs** [comment]
The first one should be covered by https://github.com/openbmc/openbmc/pull/19

**Comment by williamspatrick** [comment]
@shenki - What is the current state of this?

**Comment by shenki** [comment]
We don't need to track this anymore.

We will soon move to a 2016 based u-boot release for all platforms, which will include these features.
