### ISSUE TITLE
Detect OCC errors and notify userspace

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1802]
Per the "OCC_P9_FW_Interface" specification, the BMC needs to monitor for these failures and take corrective action.

```
The BMC must send a request to reset the OCCs when it detects one of the following and the “OCC Active” sensor is TRUE with no checkstop present:
- Communication failure to an OCC defined in BMC-OCC Communication Failure section.
- Number of bits set in “OCCs Present” from master poll response does not match the number of OCCs the BMC is communicating with.
- Current OCC State byte in poll response is “Safe” for one minute and the “OCC Active” sensor is TRUE.
```

This story will track the driver work to detect these failures and provide a sysfs entry indicate the error that userspace can monitor.

**Comment by eddiejames** [comment]
- [ ] Add non-hwmon sysfs attribute for occ error state
- [ ] Set the error state according to logic detailed above

**Comment by bradbishop** [comment]
This has been merged.
