### ISSUE TITLE
Missing properties for inventory/system/chassis/motherboard 

### ISSUE THREAD

**Issue by jayeshmpatel** [openbmc/openbmc#1809]
Some of the properties (Functional, Cached or FieldReplaceable) for the motherboard are not available. Not sure if it is as per design or missing. 

"/xyz/openbmc_project/inventory/system/chassis/motherboard": {
        "BuildDate": "", 
        "Manufacturer": "0000000000000000", 
        "Model": "", 
        "PartNumber": "00VK525         ", 
        "Present": 0,                                      
        "PrettyName": "SYSTEM PLANAR   ", 
        "SerialNumber": "Y130UF72702D    "
    }, 

I have seen this on Witherspoon system with following BMC code level and chassis/Host State.

/xyz/openbmc_project/software/25bd815": {
        "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active", 
        "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC", 
        "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None", 
        "Version": "ibm-v1.99.7-0-r0"
    }, 
    "/xyz/openbmc_project/state/bmc0": {
        "CurrentBMCState": "xyz.openbmc_project.State.BMC.BMCState.Ready", 
        "RequestedBMCTransition": "xyz.openbmc_project.State.BMC.Transition.None"
    }, 
    "/xyz/openbmc_project/state/chassis0": {
        "CurrentPowerState": "xyz.openbmc_project.State.Chassis.PowerState.On", 
        "RequestedPowerTransition": "xyz.openbmc_project.State.Chassis.Transition.Off"
    }, 
    "/xyz/openbmc_project/state/host0": {
        "CurrentHostState": "xyz.openbmc_project.State.Host.HostState.Running", 
        "RequestedHostTransition": "xyz.openbmc_project.State.Host.Transition.On"
    },

**Comment by gtmills** [comment]
@dkodihal We missing any properties for inventory/system/chassis/motherboard or can we close?
