### ISSUE TITLE
HWMON Core dump [ Witherspoon ]

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc#1815]
Log Info:
```
root@witherspoon:~# journalctl --no-pager | egrep 'SEGV|core-dump'
Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x4                                                                                                                     01e78a000-i2c\x2dbus\x40140-ir35221\x4070.service: Failed with result 'core-dump                                                                                                                     '.
Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x4                                                                                                                     01e78a000-i2c\x2dbus\x40400-ucd90160\x4064.service: Failed with result 'core-dum                                                                                                                     p'.
Apr 20 18:48:26 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x4                                                                                                                     01e78a000-i2c\x2dbus\x40140-ir35221\x4070.service: Failed with result 'core-dump    
  ```

System Info:

```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.7-13"
VERSION_ID="v1.99.7-13-gb0261ea"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.7-13"
BUILD_ID="v1.99.7"
root@witherspoon:~#
```

Attached Journal , dmseg, FFDC logs
[witherspoon_journal.txt](https://github.com/openbmc/openbmc/files/1087815/witherspoon_journal.txt)
[dmesg.txt](https://github.com/openbmc/openbmc/files/1087818/dmesg.txt)
[20170620050850114839_MyFFDCLogs.zip](https://github.com/openbmc/openbmc/files/1087819/20170620050850114839_MyFFDCLogs.zip)

**Comment by sivassrr** [comment]
Looks like this is same as https://github.com/openbmc/openbmc/issues/1798

Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x401e78a000-i2c\x2dbus\x40140-ir35221\x4070.service: Main process exited, code=dumped, status=6/ABRT
Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x401e78a000-i2c\x2dbus\x40140-ir35221\x4070.service: Unit entered failed state.
Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x401e78a000-i2c\x2dbus\x40140-ir35221\x4070.service: Failed with result 'core-dump'.
Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x401e78a000-i2c\x2dbus\x40400-ucd90160\x4064.service: Main process exited, code=dumped, status=6/ABRT
Apr 20 18:39:39 witherspoon systemd[1]: Stopped Phosphor Hwmon Poller.
Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x401e78a000-i2c\x2dbus\x40400-ucd90160\x4064.service: Unit entered failed state.
Apr 20 18:39:39 witherspoon systemd[1]: xyz.openbmc_project.Hwmon@ahb-apb-i2c\x401e78a000-i2c\x2dbus\x40400-ucd90160\x4064.service: Failed with result 'core-dump'.
