### ISSUE TITLE
Provide throttling and overtemp information to external users

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1821]
#1619 provides new hwmon entries for things like throttling due to overtemps and power limits.  When these get set, we need something to provide this information to the user (via event log or some other mechanism).   This issue is to track that work.

**Comment by geissonator** [comment]
We'll use this story to add the new sensors to hwmon.  #1966 for notifying people of the events.

**Comment by eddiejames** [comment]
# **STATUS**

08/09 - No progress yet due to working on pmbus core.

**Comment by dkodihal** [comment]
This would need to use the event logging mechanism (#1856) to be able to log the event, once the overtemp info is known.

**Comment by geissonator** [comment]
Eddie to look into using alarm feature for over temps.  
Reporting throttling?  debugfs?  Some non-standard mechanism.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7056> Add watches for throttling reported by the OCC
Resolves  #1821 Provide throttling and overtemp information to external users
