### ISSUE TITLE
Reduce host shutdown timeout from 45 min to 5 min

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1823]
We've hit a few bugs where the host acknowledges the shutdown SMS ATTN but then does not properly shutdown.  We currently give the host 45 minutes to shut down which is very excessive.  Reducing this timeout to 5 minutes per discussion this morning with the team.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4895> Reduce host shutdown timeout to 5 minutes
Resolves  #1823 Reduce host shutdown timeout from 45 min to 5 min
