### ISSUE TITLE
Fan Control - Add 'delay' parameter on events

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1835]
Until OCC goes "Active", a group of sensors provided by OCC will not exist and should be delayed from having the fan control application matching on those dbus signals.

An event parameter for a 'delay' will be needed driven by a group of properties changing. The property change delay should read each group entry's initial property state and then trigger the group defined to be 'delayed'  to start matching once all the entries in the group equals some given state.

The design to provide this should take into account other means of 'delays' being configured on an event group, such as the use of a timer.

**Comment by bjwyman** [comment]
STATUS:
Actually had a start Tuesday. Discussion with @msbarth. Started updating example/events.yaml.
07/12 - Added occ active condtion check to events.yaml.
- Started updating functor.hpp for handling a condition, and created conditions.hpp.
- Simple updates to YAML parser, but apparently not simple enough, bitbake build fails.

**Comment by geissonator** [comment]
Need task list

**Comment by bjwyman** [comment]
- [ ] Update events YAML file(s) to have conditions section.
 * Add condition to check for OCC status active.
- [ ] Update fan control code to create and use condition checking method.
- [ ] Update fan control YAML parser to handle conditions for fan_zone_defs.cpp

**Comment by msbarth** [comment]
- [ ] Review functional implementation of provided code
- [ ] Add 'condition' section to events yaml supporting 1-to-many property changed conditions
- [ ] Determine yaml and generated source layout of using conditions within an event
- [ ] Read the conditions' properties and subscribe to their signal changes prior to init'ing any event
- [ ] Only init events when no condition is provided or 'condition' is in TRUE state
- [ ] When condition is TRUE, get the event group's properties, subscribe to their signal changes, and run the event action
- [ ] When condition is FALSE, unsubscribe from event group's signal changes and remove from property cache

# **STATUS**
7/26
Caught up on things while out and had meeting(1.5hr) with Todd over OpenBMC.
Walked thru #1835 handoff with Brandon, begin reviewing #1835 changes for reuse after acquiring.

No scrum, demo meeting, retrospective discussion, and 0x3030 support discussion(3.5hr total)
Determine final design for #1835 based on what's intended and code provided.
Walk thru provided #1835 code to determine re-usability with decided design.
Begin implementation layout framework(yaml, generated code structure, etc...)

Blockers -

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5859> Update parser to support optional preconditions
Resolves  #1835 Fan Control - Add 'delay' parameter on events
