### ISSUE TITLE
No PRDF callout generated on COREFIR checkstop through cronus putscom operations [witherspoon]

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc#1838]
Issue:

No PRDF callout generated on COREFIR checkstop through cronus putscom operations.

Expectation:

PRDF callout corresponding to COREFIR checkstop should be generated.

System Info:

```
 cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.7-29"
VERSION_ID="v1.99.7-29-ga20607b"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.7-29"
BUILD_ID="v1.99.7"

```

Test Procedure:

1. HOST OS should be running before the error injection.
2. Inject below error through BMC cronus setup

 
```

getscom pu.c 20010A40 -all
putscom pu.ex 20010A40 4000000000000000 -n0 -p0 -cft

```

FFDC, ESEL< journal, dmesg logs are attached

[esel.out.txt](https://github.com/openbmc/openbmc/files/1097696/esel.out.txt)
[witherspoon_dmesg.txt](https://github.com/openbmc/openbmc/files/1097698/witherspoon_dmesg.txt)
[witherspoon_journal.txt](https://github.com/openbmc/openbmc/files/1097701/witherspoon_journal.txt)
[20170623065240480930_MyFFDCLogs.zip](https://github.com/openbmc/openbmc/files/1097702/20170623065240480930_MyFFDCLogs.zip)

**Comment by geissonator** [comment]
The BMC is not involved in checkstop analysis and callout.  My understanding is this function from OCC/Hostboot will not be available until after 7/1.
