### ISSUE TITLE
Fan Control: Add sensor 'Scale' property support

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#1839]
Each sensor includes a 'Scale' property that needs to be investigated & taken into account for accurately reflecting the sensor's value. This also allows the user to define each event with the "human readable" values. i.e.) Ambient temp sensor - Value = 22800, Scale = -3 --> 22.800 degC

**Comment by msbarth** [comment]
- [ ] Add reading the 'Scale' property for each sensor object
- [ ] Apply 'Scale' value against the sensor 'Value' value when storing the property

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/97
