### ISSUE TITLE
PNOR: Dynamicall set size of read-only partition via file size

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1840]
The read-only partition is hardcoded to 32MB (to fit the 20MB witherspoon squashfs pnor image). But in systems with 32MB pnor chips like Palmetto, this partition size is too big and the volume can't be created, the pnor squashfs for palmetto is ~12MB so a much smaller volume can be created.

Pass the desired size via a recipe append so that the size can be set in a per-system basis.

**Comment by mdmillerii** [comment]
Can we just use the size of the mtd partition?

**Comment by anoo1** [comment]
Per conversation with Milton, use the squashfs file size to set the partition size.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7184> Dynamically set size of pnor read-only partition
Resolves  #1840 PNOR: Dynamicall set size of read-only partition via file size
