### ISSUE TITLE
PNOR: Remove the BlocksTransition object when activation completes

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1841]
With some recent changes in the Set Activation function, the BlocksTransition are not being removed anymore because when the sdbusplus function is being called instead of the override.

Need to ensure the BlocksTransition is removed when the activation completes on both pnor and bmc updaters.

**Comment by saqibkh** [comment]
change for PNOR: https://gerrit.openbmc-project.xyz/#/c/4961/

Change for BMC is not possible at this point since the logic for code update is not in place.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4961> PNOR: Remove the BlocksTransition object when activation completes
Resolves  #1841 PNOR: BMC: Remove the BlocksTransition object when activation completes
