### ISSUE TITLE
BMC: Create Manifest file and add it to the <system>.tar image

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1842]
Generate a Manifest file for the BMC that includes the purpose and version, and package it with the other image-* files in the <system>.tar

**Comment by lgon** [comment]
**TASKLIST**
- [ ] Generate Manifest file that includes purpose and version.
- [ ] Package Manifest file with the other image-* files in the .tar.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5473> overlay: Add MANIFEST to tar files
Resolves:  #1842 BMC: Create Manifest file and add it to the <system>.tar image
