### ISSUE TITLE
PNOR: Discover activated images and create (restore) their version dbus objects on BMC reboot

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1846]

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5355> PNOR: Restore version and activation dbus objects on BMC reboot.
Resolves  #1846 PNOR: Discover activated images and create (restore) their version dbus objects on BMC reboot

**Comment by saqibkh** [comment]
# **STATUS**

July 19:
Addressed all code review comments. Pushed a new patch on gerrit
