### ISSUE TITLE
PNOR: Version activation shouldn't be implemented until the next reboot

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#1847]
During activation check for power on. If the Host is up then wait for the next reboot to switch to user requested activation version.

**Comment by saqibkh** [comment]
- [ ] If Host is up then create/copy the files to the required dir, but wait to switch to user requested activation version.
- [ ]  If Host is down, then create/copy the files to required dir and switch to user requested activation version.

**Comment by geissonator** [comment]
Need to handle reset/reload - go back to previous image

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5336> PNOR: Version activation shouldn't be implemented until the Host is powered down.
Resolves  #1847 PNOR: Version activation shouldn't be implemented until the next reboot
