### ISSUE TITLE
DCMI : Identification function : Implement Management Controller ID

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1855]
Implement the ability to set and get the Management Controller ID (or hostname).

**Comment by tomjoseph83** [comment]
DCMI Specification Link
https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/dcmi-v1-5-rev-spec.pdf

This involves the implementation of the Get/Set Management Controller identifier String command.

The management controller identifier string needs to be updated to the HostName property implemented by the SystemConfiguration.interface.yaml

https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Network/SystemConfiguration.interface.yaml

**Comment by stamerlan** [comment]
Hello,

Could you please review https://gerrit.openbmc-project.xyz/#/c/6044/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6044> Add DCMI Get/Set Management Controller Id String
Resolves:  #1855 DCMI : Identification function : Implement Management Controller ID
