### ISSUE TITLE
List of information that can be displayed without login

### ISSUE THREAD

**Issue by iftekharuli** [openbmc/openbmc#1857]
Our current login page for the GUI looks like the following image. Before they login, we planned to display some basic information. For now, we are thinking the following- 

- Server firmware level
- Hostname (need clarification)
- Server model
- Server power state

If any of these will raise security concern or any other issue, we are open for discussion. 

![screen shot 2017-06-27 at 11 21 35 am](https://user-images.githubusercontent.com/4976631/27598642-be4956f0-5b2b-11e7-9e57-80c458028829.png)

**Comment by iftekharuli** [comment]
We decided to use Hostname :)

**Comment by geissonator** [comment]
Looks fine to me
