### ISSUE TITLE
TESTING: OCC Powercap bad path not posting https 40x

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#186]
The test_occ_powercap.robot suite is failing on a palmetto.  In two tests "Set More Than Maximum PowerCAP"  and "Set Less Than Minimum PowerCAP" the user is forcing the code down a bad path and yet the HTTP response is 200.  This is wrong and should be fixed. 

/org/openbmc/sensors/host/PowerCap/action/setValue 
It was setting it to 1000 when the minpower cap read was 1100.  This should have been an HTTP of invalid parms.

**Comment by adamliyi** [comment]
Fixed in PR: https://github.com/openbmc/skeleton/pull/50
When setting an invalid powercap value, a dub Exception will be returned:
E.g, a test on Barreleye (should be same on Palmetto):

 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST -d "{\"data\": [ 1900 ]}"  https://9.3.23.24/org/openbmc/sensors/hot/PowerCap/action/setValue
{
  "data": {
    "description": "Internal Server Error",
    "exception": "DBusException('Set PowerCap error: check value range',)",
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 862, in _handle",
      "    return route.call(**args)",
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 1734, in wrapper",
      "    rv = callback(*a, **ka)",
      "  File \"/usr/sbin/obmc-rest\", line 569, in __call__",
      "    return self.callback(*a, **kw)",
      "  File \"/usr/sbin/obmc-rest\", line 657, in wrap",
      "    resp = { 'data': callback(*a, **kw) }",
      "  File \"/usr/sbin/obmc-rest\", line 622, in wrap",
      "    return callback(*a, **kw)",
      "  File \"/usr/sbin/obmc-rest\", line 646, in wrap",
      "    return callback(*a, **kw)",
      "  File \"/usr/sbin/obmc-rest\", line 79, in __call__",
      "    return getattr(self, 'do_' + request.method.lower())(**kw)",
      "  File \"/usr/sbin/obmc-rest\", line 240, in do_post",
      "    return request.route_data['method'](*request.parameter_list)",
      "  File \"/usr/lib/python2.7/site-packages/dbus/proxies.py\", line 145, in __call__",
      "    **keywords)",
      "  File \"/usr/lib/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking",
      "    message, timeout)",
      "DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Set PowerCap error: check value range"
    ]
  },
  "message": "500 Internal Server Error",
  "status": "error"
}
