### ISSUE TITLE
Add deglitch for power supply presence

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1862]
Setting the interval is a simple DT update (debounce-interval).  So this is a Witherspoon specific story - there is no plumbing in the Phosphor layer for configuring this.

For Witherspoon, the exact interval is not clear, and the interaction with the Witherspoon power supply monitoring application may prevent use of a longer interval.

**Comment by bradbishop** [comment]
Kicking to phase 6.

**Comment by spinler** [comment]
Everything seems to work OK without this.  Going to close for now and will only reopen if we see a problem.
