### ISSUE TITLE
MBOXD:- Add more test cases in the unit test code for create read window.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1868]

**Comment by amboar** [comment]
Please provide more information, for example why the current testing is insufficient and how you propose to resolve that.

**Comment by amboar** [comment]
Also, whether or not your proposed tests are specific to the extra functionality in phosphor-mboxd, or if they're general and should be included in the upstream mboxbridge repository.

**Comment by amboar** [comment]
Similar to #2071, so closing.
