### ISSUE TITLE
Witherspoon: After code update boot progress is failing

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#1874]
Boot progress is always off after code update to build 858.

obmcutil bootprogress
units =
value = Off
error = 0

Details:
Linux witherspoon 4.10.17-9e95993e2d6edc68af5ca3f2345789e0f450d0db #1 Wed Jun 28 17:24:02 UTC 2017 armv6l GNU/Linux

Version details:
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.7-66"
VERSION_ID="v1.99.7-66-g9910bce"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.7-66"
BUILD_ID="v1.99.7"

pnor:
open-power-witherspoon-v1.17-99-g201e532-dirty
        buildroot-2017.02.2-7-g23118ce
        skiboot-5.6.0-158-ga1e0a047b2a0
        hostboot-31d0974
        linux-4.11.6-openpower1-p3654e00
        petitboot-v1.4.3-pb1c761f
        machine-xml-d0f86cf
        occ-1dc97a6
        hostboot-binaries-711147e
        capp-ucode-9c73e9f
        sbe-0df81aa

Pls find attached logs for the same
[journallog.txt](https://github.com/openbmc/openbmc/files/1111187/journallog.txt)

**Comment by sivassrr** [comment]
@prkatti1 journal log showing as Palmetto..
Please double check. Please reopen if we able to recreate. 

Today's driver it worked well. So I am closing this.
