### ISSUE TITLE
hwmon driver for PMBUS Power Supply

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1883]
Add powerN_input sensors for PMBUS power supply.

**Comment by geissonator** [comment]
Needs task list when ready to work on

**Comment by zahrens** [comment]
@eddiejames Do you have the task list?

**Comment by eddiejames** [comment]
- [ ] Investigate pmbus interface
- [ ] Create power supply (p17531) driver shell using pmbus and set up to export input power
- [ ] Test it.

**Comment by bjwyman** [comment]
P17531 refers to a power supply specification document revision. I believe driver was renamed to ibmps.

**Comment by geissonator** [comment]
Merged into openbmc kernel

**Comment by bjwyman** [comment]
https://github.com/openbmc/openbmc/commit/83a4307ecef9a5451af4f46ca3f84c1b45d9cd1b

**Comment by mdmillerii** [comment]
>  I believe driver was renamed to ibmps.

And later renamed again to "IBM Common Form Factor power supply" (compatible `ibm,cffps1`).
