### ISSUE TITLE
Expose sysfs attrs for PMBUS power supply

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#1884]
writeable clear faults
readable errors

**Comment by eddiejames** [comment]
- [ ] Create writeable clear_faults sysfs entry and status sysfs entries under I2C device.
- [ ] Obtain additional p17531 status registers over I2C
- [ ] Test it.

**Comment by eddiejames** [comment]
## Status: July 18, 2017
PSU doesn't seem to provide correct smbus packet error checking byte, so I'm getting I2C errors. However, Guenter indicated that userspace should just get these attributes with the i2c ioctl interface.
