### ISSUE TITLE
REST Post method unable to handle BYTE data

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#1889]
Need support for POST method to handle BYTE data

**Comment by sivassrr** [comment]
Any update here.

**Comment by sivassrr** [comment]
Currently we are testing it using 3000 port - This may not be available for GA, I guess. 
So we need to get this ASAP.

**Comment by prkatti1** [comment]
@sivassrr Since IP address configuration, prefix length and network gateway scenarios coupled with this, All the scenarios involving configuring IP address, prefix length and configuring gateway IP address are blocked. This count will be around 35 tests.

**Comment by sivassrr** [comment]
Thank you @prkatti1 for updating it. Working with development team and getting right focus here.

**Comment by ratagupt** [comment]
*# STATUS

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5813> Convert value to expected type during POST method
Resolves  #1889 REST Post method unable to handle BYTE data
