### ISSUE TITLE
The curl call for sensor name is case-sensitive

### ISSUE THREAD

**Issue by yadron** [openbmc/openbmc#1891]
The curl call of sensor name is case-sensitive.

So these two are different commands:

```
curl -b cjar -k https://172.17.27.68/org/openbmc/sensors/temperatur/INLet_Temp1

curl -b cjar -k https://172.17.27.68/org/openbmc/sensors/temperatur/INlet_Temp1
```

We've renamed this sensor in config some days ago, so detected this as result.

I think that this is a bug and sensor name should not be case-sensitive (at least when fetching using RestAPI/curl)

Currently if using incorrect name, then the result:
```

curl -b cjar -k https://172.17.27.90/org/openbmc/sensors/temperature/INLet_Temp2
{
  "data": {
    "description": "org.freedesktop.DBus.Error.FileNotFound: path or object not found: /org/openbmc/sensors/temperature/INLet_Temp2"
  }, 
  "message": "404 Not Found", 
  "status": "error" }
```

I know that the new correct naming is xyz instead of org, but it doesn't work  yet apart from two sensors (see https://github.com/openbmc/openbmc/issues/1870 ), so simpler talking about working example (I think that this is the same for xyz too).

**Comment by williamspatrick** [comment]
@bradbishop - Want you to comment with your thoughts on this, not necessarily do it.
@yadron - Is this something your team could help implement?
