### ISSUE TITLE
[xCAT] Require the ability to set VLAN tagging configuration in-band using ipmitool

### ISSUE THREAD

**Issue by whowutwut** [openbmc/openbmc#1899]
Looking for the ability to set VLAN tag on the OpenBMC `eth0` using inband ipmitool. 

The command that we are looking to be able to execute is: `ipmitool -d 0 lan set 1 vlan id <ID>`

@bradbishop Please add this to #1880 
Priority: High

**Comment by whowutwut** [comment]
@bradbishop and @ratagupt  Just making sure that it's clear inband is the primary focus, then out of band later on, if that separation is able to be done in the code.

**Comment by williamspatrick** [comment]
The "out-of-band" is free, because we always define the DBus objects first and the REST API comes through introspection.  We have to do that part first anyhow.  The IPMI provider is then done second and with that we get both in-band and out-of-band IPMI support.

**Comment by ratagupt** [comment]
Can we mark this issue as enhancement?

**Comment by ratagupt** [comment]
- [ ] Implement the Dbus Object Implementing VLAN.interface.

- [ ] Define the create interface for VLAN.

- [ ] Implement the create interface for VLAN.

- [ ] Write the VLAN configuration in the systemd.networkd.

- [ ] Create the VLAN interfaces as a child object of Network Manager.

- [ ] Write the test cases to verify that VLAN configuration have been written.

**Comment by ratagupt** [comment]
Update:- Worked with victor to get the VLAN setup.

**Comment by whowutwut** [comment]
@ratagupt  I tried to set up the USB to serial on another node in the frame...  give that a shot and let me know if you can access the BMC.

**Comment by ratagupt** [comment]
@whowutwut : I needed for openbmc machine.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5635> Add support for vlan(set lan command)
Resolves  #1899 [xCAT] Require the ability to set VLAN tagging configuration in-band using ipmitool
