### ISSUE TITLE
Networkd:- Write a new app which monitors the address change event.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#1903]
Trigger could be 

1) Interface up/down.
2) Link up/down
3) DHCP lease renegotiation 

We need to explore that do we need to listen on RTNETLINK address change event or systemd gets us some dbus signal for address change.

On getting of IPaddress chnage event we need to refresh the ipadress dbus object on the ethernet interface.

**Comment by geissonator** [comment]
Done in #2171 @ratagupt ?

**Comment by ratagupt** [comment]
@geissonator :- we can close this one.

**Comment by dkodihal** [comment]
Fully done via #2171.
