### ISSUE TITLE
Zaius : Need host checkstop detection support

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/openbmc#1905]
In Witherspoon, a GPIO gets asserted at checkstop, which is monitored by a process sitting in BMC ( phosphor-gpio-monitor ). Need this GPIO assertion support implemented in Zaius so that we can enable checkstop monitoring.

https://gerrit.openbmc-project.xyz/#/c/3568/ implemented GPIO monitor function for WItherspoon.

**Comment by GHF** [comment]
Please assign to me.

**Comment by GHF** [comment]
Waiting for ack and review for https://patchwork.ozlabs.org/patch/787989/ so that the kernel emits the necessary key code.
