### ISSUE TITLE
Upstream: Expose extra aspeed2[45]xx watchdog configurations 

### ISSUE THREAD

**Issue by rfrandse** [openbmc/openbmc#1906]
Tracking community, ltc should be merging soon. 
Originating issue: https://github.com/openbmc/openbmc/issues/1636

**Comment by cbostic** [comment]
++++++++++++++++++++++++++++++++++++++
#STATUS

8/15
Today: patch 1/2 is approved now.   Just received Reviewed-by: Guenter Roeck <linux@roeck-us.net>   Previously received an 'Acked-by' Rob Herring.   Guenter also approved Patch 2/2 last night.
Next: Still waiting on an 'Acked-by' for patch 2/2.
Blockers: None

++++++++++++++++++++++++++++++++++++++

**Comment by rfrandse** [comment]
In kernel stream
