### ISSUE TITLE
Restarting the org.open_power.Occ.Control service after inventory created will not work 

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1911]
The creation of the CPU0/1 inventory objects is what triggers the creation of the OCC control dbus objects.  If you have to restart the occ control service after the inventory objects are created, we'll never create the control objects.

When instantiating the occ control manager object, we should probably check for the inventory items and just call the cpuCreated() interface directly if they're available.

**Comment by geissonator** [comment]
FYI - @dkodihal @vishwabmc

**Comment by dkodihal** [comment]
I was going to fix the same problem via #1824, so this is a dup.
