### ISSUE TITLE
Software Version disappears after RequestedActivation is set to Active

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#1917]
Software Version seems to disappear after an image is set to "Active".
I can view the versionId with its objects (Activation, RequestedActivation, Path, Version etc) from <BMCIP:3000> but it doesn't show up through the REST command.

--------------------------------------------------------------------------------------------------------------
Before the code update
-bash-4.1$ ./rest_cmd -i 9.3.29.119 -o GET -u /xyz/openbmc_project/software/enumerate
Executing: GET  /xyz/openbmc_project/software/enumerate

/xyz/openbmc_project/software/enumerate
{
    "/xyz/openbmc_project/software/18867d68": {
        "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active",
        "Path": "",
        "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC",
        "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None",
        "Version": "v1.99.7-66-g9910bce"
    },
    "/xyz/openbmc_project/software/944a0717": {
        "Activation": "xyz.openbmc_project.Software.Activation.Activations.Ready",
        "ExtendedVersion": "buildroot-2017.02.2-7-g23118ce,skiboot-f0ebbc8,hostboot-56a7aab,linux-4.11-openpower1-pd4d4971,witherspoon-xml-cee25d2-pac01485,occ-43b9907,hostboot-binaries-8cbbc67,capp-ucode-9c73e9f,sbe-9b98de3-p43ac507",
        "Path": "/tmp/images/944a0717",
        "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.Host",
        "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None",
        "Version": "open-power-witherspoon-v1.16-53-gfb396b3-dirty"
    },
    "/xyz/openbmc_project/software/98059035": {
        "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active",
        "ExtendedVersion": "buildroot-2017.02.2-7-g23118ce,skiboot-f0ebbc8,hostboot-56a7aab,linux-4.11-openpower1-pd4d4971,witherspoon-xml-cee25d2-pac01485,occ-43b9907,hostboot-binaries-8cbbc67,capp-ucode-9c73e9f,sbe-9b98de3-p43ac507",
        "Path": "",
        "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.Host",
        "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None",
        "Version": "open-power-witherspoon-v1.16-53-aaaa96b5"
    }
}

---------------------------------------------------------------------------------------------------
After the "RequestedActivation" object for version 944a0717 is set to "Active", the version disappears from the list.

-bash-4.1$ ./rest_cmd -i 9.3.29.119 -o GET -u /xyz/openbmc_project/software/enumerate
Executing: GET  /xyz/openbmc_project/software/enumerate

/xyz/openbmc_project/software/enumerate
{
    "/xyz/openbmc_project/software/18867d68": {
        "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active",
        "Path": "",
        "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC",
        "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None",
        "Version": "v1.99.7-66-g9910bce"
    },
    "/xyz/openbmc_project/software/98059035": {
        "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active",
        "ExtendedVersion": "buildroot-2017.02.2-7-g23118ce,skiboot-f0ebbc8,hostboot-56a7aab,linux-4.11-openpower1-pd4d4971,witherspoon-xml-cee25d2-pac01485,occ-43b9907,hostboot-binaries-8cbbc67,capp-ucode-9c73e9f,sbe-9b98de3-p43ac507",
        "Path": "",
        "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.Host",
        "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None",
        "Version": "open-power-witherspoon-v1.16-53-aaaa96b5"
    }
}

--------------------------------------------------------------------------------------------------------------

I checked the journal and there is absolutely noting to reflect this apart from the POST command to request the "RequestedActivation" change to "Active".

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/5346 Call emit_interfaces signal for temporary interfaces
Resolves openbmc/openbmc#1917
