### ISSUE TITLE
OP910:OPRAS:Witherspoon: No Call out logged on errors associated with eSEL corresponding to L2 Directory CE

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1920]

**Comment by geissonator** [comment]
Need task list for review

**Comment by tomjoseph83** [comment]
- [ ] Host error log should inherit callout metadata

- [ ] Invoke generated code to find mapping between sensor and inventory object

- [ ] Log callout information along with host error log

**Comment by tomjoseph83** [comment]
No progress, tasks broken down.

**Comment by tomjoseph83** [comment]
https://gerrit.openbmc-project.xyz/#/q/topic:1920

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5453> Add inventory path metadata to host event log entry
Resolves  #1920 OP910:OPRAS:Witherspoon: No Call out logged on errors associated with eSEL corresponding to L2 Directory CE
