### ISSUE TITLE
IPMI FRU : non-host inventory

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1931]
#1559 and #1560 make it possible to map host inventory to IPMI FRUs. This story is to map non-host (BMC inventory) to IPMI FRUs.

**Comment by devenrao** [comment]
- [ ] Create config file for non host inventory items

- [ ] Add native recipe that consumes non host inventory config file and generates fru config file by executing gen_ipmi_fru perl script
fd

- [ ] Generate fru details by consuming non host config yaml file and append to existing C header file

- [ ] Make changes to IPMI fru read code to cater for non host inventory items

**Comment by geissonator** [comment]
Need story in 2.1 backlog for using MRW, for this story we'll hand code file for witherspoon.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5542> openpower - cater for generating FRU map for non host FRU's
Resolves  #1931 IPMI FRU : non-host inventory
