### ISSUE TITLE
BMC: Build: Remove the initramfs from the kernel fit image

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1935]

**Comment by williamspatrick** [comment]
### STATUS

7/21 - Played with this a bit today and was able to hack at it enough to boot up with a RO filesystem.  Need to clean it up and make it a selectable option.

```root@romulus:~# mount
/dev/mtdblock4 on / type squashfs (ro,relatime)```

**Comment by williamspatrick** [comment]
This is up in Gerrit and Brad gave it a first pass review, so I think we're in good shape for getting this done by Wed for last sprint.  https://gerrit.openbmc-project.xyz/#/c/5585/1

**Comment by williamspatrick** [comment]
Merged.
