### ISSUE TITLE
BMC: Split u-boot env into 2 copies

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1937]

**Comment by mdmillerii** [comment]
Define env as two (redundant) environment copies each one 64k nor sector so one will always be valid even when erasing and writing the other.  For dual flash systems each flash will have a u-boot and pair of environment regions.

**Comment by geissonator** [comment]
Need task list, Eddie to talk with Milton (hopefully mostly a uboot config change)

**Comment by eddiejames** [comment]
- [ ] Modify u-boot AST config for redundancy.
- [ ] Define redundant chunks in the fw_env config.
- [ ] Make sure everything works.

**Comment by eddiejames** [comment]
## Status: July 13, 2017
Discovered how to edit u-boot redundancy config, and enabled it. Tested this on Barreleye with a variety of settings. Still need to test on Witherspoon and make sure shutdown script can be safely modified.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5312> Add u-boot redundant environments.
Resolves  #1937 BMC: Split u-boot env into 2 copies
