### ISSUE TITLE
BMC: Reduce shutdown watchdog value back to default

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1938]
The BMC code update won't be executed during shutdown anymore, so we can decrease back the watchdog timer.

This appears to be the commit that increased the timeout, which would need to be reverted.
https://github.com/openbmc/openbmc/commit/45af9a22aabf38474a00698f511e334c14d84c76

**Comment by charleshofer** [comment]
I was able to build an OpenBMC image with the proper and deploy it to a Witherspoon system. The deployment went fine, but did not produce the expected changes.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5342> Revert "systemd: Configure shutdown watchdog to 20min" Resolves openbmc/openbmc#1938
Resolves  #1938 BMC: Reduce shutdown watchdog value back to default
