### ISSUE TITLE
BMC: Determine if there's still an issue with erase of boot env

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1939]
Per Milton, writing env variables was causing the erase to not write correctly, so on the update script (obmc-update.sh) he has a workaround to copy out the variables and write them back. Need to check if there's still an issue, and if yes, figure out a solution for the new implementation of the bmc code update.

**Comment by spinler** [comment]
@mdmillerii Anything you can elaborate on here?

**Comment by geissonator** [comment]
Needs some discussion and task list before we can commit.

**Comment by spinler** [comment]
I spoke with @eddiejames, and he said some 4.10 mtd updates negated the need for this.

He's removing the code in obmc-shutdown.sh to restore the env vars from /run/fw_env with https://gerrit.openbmc-project.xyz/#/c/5312

**Comment by spinler** [comment]
Closing this as investigation is done and there is no further work to do.
