### ISSUE TITLE
BMC: Build: Create flash-able image with a static layout

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1941]

**Comment by geissonator** [comment]
Needs task list

**Comment by bradbishop** [comment]
# **STATUS**
7/13 - No progress

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5801> images: Add support for generating ubi images
Resolves:  #1941 BMC: Build: Create flash-able image with a static layout
