### ISSUE TITLE
BMC: Change primary and alt BMC layout to just have u-boot, boot env, and a ubi mtd

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1942]
Change for witherspoon first, with a feature to enable/disable the new layout to allow testing until all the pieces for BMC code update are complete.

**Comment by maksymko** [comment]
I think U-Boot env can also be in UBI partition.

**Comment by mdmillerii** [comment]
It can read its environment from an ubi volume, but support is read only and only one ubi container can be accessed, which would make try there times then fall back to a known image difficult or impossible from env and alternate boot images on different flash devices with separate ubi space difficult.

**Comment by eddiejames** [comment]
- [ ] Modify partition definition in device tree.
- [ ] Enable new partitions for Witherspoon only
- [ ] Create a means of selecting whether or not to use the new partitions.

**Comment by eddiejames** [comment]
07/12: Modified partition definitions. Did some research on uboot and investigated how the OpenBMC filesystem works as a whole.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5316> kernel: Patch in bmc flash partition changes
Resolves  #1942 BMC: Change primary and alt BMC layout to just have u-boot, boot env, and a ubi mtd
