### ISSUE TITLE
BMC: Block BMC reboot during u-boot update

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1944]
Add a BlocksTransition dependency to the BMC reboot target during u-boot update so that BMC is prevented from being rebooted and corrupting u-boot.

**Comment by saqibkh** [comment]
- [ ]  Create service files that can disable BMC transtition through reboot, shutdown, halt etc.
- [ ]  Call Enable reboot halt services when ActivationBlockTransition object is created.
- [ ]  Call Disable reboot halt services inside ActivationBlockTransition destructor.

Status:
May 11: 
- Discussed possible implementations with Andrew, Adriana and Patrick.
- Created service files and add added the logic to ActivationBlocksTransition class inside 
  phosphor-bmc-code-mgmt.

**Comment by geissonator** [comment]
Needs more investigation

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5266> BMC: Block BMC reboor during code update
Resolves  #1944 BMC: Block BMC reboot during u-boot update

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5266> BMC: Block BMC reboot during code update
Resolves  #1944 BMC: Block BMC reboot during u-boot update

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6613> BMC: Block BMC reboots during Code Update
Resolves  #1944 BMC: Block BMC reboot during u-boot update

**Comment by geissonator** [comment]
Lets get yocto updated to 2.4, and see if the new systemd provides the function we need.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6613> BMC: Block BMC reboots during Code Update
Resolves  #1944 BMC: Block BMC reboot during u-boot update

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6613> BMC: Block BMC reboots during Code Update
Resolves  #1944 BMC: Block BMC reboot during u-boot update
