### ISSUE TITLE
DCMI: Implement Power Limit commands

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1955]
Implement get/set power limit.
Implement enable/disable power limit setting.

**Comment by tomjoseph83** [comment]
- [ ]  Get Power Limit Command

- [ ]  Set Power Limit Command

- [ ]  Activate/Deactivate Power Limit command

**Comment by tomjoseph83** [comment]
https://gerrit.openbmc-project.xyz/#/q/topic:1955

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5547> dcmi: Implement activate/deactivate power limit
Resolves  #1955 DCMI: Implement Power Limit commands
