### ISSUE TITLE
Increase VDDR voltage setpoint for Witherspoon

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#1959]

**Comment by geissonator** [comment]
- [ ] Rename avs workaround script to power workarounds
- [ ] Update script with desired commands from power team (memory volt increase)
- [ ] Update script with desired commands from power team (vdn volt decrease)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5617> Decrease VDN to .8v for power on
Resolves  #1959 Increase VDDR voltage setpoint for Witherspoon

**Comment by rkgebhardt** [comment]
The VDDR rail on Witherspoon is still running at the old level (1.21v) on build 1734B:  ibm-v1.99.8-98-g06734f31-r3
Jordan Keuseman has given me the i2cset commands to use as a workaround.  These do move the VDDR set point to 1.23v, but it does not change the nominal voltages to match those.  This shows up in the  Converged Firmware Toolkit command: mfgcommand -m vapi with the -r (read) and -s (set) commands.  To be able to set the voltage by percentage the nominal voltage for VDDR must be 1.23v.   Is there anything holding this up?
