### ISSUE TITLE
phosphor-objmgr: No documentation for new required args

### ISSUE THREAD

**Issue by mdmillerii** [openbmc/openbmc#1962]
In #1767, new required args were added in openbmc/phosphor-objmgr@cb2e1b308c51036667766a7d6b9b288399470b99 but the only hint how to run this is in the change log.

The description for these new required arguments should be either in documentation or at least as help= attributes in the python help so that when the command fails someone can have a clue where to look without searching git history to find this commit.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/106
