### ISSUE TITLE
External Event Notification

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1966]
Track all work required to allow external applications to register for event notification and then be notified of those events.  

Some notes:
- Plan is some mechanism to subscribe to dbus events to send up to REST web socket
  - Something similar was done on Barreleye (but never merged)
  - Implementation was single direction (not bi-directional)
- external app would connect, and say the things it wants to know about
  - bmc would then send requested alerts over the socket
- Redfish has some alert-like function coming

Build on top of what comes out of #1856 

The MRW indicates sensors of interest and their thresholds.  We need to use the MRW data to know which alerts to bubble up.

**Comment by geissonator** [comment]
Moving to 5.1, critical for some

**Comment by bradbishop** [comment]
Some example code: 

https://bottlepy.org/docs/dev/async.html#finally-websockets
