### ISSUE TITLE
Rebuild Dump Entry D-bus objects  during reboot.

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#1969]
- [ ] Provide Interface in Dump manager to rebuild dump entry's from persistent location during phosphor-dump-manager application start time.

- [ ] Update dump entry ID in dump manager.
     Two approaches here , 
     1. Based on available entry  objects in the persistent location. 
      2.Persist dump entry id using BMC  Settings infrastructure?
  Need discussion on this.

**Comment by dkodihal** [comment]
Implemented alongwith #1506.
