### ISSUE TITLE
Add debug tools for sdbus in to our environment 

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#197]
https://github.com/systemd/systemd/blob/16a798deb3b560f8b27848fe292a76b362c0b581/src/libsystemd/sd-bus/bus-dump.c#L63

That is a pretty powerful debug tool.  Unfortunately it is not available for our project (or any other from what I understand).  I'd like the capability in our environment.  I think tools like bus-dump would be helpful when you are trying to test out your code.  How many references exist?  What is the format of the message?

**Comment by williamspatrick** [comment]
Will this be necessary when we have a c++ binding in place?  I'm not sure what the scope of this is.

The API pointed at appears to be internal to systemd.
