### ISSUE TITLE
mboxd: investigate libflash

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#1973]
Investigate if skiboot/libflash code can be employed to simplify some of the PNOR partition code.

**Comment by cyrilbur-ibm** [comment]
Hi @dkodihal,

Some time ago I wrote a basic implementation for libflash to what I believe the openbmc people are trying to do, hopefully it can help.

I've recently revisited it and gone through and fixed somethings up, I'm actually interested to see if the interface is useful and if there are any more bugs I haven't caught.

Thanks,

Cyril

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/135
