### ISSUE TITLE
BMC: Support for booting on the alternate BMC chip

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1974]
Issue to discuss the needed pieces to support booting from the alternate BMC chip.

Possibly topics include:
1. Need to find where to clear the alternate boot chip select override. Also clearing the watchdog.
2. Get u-boot support to access the alternate bmc chip (chip select 0 and 1).
3. There's only one copy of rwfs, if bmc chip is replaced, the rwfs copy would be lost (is this a RAS issue)

**Comment by geissonator** [comment]
Notes from design:
- We put rootfs in both primary and alternate bmc chip.  uboot always boots from kernel in primary bmc chip, it can then mount the alternate chip when needed and boot from that
- First priority is to mount rw filesystem, different story from @anoo1 , put this one in actual

**Comment by anoo1** [comment]
After further discussion about the watchdog behavior, closing this story.
Chris will follow up on submitting some kernel patches that Milton has, and sending a device tree proposal to the mailing list.
