### ISSUE TITLE
sdbusplus: object: Use "interfaces_removed" instead of "object_removed"

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1975]
When an object is destroyed, it emits an "object_removed" signal that causes all the interfaces on that dbus object to be removed.

To support individual interfaces that can be added and removed on demand to a dbus object, need to support "interfaces_removed" signal instead.

**Comment by geissonator** [comment]
@anoo1 - phase 6 or 7 on this?  i.e. nice to have or required for something?

**Comment by bradbishop** [comment]
@anoo1 does this commit provide the necessary function?

https://github.com/openbmc/sdbusplus/commit/d294557acbb16cff564834d669e68b5a5fecd724

**Comment by anoo1** [comment]
Per Brad, this won't be done.
