### ISSUE TITLE
REST call failure due to "SSL connect error"

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#1978]
Driver Info:
=========
root@witherspoon:# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.8-23"
VERSION_ID="v1.99.8-23-g2ad7ce3"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.8-23"
BUILD_ID="v1.99.8"
root@witherspoon:#

root@witherspoon:# cat /etc/timestamp
20170718013103

Problem Description
------------------------
curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://<SystemName>/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"
curl: (35) SSL connect error

root@witherspoon:# ls -al /proc/*/fd/ | wc -l
ls: /proc/14334/fd/3: cannot read link: No such file or directory
ls: /proc/self/fd/3: cannot read link: No such file or directory
ls: /proc/thread-self/fd/3: cannot read link: No such file or directory
2497
root@witherspoon:#

**Comment by gkeishin** [comment]
This is same as https://github.com/openbmc/openbmc/issues/1389  we can close this one

**Comment by sivassrr** [comment]
This happened immediately after code update, CI also failed.

**Comment by gkeishin** [comment]
So we will need the FFDC for this one.. and re-open then.. including the proc fd list output as well.
