### ISSUE TITLE
PNOR: Build: Add size of RW partitions to the Manifest

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1979]
Prereq: https://github.com/open-power/pnor/issues/71 , which would add the read-only flag to the read-only partitions.

The generate-squashfs script would calculate the space that the read-write partitions take, and add it to the Manifest file.
The pnor updater would then use that info to create an appropriate-sized read-write ubi volume.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/137
