### ISSUE TITLE
Prevent Delete on currently running version

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1986]
With #1550 , Delete is being implemented in the version object. Need to prevent deleting the currently running one.

For BMC, do not delete the kernel and rofs version pointed by the boot args.

**Comment by eddiejames** [comment]
Task List
- [] Remove version object delete method
- [] Add delete dynamically to versions that are not the current one
- [] Manage delete objects for switching versions

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6351> Add checks for currently running host image before erasing
Resolves  #1986 Prevent Delete on currently running version
