### ISSUE TITLE
Update 9552 LED names in MRW to match device tree

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#1987]
The driver prepends 'pca955x:' to the names, so the MRW will have to match that so the led code can find them.

**Comment by bjwyman** [comment]
See 1738 comment from Milton. Thinks label should be `pca955x:amber:fan0`.

**Comment by mdmillerii** [comment]
We also need to fix the directly attached leds to the naming format.

**Comment by spinler** [comment]
The latest MRW fails our builds because of some empty sensor ID fields on the GPU targets.  Have requested the owner to fix those, and then I can fix the LEDs.

**Comment by spinler** [comment]
For reasons I don't completely understand, the latest drivers don't even have the 'pca955x:' in sysfs anymore:
```
# ls /sys/class/leds/
fan0         fan1         fan2         fan3         front-fault  front-id     front-power  rear-fault   rear-id      rear-power
```

and all of the LEDs show up in D-Bus now.
I guess I will close this.

**Comment by mdmillerii** [comment]
That would be because they changed from the leds-pca955x driver to the leds-gpio driver.  It doesn't tack on the name.  It also can not support hardware blink and will rely on a kernel timer to change the led state.
