### ISSUE TITLE
Raspberrypi Build Fails with "phosphor-gpio-keys" file missing error

### ISSUE THREAD

**Issue by sambaranghosh** [openbmc/openbmc#1995]
Build fails with error. Can anyone help?

> ERROR: linux-raspberrypi-1_4.4.48+gitAUTOINC+7ddf96fbb7-r0 do_kernel_metadata: Function failed: do_kernel_metadata (log file is located at /home/sambaran/openbmc/build/tmp/work/raspberrypi3-openbmc-linux-gnueabi/linux-raspberrypi/1_4.4.48+gitAUTOINC+7ddf96fbb7-r0/temp/log.do_kernel_metadata.11326)
ERROR: Logfile of failure stored in: /home/sambaran/openbmc/build/tmp/work/raspberrypi3-openbmc-linux-gnueabi/linux-raspberrypi/1_4.4.48+gitAUTOINC+7ddf96fbb7-r0/temp/log.do_kernel_metadata.11326
Log data follows:
| DEBUG: Executing shell function do_kernel_metadata
| ERROR. input file "phosphor-gpio-keys" does not exist
| ERROR: could not process input files: /home/sambaran/openbmc/import-layers/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi/defconfig /home/sambaran/openbmc/import-layers/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi-4.4/0001-fix-dtbo-rules.patch phosphor-gpio-keys
|        See /tmp/tmp.a98YvU1MS2 for details
| ERROR. input file "phosphor-gpio-keys" does not exist
| ERROR: could not process input files: /home/sambaran/openbmc/import-layers/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi/defconfig /home/sambaran/openbmc/import-layers/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi-4.4/0001-fix-dtbo-rules.patch phosphor-gpio-keys
|        See /tmp/tmp.ZtehoVt3lm for details
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_kernel_metadata (log file is located at /home/sambaran/openbmc/build/tmp/work/raspberrypi3-openbmc-linux-gnueabi/linux-raspberrypi/1_4.4.48+gitAUTOINC+7ddf96fbb7-r0/temp/log.do_kernel_metadata.11326)
ERROR: Task (/home/sambaran/openbmc/import-layers/meta-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.4.bb:do_kernel_metadata) failed with exit code '1'

I initialised  TEMPLATECONF=meta-openbmc-machines/meta-evb/meta-evb-raspberrypi/conf . openbmc-env 
bitbake obmc-phosphor-image

**Comment by williamspatrick** [comment]
The Raspberrypi build was something someone added "for fun" pretty much and has never fully worked.  I don't think it was ever tested on a real piece of hardware.  So unless you're really interested in making it work, I would not invest much time in it.

It sounds like it is missing a kernel config file that we have added to the other machines:
```
$ git ls-files "*gpio-keys*"
meta-phosphor/common/recipes-kernel/linux/linux-obmc/phosphor-gpio-keys.cfg
meta-phosphor/common/recipes-kernel/linux/linux-obmc/phosphor-gpio-keys.scc
```
