### ISSUE TITLE
ItemUpdater: Implement Associations

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2007]
Implement the Associations and Active path as described in: https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software#itemupdater

The association implementation would be listening to the symlinks to be created/updated, and create the association to active based on that.

**Comment by gtmills** [comment]
- [ ] implement locally the Associations object in xyz namespace

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6288> Create active association
Resolves  #2007 ItemUpdater: Implement Associations
