### ISSUE TITLE
Reset Reload when Host running switches to Alt side

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#2015]
- [x] Boot the Host
- [x] Reset BMC 

BMC come up with the alt side on reset. This is pervasive on all newer master build

**Comment by eddiejames** [comment]
# **STATUS**
07/26 - Got a patch on the mailing list and in gerrit to fix this issue.

**Comment by amboar** [comment]
@eddiejames it's helpful to provide a link to the patch in comments like that. I'm curious, but not to the point of searching Gerrit for it :)

**Comment by gkeishin** [comment]
@amboar I think this is the one https://gerrit.openbmc-project.xyz/#/c/5578/

**Comment by geissonator** [comment]
Fixed
