### ISSUE TITLE
Systemd:- Upstream the changes for issue 1949

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2016]
https://github.com/openbmc/openbmc/issues/1949.

On systems where kernel is not configured with namespace support  then don't return error during setting up network namespace.

We could have configured the kernel with namespace support but by doing this it brings the unnecessary code which we don't want.

**Comment by gtmills** [comment]
@ratagupt We still need to upstream?

**Comment by bradbishop** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/15608/
