### ISSUE TITLE
witherspoon FA: Project/HPC/ Customer Requirements for  IPV4 MAC versus IPv6 addressing

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2018]

**Comment by rfrandse** [comment]
The question from originator is to  know whether the BMC must used MAC mode  (IPV4 - 12 byte addressing) or  IPv6 address format 

The defect was put into fixed verify state  with the comment
the Ethernet address is expected to be in the IPV4 format.  This should be compatible with the IBM manufacturing servers.

When the CQ defect was placed in to verify it opened this github.

**Comment by rfrandse** [comment]
No longer open
