### ISSUE TITLE
BMC: Implement Software ActivationProgress.interface

### ISSUE THREAD

**Issue by mtritz** [openbmc/openbmc#2030]
As in https://github.com/openbmc/openbmc/issues/1554, but on the BMC side. Requires prerequisite https://github.com/openbmc/openbmc/issues/2031

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5555> BMC Activation: Implement ActivationProgress interface
Resolves  #2030 BMC: Implement Software ActivationProgress.interface

**Comment by mtritz** [comment]
# **STATUS**
7/26: https://gerrit.openbmc-project.xyz/#/c/5555/ ready for review
