### ISSUE TITLE
[xCAT] How to get time zone information of BMC?

### ISSUE THREAD

**Issue by xuweibj** [openbmc/openbmc#2034]
Hi, I am working on getting log information.

```
'/xyz/openbmc_project/logging/entry/40' => {
                 'associations' => [],
                 'Timestamp' => '1501011776382',
                 'Resolved' => 0,
                 'Id' => 40,
                 'Message' => 'org.open_power.Host.Error.Checkstop',
                'Severity' => 'xyz.openbmc_project.Logging.Entry.Level.Error',
                'AdditionalData' => []
               }
```
 I saw that timestamp is ``Commit timestamp of the error event entry in milliseconds since 1970.``  I think we need to get time zone information to know what the exact time of log. 

How could I get it? Or will you provide other time format in the future?

**Comment by williamspatrick** [comment]
The BMC only operates in UTC.

**Comment by xuweibj** [comment]
OK, Thank you for your comments. I will close this issue.
