### ISSUE TITLE
PNOR image activation fails

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc#2036]
Image activation fails.

```
Jul 25 20:08:49 witherspoon daemon.info systemd[1]: Starting Attach the PNOR mtd device to UBI... 
Jul 25 20:08:49 witherspoon daemon.info obmc-flash-bios[1198]: ubiattach: error!: cannot attach mtd7 
Jul 25 20:08:49 witherspoon daemon.info obmc-flash-bios[1198]:            error 17 (File exists) 
Jul 25 20:08:50 witherspoon daemon.info obmc-flash-bios[1198]: /usr/sbin/obmc-flash-bios: error 255
```

Steps to replicate:
1. Build an image from https://gerrit.openbmc-project.xyz/#/c/5431/
2. Patch with https://gerrit.openbmc-project.xyz/#/c/5517/, or you can also do `scp /esw/san5/andrewg/mboxd root@<your bmc ip>:/usr/sbin/mboxd`
3. Update PNOR through the REST interface and the activation step should fail

**Comment by mdmillerii** [comment]
https://gerrit.openbmc-project.xyz/#/c/5409/3/meta-openbmc-machines/meta-openpower/common/recipes-phosphor/flash/openpower-software-manager/obmc-flash-bios

**Comment by mdmillerii** [comment]
... except that is the bmc version and this was the pnor version.
