### ISSUE TITLE
phosphor-logging should not use mapper on commit interface

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2039]
See #2029  Further discussion on this made us realize that because the commit interface is internal to phosphor-logging, it should not need to use mapper.

Also, how do we ensure applications that load libraries in have their dependencies set up correctly?  This one may need it's own issue.

**Comment by geissonator** [comment]
FYI @dkodihal @devenrao

**Comment by dkodihal** [comment]
@geissonator the logging server does not use it. The client lib does, because it runs in the client's process.

**Comment by geissonator** [comment]
Still, the client lib is tied directly to the server interface, so seems like we could skip mapper.

**Comment by bradbishop** [comment]
I still think this would be a good change to make.

**Comment by spinler** [comment]
I will take care of this.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35212

**Comment by geissonator** [comment]
Gerrit commit (https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-logging/+/35212) merged so good to close.
