### ISSUE TITLE
PNOR: Persist redundancy priorities

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#2040]
Image redundancy priorities need to persist through a bmc reset.

**Comment by mtritz** [comment]
- [ ] Store redundancy priority in the RW partition for each image.
- [ ] When restoring PNOR images upon reboot, read the priority from the RW partition.

**Comment by mtritz** [comment]
# **STATUS**
7/29: Code in Gerrit for review.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5634> PNOR: Restore RedundancyPriority on reset
Resolves  #2040 PNOR: Persist redundancy priorities
