### ISSUE TITLE
OpenBMC : FVT: Witherspoon : Unable to connect SOL session (inconsistent)

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2053]

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5667> sol: Handle deactivate payload correctly when session is closed
Resolves  #2053 OpenBMC : FVT: Witherspoon : Unable to connect SOL session (inconsistent)

**Comment by tomjoseph83** [comment]
# **STATUS**

8/7
Ready for merge review.
