### ISSUE TITLE
OpenBMC : FVT: Witherspoon : IPMI's get asset tag command not working

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2054]

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5686> Add extra_interfaces.d directory in yaml path
Resolves  #2054 OpenBMC : FVT: Witherspoon : IPMI's get asset tag command not working

**Comment by tomjoseph83** [comment]
# **STATUS**

8/7
Ready for merge review.
