### ISSUE TITLE
setPowerState method in org.openbmc.control.Power

### ISSUE THREAD

**Issue by yongli3** [openbmc/openbmc#2055]
I want to know if there is any service calls the setPowerState method in org.openbmc.control.Power?

It seems that the setPowerState is the key to power on the host, but I cannot find which service is using it

**Comment by geissonator** [comment]
@yongli3 - please take a look at https://github.com/openbmc/docs/blob/master/openbmc-systemd.md and https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/State.  Controlling the server boots and power on's goes through the xyz.openbmc_project.State.* interfaces.
