### ISSUE TITLE
Failed to mount PNOR RO and RW volumes after BMC code update

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#2062]
BMC code update deletes the directories inside /media/.
Therefore the obmc-flash-bios-ubiremount.service is unable to mount all ubi volumes after the system boots up. Therefore the service fails.

Need to add a check to create a mountdir if it doesn't exists.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5705> openpower-software-manager: Create a mount dir for ubi volumes.
Resolves  #2062 Failed to mount PNOR RO and RW volumes after BMC code update
