### ISSUE TITLE
Hostname edit or adding user defined name functionality in GUI

### ISSUE THREAD

**Issue by iftekharuli** [openbmc/openbmc#2063]
We have this edit button in the main server overview page where we plan to edit the existing hostname or have users to name servers to track the servers easily. We were wondering if this functionality will be in API soon. 

![screen shot 2017-08-01 at 1 07 06 pm](https://user-images.githubusercontent.com/4976631/28839999-22c306b2-76bb-11e7-9578-e1eb30f67b48.png)

![screen shot 2017-08-01 at 1 07 17 pm](https://user-images.githubusercontent.com/4976631/28840005-290c60c2-76bb-11e7-8572-da8920bbb951.png)

**Comment by gtmills** [comment]
This is done. https://gerrit.openbmc-project.xyz/#/c/10442/ was the commit for this work.
