### ISSUE TITLE
mboxd: Create vpnor copy_flash test case

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2071]
Create unit test case to test the read path using copy_flash.

**Comment by amboar** [comment]
Several tests have been added covering this functionality:

https://github.com/openbmc/phosphor-mboxd/commit/730e3b0409894112d1984fb26e2cfacf886f983c
https://github.com/openbmc/phosphor-mboxd/commit/2b73f172f048e5b232d2c8f7e78d74fd9f94dc67
https://github.com/openbmc/phosphor-mboxd/commit/3c9bb3e45ebc3a4892ba368ac9c8634d06cd152d
https://github.com/openbmc/phosphor-mboxd/commit/7eed6de0bdbb973091517343859e8e8dc030fd67
