### ISSUE TITLE
Make /media tmpfs

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2072]
The /media dir is where the ubi volumes are currently mounted. The rootfs will become RO with the bmc filesystem updates, so need to make /media a tmpfs so that dirs can be created. There may be a .bbapped that could get this done.

**Comment by lgon** [comment]
Related:  https://gerrit.openbmc-project.xyz/#/c/5705/2/meta-openbmc-machines/meta-openpower/common/recipes-phosphor/flash/openpower-software-manager/obmc-flash-bios

**Comment by mdmillerii** [comment]
An alternative to creating an additional `tmpfs` is to make `/media` a symlink to /run/media and create that directory (maybe through systemd `tmpfiles`, or the existing `mkdir -p` in the above reference).

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6037> filesystem: mount rw /media with fstab
Resolves  #2072 Make /media tmpfs

**Comment by lgon** [comment]
GitHub Comment
++++++++++++++++++++++++++++++++++++++
TASK LIST

    Version - Add unique pointer to erase callback method from parent.
    Implement Object.Delete in version, and override delete method to call parent's erase method.
    Add erase method to image manager to remove version and activation from maps, and delete tmp image directory. Bind erase method to version when inserted in map.
    Add erase method to item updater to remove version from map and remove ro,rw partitions. Bind erase method to version when inserted in map.
    Create service files to delete read only and read write partitions.

#STATUS Resolved and merged.
8-23 - My change is based off of Edward A. James's changes for https://gerrit.openbmc-project.xyz/#/c/5962/       Once his code is merged, I can make a final test with my changes, and resolve this issue.
++++++++++++++++++++++++++++++++++++++
