### ISSUE TITLE
dreport: Improve -t option.

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#2076]
refer reveiw link for details.
https://gerrit.openbmc-project.xyz/#/c/5451/3/dreport/dreport.sh@23

**Comment by ojayanth** [comment]
This is included as part of issue https://github.com/openbmc/openbmc/issues/2037.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/93
