### ISSUE TITLE
dreport: refactor cli using getopt.

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#2077]
Details : https://gerrit.openbmc-project.xyz/#/c/5536/2/dreport/dreport.sh@69

"We should be using 'getopt' rather than writing our own parser. Need to ensure our busybox is compiled with ENABLE_FEATURE_GETOPT_LONG"

**Comment by ojayanth** [comment]
Phase 7 candidate.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/94
