### ISSUE TITLE
Core dump on org.open_power.Software.Host.Updater

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#2091]
Seeing this on the latest master where org.open_power.Software.Host.Updater stopped after a core dump.
This seems to be related to https://gerrit.openbmc-project.xyz/#/c/5750/

openpower-update-manager[1075]: terminate called after throwing an instance of 'cereal::RapidJSONException'
Jul 26 05:05:57 witherspoon daemon.info openpower-update-manager[1075]:   what():  rapidjson internal assertion failure: IsObject()
Jul 26 05:05:57 witherspoon daemon.info systemd[1]: Started Phosphor Chassis0 Control.
Jul 26 05:05:57 witherspoon daemon.warn systemd[1]: org.open_power.Software.Host.Updater.service: Main process exited, code=dumped, status=6/ABRT
Jul 26 05:05:57 witherspoon daemon.err systemd[1]: Failed to start OpenPower Software Update Manager.
Jul 26 05:05:57 witherspoon daemon.notice systemd[1]: org.open_power.Software.Host.Updater.service: Unit entered failed state.
Jul 26 05:05:57 witherspoon daemon.warn systemd[1]: org.open_power.Software.Host.Updater.service: Failed with result 'core-dump'.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5790> Fix for serial restoreFromFile exception
Resolves  #2091 Core dump on org.open_power.Software.Host.Updater
