### ISSUE TITLE
Install same versions of new PNOR (squashfs)

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#2093]
```
0. Power off Host
1. PNOR already installed, try to re-installing the same version and verify
2. Use new PNOR  update method and  install
```

 It doesn't update the same version, I believe this one is expected, however,  couple of suggestions

- [x]  Software Manager need to return/log appropriate msg if the same version is already installed (for Dev folks)
- [x] Automation needed to verify if the same version installed [For test folks]

From the journald and elog entries, the error logged and journald data doesn't help here to tell whats the error is about. This needed to be more specific in terms of what is logged.
```
Jul   21 11:28:05 witherspoon phosphor-version-software-manager[1021]: tar: short   read     
Jul 21 11:28:05 witherspoon phosphor-version-software-manager[1021]: Error   No manifest file     
Jul 21 11:28:05 witherspoon phosphor-version-software-manager[1021]: An   error when reading the Manifest file.     
Jul 21 11:28:05 witherspoon phosphor-version-software-manager[1021]: Error   processing image  

Entry : /xyz/openbmc_project/logging/entry/16     {
          "AdditionalData":   [],
          "Id": 16,         "Message":   "xyz.openbmc_project.Software.Version.Error.ManifestFileFailure",  
         "Resolved": 0,         "Severity":   "xyz.openbmc_project.Logging.Entry.Level.Error",  
         "Timestamp":   1500637017373,
         "associations":   []
     }

```

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5823> item_updater: Add a log to indicate duplicate image upload.
Resolves  #2093 Install same versions of new PNOR (squashfs)
