### ISSUE TITLE
Need a 5 second delay on checkstop detection

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2094]
On a checkstop, the OCC collects some data and stores it in PNOR for later analysis.  BMC needs to be sure to give the OCC some time to collect that data before doing any recover.

Per discussion with hostboot team, this should be 5 seconds.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5782> Add 5 seconds delay before processing host checkstop
Fixes  #2094 Need a 5 second delay on checkstop detection
