### ISSUE TITLE
Missing OCC active sensor in witherspoon.xml used in the build.

### ISSUE THREAD

**Issue by dhruvibm** [openbmc/openbmc#2097]
There is no occ_active sensor present in the witherspoon.xml which is used, either need to include an updated witherspoon.xml or need to hardcode occ_active parameters in YAML to get OCC active sensor working

**Comment by dhruvibm** [comment]
@williamspatrick @spinler

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5794> Adding support for hardcoded sensor yaml.
Resolves  #2097 Missing OCC active sensor in witherspoon.xml used in the build.

**Comment by dhruvibm** [comment]
# **STATUS**

08/08: Ready for merge review

**Comment by dhruvibm** [comment]
added changes in  openbmc to merge Hardcoded sensor yaml with output of MRW parser to support sensors not present in MRW for MRW based systems.
