### ISSUE TITLE
CPU callout is broken

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2103]
A change in the master/slave processor path (in the 4.10 kernel I presume) is impacting CPU callouts. Should be a simple fix in gen_callouts.pl.

**Comment by dkodihal** [comment]
# **STATUS**

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6024> callouts script: fsi path fixups
Resolves  #2103 CPU callout is broken
