### ISSUE TITLE
Map TPM setting to ipmi sensor

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2104]
This will involve implementing the ability to get ipmi sensors via the infrastructure @dhruvibm is working on.

**Comment by tomjoseph83** [comment]
# **STATUS**

8/14 

Made the yaml change for the TPM sensor. Tomorrow will do the coding for the host-ipmid.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6084> tpm: Add tpm_required_sensor in sensor config.yaml
Resolves  #2104 Map TPM setting to ipmi sensor
