### ISSUE TITLE
Network:- Add support for configuring NTP server.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2106]
<cde:info> SW390259 </cde:info>
We have the dhcp ntp option but this is for configuring the static ntp server.

**Comment by ratagupt** [comment]
- [ ] Configure the NTP server if interface mode is static.

- [ ] Need to make the change in the dbus interface yaml file for adding of NTP servers.

- [ ] Load the NTP servers during start up of network manager.

- [ ] Write the test case to verify the above functionality.

**Comment by ratagupt** [comment]
# **STATUS**

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6207> Test: Add test cases for DNS and NTP
Resolves  #2106 Network:- Add support for configuring NTP server.
