### ISSUE TITLE
Network:- Add support for configuring the DNS server.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2107]

**Comment by ratagupt** [comment]
- [ ] Set the DNS servers to the Networkd conf in the case of if interface mode is Static.

- [ ] Get the DNS servers when the network manager starts .
       On the dbus interface will only show the configured static nameserver.

**Comment by ratagupt** [comment]
#**STATUS**

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6131> Update the resolv.conf when DNS info is provided by DHCP
Resolves  #2107 Network:- Add support for configuring the DNS server.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6131> Update the resolv.conf when DNS info is provided by DHCP
Resolves  #2107 Network:- Add support for configuring the DNS server.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6131> Update the resolv.conf when DNS info is provided by DHCP
Resolves  #2107 Network:- Add support for configuring the DNS server.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6131> Update the resolv.conf when DNS info is provided by DHCP
Resolves  #2107 Network:- Add support for configuring the DNS server.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6131> Update the resolv.conf when DNS info is provided by DHCP
Resolves  #2107 Network:- Add support for configuring the DNS server.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6131> Update the resolv.conf when DNS info is provided by DHCP
Resolves  #2107 Network:- Add support for configuring the DNS server.
