### ISSUE TITLE
BMC does not get updated with DNS server provided by DHCP

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#2108]
BMC does not get updated with DNS server provided by DHCP.
1. Enable DHCP on BMC
2. Send DHCP request 
3. DHCP server sends DHCP response with IP, Netmask, GW and DNS server IP
BMC does not extract DNS and update its DNS server in its DB.

**Comment by ratagupt** [comment]
is it for new xyz or old org?

**Comment by prkatti1** [comment]
it is on new xyz

**Comment by prkatti1** [comment]
as discussed closing this as setup issue
