### ISSUE TITLE
Witherspoon - raise AVDD +100mV for P9 errata

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2112]

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5832> Increase AVDD on witherspoon
Resolves  #2112 Witherspoon - raise AVDD +100mV for P9 errata

**Comment by geissonator** [comment]
# **STATUS**
8/8 - Uploaded code but it's failing CI with a pgood timeout, Jordan is looking
