### ISSUE TITLE
BMC Update: Verification, test and automation integration

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2113]
Perform verification of BMC update, coordinate test and automation of test case and drive to resolution any issues during verification.

**Comment by saqibkh** [comment]
- [ ]  Delete kernel-<versionId> ubi with BMC delete interface.
- [ ]  Don't delete rw ubi with BMC delete interface
- [ ]  Delete rw ubi with BMC Factory Reset
- [ ]  Recreate BMC Versions on reboot
- [ ]  Store BMC priority persistence files in two different places and sync them
