### ISSUE TITLE
hwmon config file for power supplies

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2115]
After the power supply driver is done, we need to make some hwmon config files to expose the power, current, and voltage readings for them.  

Required for early ship.

**Comment by spinler** [comment]
- [ ] Create config files for each power supply with labels so all current, voltage, power, temp, and fan sensors get picked up by hwmon
- [ ] Check into the openbmc repository so they get installed with the conf files

**Comment by spinler** [comment]
# **STATUS**
* 8/10: Put a preview of the PS driver on a system and built the config files and rebound the driver and saw everything show up in REST.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5982> Add power supply hwmon config files
Resolves  #2115 hwmon config file for power supplies
