### ISSUE TITLE
image-* missing from latest builds

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2116]
Build team reported that these files suddenly disappeared from recent master builds.  Theory is it has something to do with the recent UBI image changes.

```
  | image-bmc | 32.00 MB | view
  | image-kernel | 3.50 MB | view
  | image-rofs | 13.60 MB | view
  | image-rwfs | 4.00 MB | view
  | image-u-boot
```

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5852> image-overlay.bbclass: Restore deploying the intermediate files
Resolves  #2116 image-* missing from latest builds
