### ISSUE TITLE
Do not allow power on if PNOR does not have required image

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2117]
New BMC code requires the new UBI based PNOR image be loaded in.  There are situations where we may have new BMC code, but old PNOR.  We want a clear error in the journal and quick fail on boot to notify the user.

**Comment by geissonator** [comment]
Looks like @saqibkh may have this one covered.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5971> Do not allow power on if PNOR doesn't have required image
Resolves  #2117 Do not allow power on if PNOR does not have required image
