### ISSUE TITLE
BMC: Persist redundancy priorities

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#2125]
Image redundancy priorities need to persist through a bmc reset.

This is similar to what Michael did for PNOR.
https://github.com/openbmc/openbmc/issues/2040

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5899> BMC: Restore RedundancyPriority on reset
Resolves  #2125 BMC: Persist redundancy priorities

**Comment by saqibkh** [comment]
# **STATUS**
Aug 13: Waiting for merge review.
