### ISSUE TITLE
PNOR: Store redundant copy of Priority value

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2133]
The Priority value of PNOR versions is stored in the BMC, but if a BMC factory reset is performed, then the values would be lost. Need to keep a redundant value in the PNOR itself and restore the values if they're deleted from the BMC.

**Comment by mtritz** [comment]
- [ ] Determine a location in the PNOR to store priority values
- [ ] Update priority storage calls to store in both the current and the new locations
- [ ] When attempting to restore priority from file, check the second location if necessary.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5977> PNOR: Store a redundant copy of the priority persistence file
Resolves  #2133 PNOR: Store redundant copy of Priority value
