### ISSUE TITLE
PNOR: Generate squashfs tarball as part of op-build

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2135]
As part of building op-build (https://github.com/open-power/op-build) to create a PNOR image, also generate the openbmc pnor squashfs tarball so that users don't need to manually create one when then want to update the PNOR on openbmc systems.

**Comment by charleshofer** [comment]
- [ ] Create variables to set defconfigs as OpenBMC machines and VPNOR machines
- [ ] Create a new package to get the generate-squashfs script
- [ ] Modify op-build to build pflash
- [ ] Modify the PNOR package to run the generate-squashfs script

**Comment by amboar** [comment]
Given that op-build already has all the information required to assemble the PNOR image in the first place, shouldn't we be leveraging that to generate the VPNOR image rather than tearing apart the PNOR image after it's generated? This approach feels like a bit of a Rube Goldberg machine.

**Comment by charleshofer** [comment]
Pull request: https://github.com/open-power/op-build/pull/1325
