### ISSUE TITLE
OCC power values in hwmon don't match scale factor

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2136]
The hwmon documentation states that power values should be in microWatts:

```
power[1-*]_input		Instantaneous power use
				Unit: microWatt
				RO
```
(And the scale factor that shows up in D-Bus from phosphor-hwmon for them is -6)

but they are showing up in Watts in /sys/class/hwmon.

So I think the driver will probably need to do the conversion.

**Comment by rfrandse** [comment]
Fixed
