### ISSUE TITLE
Re-create BMC Software Versions after reboot

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#2137]
The dbus objects for all BMC Active images must be restored after BMC reboot.

**Comment by saqibkh** [comment]
- [ ]  Create a service that mounts the RO ubi volume for BMC images when a system boots up.
- [ ]  Recreate the dbus objects for BMC Software versions by checking /media for available versions.
- [ ]  Restore the priority by reading the persistence priority files.

**Comment by saqibkh** [comment]
Sequence of commits:
1) https://gerrit.openbmc-project.xyz/#/c/5934/
2) https://gerrit.openbmc-project.xyz/#/c/5946/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5946> BMC: Restore version and activation dbus objects on BMC reboot.
Resolves  #2137 Re-create BMC Software Versions after reboot
