### ISSUE TITLE
IPMI:- Implement Network mode change support from IPMI

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2138]
User should be able to change the interface mode(Static/Dynamic) from IPMI

**Comment by ratagupt** [comment]
Confirmed with @whowutwut(victor hu) that we don't need this support in phase5.

**Comment by whowutwut** [comment]
Thanks @ratagupt .  

@zet809, FYI this was a request for inband change for ipsrc to dynamic, I searched our code and we don't call that.. so I think it's not needed.

**Comment by ratagupt** [comment]
Here we need to support multiple interfaces through IPMI,Currently IPMI supports single interface.

**Comment by ratagupt** [comment]
I had a discussion with @whowutwut 
and he confirmed that we  need to cover the following:

Scenario 1
1) Factory Reset
2) Get DHCP IP  
3) ipmitool to change network properties to static

Here after step 3 we need to change the mode to static.so we need this in phase 5.

Scenario 2:   (broke with new code)
1) factory reset
2) In DHCP mode
3) 10pin direct to BMC and run

**Comment by ratagupt** [comment]
- [ ] Implement the support for following command.
        ipmitool lan set 1 ipsrc static/dynamic.

Will list out the various condition and verify it with Victor Hu, that how it is implemented in other stack.

**Comment by whowutwut** [comment]
@ratagupt  This is an implementation to support this via REST?  What is the proposed endpoint for it?

**Comment by ratagupt** [comment]
@whowutwut :- Suppose the system ethenet interface is in DHCP  mode and through IPMI you want to set some ip through the below commands.

Currently IPMI doesn't support the ipsrc static/dynamic command so you would not be able to change the mode of the ethernet interface hence the IP would not be added.

However if the interface mode is Static then it will work fine.

Now with the implementation of ipsrc command type through IPMI will have below behavior.

==>If eth0 is having DHCP IP and through IPMI user change the mode to SATTIC then user have to supply all the data(address/mask/gateway).we will not use the IP which is already assigned to eth0 through DHCP.

==>If eth0 is having DHCP IP and through IPMI user change the mode to DHCP,it is a NO-OP

==>if eth0 is having Static IP and through IPMI user says that he wants to enable DHCP then it may happen that interface gets new ip address from DHCP server.

==>if eth0 is having Static IP and through IPMI user change the mode to static then we will inherit the ip info which is configured on the system if user has given partial data.

**Comment by whowutwut** [comment]
@zet809 FYI above

**Comment by whowutwut** [comment]
@ratagupt  Is the above behavior default behavior? What is suppose to happen in RedFish specification?  Really, we just want the BMC to behave in a documented fashion, if you document this behavior on the README, that is fine.  Otherwise how would other consumers of the API know the intended behavior without actually trying it out to see what happens...

**Comment by ratagupt** [comment]
@whowutwut :- Every protocol comes with its own limitation..But seems to me the behaviour would be same. except last one,User has to give all the data, all this limittaion comes as IPMI supports either tagged packet or untagged packet..That limittaion I don't see in REST/REDFISH.
Regarding this behaviour I would update the README.

**Comment by ratagupt** [comment]
# **STATUS**
08/31
Starting the coding today.
09/01
Still Coding,Planning it to complete it by today.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6383> SetLan: Make changes in set channel access to support ipsrc param
Resolves  #2138 IPMI:- Implement Network mode change support from IPMI
