### ISSUE TITLE
BMC: Check that the BMC tarball has all required files during image verifcation

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2143]
Currently the image verification checks that the uploaded BMC tarball has file image-rofs. Need to add the rest of the files that are expected to be present in a BMC tarball.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6000> Check if BMC tarball has all required files during image verifcation
Resolves  #2143 BMC: Check that the BMC tarball has all required files during image verifcation
