### ISSUE TITLE
Create error log on PGOOD timeout

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2147]
There needs to be an error log when the PGOOD signal from the power sequencer chip doesn't come on.

Eventually, I'll be analyzing that chip to see why it didn't come on, but not for phase 5.

**Comment by spinler** [comment]
# **STATUS**

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5990> Add service and recipe for PGOOD fail errors
Resolves  #2147 Create error log on PGOOD timeout
