### ISSUE TITLE
Unset occ active on host power down events

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2148]
Need to monitor for the host power off event and set the occ active sensors appropriately.

FYI - @vishwabmc @dkodihal

**Comment by geissonator** [comment]
# **STATUS**
8/15 - Initial code written to monitor for host off state and put occ's into non-active

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6012> Disable occ active on host stop
Resolves  #2148 Unset occ active on host power down events
