### ISSUE TITLE
Create power supply redundancy and derating factor sensors

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2154]
Some details in #1213.  Need to implement these using the new ipmid sensor design.

**Comment by geissonator** [comment]
Phase 5 for now, @spinler to check with occ team on impacts.

**Comment by dhruvibm** [comment]
- [ ] Add YAMLs for ps derating and redundancy

- [ ] Create an application for handling PS redundancy and derating

- [ ] Add IPMI sensor read support for new interfaces.

**Comment by tomjoseph83** [comment]
# **STATUS**

09/01
Made changes that are need for Phase 5. I would be completing 2220 first before moving on to this one.

**Comment by tomjoseph83** [comment]
We should be removing the Power Supply redundancy/Power derating & Turbo allowed(Power specific) from the legacy dbus path check, once we get these changes in.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6782> Remove legacy reading of PS derating
Resolves  #2154 Create power supply redundancy and derating factor sensors

**Comment by geissonator** [comment]
This was backed out, need to find story where we bring this back in.

**Comment by dkodihal** [comment]
@dhruvibm can you use this story to write new dbus interfaces and app for the PS sensors, along with ipmid changes?

**Comment by dhruvibm** [comment]
# **Status**
Need to decide the application implementing the PS derating and redundancy servers.

**Comment by dkodihal** [comment]
This was implemented via https://gerrit.openbmc-project.xyz/#/q/topic:PowerSupplyRedundancy

**Comment by tomjoseph83** [comment]
There are 2 sensors that needs to be moved from legacy code to sensor generated code.

a) Power Supply Redundancy is supported in the settings. So the input yaml for the sensor generation needs to be updated.

b) The implementation of power derating sensor needs to be discussed.

**Comment by gtmills** [comment]
@tomjoseph83 @dkodihal What is this issue tracking now? Should it just be closed? We have a power supply redundancy sensor.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/66

**Comment by anoo1** [comment]
Done with:
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/12165/
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/12166/
https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/12167/
