### ISSUE TITLE
PNOR: Delete lowest priority PNOR image before update if there are already 3 present

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2155]
Only 3 pnor images fit in the pnor chip, delete the lowest priority one if we've hit the limit to allow the user to update without having to manually delete an image.
This until we get the work done to monitor for flash space.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6074> Limit the number of Active pnor versions
Resolves  #2155 PNOR: Delete lowest priority PNOR image before update if there are already 3 present
