### ISSUE TITLE
Eventlog service need to use conf file for setting dblog instead of hardcoding the size

### ISSUE THREAD

**Issue by mkumatag** [openbmc/openbmc#216]
https://github.com/openbmc/openbmc/pull/214

IMO we should use EnvironmentFile entry under the service section and read the option from that file instead of hardcoding the value directly. This option will even help to change the value runtime and test it.

Reference - http://fedoraproject.org/wiki/Packaging:Systemd#EnvironmentFiles_and_support_for_.2Fetc.2Fsysconfig_files

**Comment by causten** [comment]
The systemd config file has the value settable in there.  
meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/files/obmc-phosphor-event.service

Are you thinking of a different technique?

**Comment by mkumatag** [comment]
currently we have following code in meta-phosphor/common/recipes-phosphor/obmc-phosphor-event/files/obmc-phosphor-event.service for size

[Service]
ExecStart=/usr/sbin/obmc-phosphor-eventd -s 200000

Having value directly here will become very difficult to change it programmatically, instead it will good if we read same value from environment file like below:

[Service]
EnvironmentFile=-/etc/eventd.conf
ExecStart=/usr/sbin/obmc-phosphor-eventd $OPTIONS


And the file content for /etc/eventd.conf looks like below:

OPTIONS="-s 200000"

Following this approach we have 2 advantages - 

1. Easy to modify the value quickly and restart the service.
2. As we are not changing anything in the service files, so no need to daemon-reload for config change.

**Comment by anoo1** [comment]
We need to add an additional argument for the max number of logs (added via https://github.com/openbmc/phosphor-event/pull/18), so this may be an opportunity to move the size and number into the config file.

**Comment by anoo1** [comment]
Doug can take a look

**Comment by causten** [comment]
This isn't a v1.0 Backlog request.  The service works the way it does now fine.  This is a feature change request not a bug.  Nothing wrong with the request but we can ship as it is.  I do believe there will be a review of the event log service for GA3 in which case the milestone can be changed.  Nothing to do here for v1.0 Backlog

**Comment by causten** [comment]
I vote this moves to a different backlog.  Not a needed change for v1.0
 
 
Chris AustenPOWER Systems Enablement Manager(512) 286-5184 (T/L: 363-5184)
 
 
----- Original message -----From: anoo1 <notifications@github.com>To: openbmc/openbmc <openbmc@noreply.github.com>Cc: Chris Austen/Austin/IBM@IBMUS, Comment <comment@noreply.github.com>Subject: Re: [openbmc/openbmc] Eventlog service need to use conf file for setting dblog instead of hardcoding the size (#216)Date: Mon, May 23, 2016 1:36 PM 
Doug can take a look
