### ISSUE TITLE
Persistence Priority files not deleted after calling the Delete interface.

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#2160]
We noticed that several persistence files with priority "0" were stored under "/var/lib/obmc/openpower-pnor-code-mgmt/". 

$ls /var/lib/obmc/openpower-pnor-code-mgmt/
136cf504  137a04a4  2b6dcac8  e49bc78e

It seems that the user called the delete interface on all these versions and was successfully able to delete the corresponding ubi volumes. However these priority files were not deleted.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6035> Item_updater:Restructure the sequence of delete interface.
Resolves  #2160 Persistence Priority files not deleted after calling the Delete interface.
