### ISSUE TITLE
Increase host shutdown timeout from 5 to 45 minutes

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2162]
Large configured systems can take a long time to properly shut down.  We reduced the timeout given to the host to shutdown from 45 to 5 min due to https://github.com/open-power/skiboot/issues/81 but we need to bump it back up to 45.  We now have a "obmcutil chassisoff" to force the power off if needed.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6049> Increase host shutdown timeout to 45 minutes
Resolves  #2162 Increase host shutdown timeout from 5 to 45 minutes
