### ISSUE TITLE
Enable occ error detection

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/openbmc#2165]
openpower-occ-control had put the occ error detection code before but due to the hub FSI expectation, occ control now needs to wait till all the OCCs are bound before starting error detection and this needs change in the occ management code

**Comment by vishwabmc** [comment]
@geissonator please assign this to me

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6089> Enable OCC error monitoring
Fixes  #2165 Enable occ error detection

**Comment by vishwabmc** [comment]
# **STATUS**

- 8/21:
   - Pushed the code for review
