### ISSUE TITLE
start_host.cpp needs to check for boot count >= 1

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2169]
The new code to always decrement the boot count before the boot is attempted means we need the startHost() procedure to boot off of sbe seeprom side 0 if the boot count is 1 or greater.  Only at 0 should we try sbe side 1.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6076> Boot from sbe side 0 when boot count is greater than 0
Resolves  #2169 start_host.cpp needs to check for boot count >= 1
