### ISSUE TITLE
Network:- Implement the Network Monitor app

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2171]
Impelement the network monitor app which will listen on the new address event ,which sends the dbus message to the network manager app to refresh its interfaces to reflect the action on the interface.

**Comment by ratagupt** [comment]
- [ ] Create an app which listens on systemd signal (if systemd-networkd sends it) / RTNETlink addADDR signal on an interface 

- [ ] After getting signal on a particular interface it will ask the networkmanager to refresh the IP objects of the given interface.

**Comment by ratagupt** [comment]
# **STATUS**
08/31
Discussed the approach in the design meeting.
01/09
Haven't started the coding.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6399> Network: Add network Monitor
Resolves  #2171 Network:- Implement the Network Monitor app
