### ISSUE TITLE
SBE side selection always using side 1

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2178]
Noticed this during some other testing.  The start_host code was always selecting sbe side 1, even when boot count was greater then 1.  I dug in and found it was because the variant type was an int, but the new AttempsLeft variable is now an unsigned int.  A little weird we don't get any errors during reading it, just always got a 0 back.  Anyway, got a quick fix.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6119> Convert over to uint32_t for AttemptsLeft
Resolves  #2178 SBE side selection always using side 1
