### ISSUE TITLE
enumerate is now a keyword, method names should not match

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#218]
Found this issue while using our obmc UI.  
https://github.com/LRRoberts0122/openbmc/issues/13

Once the /enumerate became part of the REST schema it can no longer be a dbus interface.  Need to remove org.openbmc.enumerate from /org/openbmc/inventory and anywhere else it is found.  The same information can be retrieved via /org/openbmc/inventory/enumerate

**Comment by williamspatrick** [comment]
The enumerate method was meant as a performance optimization for the enumerate REST interface. Can you give more of an explanation what the problem is?

Patrick

**Comment by causten** [comment]
Brad mentioned the issue.  The existing REST interface doesn't handle it well
See the issue above for more details

**Comment by anoo1** [comment]
@bradbishop , is this still an issue?

**Comment by williamspatrick** [comment]
Need one update to the recipes and this can be closed.
