### ISSUE TITLE
Fan Monitor - Set nonfunctional fans back to functional at poweron

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#2187]
When fan(s) are marked non-functional and the system is powered off, the fans should be marked as functional at the next poweron.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6213> Add phosphor-fan-monitor init service
Resolves  #2187 Fan Monitor - Set nonfunctional fans back to functional at poweron
