### ISSUE TITLE
Create error log with message field on system shutdown due to 3 cores over 115C

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2190]

**Comment by gtmills** [comment]
Matt B wants an error log with a message of "System powered off, too many cores overtemp."  on system shutdown due to 3 cores over 115C

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6632> Create SystemShutdown error log on core overtemp
Resolves  #2190 Create error log with message field on system shutdown due to 3 cores over 115C
