### ISSUE TITLE
BMC: Mount /usr/local/ in read-only filesystem for patching

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2199]
Currently, /usr/local is mounted via a mount systemd unit which creates the directory, but in a read-only filesystem, need to change that approach since systemd can't create the directory.

**Comment by mdmillerii** [comment]
We just need a package create the base mount point via `install -d ${D}/usr/local` and declare it in `FILES_${PN}`.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6220> Create dir /usr/local for ubi patch service
Resolves  #2199 BMC: Mount /usr/local/ in read-only filesystem for patching
