### ISSUE TITLE
BMC Update: Write kernel to both chips and update boot env only on success

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2200]
Currently the BMC will only create the kernel volume in the BMC chip, need to write a copy to the alt BMC chip for backup.

Also just set the boot env variables to point to the updated image if all the volumes were created successfully. Strengthen the error checking on the update script.

**Comment by anoo1** [comment]
- [ ] When creating a kernel volume, create a copy on the alt bmc chip (if an alt chip exists).
- [ ] When deleting a kernel volume, delete the copy from the alt bmc chip (if it exists).
- [ ] Only update the boot env variables with the information of the new volumes if updating the kernel and rootfs finished successfully, this can be done by adding a postExec in the update service file that updates the env variables.
- [ ] Verify that the volumes exist before setting the env variables, this will prevent bricking the system if a volume has been deleted/renamed.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6426> obmc-flash-bmc: Create a duplicate kernel volume in alt
Resolves  #2200 BMC Update: Write kernel to both chips and update boot env only on success
