### ISSUE TITLE
BMC Update: Update documentation

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2201]
Document the BMC update process using the software dbus interfaces.

**Comment by anoo1** [comment]
Update the code-update.md with:
- [ ] usage of the software dbus interfaces.
- [ ] instructions to enabling the ubi layout.
- [ ] information on where the volumes are stored and how to define the location in a per-system basis.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8281> Add information about storing images
Resolves  #2201 BMC Update: Update documentation
