### ISSUE TITLE
Inventory deserialization : reconstruct items with properties in one shot (per item)

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2206]
Story #957 is introducing inventory persistence. Cereal is used for serialization of inventory properties.

The code for #957, in the deserialize path, default constructs inventory items and then deserializes inventory properties onto the items. This is because Cereal requires a constructed type reference to deserialize onto. This results in both d-bus InterfacesAdded and PropertiesChanged (several) signals to be emitted for each time. The properties will change because initially they were default and then the deserialzation restored them. Such signalling can adversely impact apps interested in the signals.

Talked to @williamspatrick and @bradbishop about this today - a possible solution that was discussed was to deserialize onto a templatised holder object, which holds a map of properties for the template type (which would be the sdbusplus binding type). Post that, the actual sdbsplus binding type can be constructed. This story is to implement such a solution.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/124
