### ISSUE TITLE
Misc state service file issues.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#2207]
1.
phosphor-reset-host-running@.service has
```
# TODO: openbmc/openbmc#1205 - target name refactor
ExecStart=/bin/systemctl start obmc-host-start@%i.target
```
but that issue is closed.

2.
There is a service file called 'op-reset-chassis-on@.service' that is actually an obmc service.  That file is likely also in the wrong place (I think it is a legacy file that changed action without changing name or location).

**Comment by gtmills** [comment]
1 is done. https://github.com/openbmc/openbmc/commit/d6a8ca3b0fb0049401cd045ebbc6c968d2c39fe4
