### ISSUE TITLE
Implement support for reset tolerance in Aspeed GPIO controller

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#2208]
Reset tolerance holds the state of individual GPIO pins across SoC resets. This is essential for "reset/reload" support, and for maintaining LED state in some systems.

**Comment by geissonator** [comment]
We good on this one @amboar ?

**Comment by amboar** [comment]
I started looking at it, but it's not yet implemented

**Comment by amboar** [comment]
I've sent patches upstream which have received some feedback: http://patchwork.ozlabs.org/project/openbmc/list/?series=9241&state=%2A&archive=both

I'll need to rework them, but interested parties might want to jump on and give their opinion on whether or not we'd like to have the reset tolerance be configurable from userspace for userspace-exported GPIOs. @bradbishop @shenki

**Comment by amboar** [comment]
Implementation is upstream and also applied to the openbmc kernel
