### ISSUE TITLE
Implement generic code that provide support for handling a new sensor with Get Sensor reading command

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#2220]

**Comment by tomjoseph83** [comment]
# **STATUS**

09/01
Started coding on this today.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6523> sensor: Add placeholder for set::reading
Resolves  #2220 Implement generic code that provide support for handling a new sensor with Get Sensor reading command
