### ISSUE TITLE
Fan Control / Hwmon(#2329): Handle OCC temp sensor failure

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#2222]
When a temp sensor that is provided by the OCC times out having read failures, a 0xFF value is returned in the current temp reading byte. When a 0xFF is read by fan control, the fans for zone 0 should be set to full speed (10500rpms)
![occ_temp_format](https://user-images.githubusercontent.com/14202667/29827977-1eeffb7a-8ca1-11e7-9ee0-5c855c671819.jpg)

**Comment by amboar** [comment]
Are we exposing these values via the sensor value attribute? I feel like this case should be translated into `-EAGAIN` or `-EIO` on reading the attribute.

**Comment by msbarth** [comment]
Pre-4.13 these 0x00 & 0xFF values were being presented in the sensor value attribute. A driver update was made (and included in post-4.13) to provied EAGAIN for 0x00 and EIO on 0xFF, however the user side support in hwmon was not complete, hence this issue. This problem is in discussion right now and scheduling the work is underway.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10334> wspoon: Handle faulted OCC temp sensors
Resolves:  #2222 Fan Control / Hwmon(#2329): Handle OCC temp sensor failure
