### ISSUE TITLE
Mapper bug with GetSubTreePaths  /xyz/openbmc_project/inventory/system/chassis/

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2226]
```root@witherspoon:/tmp# busctl call  xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper GetSubTreePaths sias /xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/  0  1 xyz.openbmc_project.Inventory.Item```
works
```
as 2 "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc/ethernet" "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc"
```
but as soon as shorten the path to `/xyz/openbmc_project/inventory/system/chassis/` it does not
```root@witherspoon:/tmp# busctl call  xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper GetSubTreePaths sias /xyz/openbmc_project/inventory/system/chassis/  0  1 xyz.openbmc_project.Inventory.Item```

```Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 602, in GetSubTreePaths
    interfaces)
  File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 587, in filter_interfaces
    return dict(filter(lambda x: x[1], map(obj_map, iter(item))))
  File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 585, in <lambda>
    ifaces))
  File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 587, in filter_interfaces
    return dict(filter(lambda x: x[1], map(obj_map, iter(item))))
TypeError: 'NoneType' object is not iterable```

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6600> Fix interface filter logic bug on GetSubTreePaths
Resolves:  #2226 Mapper bug with GetSubTreePaths  /xyz/openbmc_project/inventory/system/chassis/
