### ISSUE TITLE
ubi0:rwfs: Missing core file in BMC Dump 

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#2240]
BMC Dump manager watch core file created by systemd-coredump for core base BMV dump creation . In the system which have ubi0:rwfs based /var/lib/systemd/coredump directory , noticed that  existing inotify-event structure provide  only core file “#<inode>” format instead of actual file name for IN_CLOSE_WRITE event watch.  Also this file  name is getting changed systemd-coredump format with different events. This is causing dreport fail to copy the file in to BMC dump

**Comment by ojayanth** [comment]
Refer https://github.com/openbmc/openbmc/issues/2214 for more details

**Comment by ojayanth** [comment]
Proposed fix , till e identified the actual fix  from systemd-coredump is to mount the core path in tmpfs filesystems.

**Comment by ojayanth** [comment]
# **Status**
09/08: Coding is in progress.

**Comment by amboar** [comment]
Isn't the actual fix a kernel patch? Is there some discussion of why UBI behaves this way? I dug through this with @ojayanth but I wouldn't think the actual solution is to just use a tmpfs instead.

**Comment by ojayanth** [comment]
@amboar this is temporary fix . Actual fix should be related Kernel or systemd-core dump side . Planing to open new issue to track the actual fix.

**Comment by ojayanth** [comment]
https://github.com/openbmc/openbmc/issues/2287 used to track the actual fix.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6626> phosphor-debug-collector: Create /var/lib/systemd/coredump mount point
Resolves  #2240 ubi0:rwfs: Missing core file in BMC Dump

**Comment by geissonator** [comment]
Workaround did not work, reopening

**Comment by geissonator** [comment]
Core dumps disabled for now, moving to 5.1

**Comment by ojayanth** [comment]
# **Status**

09/18: Code changes are ready. tmpfs based core path , inotify reporting incorrect core file name for dir level events. As per inotify documentation optional data is valid only for file events. Waiting for driver which have ubfi filesystem enabed.

**Comment by ojayanth** [comment]
In ubfi filesystem inotify notification events behaves very diffrently like 
   - IN_CREATE notification event structure provides the core file name 
   - IN_CLOSE_WRITE notification event structure provides the INODE number instead of file name 
    - IN_CLOSE_NOWRITE  notification triggers "directory" level and  "Size of name field " shows 0 . inthis case file name trucates most of the cases. 
As a temporary solution we need to change the watch to IN_CREATE instead of IN_CLOSE_WRITE. 
In my testing, dreports package conatins the good core file with this event.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6835> Fix for missing core file in the Applicationcore type BMC dump
Resolves  #2240 ubi0:rwfs: Missing core file in BMC Dump
