### ISSUE TITLE
Implement the ability to delete all BMC dumps in one shot

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2255]
Implement the ability to delete all BMC dumps in one shot.

**Comment by ngorugan** [comment]
- []  Add a new interface Remove.interface.yaml at /xyz/openbmc_project/Dump with a method RemoveAll, which is suppose to delete all BMC dumps in one shot.

- [] Implement Remove interface

**Comment by dkodihal** [comment]
@ngorugan based on your current "delete all error logs", the interface we finalize there should be usable here as well. We don't need a new interface.

**Comment by ngorugan** [comment]
@dkodihal Okay, let me wait until Patrick replays back to your comments on my "delete all error logs" related yaml file changes, then I will update tasks of this Issue accordingly.

**Comment by ngorugan** [comment]
# **STATUS**
09/20
Cod is under review

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6611> Add implementation for delete all BMC Dumps in one shot
Resolves  #2255 Implement the ability to delete all BMC dumps in one shot
