### ISSUE TITLE
[Barreleye 1.99.9.*] RestAPI: BootProgress incorrect and sensors missed

### ISSUE THREAD

**Issue by yadron** [openbmc/openbmc#2256]
1. If I retrieve BootProgress value, I get "Off", but actually it is On:

```
curl -b cjar -k https://172.17.27.240/org/openbmc/sensors/host/BootProgress
{
  "data": {
    "error": 0, 
    "units": "", 
    "value": "Off"
  }, 
  "message": "200 OK", 
  "status": "ok"
}
```

and actually

```
root@v:~# obmcutil bootprogress
BootProgress:       xyz.openbmc_project.State.Boot.Progress.ProgressStages.OSStart

root@v:~# obmcutil power       
pgood = 1
state = 1
pgood_timeout = 10
```

2. No any other data available (e.g. sensors) apart from these three values:

curl -b cjar -k https://172.17.27.240/org/openbmc/sensors/host/
{
  "data": [
    "/org/openbmc/sensors/host/BootCount", 
    "/org/openbmc/sensors/host/BootProgress", 
    "/org/openbmc/sensors/host/OperatingSystemStatus"
  ], 
  "message": "200 OK", 
  "status": "ok"
}

How to add sensors?
I need commands like these that worked with older OpenBMC (before June) well):
`curl -b cjar -k https://172.17.27.229/org/openbmc/sensors/temperature/ambient`
or
`curl -b cjar -k https://172.17.27.229/org/openbmc/sensors/host/temperature/ambient`
non available currently. Why and how to fix it?

**Comment by geissonator** [comment]
We've moved all sensors out of the org.openbmc namespace.  Here are new areas:

curl -c cjar -b cjar -k -H "Content-Type: application/json" -X  GET https://$BMC_IP/xyz/openbmc_project/state/enumerate

 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET https://${BMC_IP}/xyz/openbmc_project/sensors/enumerate
