### ISSUE TITLE
MFG:Witherspoon, Sensor.Device.Error.ReadFailureError, max31785 fan controller, 0812q driver

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2262]

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6546> sysfs IO enhancements
Resolves:  #2262 MFG:Witherspoon, Sensor.Device.Error.ReadFailureError, max31785 fan controller, 0812q driver
