### ISSUE TITLE
Network:- Enable Zeroconf

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#2265]
We need to make sure while enabling the Zeroconf that IPMI should behave correctly.
If on the system there are multiple IP address objects then we should not return the Zeroconfig address.
But if there is no other IP address on the system except zeroconfig then we can return the Zeroconf address.

ZeroConf can be enabled on the system by writing the following parameter under Network Section in network file.
LinkLocalAddressing = yes.

**Comment by ngorugan** [comment]
- [ ]  Enable zeroconf in network file,While we write the configuration file.
- [ ] Make the changes in IPMI so that we should not return the zeroconfig address while there are other IP address.
- [ ] Write a test case in phosphor-networkd to verify that parameter is correctly written.

**Comment by ngorugan** [comment]
# **STATUS**
09/21
Cod is under review

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6810> Don't return zeroconfig address if other IP address is present
Resolves  #2265 Network:- Enable Zeroconf
