### ISSUE TITLE
IPL: /usr/local/share/pnor/ is not cleared on PNOR updates

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2273]
Pflash would overwrite a patched pnor partition during an update since it overwrites the whole chip.
This behavior should be followed by the virtual pnor partition as well, where it clears the patch
pnor directory.

<cde:info> SW401428 </cde:info>

**Comment by anoo1** [comment]
@saqibkh would you take this issue? Maybe we can clear the share/pnor/ dir as part of the symlink creation to avoid clearing it when the host is using it.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6583> Clear PNOR patch location while updating symlinks
Resolves  #2273 IPL: /usr/local/share/pnor/ is not cleared on PNOR updates
