### ISSUE TITLE
Software Object: Create Functional Association

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2279]
Create an association to the currently running version of FW for the BMC and Host so that the user can query what FW is running on the system at any time.

This association would dynamically change as part of a Host FW update for example.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6718> Call updateFunctionalAssociation on symlink change
Resolves  #2279 Software Object: Create Functional Association
