### ISSUE TITLE
/usr/sbin/pflash tool is still available in Zaius Open BMC shell prompt

### ISSUE THREAD

**Issue by PavamanSubramaniyam** [openbmc/openbmc#2281]
I have installed the latest master Open BMC build on Zaius P9 Hardware.
Still I can see the pflash tool available in the Open BMC shell prompt. 
However, the same utility is not available in Witherspoon Hardware.

```
root@zaius:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.9-123"
VERSION_ID="v1.99.9-123-gdbf5de0"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.9-123"
BUILD_ID="v1.99.9"

root@zaius:~# which pflash
/usr/sbin/pflash

root@zaius:~# /usr/sbin/pflash  --version
Open-Power Flash tool v5.7-rc2
```

**Comment by geissonator** [comment]
Yep, we have not enabled the new PNOR code update functionality on Zaius, it's only on Witherspoon at this point.  The pflash tool being there indicates you should still use the old pflash methods to flash PNOR.
