### ISSUE TITLE
Stop certain services when entering quiesce state

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2282]
The purpose of quiesce is to leave the system in a state where it could be debugged (i.e. change as little as possible).  But, if a checkstop occurs, we should disable the host watchdog, otherwise we get a checkstop error, and then a host watchdog error.

For this specific situation we could probably just have the host watchdog app conflict with quiesce.  We may want to discuss a longer term solution if we think there will be other scenarios like this (i.e. do we create a new target that can stop and clean up anything else like this when going into quiesce)?

**Comment by geissonator** [comment]
Sizing of this will depend on scope of change.  Just a 0 pointer if we do the conflicts.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7013> Host watchdog needs to conflict with quiesce target
Resolves  #2282 Stop certain services when entering quiesce state
