### ISSUE TITLE
Software ID list includes things that aren't software IDs.

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2289]
<cde:info> SW401759 </cde:info>

**Comment by anoo1** [comment]
Brad mentioned he could do a quick change in the REST server to show the interfaces in a grouped way so that it's cleared which ones are interfaces an which ones associations. Ex of current output:
```
curl -s  -b cjar  -c cjar   -k  -H  'Content-Type: application/json'   -X GET https://BMC///xyz/openbmc_project/software/
{
  "data": [
    "/xyz/openbmc_project/software/active",
    "/xyz/openbmc_project/software/b9f2f57"
  ],
  "message": "200 OK",
  "status": "ok"
}
```

**Comment by anoo1** [comment]
No current plans to make changes.
