### ISSUE TITLE
Software ID believes two different images are identical

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2290]
<cde:info> SW400271 </cde:info>

**Comment by anoo1** [comment]
**STATUS**
9/28 - No resolution has been determined yet.

**Comment by anoo1** [comment]
This issue would address the issue that the version id is a hash over the version string, creating the same id for the same version strings such as -dirty ones even though the image might contain different code.

This and other enhancements are being summarized in epic openbmc/openbmc#2291
