### ISSUE TITLE
Unable to activate BMC images

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc#2307]
1. Upload a UBI BMC image via REST
2. Attempt to activate it
The "Activation" property is set to failed

```
root@witherspoon:~# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.9-162"
VERSION_ID="v1.99.9-162-g5723ce2"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.9-162"
BUILD_ID="v1.99.9"
```

Here's the journal
[journal.txt](https://github.com/openbmc/openbmc/files/1300447/journal.txt)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6657> Check if the BMC version already exists in /media before mounting.
Resolves  #2307 Unable to activate BMC images
