### ISSUE TITLE
Telemetry design : define aggregation d-bus interfaces.

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2313]
@tomjoseph83 to add details here and/or #1957.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6743> telemetry: Add aggregation interfaces
Resolves  #2313 Telemetry design : define aggregation d-bus interfaces.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6743> telemetry: Add aggregation interfaces
Resolves  #2313 Telemetry design : define aggregation d-bus interfaces.

**Comment by rfrandse** [comment]
tracked by ibm-openbmc/dev#54
