### ISSUE TITLE
Host factory reset: clear volumes instead of deleting them

### ISSUE THREAD

**Issue by mtritz** [openbmc/openbmc#2322]
Currently, the host factory reset deletes read-write volumes created during PNOR activation. It should instead clear these volumes.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6841> Host reset: Change deletes to clears
Resolves  #2322 Host factory reset: clear volumes instead of deleting them

**Comment by rfrandse** [comment]
ibm-v1.99.10-113-g65edf7d-r1"  iit is not clearing volumes after host factory reset.

**Comment by rfrandse** [comment]
Michael verfied it worked, so unable to recreate.
