### ISSUE TITLE
At build time, calculate the version id of the BMC ubi volumes

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2323]
cde:info SW406771 </cde:info>
Currently, when a ubi-enabled BMC image is created, the volume names have a 0 appended to their name (ex: kernel-0). During a code update, a hash of the version string is calculated to generate a unique id for the name (ex: kernel-123xyz). So there's a situation where 2 machines at the same level would display a version object of software/0 (if chip was flashed like in manufacturing) and software/123xyz (if code updated).

Need to calculate the hash during build time so that an id is generated instead of hard-coding 0 as the volume names.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6847> Calculate the version ID of BMC UBI volumes during build time.
Resolves  #2323 At build time, calculate the version id of the BMC ubi volumes
