### ISSUE TITLE
BMC delete image REST action should return an error if delete is not permitted on a currently active image

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2335]
<cde:info> SW402587 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7057> BMC Updater: Remove the Object.Delete interface from functional version
Resolves  #2335 [xCAT] BMC delete image REST action should return an error if delete is not permitted on a currently active image

**Comment by rfrandse** [comment]
@mtritz: only one of two commits has been merged

**Comment by rfrandse** [comment]
Both commits are now merged.
