### ISSUE TITLE
Remove org.openbmc settings

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/openbmc#2339]
After transitioning settings to xyz, the support in org.openbmc needs to be removed and also the document needs to be updated to explain the new setting objects.

**Comment by geissonator** [comment]
This got higher priority as we've continued to battle CPU performance issues after BMC reboots.  These legacy python applications are putting a lot of un-needed burden on the processor.

See https://gerrit.openbmc-project.xyz/#/q/topic:2339 for details.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8829> Remove legacy settings service
Resolves  #2339 Remove org.openbmc settings
