### ISSUE TITLE
ipv6 link local addresses should not implement Delete.

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#2342]
Any attempt to do this is just going to raise an error so the option should not be given in the first place.

@ratagupt @dkodihal ^

**Comment by ratagupt** [comment]
I think we can implement delete but during delete we should put a check if it is linklocal/zeroconfig then it can not be deleted..

**Comment by ratagupt** [comment]
Currently if user says delete then it is a no-op for user..as we would restart the network which will again create it.But we can optimisie it as don't allow to delete it.

**Comment by bradbishop** [comment]
I still think we should have better behavior here, if we haven't addressed this.  @ratagupt or @wak-google any idea what the current behavior is?
