### ISSUE TITLE
Witherspoon : BMC hung after BMC reboot test

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2345]
<cde:info> SW402319 </cde:info>

**Comment by rfrandse** [comment]
Eddie's comment: finally figured out whats causing the hang. will have a new patch set up in a bit, assuming my idea to fix it works...

**Comment by eddiejames** [comment]
# ** STATUS **
09/28 - Testing OK with patches in gerrit... Seeing some memory corruption issues around the kernel, possibly related. Will look into that.
