### ISSUE TITLE
phosphor-fan-presence-tach not detecting missing fans

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2348]
On the latest master on wsbmc011, phosphor-fan-presence-tach isn't detecting when a fan is removed.

ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.10-19"
VERSION_ID="v1.99.10-19-g319ec41"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.10-19"
BUILD_ID="v1.99.10"

This did work on an older GHE driver we used yesterday, so not sure what happened.

**Comment by spinler** [comment]
```
root@witherspoon:~# i2cget -y 3 0x60 0 b
0x0e
```

**Comment by amboar** [comment]
A fix is on the list: http://patchwork.ozlabs.org/patch/818028/

**Comment by spinler** [comment]
merged with https://gerrit.openbmc-project.xyz/#/c/7062/
