### ISSUE TITLE
UBI- empty file after unclean reboot

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#2350]
See https://github.com/openbmc/openbmc/issues/2337 for details

**Comment by ojayanth** [comment]
# **Status**
09/22: Proposed fix is in reveiw.

**Comment by amboar** [comment]
@ojayanth please link to the patch if it is in Gerrit for review.

**Comment by ojayanth** [comment]
@amboar Proposed solution , still in discussion. Code is not ready.

**Comment by gtmills** [comment]
@ojayanth Can this be closed? #2337 was closed.
