### ISSUE TITLE
dreport plugin support 

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#2351]
Non-recipe related changes tracked here.
 in https://github.com/openbmc/openbmc/issues/2037

**Comment by ojayanth** [comment]
- [ ] dreport utility function support
logging ( info/important/summary/warning).
Error handling
Saving contents
Getting dump context Configuration parameters

- [ ] restructure the existing  dreport  code to support
CLI infrastructure
Initializing the  dump type config parameters
Invoking data collection based on the dump type
compression and copy  into permanent location
Error management

- [ ] Create individual bash scripts for the existing data collection functions.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7358> Change dreport source location to tools/dreport.d/dreport
Resolves  #2351 dreport plugin support
