### ISSUE TITLE
Tooling to cherry pick specific changes into releases and branches

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2352]
Once we get close to shipping systems, we'll need to start locking down internal branches and tags.  Would like some tooling (via this story) where a user could point to specific patches (either merged in github, or un-merged changes in gerrit) and a target branch which would:
- Cherry pick the change(s)
- Generate patch(es) based on input tag
- Copy patch to appropriate dir, update corresponding .bb file to use patch

(this is all via the openbmc/openbmc tree)

Also do the following:
- Take the input tag, take the new tag, checkout the tag, apply the fixes, create the new tag

**Comment by amboar** [comment]
Does yocto already provide something in this regard? This process is applicable to all the tools and applications it provides recipes for.

**Comment by geissonator** [comment]
Could also use this to verify changes in sub-repo's in CI (i.e. do full openbmc build and validate)

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/68
