### ISSUE TITLE
Serial over lan console using Hterm in GUI 

### ISSUE THREAD

**Issue by iftekharuli** [openbmc/openbmc#2353]
We have placed the hterm console in the GUI as required with the open in new window function. Not sure what story to create in this regard as mentioned in https://github.com/openbmc/openbmc/issues/361 
@geissonator 
![screen shot 2017-09-22 at 11 06 45 am](https://user-images.githubusercontent.com/4976631/30753890-51c4510c-9f86-11e7-94c6-f9733b93563e.png)

**Comment by gtmills** [comment]
Serial Over Lan is working in the GUI. 
Closing this story.
