### ISSUE TITLE
System-pfault-analysis: Make use of the State.Shutdown.ThermalEvent.GPU and State.Shutdown.Power.Fault errors

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2362]
Need to start using these 2 new errors in phosphor-dbus-interfaces instead of the current ones in the witherspoon-pfault-analysis repository

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7200> Use the phosphor-dbus-interfaces shutdown error
Resolves  #2362 witherspoon-pfault-analysis: Make use of the State.Shutdown.ThermalEvent.GPU and State.Shutdown.Power.Fault errors

**Comment by rfrandse** [comment]
Nice to have. Moving to Phase 8 to revisit at another time.

**Comment by geissonator** [comment]
#2705 should help here

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7200> Use the phosphor-dbus-interfaces shutdown error
Resolves  #2362 System-pfault-analysis: Make use of the State.Shutdown.ThermalEvent.GPU and State.Shutdown.Power.Fault errors

**Comment by spinler** [comment]
This still can't work due to how this would require a local elog-errors.hpp and the one from the include path being included in the same file, and then there are symbol conflicts.  As it's not like I would be completely removing repository local errors anyway, I'm just going to give up on this.
