### ISSUE TITLE
IPL: BMC code update failure when updating to same version

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2371]
<cde:info> SW402308 </cde:info>

**Comment by anoo1** [comment]
Tets case result:
FAIL: Bmc Code Update.REST BMC Code Update
xyz.openbmc_project.Software.Activation.Activations.Active != xyz.openbmc_project.Software.Activation.Activations.Ready

**Comment by anoo1** [comment]
Addressed with openbmc/openbmc-test-automation#1008
