### ISSUE TITLE
[xCAT] On very first update to 1738, the priority value of the BMC is set to 255 instead of 0

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2373]
<cde:info> SW403131 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6887> Set Priority value of functional BMC version to 0
Resolves  #2373 [xCAT] On very first update to 1738, the priority value of the BMC is set to 255 instead of 0

**Comment by anoo1** [comment]
**STATUS**
9/28 - Ready for merge review.
