### ISSUE TITLE
SBE - Host passthrough commands fails often

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2375]
<cde:info> SW402730 </cde:info>

**Comment by eddiejames** [comment]
Debugging this now. So far I cannot recreate with my command line sbefifo tool on the bmc. So far no indication that sbefifo driver is getting two different clients mixed up, everything looks correct. Need to recreate with cronus setup

**Comment by rfrandse** [comment]
Answer = [Unreproducible]
Neither Venkatesh nor I can reproduce this now...
Possible the latest updates to SBEFIFO driver have fixed this.
