### ISSUE TITLE
Delete orphaned pnor read-write volumes

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#2376]
We have seem many instances where the read-only volumes were deleted but the read-write partitions were preserved. This had causes subsequent PNOR updates to fail as the space on PNOR chip is occupied by these orphaned rw volumes.
Therefore we need to delete the pnor read-write volumes if corresponding read-only volumes are not present.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/6901> Delete orphaned pnor read-write volumes.
Resolves  #2376 Delete orphaned pnor read-write volumes
