### ISSUE TITLE
Remove org.openbmc.* from REST server

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2378]
<cde:info> SW407587 </cde:info>
The goal here is to put a filter on what the REST server allows users to read and write.  Basically anything using the old org.openbmc would not be allowed in our out via REST.

**Comment by ngorugan** [comment]
- [ ] Create new map(container) with cap size of 10(configurable) for info logs

- [ ] Once we reach 10 info logs, send a warning/info msg and Clear oldest info log to make room for new  and store it.

- [ ] Use the existing map(container) with existing cap size of 100 to store error logs.

- [ ] Once we reach cap size, send a warning

**Comment by dkodihal** [comment]
@ngorugan @bradbishop I'm thinking this can be a plug-in which runs on each request, checks if the request url consists of /org/openbmc, if so, fails with a 'not allowed'.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7422> Remove org.openbmc.* from REST server
Resolves  #2378 Remove org.openbmc.* from REST server

**Comment by mine260309** [comment]
This breaks the code update for non-UBIFS BMCs, a.k.s all OpenBMC machines except Witherspoon.
I suggest revert it ASAP and commit it back until we have moved all services under `/org/openbmc/` to `/xyz/openbmc_project/`

**Comment by geissonator** [comment]
We'll need to put this new code in it's own file, so it can easily be pulled in for just systems that want it.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10209> Remove org.openbmc.* from REST server
Resolves  #2378 Remove org.openbmc.* from REST server
