### ISSUE TITLE
Handle more then 100 error logs

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2381]
<cde:info> SW402443 </cde:info>
With the creation of #2380, the BMC will start getting periodic error logs created, that could potentially not be resolved.  Need a medium term solution for this with this story.  Some thoughts:

- Once we reach 100, start deleting oldest informational errors
- Only allow 1 informational
- Increase the 100 count and still do some of the above?

**Comment by ngorugan** [comment]
- [ ] Create new map(container) with cap size of 10(configurable) for info logs

- [ ] Once we reach 10 info logs, send a warning/info msg and Clear oldest info log to make room for new  and store it.

- [ ] Use the existing map(container) with existing cap size of 100 to store error logs.

- [ ] Once we reach cap size, send a warning

**Comment by dkodihal** [comment]
I doubt if we need any warnings.

Also, I don't think we need any new containers. Just keep a count of errors based on the info, non-info severity.

**Comment by ngorugan** [comment]
# **STATUS**
10/13
Code is up for review.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7307> Handle more then 100 error logs
Resolves  #2381 Handle more then 100 error logs
