### ISSUE TITLE
No API to clear GUARD, leading to bricked systems

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2389]
<cde:info> SW403432 </cde:info>

**Comment by geissonator** [comment]
# **STATUS**
9/29 - Discussed in team meeting, overall a fairly simple change but looking for the right place to put the new object.  Will finalize on Monday.

**Comment by anoo1** [comment]
Per team discussion, we'll create a /org/openpower/control/gard object path under the pnor updater and implement FactoryReset on it.
On the documentation, describe the assertions and assumption about gard, like the one where gard is a preserved partition.

**Comment by mtritz** [comment]
- [ ] Create a new object path under the host updater at /org/openpower/control/gard
- [ ] Implement the FactoryReset interface under the new path
- [ ] Create a reset() function - when FactoryReset is called, clear the gard partition

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7352> Host updater: implement GUARD factory reset
Resolves  #2389 No API to clear GUARD, leading to bricked systems

**Comment by stewart-ibm** [comment]
Please reopen this until there's some documentation on the API. I only seem to find the implementation.

**Comment by zahrens** [comment]
Opened #2637 to track documentation
