### ISSUE TITLE
NCSI Driver issue

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2392]
<cde:info> SW403075 </cde:info>

Summaryof this issue is that if you cause the ethernet port the BMC is using to fail, the NCSI hardware will try to fail over to the other port.  If that port is not functional, or on a different network, then the BMC just suddenly drops off the network.

**Comment by geissonator** [comment]
# **STATUS**
9/29/17 - Sam is driving debug of this with system owner.
