### ISSUE TITLE
IPL: Error log cleanup: occ1-dev0 Sensor.Device.Error.ReadFailure (ERRNO=125) on wsbmc016 with 910.1740.20170929a

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2401]
<cde:info> SW403721 </cde:info>

**Comment by spinler** [comment]
The OCC driver is returning ECANCELLED when it is in the process of being unbound on a power off.

I will add this errno to phosphor-hwmon's retry list, where it will try for up to a second.  In that second, the unbinding should complete and the phosphor-hwmon process will be terminated.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7078> Retry on ECANCELED errnos
Resolves  #2401 IPL: Error log cleanup: occ1-dev0 Sensor.Device.Error.ReadFailure (ERRNO=125) on wsbmc016 with 910.1740.20170929a

**Comment by spinler** [comment]
For awareness: the OCC driver is changing from returning an ECANCELLED TO ENODEV.
