### ISSUE TITLE
IBM Milestone 3 : Inband Firmware Update

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2404]
Epic to track all the work related to enabling inband firmware updates.

**Comment by anoo1** [comment]
* Need protocol (mbox, ipmi, lpc, pci, ...,) to send image file from host to BMC to the location where the REST upload currently copies image files to (/tmp/images/).
* New IPMI command handler to trigger the activation when ipmitool hpm request is done. The request could be blocked for out-of-band.

**Comment by shenki** [comment]
Discussion on in-band code update from January OpenBMC hackfest: https://docs.google.com/document/d/1xO3Vl_M5sY3lcCAAM3noBtleH1d9xk-bwqxzVbTX36o/edit?usp=sharing

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/67
