### ISSUE TITLE
STC:OP910:witherspoon:yl13ue: 2 Sensor.Device.Error.ReadFailure logged per minute

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2408]
<cde:info> SW403723 </cde:info>

**Comment by spinler** [comment]
For tracking removing the OCC temp = 0 -> EAGAIN/temp = 0xFF->EIO(or whatever it was) changes since userspace doesn't have time to implement them.

**Comment by rfrandse** [comment]
**STATUS**
10/10: This is done https://gerrit.openbmc-project.xyz/#/c/7186/

**Comment by rfrandse** [comment]
ibm-v1.99.10-113-g65edf7d-r1
