### ISSUE TITLE
Add hwmon config file for PCIE temp

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2411]
There is a tmp275 to provide air temperature around the witherspoon pcie slots that fan control will use.  It needs a phosphor-hwmon config file so the temp will be exposed on D-Bus.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7016> Add phosphor-hwmon config file for the PCIE temp
Resolves  #2411 Add hwmon config file for PCIE temp
