### ISSUE TITLE
Need a method to create an internal error in error logs

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#2416]
Need a method to create an internal error in error logs. This is required for dump testing. My main intention is to see a dump getting created once this entry is logged.

Development support for the dump to get created is already in place. All we need is a method to generate an internal error.

**Comment by rahulmah** [comment]
@mtritz : As discussed, here is the task which we need for our testing.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7076> Add InternalFailure to logging-test
Resolves  #2416 Need a method to create an internal error in error logs

**Comment by rahulmah** [comment]
@mtritz : To be exact, we want to see below error getting logged. 
`Message = xyz.openbmc_project.Common.Error.InternalFailure`

**Comment by rahulmah** [comment]
@rfrandse :  As discussed, this is something we need for verifying internal failure dump. Please move this up in the priority list.

**Comment by mtritz** [comment]
commit is actually here - https://gerrit.openbmc-project.xyz/#/c/7389/
