### ISSUE TITLE
STC:CORAL:OP910:Not being able to upload BMC or PNOR to Witherspoon BMC with tagged vlan IP

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2418]
<cde:info> SW403404 </cde:info>

**Comment by geissonator** [comment]
# **STATUS**
10/06 - Looking for a recreate of this, none seen recently

**Comment by rfrandse** [comment]
CQ SW403404 was dup'ed to SW387409
This will now be tracked by https://github.com/openbmc/openbmc/issues/2467
