### ISSUE TITLE
Cannot enable field mode

### ISSUE THREAD

**Issue by charleshofer** [openbmc/openbmc#2428]
```ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v1.99.10"
VERSION_ID="ibm-v1.99.10-0-r11-0-g9c65260"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v1.99.10"
BUILD_ID="ibm-v1.99.10-0-r11"
```

1. Enable field mode with `curl -b cjar -k -H 'Content-Type: application/json' -X PUT -d '{"data":0}' https://9.3.185.164/xyz/openbmc_project/software/attr/FieldModeEnabled`
2. Check that the FieldModeEnabled was actually set
```
Getting: https://9.3.185.164/xyz/openbmc_project/software
{
  "data": {
    "FieldModeEnabled": 1, 
    "associations": [
      [
        "active", 
        "software_version", 
        "/xyz/openbmc_project/software/9e55358e"
      ], 
      [
        "active", 
        "software_version", 
        "/xyz/openbmc_project/software/a5e1c851"
      ]
    ]
  }, 
  "message": "200 OK", 
  "status": "ok"
}
```

/usr/local is not unmounted like it should be. Plus, if you reboot the BMC the FieldModeEnabled property goes back to 0.

[journal.txt](https://github.com/openbmc/openbmc/files/1360850/journal.txt)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7521> Fix for field mode not working after reboot
Resolves  #2428 Cannot enable field mode
