### ISSUE TITLE
/etc/systemd/ unwriteable after update to latest code

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2429]
This is a post-find bug but wanted to get something open to track it.  Basically we found an issue where /etc/systemd/ was not writeable, which means software couldn't write the network file.

Eddie did some analysis and found we were doing the overlay service twice during boot.

Fix is here - https://gerrit.openbmc-project.xyz/#/c/7089/1

**Comment by amboar** [comment]
Ah, we should close #2431 as a duplicate

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7089> Prepare-overlay service: check for mountpoint before remving workdir
Resolves  #2429 /etc/systemd/ unwriteable after update to latest code
