### ISSUE TITLE
phosphor-fan-watchdog.service uses %i in it

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2432]
This service isn't a template service, but for some reason I still had it doing:

```
Wants=phosphor-fan-control-init@%i.service
Before=phosphor-fan-control-init@%i.service
RequiredBy=obmc-chassis-poweron@%i.target
```
That leads to humorous traces like:
```
witherspoon systemd[1]: Reached target Powerwitherspoon-fan-watchdog (On).
```
and 
```
witherspoon systemd[1]: phosphor-fan-control-init@witherspoon-fan-watchdog.service: Unit entered failed state.
```

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7116> Don't use template parameters in fan watchdog service
Resolves  #2432 phosphor-fan-watchdog.service uses %i in it
