### ISSUE TITLE
MFG:Witherspoon, "Sensor.Device.Error.ReadFailureError" with 1738 driver, CALLOUT_DEVICE_PATH=../sbefifo1-dev0/occ1-dev0

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2435]
<cde:info> SW402150 </cde:info>

**Comment by rfrandse** [comment]
defect has 3 unique fails in it.  

1. The first one is the EAGAIN and will hopefully go away on the next kernel bump we get.  
2. The errno 125  @bradleyb just asked @eajames to change to something else in a review, and then we need a phoshpor-hwmon change for it.  
3. The errno 14 ? @eajames was also asked to changed to something else, not sure where that is, I will follow up with Eddie

**Comment by rfrandse** [comment]
done https://gerrit.openbmc-project.xyz/#/c/7186/`
ibm-v1.99.10-113-g65edf7d-r1
