### ISSUE TITLE
phosphor-dbus-monitor: Ambient temp based shutdown

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#2459]
This issue is really to verify that pdm is able to support a system shutdown based off a temperature sensor reading, which is available on dbus and add to the witherspoon thermal policy. Initial ambient temp of 45C should cause the system to shutdown.

**Comment by spinler** [comment]
Needed for Witherspoon LC

**Comment by msbarth** [comment]
This is able to be configured in pdm. Similarly, a witherspoon system is configured within pdm to shutdown when 3 or more core temps are at/above 115C.
