### ISSUE TITLE
phosphor-network: Allow IP addresses to be added to an interface with dhcp enabled.

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#2460]
As of today, adding an IP alias to a dhcp enabled interface will silently switch dhcp mode off.  Exit criteria for this story is the ability to add IP addresses to an interface in dhcp mode without turning it off.

**Comment by ratagupt** [comment]
We have the same issue opened here https://github.com/ibm-openbmc/dev/issues/389

**Comment by truehomie** [comment]
hey wassup, i have an issue i can't resolve ... 

I need to change/renew/refresh/reset/modify my DUID client DHCPv6 ...
after i changed my MAC address it consists of two parts : my new MAC address + my old MAC address...

looking someone who can assist
