### ISSUE TITLE
Image activation progress at 10% for 5+ minutes, UBI errors in kernel log

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2462]
<cde:info> SW401761 </cde:info>

**Comment by anoo1** [comment]
This issue tracks the enhancement mentioned in https://github.com/openbmc/openbmc/issues/1554 regarding figuring out a way to get progress out of ubiupdatevol, maybe there's some indication in /proc, instead of having hard-coded progress numbers throughout the code.

**Comment by mdmillerii** [comment]
It'd probably be easier to do the copy loop and update a dbus sensor in one application.  It could also do the atomic volume rename to never have a partial volume.

**Comment by anoo1** [comment]
No current plans to make changes.
