### ISSUE TITLE
[xCAT] Creating/Copying over ssh keys does not work all the time with OpenBMC

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2464]
<cde:info> SW403668 </cde:info>

**Comment by rfrandse** [comment]
@whowutwut  said
I think #1517 is different then the SW403668 CQ issue I opened. #1517 is asking for a REST method for uploading a public key to the BMC....

**Comment by rfrandse** [comment]
#**STATUS**
10/10:
Pending Victor getting back to Michael - there’s a suspicion that it may be a problem with the XCAT tool and not a defect on openbmc end

**Comment by whowutwut** [comment]
I think we can close/reject this one for now until I can prove that it's not something in the xCAT framework, it seems like i can't re-create this error using ssh scripts.
