### ISSUE TITLE
EIO error (5) on i2c device after large byte read request

### ISSUE THREAD

**Issue by janssens2** [openbmc/openbmc#2468]
When attempting to run the command `geti2c pu 6 0 A0 65536 0 2 `  Which attempts to read 64K bytes of data at once from the device /dev/i2c-100.  
This command fails with a errno 5 EIO error.  The data line appears to be stuck low per Eddie James.   Recovery involved hard power cycling of the server.  Other attempts to reset i2c did not work at the time.

To see the error it is necessary to run the command `geti2c pu 6 0 A0 65536 0 2 -debug5.fg`

This issue should be assigned to @eddiejames

**Comment by eddiejames** [comment]
Got a fix for this one up on the mailing list: http://patchwork.ozlabs.org/project/openbmc/list/?series=10655
