### ISSUE TITLE
phosphor-dbus-monitor: Duplicate non-functional fan error logs created

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#2472]
While verifying a defect was already fixed, noticed that PDM creates an extra error log for the first fan found to be not present (non-functional). The scenario was removed 2 fans while powered off and then power on the system. PDM correctly shuts down as configured with 2 fans missing, however 3 error logs are created associated with the fans that are non-functional. The extra error log appears to be associated with the first fan requiring an error log be created for not being present/functional.

![fanerrorlogs](https://user-images.githubusercontent.com/14202667/31560719-081f21f8-b01b-11e7-9c4e-955be7115482.JPG)

 ```
root@witherspoon:/sys/class/hwmon/hwmon0# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v1.99.10"
VERSION_ID="ibm-v1.99.10-0-r13-0-g076c283"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v1.99.10"
BUILD_ID="ibm-v1.99.10-0-r13"
```

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7685> Create Witherspoon fan errors
Resolves  #2472 phosphor-dbus-monitor: Duplicate non-functional fan error logs created
