### ISSUE TITLE
witherspoon: energy scale dcmi power set_limit not working

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2481]
<cde:info> SW405068 </cde:info>

**Comment by ssombar** [comment]
Its working again but the maximum limit we can set is 1000 watts.

**Comment by spinler** [comment]
https://gerrit.openbmc-project.xyz/#/c/7079/  by @gtmills will fix the limits

**Comment by gtmills** [comment]
This code has been merged. Closing.
