### ISSUE TITLE
Deglitch all power supply errors

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2484]
<cde:info> SW407275 </cde:info>
They should all take 3 consecutive positives before creating an error, just like #2473.

**Comment by bjwyman** [comment]
# **STATUS**
**10/25**
- Today: Discussed working on this, but chose to work on bug #2516 first.
- Tomorrow: Work on this if bug task list complete.
- Blockers: none

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7914> Implement de-glitch for input fault
Resolves:  #2484 Deglitch all power supply errors
