### ISSUE TITLE
Remove rest-dbus from Witherspoon

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2485]
Remove the rest-dbus development debug package from the Witherspoon image now that Witherspoon is going into production.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7756> Witherspoon: Remove the rest-dbus development package
Resolves  #2485 Remove rest-dbus from Witherspoon

**Comment by anoo1** [comment]
Built in internal driver, it won't be merged in master.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7756> (Do Not Merge): Witherspoon: Remove the rest-dbus development package
Resolves  #2485 Remove rest-dbus from Witherspoon
