### ISSUE TITLE
/home/root/.bash_history and /var/log/wtmp growing uncontrolled?

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2488]
<cde:info> SW407048 </cde:info>
I'm not seeing anything obvious that keeps these from just continuing to grow?

For wtmp, I see reference to using logrotate but not sure we have that on openbmc

**Comment by geissonator** [comment]
For the .bash_history file
```
root@witherspoon:~# echo $HISTSIZE
500
root@witherspoon:~# echo $HISTFILESIZE
500
```

**Comment by geissonator** [comment]
Team discussion:

- Lets just disable wtmp logging for now.
.bbappend to package that installs wtmp, and basically just don't install it.  Probably something does a touch on wtmp to get 0 file size, which is what wtmp looks at to know if it should write the file.
- Look for way to reduce bash history to something like 10

**Comment by geissonator** [comment]
Going to use this to just track the wtmp issue.  That file grows unchecked.  The .bash_history doesn't get much past 30KB before it starts wrapping.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7785> Disable wtmp function on openbmc systems
Resolves  #2488 /home/root/.bash_history and /var/log/wtmp growing uncontrolled?

**Comment by geissonator** [comment]
Rebased fix onto a change from Eddie and put into https://gerrit.openbmc-project.xyz/#/c/7844/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7844> Disable wtmp function on openbmc systems
Resolves  #2488 /home/root/.bash_history and /var/log/wtmp growing uncontrolled?

**Comment by geissonator** [comment]
After an afternoon of searching, I think I've tracked what we need down to https://github.com/systemd/systemd/pull/6006

This is in systemd v234, which is included in yocto 2.4.  That plus a change to pass in "EXTRA_OECONF += " --disable-utmp" should do it the "right way".

**Comment by geissonator** [comment]
We have a temporary solution with https://gerrit.openbmc-project.xyz/#/c/7844/.  I'll need to defer the final solution documented above until we get yocto 2.4 in.

**Comment by geissonator** [comment]
After moving to 2.4, this was fixed because systemd started honoring the utmp disable flag. https://github.com/openbmc/meta-phosphor/blob/master/common/recipes-core/systemd/systemd_%25.bbappend#L6 already has this in by default for openbmc.
