### ISSUE TITLE
Cannot delete firmware image

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2490]
<cde:info> SW405386 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7478> BMC: Prevent duplicate version dbus objects.
Resolves  #2490 Cannot delete firmware image

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7465> PNOR: Fix the delete implementation
Partially resolves  #2490 Cannot delete firmware image

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7478> BMC: Fix the delete implementation.
Partially resolves  #2490 Cannot delete firmware image

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7465> PNOR: Fix the delete implementation
Partially resolves  #2490 Cannot delete firmware image

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7478> BMC: Fix the delete implementation.
Partially resolves  #2490 Cannot delete firmware image
