### ISSUE TITLE
system fails to power off - ir35221 4-0071: Failed to read PMBUS_MFR_ID

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2496]
<cde:info> SW405496 </cde:info>

**Comment by eddiejames** [comment]
kernel fix, http://patchwork.ozlabs.org/patch/828335/ on the openbmc mailing list

**Comment by amboar** [comment]
Fixed in openbmc/linux@da78428ac543d6d9ac2493dfa77364eb300a47cb
