### ISSUE TITLE
No error while setting BMC/HOST time in case of invalid case

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#2499]
No error while setting BMC/HOST time in case of invalid case. 

Example: Set Host time when BMC is owner and NTP is sync mode.  In journal proper error is getting logged(see attached journal logs) but this error should also be thrown by REST so that customer can get to know while setting time in case of invalid case.

```
bash-4.1$ curl -c cjar -b cjar -k -X GET  https://<BMC_IP>/xyz/openbmc_project/time/owner/attr/TimeOwner
{
  "data": "xyz.openbmc_project.Time.Owner.Owners.BMC",
  "message": "200 OK",
  "status": "ok"
}
```

```
bash-4.1$ curl -c cjar -b cjar -k -X GET  https://<BMC_IP>/xyz/openbmc_project/time/sync_method/attr/TimeSyncMethod
{
  "data": "xyz.openbmc_project.Time.Synchronization.Method.NTP",
  "message": "200 OK",
  "status": "ok"
}
[journal logs time issue.txt](https://github.com/openbmc/openbmc/files/1407258/journal.logs.time.issue.txt)
```

```
bash-4.1$
bash-4.1$ curl -c cjar -b cjar -k -X GET  https://<BMC_IP>/xyz/openbmc_project/time/bmc/attr/Elapsed
{
  "data": 1507817371386383,
  "message": "200 OK",
  "status": "ok"   -----> here REST shoud throw an error
)```

Fw info:
BMC : v1.99.10-169-g0bb2201
PNOR :  IBM-witherspoon-ibm-OP9_v1.19_1.72

Journal log:
[journal logs time issue.txt](https://github.com/openbmc/openbmc/files/1407259/journal.logs.time.issue.txt)

**Comment by rahulmah** [comment]
I believe in all below cases we should see REST's set time throw error.

Mode      | Owner | Set BMC Time 
--------- | ----- | ------------
NTP       | BMC   | Fail to set
NTP       | HOST  | Not allowed
NTP       | SPLIT | Fail to set
NTP       | BOTH  | Fail to set
MANUAL    | HOST  | Not allowed

Mode      | Owner |Set Host Time
--------- | ----- | ------------
NTP       | BMC   | Not allowed
NTP       | HOST  | Not allowed
NTP       | BOTH  | Not allowed
MANUAL    | BMC   | Not allowed

**Comment by mine260309** [comment]
For now there will not be any REST error on setting time, because we do not support property's errors in phosphor-dbus-interface.
There will be a journal log error in such cases.
So this is expected behavior now.

**Comment by gkeishin** [comment]
@mine260309  Do u mean we won't support ahead ? or we are going to add it eventually? 

If so , please provide the github# for the same for our reference.

**Comment by gkeishin** [comment]
```
Lei Yu [10:57] 
currently we do not support errors on setting a dbus property, so there will not be any error on REST side, only the error log in journal
```
@rahulmah Please confirm the same.

**Comment by rahulmah** [comment]
Yeah, we are getting the journal entry. Closing the issue.
