### ISSUE TITLE
Add support for the Turbo allowed sensor in ipmi

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#2500]
<cde:info> SW405071 </cde:info>
The turbo allowed IPMI sensor would have a mapping to the /org/openbmc/sensors/host/TurboAllowed D-Bus object.

**Comment by ojayanth** [comment]
- [ ] Create d-bus interface for turbo allowed.

- [ ] Update Settings configuration to include turbo allowed setting

- [ ] Update IPMI Sensor configuration to enable IPMI Interface.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8867> TurboAllowed: Add support for TurboAllowed sensor type
Resolves  #2500 Add support for the Turbo allowed sensor in ipmi
