### ISSUE TITLE
Setting NTP as mode and HOST as owner at the same time not throwing error

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#2501]
I believe only BMC can be set to NTP (this is how it use to work in old ORG interface). So setting HOST as owner and NTP as mode at the same time should not be allowed. But at present in xyz, it is not throwing error while setting these settings.

```
bash-4.1$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\": \"xyz.openbmc_project.Time.Synchronization.Method.NTP\"}" -X PUT  https://<BMC_IP>/xyz/openbmc_project/time/sync_method/attr/TimeSyncMethod
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}bash-4.1$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\": \"xyz.openbmc_project.Time.Owner.Owners.Host\"}" -X PUT  https://<BMC_IP>xyz/openbmc_project/time/owner/attr/TimeOwner
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}bash-4.1$
bash-4.1$ curl -c cjar -b cjar -k -X GET  https://<BMC_IP>/xyz/openbmc_project/time/owner/attr/TimeOwner
{
  "data": "xyz.openbmc_project.Time.Owner.Owners.Host",
  "message": "200 OK",
  "status": "ok"
}bash-4.1$ curl -c cjar -b cjar -k -X GET  https://<BMC_IP>/xyz/openbmc_project/time/sync_method/attr/TimeSyncMethod
{
  "data": "xyz.openbmc_project.Time.Synchronization.Method.NTP",
  "message": "200 OK",
  "status": "ok"
}bash-4.1$
```

Fw info:
BMC : v1.99.10-169-g0bb2201
PNOR :  IBM-witherspoon-ibm-OP9_v1.19_1.72

Journal Logs:
[Journal_log_NTP_HOST.txt](https://github.com/openbmc/openbmc/files/1407427/Journal_log_NTP_HOST.txt)

**Comment by mine260309** [comment]
There will be no error log in such case.
Each settings combinations are allowed which is set by user.
The different combinations result in different behavior on settings BMC/Host time, as https://github.com/openbmc/phosphor-time-manager/blob/master/README.md#time-settings describes.

**Comment by rahulmah** [comment]
Okay. Closing the issue.
