### ISSUE TITLE
mount: wrong fs type, bad option, bad superblock on ubi8:pnor-patch,

### ISSUE THREAD

**Issue by saqibkh** [openbmc/openbmc#2502]
The PNOR code update went fine but the system failed to power on the HOST on the first try.
A retry of HOST poweron worked.
Found this error log on a system with VERSION_ID="ibm-v1.99.10-0-r13-0-g076c283"

Oct 23 07:03:34 witherspoon obmc-flash-bios[1176]: mount: wrong fs type, bad option, bad superblock on ubi8:pnor-patch,
Oct 23 07:03:34 witherspoon obmc-flash-bios[1176]:        missing codepage or helper program, or other error
Oct 23 07:03:34 witherspoon obmc-flash-bios[1176]:        In some cases useful info is found in syslog - try
Oct 23 07:03:34 witherspoon obmc-flash-bios[1176]:        dmesg | tail or so.

**Comment by gtmills** [comment]
Have not seen a recreate of this. Closing.
