### ISSUE TITLE
DHCP get wrong domain.

### ISSUE THREAD

**Issue by KenChenIEC** [openbmc/openbmc#2506]
My domain should be 10.6.45.xx, but the lastest openbmc code base will get 169.254.163.43 as below.
![ip](https://user-images.githubusercontent.com/16094021/31920365-1380a8a4-b89b-11e7-902c-b2fb9fd531dc.png)

I changed the commit ID in meta-phosphor/classes/phosphr-networkd-rev.bbclass to c9645fe5c874930445bca6ba51ac9daee916c99b, which is older version.
The IP is normally.

**Comment by ratagupt** [comment]
I need the out put of "ipaddr show dev eth0" instead of ifconfig.
Ifconfig is deprecated now.

**Comment by amboar** [comment]
@KenChenIEC For what it's worth 169.254.0.0/16 is the IPv4 link-local network block. Also, multiple IPs can be bound to a single interface, so it looks like you just need your usual network configuration applied.

@KenChenIEC Also, please try to refrain from posting images where possible, ideally the text from the console should be put into the issue. Given this is a networking problem I appreciate that might be harder, but given you're on the console you're probably viewing that on a different machine anyway.

**Comment by KenChenIEC** [comment]
@ratagupt Thanks you updated. it's work on "ip addr show dev eth0"

> root@2400-rep:~# ip addr show dev eth0
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
>     link/ether d6:78:56:a6:ec:66 brd ff:ff:ff:ff:ff:ff
>     inet 169.254.197.174/16 brd 169.254.255.255 scope link eth0
>        valid_lft forever preferred_lft forever
>     inet 10.6.45.80/24 brd 10.6.45.255 scope global dynamic eth0
>        valid_lft 259173sec preferred_lft 259173sec
>     inet6 fe80::d478:56ff:fea6:ec66/64 scope link tentative flags 08
>        valid_lft forever preferred_lft forever

@amboar Got it, I will post the text in future.

**Comment by ratagupt** [comment]
@KenChenIEC Can we close this issue now?

**Comment by KenChenIEC** [comment]
@ratagupt Sure, Thanks.
