### ISSUE TITLE
Witherspoon FA:  Pnor nonfunctional after Dediprod image Witherspoon.pnor from OP910_1740A/1738F

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2509]
<cde:info> SW405720 </cde:info>

**Comment by gtmills** [comment]
Need a script to create a UBI image from the squashfs image

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7480> Create UBI image
Resolves  #2509 Witherspoon FA:  Pnor nonfunctional after Dediprod image Witherspoon.pnor from OP910_1740A/1738F
