### ISSUE TITLE
OP910:OPRAS:witherspoon: Host is not sending down the esel data to BMC on checkstop/recoverable attention.

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2510]
<cde:info> SW405903 </cde:info>

**Comment by geissonator** [comment]
Tom, please provide summary of issue.  I believe high level the hostboot team changed the eSEL to 0x3A and we need to add to our white list?

**Comment by tomjoseph83** [comment]
This issue is to drop fix for changing the Net Function of Partial Add eSEL command. The hostboot was earlier using 0x32 as Net function which was AMI specific OEM. This is changed to 0x3A which stands for IBM specific OEM.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7538> Change the NetFn for Partial Add eSEL command.
Resolves  #2510 OP910:OPRAS:witherspoon: Host is not sending down the esel data to BMC on checkstop/recoverable attention.
