### ISSUE TITLE
xyz.openbmc_project.Common.Error.InternalFailure: Set sensor failed in phosphor-ipmi-host.service

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2515]
<cde:info> SW405699 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7542> Always watch for CPU inventory creation
Resolves  #2515 xyz.openbmc_project.Common.Error.InternalFailure: Set sensor failed in phosphor-ipmi-host.service
