### ISSUE TITLE
BMC allows to configure invalid gateway address

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2520]
<cde:info> SW405141 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7743> Fix Validate default gateway
Resolves  #2520 Witherspoon:FVT:910- BMC allows to configure invalid gateway address

**Comment by rfrandse** [comment]
@ngorugan 
System allows to configure invalid gateway address
It is also not have validation for configuration of broadcast, multicast, loopback and Network ID.
...
Right now we are only supporting ipv4, opened new issue: https://github.com/openbmc/openbmc/issues/2570 to support ipv6.
