### ISSUE TITLE
STC:OP910:Witherspoon:yl13u9bmc: System bmc code level went back to 1740B after dd2.1 update

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2535]
<cde:info> SW406413 </cde:info>

**Comment by anoo1** [comment]
The u-boot env variables get updated multiple times during a code update or when the priority of a version is changed. Changes are being made so that they get updated only once.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7649> Call update u-boot env once when a priority is changed
Resolves  #2535 STC:OP910:Witherspoon:yl13u9bmc: System bmc code level went back to 1740B after dd2.1 update
