### ISSUE TITLE
dreport tool adoption for collecting debug data

### ISSUE THREAD

**Issue by ojayanth** [openbmc/openbmc#2539]
-Move the ffdc backend to dreport.
-Inform users to start using dreport instead of ffdc collection tool - Mail to community
-Remove FFDC collection tool.

**Comment by ojayanth** [comment]
Peer review is in progress.

**Comment by ojayanth** [comment]
# **Status**
12/14: Completed Tasks "Move the ffdc backend to dreport and Inform users to start using dreport instead of ffdc collection tool - Mail to community" .FFDC tool removal from build will be doing only in Feb time frame , based on community response.

**Comment by geissonator** [comment]
ffdc tool now uses dreport as back end.  We'll not remove ffdc tool for backwards compatibility so this is done.
