### ISSUE TITLE
MFG:Witherspoon - xyz.openbmc_project.Sensor.Device.Error.ReadFailureError with 1742C; /sys/devices/platform/ahb/ahb:apb/ahb:apb:i2c@1e78a000 callout

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2540]
<cde:info> SW406639 </cde:info>

**Comment by spinler** [comment]
This was automatically opened by someone mistakenly opening an IBM internal defect in the wrong component. closing.
