### ISSUE TITLE
Include Power Cycle count in System telemetry data

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2543]
There is a requirement to know how many times the system has booted.

This will need to persist across AC loss of course.

**Comment by geissonator** [comment]
FYI @tomjoseph83 @dkodihal

**Comment by spinler** [comment]
To clarify - the count is how many times we turn on power, not necessarily how many times the host has booted all the way.

**Comment by rfrandse** [comment]
tracked by ibm-openbmc/dev#58
