### ISSUE TITLE
Add inventory UT

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2551]
Potentially in ipmid and openpower-vpd-parser.

**Comment by devenrao** [comment]
# **Status**
12/14 - Working on code changes. Got training from Ratan on gtest and gmock.

**Comment by devenrao** [comment]
phopshor-inventory-manager 
It has sufficient tests to cover various cases so do not see much scope for adding unit tests
ipmi-fru-parser
There is only one global method and as it is C code do not have much scope to write unit tests
openpower-vpd-parser
Tests present for parse and store, do not see much scope here.
