### ISSUE TITLE
After activating debug image, on multiple reboots switched back to old image

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#2564]
Pre-condition:
System is in dhcp mode
 version:

ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.10"
VERSION_ID="v1.99.10-113-g65edf7d-r9-0-g67617be"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.10"
BUILD_ID="v1.99.10-113-g65edf7d-r9"

Steps:
1. updated and activated debug image
2. on 1st reboot, sytstem was showing debug image version
3. After multiple reboots it switched back to old build

{
  "data": {
    "/xyz/openbmc_project/software/68967d96": {
      "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active",
      "Path": "",
      "Priority": 0,
      "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC",
      "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.Active",
      "Version": "v1.99.10-225-gd662943",
      "associations": [
        [
          "inventory",
          "activation",
          "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc"
        ]
      ]
    },
    "/xyz/openbmc_project/software/68967d96/inventory": {
      "endpoints": [
        "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc"
      ]
    },
    "/xyz/openbmc_project/software/68967d96/software_version": {
      "endpoints": [
        "/xyz/openbmc_project/software"
      ]
    },
    "/xyz/openbmc_project/software/e0e1ac80": {
      "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active",
      "Path": "",
      "Priority": 1,
      "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC",
      "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None",
      "Version": "v1.99.10-113-g65edf7d-r9-0-g67617be",
      "associations": [
        [
          "inventory",
          "activation",
          "/xyz/openbmc_project/inventory/system/chassis/motherboard/boxelder/bmc"
        ]
      ]
    },
  "message": "200 OK",
  "status": "ok"

**Comment by amboar** [comment]
@prkatti1 This issue references an IBM-internal tag. Please edit the issue to describe it in terms of publicly accessible tags. If that can't be done, then it's likely this issue should not be in the public issue tracker.

**Comment by prkatti1** [comment]
closing this as discussed with George, known issue.
