### ISSUE TITLE
Fix up InternalErrors to include metadata

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2568]
<cde:info> SW407475 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7831> Fix up InternalFailure to include metadata
Resolves openbmc/openbmc#2552,  #2568 Fix up InternalErrors to include metadata

**Comment by rfrandse** [comment]
@devenrao 
here are some internal errors that are raised that do not have accompanying error and meta data. Added additional error message and metadata that aids in debugging errors in field.

'InternalError' errors should have accompanying error messages and/or metadata.

**Comment by rfrandse** [comment]
commit merged.
https://gerrit.openbmc-project.xyz/7831 Fix up InternalFailure to include metadata
