### ISSUE TITLE
Watchdog: Provide device tree properties to indicate behavior

### ISSUE THREAD

**Issue by cbostic** [openbmc/openbmc#2569]
- [ ] Send Milton's fixes for device tree parsing to lkml mailing list.

- [ ] Add new device tree property to tell if we are to ping watchdog.

- [ ] Add 2nd device tree property to indicate if we are to enable booting from alternate bank.

- [ ] Identify what u-boot is doing with watchdog.  Differentiate between initial path and the reboot path.  Key off DRAM configuration as a guide.

Patches from Milton:
mdmillerii. github.com -   first two are relevant.

**Comment by geissonator** [comment]
Changes up on mailing list
