### ISSUE TITLE
Move obmc-pydevtools to tools package

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2571]
<cde:info> SW407488 </cde:info>

**Comment by anoo1** [comment]
On Witherspoon, we removed the packagegroup-obmc-apps-extrasdev to disable the rest-dbus package, but turns out that other packages like obmcutil are added to the extrasdev package. Need to only disable rest-dbus.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7853> Move obmc-pydevtools to tools package
Resolves  #2571 Witherspoon: obmcutil command utility not available ibm-v2.0-0-r2-0-g4b46995
