### ISSUE TITLE
mapper should only monitor for association property changes

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2573]
Currently mapper monitors for all property changes, we could greatly optimize this by modifying mapper to only monitor for property changes that are with associations.

The problem is that mapper is written in python and the Arg0 options (the easiest way to solve this problem) are not native so some innovation is needed to get this working in python.

Some discussion in this in https://gerrit.openbmc-project.xyz/#/c/7807/

FYI @bradbishop

**Comment by bradbishop** [comment]
I think @dkodihal said he was going to work on this.

**Comment by bradbishop** [comment]
https://gerrit.openbmc-project.xyz/#/c/7926/
