### ISSUE TITLE
Don't throw exception while validating the IP configuration.

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2576]
<cde:info> SW407820 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7882> Update Create.interface.yaml to return errors
Fixes  #2576 Don't throw exception while validating the IP configuration.

**Comment by rfrandse** [comment]
@ratagupt
During validation of network configuration,should not throw exception which will lead to core dump of the process.
We need to send the error through dbus interface.
Need to make the change in internal repo specific yaml to return the error.
