### ISSUE TITLE
Security Feature: Lockdown BMC chip

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#258]
This is a customer request agreed by to lockdown the chip from users for security reasons.

**Comment by anoo1** [comment]
Per previous discussions, this may need input from the IBM's LTC team to see if an interim implementation could be done sooner while the full lockdown feature is designed.

**Comment by williamspatrick** [comment]
This is not necessarily applicable to Witherspoon.  Marking as low priority for now.

**Comment by geissonator** [comment]
@amboar or @anoo1 any idea on what this one was tracking? Given it's age and our recent changes in this area, I assume we can just close this one out?

**Comment by amboar** [comment]
the "from users" is the unclear part. @anoo1 - what did that mean?

**Comment by amboar** [comment]
No-one cares, and given recent developments this has probably been taken care of.
