### ISSUE TITLE
User-initiated dump REST request does not respond with dump ID

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2592]
<cde:info> SW407893 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7889> Fix missing return value form do_post
Fixes  #2592 [Witherspoon] User-initiated dump REST request does not respond with dump ID

**Comment by rfrandse** [comment]
@ngorugan 
missing return value from do_post - For example user-initiated dump REST request has to respond with dump ID. This is not happening, the dump-manager is returning the ID, but rest-bus is not passing the ID to caller.
