### ISSUE TITLE
Implement PAM Authentication

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#260]
Some initial work found that adding the PAM package to openbmc makes the image too big to fit on flash. Also it turns off busybox. So this work would need some recipe manipulation to only add the desired PAM package to the image and prevent busybox from turning off busybox.

**Comment by amboar** [comment]
@anoo1 can we add some words explaining the motivation for introducing PAM? How do we plan to use it?

**Comment by anoo1** [comment]
@bradbishop will be able to provide a better background for implementing PAM.

**Comment by williamspatrick** [comment]
Should include:

1. Updating PAM recipe to ensure it fits on flash.
2. Converting login applications to use PAM.

**Comment by williamspatrick** [comment]
Created #545 for a portion of this.

**Comment by zahrens** [comment]
PAM based authentication (Total: 2pts)
a) Deploy PAM config files.
b) What does systemd have to offer in terms of PAM? Do we need to implement our own plugin?
d) Login implementation to use PAM. (2pts)

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/86
