### ISSUE TITLE
BitBake error for git branch --set-upstream

### ISSUE THREAD

**Issue by GHF** [openbmc/openbmc#2608]
The devs at Google are all running into the bug outlined by the fix at http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?h=morty&id=6da3e0a0abf1251db243548639979f8d74e99766

Anyone else with a bleeding edge git binary will encounter the same issue. We put in an internal fix with an identical diff but would prefer to the backport the above referenced fix.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8458> bitbake: Replace deprecated git branch parameter "--set-upstream"
(cherry-picked from unreleased Yocto 2.2.3. Fixes  #2608 BitBake error for git branch --set-upstream
