### ISSUE TITLE
SERIAL PORT USED BY PALMETTO

### ISSUE THREAD

**Issue by radhikapradeep** [openbmc/openbmc#2609]
Hi ,

We have just built the ibm openbmc code for platform palmetto and would like to know which is the serial port used by the ibm openbmc code.

Please help with the serial port query.

Thanks and Regards,
Radhika

**Comment by amboar** [comment]
Hi @radhikapradeep - there's a short piece of documentation in openbmc/docs that describes how to convert Palmetto to OpenBMC from AMI's firmware: https://github.com/openbmc/docs/blob/master/openbmc-conversion.md

**Comment by gtmills** [comment]
@amboar @radhikapradeep Can this be closed?

**Comment by amboar** [comment]
Yeah, closing this due to lack of response. I'll assume the OP was satisfied with the documentation.
