### ISSUE TITLE
SDR : MRW Parser

### ISSUE THREAD

**Issue by zahrens** [openbmc/openbmc#2611]

**Comment by anoo1** [comment]
Write an MRW parser that would generate a YAML file with the SDR information.
First it'd generate SDR records for all MRW items that have a sensor id.
Then it'd have some filtering mechanism to not add certain items that are not desired to be exposed via IPMI, like the boot count.
The YAML file later would be used by the IPMI code to be parsed via python / mako scripts.

**Comment by gtmills** [comment]
@anoo1 We still need?

**Comment by anoo1** [comment]
Closing since openbmc/openbmc#2612 already implemented reading from the MRW.
