### ISSUE TITLE
SDR mapping sensors to dbus objects - hwmon sensors

### ISSUE THREAD

**Issue by zahrens** [openbmc/openbmc#2613]

**Comment by dkodihal** [comment]
Need to update sensor input yaml(s) for the BMC sensors.

**Comment by dkodihal** [comment]
- [ ] Make sure every hardware sensor/hwmon sensor, which is in the sensors/ namespace has an entry with the same strcuture as the final sensors.yaml, in a hand-coded witherspoon specific yaml.
- [ ] Update the sensors MRW script to merge this hand-coded yaml and the generated yaml.
- [ ] Make sure hand-coded yaml has unique sensor numbers

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8818> Add witherspoon hardware sensors for SDR mapping to DBus objects
Resolves  #2613 SDR mapping sensors to dbus objects - hwmon sensors
