### ISSUE TITLE
Get SDR Repository Command

### ISSUE THREAD

**Issue by zahrens** [openbmc/openbmc#2614]

**Comment by dkodihal** [comment]
- [ ] We have an implementation of Get Device SDR Info - investigate if we need separate impl for Get Device SDR. In the least, point both commands to same implementation function.
- [ ] Make sure the information comes from both FRU and Sensors maps.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8884> Add Get Repository Info Command
resolves  #2614 Get SDR Repository Command
