### ISSUE TITLE
Get SDR Command

### ISSUE THREAD

**Issue by zahrens** [openbmc/openbmc#2615]

**Comment by dkodihal** [comment]
Need to figure out Get SDR vs Get Device SDR. Same goes for #2614.

**Comment by dkodihal** [comment]
- [ ] Figure out if we need both Get SDR and Get Device SDR. If yes, make sure implementations are registered for both commands.
- [ ] Make sure 'sdr list all' and 'sensor list' show appropriate output for all types of sensors. Start with one phosphor-hwmon entry in one of the final yamls.
- [ ] Evaluate that all fields of type 1 SDR are accounted for.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9101> Implement Get SDR command
Resolves  #2615 Get SDR Command
