### ISSUE TITLE
BMC time is going backwards after a reboot 

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2619]
<cde:info> SW407790 </cde:info>

**Comment by rfrandse** [comment]
@mine260309 
The dns server is empty in `/etc/resolv.conf`, and cause the BMC fails to access network via hostnames, and result in failure to sync NTP.
If it's set correctly, NTP time will sync and RTC time will be correct.
It looks like something wrong in `phosphor-networkd`?

**Comment by rfrandse** [comment]
@ratagupt 
Ratan is testing with the DNS resolver fix

**Comment by geissonator** [comment]
This one is no longer seen after setting up NTP correctly.
