### ISSUE TITLE
IPMI DCMI : chassis identify via LED

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2621]

**Comment by yongli3** [comment]
For this chassis ID command support, is there any more information/plan/code review?

**Comment by yongli3** [comment]
https://gerrit.openbmc-project.xyz/#/c/8086

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8086> Add chassis identify ipmi command.
Resolves  #2621 IPMI DCMI : chassis identify via LED
