### ISSUE TITLE
IPMI DCMI : Get sensor threshold

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2624]

**Comment by dkodihal** [comment]
- [ ] Map input sensor number to D-Bus object.
- [ ] Check if D-Bus object implements Sensor.Value and Sensor.Threshold interfaces - accordingly set bitfield to indicate existing thresholds.
- Convert threshold value to scale (using whatever math is required) and populate the response.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8588> Support Get Sensor Threshold Command
Resolves  #2624 IPMI DCMI : Get sensor threshold
