### ISSUE TITLE
IPMI DCMI : Get power reading

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2625]

**Comment by dkodihal** [comment]
- could be an aggregate of sensors
- sensor dbus name depends on hwmon config, so can't be hard coded.

**Comment by dkodihal** [comment]
- [ ] Need to investigate from which D-Bus object(s)/interface(s) current power reading can be read. May need to encode this in a data file, based on design discussion.
- [ ] Populate current power reading, in Watts, in the response. Fill up other fields of the response.
- [ ] For now, set min/max/avg reading to the same value as current. Open an issue to rework this when telemetry is in.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8573> DCMI: Populate response buffer with power reading
Resolves  #2625 IPMI DCMI : Get power reading
