### ISSUE TITLE
IPMI DCMI : Get temperature readings

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2626]
- Refers to ambient temperature

**Comment by dkodihal** [comment]
- [ ] Generate a JSON from MRW, which has - entity id, instances per id, sensor ids per entity id, D-Bus object (HWMON) pointing to the sensor. Maybe start off with hand-coding this YAML first.
- [ ] MRW has only CPU temp sensors. Need the inlet and baseboard sensors either in MRW or config YAML.
- [ ] Code to parse the JSON from above task.
- [ ] Code to implement the DCMI command.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8617> dcmi: get temperature readings: read temp sensors
Resolves  #2626 IPMI DCMI : Get temperature readings
