### ISSUE TITLE
GUI: OpenBMC GUI: Not able to login using Safari as browser

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#2627]
Problem Description:
Using bluemix app trying to launch openbmc GUI using Safari as browser. 
But failed to login. Where as Chrome browser able to open the same. 

Have shared the details with Karl Vochatzer on the same. 
![image](https://user-images.githubusercontent.com/19144129/32792436-5df80194-c989-11e7-8991-0b3bf0d61053.png)

**Comment by sivassrr** [comment]
In today's recreate, Observe that mail screen comes and goes back to login screen as a flash

**Comment by iftekharuli** [comment]
@sivassrr this is not the latest version. In the latest version login changed. We have host input now 

<img width="1140" alt="screen shot 2017-11-16 at 9 10 14 am" src="https://user-images.githubusercontent.com/4976631/32898534-0293f0a8-caae-11e7-95a5-406b167bd2d5.png">

**Comment by sivassrr** [comment]
Point is Safari browser not helping to log into the main screen. Its login and logsout immediately. Probably we can try that tomorrow.

**Comment by sivassrr** [comment]
Thank you @iftekharuli - With the code what you had provided able to log into BMC using safari browser, but it takes time and not coming out the below screen. 

![image](https://user-images.githubusercontent.com/19144129/32960444-e1156fc2-cbea-11e7-825f-b5021f5e2113.png)

**Comment by iftekharuli** [comment]
I was able to login and perform actions using safari. Let me know if this is still and issue 

![screen shot 2018-03-13 at 11 14 42 am](https://user-images.githubusercontent.com/4976631/37354505-d699444a-26af-11e8-8c82-1e7cf09b5d80.png)

**Comment by sivassrr** [comment]
Today also tried and able to use it successfully.. we can close
