### ISSUE TITLE
on click logout -  not happening

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#2649]
Continuation of  previous issue https://github.com/openbmc/openbmc/issues/2648

On click logout - not happening, Had to refresh and then it logs off. 

Expectation is to logoff after clicking logout button. ( Refresh should be avoided).

**Comment by iftekharuli** [comment]
This has been fixed. Let me know

**Comment by amboar** [comment]
@iftekharuli Please could link to the patch fixing the issue when making these comments? That way others can figure out what they need to do to get the fix.

**Comment by iftekharuli** [comment]
Duplicate https://github.com/openbmc/openbmc/issues/2737 
Also link for the the fix https://gerrit.openbmc-project.xyz/#/c/8828/

**Comment by gtmills** [comment]
This was a duplicate of #2737 and has been fixed with https://gerrit.openbmc-project.xyz/#/c/8828/.
