### ISSUE TITLE
Openbmc Redfish for 2.7 Release

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#265]
Track the Redfish work needed for OpenBMC's 2.7 Release

**Comment by vrpradeepkumar** [comment]
Hi,

Is there any plans regarding this?
Interested  to contribute in Redfish support.
If there is any plans/design or implementation which is already done regarding this please let me know.

Currently planning to support the network URI (redfish/v1/Managers/bmc/EthernetInterfaces/eth0) in Redfish.

Thanks
Pradeep

**Comment by mdmillerii** [comment]
There is some outline documentation talking about the requirements of an implementation in gerrit from @causten.

https://gerrit.openbmc-project.xyz/#/c/5792/

**Comment by krtaylor** [comment]
Firmware update design:
https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/18186/

**Comment by gtmills** [comment]
The following Redfish functionality was in 2.7: 
Firmware Update
Inventory
Logging
Network
Partial Certificates
Power & Thermal
State Management
Time
Management
User Management

The following Redfish functionality is planned for 2.8 (subject to change):


All Sensors
Event Service
Full Certificate Management
LDAP
LED
Multiple Firmware Image Support 
Telemetry Service
Subscription Collection
Virtual Media

**Comment by gtmills** [comment]
Closing this issue since 2.7 (warrior) was released in Aug 2019.
