### ISSUE TITLE
Refactor OpenPOWER features into MACHINE_FEATURES

### ISSUE THREAD

**Issue by GHF** [openbmc/openbmc#2652]
Currently OpenPOWER features are selected by building an image with meta-openpower included in `BBLAYERS`. However, our (Google's) internal builds are done with all layers included; enabled features are selected using the `MACHINE` variable, which will then pull in the necessary includes and build the appropriate packages. To make the meta-openpower play nice with this setup, I'd like to move the current packages into OpenPOWER-specific `MACHINE_FEATURES`.

For example in `meta-openbmc-machines/meta-openpower/common/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend` there is
```RDEPENDS_${PN}-inventory += "obmc-mgr-inventory"```
which I would change to
```RDEPENDS_${PN}-inventory_append := " ${@cf_enabled(d, 'obmc-openpower-legacy', 'obmc-mgr-inventory')}"```
so that it depends on the `obmc-openpower-legacy` feature being selected, which would be a thing that only OpenPOWER BMC builds would do.

The features I'm proposing are:

- `obmc-openpower` for required OpenPOWER support (e.g. host start, MRW)
- `obmc-openpower-extra` for non-essential tools (e.g. pdbg, pflash)
- `obmc-openpower-legacy` for deprecated packages (e.g. skeleton stuff)

and they'd all be selected by default for phosphor builds (present in `DISTRO_FEATURES`), but not built unless the machine supports them (present in `MACHINE_FEATURES`).

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7989> meta-openpower: Predicate packages on MACHINE_FEATURES
Fixes  #2652 Refactor OpenPOWER features into MACHINE_FEATURES
