### ISSUE TITLE
BMC 2.0 version, lan print 1 does not show VLAN , ZeroConfigIP question

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2664]
<cde:info> SW408847 </cde:info>

**Comment by rfrandse** [comment]
@ratagupt 
Problem description:- Through IPMI get LAN command doesn't show the vlan info.
However setLAN is not having issues.
...
Fix the getLan config. the filtering is during IPAddress parameter to avoid link local address but left it for subnetMask and vlan parameter. With the introduction of zeroconfig IP we have multiIPaddress can exist on the interface. the  commit introduces the filtering for subnetmask and vlan parameter also.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8022> Fix the getLan config
Resolves  #2664 BMC 2.0 version, lan print 1 does not show VLAN , ZeroConfigIP question
