### ISSUE TITLE
chassis_control.py in skeleton

### ISSUE THREAD

**Issue by yongli3** [openbmc/openbmc#2668]
These chassis control/system manager related projects in skeleton should be initial/reference code. I would like to know if there is any plan or on-going projects to replace them?

**Comment by gtmills** [comment]
@spinler Did we replace chassis_control.py ?

**Comment by yongli3** [comment]
@gtmills FYI actually we did something about the chassis and power control. Reactor them using sdbusplus. We are working on the upstreaming: https://gerrit.openbmc-project.xyz/#/c/openbmc/x86-power-control/+/11746/

**Comment by gtmills** [comment]
@yongli3 I see https://gerrit.openbmc-project.xyz/#/c/openbmc/x86-power-control/+/11746/ merged. Can we close?

**Comment by yongli3** [comment]
@gtmills YES, we can close now.
