### ISSUE TITLE
GPU Sensors incorrectly populated on system with 4 GPUs

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2674]
<cde:info> SW409181 </cde:info>

**Comment by spinler** [comment]
preliminary bridge. closing.

**Comment by spinler** [comment]
In the witherspoon OCC hwmon config files, it only allows for 32 temperatures to be reported per OCC, in the order of cores, DIMMs, GPUs.  On systems with high counts of good-core processors,  it will start skipping GPU temps.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8081> wspoon: add more OCC hwmon temps of mode 'label'
Resolves  #2674 GPU Sensors incorrectly populated on system with 4 GPUs
