### ISSUE TITLE
Run collection of changes through customer regression tests

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2679]
HW CI tests changes on a per commit basis (for the most part, unless it's grouped into a single bump request).  We need to take a collection of changes, prior to merge, and run them through some of our more thorough, and longer running regression suites.  In particular, functional areas that are not widely tested by other teams (factory resets, DHCP modes, ipmi, error paths).

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/71
