### ISSUE TITLE
Improve reporting of HW CI failures

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2680]
As we add additional machines to the HW CI pool, and add additional tests, we need to ensure we're reporting the failures in a consumable way.  A quick summary of the failure, a pointer to the relevant FFDC, and some easy mechanism for them to resubmit if infrastructure is at fault.

Currently all FFDC data is pushed out to github, we may want to revisit this, or enhance it.

**Comment by geissonator** [comment]
We made a change to export the data to dropbox.  Still not perfect but good enough for now (much faster and easier to access)

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/72
