### ISSUE TITLE
Enable performance testing in CI

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2681]
How do we ensure a change is not negatively impacting openbmc?  We've seen single line changes cause 50% additional CPU utilization.  Need to catch these types of things within our CI testing.  First need to identify how we measure performance, then use that metric in our runs.  Once we have a baseline, we need to add a check that ensures new code changes don't exceed it.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/73
