### ISSUE TITLE
Enhance CI test bucket (QEMU and HW)

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2682]
What robot tests can we add to get more coverage in both QEMU and HW situations without adding a lot of additional time?  Where have our regressions been that we need more coverage?
- New error logs
- Unexpected fails in the journal
- Intermittent errors
- Factory resets, DHCP modes
- BMC performance
- External interfaces (REST, IPMI, SSH)

#2272 will give us more options with QEMU, this should build on that.

**Comment by geissonator** [comment]
Current CI bucket is https://github.com/openbmc/openbmc-test-automation/blob/master/test_lists/HW_CI

Basically a REST api test, a power on, and a check for any application failures.

I think we should add:
- Verify no error logs generated
- Verify SSH and IPMI interfaces
- Verify the load averages in "uptime" do not exceed some upper limit (1 maybe?) - performance testing
- Verify code update from the image under test still works (ideally find a way to not require a full code update)
- Verify OCC active once host booted
- Add some additional REST api tests to get as much coverage as possible
- Verify a BMC reset with the host up (ensure proper states, no errors, and occ active)

**Comment by gkeishin** [comment]
@mtritz let me know if u need more info. We got most of them as a test case , so all you may need to do is create a test_list/QEMU_CI and include those TC's .

**Comment by anoo1** [comment]
Pending commits:
https://gerrit.openbmc-project.xyz/#/q/status:open+project:openbmc/openbmc-test-automation+branch:master+topic:2682

**Comment by gkeishin** [comment]
@ssombar We can abandon the gerrit and start fresh since a bunch of code restructure and base is done. So

**Comment by gkeishin** [comment]
- Add a whitelist error log such as power supply or any on demand. the best bet via an argument passed by the user explicitly
- Check for error and fail if there is a new error but ignore if the error generated is in the whitelist

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/74
