### ISSUE TITLE
Scale out build and test capabilities of openpower.xyz

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2683]
build-setup.sh is configured now to support kubernetes, can we get a cluster for this?  Should we try the swarm plugin for jenkins?  Can we get companies to volunteer a few more build servers?  As we add more and more testing (unit and qemu) we'll need more build power on openpower.xyz.  This story is to pursue the vision and implementation of this.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/75
