### ISSUE TITLE
Add device driver access to power supply PN/SN/etc

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2685]
We need to display the power supply part number and serial number (and maybe some other fields) in the inventory, so the device driver will need to expose it.  This is for the Witherspoon system.

**Comment by bjwyman** [comment]
6 bytes from MFR_SERIAL (9Eh) 
12 bytes from MFR_REVISION (9Bh) - Part Number
12 bytes from MFR_MODEL (9Ah) - FRU Number

**Comment by spinler** [comment]
While we're at it, maybe add a file for the firmware level too

**Comment by geissonator** [comment]
Code upstreamed, just need to get pulled into 4.10 kernel

**Comment by geissonator** [comment]
In 4.10 kernel
