### ISSUE TITLE
phosphor-hwmon-readd logging EAGAIN failures against OCCs

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2686]
<cde:info> SW407886 </cde:info>

**Comment by spinler** [comment]
The phosphor-hwmon code is using a uint32_t when reading hwmon values out of sysfs.  However, the power values, reported in microwatts, can overflow that.  When that happens, we've seen exceptions thrown as well as a mysterious EAGAIN errno logged.  Using this issue to extract an int64_t instead, which also matches the D-Bus property type the value will go into.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8097> Support reading 64 bit integers
Resolves  #2686 phosphor-hwmon-readd logging EAGAIN failures against OCCs
