### ISSUE TITLE
System: BMC Error Log, logs 100 errors and quits logging

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2687]
<cde:info> SW409493 </cde:info>

**Comment by ngorugan** [comment]
After 100 error logs have been logged no other errors are being logged.  Check stop errors are lost if any happen after the 100 errors have been logged.  This behavior may not be exceptable for systems in the field where the expectation is that the customer monitor and delete logs frequently .

**Comment by ngorugan** [comment]
With the assumption the CSM will periodically read and store errors in another repository, we are now going to roll errors as solution to this issue.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8102> Roll errors after reaching Cap size
Fixes  #2687 System: BMC Error Log, logs 100 errors and quits logging
