### ISSUE TITLE
[P8 openpower-occ-control]: unable to set power cap

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#2688]
The power cap setting is not enabled on P8 in `openpower-occ-control`, due to P8 is using i2c-occ instead of FSI.

This issue is to enable P8's power cap control.

**Comment by mine260309** [comment]
https://gerrit.openbmc-project.xyz/#/c/8104/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8104> Powercap: add p8 support
Fixes  #2688 [P8 openpower-occ-control]: unable to set power cap
