### ISSUE TITLE
Phosphor-logging : document API and usage

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2691]

**Comment by devenrao** [comment]
Following is expected from this issue
REST API and improvement on d-bus API

**Comment by devenrao** [comment]
# **Status**
12/14 - Pushed documentation changes, currently in review

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8262> Add README for logging
Resolves  #2691 Phosphor-logging : document API and usage
