### ISSUE TITLE
OpenBMC:Witherspoon:FVT- MAC address from REST will not show 0 when first nibble is 0

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2701]
<cde:info> SW407884 </cde:info>

**Comment by ngorugan** [comment]
Fix format specifier issue with MACAddress: we are using "%hhx:%hhx:%hhx:%hhx:%hhx:%hhx" as  format specifier while converting  array of integers to string using snprintf. we have to use "%02hhx:%02hhx:%02hhx:%02hhx:%02hhx:%02hhx".
-Here hh is to tell snprintf that the argument is an unsigned char. Use 0 to get zero padding and 2 to set the width to 2. x or X for lower/uppercase hex characters.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8143> Fix format specifier issue with MACAddress
Fixes  #2701 OpenBMC:Witherspoon:FVT- MAC address from REST will not show 0 when first nibble is 0
