### ISSUE TITLE
Control Error log entries using  policy driven.

### ISSUE THREAD

**Issue by ngorugan** [openbmc/openbmc#2702]
Right now we are rolling errors once we reach Cap size. It will good to control error logs using policy.

**Comment by geissonator** [comment]
Our RAS team has requested the ability to implement the following policy:

If FW needs to post an error and the log is full, then make space by taking the following actions in the order listed below until space is freed.
1) Delete the oldest log marked RESOLVED.  (these are logs which have been reviewed and are here for historical purposes only).  
2) Delete the oldest INFORMATIONAL log
3) Delete the oldest WARNING log
4) Delete the oldest CRITCIAL log
