### ISSUE TITLE
Recover from a dump-partition full scenario

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2703]
Witherspoon has a 32M flash. We've reserved 1M for OpenBMC dumps. Dumps could be of 3 types (at the moment) :

a) A user initiated dump - this dump could be about a 100K in size.
b) A dump automatically to collect information pertaining to an "InternalError", aka code bug. This dump is about 10K.
c) A dump to capture a core dump (core dumps are currently disabled). This dump could be large (about 100-200K).

Once you've hit the 1M cap, the dump creation API now tells you about an out of space error, and there are also APIs to delete one or all dumps. So a) shouldn't be a concern once the cap is hit, in fact to be still be able to do a) if the dump partition is full, we'd recommend to download and delete dumps.

We'd need to automatically recover to be able to continue doing b) and c) though.

Potential solutions :
a) Log an error indicating a dump partition full scenario, so that a customer can be notified.
b) Offload the dumps to a host partition once the dump partition is full.
c) An external app could periodically probe and offload dumps, or it could depend on a) to offload, or it could the OpenBMC event notification mechanism to be notified of dumps.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/128
