### ISSUE TITLE
System:Brick:Hostboot fails to attempt clearonecc on ECC corruption in PNOR

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2704]
<cde:info> SW409356 </cde:info>

**Comment by anoo1** [comment]
The virtual pnor partition table didn't have the 'clear on ecc error' flag (https://github.com/open-power/hostboot/blob/master/src/usr/pnor/common/ffs_hb.H) so hostboot doesn't attempt to fix ecc errors. Need to add the flags to the virtual toc.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8161> pnor_partition_table: Add all misc flags
Resolves  #2704 System:Brick:Hostboot fails to attempt clearonecc on ECC corruption in PNOR
