### ISSUE TITLE
Porting for application local errors

### ISSUE THREAD

**Issue by devenrao** [openbmc/openbmc#2705]
Following applications need to be catered for changes done to application local errors. At present it is done for open-power-debug-collector same needs to be done to below applications.

Applications should not be check-in manually generated elog-errors.hpp header file.

./phosphor-led-manager/elog-errors.hpp
./openpower-occ-control/elog-errors.hpp
./openpower-host-ipmi-oem/elog-errors.hpp
./phosphor-bmc-code-mgmt/elog-errors.hpp
./phosphor-host-ipmid/elog-errors.hpp
./phosphor-time-manager/elog-errors.hpp

**Comment by spinler** [comment]
Can you also look at witherspoon-pfault-analysis?

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8349> Enable obmcconsole script for elog type error
Resolves  #2705 Porting for application local errors

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8394> op-occ-control: add native recipe to install error yaml to shared location
Partially resolves  #2705 Porting for application local errors

**Comment by bjwyman** [comment]
WARNING: openpower-occ-control-1.0-r1 do_configure: QA Issue: openpower-occ-control: configure was passed unrecognised options: --disable-gen_errors [unknown-configure-option]

Seems that the --disable-gen_errors part of the recipe did not have a matching change in all the other affected repos.

**Comment by devenrao** [comment]
There is a patch pending to be merged, working on it.
 
----- Original message -----From: "B. J. Wyman" <notifications@github.com>To: openbmc/openbmc <openbmc@noreply.github.com>Cc: MARRI DEVENDER RAO <devenrao@in.ibm.com>, Assign <assign@noreply.github.com>Subject: Re: [openbmc/openbmc] Porting for application local errors (#2705)Date: Fri, Feb 2, 2018 5:33 AM 
WARNING: openpower-occ-control-1.0-r1 do_configure: QA Issue: openpower-occ-control: configure was passed unrecognised options: --disable-gen_errors [unknown-configure-option]
Seems that the --disable-gen_errors part of the recipe did not have a matching change in all the other affected repos.

**Comment by bjwyman** [comment]
Assuming you are referring to this up on gerrit:
https://gerrit.openbmc-project.xyz/8383
