### ISSUE TITLE
Improve fan speed control to minimize fan speed oscillations

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2710]
<cde:info> SW410936 </cde:info>

**Comment by msbarth** [comment]
This is a change in requirements for determining when fan speed decreases are allowed to occur based on multiple sets of sensor groups.

**Comment by msbarth** [comment]
Fix is complete with patch available for thermal to verify. I'm not able to test due to hardware availability to reproduce the scenario correctly that exhibited these oscillations.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8312> Decreases allowed based on all groups
Resolves  #2710 Improve fan speed control to minimize fan speed oscillations
