### ISSUE TITLE
Don't consider voltage warnings as faults

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2714]
This is only for Witherspoon.

The original requirement for the power sequencer monitoring code was to consider a voltage rail to be faulted if any bits were on in its status_vout response.  However, bits 6, 5, 3, and 1 are just warning bits and shouldn't have faults logged if just those bits are on.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8297> Don't log errors for voltage warnings
Resolves  #2714 Don't consider voltage warnings as faults
