### ISSUE TITLE
 Common.Error.InternalFailure on WS-Seq-FW-1 with 910.1746.20171208a

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2716]
<cde:info> SW410869 </cde:info>

**Comment by ojayanth** [comment]
Missing PID specific Journal info for the internal failure reported during BMC reboot path.  to debug these kind of failure need journal info . This issue used for adding enhancement to BMC dump to collect last 500 journal entries when the PID is not present.  That will ensure we always have needed FFDC for whatever is causing this failure.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8435> dreport: Collect journal log incase PID is not present
Resolves  #2716  Common.Error.InternalFailure on WS-Seq-FW-1 with 910.1746.20171208a
