### ISSUE TITLE
Enhance mapper FFDC on service discovery failures

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2718]
We had a recent defect where mapper failed to discover a service.  The theory is that it was BMC performance related but there was no conclusive data due to there being no exception back trace on the failure.  All we got was this:

```
Dec 13 16:39:38 witherspoon phosphor-mapper[1126]: xyz.openbmc_project.Network discovery failure on /
Dec 13 16:39:38 witherspoon phosphor-mapper[1126]: None
```

This issue is to track enhancing the FFDC when this failure occurs.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8319> server: Log additional information for discovery
Resolves:  #2718 Enhance mapper FFDC on service discovery failures
