### ISSUE TITLE
 FVT : BMC Image priority set to 4 by default on factory reset

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2721]
<cde:info> SW410103 </cde:info>

**Comment by mtritz** [comment]
On a BMC factory reset, BMC priorities are _sometimes_ restored incorrectly because serialize.cpp checks for "[versionid]" instead of "[versionid]="

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8315> Fix for priority restoration from environment variable
Resolves  #2721  FVT : BMC Image priority set to 4 by default on factory reset
