### ISSUE TITLE
System: Initiate dump when host is checkstopped

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2725]
<cde:info> SW411583 </cde:info>

**Comment by geissonator** [comment]
The host team has requested we generate a BMC dump when a checkstop occurs.  The main reason for this is that our dump will collect the host console log which is very useful for debugging the different checkstops.  This issue will be used to add the host console to the error based BMC dumps and to collect this BMC dump when the org.open_power.Host.Boot.Error.Checkstop error is created.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8349> Enable obmcconsole script for elog type error
Resolves  #2725 System: Initiate dump when host is checkstopped

**Comment by ojayanth** [comment]
Need to redesign the code to address the review comments from @bradbishop

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8349> Enable obmcconsole script for elog type error
Resolves  #2725 System: Initiate dump when host is checkstopped

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/150
