### ISSUE TITLE
OpenBMC GUI - In the title frame IP address of the system and Name has to display properly

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2729]
![ip address and system name](https://user-images.githubusercontent.com/29222610/34158698-6d8794e8-e4ec-11e7-946c-6d9a6994e17c.png)

**Comment by sivassrr** [comment]
@samahaba I had already opened an issue for this. 
I think it is dup of https://github.com/openbmc/openbmc/issues/2648

**Comment by samahaba** [comment]
see here one more issue is there that is it is showing label as "BMC IP address" but in front of this system name is displaying that is "002.aus.stglabs.ibm.com". Here system name is also not correct it should display as "wsbmc002.aus.stglabs.ibm.com" not simply as "002.XXX.XXX.com"

**Comment by samahaba** [comment]
Please here am requesting you that it will be good if you discuss with me before closing the issue as like this
