### ISSUE TITLE
OpenBMC GUI - Editing of System name is not possible

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2730]
![systmename editing](https://user-images.githubusercontent.com/29222610/34159539-a5438f24-e4ef-11e7-9659-ce51c60b37b7.png)

**Comment by iftekharuli** [comment]
@ratagupt I must have asked you this before- what is the rest command to rename the system name?

**Comment by ratagupt** [comment]
@iftekharuli I thought I had given it before in the mail which I sent it few months back :)
Anyways you can refer the section("Configure HostName") in the following link.
https://gerrit.openbmc-project.xyz/#/c/6872/5/xyz/openbmc_project/Network/README.md

**Comment by gtmills** [comment]
same issue here: https://github.com/openbmc/openbmc/issues/3104

**Comment by gtmills** [comment]
Going to close this issue since is the same issue as #3104. Typically I would close the newer one and dub to the older one, but the newer has a TODO in the code.
