### ISSUE TITLE
OpenBMC GUI - System Model Name is Blank

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2734]
![system model name is blank](https://user-images.githubusercontent.com/29222610/34206678-8efcc384-e5ad-11e7-9fd8-e6d5a0848951.png)

**Comment by iftekharuli** [comment]
"/xyz/openbmc_project/inventory/system": {
      "AssetTag": "", 
      "BuildDate": "", 
      "Cached": 0, 
      "FieldReplaceable": 0, 
      "Manufacturer": "", 
      **"Model": "8286-42B",** 
      "PartNumber": "", 
      "Present": 1, 
      "PrettyName": "", 
      "SerialNumber": "wsbmc011"

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/#/c/10124/ fixed this. The server overview page was not looking at /xyz/openbmc_project/inventory/system, 10124 fixed that. closing
