### ISSUE TITLE
OpenBMC GUI - Logout functionality is not working properly

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2737]
![logout functionality is not working properly](https://user-images.githubusercontent.com/29222610/34207832-119ee73c-e5b2-11e7-86a0-595d8d4caa3f.png)

**Comment by sivassrr** [comment]
If we do refresh then it logs out.  We need to have auto refresh and logout.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8828> Fixing the logout issue in webui
fixes  #2737 OpenBMC GUI - Logout functionality is not working properly
