### ISSUE TITLE
OpenBMC:System:FVT- BMC loses IP and change mode from DHCP to static when we turn-off vlan via IPMI

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2738]
<cde:info> SW411481 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8347> LANConf: Minor Fixes
Resolves  #2738 OpenBMC:System:FVT- BMC loses IP and change mode from DHCP to static when we turn-off vlan via IPMI
