### ISSUE TITLE
System:yl13ui:BMC Journal:phosphor-network-manager spamming journal

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2739]
<cde:info> SW411680 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8361> Don't handle the ipv6 routing advertisement message
Resolves  #2739 System:yl13ui:BMC Journal:phosphor-network-manager spamming journal

**Comment by ratagupt** [comment]
In an ipv6 auto conf enabled network where the router advertises the prefix and BMC gets this advertisement message and configure the IP on the interface,In this env router keeps sending the prefix and BMC keeps adding the IP and as part of handling any ip change BMC refreshes  the dbus objects.
