### ISSUE TITLE
OpenBMC GUI - "Users" main menu -> "Manage user account" Sub menu is not working

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2741]
![manage user account submenu is not working](https://user-images.githubusercontent.com/29222610/34300832-005016aa-e750-11e7-95df-f3279c24a0b1.png)

**Comment by samahaba** [comment]
"Manage user account" sub menu functionality is not working as per the latest OpenBMC gui code dated 22nd December 2017

**Comment by samahaba** [comment]
"Manage user account" sub menu functionality is not working as per the latest OpenBMC gui code dated 22nd December 2017. phosphor-webui-master code repo

**Comment by iftekharuli** [comment]
We did not code this part due to the lack of the completion rest command when we handed off the GUI. This is being resolved now in https://github.com/openbmc/openbmc/issues/2741

**Comment by gtmills** [comment]
https://gerrit.openbmc-project.xyz/#/c/9610 resolves this

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9610> Display error and success text
Resolves  #2741 OpenBMC GUI - "Users" main menu -> "Manage user account" Sub menu is not working
