### ISSUE TITLE
qemu-system-arm palmetto error

### ISSUE THREAD

**Issue by lockless** [openbmc/openbmc#2742]
I try to emulate palmetto, when type:

    root@Ubuntu:/home/skunlin/qemu/build/arm-softmmu# ./qemu-system-arm -m 256 -M palmetto-bmc -nographic -drive file=./flash-palmetto,format=raw,if=mtd -net nic -net user,hostfwd=:127.0.0.1:2222-:22,hostfwd=:127.0.0.1:2443-:443,hostname=qemu

the screen output follow information, then the cpu 100%, and can't continue anymore.

    qemu-system-arm: Aspeed iBT has no chardev backend

    DRAM Init-DDR3
    CBR0-1

when try ssh the ,it seems no response.

    root@Ubuntu:/home/skunlin/qemu/build/arm-softmmu# curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://localhost:2443/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"

can i get some advise?

**Comment by bgrupczy** [comment]
> On Dec 25, 2017, at 9:51 PM, lockless <notifications@github.com> wrote:
> 
> I try to emulate palmetto, when type:
> 
> root@Ubuntu:/home/skunlin/qemu/build/arm-softmmu# ./qemu-system-arm -m 256 -M palmetto-bmc -nographic -drive file=./flash-palmetto,format=raw,if=mtd -net nic -net user,hostfwd=:127.0.0.1:2222-:22,hostfwd=:127.0.0.1:2443-:443,hostname=qemu
> the screen output follow information, then the cpu 100%, and can't continue anymore.
> 
> qemu-system-arm: Aspeed iBT has no chardev backend
> 
> DRAM Init-DDR3
> CBR0-1
> when try ssh the ,it seems no response.
> 
> root@Ubuntu:/home/skunlin/qemu/build/arm-softmmu# curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://localhost:2443/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"
> can i get some advise?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

I had the same issue with my first build. I did a clean pull, rebuilt, and it started working. It’s the only “solution” I have to offer. You may want to keep your existing image for someone to look at. 

It has not booted up so you will not be able to ssh or anything else with it. 

-Brad

Sent from my iPhone

**Comment by lockless** [comment]
I suppose the build process has no problem.
When using the "flash-palmetto" download from autobuild "https://openpower.xyz/", it has the same output.
