### ISSUE TITLE
OpenBMC GUI - Sub menu is not hiding or closing

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2743]
![click any ware other than menu and sub menu area](https://user-images.githubusercontent.com/29222610/34353328-68c3af12-ea4d-11e7-8391-b7dac397ae93.png)

**Comment by samahaba** [comment]
Problem Description.
Open any sub menu and click any ware other than menu and sub menu area the sub menu should hide/close but here it is not hide/close.

**Comment by sivassrr** [comment]
@samahaba Do you want header to get close? Header will be always there to display the current status about the system. Below the header, frames applicable to that will get change. 

Or, You are asking about the frame itself. Getting confuse with your arrow. May be you want to highlight with right circle/  rectangle / square box.

**Comment by samahaba** [comment]
If I click some are on the gui is should hide.. If you want I will show you the demo that what is expectation if  the GUI is more user friendly from the user prospective.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8915> Fixing the submenu closing issue
fixes  #2743 OpenBMC GUI - Sub menu is not hiding or closing
