### ISSUE TITLE
OpenBMC GUI - "Server health" -> "Event log", option "Medium" is not able to select independently 

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2744]
![high option should be disabled](https://user-images.githubusercontent.com/29222610/34353540-c9c5572e-ea4e-11e7-9847-4739470de072.png)

**Comment by samahaba** [comment]
Problem Description
-----------------------

1. Go to  "Server health" -> "Event log"
2. Click button "High" and then click "Medium" button. here indicate/looks that both "High" and "Medium" buttons are selected, but "High" button has to deselect after clicking on "Medium" button.

**Comment by iftekharuli** [comment]
yes. You are correct. That is how we wanted to design. The idea was to be able to select multiple events together. Meaning- lets say someone wants to see both high and medium events, they click on both- high and medium events are shown. If they want to see medium events only. they have to deselect high events like you mentioned by clicking on high again.


Let me know if you have any more questions, thanks!

**Comment by iftekharuli** [comment]
@samahaba this is similar to #2750 .. I have replied in detail about the behavior. Let me know if you need more info

**Comment by gtmills** [comment]
The GUI was designed this way. Closing this issue.
