### ISSUE TITLE
Document to describe OpenBMC bitbake layers and how a person would go about adding a new system

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2754]
A lot of requests on the mailing list about supporting new systems, and what we currently support for AST boards. Add a document to describe this. This document should include information about the bitbake layers, kernel config parts, and device tree type stuff.

**Comment by gtmills** [comment]
Adding a README to several OpenBMC Yocto layers
From https://community.nxp.com/docs/DOC-331917 
"- A README with information regarding what’s contained in the layer and any dependencies"

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/110
