### ISSUE TITLE
did openbmc have some command or tools for upgrade the firmware?

### ISSUE THREAD

**Issue by lockless** [openbmc/openbmc#2760]
I use the GUI to download ta new firmware like this：
![image](https://user-images.githubusercontent.com/13847809/34593533-6f33ea0e-f206-11e7-99e3-4d3da4738c75.png)

then， there has flash-garrison image in dir /tmp/

$ ls /tmp/
**flash-garrison**                                                                     systemd-private-ea3e9f4c508543bbb3a7201b16a14026-systemd-timesyncd.service-zbrl2h
images

so， is there any command or tools i can use to upgrade the system to this version？

thanks！

**Comment by mine260309** [comment]
The docs provides nice information about this:
https://github.com/openbmc/docs/tree/master/code-update

**Comment by lockless** [comment]
thanks， it is helpful
