### ISSUE TITLE
Using FW 1743Ef, BMC is NotReady but REST returns OK (Inconsistent data)

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2761]
<cde:info> SW409841 </cde:info>

**Comment by gtmills** [comment]
@ojayanth @dkodihal Can someone fix this title? 1743Ef is an internal IBM release.

**Comment by gtmills** [comment]
@ojayanth @dkodihal Can we close? If not can a description be added and the title updated?
