### ISSUE TITLE
os-release.bb.do_compile: the basehash value changed from 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2769]
Keep hitting this when building OpenBMC GitHub master 

```NOTE: Running task 4005 of 4012 (/home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d4ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d438762ab76eb34ab2faa33293eb8ae/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from 72608cf46133892bd90965ab600479f6 to 41acf8081776de52d4b8a643f3f33b4f. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d438762ab76eb34ab2faa33293eb8ae/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from 72608cf46133892bd90965ab600479f6 to 41acf8081776de52d4b8a643f3f33b4f. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d438762ab76eb34ab2faa33293eb8ae/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from 72608cf46133892bd90965ab600479f6 to 41acf8081776de52d4b8a643f3f33b4f. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d438762ab76eb34ab2faa33293eb8ae/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from 72608cf46133892bd90965ab600479f6 to 41acf8081776de52d4b8a643f3f33b4f. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d438762ab76eb34ab2faa33293eb8ae/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from 72608cf46133892bd90965ab600479f6 to 41acf8081776de52d4b8a643f3f33b4f. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d438762ab76eb34ab2faa33293eb8ae/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from 72608cf46133892bd90965ab600479f6 to 41acf8081776de52d4b8a643f3f33b4f. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/f88f5a8b5d438762ab76eb34ab2faa33293eb8ae/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from 72608cf46133892bd90965ab600479f6 to 41acf8081776de52d4b8a643f3f33b4f. The metadata is not deterministic and this needs to be fixed.
Build failed
```
Deleting the current shared state caches did not help. 
  
I see this from Rick https://www.kc8apf.net/2017/01/tired-of-taskhash-mismatch/
  
 37a0e4ddff58c0120cc5cfef104b60d0e180638c is the failing commit.

3c4c45d1e9a2324191a8640b22df1b71f15f3037 succeeded,  37a0e4ddff58c0120cc5cfef104b60d0e180638c failed

**Comment by sdturne** [comment]
Does anybody have any insight here?  This failure tends to occur when we run a full clean build in a new output tree, but when pointing to an existing shared-state cache from a previous build.  The failure causes the os-release file to not be generated.  Re-attempting that same build (same source) in yet another clean output tree, but against the share-state cache updated by the previous (failed) run usually succeeds (!), but the os-release file is still not generated.

**Comment by gtmills** [comment]
@bradbishop Can you have a look at this when you get a chance.

**Comment by sdturne** [comment]
We're now seeing that the shared state cache has nothing to do with this failure; we're seeing it on every build, and every platform we build (barreleye, romulus, witherspoon, and zaius).  We're running full clean builds with clean output trees and no pre-existing shared state cache.  Output from this morning's witherspoon build:

NOTE: recipe obmc-phosphor-image-1.ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/e5716703022a0d9ce8591a11f43f741abf265385/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from ad7e2efb5361c2980324f4371e372115 to e0825d05a629a48fca8c92390fb186f0. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/e5716703022a0d9ce8591a11f43f741abf265385/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from ad7e2efb5361c2980324f4371e372115 to e0825d05a629a48fca8c92390fb186f0. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/e5716703022a0d9ce8591a11f43f741abf265385/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from ad7e2efb5361c2980324f4371e372115 to e0825d05a629a48fca8c92390fb186f0. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/e5716703022a0d9ce8591a11f43f741abf265385/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from ad7e2efb5361c2980324f4371e372115 to e0825d05a629a48fca8c92390fb186f0. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/e5716703022a0d9ce8591a11f43f741abf265385/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from ad7e2efb5361c2980324f4371e372115 to e0825d05a629a48fca8c92390fb186f0. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/bmcbuild/releases/obmc910/Builds/extract/e5716703022a0d9ce8591a11f43f741abf265385/meta/recipes-core/os-release/os-release.bb.do_compile, the basehash value changed from ad7e2efb5361c2980324f4371e372115 to e0825d05a629a48fca8c92390fb186f0. The metadata is not deterministic and this needs to be fixed.
Build failed

**Comment by gtmills** [comment]
"out-of-tree" still fails. This is still a problem.
