### ISSUE TITLE
GUI: Codeupdate "Upload firmware" hangs

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#2770]
Problem Description:
Tried to do code update via openbmc GUI, But GUI struck for more than half an hour in the same position.

![guicodeupdatewsbmc015](https://user-images.githubusercontent.com/19144129/34732870-84846b7a-f58c-11e7-9358-4a6702009e75.jpg)
[journlactlcodeupdatewsbmc015.txt](https://github.com/openbmc/openbmc/files/1615933/journlactlcodeupdatewsbmc015.txt)

**Comment by sivassrr** [comment]
Tried PNOR image as well, same behaviour observed.

**Comment by gtmills** [comment]
Choosing an image then pressing "Upload firmware" hangs. No commands to upload the image are sent to the BMC.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9056> Fix the "Upload firmware" button
Resolves  #2770 GUI: Codeupdate "Upload firmware" hangs
