### ISSUE TITLE
OpenBMC GUI: Events export as CSV option missing

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#2772]
![eventlogcsvoption](https://user-images.githubusercontent.com/19144129/34755735-1e8f3ede-f5ec-11e7-88b5-9232bcfa04e7.jpg)

When we were using GUI sandbox / Bluemix way, We used to observe CSV export options in Eventlog screen. Currently that is missing.

**Comment by iftekharuli** [comment]
We made that export function available for sensor page. One thing to mention here though, talking to sponsor users we found out json is a much desirable format for them, not CSV.

**Comment by iftekharuli** [comment]
This push https://gerrit.openbmc-project.xyz/#/c/9730/   fixes this issue

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9730> Add Events export as json functionality
fixes  #2772 OpenBMC GUI: Events export as CSV option missing

**Comment by gtmills** [comment]
The change is for exporting JSON format only. Is this okay, or is CSV format needed?  @sivassrr

**Comment by sivassrr** [comment]
If we are planning to export as CSV as well, then we can have this issue/story open. Otherwise, We can close ,  I guess.

**Comment by gtmills** [comment]
No plan to support CSV closing.
