### ISSUE TITLE
to run the aspeed 2400 chip what is minimum openBmc code

### ISSUE THREAD

**Issue by sdemirhan** [openbmc/openbmc#2773]
Hi All,
I just wonder of that is there any openbmc code that only prints something using seri channel when aspeed 2400 is power on. before or after bmc access to ram or flash, aspeed again prints something on seri channel. I actually want to debug bmc chip. Do you have any recommends for that?

Thank you for your time.

**Comment by gtmills** [comment]
@amboar Can you answer @sdemirhan's question above?

**Comment by amboar** [comment]
Hi @sdemirhan, this is a good question for the mailing list, as it's not a bug for or feature request. You can sign yourself up at for the list at https://lists.ozlabs.org/listinfo/openbmc

Thanks,

Andrew
