### ISSUE TITLE
Add checkstop sensor to non-Barreleye platforms

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#278]
Change https://github.com/openbmc/skeleton/pull/74 added the handling of the checkstop sensor so that the BMC resets the system if the OS is hung. It also added the checkstop sensor to Barreleye.
Need to look up the specifications for the other supported openbmc platforms like palmetto, garrison, etc and add the checkstop sensor as well so that they make use of this function for handling OS checkstops.

**Comment by anoo1** [comment]
Added with https://github.com/openbmc/skeleton/commit/b4140b888f586c98c5d03893166c5074a98cf951

**Comment by williamspatrick** [comment]
Oops.  We should have put that in the commit message.

'Closes openbmc/openbmc#278.'

**Comment by anoo1** [comment]
Yeah, next time 👍
