### ISSUE TITLE
After the obtainment of IP address by DHCP, it would be changed to 169.254.x.x

### ISSUE THREAD

**Issue by henbin** [openbmc/openbmc#2782]
Hi,
As the tittle, do anyone meet the identical symptom?
Why could the link local addressing override the IP address even BMC got the valid IP address from DHCP server?

The IP address **10.99.241.174** was obtained from DHCP server.
![link_local_01](https://user-images.githubusercontent.com/21031064/34859153-78c1597e-f78f-11e7-97b8-3702b8552357.png)

The IP address would become **169.254.54.0** after several seconds.
![link_local_02](https://user-images.githubusercontent.com/21031064/34859162-7ff57536-f78f-11e7-818d-524612ac8c62.png)

The issue would disappear if I set **LinkLocalAddressing=no** in the **/etc/systemd/network/00-bmc-eth0.network**

**Comment by mine260309** [comment]
OpenBMC supports [IP_aliasing](https://en.wikipedia.org/wiki/IP_aliasing), so you would see multiple IPs on an interface via `ip addr`.
`ifconfig` is deprecated, please use `ip` instead.

**Comment by henbin** [comment]
Thanks @mine260309 
I got the point.
![link_local_03](https://user-images.githubusercontent.com/21031064/34861102-4cc8c2a4-f79d-11e7-93cc-9a5411e96084.png)
