### ISSUE TITLE
MAX31785revA is reporting faulted rear rotor in different words

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#2798]
An update is needed due to an issue within the MAX31785revA to ensure the reporting of each fan rotor in a dual rotor fan assembly is handled correctly within the fan monitor application. The spec for the MAX31785revA does not match the implementation within the chip when the rear rotor is faulted where the faulted rotor is reported in the first word of the READ_FAN_SPEED_1 reg when a target RPM is reached, but is reported in the second word of the READ_FAN_SPEED_1 reg when the chip is transitioning the fans to a newly requested target RPM.

**Comment by msbarth** [comment]
MAX31785revA rotor feedbacks appear to be in a slow/fast relationship in the READ_FAN_SPEED_1 register, therefore the fan*_0 object will always represent the slowest rotor (may or may not be the front) and marked non-functional first. Since the MAX31785revA latches its TACHSEL = 0 during a speed transition, no rotor(or fan) should have its functional state updated during a speed transition.

- [ ] Include all rotors within a trust group and determine a transition is occuring by all _1 rotors = 0 tach
- [ ] Stop all timers while transitioning to a target RPM(store current timer and restore after target reached?)
- [ ] Update fan*_0 object's functional state based on the first set of fan*_input sysfs files
- [ ] The fan*_1 object's functional state is based on the fast rotor, therefore to be faulted fan*_0 must be if a faulted state first (due to comparing target & feedback speeds when not transitioning)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9084> wspoon: MAX31785revA fan controller workaround
Resolves  #2798 MAX31785revA is reporting faulted rear rotor in different words
