### ISSUE TITLE
PreTag 0.8 Testing failure for 'Set the power with string of characters'

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#280]
Robot Test Case failed
Full Name: 	Tests.Test Generic Conf.Set the power with string of characters
Documentation: 	

**BAD PATH** This test case set the power values with string of characters Expectation is to return error.
Start / End / Elapsed: 	20160519 15:17:43.333 / 20160519 15:17:46.618 / 00:00:03.285
Status: 	FAIL (critical)
Message: 	''abcdefg'=='abcdefg'' should not be true.

**Comment by rahulmah** [comment]
@ratagupt : Can you please look at this failure. I think this test case was never working.

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc-test-automation #17](https://github.com/openbmc/openbmc-test-automation/issues/17) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gkeishin** [comment]
https://github.com/openbmc/openbmc-test-automation/issues/17#issuecomment-240934248
