### ISSUE TITLE
SNMP Support in OpenBMC

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2800]
Need to investigate what we have and what is available.   There was talk that we did some light version @ratagupt @bradbishop ?

**Comment by geissonator** [comment]
Once initial work done we'll need to size it up and pick a milestone.

**Comment by jpmulhol-ibm** [comment]
We have customers asking for SNMP trap functions.  They had this available on p8 BMC based systems and see this as a loss of function between p8 and p9 openBMC.  Commenting to ensure that traps are included in SNMP functionality.

**Comment by AlexanderAmelkin** [comment]
I believe this issue has to be linked to #3002, #3004, and #3005.
Please take a look at https://github.com/YADRO-KNS/phosphor-snmp

**Comment by liudubang** [comment]
I just know how to config in the web ,but don't know how to use in other pc get a trap, can you give me some example,thanks
