### ISSUE TITLE
PreTag 0.8 Testing failure for 'Set the boot flags with string'

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#282]
Full Name: 	Tests.Test Generic Conf.Set the boot flags with string
Documentation: 	

**BAD PATH** This test case sets the boot flag with some invalid string Expectation is it should not be set.
Start / End / Elapsed: 	20160519 15:17:57.046 / 20160519 15:18:00.763 / 00:00:03.717
Status: 	FAIL (critical)
Message: 	3ab56f == 3ab56f

**Comment by rahulmah** [comment]
@ratagupt : I think this test case was never passing. Please let me know if it has ever worked.

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc-test-automation #19](https://github.com/openbmc/openbmc-test-automation/issues/19) via [**ZenHub**](https://www.zenhub.com/)
