### ISSUE TITLE
SDR mapping sensors to dbus objects - BMC FRUs and non-MRW systems

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2823]
Mostly requires updates to FRU config yamls with what @ratagupt is proposing in #2776.

**Comment by dkodihal** [comment]
- [ ] Make sure SRD w.r.t FRUs work with 'FRU print' abd 'sdr list' command.
- [ ] Make appropriate changes to the BMC hand-coded FRU yaml.
- [ ] Handle changes for for non-MRW based system yamls.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8765> FRU:- Add entityID and entityInstance property for BMC FRUS
Partially Resolves  #2823 SDR mapping sensors to dbus objects - BMC FRUs and non-MRW systems
