### ISSUE TITLE
IBM Milestone 3 : BMC Image FIT Verification

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2829]
Epic for checking FIT in u-boot before booting from a newly flashed image.

**Comment by anoo1** [comment]
A reference link from Yugi - https://chromium.googlesource.com/chromiumos/third_party/u-boot-next/+/chromeos-v2013.06/doc/uImage.FIT

**Comment by anoo1** [comment]
This should probably also ensure that netbooted images are verified.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/129
