### ISSUE TITLE
PreTag 0.8 Testing failure for 'minimal fan inventory'

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#283]
Full Name: 	Tests.Test Inventory.minimal fan inventory
Start / End / Elapsed: 	20160519 15:20:33.029 / 20160519 15:20:33.050 / 00:00:00.021
Status: 	FAIL (critical)
Message: 	'0>4' should be true.

This test checks the number of fans with a presence value of 'True' .  Seems like there is not any

**Comment by rahulmah** [comment]
Same issue is also seen with miminum cpu, dimm, memory buffer and core.

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc-test-automation #20](https://github.com/openbmc/openbmc-test-automation/issues/20) via [**ZenHub**](https://www.zenhub.com/)
