### ISSUE TITLE
 host off / chassis on after BMC reset from runtime on System system

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2832]
<cde:info> SW413639 </cde:info>

**Comment by geissonator** [comment]
OpenBMC is dealing with some performance issues right after
    a reboot. Systemd does almost too good a job at parallelizing
    all of the services which causes a 6X hit on the processor
    during the initial boot once mapper is ready.
    
    In situations where the BMC is rebooted when the host is up,
    this performance issue coupled with errors queued up by the
    host to send down to the BMC, can cause OpenBMC to exceed
    its current 3 second timeout for attentions.
    
    This initial message from OpenBMC to the host is done to
    check if the host is running. If the message times out then
    it's assumed the host is not running which causes all sorts

My proposal for now is to just bump up the timeout that we give the host to respond.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8679> Increase timeout for host to respond to attentions
Resolves  #2832  host off / chassis on after BMC reset from runtime on witherspoon system

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8679> Increase timeout for host to respond to attentions
Resolves  #2832  host off / chassis on after BMC reset from runtime on witherspoon system
