### ISSUE TITLE
Have PowerSupplyRedundancy persist across reboots and code updates

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2833]
<cde:info> SW415250 </cde:info>

**Comment by geissonator** [comment]
The PowerSupplyRedundancy sensor is used by the Host to know whether the system has redundant power supply support. The sensor is implemented under the legacy openbmc/pyphosphor repo which does not persist it's values.  This commit will move this sensor into the official phosphor settings repo (which does have persistency support) but also keep the legacy interfaces in place for backwards compatibility.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8686> Point PowerSupplyRedundancySensor to new interface
Resolves  #2833 Have PowerSupplyRedundancy persist across reboots and code updates
