### ISSUE TITLE
OpenBMC GUI: Clicking refresh button resulted in logout 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#2834]
Problem: Refresh button click resulted in logout with following screen. 
Note: logout button was not pressed earlier.

**Comment by sivassrr** [comment]
![refreshlogoutissue2834](https://user-images.githubusercontent.com/19144129/35484821-aff88a7c-047b-11e8-8e8b-e92125d7b98b.jpg)

**Comment by sivassrr** [comment]
Browser used was chrome (Version 64.0.3282.119 (Official Build) (64-bit) ) and with the latest chrome driver
/usr/local/bin/chromedriver -v
ChromeDriver 2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef)

**Comment by rfrandse** [comment]
fixed with 
https://gerrit.openbmc-project.xyz/#/c/8828
