### ISSUE TITLE
Image Signing: Add signature and public key to image

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2837]
As part of the build process, add the public key to the image and the digital signature so that it's part of the final firmware image.
Reference: openbmc/openbmc#2835 and openbmc/openbmc#2836

**Comment by amboar** [comment]
I'm looking at [swupdate](https://github.com/sbabic/swupdate) and its capabilities.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8949> Add image signing framework and open keys
Resolves  #2837 Image Signing: Add signature and public key to image
