### ISSUE TITLE
Image Signing: BMC digital signature check

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2838]
* Calculate the SHA-256 hash over the image files uploaded to the BMC.
* Decrypt the signature contained in the image using an existing public key.
* Compare the decrypted signature with the calculated hash.
* Set activation to failed if signature does not match, create error log

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9093> Enabled Signed image validation in Item Updater
Resolves  #2838 Image Signing: BMC digital signature check
