### ISSUE TITLE
PreTag 0.8 Testing failure for 'Verify system vpd properties'

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#284]
Full Name: 	Tests.Test Inventory.Verify system vpd properties
Start / End / Elapsed: 	20160519 15:20:33.478 / 20160519 15:20:33.493 / 00:00:00.015
Status: 	FAIL (critical)
Message: 	Lengths are different: 20 != 5

**Comment by anoo1** [comment]
@rahulmah what is the test case trying to do?

**Comment by causten** [comment]
the test cases doesn't exist anymore. Hold off on this one

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc-test-automation #21](https://github.com/openbmc/openbmc-test-automation/issues/21) via [**ZenHub**](https://www.zenhub.com/)
