### ISSUE TITLE
Alternate BMC chip thinks it's the primary one

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2840]
When the watchdog is triggered and the Aspeed hardware directs the system to boot from the alternate BMC chip, the alternate BMC is seen as the primary one, meaning the mtd number for the device and setting environment variables don't match.
Need to address this issue to be able to provide alternate boot support.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8794> fix alternate boot after watchdog reset
Resolves  #2840 Alternate BMC chip thinks it's the primary one
