### ISSUE TITLE
OpenBMC GUI - When system state is in Unreachable, there is no option under "Select a power operation"

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2843]
![system state unreachable - select a power operation](https://user-images.githubusercontent.com/29222610/35501047-b2d42296-04fe-11e8-9754-a57679fdf875.png)

**Comment by karlvochatzer** [comment]
Please handle this situation by displaying the following message under the "Select a power operation" section:
“There are no power operations to display while a power operation is in progress. When complete, any new power operations will be displayed here.”

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9174> Sloving When system state is in Unreachable, there is no option under "Select a power operation issue
fixes  #2843 OpenBMC GUI - When system state is in Unreachable, there is no option under "Select a power operation"
