### ISSUE TITLE
Support code-style only validation in CI

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2856]
Currently the openbmc CI process requires the repo under test be automake configured.  Some openbmc repos (like the python based one's) do not have automake but we'd still like to use the new code style validation function within CI.

This issue is to track some tweaks to our CI flow to allow this to happen.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8761> Exit without error in CI if not Automake
Resolves  #2856 Support code-style only validation in CI
