### ISSUE TITLE
security fixes broke web sockets

### ISSUE THREAD

**Issue by mdmillerii** [openbmc/openbmc#2858]
When the security fixes in #2423 added the ciphers keyword to the rest server invocation it removed the kw hash that conditionally enabled web sockets.

https://github.com/openbmc/phosphor-rest-server/commit/91ff11046014765563f4b22fc9eaaf1bebc56497#diff-09e55d75ffd48804bb8382cd4b579a49R74

Noticed when reading the patch.
Considering passing all keyword arguments to the kw variable.

**Comment by anoo1** [comment]
Fixed with https://github.com/openbmc/phosphor-rest-server/commit/5ce760dc9f54f79c79f1c1278f73f7a0db5d0ad0
