### ISSUE TITLE
System has unsupported level of code

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2865]
<cde:info> SW415302 </cde:info>
<breakcde> unintentional bridging.  breaking link to CQ </breakcde>

**Comment by geissonator** [comment]
Summary of issue:  

system shipped that has a unsupported level of code on one side of flash.  Need to ensure both side of BMC flash have supported firmware.

**Comment by rfrandse** [comment]
closing. Maybe reopened once @anoo1 investigates SW415302 CQ
