### ISSUE TITLE
Do real inventory callouts on GPU overtemps and PGOOD faults

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2869]
On witherspoon when I did the power fault analysis code the GPUs weren't in the inventory.  Now that they were added, I should be able to do callouts using the standard method of inventory path associations.  This only applies to the witherspoon system.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8950> Call out GPUs using their inventory path
Resolves  #2869 Do real inventory callouts on GPU overtemps and PGOOD faults
