### ISSUE TITLE
Fault LEDs Remaining on From AC unplugged from PSU Even After Being Resolved by Plugging AC Back into PSU

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2873]
<cde:info> SW413859 </cde:info>

**Comment by spinler** [comment]
On Witherspoon, every now and then pulling AC on a power supply would cause a PGOOD error log instead of an InputFault error log.   When that happens, plugging back in the AC won't turn off the fault LEDs like it should.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8991> Skip other fault checks if inputFault count bump
Resolves:  #2873 Fault LEDs Remaining on From AC unplugged from PSU Even After Being Resolved by Plugging AC Back into PSU
