### ISSUE TITLE
The High Warning and High Critical values are not correct on the GUI.

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2874]
The `High Warning` and `High Critical` values are not correct on the GUI. They are displayed as 1000 times their value. I assume the problem is they aren't being multiplied by the scaling value. 
![gui_bug](https://user-images.githubusercontent.com/5455127/35826646-f311d404-0a7e-11e8-9f5b-539233f836ae.PNG)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8900> Scale critical and warning values
Resolves  #2874 The High Warning and High Critical values are not correct on the GUI.
