### ISSUE TITLE
Mirror u-boot to alt BMC chip

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2876]
If a system has an alternate BMC chip, mirror the u-boot image to it upon boot, so that the system recovers from a corrupted u-boot that triggered the aspeed chip to switch BMCs.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9307> Add mirror u-boot option to obmc-flash-bmc
Resolves  #2876 Mirror u-boot to alt BMC chip
