### ISSUE TITLE
expand(1) is not available in the rootfs

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#2879]
`expand` is a tool provided by `coreutils` that converts tabs to spaces. Some tools, such as `perf`, assume `expand` is available. Update the busybox configuration to enable `CONFIG_EXPAND`.

**Comment by amboar** [comment]
Pushed a patch to enable expand: https://gerrit.openbmc-project.xyz/#/c/8852/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8852> busybox: Enable expand(1) utility
Resolves:  #2879 expand(1) is not available in the rootfs
