### ISSUE TITLE
PreTag 0.8 Testing failure for 'Get OCC Status'

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#288]
Get OCC status
Full Name: 	Tests.Test Occ Powercap.Get OCC status
Documentation: 	

This testcase is to test the OCCstatus for the system is Enabled or not
Start / End / Elapsed: 	20160519 15:24:54.197 / 20160519 15:24:57.960 / 00:00:03.763
Status: 	FAIL (critical)
Message: 	 != Enabled

**Comment by anoo1** [comment]
The powercap should be available and working through the sensors. Perhaps the test case is looking at the settings file. @rahulmah could you take a look?

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc-test-automation #15](https://github.com/openbmc/openbmc-test-automation/issues/15) via [**ZenHub**](https://www.zenhub.com/)
