### ISSUE TITLE
Image Signing: PNOR signed image and verification

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2886]
Explore adding a mechanism (like env variables) to specify a private key that would sign the PNOR image as part of the squashfs script https://github.com/openbmc/openpower-pnor-code-mgmt/blob/master/generate-squashfs .

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9221> Add PNOR image signing during squashfs generation
Resolves  #2886 Image Signing: PNOR signed image and verification
