### ISSUE TITLE
Remove org.openbmc.managers.System

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2889]
The only remaining function in here is the gpio init routines.  It loads in system.py config object and uses that to do some manipulation of the GPIO's.  This story would involve moving the required data from the system.py into a MRW generated (or at least intermediate yaml file) and consuming that in a new c++ application (or moving to an existing application if it fits).

**Comment by gtmills** [comment]
@geissonator Is this done or still an issue?

**Comment by geissonator** [comment]
I think we're good here @anoo1 with https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-intel/+/13723/ ?

**Comment by anoo1** [comment]
There were a couple more layers left, finally removed everything with https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/18659/ .
