### ISSUE TITLE
GUI Immediate Shutdown should call the chassis object

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2890]
"Immediate Shutdown" on the GUI calls the host shutdown, this is the same as "Orderly shutdown".  
"Immediate Shutdown" should be a hard power off and differ from the "Orderly shutdown". 

After pressing "Immediate Shutdown"..

Feb 06 21:37:49 witherspoon phosphor-gevent[2326]: ::3a:b976:8e91:f402%1268294196 - - [2018-02-06 21:37:49] "PUT /xyz/openbmc_project/state/host0/attr/RequestedHostTransition HTTP/1.1" 200 258 2.551181

From https://github.com/openbmc/docs/blob/master/host-management.md:

To issue a hard power off (accomplished by powering off the chassis):
```
curl -c cjar -b cjar -k -H "Content-Type: application/json" -X PUT \
  -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}' \
  https://${bmc}/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition
```

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8875> Have Immediate Shutdown call the chassis object
Resolves  #2890 GUI Immediate Shutdown should call the chassis object
