### ISSUE TITLE
GUI: BMC IP should be BMC Host /IP in GUI header / server overview page

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#2894]
Currently in GUI header, It marked as BMC IP. 

- [ ] It should be BMC Host / IP in gui header / server overview main page

![image](https://user-images.githubusercontent.com/19144129/36012886-33930a38-0d87-11e8-8442-235446e9d4f3.png)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9024> BMC IP changed to BMC host/IP in webui header/server overview page
Resolves  #2894 GUI: BMC IP should be BMC Host /IP in GUI header / server overview page

**Comment by gtmills** [comment]
It also cuts off the .com 
![image](https://user-images.githubusercontent.com/5455127/36503770-d74eff66-1713-11e8-8d97-8ed5db14ca1a.png)

**Comment by jaypadath** [comment]
Hi Gunnar/Sivas, I don't the see the issue happening in recent witherspoon systems which I checked.
In place of IP address, only the IP address is seen.
Does it got fixed with some other change ?

**Comment by jaypadath** [comment]
With further investigation it is observed that BMC host/IP address value
is shown depending on the user input. So kept this same design and made below
changes.

BMC IP changed to BMC host/IP in webui header/server overview page.
Also corrected the value truncation.
Attaching the fixed screen shot.
![after_change](https://user-images.githubusercontent.com/35572112/36915064-583e3d04-1e75-11e8-8934-e69322eb1fc6.png)
