### ISSUE TITLE
[System] : IPMI : DCMI power reading command not working

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2906]
<cde:info> SW416470 </cde:info>

**Comment by rfrandse** [comment]
For the command to work we need to have OccActive 1 and also we should have a total_power dbus object

curl -c cjar -b cjar -k -H "Content-Type: application/json" https://$BMC_IP/org/open_power/enumerate

    "/org/open_power/control": {},
    "/org/open_power/control/gard": {},
    "/org/open_power/control/host0": {},
    "/org/open_power/control/occ0": {
      "OccActive": 0,
      "ThrottleMemTemp": 0,
      "ThrottleProcPower": 0,
      "ThrottleProcTemp": 0
    },
    "/org/open_power/control/occ1": {
      "OccActive": 0,
      "ThrottleMemTemp": 0,
      "ThrottleProcPower": 0,
      "ThrottleProcTemp": 0
    },
