### ISSUE TITLE
Mirror rwfs to alt BMC chip

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2918]
If the watchdog triggers the aspeed hw to boot from the alternate BMC chip due to a boot failure, the read-write data that was stored on the primary chip would not be available. This includes network configuration, so that BMC may not be reachable anymore, which defeats the purpose of switching chips to 'recover' from a failure.

Need to explore mirroring the read-write data stored in the rwfs volume to the alt chip, and also the time intervals at which this should be done.

**Comment by anoo1** [comment]
Per Brad, look into a filesystem option/type that would allow mirroring, so when writing to one filesystem then kernel would write to a second one as well.

**Comment by amboar** [comment]
It sounds like you want RAID 1, but do you *really* want RAID 1? RAID management of flash on a BMC seems like overkill.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10295> sync_manager: Add callback to do rsync
Closes  #2918 Mirror rwfs to alt BMC chip
