### ISSUE TITLE
Fan Control fails to set Fan speed to safe setting during Reboot / Firmware Update

### ISSUE THREAD

**Issue by agangidi53** [openbmc/openbmc#292]
**Current**: Fan Control fails to set Fan speed to safe setting before going into a Reboot / Firmware Update.  This is important because we leave the system at risk if the Host load ramps up while BMC is rebooting (~2 minutes) or during a firmware update via /run/initramfs/image-*****\*  (~14 minutes).

**Expectation**: Fan control sets the Fans to max speed before going down and takes back the control after rebooting and ramps it down to appropriate speeds.

**Comment by anoo1** [comment]
hi @Kenthliu , is this something your team can help with?

**Comment by johnhcwang** [comment]
Is it possible that we can call fan_control.py to set full speed in systemd-reboot.service?

**Comment by Kenthliu** [comment]
Hi @anoo1, Ok we will handle this feature.
Hi @agangidi53 , the timing of fan speed you concern is during bmc reboot, right? Now we are investigating how to make fan full speed after reboot. All the update methods need to reboot BMC finally. Reboot BMC can use ipmi command in host or RestAPI, those will call warmreset dbus method. We propose to make fan full speed after warmreset was called. So the correct update procedure will be reboot BMC through ipmi command or RestAPI in the final step. Reboot directly under BMC debug console will not work. Is this OK with you? Thanks.

**Comment by agangidi53** [comment]
I am sorry for delayed reply. I was out of office for sometime and only checked this now. 
I don't understand setting fan speed to max shouldn't work via reboot via console. 
What is the difference between rebooting via RestAPI and rebooting via the console that makes fan speeds to be set to max easier than the other  ?
What is needed for you to get this to work on both ways ?

**Comment by williamspatrick** [comment]
Is this fixed in the Foxconn tree?

**Comment by Kenthliu** [comment]
Yes

**Comment by msbarth** [comment]
With the ability to configure a watchdog and/or set speed events within a yaml file for fan control, the conditions noted here can be resolved to set fan speed to a given target under these conditions. i.e.) For the witherspoon system, a watchdog is triggered when the BMC is rebooted which drives fans to 100%PWM until the fan control application returns to active state.
In another case, a property can be configured in the fan control yaml to trigger setting the fans to a specific speed, for example..in prep of a code update to occur.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8626> Support properties of type string
Resolves  #292 Fan Control fails to set Fan speed to safe setting during Reboot / Firmware Update

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9650> Changing the text Quiesced to Error
Fixes  #292 Fan Control fails to set Fan speed to safe setting during Reboot / Firmware Update
