### ISSUE TITLE
Remove netman.py from phosphor layer

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2921]
netman.py has been deprecated by new phosphor-networkd functionality.  This issue is to remove netman.py from the phosphor layer (and maybe all together?).  Need to check with OpenBMC community on current usage.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9055> Remove netman.py from the image
Resolves  #2921 Remove netman.py from phosphor layer

**Comment by sivassrr** [comment]
Based on today's morning squad discussion, Assigning it to @geissonator
