### ISSUE TITLE
Update power supply inventory paths

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2924]
On Witherspoon, the inventory paths of the power supplies don't quite match the paths as they're defined in the machine readable workbook XML.  This causes callouts that are based on errors with the CALLOUT_INVENTORY_PATH metadata to not work.

The BMC code has '/system/chassis/powersupply', and the MRW has '/system/chassis/motherboard/powersupply'.  The MRW does not allow anything but a motherboard to hang off the chassis, so the BMC is the area that will have to change, to add in the motherboard.  This will also match what the fans look like.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8936> Update power supply inventory path to match MRW
Resolves  #2924 Update power supply inventory paths
