### ISSUE TITLE
GUI does not handle "Quiesced" state correctly. 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2925]
The GUI displays the "Quiesced" state as "booting".

https://github.com/openbmc/phosphor-webui/blob/master/app/common/services/constants.js#L39

 
From https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/README.md 
"Quiesced means the host OS is in a quiesce state and the system should be checked for errors. "

The GUI should display that the host is "Quiesced"

**Comment by iftekharuli** [comment]
After talking to our sponsor users and 4 different interviews with IBMers- we decided to change the text to "Standby"

**Comment by gtmills** [comment]
I think of the "quiesced" state as an error state.. @geissonator care to comment here.

**Comment by geissonator** [comment]
Yes, quiesced implied your host is in an error state.  The normal cause is a fail to boot the host for a variety of different reasons. An error event should be present indicating the reason.

**Comment by gtmills** [comment]
I think "Failed", "Error", or "Quiesced" would be better.

**Comment by iftekharuli** [comment]
I will ask the researchers in design team who worked with sponsor users and let you know.

**Comment by zombiGoats** [comment]
The quiesced state should mean the system has just been paused/halted for some reason (that's what the term means), and the system **should** be checked for errors. This doesn’t definitively mean an error occurred. 

None of our tested users knew of the term or used the term quiesced. The term “stand by” was understood by users and they acknowledged if the system was in a stand by state for unknown reasons, they would look into potential issues.

**Comment by gtmills** [comment]
It may not have been the best choice of wording on our part then. A "quiesced" state for us means the host is in an error state. IMO, "standby" is not a strong enough word for this error state.

**Comment by iftekharuli** [comment]
After the discussion with design team, we decided to go with the word "Error" I will update the code

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9650> Changing the text Quiesced to Error
Fixes  #2925 GUI does not handle "Quiesced" state correctly.
