### ISSUE TITLE
Stop ethernet port fail over on System

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2931]
The witherspoon system owner has requested a mechanism to prevent the BMC from failing over to the other ethernet port if it detects a network drop on the one it's using.

@sammj has a patch on the mailing list via http://patchwork.ozlabs.org/patch/873610/ for the kernel support.  He also has a user space application that can be run to configure this using his new driver in https://github.com/sammj/ncsi-netlink

This story is to integrate this all into the witherspoon layer and set the NCSI to not do fail overs to the other port.

**Comment by sammj** [comment]
Proper V1 now sent to netdev: http://patchwork.ozlabs.org/patch/876963/

**Comment by sammj** [comment]
V2 applied to net-next: http://patchwork.ozlabs.org/patch/881249/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9620> Network: Bring libnl into the openbmc image
Partilally Resolves  #2931 Stop ethernet port fail over on System

**Comment by sammj** [comment]
FWIW https://github.com/openbmc/openbmc/commit/7a5340bd5014a9af06b2de9443479100acd02eaa only introduces the libnl-genl dependency, the actual failover setting is controlled in https://gerrit.openbmc-project.xyz/#/c/9670/ etc

**Comment by dkodihal** [comment]
https://gerrit.openbmc-project.xyz/#/c/9670/ only partially resolved this.

**Comment by ratagupt** [comment]
This issue is addressing to not allow the failover,There was not a requirement to make it configurable.
However we will make it configurable as a follow on feature if someone requests it.
