### ISSUE TITLE
Why some variables in bitbake.conf are "export" ?

### ISSUE THREAD

**Issue by zhiyuK** [openbmc/openbmc#2933]
When I check the content of bitbake.conf, I found some variables are exported, like as follow:
**# Path prefixes
export base_prefix = ""
export prefix = "/usr"**

But I try to remove "export", like as follow, I found the image still can be built successfully.
**# Path prefixes
 base_prefix = ""
export prefix = "/usr"**

My procedure of building image is as follow, and the built image is for QEMU :
 **. openbmc-env
 bitbake obmc-phosphor-image**

It seems to be unnecessary to add "export". 
What is the use of "export" in bitbake.conf ?

Thanks for your teaching!

**Comment by amboar** [comment]
@zhiyuK This isn't really a bug or a feature (at least, yet), and so doesn't really have a place in the issue tracker. As such I'm closing the issue. The mailing list is a much better place to ask these kind of questions, please sign yourself up and send the question there:

https://lists.ozlabs.org/listinfo/openbmc

Cheers,

Andrew
