### ISSUE TITLE
VGA: SoC kernel driver for SCU registers

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2935]
For whatever is needed for the VGA support:

- Read-only access to VGA scratch registers (SCU50-SCU6C),
       including the VGA scratch register change interrupt (via
       SCU18[17]) to allow poll().

- Read-write access to SCU2C to control BMC vs. host output

**Comment by shenki** [comment]
@amboar has merged this into our kernel and it is in openbmc as of 37911c44caef94a8d6c0a908fca9c5a7fe806ddb.

We will track the mainlining of the kernel code separately.
