### ISSUE TITLE
SDR mapping sensors to dbus objects - hwmon sensors

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2942]
Some of the sensor info that was hand-coded via #2613, can be retrieved from the MRW, by updating relevant MRW YAML config files. In addition, there could be MRW parser changes required.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9514> Modify ipmi sensor config yaml to include analog sensors
Resolves  #2942 SDR mapping sensors to dbus objects - hwmon sensors
