### ISSUE TITLE
Power cap setting validator is incorrect

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2944]
For witherspoon, the power cap setting validator is incorrect. Please see #2899 for details. The validation range in the settings should be *before* derating is applied. FYI @mine260309 and @spinler.

**Comment by spinler** [comment]
We currently yank the range from the workbook XML generically, so we'll need to figure out a way to also grab the derating factor and apply appropriately.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9485> Factor PS derating into power cap limit validation
Resolves  #2944 Power cap setting validator is incorrect
