### ISSUE TITLE
phosphor-hwmon support for the OCCs with the 4.13 kernel

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2953]
In 4.13, the OCCs were removed from the device tree.  Unfortunately the udev rule that starts phosphor-hwmon passes it the OF_FULLNAME env var, which then doesn't exist so phosphor-hwmon never starts.

**Comment by amboar** [comment]
It isn't clear what you're talking about here, though as a guess it's regarding the occ-hwmon nodes? If so, then yes, you'll need a different approach, they won't be coming back. The OCC hardware should definitely be described in the devicetree.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9420> Change phosphor-hwmon startup mechanism
Resolves  #2953 phosphor-hwmon support for the OCCs with the 4.13 kernel
