### ISSUE TITLE
Led Inventory Path Error on Systems with ESEL that can't be decoded

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2955]
<cde:info> SW418754 </cde:info>

**Comment by spinler** [comment]
The openbmc code is missing the mapping to convert the GPU Functional sensors into inventory callouts on Witherspoon.  This happens when a hostboot eSEL tries to call out a GPU that way.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9451> Add entry for gpu_func sensor in MRW config YAML
Resolves  #2955 Led Inventory Path Error on Systems with ESEL that can't be decoded
