### ISSUE TITLE
GUI: BMC last reboot time is incorrect

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2956]
![last_reboot](https://user-images.githubusercontent.com/5455127/36861504-aa0f3f34-1d49-11e8-95b5-fdc74b4895c3.PNG)

The "BMC last reboot" time is incorrect. The time shown is the last refresh time instead of the last BMC reboot. 
https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/controllers/bmc-reboot-controller.html#L10

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11628> Add LastRebootTime to BMC gui
Resolves  #2956 GUI: BMC last reboot time is incorrect
