### ISSUE TITLE
GUI: "Last power operation" time is incorrect

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2957]
![last_power_operation](https://user-images.githubusercontent.com/5455127/36861816-a1ba2b90-1d4a-11e8-8ca6-ab24676bff17.PNG)

The "Last power operation" time is incorrect. The time shown is the last refresh time instead of the last time a power operation was performed.

https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/controllers/power-operations-controller.html#L8

**Comment by iftekharuli** [comment]
Is there a rest call we can make to get the time for the last power operations?

**Comment by gtmills** [comment]
Code is here for the last power operation: https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-state-manager/+/11475/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11762> Last power operation
Resolves  #2957 GUI: "Last power operation" time is incorrect
