### ISSUE TITLE
GUI: After uploading the firmware page should display the new uploaded image

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2960]
When uploading an image the firmware page does not refresh and show the new image.
To get the new image to show, a user must refresh the page.
The upload image code needs to wait until the image is uploaded, untarred, and a new software D-Bus object is created and then refresh the page. Currently, it just waits until a good response code is returned then refreshes. This is too soon since the new object has not been created yet.  

https://github.com/openbmc/phosphor-webui/blob/master/app/configuration/controllers/firmware-controller.js#L89

**Comment by gtmills** [comment]
https://github.com/openbmc/openbmc/issues/2939 is the story to return the id of the new D-Bus software object. The REST upload should return the id after untarring and creating the image.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10128> Display error if error on upload
Resolves  #2960 GUI: After uploading the firmware page should display the new uploaded image
