### ISSUE TITLE
Barreleye attempting to uninstall a packagegroup feature - unexpected behavior 

### ISSUE THREAD

**Issue by dcobbley** [openbmc/openbmc#2963]
I noticed the barreleye configuration file is (as far as I can tell) is attempting to remove the "packagegroup-obmc-apps-extrasdev"

meta-openbmc-machines/meta-openpower/meta-rackspace/meta-barreleye/conf/machine/barreleye.conf
IMAGE_INSTALL_remove = "packagegroup-obmc-apps-extrasdev"

After running $ bitbake -g obmc-phosphor-image with the barreleye configuration, I still see:
"packagegroup-obmc-apps-extrasdev" [label="packagegroup-obmc-apps-extrasdev(packagegroup-obmc-apps) inside of package-depends.dot.

I just wanted to note this in-case the intention was to truly remove this feature from the package-group.

**Comment by gtmills** [comment]
Barreleye was removed. Closing.
