### ISSUE TITLE
The "Boot priority" down arrow should be grayed even when there is a "Ready" image. 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2965]
Before uploading an image:
![boot_priority_down_before](https://user-images.githubusercontent.com/5455127/36916580-e8f5e2d6-1e19-11e8-973b-15e7cbee87e9.PNG)
After uploading an image: 
![boot_priority_down](https://user-images.githubusercontent.com/5455127/36916587-f24b7918-1e19-11e8-94b1-c89d1564571e.PNG)

"$last" needs to be updated to not count the "Ready" images, it should only count the "functional" or "Ready" images. 
https://github.com/openbmc/phosphor-webui/blob/master/app/common/directives/firmware-list.html#L32

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10331> Gray out the 'Boot priority' down arrow key
Resolves  #2965 The "Boot priority" down arrow should be grayed even when there is a "Ready" image.
