### ISSUE TITLE
GUI: After activating an image the firmware page should display the image as activated

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2966]
When activating an image the firmware page does not refresh after the image is activated and show the image as "Active".
To get the image to show as "Active", a user must refresh the page.
The activating image code should wait until the image is activated and the D-Bus object says "Active" (or "Failed" if the image fails to activate) and then refresh the page.
Currently, it just waits until a good response code is returned then refreshes. This is too soon and the image shows "Activating".

After activating an image and until the user refreshes:
![active](https://user-images.githubusercontent.com/5455127/36917309-14afb198-1e1c-11e8-86d0-6441bf09b143.PNG)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9422> Update the GUI after an image activated
Resolves  #2966 GUI: After activating an image the firmware page should display the image as activated
