### ISSUE TITLE
GUI: Update confirm activation window to be useful

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#2967]
The current "Preserve settings" window that shows when a user activates an image is not useful.
The "Preserve settings" window does not do anything and saving network settings prior to activation is not needed.
The window could say something like "Active firmware v2.1-186-g4c78e42?" with "Continue" and "Cancel" buttons similar to the window that shows on Deleting an image. 
It could also how an option for "activate and reboot" if we want to support that for BMC images? 

![preserve_settings](https://user-images.githubusercontent.com/5455127/36919212-2b41323c-1e22-11e8-8d58-81a1fa9a132f.PNG)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9654> Add server confirm activation modal
Resolves  #2967 GUI: Update confirm activation window to be useful
