### ISSUE TITLE
OpenBMC simulation

### ISSUE THREAD

**Issue by nagvad** [openbmc/openbmc#2970]
Hello,

I am new to BMC world, need help in generating and flashing image. 

I have server with AST 2500 BMC chip which has AMI software on it, want to flash openBMC image and check it out. How to generate image for AST2500 and flash.

In below presentation, OpenBMC simulation environment mentioned in page 12. I haven't found any details on setting up simulation environment, can anyone point me steps to do it.

https://openpowerfoundation.org/wp-content/uploads/2016/11/CAusten-OpenBMC.pdf

Thanks.

**Comment by mine260309** [comment]
You can refer to https://github.com/openbmc/docs/blob/master/cheatsheet.md#using-qemu
Btw, it's better to ask such questions by sending emails to [OpenBMC mailing-list](https://lists.ozlabs.org/listinfo/openbmc) or in the IRC channel.

**Comment by nagvad** [comment]
Thank you.
