### ISSUE TITLE
Fan Monitor: Add yaml config support for zones and zone conditions

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#2976]
<cde:info> SW426724 </cde:info>
The fan monitor application should also define fans within zones and zone conditions, similarly to fan control, where each zone would contain the attributes to apply to all fans including which fans should be created in inventory based on the zone conditions. This is an enhancement to the layout of the yaml configuration to reduce redundant attribute definitions and add the zone condition generation.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10446> Add generation of propertiesMatch condition
Resolves:  #2976 Fan Monitor: Add yaml config support for zones and zone conditions
