### ISSUE TITLE
IPMI: Implement sensor mutability for inband set sensor

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#2980]
The infrastructure is mostly there - the work involved is adding a check on the mutability in the set sensor code, and populating the right mutability value in the sensor yamls.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9884> sensorhandler: Enable mutability based set function
Resolves  #2980 IPMI: Implement sensor mutability for inband set sensor
