### ISSUE TITLE
Witherspoon : IPMI : Power supply and GPU fru info not available in IPMI fru print

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2984]
<cde:info> SW418856 </cde:info>

**Comment by rfrandse** [comment]
Power supply and GPU's info not available in IPMI fru print. Cross checked and found that these are available via REST for the same system.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9639> Add power supply to BMC accessible FRUs to generate FRU map
Partially Resolves  #2984 Witherspoon : IPMI : Power supply and GPU fru info not available in IPMI fru print
