### ISSUE TITLE
phosphor-mboxd tests fail due to broken libstdc++ in CI Docker image

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#2986]
I've got a series that partly addresses issue #2524 in Gerrit:

https://gerrit.openbmc-project.xyz/#/q/project:openbmc/phosphor-mboxd+status:open

Part-way through the series Jenkins starts failing the patches. This happens at precisely the point where we introduce a nested temporary directory structure which we then try to remove with `std::experimental::filesystem::remove_all()`. Suspiciously there's [a libstdc++ bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71313) that smells like the cause of what's going wrong, and every patch in the series passes the test suite on my laptop running Ubuntu Artful.

The CI system uses the `ubuntu:latest`. As it turns out, `ubuntu:latest` [points to Ubuntu 16.04](https://hub.docker.com/_/ubuntu/). This is pretty misleading.

To keep up appearances and resolve the phosphor-mboxd test failures, lets use a more modern Ubuntu image. To that end I've got some patches that help move us to running repository CI on the Artful Docker image:

* phosphor-networkd: https://gerrit.openbmc-project.xyz/#/q/status:open+project:openbmc/phosphor-networkd+branch:master+topic:artful-ci
* phosphor-logging: https://gerrit.openbmc-project.xyz/#/q/status:open+project:openbmc/phosphor-logging+branch:master+topic:artful-ci
* openbmc-build-scripts: https://gerrit.openbmc-project.xyz/#/q/status:open+project:openbmc/openbmc-build-scripts+branch:master+topic:artful-ci

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9467> run-unit-test-docker.sh: Update to ubuntu:artful
Closes  #2986 phosphor-mboxd tests fail due to broken libstdc++ in CI Docker image
