### ISSUE TITLE
Witherspoon : Event notification is not working

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2988]
<cde:info> SW420285 </cde:info>

**Comment by rfrandse** [comment]
Event notification is not working. No event notifications are coming.
Steps to reproduce:
1. Start event notification for interface and path like below. And reload the page. Full script is attached to this issue.

"paths": ["/xyz/openbmc_project/sensors/temperature/ambient", "/xyz/openbmc_project/logging"],
"interfaces": ["xyz.openbmc_project.Sensor.Value", "xyz.openbmc_project.Logging.Entry"]

**Comment by dkodihal** [comment]
Fixed with https://gerrit.openbmc-project.xyz/#/c/9516/.
