### ISSUE TITLE
GUI: Warning icons displayed in cores of CPU that are present and functional 

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2989]
<cde:info> SW420242 </cde:info>

**Comment by gtmills** [comment]
The warning icon is displayed when a core is present and not when it is not present. This seems backwards. 

https://github.com/openbmc/phosphor-webui/blob/master/app/server-health/controllers/inventory-overview-controller.html#L50

![warning_icon](https://user-images.githubusercontent.com/5455127/37169642-1234c3a2-22ce-11e8-8d1b-5c2ca988e0f7.PNG)

bash-4.1$ curl -b cjar -k https://$BMC_IP/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/enumerate
{
  "data": {
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core0": {
      "Functional": 1, 
      "Present": 1, 
      "PrettyName": ""
    }, 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core1": {
      "Functional": 1, 
      "Present": 1, 
      "PrettyName": ""
    }, 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core10": {
      "Functional": 1, 
      "Present": 1, 
      "PrettyName": ""
    }, 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core11": {
      "Functional": 1, 
      "Present": 1, 
      "PrettyName": ""
    }, 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core12": {
      "Functional": 0, 
      "Present": 0, 
      "PrettyName": ""
    }, 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core13": {
      "Functional": 0, 
      "Present": 0, 
      "PrettyName": ""
    },

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9473> Display warning icons on non-functional subcomponents
Resolves  #2989 GUI: Warning icons displayed in cores of CPU that are present and functional
