### ISSUE TITLE
MBE error events DIMM number is wrong

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/openbmc#299]
Run test OpenPOWER RAS Verification Guide Version 1.0 -- section 3.4 Trial 4: Memory DIMM UE Checkstop Error.
Use "putscom -c 0x80000001 0201145E 0x0840000000000000" to trigger MBE. on memory buff ID 80000001.
RestApi will record two MBE error events on the same DIMM. There are no DIMM 1,4,5 events.
And check the RestApi DIMM iverntory information. DIMM 0,1,4,5 has fault present.
Blow in openbmc event
![dimm1](https://cloud.githubusercontent.com/assets/15260220/15496947/ae23f3c0-21ca-11e6-81e3-32df8c398117.jpg)
![dimm2](https://cloud.githubusercontent.com/assets/15260220/15496981/dcd87358-21ca-11e6-830e-420177719dcb.jpg)
![dimm3](https://cloud.githubusercontent.com/assets/15260220/15496986/e2b85b94-21ca-11e6-9482-bccf955560c7.jpg)

**Comment by causten** [comment]
send me the logs, I'll figure it out
How are you injecting the errors?

**Comment by Kenthliu** [comment]
Please reference section 3.4 Trial 4 in below file.
[RASverif_22January2016_pub.pdf](https://github.com/openbmc/openbmc/files/280815/RASverif_22January2016_pub.pdf)

**Comment by causten** [comment]
Ken can you add the log to box for me to view?
 
 
Chris AustenPOWER Systems Enablement Manager(512) 286-5184 (T/L: 363-5184)
 
 
----- Original message -----From: KenLiu <notifications@github.com>To: openbmc/openbmc <openbmc@noreply.github.com>Cc: Chris Austen/Austin/IBM@IBMUS, Comment <comment@noreply.github.com>Subject: Re: [openbmc/openbmc] MBE error events DIMM number is wrong (#299)Date: Tue, May 24, 2016 8:17 PM 
Please reference section 3.4 Trial 4 in below file.RASverif_22January2016_pub.pdf

**Comment by Kenthliu** [comment]
Yes @causten Here you are. event data with journctl log.

[dimm.txt](https://github.com/openbmc/openbmc/files/280962/dimm.txt)
![dimmerror](https://cloud.githubusercontent.com/assets/15260220/15527662/dcced3bc-226e-11e6-919c-38b513febe2b.jpg)

**Comment by causten** [comment]
I have had some long discussions with the hostboot team about this issue.  https://github.com/open-power/hostboot

I key off of the data they send me.  The big event log that has all the debug data useful to the hardware engineers to debug.  The eSEL which is sent to me does not contain multiple FRU callouts.  There is no plan to do it either.  

Unfortunately this means it is 'working as designed'

**Comment by Kenthliu** [comment]
It sounds like a limitation. Did you open a issue on https://github.com/open-power/hostboot? Can you please provide more detail information about why no other DIMM# log? Then we can close this issue.

**Comment by anoo1** [comment]
Opened hostboot issue: https://github.com/open-power/hostboot/issues/60

**Comment by Kenthliu** [comment]
Thanks for the explain.
Also record Patirck's response here.

A memory UE is expected to not be isolated to a single DIMM, so there is always multiple callouts. If I remember right, Hostboot does two things when there is an error with a guard event. 

Send down a SEL/eSEL. 
Assert fault sensors for the associated FRUs.
Since a SEL is associated with a sensor, in effect, the SEL also points to a FRU. What Chris was observing is only one FRU from the SEL path but all the FRUs from the fault sensor path. Since we treat sensors as "inventory" and SELS as "error events", which are handled by two different pieces of code, and the fault sensor doesn't actually have any correlation back to the SEL anyhow, the BMC is unable to show an association between the SEL and all the callout-FRUs; we only get the one for the SEL. 
This information is contained deep in the eSEL, which the BMC is not presently able to parse and would require a bunch of HUID->FRU-ID mapping on BMC side anyhow. As best as we can tell there is no way to get this information in a pure IPMI sense.
