### ISSUE TITLE
Remove support for python 2 from all OpenBMC runtime python scripts

### ISSUE THREAD

**Issue by camvanng** [openbmc/openbmc#2994]
This issue tracks removing support for python 2 from python applications that are actually used on the systems once we have updated to yocto 2.4.  See #2910 and #2920.

Grep for  "TODO: openbmc/openbmc#<this issue number> remove python 2 support" to find code that needs to be removed or changed.

We also need to change "#!/usr/bin/env python" to "#!/usr/bin/env python3".

**Comment by gtmills** [comment]
We moved to yocto 2.4, so should do this.
