### ISSUE TITLE
GUI: HOST/IP address with : at the end

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2995]
<cde:info> SW418651 </cde:info>

**Comment by gtmills** [comment]
![ipwithcolon](https://user-images.githubusercontent.com/5455127/37365954-03f98af4-26cd-11e8-9a21-2c345e34a4cb.jpg)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9534> Only add ":" when a port is given
Resolves  #2995 GUI: HOST/IP address with : at the end
