### ISSUE TITLE
Enhanced IBM error logs

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#2998]
IBM systems have some additional requirements for things to show in the error logs.  To start with, this is an event ID that can be mapped to the online system documentation, and an error message that is different than the one in the dbus-interface documentation.

This will be done with another application that will host the new interface with the same object paths as the existing logs.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9792> Install the Witherspoon error policy table
Resolves  #2998 Enhanced IBM error logs
