### ISSUE TITLE
Digital Signatures: Bring ssl error handling to consensus

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#2999]
See comments: https://gerrit.openbmc-project.xyz/#/c/9092/11..23/image_verify.cpp

Bring above comments to the community for agreement on best route and make changes if needed.

**Comment by ratagupt** [comment]
I can understand that SSL returns two type of error code..but we are not taking action differently..

in one case we are returning false and in other case we throw exception..and then it will be caught in caller context which doesn't do anything and returns false..
