### ISSUE TITLE
How to change kernel configuration

### ISSUE THREAD

**Issue by hsuedw** [openbmc/openbmc#3001]
I am trying to use configuration fragment to build **drivers/hwmon/i5k_amb.c** to linux kernel.

```
$ cat temp_sensor.cfg
CONFIG_SENSORS_I5K_AMB=y
CONFIG_SENSORS_I5500=y

$ cat linux-obmc_%.bbappend
FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
SRC_URI_append = " file://device-tree.patch"
SRC_URI_append = " file://temp_sensor.cfg"

```
However, after the code is built, CONFIG_SENSORS_I5K_AMB and CONFIG_SENSORS_I5500 are not included in .config. 

Does anyone know how to change kernel configuration in openbmc??

BRs,
Edward

**Comment by LindarLiu0724** [comment]
Below line works in my side:
SRC_URI += "file://xxx.cfg"

**Comment by hsuedw** [comment]
Hi LindarLiu0724:

Thanks for your reply. 
I have tried and didn't work. 
I think I am going to have a clean code and try again.

**Comment by hsuedw** [comment]
After having a clean code, I can build the driver successfully.

**Comment by hsuedw** [comment]
After having a clean code, I can build the driver successfully.
