### ISSUE TITLE
SNMP : Design API to provide snmp manager information to the BMC

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#3004]
In the least, the BMC would need to know the manager's IP. There could be multiple managers as well.

There are two possibilities :

- A REST API
- Run an snmp agent/other app on the BMC which can respond to an SNMP specific command from the manager to retrieve manager information.

This story does not cover the API implementation.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10234> Create Network.Client interface
Resolves  #3004 SNMP : Design API to provide snmp manager information to the BMC
