### ISSUE TITLE
GUI: Hardware status "Filter" not working as expected - Search for "CPU 0"  but CPU 1 also listed

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3006]
<cde:info> SW420999 </cde:info>

**Comment by gtmills** [comment]
![sw420999](https://user-images.githubusercontent.com/5455127/37474925-80003260-283f-11e8-82cc-f721b8f33136.jpg)

**Comment by gtmills** [comment]
Go to "Server health" -> "Hardware status" then enter "CPU 0" in the search field.
