### ISSUE TITLE
SDR elist command is not showing GPU presence data correctly

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3008]
<cde:info> SW420838 </cde:info>

**Comment by spinler** [comment]
The GPUs on the witherspoon don't show as much details as they could in some ipmitool commands, like sdr list:
```
gv100card0       | C5h | ok  | 216.1 | 0 unspecified
```
Other fields look like:
```
dimm15           | C4h | ok  | 32.8 | Presence Detected
```

The IPMI reading type and sensor type need fixing, if not also the entity ID.
