### ISSUE TITLE
[OPAL] ipmid[1252]: Failed to get /system/chassis/motherboard/cpu0/core0 busname: (null)

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3011]
<cde:info> SW419195 </cde:info>

**Comment by amboar** [comment]
Please provide a description of how to reproduce and what versions are affected.

**Comment by devenrao** [comment]
Refer to defect SW419195

**Comment by mdmillerii** [comment]
@devenrao This is supposed to be a public issue tracker.  The defect database you refer to is not.  Please summarize here.

**Comment by devenrao** [comment]
Install a P9 Open Power Hardware with the latest OP910.20 Firmware images.
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v2.0"
VERSION_ID="ibm-v2.0-0-r35-0-g7c7c1af"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v2.0"
BUILD_ID="ibm-v2.0-0-r35"
```
Seeing the following messages in the Open BMC journalctl logs.
```
root@witherspoon:~# journalctl | tail -100
Feb 08 09:12:05 witherspoon ipmid[1252]: Failed to get /system/chassis/motherboard/cpu1/core12 busname: (null)
Feb 08 09:12:05 witherspoon ipmid[1252]: Failed to find Sensor 0x80
Feb 08 09:12:05 witherspoon ipmid[1252]: Failed to get /system/chassis/motherboard/cpu1/core13 busname: (null)
Feb 08 09:12:05 witherspoon ipmid[1252]: Failed to find Sensor 0x83
```

**Comment by amboar** [comment]
@devenrao Genuine question, can we publicly access the latest OP910.20 firmware images? If not, this issue should be written in terms of publicly available source. If not, then this issue shouldn't be in the public issue tracker.

**Comment by devenrao** [comment]
Rejected
IPMI is not supported for OP910 releases.
