### ISSUE TITLE
Witherspoon : IPMI : Mfg Date in IPMI FRU data is not matching with REST inventory data

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3013]
<cde:info> SW420437 </cde:info>

**Comment by amboar** [comment]
Can you please provide a means to reproduce the bug?

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10026> Fix FRU BuildDate DBus/IPMI exporting
Resolves  #3013 Witherspoon : IPMI : Mfg Date in IPMI FRU data is not matching with REST inventory data
