### ISSUE TITLE
GUI:  Recoverable errors are displayed as high priority event error

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3014]
<cde:info> SW420348 </cde:info>

**Comment by rfrandse** [comment]
Problem:
GUI event logs showing even recoverable errors as high priority events.
Had a suspect on seeing all error as high priority events. So decided to run RAS test and check GUI outcome.
Had a discussion with Gunnar and Adriana and agreed to open defect for this.
Currently openbmc does not parse the priority out of esel data. Looks like in tomorrow's design discussion this will be discussed.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9922> Fix error level lookup
Resolves  #3014 GUI:  Recoverable errors are displayed as high priority event error
