### ISSUE TITLE
phosphor-led-manager recipe needs to export its error yaml

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#3015]
Since it isn't doing this, phosphor-logging will not be able to grab any error metadata.

**Comment by spinler** [comment]
Several other components seemed to have stopped exporting their yaml to phosphor-logging, maybe with the upgrade to the new yocto version...
* phosphor-bmc-code-mgmt
* openpower-host-ipmi-oem
* witherspoon-pfault-analysis

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11235> Tell phosphor-logging about the LED error yaml
Resolves  #3015 phosphor-led-manager recipe needs to export its error yaml
