### ISSUE TITLE
 FVT: REST server failed to respond - curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3018]
<cde:info> SW420842 </cde:info>

**Comment by rfrandse** [comment]
Set Invalid Time Mode :: Set time mode with invalid value using RE... | FAIL |
ConnectionError: HTTPSConnectionPool(host='wsbmc002', port=443): Max retries exceeded with url: /xyz/openbmc_project/time/sync_method/attr/TimeSyncMethod (Caused by ProtocolError('Connection aborted.', BadStatusLine("''",)))

gkeishin@gfwa124 ~/obmcutil-commands
$ export  BMC_IP=wsbmc002

gkeishin@gfwa124 ~/obmcutil-commands
$  curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://$BMC_IP/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"                                       {
 "data": "User 'root' logged in",
 "message": "200 OK",
 "status": "ok"
}

BAD Invalid string:

**Comment by ojayanth** [comment]
Not seeing this issue in the latest build.

}jayanths-MBP:~ ojayanth$curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://$BMC_IP/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"
{
  "data": "User 'root' logged in", 
  "message": "200 OK", 
  "status": "ok"

}jayanths-MBP:~ ojayanth$ curl b cjar -k -H 'Content-Type: application/json' -X PUT -d '{"data":"xyz.openbmc_project.Time.Synchronization.Method.abc"}' https://$BMC_IP//xyz/openbmc_project/time/sync_method/attr/TimeSyncMethod
{
  "data": {
    "description": "Internal Server Error", 
    "exception": "DBusException('An enumeration mapping was attempted for which no valid enumeration value exists.',)", 
    "traceback": [
      "Traceback (most recent call last):", 
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 862, in _handle", 
      "    return route.call(**args)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1025, in __call__", 
      "    return self.callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1090, in wrap", 
      "    return callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1273, in __call__", 
      "    return self.callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1247, in wrap", 
      "    return self.to_jsonp(callback(*a, **kw))", 
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 1742, in wrapper", 
      "    rv = callback(*a, **ka)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1212, in wrap", 
      "    data = callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 1141, in wrap", 
      "    return callback(*a, **kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 221, in __call__", 
      "    return getattr(self, 'do_' + request.method.lower())(**kw)", 
      "  File \"/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py\", line 473, in do_put", 
      "    properties_iface.Set(iface, prop, value)", 
      "  File \"/usr/lib/python2.7/site-packages/dbus/proxies.py\", line 145, in __call__", 
      "    **keywords)", 
      "  File \"/usr/lib/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking", 
      "    message, timeout)", 
      "DBusException: xyz.openbmc_project.sdbusplus.Error.InvalidEnumString: An enumeration mapping was attempted for which no valid enumeration value exists."
    ]
  }, 
  "message": "500 Internal Server Error", 
  "status": "error"

**Comment by ojayanth** [comment]
@gkeishin good to close?

**Comment by gkeishin** [comment]
Yeap.. Thanks
