### ISSUE TITLE
GUI: Entering a bad username/password should display relevant error

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3024]
Enter a bad username/password on the GUI login and the error returned is "Server unreachable".
The error should be "Incorrect username or password". 
There is code for this error, but it must not be working. 
https://github.com/openbmc/phosphor-webui/blob/master/app/login/controllers/login-controller.html#L26

![openbmc_errors](https://user-images.githubusercontent.com/5455127/37617907-70ccd686-2b82-11e8-8738-82bd59bf8110.PNG)

**Comment by iftekharuli** [comment]
This has been coded and tested before intel code merge. @gtmills do you want to fix this or what me to handle?

**Comment by gtmills** [comment]
@iftekharuli If you don't mind taking this, I have some other issues I am working. Thanks!

**Comment by gtmills** [comment]
looks like https://gerrit.openbmc-project.xyz/#/c/9618/  resolves this

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9618> Show error message received from server side
Resolves  #3024 GUI: Entering a bad username/password should display relevant error
