### ISSUE TITLE
[OPAL] ipmid[1245]: Failed to create a method call: Invalid request descriptor

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3025]
<cde:info> SW421601 </cde:info>

**Comment by rfrandse** [comment]
Nagaraju, can you include this one for the trace cleanup? There are no functional issues here. This is ipmid doing some non-existing legacy D-Bus lookups and ignoring the errors (but adding traces).

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10425> Reducing IPMI logging footprint
Resolves  #3025 [OPAL] ipmid[1245]: Failed to create a method call: Invalid request descriptor

**Comment by dkodihal** [comment]
This needs to be cleaned up with the changes for #2154.
