### ISSUE TITLE
GUI: Add activate BMC firmware and reboot BMC option 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3027]
When you activate a BMC firmware image, the BMC must be rebooted before it will operate with the new firmware. Add a radio button in the activate confirm modal (pops up when the user activates a BMC image) and the functionality to activate a  BMC image **and** reboot the BMC. 
![new_confirm_activation_modal_v2](https://user-images.githubusercontent.com/5455127/37684739-fd54cb40-2c5e-11e8-9751-f1e17b9a360f.jpg)

**Comment by gtmills** [comment]
the last part of the text body should actually be "activation has completed" instead of "when it is done"

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9888> Activate firmware and reboot if selected
Resolves  #3027 GUI: Add activate BMC firmware and reboot BMC option
