### ISSUE TITLE
GPU fru info not available in IPMI fru print

### ISSUE THREAD

**Issue by ngorugan** [openbmc/openbmc#3039]
The commit: https://gerrit.openbmc-project.xyz/9639 Add power supply to BMC accessible FRUs to generate FRU map , Partially fixes the issue  #2984, but some how the issue got closed, opening this issue to fx GPU fru info.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9872> Add GPU FRUs to generate FRU map
Resolves  #3039 GPU fru info not available in IPMI fru print
