### ISSUE TITLE
GUI: Remove "Activation" from inventory

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3042]
"Activation" is the reverse association of the Software Image to Inventory Item association. 
More information here about the association: 
https://github.com/openbmc/phosphor-dbus-interfaces/tree/master/xyz/openbmc_project/Software#itemupdater
 
![activation_inventory](https://user-images.githubusercontent.com/5455127/38041937-a64b6208-3278-11e8-9f28-4e84c2b2ee39.PNG)

**Comment by gtmills** [comment]
We could just ignore this item when we get the inventory in the GUI. But is this reverse association useful? I guess someone could look at `/xyz/openbmc_project/inventory/system/chassis/activation`  for host images or `/xyz/openbmc_project/inventory/system/chassis/motherboar/boxelder/bmc/activation` for the BMC images?

**Comment by spinler** [comment]
The callouts in errors logs are also associations that show up in the inventory.  Would be good to remove those too.

![image](https://user-images.githubusercontent.com/9370114/38995146-e4cce2ea-43ad-11e8-939b-8e95aacdc965.png)

**Comment by geissonator** [comment]
This is blocked on #3117 so pushing into backlog until that's resolved.

**Comment by gtmills** [comment]
This is done. Closing. https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/18722
