### ISSUE TITLE
On IBM systems capture the com.ibm.Logging objects in dreport

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#3043]
This namespace is going to hold some additional IBM specific error logging data.  It would be useful to get this back from a dreport dump.  Will install the dreport shell script to do this from the meta-ibm layer.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9831> dreport: Collect IBM error objects on IBM systems
Resolves  #3043 On IBM systems capture the com.ibm.Logging objects in dreport
