### ISSUE TITLE
OpenBMC CLAs are not hosted anywhere

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#3046]
The CLA signing process needs to be documented from both a contributor and maintainer view.

**Comment by bradbishop** [comment]
[OpenBMC CCLA.pdf](https://github.com/openbmc/openbmc/files/1860741/OpenBMC.CCLA.pdf)
[OpenBMC ICLA.pdf](https://github.com/openbmc/openbmc/files/1860742/OpenBMC.ICLA.pdf)

**Comment by bradbishop** [comment]
Signed CLAs for maintainers are stored here, until we get a better process:

https://drive.google.com/drive/folders/1Ooi0RdTcaOWF1DWFJUAJDdN7tRKde7Nl

**Comment by gtmills** [comment]
Can you give permission to the current maintainers to review?

**Comment by bradbishop** [comment]
> Can you give permission

Done I think.  Let me know.

**Comment by AlexanderAmelkin** [comment]
We have signed the CLA and have sent it to manager@lfprojects.org yesterday (19/04/2018 14:39 MSK). Can't see it at the google drive link so far.

**Comment by gtmills** [comment]
We have a write up here: https://github.com/openbmc/docs/blob/master/maintainer-workflow.md
What is the plan long term for hosting signed CLAs?

**Comment by krtaylor** [comment]
The long term plan, a tool for CLA mgmt being developed by the LF, is still pending. Until the LF tool is deployed, we will continue to use the google drive linked above.
