### ISSUE TITLE
Webui stop at login

### ISSUE THREAD

**Issue by ThaiThu** [openbmc/openbmc#3051]
Hi all, the webui is already built to my BMC and when I browse to its address, it stops at "Login required", like this:

![image](https://user-images.githubusercontent.com/14868732/38133894-987d0632-3443-11e8-9a15-bbeed046ff4a.png)

The Readme tell me to navigate to http://localhost:8080, but when I navigate to there, it show: connection to server refused

Thank you.

**Comment by gtmills** [comment]
`http://localhost:8080` is for running the GUI locally. 
To run the GUI locally, from your phosphor-webui repo: 
 `npm install`, `npm run-script server`, and then go to http://localhost:8080. You will want to set the `Host` field on the logon page to an OpenBMC machine. The GUI uses this `Host` field to know where to send the REST calls.
 Note: You may need to go to https://<your BMC address> and accept the certificate, otherwise, your traffic to that address may be blocked by your browser.  

![accept_certificate](https://user-images.githubusercontent.com/5455127/38149887-13955cf6-3422-11e8-8028-fce4e8c85f5a.PNG)

**Comment by gtmills** [comment]
What system are you using? The only systems I know that has the WebUI installed in the image are `Witherspoon` and `x86` systems.
https://github.com/openbmc/openbmc/blob/master/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend#L3

https://github.com/openbmc/openbmc/blob/master/meta-openbmc-machines/meta-x86/meta-intel/meta-common/recipes-intel/packagegroups/packagegroup-intel-apps.bb#L50

**Comment by ThaiThu** [comment]
Hi @gtmills ,
Yes, I already added it in my image.

![image](https://user-images.githubusercontent.com/14868732/38179706-e2c66492-3658-11e8-8bcb-1fcb50eaf38a.png)

Thank you.

**Comment by ThaiThu** [comment]
Hi, @gtmills ,

When I install it locally, I can browse to the login page, and fill the host ip/user/password, but when I login, the GUI warns that the server unreachable, although I can ping my BMC, and login into it with RestfulApi.

Thank you.

**Comment by gtmills** [comment]
@ThaiThu You might need to, in a separate tab on your browser, go to https://<BMC> and accept the certificate.

**Comment by ThaiThu** [comment]
Hi @gtmills

Yes I do accept the certificate for the BMC machine.
![screenshot from 2018-04-03 09-55-15](https://user-images.githubusercontent.com/14868732/38225364-29c6e37a-3727-11e8-8a95-8efb45f01543.png)

Thank you.

**Comment by gtmills** [comment]
Is this the latest WebUI code? https://gerrit.openbmc-project.xyz/#/c/9618/ was recently merged to show the actual login error. Before "Server unreachable" was the error displayed when any error on login occurred.  Is there anything on the console? Could you add some console.log() statements in the login path to see where it is failing?

**Comment by gtmills** [comment]
@ThaiThu Any luck?

**Comment by ThaiThu** [comment]
@gtmills sorry, we recently had a long holiday in our country, I we don't have hardware to check it.
I will check it as soon as possible.

Thanks.

**Comment by ThaiThu** [comment]
Hi @gtmills ,

We clone new git branch, and now the webui works

Thank you !!

**Comment by gtmills** [comment]
@ThaiThu Glad it worked! Can this issue be closed then?

**Comment by gtmills** [comment]
Going to close this issue. Please reopen if there is still a problem.

**Comment by EijahDuan** [comment]
Hi @gtmills,
"What system are you using? It looks to me like the WebUI package is not installed in the image. The only systems I know that has the WebUI installed in the image are Witherspoon and x86 systems."

Do you know how to installed WebUI in aspeed 2500? ths !

**Comment by ThaiThu** [comment]
@EijahDuan 
You can refer to this link to install web ui

https://github.com/openbmc/openbmc/blob/master/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend#L3
