### ISSUE TITLE
phosphor-ipmi-host package rebuilds almost every time

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#3053]
With commit https://github.com/openbmc/openbmc/commit/f02787a460b9fac4ccdb7974951a3d771da64920 , every time an image is built ( `bitbake obmc-phosphor-image` ) the phosphor-ipmi-host package gets rebuilt, including the packages depending on it, causing the build to now take much longer to rebuild simple changes unrelated to ipmi.

**Comment by anoo1** [comment]
@tomjoseph83 , Brad was saying that it can probably help to have the config file go into its own package.

**Comment by amboar** [comment]
I've pushed a patch which moves the configuration to a virtual that phosphor-ipmi-host RDEPENDs on:

https://gerrit.openbmc-project.xyz/#/c/9957/

**Comment by geissonator** [comment]
This has been merged

**Comment by anoo1** [comment]
Closing since it's being merged.
