### ISSUE TITLE
On IBM systems, display IBM error policy table fields in the GUI

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3056]
<cde:info> SW423214 </cde:info>

**Comment by spinler** [comment]
On IBM systems only, we need to figure out a way to display some IBM specific information in the Event Log page on the GUI.  This would need to of course be done generically since phosphor-webui is common to all systems.

**Comment by spinler** [comment]
An example:

![image](https://user-images.githubusercontent.com/9370114/39483970-c87c3128-4d39-11e8-870b-29b5540d0558.png)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10398> Display event log ID and description if present
Resolves  #3056 On IBM systems, display IBM error policy table fields in the GUI
