### ISSUE TITLE
SNMP : phosphor-dbus-monitor : send out traps corresponding to BMC error logs

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#3059]
Use the API implemented via #3058 to react to an InterfacesAdded signal for error log D-Bus objects, construct an SNMP trap, and send it out.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10192> SNMP event notification for error log entry objects
Resolves  #3059 SNMP : phosphor-dbus-monitor : send out traps corresponding to BMC error logs

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10192> SNMP error notification for error log entry objects
Resolves  #3059 SNMP : phosphor-dbus-monitor : send out traps corresponding to BMC error logs
