### ISSUE TITLE
SNMP : Create MIB for OpenBMC error logs

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#3060]
Design and deploy MIB to help decode a trap corresponding the OpenBMC error log event.

**Comment by ratagupt** [comment]
@dkodihal Can you please assign it to me?

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10143> Adding the mib for Error Log Notification
Resolves  #3060 SNMP : Create MIB for OpenBMC error logs
