### ISSUE TITLE
How can I add a sensor to OpenBMC?

### ISSUE THREAD

**Issue by momozizi1** [openbmc/openbmc#3063]
I'm beginner engineer of OpenBMC and embedded Linux.

I added the temp sensor lm75 on I2C bus my server board.
I did the follows step:
   1) Add I2C sensor config to devicetree
`temp1: temp1@48{
                        compatible = "national,lm75";
                        reg = <0x48>;
                        status = "okay";
                };
`
   2) Add sensor recipe(?) to recipes-phosphor/sensors/phosphor-hwmon%/obmc/hwmon/ahb/apb/i2c@1e78a000/i2c-bus@300/temp1@48.conf and bbappend file.
`MODE_temp1 = "label"
LABEL_temp1=cpu1
WARNLO_temp1=10000
WARNHI_temp1=40000`

   3) Build image.

In BMC, It seems to works good when I read use 'cat' cmd.

> ./sys/devices/platform/ahb/ahb:apb/ahb:apb:i2c@1e78a000/1e78a300.i2c-bus/i2c-7/7-0048/hwmon/hwmon1/temp1_input
26500

Then, I want to mapping sensor to d-bus xyz/openbmc_project/sensor. (I did not comprehend structure of Linux.. its right?) 
I searched xyz/openbmc_project/sensor structure with curl cmd, It is not exist.

> curl -b cjar -k https://192.168.10.221/xyz/openbmc_project/
"data": [
    "/xyz/openbmc_project/dump", 
    "/xyz/openbmc_project/software", 
    "/xyz/openbmc_project/control", 
    "/xyz/openbmc_project/network", 
    "/xyz/openbmc_project/logging", 
    "/xyz/openbmc_project/inventory", 
    "/xyz/openbmc_project/user", 
    "/xyz/openbmc_project/time", 
    "/xyz/openbmc_project/led", 
    "/xyz/openbmc_project/state"
  ], 
  "message": "200 OK", 
  "status": "ok"

Is there something as manual to add sensor or understand openbmc_project structure?
I need help.
Thank you.

**Comment by mine260309** [comment]
On Wed, Apr 4, 2018 at 9:32 AM, momozizi1 <notifications@github.com> wrote:
>
> I'm beginner engineer of OpenBMC and embedded Linux.
>
> I added the temp sensor lm75 on I2C bus our server board.
> I did the follows step:
>
> Add I2C sensor config to devicetree
> temp1: temp1@48{ compatible = "national,lm75"; reg = <0x48>; status = "okay"; };
>
> Add sensor recipe(?) to recipes-phosphor/sensors/phosphor-hwmon%/obmc/hwmon/ahb/apb/i2c@1e78a000/i2c-bus@300/temp1@48.conf and bbappend file.
> MODE_temp1 = "label" LABEL_temp1=cpu1 WARNLO_temp1=10000 WARNHI_temp1=40000

This is OK, but there is actually no need to use `MODE_temp1 = "label"` here,
because you know temp1 is for cpu1.

>
> Build image.
>
> In BMC, It seems to works good when I read use 'cat' cmd.
>
> ./sys/devices/platform/ahb/ahb:apb/ahb:apb:i2c@1e78a000/1e78a300.i2c-bus/i2c-7/7-0048/hwmon/hwmon1/temp1_input
> 26500
>
> Then, I want to mapping sensor to d-bus xyz/openbmc_project/sensor. (I did not comprehend structure of Linux.. its right?)
> I searched xyz/openbmc_project/sensor structure with curl cmd, It is not exist.
>
> curl -b cjar -k https://192.168.10.221/xyz/openbmc_project/
> "data": [
> "/xyz/openbmc_project/dump",
> "/xyz/openbmc_project/software",
> "/xyz/openbmc_project/control",
> "/xyz/openbmc_project/network",
> "/xyz/openbmc_project/logging",
> "/xyz/openbmc_project/inventory",
> "/xyz/openbmc_project/user",
> "/xyz/openbmc_project/time",
> "/xyz/openbmc_project/led",
> "/xyz/openbmc_project/state"
> ],
> "message": "200 OK",
> "status": "ok"
>
> Is there something as manual to add sensor or understand openbmc_project structure?

You are doing right. But since you did not see the sensor from DBUS, you may
want to check:
1. Where does /sys/class/hwmon/hwmon1/of-node point to?
   It should be the file in device tree, make sure it matches your .conf file
2. Make sure the conf file is correctly install into
   "/etc/default/obmc/hwmon/ahb/apb/..."
3. Check if phosphor-hwmon-readd is working on your device.
   e.g. by ps | grep hwmon

**Comment by mine260309** [comment]
On Wed, Apr 4, 2018 at 12:20 PM, momozizi1 <notifications@github.com> wrote:
>
> Thanks for reply.
>
> Where does /sys/class/hwmon/hwmon1/of-node point to?
> It should be the file in device tree, make sure it matches your .conf file
>
> Make sure the conf file is correctly install into
> "/etc/default/obmc/hwmon/ahb/apb/..."
>
> I did not make conf file. I don't know where I should do that. Can you provide to me some example?

The conf file is the one in your original mail
(recipes-phosphor/sensors/phosphor-hwmon%/obmc/hwmon/ahb/apb/i2c@1e78a000/i2c-bus@300/temp1@48.conf)

>
> Check if phosphor-hwmon-readd is working on your device.
> phosphor-hwmon-readd is exist /usr/sbin folder.
> But it is not working when I check 'ps | grep hwmon'.
>
> Do I have to study the source code of 'phosphor-hwmon' for understand to adding sensor? or more things?

No, if you have correctly put the conf file, the phosphor-hwmon will be
started by udev rule automatically and it will work just fine.

**Comment by momozizi1** [comment]
You gave me the right direction.
Thank you. I will try more.

**Comment by aaronw2** [comment]
I'm basically having a similar problem to the original author here. In my case, the .conf files are not being installed. As far as I can tell they are in the correct subdirectories which match what is shown from the of_node entries. Do I need to do anything special for the conf files to be installed?

**Comment by Student2C0** [comment]
Hi. I am trying to add a sensor to my OpenBMC environment on RaspberryPi 4-b platform but struggling this very much.
So,could someone please give me advice about my case ?

I am writing my steps below.

**Step#1: I physically connected an ADS1115 sensor to my Rpi4 board and saw where it is connected on my Raspberry Pi OS .**
  I made sure the sensor has 0x48 address and is connected to 12C Bus #1 which is shared with i2C@7e804000 on BCM2835 before I actually started to build openbmc image for this platform.

    pi@raspberrypi:/boot/overlays $ sudo i2cdetect -l
    i2c-1	i2c       	bcm2835 (i2c@7e804000)          	I2C adapter

    pi@raspberrypi:/boot/overlays $ 
    pi@raspberrypi:/boot/overlays $ sudo i2cdetect -y 1
         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
    00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
    10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    40: -- -- -- -- -- -- -- -- 48 -- -- -- -- -- -- -- 
    50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    70: -- -- -- -- -- -- -- --                         
    pi@raspberrypi:/boot/overlays $


**Step#2: I set up a new OpenBMC environment for Rpi 4 board.**

**Step#2-1: git clone**

     yocto@yocto-VM:~/Rpi4-2.8.0$ git clone https://github.com/openbmc/openbmc.git -b 2.8.0

I chose 2.8.0 due to #3812.

**Step#2-2: Set TEMPLATECONT**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc$ export TEMPLATECONF=meta-evb/meta-evb-raspberrypi/conf
    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc$ echo $TEMPLATECONF
        meta-evb/meta-evb-raspberrypi/conf

**Step#2-3: Set open-env**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/. openbmc-env
    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build

**Step#2-4: Modify local.conf**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build/conf$ diff local.conf local.conf.bk 
    1c1
    < MACHINE ??= "raspberrypi4"
    ---
    > MACHINE ??= "raspberrypi"
    18,22d17
    < 
    < DL_DIR ?= "/home/yocto/Yocto/downloads-4-2.8.0"
    < SSTATE_DIR ?= "/home/yocto/Yocto/sstate-cache-4-2.8.0"
    < IMAGE_FSTYPES += " rpi-sdimg"
    < 

**Step#2-5: Modify image_types_phosphor.bbclass file.**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/meta-phosphor/classes$ diff image_types_phosphor.bbclass image_types_phosphor.bbclass.bk 
    38c38
    < FLASH_SIZE ?= "131072"
    ---
    > FLASH_SIZE ?= "32768"

This is due to #3590

**Step#3: Set up a config file for ads1115 sensor**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/meta-evb/meta-evb-raspberrypi/recipes-phosphor/sensors/phosphor-hwmon/obmc/hwmon/soc/i2c@7e804000$ ls -la
        -rwxrwxr-x 1 yocto yocto   70  Sep 15 10:23 ads1115@48.conf

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/meta-evb/meta-evb-raspberrypi/recipes-phosphor/sensors/phosphor-hwmon/obmc/hwmon/soc/i2c@7e804000$ cat ads1115@48.conf 
    LABEL_pw1=cpu
    WARNLO_pw1=0
    WARNHI_pw1=45
    CRITHI_pw1=50
    CRITLO_pw1=-5

    I attached my dts file to see if the path is correct. As far as I see, the child path of hwmon will be soc/i2c@7e804000

**Step#4: Set up a bbappend file for the added conf file.**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/meta-evb/meta-evb-raspberrypi/recipes-phosphor/sensors/phosphor-hwmon/obmc/hwmon/soc/i2c@7e804000$ ls -la
        -rwxrwxr-x 1 yocto yocto  259  Sep 15 10:26 phosphor-hwmon_%.bbappend

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/meta-evb/meta-evb-raspberrypi/recipes-phosphor/sensors$ cat phosphor-hwmon_%.bbappend
    FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

    CHIPS = "i2c@7e804000/ads1115@48"
    ITEMSFMT = "soc/{0}.conf"

    ITEMS = "${@compose_list(d, 'ITEMSFMT', 'CHIPS')}"

    ENVS = "obmc/hwmon/{0}"
    SYSTEMD_ENVIRONMENT_FILE_${PN} += "${@compose_list(d, 'ENVS', 'ITEMS')}"


**Step#5: Modify dts file**

**Step#5-1: git clone dts file**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build$ git clone https://github.com/raspberrypi/linux.git

**Step#5-2: Add newly added sensor info to dts file.**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build/linux/arch/arm/boot/dts$ diff bcm283x.dtsi /home/yocto/Backup/bcm283x.dtsi-Rpi4
    488,494c488
    < 			status = "okay";
    < 
    < 			ads1115@48 {
    < 				compatible = "ti1,ads1115";
    < 				reg = <0x48>;
    < 				status = "okay";
    < 			};
    ---
    > 			status = "disabled";


**Step#5-3: make dts to create dtb**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build/linux$ export ARCH=arm64
    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build/linux$ echo $ARCH
    arm64

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build/linux$ make dtbs
      - Snip logs -
      DTC     arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb

**Step#5-4: Check a created dtb file**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom$ dtc -I dtb -O dts bcm2711-rpi-4-b.dtb > /home/yocto/CP-bcm2711-rpi-4-b.dts
    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom$ cat /home/yocto/CP-bcm2711-rpi-4-b.dts

    snip logs

    		i2c@7e804000 {
    			compatible = "brcm,bcm2711-i2c\0brcm,bcm2835-i2c";
    			reg = <0x7e804000 0x1000>;
    			interrupts = <0x00 0x75 0x04>;
    			clocks = <0x07 0x14>;
    			#address-cells = <0x01>;
    			#size-cells = <0x00>;
    			status = "disabled";
    			pinctrl-names = "default";
    			pinctrl-0 = <0x18>;
    			clock-frequency = <0x186a0>;
    			phandle = <0x35>;
    
    			ads1115@48 {
		    		compatible = "ti1,ads1115";   <<  I intentionally changed from ti to ti1 here. But I don't think this matters.
		    		reg = <0x48>;
					status = "okay";
    			};
    		};

The following log shows directory of bcm2711-rpi-4-b.dts and it says i2c1 is /soc/i2c@7e804000.

    /dts-v1/;

    /memreserve/	0x0000000000000000 0x0000000000001000;
    / {
	    compatible = "raspberrypi,4-model-b\0brcm,bcm2711";
	    model = "Raspberry Pi 4 Model B";
	    #address-cells = <0x02>;
	    #size-cells = <0x01>;
	    interrupt-parent = <0x01>;

    	aliases {
          snip logs
    		i2c1 = "/soc/i2c@7e804000";
           snip logs
    	};


**Step#6: Modify machine conf.**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/meta-raspberrypi/conf/machine$ diff raspberrypi4.conf raspberrypi4-bk.conf.bk
    9,10d8
    < KERNEL_DEVICETREE = "/home/yocto/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb"
    < 
    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/meta-raspberrypi/conf/machine$ 


**Step#7: bitbake the new image**

    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build$ bitbake obmc-phosphor-image

    WARNING: linux-raspberrypi-1_4.19.120+gitAUTOINC+9da67d7329-r0 do_compile: /home/yocto/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb contains the full path to the the dts file, but only the dtb name should be used.
    WARNING: linux-raspberrypi-1_4.19.120+gitAUTOINC+9da67d7329-r0 do_assemble_fitimage: /home/yocto/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb contains the full path to the the dts file, but only the dtb name should be used.
    WARNING: linux-raspberrypi-1_4.19.120+gitAUTOINC+9da67d7329-r0 do_install: /home/yocto/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb contains the full path to the the dts file, but only the dtb name should be used.
    WARNING: linux-raspberrypi-1_4.19.120+gitAUTOINC+9da67d7329-r0 do_assemble_fitimage_initramfs: /home/yocto/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb contains the full path to the the dts file, but only the dtb name should be used.
    WARNING: linux-raspberrypi-1_4.19.120+gitAUTOINC+9da67d7329-r0 do_deploy: /home/yocto/Rpi4-2.8.0/openbmc/build/linux/arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb contains the full path to the the dts file, but only the dtb name should be used.
    WARNING: obmc-phosphor-sysd-1.0-r1 do_package_qa: QA Issue: obmc-phosphor-sysd: SRC_URI uses PN not BPN [src-uri-bad]
    Using an insecure image signing key!
    NOTE: Tasks Summary: Attempted 4162 tasks of which 1495 didn't need to be rerun and all succeeded.

    Summary: There were 6 WARNING messages shown.
    yocto@yocto-VM:~/Rpi4-2.8.0/openbmc/build$ 

I saw several WARNING but it finished without ERROR.


**Step#8: See if the sensor is added to Rpi4.**

    cat /etc/os-release 
    ID=openbmc-phosphor
    NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
    VERSION="2.8.0-0"
    VERSION_ID=2.8.0-0-g314c4ecc0-dirty
    PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.8.0-0"
    BUILD_ID="2.8.0"
    OPENBMC_TARGET_MACHINE="raspberrypi4"
    root@raspberrypi4:~# 

No sensor is added and /dev/i2c1 did not even exist.

    root@raspberrypi4:~# ls /etc/default/obmc/hwm   
    mapper    watchdog/ 

    root@raspberrypi4:~# ls /sys/class/hwmon/hwmon0
    device           name             subsystem
    in0_lcrit_alarm  power            uevent

    root@raspberrypi4:~# ls /sys/firmware/devicetree/base/soc/i2c@7e804000
    #address-cells   clocks           name             pinctrl-names
    #size-cells      compatible       phandle          reg
    clock-frequency  interrupts       pinctrl-0        status

hwmon did not start.

    root@raspberrypi4:~# journalctl | grep hwmon
    Sep 15 15:07:17 raspberrypi4 systemd[1]: Created slice system-xyz.openbmc_project.Hwmon.slice.
    Sep 15 15:07:17 raspberrypi4 systemd[1]: Condition check resulted in Phosphor Hwmon Poller being skipped.

    root@raspberrypi4:~# udevadm test /sys/class/hwmon/hwmon
    This program is for debugging only, it does not run any program
    specified by a RUN key. It may show incorrect results, because
    some values may be different, or not available at a simulation run.

    Load module index
    Parsed configuration file /lib/systemd/network/99-default.link
    Created link configuration context.
    Reading rules file: /lib/udev/rules.d/50-udev-default.rules
    Reading rules file: /lib/udev/rules.d/60-autosuspend-chromiumos.rules
    Reading rules file: /lib/udev/rules.d/60-block.rules
    Reading rules file: /lib/udev/rules.d/60-cdrom_id.rules
    Reading rules file: /lib/udev/rules.d/60-drm.rules
    Reading rules file: /lib/udev/rules.d/60-evdev.rules
    Reading rules file: /lib/udev/rules.d/60-fido-id.rules
    Reading rules file: /lib/udev/rules.d/60-input-id.rules
    Reading rules file: /lib/udev/rules.d/60-persistent-alsa.rules
    Reading rules file: /lib/udev/rules.d/60-persistent-input.rules
    Reading rules file: /lib/udev/rules.d/60-persistent-storage-tape.rules
    Reading rules file: /lib/udev/rules.d/60-persistent-storage.rules
    Reading rules file: /lib/udev/rules.d/60-persistent-v4l.rules
    Reading rules file: /lib/udev/rules.d/60-sensor.rules
    Reading rules file: /lib/udev/rules.d/60-serial.rules
    Reading rules file: /lib/udev/rules.d/61-autosuspend-manual.rules
    Reading rules file: /lib/udev/rules.d/64-btrfs.rules
    Reading rules file: /lib/udev/rules.d/70-hwmon.rules
    Reading rules file: /lib/udev/rules.d/70-iio.rules
    Reading rules file: /lib/udev/rules.d/70-joystick.rules
    Reading rules file: /lib/udev/rules.d/70-leds.rules
    Reading rules file: /lib/udev/rules.d/70-mouse.rules
    Reading rules file: /lib/udev/rules.d/70-touchpad.rules
    Reading rules file: /lib/udev/rules.d/75-net-description.rules
    Reading rules file: /lib/udev/rules.d/75-probe_mtd.rules
    Reading rules file: /lib/udev/rules.d/78-sound-card.rules
    Reading rules file: /lib/udev/rules.d/80-drivers.rules
    Reading rules file: /lib/udev/rules.d/80-net-setup-link.rules
    Reading rules file: /lib/udev/rules.d/80-obmc-console-uart.rules
    Reading rules file: /etc/udev/rules.d/99-com.rules
    /etc/udev/rules.d/99-com.rules:10 Invalid value "/bin/sh -c 'ALIASES=/proc/device-tree/aliases; if cmp -s $ALIASES/uart0 $ALIASES/serial0; then echo 0;elif cmp -s $ALIASES/uart0 $ALIASES/serial1; then echo 1; else exit 1; fi'" for PROGRAM (char 58: invalid substitution type), ignoring, but please fix it.
    /etc/udev/rules.d/99-com.rules:21 Invalid value "/bin/sh -c 'ALIASES=/proc/device-tree/aliases; if cmp -s $ALIASES/uart1 $ALIASES/serial0; then echo 0; elif cmp -s $ALIASES/uart1 $ALIASES/serial1; then echo 1; else exit 1; fi '" for PROGRAM (char 58: invalid substitution type), ignoring, but please fix it.
    Reading rules file: /lib/udev/rules.d/99-systemd.rules
    Reading rules file: /etc/udev/rules.d/can.rules
    Reading rules file: /etc/udev/rules.d/touchscreen.rules
    >>Failed to open device '/sys/class/hwmon/hwmon': No such device
    Unload module index
    Unloaded link configuration context.
    root@raspberrypi4:~# 


As you can see, there is no sensor found on my Rpi platform and I am wondering if I overlooked something or took wrong steps.
There is one thing I suspect is this is a Raspberry Pi board and might need to change i2c interface to enable by rspi-config before I use i2c but I didn't do this.
Now, I will try to do this but I am not sure if this works.
So, I would really appreciate someone give me advice about this.

[bcm2711-rpi-4-b.dts.txt](https://github.com/openbmc/openbmc/files/7179096/bcm2711-rpi-4-b.dts.txt)

**Comment by AloneWarrior11011** [comment]
> On Wed, Apr 4, 2018 at 12:20 PM, momozizi1 ***@***.***> wrote:
> 
>  Thanks for reply.
> 
>  Where does /sys/class/hwmon/hwmon1/of-node point to?
>  It should be the file in device tree, make sure it matches your .conf file
> 
>  Make sure the conf file is correctly install into
>  "/etc/default/obmc/hwmon/ahb/apb/..."
> 
>  I did not make conf file. I don't know where I should do that. Can you provide to me some example?
> The conf file is the one in your original mail
> (recipes-phosphor/sensors/phosphor-hwmon%/obmc/hwmon/ahb/apb/i2c@1e78a000/i2c-bus@300/temp1@48.conf)
> 
>  Check if phosphor-hwmon-readd is working on your device.
>  phosphor-hwmon-readd is exist /usr/sbin folder.
>  But it is not working when I check 'ps | grep hwmon'.
> 
>  Do I have to study the source code of 'phosphor-hwmon' for understand to adding sensor? or more things?
> No, if you have correctly put the conf file, the phosphor-hwmon will be
> started by udev rule automatically and it will work just fine.
> […](#)



In my case the configuration file of tmp75@4d perfectly installed into /etc/default/obmc/hwmon/i2c-1/[tmp75@4d.conf](mailto:tmp75@4d.conf), but devide node not created, tmp75.dts file content looks
fine, but I think there might be some issue in linux-raspberrypi_%.bbappend recipe that don't place dts file in the right location while building openbmc image for raspberrypi.

If I get your complete recipe structure, it would really helpful for me to figure out the issue.

if you need complete recipe structure to get the actual issue I will post here as well.


```
**Configuration file been installed :** 

root@raspberrypi3:~# ls -la /etc/default/obmc/hwmon/i2c-1
drwxr-xr-x    2 root     root          1024 Apr  5  2011 .
drwxr-xr-x    3 root     root          1024 Apr  5  2011 ..
-rw-r--r--    1 root     root           211 Apr  5  2011 tmp75@4d.conf
```

```
**journalctl shows skipped logs :** 

root@raspberrypi3:~# journalctl | grep Hwmon
Dec 19 21:25:51 raspberrypi3 systemd[1]: Created slice Slice /system/xyz.openbmc_project.Hwmon.
Dec 19 21:25:54 raspberrypi3 systemd[1]: Phosphor Hwmon Poller was skipped because of an unmet condition check (ConditionFileNotEmpty=/etc/default/obmc/hwmon/devices/virtual/thermal/thermal_zone0/hwmon0.conf).

```

```
**Conf file been installed to the right directory :** 

root@raspberrypi3:~# ls -l /etc/default/obmc
drwxr-xr-x    3 root     root          1024 Apr  5  2011 hwmon
drwxr-xr-x    2 root     root          1024 Apr  5  2011 watchdog
```

```
**No entry here for tmp75 sensor (device tree entries) :** 

root@raspberrypi3:~# ls -la /sys/firmware/devicetree/base
-r--r--r--    1 root     root             4 Apr  4 10:53 #address-cells
-r--r--r--    1 root     root             4 Apr  4 10:53 #size-cells
drwxr-xr-x   25 root     root             0 Dec 19 21:25 .
drwxr-xr-x    3 root     root             0 Dec 19 21:25 ..
drwxr-xr-x    2 root     root             0 Apr  4 10:53 __overrides__
drwxr-xr-x    2 root     root             0 Apr  4 10:53 __symbols__
drwxr-xr-x    2 root     root             0 Apr  4 10:53 aliases
drwxr-xr-x    2 root     root             0 Apr  4 10:53 arm-pmu
drwxr-xr-x    3 root     root             0 Apr  4 10:53 axi
drwxr-xr-x    2 root     root             0 Apr  4 10:53 cam0_clk
drwxr-xr-x    2 root     root             0 Apr  4 10:53 cam0_regulator
drwxr-xr-x    2 root     root             0 Apr  4 10:53 cam1_clk
drwxr-xr-x    2 root     root             0 Apr  4 10:53 cam1_regulator
drwxr-xr-x    2 root     root             0 Apr  4 10:53 cam_dummy_reg
drwxr-xr-x    4 root     root             0 Apr  4 10:53 chosen
drwxr-xr-x    4 root     root             0 Apr  4 10:53 clocks
-r--r--r--    1 root     root            35 Dec 19 21:25 compatible
drwxr-xr-x    7 root     root             0 Apr  4 10:53 cpus
drwxr-xr-x    2 root     root             0 Apr  4 10:53 fixedregulator_3v3
drwxr-xr-x    2 root     root             0 Apr  4 10:53 fixedregulator_5v0
-r--r--r--    1 root     root             4 Apr  4 10:53 interrupt-parent
drwxr-xr-x    4 root     root             0 Apr  4 10:53 leds
drwxr-xr-x    2 root     root             0 Apr  4 10:53 memory@0
-r--r--r--    1 root     root             8 Apr  4 10:53 memreserve
-r--r--r--    1 root     root            31 Apr  4 10:53 model
-r--r--r--    1 root     root             1 Apr  4 10:53 name
drwxr-xr-x    2 root     root             0 Apr  4 10:53 phy
drwxr-xr-x    3 root     root             0 Apr  4 10:53 reserved-memory
-r--r--r--    1 root     root            17 Apr  4 10:53 serial-number
drwxr-xr-x   52 root     root             0 Apr  4 10:53 soc
drwxr-xr-x    2 root     root             0 Apr  4 10:53 system
drwxr-xr-x    3 root     root             0 Apr  4 10:53 thermal-zones
drwxr-xr-x    2 root     root             0 Apr  4 10:53 timer

```
```
**tmp75 driver not loaded even after I have configured lm75 driver support through kernel configuration :** 

root@raspberrypi3:~# dmesg | grep tmp75

```

```
**udevadm output has some problem** 

root@raspberrypi3:~#  udevadm test /sys/class/hwmon/hwmon0
This program is for debugging only, it does not run any program
specified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
Trying to open "/usr/lib/systemd/hwdb/hwdb.bin"...
Trying to open "/usr/lib/udev/hwdb.bin"...
hwdb.bin does not exist, please run 'systemd-hwdb update'.
Found container virtualization none.
Using default interface naming scheme 'v257'.
Parsed configuration file "/usr/lib/systemd/network/99-default.link"
Parsed configuration file "/usr/lib/systemd/network/80-vm-vt.link"
Parsed configuration file "/usr/lib/systemd/network/80-namespace-ns.link"
Parsed configuration file "/usr/lib/systemd/network/80-container-vz.link"
Parsed configuration file "/usr/lib/systemd/network/80-container-ve.link"
Parsed configuration file "/usr/lib/systemd/network/80-container-vb.link"
Parsed configuration file "/usr/lib/systemd/network/80-6rd-tunnel.link"
Created link configuration context.
Reading rules file: /usr/lib/udev/rules.d/50-udev-default.rules
Reading rules file: /usr/lib/udev/rules.d/60-autosuspend.rules
Reading rules file: /usr/lib/udev/rules.d/60-block.rules
Reading rules file: /usr/lib/udev/rules.d/60-dmi-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-drm.rules
Reading rules file: /usr/lib/udev/rules.d/60-evdev.rules
Reading rules file: /usr/lib/udev/rules.d/60-infiniband.rules
Reading rules file: /usr/lib/udev/rules.d/60-input-id.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-mtd.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /usr/lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /usr/lib/udev/rules.d/60-sensor.rules
Reading rules file: /usr/lib/udev/rules.d/60-serial.rules
Reading rules file: /usr/lib/udev/rules.d/64-btrfs.rules
Reading rules file: /usr/lib/udev/rules.d/70-camera.rules
Reading rules file: /usr/lib/udev/rules.d/70-hwmon.rules
Reading rules file: /usr/lib/udev/rules.d/70-iio.rules
Reading rules file: /usr/lib/udev/rules.d/70-joystick.rules
Reading rules file: /usr/lib/udev/rules.d/70-leds.rules
Reading rules file: /usr/lib/udev/rules.d/70-mouse.rules
Reading rules file: /usr/lib/udev/rules.d/70-touchpad.rules
Reading rules file: /usr/lib/udev/rules.d/75-net-description.rules
Reading rules file: /usr/lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /usr/lib/udev/rules.d/78-sound-card.rules
Reading rules file: /usr/lib/udev/rules.d/80-net-setup-link.rules
Reading rules file: /usr/lib/udev/rules.d/80-obmc-console-uart.rules
Reading rules file: /usr/lib/udev/rules.d/81-net-dhcp.rules
Reading rules file: /etc/udev/rules.d/99-com.rules
/etc/udev/rules.d/99-com.rules:2 Unknown group 'i2c', ignoring.
/etc/udev/rules.d/99-com.rules:3 Unknown group 'spi', ignoring.
/etc/udev/rules.d/99-com.rules:4 Unknown group 'gpio', ignoring.
/etc/udev/rules.d/99-com.rules:10 Unknown group 'gpio', ignoring.
Reading rules file: /usr/lib/udev/rules.d/99-systemd.rules
Reading rules file: /etc/udev/rules.d/can.rules
Reading rules file: /etc/udev/rules.d/fb.rules
Reading rules file: /etc/udev/rules.d/touchscreen.rules
hwmon0: /usr/lib/udev/rules.d/70-hwmon.rules:1 RUN '/usr/bin/start_hwmon.sh start %p %E{OF_FULLNAME}'
Properties:
  DEVPATH=/devices/virtual/thermal/thermal_zone0/hwmon0
  ACTION=add
  SUBSYSTEM=hwmon
  USEC_INITIALIZED=307964567
Queued commands:
  RUN{program} : /usr/bin/start_hwmon.sh start /devices/virtual/thermal/thermal_zone0/hwmon0 
Unloaded link configuration context.

```
device not created in sysfs despite being tmp75@4d.conf installed into /etc/default/obmc/hwmon/i2c-1/tmp75@4d.conf. 

do resolve my problem, I would be thankful to you always...!
