### ISSUE TITLE
Witherspoon : IPMI : IPMI still show cdrom after changing boot device from cdrom to bios via IPMI

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3068]
<cde:info> SW423878 </cde:info>

**Comment by rfrandse** [comment]
Unable to set the boot device from cdrom to bios via IPMI.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10479> Fix get boot options returning unexpected results
Resolves  #3068 Witherspoon : IPMI : IPMI still show cdrom after changing boot device from cdrom to bios via IPMI
