### ISSUE TITLE
TPM sensor is not displayed on BMC Web Interface

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3072]
<cde:info> SW422777 </cde:info>

**Comment by rfrandse** [comment]
Problem Description :
TPM enable  Sensor is showing in IPMI inetrface
-bash-4.1$ ipmitool -I lanplus -H  9.5.166.186  -P 0penBmc sensor list|grep -i TPM
TPMEnable        | 0x0        | discrete   | 0x0100| na        | na        | na        | na        | na        | na
-bash-4.1$

But  on GUI sensor TPM Enable is not showing ,
Customer would be checking both GUI and IPMI ,
pls check why TPM Enable not showing  in sensor

**Comment by zhuifeng091** [comment]
how to configure the discrete sensor?
