### ISSUE TITLE
Add Aspeed Video Engine Driver

### ISSUE THREAD

**Issue by eddiejames** [openbmc/openbmc#3082]
Init HW video engine
Setup compression
Use Video4Linux2 for userspace interface

Under the "KVM over IP" epic, #2799

**Comment by edtanous** [comment]
Has any progress been made on this?  I would love to see/test an early WIP if you have one.

**Comment by amboar** [comment]
I haven't heard of any progress.

**Comment by eddiejames** [comment]
Still working on it; side-tracked with other work at the moment.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/45
