### ISSUE TITLE
How to login web ui when run fw use qemu

### ISSUE THREAD

**Issue by FrankHome** [openbmc/openbmc#3084]
Hi,
    I need help,
    I run openbmc fw in qemu ,and can use 'ssh -p 2222 root@localhost' to login console,
    Can I use http://127.0.0.1:2222 to login web ui, or, have any other way to open webui
thanks alot ~~

**Comment by geissonator** [comment]
Questions like these are better for the mailing list or IRC channel.

I start QEMU with the parameter "hostfwd=:127.0.0.1:2443-:443" to forward the https port and then you can go to "https://127.0.0.1:2443" to get web interface.
