### ISSUE TITLE
Generic approach for running all the post inst script after first boot

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#3086]
for example a BMC image that has additional user accounts (and therefore a bigger /etc/group file) is installed on the BMC, the /etc/group or /etc/passwd file would not be updated because is part of the persistent files, so the old /etc/group or /etc/passwd file would remain.

eg once we add the post-install section in the bb file where we can define the creation of user,groups and then bitbake creates the post install script.
We need to find a way to run this script after first boot.

I could have seen that avahi bb file is creating the following postinst script which needs to be packaged and needs to be run.

tmp/work/armv6-openbmc-linux-gnueabi/avahi/0.6.32-r0/sysroot-destdir/usr/bin/postinst-useradd-avahi

**Comment by anoo1** [comment]
Reference: https://gerrit.openbmc-project.xyz/#/c/9632/
