### ISSUE TITLE
GUI: Set Network Settings

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3089]
<cde:info> SW424563 </cde:info>
<cde:info> SW424558 </cde:info>
<cde:info> SW425219 </cde:info>

**Comment by gtmills** [comment]
In "Network Settings", when the user selects "Save settings".. The network settings should be set.

**Comment by gtmills** [comment]
This includes: 
-MAC Address
-Hostname
-Obtain an IP address
-automatically (use DHCP)
-Use the following IP address:
-IPv4 Setting
--IP Address
--Subnet Mask
--Gateway

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11020> Add "Add new DNS server" button
Resolves  #3089 GUI: Set Network Settings
