### ISSUE TITLE
Witherspoon needs over-current warn value changed

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3099]
<cde:info> SW424935 </cde:info>

**Comment by geissonator** [comment]
The over current values we program into the voltage controller for witherspoon need to be changed due to some testing observations.

From our power engineer:
```
-----change this----
# VDD A master OC warn to 384A
i2cset -y 4 0x70 0x4A 0x08C0 w
# VDD B master OC warn to 384A
i2cset -y 5 0x70 0x4A 0x08C0 w
-----to these -----
# VDD A master OC warn to 326A
i2cset -y 4 0x70 0x4A 0x08A3 w # A308
# VDD B master OC warn to 326A
i2cset -y 5 0x70 0x4A 0x08A3 w
```

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10167> Change over-current warning value on witherspoon
Resolves  #3099 Witherspoon needs over-current warn value changed for defect SW424766

**Comment by amboar** [comment]
What is SW424766?

**Comment by geissonator** [comment]
Got the fix up before I edited out the IBM'isms.  It's removed now.

**Comment by amboar** [comment]
So now there's less IBM-internal information, but there's also just less information generally :) A problem description would be nice (in the future, if it's possible to do so).

**Comment by geissonator** [comment]
code as merged
