### ISSUE TITLE
Optimize Nginx keepalive_timeout when user authenticated

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#3103]
There was a discussion in this review, at line 27 about the keepalive_timeout.  Once user authentication is in place, we'd like to look into changing this timeout once a user is authenticated. The idea is to give an authenticated user a longer keepalive_timeout.

https://gerrit.openbmc-project.xyz/#/c/6879/13..16/meta-phosphor/common/recipes-httpd/nginx/files/nginx.conf

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/91
