### ISSUE TITLE
IBM Witherspoon - mismatched GPU labels for temp vs power sensors

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3111]
<cde:info> SW425373 </cde:info>

**Comment by spinler** [comment]
On Witherspoon, the power sensors are called P0_GPU0, P0_GPU1...P1_GPU2, but the temp ones are just called GPU0...GPU5.   We're going to make them consistent by changing the labels on the power ones to just be GPU0 to GPU5.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10219> Witherspoon: Change hwmon GPU power labels
Resolves  #3111 IBM Witherspoon - mismatched GPU labels for temp vs power sensors
