### ISSUE TITLE
GUI for fan doesn't turn Red/Yellow when fan is unplugged. Lower and Upper Critical and warning values not defined for fan

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3114]
<cde:info> SW424114 </cde:info>

**Comment by spinler** [comment]
IBM Witherspoon needs fan sensor thresholds defined.  Before that, we need to figure out how to not display the fan 1 temp sensors on the water cooled version of the system so we don't always show that unnecessary fan hitting those thresholds.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10322> wspoon: Add critical thresholds for fan speeds
Resolves  #3114 GUI for fan doesn't turn Red/Yellow when fan is unplugged. Lower and Upper Critical and warning values not defined for fan

**Comment by edtanous** [comment]
@spinler I think this is something that entity-manager intended to solve by enabling or disabling features based on component detection.  In this case, your water cooled chassis would be a "component" and would have different thresholds and fan interfaces defined.  If you're interested in trying to see how difficult  making the switch would be for witherspoon, both @feistjj and myself are on IRC and could walk you through it.  It should just be a matter of building config files for witherspoon baseboard, water cooled chassis, and air cooled chassis. I'd be very interested to see if we can use the same solution here.
