### ISSUE TITLE
Firmware level not documented in error logs

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3133]
<cde:info> SW419653 </cde:info>

**Comment by amboar** [comment]
@spinler have you asked on the mailing list?

**Comment by spinler** [comment]
Changed direction a bit and now will put this into the phosphor-logging code instead, as it seems like it could be useful for anyone who uses error logs.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10395> Add the BMC code version to error logs
Resolves  #3133 Firmware level not documented in error logs
