### ISSUE TITLE
Witherspoon : IPMI : Supported CipherSuites in DCMI compliance is failing

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3143]
<cde:info> SW426666 </cde:info>

**Comment by tomjoseph83** [comment]
The cipher_list.json is not packaged into the image, so cipher suites list command is failing.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10326> Add the default cipher list for all platforms
Resolves  #3143 Witherspoon : IPMI : Supported CipherSuites in DCMI compliance is failing
