### ISSUE TITLE
GUI: Should be able to activate a failed image

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3144]
![failed](https://user-images.githubusercontent.com/5455127/39445808-e3055c4e-4c81-11e8-9e24-520bb5f37239.PNG)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10599> Allow a "Failed" image to be "Activated"
Resolves  #3144 GUI: Should be able to activate a failed image
