### ISSUE TITLE
Phosphor-snmp: Make the community and the SNMP version configurable

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#3145]
While sending the trap presently community and the snmp version is hardcoded to community = public and the version is SNMPv2.
With this defect we need to make it configurable.

**Comment by nest1ing** [comment]
We are talking about the receivers of snmp traps.
Each of this receivers may have different requirements for snmp version and community name or user name for SNMPv3.
I believe that this should be configurable for each receivers instance.
