### ISSUE TITLE
GUI: "copy" in the event log should copy the error log name.

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3146]
"copy" in the event log copies only the additional information.. It should copy the error log name as well.

emilyshaffer
16:23
Gunnar M: seems like if you're going to paste it somewhere you're likely to be retyping the log name anyway if it's not included in the clipboard.

![copy_event_log](https://user-images.githubusercontent.com/5455127/39481390-ec04b010-4d30-11e8-9d00-ace6b9eadf77.PNG)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11679> Copy to clipboard button to include title
Resolves  #3146 GUI: "copy" in the event log should copy the error log name.
