### ISSUE TITLE
"HOST" on login screen should be renamed

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3147]
![host_login_page](https://user-images.githubusercontent.com/5455127/39492804-680b5946-4d56-11e8-9f44-ff25e8f54958.PNG)
Should be "BMC HOST" or "BMC HOST/IP ADDRESS".. Need to specify this is the BMC host.

**Comment by gtmills** [comment]
After talking with Karl, going with "BMC HOSTNAME or BMC IP ADDRESS"

**Comment by gtmills** [comment]
We got feedback that we needed to specify BMC.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10397> Rename BMC Host/IP field on login
Closes  #3147 "HOST" on login screen should be renamed
