### ISSUE TITLE
GUI: BMC information: Should have IP Addresses

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3148]
![overview_page_ip_address](https://user-images.githubusercontent.com/5455127/39495796-791350ee-4d61-11e8-8bdb-beebf87732ea.PNG)
Instead of BMC HOST/IP ADDRESS, display the IP address(es) of the system.
This label should be changed to "IP ADDRESSES" with the IP addresses of the BMC underneath. No reason to have BMC in the name since this information is already under the BMC information section.

**Comment by gtmills** [comment]
BMC HOST/IP ADDRESS is not needed since it is already displayed in the header at the top.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10410> Display ip addresses in 'BMC information' section
Resolves  #3148 GUI: BMC information: Should have IP Addresses
