### ISSUE TITLE
Should display a red "error" symbol when Server Power is in an "Error" state

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3149]
Instead of displaying a yellow warning symbol display a red "error" symbol.
![error_server_power](https://user-images.githubusercontent.com/5455127/39495959-31c5ccc0-4d62-11e8-8179-3008d7687a19.PNG)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10400> Display red 'error' icon for Error state
Resolves  #3149 Should display a red "error" symbol when Server Power is in an "Error" state
