### ISSUE TITLE
GUI: Need to support IPV6

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3150]
When IPV6 is officially supported by OpenBMC, need to support IPV6 on the GUI. 
Need changes in the Network Settings, https://github.com/openbmc/phosphor-webui/blob/master/app/configuration/controllers/network-controller.html#L38. 
Also will probably need changes on the overview page.

**Comment by edtanous** [comment]
+1

**Comment by gtmills** [comment]
https://github.com/openbmc/phosphor-webui/issues/62 tracks this. Closing.
