### ISSUE TITLE
A promise failing should not stop the rest of the promises when loading the pages

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3151]
This came up in a code review. 

"The all function returns a promise for an array of values. When this promise is fulfilled, the array contains the fulfillment values of the original promises, in the same order as those promises. If one of the given promises is rejected, the returned promise is immediately rejected, not waiting for the rest of the batch."  

q.all needs to be changed to something else when loading the pages, 
https://github.com/openbmc/phosphor-webui/blob/master/app/overview/controllers/system-overview-controller.js#L47

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10475> Do not abort when one of multiple promises fails
Resolves  #3151 A promise failing should not stop the rest of the promises when loading the pages

**Comment by edtanous** [comment]
This doesn't seem like a bug, and we should code in such a way that we don't unnecessarily fail promises.  I get the feeling I'm missing some context here.
