### ISSUE TITLE
Witherspoon: Sensor GPU Power is reported incorrectly on GUI

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3152]
<cde:info> SW427368 </cde:info>

**Comment by spinler** [comment]
The Witherspoon OCC hwmon config file needs some fixups to get all of the power readings named right.  Also we'll need to add the same sort of indirect lookup we were doing on the OCC temps with the _label file to the _function_id file.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10459> wspoon: Find OCC power labels using function IDs
Resolves  #3152 Witherspoon: Sensor GPU Power is reported incorrectly on GUI
