### ISSUE TITLE
Implement Host console sub-options

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#3153]
In the webui, implement the "export in new tab" feature, which is supposed to launch the host console in a new browser tab. Also implement the "export" feature to be able to download console data.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11893> Serial LAN console export
Resolves  #3153 Implement Host console sub-options

**Comment by BeccaBroek** [comment]
"new tab" function is resolved by https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/12345/
"export" function is still under discussion, this ticket is not resolved until addressed

**Comment by gtmills** [comment]
This issue is for the "new tab" button only.
