### ISSUE TITLE
System shut down after a solid UE Injection to OCC

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3155]
<cde:info> SW425502 </cde:info>

**Comment by eddiejames** [comment]
An error in the OCC cache results in a valid OCC response when polled from the BMC, but corrupted response data.

According to the OCC specification, the BMC OCC driver needs to validate the checksum of the response and return an error upon mismatch.

**Comment by gtmills** [comment]
@eddiejames Can we close?

**Comment by gtmills** [comment]
The internal bug was closed, closing.
