### ISSUE TITLE
Witherspoon: SBE failed to recover after SBE went bellyup at runtime

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3156]
<cde:info> SW427128 </cde:info>

**Comment by eddiejames** [comment]
If the SBE goes down, the BMC SBEFIFO driver has no recovery mechanism, resulting in continued failures on the BMC even if the SBE is recovered.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10482> Add Bus class to reset OCC bus driver
Resolves  #3156 Witherspoon: SBE failed to recover after SBE went bellyup at runtime
