### ISSUE TITLE
Need a REST API to get the last BMC reboot time

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3159]
Using this API, in the GUI we could show last Reboot time
![image](https://user-images.githubusercontent.com/5455127/39600005-23e20560-4ee3-11e8-97c0-f5be00eb71e4.png)

**Comment by gkeishin** [comment]
Looking forward to the REST API for it.

**Comment by spinler** [comment]
I will take this one and add a d-bus interface for the last reboot time (current time minus uptime).

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11473> BMC state manager support for LastRebootTime
Resolves  #3159 Need a REST API to get the last BMC reboot time
