### ISSUE TITLE
On the server overview page only show the 5 newest high priority event logs

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3160]
![event_logs](https://user-images.githubusercontent.com/5455127/39641941-a307dd9e-4f95-11e8-890e-de13da2da0aa.PNG)
Should only show the newest 5 high priority events on the server overview page. 
Should still display the number of high priority event "High priority events (8)".
On the event log page, the user should still be available to see all of them.

**Comment by jaypadath** [comment]
Tested the changes and verified the number of high priority events as 4, 5, 6 and 10. Change is in review.
