### ISSUE TITLE
Event logs should be newest events on top on both server overview and event log page 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3161]
![event_logs](https://user-images.githubusercontent.com/5455127/39642162-58ad253c-4f96-11e8-9541-61cd88c94870.PNG)

**Comment by gtmills** [comment]
Just need to reverse the order.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10591> Display event logs in ascending order
Resolves  #3161 Event logs should be newest events on top on both server overview and event log page
