### ISSUE TITLE
GUI: On the 'BMC network settings' page, check if the network settings have changed before saving new settings

### ISSUE THREAD

**Issue by camvanng** [openbmc/openbmc#3165]
Reference https://gerrit.openbmc-project.xyz/#/c/10108/5/app/configuration/controllers/network-controller.js@37

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10942> Set DHCP on "Save settings"
Resolves  #3165 GUI: On the 'BMC network settings' page, check if the network settings have changed before saving new settings
