### ISSUE TITLE
Format and mount eeprom

### ISSUE THREAD

**Issue by ThaiThu** [openbmc/openbmc#3166]
Hi all,

Is it possible to format eeprom buffer to jffs2 file system on BMC ?
And after that, we can access it like a normal directory to store or retrieve data from it ?

By the way, is there any command on bmc to implement jffs2 format ?

Thanks a lot !!!

**Comment by amboar** [comment]
You can mount an erased flash device as a JFFS2 partition out of the box - I think that should be enough? Busybox does have a `-j` option for `flash_eraseall` that is JFFS2 specific, so that might help out. Also (obviously) make sure your kernel is compiled with JFFS2 support.

**Comment by gtmills** [comment]
@ThaiThu Need more information or can this be closed? Thanks!
