### ISSUE TITLE
 occ-control core dump - OCC.Device.Error.OpenFailure: Opening OCC device failed on wsbmc016 with 920.1808.20180504a

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3168]
<cde:info> SW427850 </cde:info>

**Comment by eddiejames** [comment]
Rebooting the BMC while the host is up causes a problem with the OCC, temporarily. This means that when the OCC control app starts up on the BMC, it fails to communicate with the OCC, resulting in the app crashing.

**Comment by eddiejames** [comment]
The problem is that the SCOM driver is performing a PIB reset during probe(), which runs when FSI is scanned during BMC boot. This reset can break the OCC. Fix is to remove that PIB reset from SCOM probe.

**Comment by gtmills** [comment]
@eddiejames Can you update the title? It has an IBM machine and driver listed.

**Comment by eddiejames** [comment]
I don't seem to have permissions. This can be closed anyway, fixed
