### ISSUE TITLE
Create an ast2400 evaluation board machine

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#317]
It would be nice to have this like we do for the ast2500.

**Comment by williamspatrick** [comment]
Minor Yocto work involved here.  Mostly kernel / u-boot work.

**Comment by zahrens** [comment]
@jk-ozlabs Hi Jeremy, Patrick had this one in the backlog.  Not sure if this is done, or still needed?  Thank you Zenta

**Comment by amboar** [comment]
Does anyone have an AST2400 EVB to test it on?

**Comment by gtmills** [comment]
@bradbishop Do we still need this or can this be closed?

**Comment by amboar** [comment]
I don't think anyone cares about this. Reopen it if/when they do.
