### ISSUE TITLE
 Aspeed AST2520 support

### ISSUE THREAD

**Issue by lakesh-sharma** [openbmc/openbmc#3172]
Is Aspeed AST2520 supported by openbmc ?
I don't see it in  folder meta-openbmc-machines/meta-arm

**Comment by amboar** [comment]
The AST2520 is an AST2500 without the graphics IP. As such you can make use of the AST2500 layer.

For future reference, this kind of question is best asked on the mailing list, as it isn't a big report or feature request.

Regardless, I hope this helps.
