### ISSUE TITLE
Witherspoon: BMC is reading wrong location for Boxelder card serial number

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3174]
<cde:info> SW428581 </cde:info>

**Comment by spinler** [comment]
The code was getting it from the SN keyword in the VINI record instead of the VS keyword in the OPFR record.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10557> openpower: Read the BMC VPD from the OPFR record
Resolves  #3174 Witherspoon: BMC is reading wrong location for Boxelder card serial number
