### ISSUE TITLE
OpenBMC:Witherspoon- Multiple applications core after enabling DHCP and reboot

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3175]
<cde:info> SW428333 </cde:info>

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10556> Phosphor-networkd: Add dependency on inventory service
Resolves  #3175 OpenBMC:Witherspoon- Multiple applications core after enabling DHCP and reboot

**Comment by rfrandse** [comment]
The CQ defect was closed as unreproducible.
