### ISSUE TITLE
obmc-ubi-fs feature does not include ubi utils

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#3177]
OpenBMC has ubi related features, one is `obmc-ubi-fs` for OpenBMC's UBI FS, the other is `openpower-ubi-fs` for PNOR's UBI FS.

If a build only enables `obmc-ubi-fs` feature, the built image does not include ubi utils, e.g. `ubimkvol`, `ubinfo`, etc.
This results in failure to do code update based on UBI-FS way.

**Comment by mine260309** [comment]
The root cause is that there is no `RDEPENDS` to `mtd-utils-ubifs` for `obmc-ubi-fs`.
And it can be fixed by adding this in `phosphor-software-manager.bb`

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10577> Add RDEPENDS to mtd-utils-ubifs in phosphor-software-manager
Resolves  #3177 obmc-ubi-fs feature does not include ubi utils
