### ISSUE TITLE
Witherspoon: GPU power values are inaccurate - remove them

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3183]
<cde:info> SW429251 </cde:info>

**Comment by spinler** [comment]
The power values we get from the OCC are instantaneous readings, and as such can report some whacky values.  So we're just going to remove the sensors from the GUI, and users can get them on the host with the nvidia-smi tool.

In the future we may decide to do some averaging to give better values and add them back in.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10628> wspoon: Remove GPU power sensors
Resolves  #3183 Witherspoon: GPU power values are inaccurate - remove them
