### ISSUE TITLE
Replace hard-coded service name with call to ObjectMapper

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#319]
Throughout the openbmc code, the dbus service name is hardcoded. The ObjectMapper provides a way to find out the service name: https://github.com/openbmc/docs/blob/master/dbus-interfaces.md

**Comment by bradbishop** [comment]
It might make sense to rework the mapper API:

https://github.com/openbmc/skeleton/pull/96#discussion_r67190512

**Comment by williamspatrick** [comment]
Need to make sure epic #327 includes a wrapper for object mapper calls.  Part of proxy object work.
