### ISSUE TITLE
 FVT IPMI lan print shows 2 channels when it got only one eth0 interface

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3191]
<cde:info> SW427495 </cde:info>

**Comment by dkodihal** [comment]
`ipmitool -I lanplus -C 3 -P 0penBmc -H <witherspoon> lan print 1` alone should show output on a Witherspoon, but `lan print 2` works as well.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10861> Add witherspoon specific channel.yaml
Resolves  #3191  FVT IPMI lan print shows 2 channels when it got only one eth0 interface
