### ISSUE TITLE
Web UI sometimes gets stuck reading 200 event logs

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3199]
<cde:info> SW429253 </cde:info>

**Comment by gtmills** [comment]
The logging enumerate takes almost 20 seconds with 200 errors. Might need to update the logging timeout.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10866> Increase the event log enumerate timeout
Resolves  #3199 Web UI sometimes gets stuck reading 200 event logs
