### ISSUE TITLE
OpenBMC:Witherspoon- mboxd.service is crashing after factory reset

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3210]
<cde:info> SW428410 </cde:info>

**Comment by amboar** [comment]
how about we just tell mboxd about it with `mboxctl --suspend` and `mboxctl --resume modified` in the appropriate places?

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11412> reset: Call Suspend / Resume mbox
Closes  #3210 OpenBMC:Witherspoon- mboxd.service is crashing after factory reset
