### ISSUE TITLE
BMC Reboot GUI option throws Unexpected Error

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3211]
<cde:info> SW430336 </cde:info>

**Comment by gtmills** [comment]
From the GUI, Server Control -> BMC Reboot, then select the reboot BMC option.

Immediately get the Unexpected Error message shown below

![rebootbmc 2](https://user-images.githubusercontent.com/5455127/40681440-b655ff4e-634e-11e8-86c0-33be37fb1842.png)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11025> Avoid unexpected error when BMC reboots
Resolves  #3211 BMC Reboot GUI option throws Unexpected Error
