### ISSUE TITLE
BMC cannot change user password using RESTFUL API

### ISSUE THREAD

**Issue by ThaiThu** [openbmc/openbmc#3215]
Hi all,

we want to test restfull api to change "root" user password.
I already logined into the bmc the root account.

And after that, I used below curl command to change the password to ABC:

curl -c cjar -k -X POST -H "Content-Type: application/json" -d '{"data": ABC }'  ttps://${bmc}/xyz/openbmc_project/user/root/action/SetPassword

But the result is:

{
  "data": {
    "description": "Login required"
  },
  "message": "401 Unauthorized",
  "status": "error"
}

Could anyone give me some advises please ?

Thank alot !!!

**Comment by gtmills** [comment]
@ThaiThu Still a problem? Can you add the journal? What system?

**Comment by gtmills** [comment]
Closing. Need more information. Please reopen if still an issue. Thanks!
