### ISSUE TITLE
Witherspoon : IPMI : GPU fru info not available in IPMI fru print

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3216]
<cde:info> SW425292 </cde:info>

**Comment by ngorugan** [comment]
This is the dup of #3039. Fix for #3039 is in the master.

Below given commits will this issue:https://gerrit.openbmc-project.xyz/#/c/9872 and  https://gerrit.openbmc-project.xyz/#/c/9969

**Comment by gtmills** [comment]
The internal bug was closed, closing.
