### ISSUE TITLE
Write unit tests for the phosphor-logging server

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#3217]
Some of the functions I can think of :

- Retrieving metadata from journal
- Creation of error D-Bus objects
- Forming associations to inventory (callouts)
- Error wrapping
- etc

**Comment by geissonator** [comment]
Good stuff, please reference https://github.com/openbmc/openbmc/wiki/files/2018-05-26_automated-testing.pdf for good unit test practices.
