### ISSUE TITLE
PreTag: [System - barreleye Build - 20160610155319 ]  Set PowerCap

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#322]
One of the test case is looking for SetValue object... This object is not found as per the log ..

Can someone look into it and let us know.. why this is not available.. Thanks

For Reference log:

Start / End / Elapsed: 	20160613 12:31:25.747 / 20160613 12:31:25.747 / 00:00:00.000
12:31:25.747 	INFO 	${msg} = URI:https://9.3.23.30/org/openbmc/sensors/host/PowerCap/action/setValue, method:Post, args:{u'data': {u'data': [0]}, u'headers': {u'Content-Type': u'application/json'}} 	
00:00:00.001 KEYWORD rest_client . Logging ${msg}, console=TRUE

12:31:26.869 	INFO 	${resp} = <Response [404]> 	
12:31:26.870 	INFO 	${resp} = <Response [404]>

Documentation: 	

Fails if objects are unequal after converting them to strings.
Start / End / Elapsed: 	20160613 12:31:26.870 / 20160613 12:31:26.872 / 00:00:00.002
12:31:26.871 	INFO 	Argument types are:
<type 'int'>
<type 'unicode'> 	
12:31:26.872 	FAIL 	404 != 200

**Comment by williamspatrick** [comment]
Issue moved to [openbmc/openbmc-test-automation #26](https://github.com/openbmc/openbmc-test-automation/issues/26) via [**ZenHub**](https://www.zenhub.com/)
