### ISSUE TITLE
Redfish : Investigate bmcweb

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#3220]
Investigate https://github.com/openbmc/bmcweb. Some of the tasks :

- Try out the webserver via a redfish client.
- Check if redfish backend can be plugged out and plugged to another webserver.
- Investigate how redfish resources are mapped to D-Bus.

Results can be emails to the community, etc.

**Comment by geissonator** [comment]
Some initial code to get bmcweb into witherspoon - https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/11509/

**Comment by jinneal** [comment]
Could it be in use for AST2500? I try to install the redfish into the AST2500 and access it by https

**Comment by geissonator** [comment]
We now have bmcweb in the IBM layer and it has the basic redfish functions working. This story should track more specific work, like maybe helping with https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/12018/ and other required features for Redfish.

**Comment by gtmills** [comment]
Closing. 
bmcweb is the default webserver.  It includes support for redfish. 
more information at https://github.com/openbmc/bmcweb
