### ISSUE TITLE
Set Power Cap from GUI. 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3221]
Currently, the user can only view the power cap not set/enable it. This story is to allow the user to set/enable it.
![power_cap](https://user-images.githubusercontent.com/5455127/40801563-d200d990-64d8-11e8-850e-51ab3c880262.PNG)

**Comment by gtmills** [comment]
After talking with Karl, new page under "Server control". Named like "Power consumption".

**Comment by gtmills** [comment]
Start of the page 
![manage_power_usage_menu](https://user-images.githubusercontent.com/5455127/41736628-b473812c-7552-11e8-9016-960f9a552ce6.PNG)

![manage_power_usage](https://user-images.githubusercontent.com/5455127/41736619-afb0309a-7552-11e8-82ad-56630c378ea9.PNG)

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11291> Set the power cap
Resolves  #3221 Set Power Cap from GUI.

**Comment by gtmills** [comment]
![manage_power_settings](https://user-images.githubusercontent.com/5455127/42397757-be194e38-812c-11e8-9f8e-b5faf189149e.PNG)

**Comment by gtmills** [comment]
Look at having a link from the overview page.
