### ISSUE TITLE
GUI: Add functionality to manage BMC and Host time

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3222]
https://github.com/openbmc/phosphor-time-manager

Will need things like TimeSyncMethod (NTP vs Manual), TimeOwner (BMC and/or Host), setting the time, and timezone.

**Comment by gtmills** [comment]
Need to work with the design team to come up a new page to do this.

**Comment by alissaylee** [comment]
![manual_default_same](https://user-images.githubusercontent.com/42816433/44811370-22164c00-ab9a-11e8-802a-fddb74dbb183.jpg)
![manual_different](https://user-images.githubusercontent.com/42816433/44811371-22aee280-ab9a-11e8-9fdd-e7504cfbcf36.jpg)

- First prompt: User chooses to set date and time a) manually or b) via the NTP server.
- Second prompt: User chooses to set BMC and server's date and time as the same or different.
- Date and Time fields are selectable (and utilize default browser settings). 
- Time zone will be read-only.

**Comment by alissaylee** [comment]
![automatic](https://user-images.githubusercontent.com/42816433/44811645-c00a1680-ab9a-11e8-8f5b-042786860109.jpg)
![automatic_ntp_invalid_format](https://user-images.githubusercontent.com/42816433/44811868-51798880-ab9b-11e8-8b42-dd2791eebf40.jpg)
![automatic_leave_before_saving](https://user-images.githubusercontent.com/42816433/44812176-293e5980-ab9c-11e8-8bc6-642770b09b04.jpg)


**Setting date and time via the NTP server**
- Date, Time, and Timezone are read-only. 
- Initial setup: Text field to set up primary NTP server option is made available.
- Ability to add more NTP server(s).
- Remove NTP server(s) starting with the 2nd NTP server.
- Can "Test" connection before "Saving settings".
- States successful connection of an NTP server with a success icon after user selects "Test" or "Save settings".
- States "Invalid format" text and warning icon for an invalid NTP server entry after user is done typing.
- States "Does not exist or connection problem" text and warning icon for a 'bad' NTP server after selecting "Test" or "Save settings".
- Alerts when user attempts to leave page without saving settings.

**Comment by alissaylee** [comment]
To view additional instances for Date and Time Settings, please go here: https://ibm.ent.box.com/folder/52973968475

**Comment by alissaylee** [comment]
Public InVision link: https://ibm.invisionapp.com/share/YSNTBXAJGUC#/318326214_Manual_Default_Same
