### ISSUE TITLE
Move to python3 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3224]
https://github.com/openbmc/openbmc/issues/2920 added support for python3

```
 geissonator commented on Mar 4

I think @bradbishop ended up finding that we don't in fact have to update to python 3 within our image. But at some point we'll want to, in order to take advantage of some of the new features in python 3. But not required for yocto 2.4.
```

After moving to python3 should remove python2 
https://github.com/openbmc/openbmc/issues/2994

**Comment by gtmills** [comment]
Currently we have 
```
root@Witherspoon:~# python -V
Python 2.7.13

```

**Comment by gtmills** [comment]
We can close https://github.com/openbmc/openbmc/issues/1556 when we move to python 3

**Comment by shenki** [comment]
Good idea: https://github.com/openbmc/meta-phosphor/issues/13#issuecomment-141889784 :)

**Comment by gtmills** [comment]
We removed Python from the image. Closing.
