### ISSUE TITLE
Witherspoon: reinserting a fan does not turn off the fault led sometimes

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#3231]
<cde:info> SW429703 </cde:info>

**Comment by spinler** [comment]
On Witherspoon we have a window where if you pull out a previously unfaulted fan for long enough for it to be marked as missing but not long enough for it to be marked as faulted from an RPM point of view, then when you put it back on the associated LEDs won't turn off.

A fix to the rules we use for when to create and resolve error logs should take care of it.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11007> wspoon: Improve fan error resolving rules
Resolves  #3231 Witherspoon: reinserting a fan does not turn off the fault led sometimes
