### ISSUE TITLE
GUI: Not sorting event logs correctly

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3233]
![event_logs_sort](https://user-images.githubusercontent.com/5455127/40990273-e89a5498-68b5-11e8-9570-c6dd253407e9.PNG)

8 should not be before 79. We only show 5 event logs on the overview page, the 5 should be the most recent, which they are not. https://gerrit.openbmc-project.xyz/#/c/10862/.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11008> Fix event log sorting
Resolves  #3233 GUI: Not sorting event logs correctly
