### ISSUE TITLE
Unable to open the core in the case of SIGABRT inside the process.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#3242]
**If I put the abort() call inside the process** then it generates the core which is not being opened up in our SDK env.
However if the core generated for SIGSEGV,I am able to open it.

**Surprisingly if I give the sigabort signal from outside the process (kill -6 pid) then it generates the core which I am able to open it.**

Here is the test program which generates the core but I was unable to open in the SDK env.

#include <stdlib.h>
int testfunction()
{
    int a = 7;
    abort(); // send the SIGABRT and generate the core.
}

int main()
{
    testfunction();
    return 0;
}

*However If I modify the above program for SEGV then I am able to open the core.*

#include <stdlib.h>
int testfunction()
{
    int a = 7;
    char *p = NULL;
    *p = 'c' ; //  SIGSEGV 
}
int main()
{
    testfunction();
    return 0;
}
I verified the same with the openbmc application,I was getting the same behavior.
@bradbishop @anoo1 @geissonator ^^^

**Comment by ojayanth** [comment]
@ratagupt are you followed the same steps mentioned  in https://github.com/openbmc/docs/blob/master/cheatsheet.md ?
