### ISSUE TITLE
GIU: Remove 2nd scroll bar from Serial over LAN console 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3243]
![sol](https://user-images.githubusercontent.com/5455127/41173162-88edb482-6b1b-11e8-9809-249803ceeb8a.PNG)
2 scroll bars on the right hand side, need to remove one.

**Comment by jaypadath** [comment]
Made the changes and sent code for review...

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11099> Remove extra scroll bar from the SoL console menu
Resolves  #3243 GIU: Remove 2nd scroll bar from Serial over LAN console
