### ISSUE TITLE
Flashing Linux image using u-boot TFTP failed.

### ISSUE THREAD

**Issue by akashgj** [openbmc/openbmc#3244]
I build the system using the steps given, target machine as Zaius. I flashed u-boot into the board containing aspeed ast 2500 and got an 'runBMC' command prompt. But flashing Linux image using u-boot TFTP failed. Please someone share how to burn Linux image into the flash memory.

**Comment by gtmills** [comment]
@anoo1 Could you help here?

**Comment by anoo1** [comment]
hi @akashgj , could you share how the 'runBMC' prompt looks like, and what command(s) did you use to flash via tftp. Also which file you used for the upload.
