### ISSUE TITLE
phosphor-software-manager: Check if alt rwfs exists before mounting

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#3245]
The phosphor-software-manager-sync distro feature tries to mount the alt rwfs volume, but if it doesn't exist, the journal will log the following errors:
```
May 09 06:56:38 witherspoon systemd[1]: Starting Reload mboxd during power on...
May 09 06:56:38 witherspoon kernel: UBIFS error (pid: 1220): cannot open "ubi4:rwfs", error -19
May 09 06:56:38 witherspoon kernel: ucd9000 11-0064: Device ID UCD90160|2.3.4.0000|110603
May 09 06:56:38 witherspoon kernel[1035]: [  125.398030] UBIFS error (pid: 1220): cannot open "ubi4:rwfs", error -19
```
Need to check the volume exists before attempting to mount and access.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11309> obmc-flash-bmc: Check alt rwfs volume exists
Resolves  #3245 phosphor-software-manager: Check if alt rwfs exists before mounting
