### ISSUE TITLE
Host poweron may get blocked if reboot was attempted on a powered off host

### ISSUE THREAD

**Issue by AlexanderAmelkin** [openbmc/openbmc#3249]
In some scenarios an attempt may be made to reboot a powered off host.  The possible reasons for the attempt are an `obmcutil` call, pushing the 'reset' button, an IPMI request, et al. Rebooting is done by calling `obmc-host-reboot@0.target`. When the target is called, it tries to shut off the host by calling `obmc-host-shutdown@0.target`, and then turn it back on by calling `phosphor-reboot-host@0.service`. 

The `xyz.openbmc_project.Ipmi.Internal.SoftPowerOff.service` powers off the host by simply preparing  an IPMI transition request that is queued and presented to OPAL upon request. If the host was off when the request was queued, the host will get it upon execution of `phosphor-reboot-host@0.service`, and as a result will not start. After 3 failed attempts to start the host, the BMC will set it to Quiesced state and it will be impossible to start the host anymore.

That happens in most cases, but not for IPMI-initiated reboot. When a powered off host is rebooted using IPMI 'chassis power cycle' command, the host powers on as expected. When that command is sent, `netipmid` daemon creates `/run/openbmc/host@0-request` file, then `xyz.openbmc_project.Ipmi.Internal.SoftPowerOff.service` sees that file and doesn't run, and the host is then able to start. In all other scenarios that file is not created and the host can't start.

It must be noted that some services use `/run/openbmc/host@0-on` and `/run/openbmc/chassis@0-on` to determine the state of the host, but `/run/openbmc/host@0-on` is only created during BMC boot if the host was on at the time. Maybe openbmc should be using those files when calling the host shutdown service?

**Comment by mine260309** [comment]
Reproduced on Romulus.

@geissonator Could you please help to look into the issue?
I remember that I talked with you about the usage of state files in `/run/openbmc`, as @AlexanderAmelkin suggests, it probably should uses these state files to determine the host state, not only for discover host state but for maintain host state?

@gkeishin This case is better to be added into test cases as well. It really missed to catch the issue.
