### ISSUE TITLE
GUI : No error message while setting invalid default gateway address and MAC address

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3261]
If you set a non-admin mac address, the GUI does not display an error. It should. This is caused by the backend not returning an error.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11181> Throw InvalidArgument on bad Default Gateway
Resolves  #3261 GUI : No error message while setting invalid default gateway address and MAC address
