### ISSUE TITLE
GUI: SOL window does not scroll correctly when it is full

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#3262]
The SOL window in WebUI looks great!
But it has an issue that the content does not scroll automatically, instead, it shows only the last line but not clear the other lines. See below screenshot:

![issue_sol_in_webui](https://user-images.githubusercontent.com/717009/41640794-8f0b411c-7495-11e8-906d-b0a1efd40868.gif)

**Comment by sivassrr** [comment]
I believe this is a known issue. When the code checking for SOL happened it was mentioned in the commit message, I guess. @dkodihal was working on it.

**Comment by mine260309** [comment]
Good to know it's known issue.
I just hit this, searched openbmc issues and did not find one. So submitted a new issue.

**Comment by BeccaBroek** [comment]
@mine260309 
I am trying to recreate this, but it seems to be resolved from what I can tell. Tried it in chrome, firefox, and safari. Wondering if it was resolved with https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/11099/ . Are you still seeing this issue?

**Comment by mine260309** [comment]
@BeccaBroek Still see the issue on v2.3-181-g7639cd5.

My environment:
Mozilla Firefox 61.0.1 on Ubuntu 14.04.5 LTS

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/12602> Switch to xterm
Resolves  #3262 GUI: SOL window does not scroll correctly when it is full
