### ISSUE TITLE
Unable to use ipmitool in OpenBMC Linux

### ISSUE THREAD

**Issue by akashgj** [openbmc/openbmc#3267]
I added ipmitool into the root file system of OpenBMC Linux and booted it. When I tried to execute ipmi tool(inside OpenBMC Linux), it is showing the following error.

root@zaius:# ipmitool sdr elist full
**Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0. No such file or directory.**

Please someone help to resolve this.

**Comment by gx0128** [comment]
Did you download the ipmitool from the website https://github.com/openbmc/ipmitool?
