### ISSUE TITLE
IKVM: Add Aspeed USB gadget driver

### ISSUE THREAD

**Issue by eddiejames** [openbmc/openbmc#3269]
This is a driver to control the AST2XXX as a slave device to the host processor. This is necessary in order to drive input to the host for IKVM.

This will also be used for virtual media devices.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/46

**Comment by eddiejames** [comment]
@wengerxin https://github.com/openbmc/linux/tree/dev-4.18/drivers/usb/gadget/udc/aspeed-vhub
