### ISSUE TITLE
CI: Run CI tests on all supported architectures

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#3277]
Per a discussion in IRC with @wak-google it was noted that certain CI tests were passing on x86 but failing on ppc64le machines.  Right now, the machine type chosen by https://openpower.xyz/job/openbmc-repository-ci/ is based on availability and only run on that one machine.

We'd like to modify the job to ensure both machine types (and any future one's (ARM?)) are always tested with every CI commit.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/76
