### ISSUE TITLE
No event log when temperature over threshold

### ISSUE THREAD

**Issue by LindarLiu0724** [openbmc/openbmc#3278]
Hi all,
I have added a temperature sensor in hwmon, and from the REST interface I notice 
"""WarningAlarmLow = 1"""
but no any event log found. I didn't do any porting for SEL part.

Could somebody give suggestion how to debug and how to make the sel function work?
thanks.

**Comment by gtmills** [comment]
Hi @LindarLiu0724, I believe we don't create event logs when sensors are in a warning or critical state. On Witherspoon, we create an event log if 3 or more cores are overtemp using D-Bus monitoring. 
https://github.com/openbmc/openbmc/blob/master/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/fans/witherspoon-thermal-policy/thermal-policy.yaml#L170
 @spinler could help answer this though. This is a good question for the mailing list, as it's not a bug or feature request. You can sign yourself up at for the list at https://lists.ozlabs.org/listinfo/openbmc

Thanks, 
Gunnar

**Comment by gtmills** [comment]
Similiar question on https://github.com/openbmc/openbmc/issues/1828. Maybe @spinler you can close both after answering. Thanks!

**Comment by spinler** [comment]
@tomjoseph83 Are there any IPMI stories planned to create SEL events when the various thresholds are crossed?

**Comment by tomjoseph83** [comment]
@spinler We do not have any stories open to track mapping the thresholds to SEL entries.
