### ISSUE TITLE
Inband ipmitool command is failing for dcmi power get_limit

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#3290]
Out-of-band ipmitool dcmi command worked fine.
ipmitool -I lanplus -H x.x.x.x -U admin -P 0penBmc dcmi power get_limit

    Current Limit State: No Active Power Limit
    Exception actions:   Hard Power Off & Log Event to SEL
    Power Limit:         0 Watts
    Correction time:     0 milliseconds
    Sampling period:     0 seconds

Inband ipmitool dcmi command is failing.
ipmitool  dcmi power get_limit

A valid DCMI command was not returned! (80)

**Comment by mousumipaul** [comment]
For me out-of-band is also not working..
