### ISSUE TITLE
linux-aspeed uses incorrect defconfig with devtool

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#3294]
Before `linux-aspeed` change, the linux kernel recipe was `linux-obmc`, and it is OK to use devtool to modify and build linux kernel:
```
devtool modify linux-obmc
bitbake linux-obmc -c build  # Do the build
bitbake linux-obmc -c clean  # Clean the build
bitbake linux-obmc -c build  # Build it again
```

Now with `linux-aspeed` recipe, the above is broken if the recipe is cleaned and built again:
```
devtool modify linux-aspeed
bitbake linux-obmc -c build  # Do the build, OK
bitbake linux-obmc -c clean  # Clean the build, OK
bitbake linux-obmc -c build  # Not OK, the defconfig becomes default one
```
The expected `defconfig` should be the one in openbmc, however, the `defconfig` becomes default one.
From `log.do_configure`:
```
# using defaults found in /boot/config-4.4.0-127-generic
```

The built kernel will not work with OpenBMC.

**Comment by mine260309** [comment]
The `defconfig` is expected to be fetched by bitbake.

In `do_unpack` task, the files are defined in `SRC_URI` and fetched.
```
  1 def base_do_unpack(d):
  2     src_uri = (d.getVar('SRC_URI') or "").split()
  3     if len(src_uri) == 0:
  4         return
  5
  6     try:
  7         fetcher = bb.fetch2.Fetch(src_uri, d)
```

In previous `linux-obmc` case, the `defconfig` is copied from `oe-local-files` to the working dir:
```
NOTE: Unpacking /home/leiyu/work/openbmc/build/workspace/sources/linux-obmc/oe-local-files/defconfig to /home/leiyu/work/openbmc/build/tmp/work/romulus-openbmc-linux-gnueabi/linux-obmc/4.13.16+git999-r0/
```
Then in following tasks, the `defconfig` is used as normal.

In `linxu-aspeed` case, the `defconfig` is not in `oe-local-files`, but in `oe-local-files/ast2500/`, so the file is copied to `ast2500/` dir in working directory, effectively, it is missing in working directory.
That is why the linux build uses a default `defconfig`, since it is missing.

**Comment by mine260309** [comment]
https://gerrit.openbmc-project.xyz/#/c/11424/

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11424> linux-aspeed: Fix defconfig SRC_URI
Resolves:  #3294 linux-aspeed uses incorrect defconfig with devtool

**Comment by MichaelWang2017** [comment]
I modified linux-aspeed.inc by [https://gerrit.openbmc-project.xyz/11424](url)

Some warning message appears:
WARNING: SRC_URI is conditionally overridden in this recipe, thus several devtool-override-* branches have been created, one for each override that makes changes to SRC_URI. It is recomme
nded that you make changes to the devtool branch first, then checkout and rebase each devtool-override-* branch and update any unique patches there (duplicates on those branches will be i
gnored by devtool finish/update-recipe)
And this info comes from scripts/devtool

wangpeng@wangpeng-VIT-E2250:~/workspace/ali/openbmc/build/workspace/sources/linux-aspeed$ git branch
  dev
  dev-4.10
  dev-4.13
  dev-4.17
  dev-4.3
  dev-4.4
  dev-4.6
  dev-4.7
\* devtool
  devtool-no-overrides
  devtool-override-df-obmc-ubi-fs
  master

**Comment by mine260309** [comment]
Yup, I saw this message as well, but the warning message does not seems to break the function.

Btw, please use `markdown` format to make your message either like a quote

> This is a quote

or make it like a code

```
This is a code
```

**Comment by MichaelWang2017** [comment]
Okay, I got it, thank you.
