### ISSUE TITLE
phosphor-bmc-code-mgmt: Improve Subscribe method

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#3298]
The code update logic relies on systemd service files to write the new image to flash, and since starting a service is an async operation, it subscribes to systemd signals to determine when the services complete.

Currently the Subscribe method does not return any value, so the caller is unaware if it failed to subscribe.
Also there's no tracking on when clients have Subscribed / Unsubscribed to signals, which can cause duplicate calls to Subscribe if there was no Unsubscribe done.
The bus that calls the Subscribe method is common among the clients, so there may be even a case where an Unsubscribe call Unsubscribes all the Activation clients, but this needs to be checked.

Reference: https://www.freedesktop.org/wiki/Software/systemd/dbus/
```
Subscribe() enables most bus signals to be sent out. Clients which are interested in signals need to
call this function. Signals are only sent out if at least one client invoked this function. Unsubscribe()
undoes the signal subscription that Subscribe() implements. It is not necessary to invoke
Unsubscribe() as clients are tracked. Signals are no longer sent out as soon as all clients which
previously asked for Subscribe() either closed the bus connection or invoked Unsubscribe().
```

**Comment by gtmills** [comment]
We also should do this here: 
https://github.com/openbmc/openpower-pnor-code-mgmt/blob/master/activation.cpp#L40
