### ISSUE TITLE
User management : design password REST API

### ISSUE THREAD

**Issue by dkodihal** [openbmc/openbmc#3303]
Design OpenBMC REST API to set/change user passwords. See if https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/User/Password.interface.yaml can be leveraged.

**Comment by vishwabmc** [comment]
@dkodihal Are we using this and use the pam libraries to updt/create the password ?

**Comment by dkodihal** [comment]
@vishwabmc I think that would be the way to go. The implementation of the set/change password API would be in the REST server. The REST server will directly make calls to PAM to store/authenticate passwords (no passwords over D-Bus).

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/90
