### ISSUE TITLE
os sonic cann't communicate with openbmc

### ISSUE THREAD

**Issue by jianbaishi** [openbmc/openbmc#3304]
env：x86(xeon) use os sonic
         openbmc use cpu: ast2520
log:
sonic:
(2018_07_12:10:03:11)[  165.137544] ipmi_si: probing via hardcoded address                                                               
(2018_07_12:10:03:11)[  165.137545] ipmi_si: Adding hardcoded-specified kcs state machine                                                
(2018_07_12:10:03:11)[  165.137548] ipmi_si: Trying hardcoded-specified kcs state machine at i/o address 0xca2, slave address 0x0, irq 0 
(2018_07_12:10:03:11)[  165.137553] ipmi_si: Interface detection failed                                                                  

in the process，code try to get stauts：
static int kcs_detect(struct si_sm_data *kcs)
{
	/*
	 * It's impossible for the KCS status register to be all 1's,
	 * (assuming a properly functioning, self-initialized BMC)
	 * but that's what you get from reading a bogus address, so we
	 * test that first.
	 */
	if (read_status(kcs) == 0xff)
		return 1;

	return 0;
}
get value 0xff，so go to fail.

What is the cause of the problem？？？

**Comment by chunghuihuang** [comment]
i have the same issue.
did you fix?

**Comment by jianbaishi** [comment]
> i have the same issue.
> did you fix?

My problem：other devices have conflicts in the LPC bus

**Comment by michealylj1** [comment]
I also meet the same issue, do you have any solution to fix it?

**Comment by amboar** [comment]
Have you enabled the KCS devices in the BMC devicetree?

**Comment by michealylj1** [comment]
--- a/arch/arm/boot/dts/aspeed-g5.dtsi
+++ b/arch/arm/boot/dts/aspeed-g5.dtsi
@@ -387,7 +387,8 @@
 						compatible = "aspeed,ast2500-kcs-bmc";
 						interrupts = <8>;
 						kcs_chan = <3>;
-						status = "disabled";
+						kcs_addr = "0xca2";
+						status = "okay";
 					};
 				};

**Comment by amboar** [comment]
Can you please wrap the comment in code markers? I can't make sense of that as it stands. See https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by michealylj1** [comment]
![image](https://user-images.githubusercontent.com/46735287/60064129-046e3080-9732-11e9-8672-95ee60786c88.png)

**Comment by michealylj1** [comment]
We also use the oscilloscope to measure the KSC signal in the LPC bus between X86 and AST2500, When I run command as "modprobe ipmi_si" in the SONIC system, It can be saw the KCS request from X86 to AST2500, but there is no any repspson from BCM side. So I just suspect the AST2500 don't run in KCS mode.

**Comment by amboar** [comment]
Have you enabled the kcsbridge package in the OpenBMC build for your machine?

**Comment by michealylj1** [comment]
Yes, I already enable the KSC bridge in the openBMC build.
```
Index: classes/obmc-phosphor-image.bbclass
===================================================================
--- classes/obmc-phosphor-image.bbclass (revision 130424)
+++ classes/obmc-phosphor-image.bbclass (working copy)
@@ -95,7 +95,7 @@
         lrzsz \
         "
 
-OBMC_IMAGE_EXTRA_INSTALL ?= ""
+OBMC_IMAGE_EXTRA_INSTALL ?= "virtual-obmc-host-ipmi-hw"
 
 # The /etc/version file is misleading and not useful.  Remove it.
 # Users should instead rely on /etc/os-release.
Index: conf/distro/include/phosphor-defaults.inc
===================================================================
--- conf/distro/include/phosphor-defaults.inc   (revision 130173)
+++ conf/distro/include/phosphor-defaults.inc   (working copy)
@@ -11,7 +11,8 @@
 PREFERRED_PROVIDER_virtual/obmc-chassis-mgmt ?= "obmc-phosphor-chassisd"
 PREFERRED_PROVIDER_virtual/obmc-fan-mgmt ?= "obmc-phosphor-fand"
 PREFERRED_PROVIDER_virtual/obmc-flash-mgmt ?= "obmc-phosphor-flashd"
-PREFERRED_PROVIDER_virtual/obmc-host-ipmi-hw ?= "phosphor-ipmi-hw-example"
+#PREFERRED_PROVIDER_virtual/obmc-host-ipmi-hw ?= "phosphor-ipmi-hw-example"
+PREFERRED_PROVIDER_virtual/obmc-host-ipmi-hw ?= "phosphor-ipmi-bt"
 
```

**Comment by amboar** [comment]
and `kcsbridged` is running on the BMC?

**Comment by michealylj1** [comment]
Yes, It's running:

![image](https://user-images.githubusercontent.com/46735287/60075164-48276100-9757-11e9-9fa0-572f7b2c1c0b.png)

**Comment by amboar** [comment]
Intel and Facebook are making use of KCS, maybe @edtanous or @sdasari73 can find people who can better help you debug. I don't have any experience with kcsbridged, was just going through the obvious questions :)
