### ISSUE TITLE
Phosphor-User-Management:- LDAP Configuration

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#3305]
Do we need separate service for that? Can we extend the phosphor-settingsd/networkd for the LDAP configuration?
What should be the configuration parameters
LDAP server ip as multiple servers can be configured.
What would be the DN(eg ou=Users,dc=example,dc=local).
What would be the port? etc
Secure LDAP v/s Non-secure LDAP.

**Comment by ratagupt** [comment]
@rthomaiy ^^^^

**Comment by rthomaiy** [comment]
I thought phosphor-user-manager itself will be the right place for this. we need to define one interface for LDAP (which will also us to do all those configurations accordingly. Let me know).
