### ISSUE TITLE
bump version as a commit description

### ISSUE THREAD

**Issue by bazhenov-dn** [openbmc/openbmc#3307]
Hi everyone,

Currently it is quite frustrating to see the enormous amount of commits with 'bump version' description for various OpenBMC components without any glue of what actually has been changed.

Is it possible to replicate the 'bump version' description with the one from a corresponding component commit to understand changes that the distribution underwent?

Thanks,
Dmitry

**Comment by spinler** [comment]
I think that's a good idea.  The autobump script is https://github.com/openbmc/openbmc-tools/blob/master/infra/autobump.pl if you care to take a crack at it.

**Comment by gtmills** [comment]
+1 this idea.

**Comment by spinler** [comment]
FYI, this was done.  Check out how  https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-phosphor/+/12217/ looks

**Comment by bazhenov-dn** [comment]
Looks awesome.
