### ISSUE TITLE
GUI: firmware page does not load. 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3309]
Firmware page does not load and see this in the console output.
```
TypeError: content.data[key].Activation is undefined
Stack trace:
getFirmwares/<@http://localhost:8080/app.bundle.js:65522:15
processQueue@http://localhost:8080/app.bundle.js:27473:37
scheduleProcessQueue/<@http://localhost:8080/app.bundle.js:27521:27
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8080/app.bundle.js:28656:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8080/app.bundle.js:28953:13
done@http://localhost:8080/app.bundle.js:22931:36
completeRequest@http://localhost:8080/app.bundle.js:23175:7
requestLoaded@http://localhost:8080/app.bundle.js:23092:9
```

**Comment by gtmills** [comment]
@anoo1 Any idea why we would not have an Activation interface..?

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11492> Fix firmware page not loading
Resolves  #3309 GUI: firmware page does not load.

**Comment by anoo1** [comment]
> @anoo1 Any idea why we would not have an Activation interface..?

That sounds like a bug, could be the updater app is in failed state because of a core dump for example, or some kind of state where only part of the version object was removed but not all of it. Could you document the bmc level and if known the steps to get the system into that state and open an issue?

**Comment by gtmills** [comment]
@anoo1 After investigating more, I believe this was caused by a core dump of the openpower update manager. The image I saw this on had the sdbusplus change to throw exceptions,  https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/11456/. I believe the backend is fixed with: https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-pnor-code-mgmt/+/11501/ and https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-pnor-code-mgmt/+/11486/. I still think not relying on Activation would be a good change in the WebUI.
Will keep this open until a change to not rely on the Activation is merged. Thanks for the information!
