### ISSUE TITLE
Invalid python in Centriq2400-rep.py

### ISSUE THREAD

**Issue by alehed** [openbmc/openbmc#3310]
It seems like the brackets don't match in this part of the `Centriq2400-rep.py` file.

https://github.com/openbmc/openbmc/blob/d6a8ca3b0fb0049401cd045ebbc6c968d2c39fe4/meta-openbmc-machines/meta-arm/meta-qualcomm/meta-centriq2400-rep/recipes-phosphor/workbook/centriq2400-rep-config/Centriq2400-rep.py#L57-L71

Since I don't enough about this type of configuration files, I don't know how the correct file would look though.

**Comment by mine260309** [comment]
@KenChenIEC Please check this
