### ISSUE TITLE
Unit test valgrind runs on powerpcle giving spurious warnings

### ISSUE THREAD

**Issue by wak-google** [openbmc/openbmc#3315]
Any libraries compiled with gcc 7+ have an inline strcmp optimization applied which performs branches on possibly uninitialized data. Both sides of the branch handle the uninitialized data correctly, but valgrind is unable to determine this is the case currently. This affects any system libraries used in our testing since strmcp is a universally used c function. Notably this affects libsystemd since they do strcmp's all over their codebase. Googletest has a single dangling strcmp which could be converted to a c++ string comparison as a workaround.

Related sightings and reports with more detail on the issue
https://lists.ozlabs.org/pipermail/linuxppc-dev/2018-July/175321.html
https://bugs.kde.org/show_bug.cgi?id=386945

**Comment by acsawdey** [comment]
You can shut off the inline expansion of strcmp/strncmp with gcc option -mstring-compare-inline-limit=0 if that helps.

**Comment by wak-google** [comment]
Yeah, I did that for googletest at one point. We don't build all of the software we depend on from source, notably systemd, so this doesn't directly help us.
