### ISSUE TITLE
"Activate and reboot host" selection when activating a host image. 

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3323]
Similiar to how we the BMC reboot selection
![confirm_bmc_firmware_file_activation](https://user-images.githubusercontent.com/5455127/43207098-db07782a-8fec-11e8-99dd-841389ecc79a.PNG)
but for a Host image

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11945> Activate image and reboot host
Resolves  #3323 "Activate and reboot host" selection when activating a host image.
