### ISSUE TITLE
Not able to access the Web UI on the latest master.

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3324]
https://github.com/openbmc/phosphor-rest-server/commit/0cf702c3948487089723d539efc59275b958bf34 is not allowing access to the Web UI. 

```
 "description": "Trying to access Blocked URL"
```
is the error.

**Comment by gtmills** [comment]
Reverting https://github.com/openbmc/phosphor-rest-server/commit/0cf702c3948487089723d539efc59275b958bf34, until this can be fixed. 
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-rest-server/+/11643/

**Comment by gtmills** [comment]
We discussed moving our web ui hosting to Nginx.

**Comment by dkodihal** [comment]
https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/11691/ - serve webui via nginx.
