### ISSUE TITLE
op-pwrctl: get GPIOs from somewhere other than D-Bus

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#3332]
We'd like to get rid of the system_manager.py app, as python apps are slower to start and affect boot times.  Since this app hosts the GPIO configs used by the op-pwrctl code, op-pwrctl code needs to get the GPIO config from somewhere else, such as a systemd environment file.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11848> Add Witherspoon GPIO JSON
Resolves  #3332 op-pwrctl: get GPIOs from somewhere other than D-Bus
