### ISSUE TITLE
Why can‘t open the WEB UI？?

### ISSUE THREAD

**Issue by FrankRenn** [openbmc/openbmc#3334]
1.ip can ping success
2.ssh can login success
3.ipmi command can send success
4.had build phosphor-webui
5.bmcweb.service is runing 
But Always can not open the web ui 
Need your help, Thanks a lot!!
![default](https://user-images.githubusercontent.com/24242110/43561359-4879c5ae-9649-11e8-968f-d0f324b21cb3.JPG)
![2](https://user-images.githubusercontent.com/24242110/43561405-79629e70-9649-11e8-90c1-2a462801bc3c.JPG)
![3](https://user-images.githubusercontent.com/24242110/43561440-a8e5ef9e-9649-11e8-9c83-d3544633d61e.JPG)

**Comment by sivassrr** [comment]
Have you tried with https? and also you may want to accept the advance option "proceed to <ip>". (case of chrome browser). Screen will be as shown below. 
![image](https://user-images.githubusercontent.com/19144129/43562090-12a89d9e-9638-11e8-9673-bc70b21dfb27.png)

**Comment by FrankRenn** [comment]
@sivassrr 
Hi sivassrr ,thanks for your help ,but I tried with https, still fail
And I have a question, if I need to install nodejs in obmc system ?
![5](https://user-images.githubusercontent.com/24242110/43563123-202d73c0-9653-11e8-9eca-3774bdc533e0.JPG)
![4](https://user-images.githubusercontent.com/24242110/43563130-2dcaa6e2-9653-11e8-95d9-e9fb972a0163.JPG)

**Comment by sivassrr** [comment]
With the official image I see  in systemctl output
```
  nginx.service                              loaded    active   running   The NGINX HTTP and reverse```

As you are running with your sandbox, Pls check whether it is running.

**Comment by FrankRenn** [comment]
After check ,I find there is no nginx.service in obmc system, so i try to add and build ,but occur the fellow error:
![snip20180802_1](https://user-images.githubusercontent.com/24242110/43594624-44437db8-96ad-11e8-9b44-58c39075d2ee.png)
The build system is ubuntu14.04
Any suggestion about that?

**Comment by FrankRenn** [comment]
The issue has solved ,so close the issue

**Comment by sivassrr** [comment]
Good to hear, Issue is resolved. Could you pls put how it got resolved that helps. If any one checks the history of this issue.

**Comment by michealylj1** [comment]
Hi FrankRenn,

> At first can not login webui because have no bmcweb.socket in obmc system.
> The nodejs-native do_compile fail because my npm have some problem
> At last to login web ui again,need to appoint port number883: https://10.0.15.177:883
> Used the meta-x86/meta-intel/meta-s2600wf

I just meet the same issue with you when I run openbmc in the chip "meta-evb-ast2500", Please tell me 

1) how to add nginx service in obmc system?
2) how to enable bmcweb.socket  in obmc system?
3) If I need to install nodejs in obmc system, how to do ?

Thanks,
Michael
