### ISSUE TITLE
Update the code update whitelist

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#3346]
The code update whitelist included the BMC settings properties located in the `/var/lib/obmc` directory (https://github.com/openbmc/openbmc/commit/a643f743c0c7cdefd2afea9a89b2c41bf51d57af#diff-fd16bc9a770bb803767ba5fdda78d27e).

But the settings and other app data have been moved to new directories under /var/lib/  such as `/var/lib/phosphor-settings-manager`. Need to update the whitelist to include these new directories.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11765> whitelist: Add new phosphor settings directories
Closes  #3346 Update the code update whitelist
