### ISSUE TITLE
Development related to Intel ME (management engine)

### ISSUE THREAD

**Issue by MichaelWang2017** [openbmc/openbmc#3354]
Hi all, we plan to launch a project on the X86 platform, and need to get information from the ME, so I want to know whether openbmc has done something like openpower-occ-control, or something else. Thank you.

**Comment by sharadkhetan** [comment]
Hi Michael,
OpenBMC does not have ME interaction functionality at this time. It will be a good addition to OpenBMC.

Thanks,
-Sharad

**Comment by MichaelWang2017** [comment]
Okay, thank you.
