### ISSUE TITLE
mboxd cause host IRQ flood on P8

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#3357]
This is an issue found by Yadro on P8 vesnin system, and reproduced on Palmetto as well.

With a recent OpenBMC, the host gets flood of IRQ:
```
$ cat /proc/interrupts | grep 22
           CPU0       CPU1        ...
 22:    5894954 2356550678        ...
...
```

**Comment by mine260309** [comment]
The direct cause is because `mboxd` service sends an event to host, and generate the interrupt to the host.
While host does not enable mbox feature and the interrupt is not cleared, and thus cause the issue.

**Comment by mine260309** [comment]
One quick workaround is to make `mboxd` not sends event to host.
```
diff --git a/mboxd.c b/mboxd.c
index 070c8bc..6dcf263 100644
--- a/mboxd.c
+++ b/mboxd.c
@@ -337,10 +337,10 @@ int main(int argc, char **argv)
                MSG_ERR("LPC configuration failed, RESET required: %d\n", rc);
        }

-       rc = set_bmc_events(context, BMC_EVENT_DAEMON_READY, SET_BMC_EVENT);
-       if (rc) {
-               goto finish;
-       }
+//     rc = set_bmc_events(context, BMC_EVENT_DAEMON_READY, SET_BMC_EVENT);
+//     if (rc) {
+//             goto finish;
+//     }

        MSG_INFO("Entering Polling Loop\n");
        rc = poll_loop(context);
@@ -349,7 +349,7 @@ int main(int argc, char **argv)

 finish:
        MSG_INFO("Daemon Exiting...\n");
-       clr_bmc_events(context, BMC_EVENT_DAEMON_READY, SET_BMC_EVENT);
+//     clr_bmc_events(context, BMC_EVENT_DAEMON_READY, SET_BMC_EVENT);

        free_mboxd_dbus(context);
        free_flash_dev(context);
```

Note that the BMC is unable to clear the interrupt bit, so it requires AC cycle for the bit to be cleared with the workaround.

A more proper fix is to be discussed:
1. On BMC side, probably make mboxd only do necessary init (mapping LPC to flash with correct size), and exit;
2. On host side, is it possible to mask the interrupt, or ignore the interrupt, or clear the interrupt?

@AlexanderAmelkin @ozbenh @amboar

**Comment by ozbenh** [comment]
On Fri, 2018-08-10 at 09:09 +0000, Lei YU wrote:
> A more proper fix is to be discussed:
> On BMC side, probably make mboxd only do necessary init (mapping LPC to flash with correct size), and exit;
> On host side, is it possible to mask the interrupt, or ignore the interrupt, or clear the interrupt?
> @AlexanderAmelkin @ozbenh @amboar

2) requires the host to use the SIO to enable the LPC MBOX, then go
   mask the interrupt, which is rather convoluted, esp when *not* using
   mbox...

Ben.

**Comment by amboar** [comment]
Yeah, we should just "fix" mboxd so it's possible to avoid triggering the interrupt and just configure the LPC2AHB mapping to point to the flash mapping.

**Comment by mine260309** [comment]
So the existing `mboxd.service` and `mboxd-reload@.service` are not necessary, we P8 really needs is something like `mboxd-init.service` which is a oneshot service.

Probably we should add a P8 distro-feature, and use this df to install only `mboxd-init.service`.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11910> meta-palmetto: Replace mboxd with mboxd-init-only
Resolves:  #3357 mboxd cause host IRQ flood on P8

**Comment by AlexanderAmelkin** [comment]
@rfrandse, great! Going to test this for VESNIN.

**Comment by mine260309** [comment]
@AlexanderAmelkin Could you please test https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/11913/, where the source code is in https://github.com/shenki/aspeed-lpc-control

It is more straightforward fix, and does not needs to include the mbox daemon anymore.

**Comment by nest1ing** [comment]
Solution from @shenki  also works fine for YADRO VESNIN
