### ISSUE TITLE
ubi image build failure for evb-ast2500

### ISSUE THREAD

**Issue by aminaminf** [openbmc/openbmc#3361]
I have been able to succesfully  follow the code update procedure described in [https://github.com/openbmc/docs/blob/master/code-update/code-update.md](url)
on the ast2500 evaluation board, however I am not able to build ubi images for the evaluation board to try the ubi code update described in [https://github.com/openbmc/docs/blob/master/code-update/ubi-code-update.md](url).

As a try, I added a "require conf/distro/include/phosphor-ubi.inc" line in the meta-evb-ast2500/conf/layer.conf file (the include file seems to add the obmc-ubi-fs distro feature) and triggered the build but I got the below error:

Error:
 Problem: conflicting requests
  - nothing provides phosphor-software-manager-updater-ubi needed by packagegroup-obmc-apps-software-1.0-r1.noarch

ERROR: obmc-phosphor-image-1.0-r0 do_rootfs: Function failed: do_rootfs

I am pretty sure that layer.conf is not the correct place to add obmc-ubi-fs feature (conf/distro ?) , so I appreciate any help on where to add this feature and possibly the other missing configs or hints that would fix this build failure .

**Comment by anoo1** [comment]
Hi @aminaminf , you're close, just need to create a new .conf file to put the ubi distro feature in (and also the phosphor-base one), and change the local.conf.sample file with the name of that new distro file.

Here are the needed changes, I named the file openbmc-evb-ast2500.conf to follow other system's name conventions:

```
| diff --git a/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/distro/openbmc-evb-ast2500.conf b/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/distro/openbmc-evb-ast2500.conf
| new file mode 100644
| index 0000000..02b7b41
| --- /dev/null
| +++ b/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/distro/openbmc-evb-ast2500.conf
| @@ -0,0 +1,2 @@
| +require conf/distro/include/phosphor-base.inc
| +require conf/distro/include/phosphor-ubi.inc
| diff --git a/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/local.conf.sample b/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/local.conf.sample
| index 6a12c60..1febbb4 100644
| --- a/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/local.conf.sample
| +++ b/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/local.conf.sample
| @@ -1,5 +1,5 @@
|  MACHINE ??= "evb-ast2500"
| -DISTRO ?= "openbmc-phosphor"
| +DISTRO ?= "openbmc-evb-ast2500"
|  PACKAGE_CLASSES ?= "package_rpm"
|  SANITY_TESTED_DISTROS_append ?= " *"
|  EXTRA_IMAGE_FEATURES = "debug-tweaks"
```

**Comment by aminaminf** [comment]
@anoo1 thanks. The build is fixed.  
@mine260309 thanks for the note.  Could you point me to the ubi related scripts you mentioned. Just to know where to start looking into. Thanks again

**Comment by mine260309** [comment]
@aminaminf By the ubi related scripts, I mean:
1. https://github.com/openbmc/openbmc/blob/master/meta-phosphor/common/recipes-phosphor/flash/phosphor-software-manager/obmc-flash-bmc
2. The patches to u-boot related to ubi-fs:
https://github.com/openbmc/openbmc/blob/master/meta-phosphor/aspeed-layer/recipes-bsp/u-boot/u-boot-aspeed.inc#L5-L10

**Comment by aminaminf** [comment]
@gtmills yes thanks. @mine260309 thanks for the pointers.
