### ISSUE TITLE
Base Function - VPD

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#337]
IPMI format supported, no support for IBM format.

**Comment by vishwabmc** [comment]
@anoo1 can you please add more to it ?.. What delta are we looking here than whats already implemented in Barreleye ?.

**Comment by anoo1** [comment]
@williamspatrick can help expand on this story.

**Comment by geissonator** [comment]
Need to move the inventory stories over to this and remove the points from this epic.  Anything special for VPD will come from mfg and we have sizing over there.

**Comment by williamspatrick** [comment]
Able to be closed?
