### ISSUE TITLE
GUI: "Select All" checkbox should select only filtered events

### ISSUE THREAD

**Issue by BeccaBroek** [openbmc/openbmc#3373]
Currently when a user selects all on the Event Log page, all events are selected, regardless of the filter. 

For example, if there are 3 low priority events:
<img width="1139" alt="screen shot 2018-08-28 at 10 53 45 am" src="https://user-images.githubusercontent.com/26717697/44735255-87dad900-aab1-11e8-8f68-4afd2aa69d91.png">

And when select all input is selected while the low priority filter is applied,
<img width="1146" alt="screen shot 2018-08-28 at 10 53 53 am" src="https://user-images.githubusercontent.com/26717697/44735281-9aeda900-aab1-11e8-965d-fea980d4a434.png">

51 events are selected. (All of the events) and subsequently are all deleted, exported, etc.

**Comment by BeccaBroek** [comment]
Also seeing that when a filter is applied, and all boxes are checked, the 'select all' box is not checked as it should be.

<img width="1116" alt="screen shot 2018-08-30 at 10 12 44 am" src="https://user-images.githubusercontent.com/26717697/44861114-7cb4b400-ac3d-11e8-9405-49578f9f4a82.png">

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/12228> Event log select all checkbox
Resolves  #3373 GUI: "Select All" checkbox should select only filtered events
