### ISSUE TITLE
SOL console export to text file button

### ISSUE THREAD

**Issue by BeccaBroek** [openbmc/openbmc#3374]
Implement ability to export SOL console data to text file.

**Comment by BeccaBroek** [comment]
https://gerrit.openbmc-project.xyz/#/c/10426/ removed new tab and export buttons

https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-webui/+/12345/ added new tab button

**Comment by gtmills** [comment]
I think we should still do this. Give us 6 more months stalebot.
