### ISSUE TITLE
How to activate the BMC firmware by WEB GUI ( such as in QEMU/Real hardware)? is it supported fully?

### ISSUE THREAD

**Issue by jinneal** [openbmc/openbmc#3376]
I try to upgrade the eSW of BMC by WEBUI, and activate it failed, it seems some device missing, the following log will be printout:

root@witherspoon:~# journalctl -r | more                
-- Logs begin at Wed 2018-09-12 08:31:23 UTC, end at Wed 2018-09-12 08:50:14 UTC. --
Sep 12 08:50:14 witherspoon systemd[1]: Started Deletes read-only and kernel ubi volume 8d4ca4dc.
Sep 12 08:50:14 witherspoon systemd[1]: Started Removes the guard that blocks BMC reboot.
Sep 12 08:50:13 witherspoon systemd[1]: Starting Removes the guard that blocks BMC reboot...
Sep 12 08:50:13 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 12 08:50:13 witherspoon systemd[1]: Starting Deletes read-only and kernel ubi volume 8d4ca4dc...
Sep 12 08:50:13 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 12 08:50:13 witherspoon systemd[1]: Created slice system-obmc\x2dflash\x2dbmc\x2dubiro\x2dremove.slice.
Sep 12 08:50:13 witherspoon systemd[1]: obmc-flash-bmc-ubiro@8d4ca4dc.service: Triggering OnFailure= dependencies.
Sep 12 08:50:13 witherspoon phosphor-image-updater[1099]: BMC activation has ended - BMC reboots are re-enabled.
Sep 12 08:50:13 witherspoon systemd[1]: Failed to start Store read-only images 8d4ca4dc to BMC storage.
Sep 12 08:50:13 witherspoon systemd[1]: obmc-flash-bmc-ubiro@8d4ca4dc.service: Failed with result 'exit-code'.
Sep 12 08:50:13 witherspoon systemd[1]: obmc-flash-bmc-ubiro@8d4ca4dc.service: Main process exited, code=exited, status=255/n/a
Sep 12 08:50:13 witherspoon obmc-flash-bmc[1338]:           error 2 (No such file or directory)
Sep 12 08:50:13 witherspoon obmc-flash-bmc[1338]: ubimkvol: error!: error while probing "/dev/ubi4"
Sep 12 08:50:13 witherspoon obmc-flash-bmc[1338]:         error 2 (No such file or directory)
Sep 12 08:50:13 witherspoon obmc-flash-bmc[1338]: libubi: error!: cannot get information about "/dev/ubi4"
Sep 12 08:50:13 witherspoon obmc-flash-bmc[1338]: grep: /sys/class/ubi/ubi4/subsystem/ubi4*/name: No such file or directory
Sep 12 08:50:11 witherspoon systemd[1]: Started Create BMC read-write ubi volume.
Sep 12 08:50:11 witherspoon systemd[1]: Starting Store read-only images 8d4ca4dc to BMC storage...
Sep 12 08:50:11 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 12 08:50:11 witherspoon phosphor-gevent[1249]: 127.0.0.1 user:root PUT http://127.0.0.1:8081/xyz/openbmc_project/software/8d4ca4dc/attr/RequestedActivation json:{u'data': u'xyz.openbmc_project.Software.Activation.RequestedActivations.Active'} 200 OK
Sep 12 08:50:11 witherspoon systemd[1]: Created slice system-obmc\x2dflash\x2dbmc\x2dubiro.slice.
Sep 12 08:50:10 witherspoon systemd[1]: Starting Create BMC read-write ubi volume...
Sep 12 08:50:10 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 12 08:50:10 witherspoon phosphor-image-updater[1099]: Successfully completed Signature vaildation.
Sep 12 08:50:10 witherspoon systemd[1]: Started Enable a guard that blocks BMC reboot.
Sep 12 08:50:09 witherspoon systemd[1]: Starting Enable a guard that blocks BMC reboot...
Sep 12 08:50:09 witherspoon systemd[1]: Detaching egress BPF program from cgroup failed: Invalid argument
Sep 12 08:50:09 witherspoon phosphor-image-updater[1099]: BMC image activating - BMC reboots are disabled.
Sep 12 08:48:33 witherspoon phosphor-gevent[1249]: 127.0.0.1 user:root POST http://127.0.0.1:8081/upload/image json:None 200 OK
Sep 12 08:48:31 witherspoon phosphor-version-software-manager[1122]: Untaring

**Comment by mine260309** [comment]
@anoo1

**Comment by jinneal** [comment]
I can activate the BMC firmware by WEBUI (AST2500) successfully, the log is printout:

         Starting Reboot...
[ 1272.300052] watchdog: watchdog0: watchdog did not stop!
[ 1272.334040] systemd-shutdow: 29 output lines suppressed due to ratelimiting
[ 1272.430944] systemd-shutdown[1]: Syncing filesystems and block devices.
[ 1272.452854] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[ 1272.504067] systemd-journald[493]: Received SIGTERM from PID 1 (systemd-shutdow).
[ 1272.551976] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[ 1272.587568] systemd-shutdown[1]: Hardware watchdog 'aspeed_wdt', version 0
[ 1272.623663] systemd-shutdown[1]: Unmounting file systems.
[ 1272.771465] systemd-shutdown[1]: All filesystems unmounted.
[ 1272.772449] systemd-shutdown[1]: Deactivating swaps.
[ 1272.773786] systemd-shutdown[1]: All swaps deactivated.
[ 1272.774607] systemd-shutdown[1]: Detaching loop devices.
[ 1272.841685] systemd-shutdown[1]: All loop devices detached.
[ 1272.947830] watchdog: watchdog0: watchdog did not stop!
[ 1272.948451] shutdown: 4 output lines suppressed due to ratelimiting
shutdown: reboot --timeout 90000000us --log-level 6 --log-target kmsg --log-color
+ awk /oldroot|mnt/ { print $2 }
+ sort -r
+ umount /oldroot/sys/kernel/debug
+ umount /oldroot/sys/fs/cgroup/unified
+ umount /oldroot/sys/fs/cgroup/systemd
+ umount /oldroot/sys/fs/cgroup
+ umount /oldroot/sys
+ umount /oldroot/proc
+ umount /oldroot/dev/shm
+ umount /oldroot/dev/pts
+ umount /oldroot/dev
+ umount /oldroot
+ umount /mnt/initramfs/rw
+ umount /mnt/initramfs/ro
+ umount /mnt
+ set +x
Pinging watchdog with args -t 1 -T 5
update: --clean-saved-files
[ 1273.765972] jffs2: notice: (913) jffs2_build_xattr_subsystem: complete building xattr subsystem, 8 of xdatum (3 unchecked, 5 orphan) and 41 of xref (5 dead, 1 orphan) found.
Updating kernel...
Erasing block: 68/68 (100%) 
Writing kb: 4316/4316 (100%) 
Verifying kb: 4316/4316 (100%) 
Updating rofs...
Erasing block: 278/278 (100%) 
Writing kb: 17768/17768 (100%) 
Verifying kb: 17768/17768 (100%) 
Skipping empty update of rwfs.
Updating u-boot...
Erasing block: 4/4 (100%) 
Writing kb: 228/228 (100%) 
Verifying kb: 228/228 (100%) 
[ 1293.551945] jffs2: notice: (988) jffs2_build_xattr_subsystem: complete building xattr subsystem, 8 of xdatum (3 unchecked, 5 orphan) and 41 of xref (5 dead, 1 orphan) found.
ls: /run/initramfs/image-*: No such file or directory
Flash update completed.
[ 1293.782065] watchdog: watchdog0: watchdog did not stop!
Resetting watchdog timeouts to -T 15
Remaining mounts:
[ 1294.818961] watchdog: watchdog0: watchdog did not stop!
tmpfs / tmpfs rw,nosuid,nodev,mode=755 0 0
sys /sys sysfs rw,relatime 0 0
dev /dev devtmpfs rw,relatime,size=229480k,nr_inodes=57370,mode=755 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
proc /proc proc rw,relatime 0 0
[ 1294.883059] reboot: Restarting system
