### ISSUE TITLE
Core "Present" attribute is read-only 

### ISSUE THREAD

**Issue by ssombar** [openbmc/openbmc#3377]
In a test case where we exercise OpenBMC's IPMI interface, we set  cpu0/core4 "Present" = false or set "Present" = true.
However this is not working in the most recent builds, the attribute seems to be read-only and reported only as true.

This is easy to recreate.   Perhaps this is now working as designed?

Here's a manual version of the test case.  on the lastest Master builds, such as build # 1657,

Login:
 curl -c cjar -b cjar -k -H "Content-Type: application/json" -X POST https://$BMC_IP/login -d "{\"data\": [ \"root\", \"0penBmc\" ] }"  
To show status,  look for cpu0/core4 "Present"
 curl -c cjar -b cjar -k -H "Content-Type: application/json" https://$BMC/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/enumerate | grep -A 4 core4

Test case:
 1. Set cpu0/core4 "Presence" = false
  ipmitool -I lanplus -C 3 -P 0penBmc -H $BMC raw  0x04 0x30 0x1e 0xa9 0x00 0x00 0x00 0x80 0x00 0x00 0x20 0x00
 2. Show status. 
 3. Set true
  ipmitool -I lanplus -C 3 -P 0penBmc -H $BMC raw  0x04 0x30 0x1e 0xa9 0x00 0x80 0x00 0x00 0x00 0x00 0x20 0x00
 4. Show Status.

**Comment by ssombar** [comment]
we’re going to need help from @tomjoseph for this one, since no errors in the journal,

**Comment by gtmills** [comment]
Andrew has a fix here: https://gerrit.openbmc-project.xyz/#/c/openbmc/openbmc/+/12824/

**Comment by geissonator** [comment]
Does this code path try to update something in /etc/?  Inventory should be in /var/ which should be ok with that bug.

**Comment by gtmills** [comment]
@ssombar Still a problem?

**Comment by ssombar** [comment]
I did not see another instance
