### ISSUE TITLE
Not any system instances(Motherboard/Node) in system inventory after the host os booted.

### ISSUE THREAD

**Issue by jinneal** [openbmc/openbmc#3390]
I can not find any implemented (Item.Board) objects in system inventory implemented in our real hardware:

root@openbmc:~# busctl tree xyz.openbmc_project.Inventory.Manager |cat
└─/xyz
  └─/xyz/openbmc_project
    └─/xyz/openbmc_project/inventory
      └─/xyz/openbmc_project/inventory/system

 root@evb-ast2500:~# busctl introspect xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system |cat
NAME                                             TYPE      SIGNATURE RESULT/VALUE FLAGS
org.freedesktop.DBus.Introspectable              interface -         -            -
.Introspect                                      method    -         s            -
org.freedesktop.DBus.Peer                        interface -         -            -
.GetMachineId                                    method    -         s            -
.Ping                                            method    -         -            -
org.freedesktop.DBus.Properties                  interface -         -            -
.Get                                             method    ss        v            -
.GetAll                                          method    s         a{sv}        -
.Set                                             method    ssv       -            -
.PropertiesChanged                               signal    sa{sv}as  -            -
xyz.openbmc_project.Inventory.Decorator.AssetTag interface -         -            -
.AssetTag                                        property  s         ""           emits-change writable

and the result of enumerate list from Dbus:

root@host-os:~# curl -c cjar -b cjar -k -H "Content-Type: application/json" https://${bmc}/xyz/openbmc_project/enumerate
{
  "data": {
    "/xyz/openbmc_project/control": {}, 
    "/xyz/openbmc_project/control/host0": {}, 
    "/xyz/openbmc_project/control/host0/TPMEnable": {
      "TPMEnable": false
    }, 
    "/xyz/openbmc_project/control/host0/auto_reboot": {
      "AutoReboot": true
    }, 
    "/xyz/openbmc_project/control/host0/boot": {
      "BootMode": "xyz.openbmc_project.Control.Boot.Mode.Modes.Regular", 
      "BootSource": "xyz.openbmc_project.Control.Boot.Source.Sources.Default"
    }, 
    "/xyz/openbmc_project/control/host0/boot/one_time": {
      "BootMode": "xyz.openbmc_project.Control.Boot.Mode.Modes.Regular", 
      "BootSource": "xyz.openbmc_project.Control.Boot.Source.Sources.Default", 
      "Enabled": true
    }, 
    "/xyz/openbmc_project/control/host0/power_cap": {
      "PowerCap": 0, 
      "PowerCapEnable": false
    }, 
    "/xyz/openbmc_project/control/host0/power_restore_policy": {
      "PowerRestorePolicy": "xyz.openbmc_project.Control.Power.RestorePolicy.Policy.AlwaysOff"
    }, 
    "/xyz/openbmc_project/control/host0/restriction_mode": {
      "RestrictionMode": "xyz.openbmc_project.Control.Security.RestrictionMode.Modes.None"
    }, 
    "/xyz/openbmc_project/control/host0/turbo_allowed": {
      "TurboAllowed": true
    }, 
    "/xyz/openbmc_project/control/minimum_ship_level_required": {
      "MinimumShipLevelRequired": true
    }, 
    "/xyz/openbmc_project/control/power_supply_redundancy": {
      "PowerSupplyRedundancyEnabled": true
    }, 
    "/xyz/openbmc_project/dump": {}, 
    "/xyz/openbmc_project/dump/entry/1": {
      "Elapsed": 1537262533, 
      "Size": 45544
    }, 
    "/xyz/openbmc_project/dump/entry/2": {
      "Elapsed": 1537262531, 
      "Size": 45448
    }, 
    "/xyz/openbmc_project/dump/entry/3": {
      "Elapsed": 1537262531, 
      "Size": 45604
    }, 
    "/xyz/openbmc_project/dump/entry/4": {
      "Elapsed": 1537262531, 
      "Size": 45436
    }, 
    "/xyz/openbmc_project/dump/entry/5": {
      "Elapsed": 1537262531, 
      "Size": 45508
    }, 
    "/xyz/openbmc_project/dump/entry/6": {
      "Elapsed": 1537352684, 
      "Size": 45524
    }, 
    "/xyz/openbmc_project/dump/internal/manager": {}, 
    "/xyz/openbmc_project/events": {}, 
    "/xyz/openbmc_project/inventory": {}, 
    "/xyz/openbmc_project/inventory/system": {
      "AssetTag": ""
    }, 
    "/xyz/openbmc_project/led/groups": {}, 
    "/xyz/openbmc_project/led/groups/bmc_booted": {
      "Asserted": false
    }, 
    "/xyz/openbmc_project/led/groups/enclosure_fault": {
      "Asserted": false
    }, 
    "/xyz/openbmc_project/led/groups/enclosure_identify": {
      "Asserted": false
    }, 
    "/xyz/openbmc_project/led/groups/fan_fault": {
      "Asserted": false
    }, 
    "/xyz/openbmc_project/led/groups/fan_identify": {
      "Asserted": false
    }, 
    "/xyz/openbmc_project/led/groups/power_on": {
      "Asserted": false
    }, 
    "/xyz/openbmc_project/logging": {}, 
    "/xyz/openbmc_project/logging/internal/manager": {}, 
    "/xyz/openbmc_project/network": {}, 
    "/xyz/openbmc_project/network/config": {
      "DefaultGateway": "10.56.122.127", 
      "HostName": "evb-ast2500"
    }, 
    "/xyz/openbmc_project/network/config/dhcp": {
      "DNSEnabled": true, 
      "HostNameEnabled": true, 
      "NTPEnabled": true, 
      "SendHostNameEnabled": true
    }, 
    "/xyz/openbmc_project/network/eth0": {
      "AutoNeg": false, 
      "DHCPEnabled": true, 
      "DomainName": [], 
      "InterfaceName": "eth0", 
      "MACAddress": "2a:6a:b0:88:d2:ae", 
      "NTPServers": [], 
      "Nameservers": [], 
      "Speed": 0
    }, 
    "/xyz/openbmc_project/network/eth0/ipv4/761d8e8d": {
      "Address": "169.254.118.166", 
      "Gateway": "0.0.0.0", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.DHCP", 
      "PrefixLength": 16, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }, 
    "/xyz/openbmc_project/network/eth0/ipv6/fda5103b": {
      "Address": "fe80::286a:b0ff:fe88:d2ae", 
      "Gateway": "", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.DHCP", 
      "PrefixLength": 64, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv6"
    }, 
    "/xyz/openbmc_project/network/eth1": {
      "AutoNeg": false, 
      "DHCPEnabled": true, 
      "DomainName": [], 
      "InterfaceName": "eth1", 
      "MACAddress": "56:1c:d5:65:1a:ed", 
      "NTPServers": [], 
      "Nameservers": [], 
      "Speed": 0
    }, 
    "/xyz/openbmc_project/network/eth1/ipv4/352c58b8": {
      "Address": "0.0.0.0", 
      "Gateway": "0.0.0.0", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.DHCP", 
      "PrefixLength": 24, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }, 
    "/xyz/openbmc_project/network/eth1/ipv6/a9c923e7": {
      "Address": "fe80::541c:d5ff:fe65:1aed", 
      "Gateway": "", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.DHCP", 
      "PrefixLength": 64, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv6"
    }, 
    "/xyz/openbmc_project/network/host0/intf": {
      "MACAddress": "00:00:00:00:00:00"
    }, 
    "/xyz/openbmc_project/network/host0/intf/addr": {
      "Address": "0.0.0.0", 
      "Gateway": "0.0.0.0", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static", 
      "PrefixLength": 0, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }, 
    "/xyz/openbmc_project/software": {
      "FieldModeEnabled": false, 
      "associations": [
        [
          "functional", 
          "software_version", 
          "/xyz/openbmc_project/software/98ceca4f"
        ], 
        [
          "active", 
          "software_version", 
          "/xyz/openbmc_project/software/98ceca4f"
        ]
      ]
    }, 
    "/xyz/openbmc_project/software/98ceca4f": {
      "Activation": "xyz.openbmc_project.Software.Activation.Activations.Active", 
      "Path": "", 
      "Priority": 0, 
      "Purpose": "xyz.openbmc_project.Software.Version.VersionPurpose.BMC", 
      "RequestedActivation": "xyz.openbmc_project.Software.Activation.RequestedActivations.None", 
      "Version": "v2.3-252-gaa5f70c-dirty", 
      "associations": [
        [
          "inventory", 
          "activation", 
          ""
        ]
      ]
    }, 
    "/xyz/openbmc_project/software/98ceca4f/software_version": {
      "endpoints": [
        "/xyz/openbmc_project/software"
      ]
    }, 
    "/xyz/openbmc_project/software/active": {
      "endpoints": [
        "/xyz/openbmc_project/software/98ceca4f"
      ]
    }, 
    "/xyz/openbmc_project/software/functional": {
      "endpoints": [
        "/xyz/openbmc_project/software/98ceca4f"
      ]
    }, 
    "/xyz/openbmc_project/state/bmc0": {
      "CurrentBMCState": "xyz.openbmc_project.State.BMC.BMCState.Ready", 
      "LastRebootTime": 1537352581000, 
      "RequestedBMCTransition": "xyz.openbmc_project.State.BMC.Transition.None"
    }, 
    "/xyz/openbmc_project/state/chassis0": {
      "CurrentPowerState": "xyz.openbmc_project.State.Chassis.PowerState.Off", 
      "LastStateChangeTime": 0, 
      "POHCounter": 0, 
      "RequestedPowerTransition": "xyz.openbmc_project.State.Chassis.Transition.Off"
    }, 
    "/xyz/openbmc_project/state/host0": {
      "AttemptsLeft": 3, 
      "BootProgress": "xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified", 
      "CurrentHostState": "xyz.openbmc_project.State.Host.HostState.Off", 
      "OperatingSystemState": "xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Inactive", 
      "RequestedHostTransition": "xyz.openbmc_project.State.Host.Transition.Off"
    }, 
    "/xyz/openbmc_project/time/bmc": {
      "Elapsed": 1537353222179305
    }, 
    "/xyz/openbmc_project/time/host": {
      "Elapsed": 1537353222164903
    }, 
    "/xyz/openbmc_project/time/owner": {
      "TimeOwner": "xyz.openbmc_project.Time.Owner.Owners.BMC"
    }, 
    "/xyz/openbmc_project/time/sync_method": {
      "TimeSyncMethod": "xyz.openbmc_project.Time.Synchronization.Method.NTP"
    }, 
    "/xyz/openbmc_project/user": {}, 
    "/xyz/openbmc_project/user/root": {}
  }, 
  "message": "200 OK", 
  "status": "ok"
}

But I can find the motherboard in other hardware show:

curl -b cjar -k https://10.42.0.187/xyz/openbmc_project/list
{
  "data": [
    "/xyz/openbmc_project/logging", 
    "/xyz/openbmc_project/led/groups/fan_fault", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm30", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core2", 
    "/xyz/openbmc_project/state/bmc0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core7", 
    "/xyz/openbmc_project/software", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core6", 
    "/xyz/openbmc_project/dump", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm6", 
    "/xyz/openbmc_project/inventory/system", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm7", 
    "/xyz/openbmc_project/led/groups/fan_identify", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1", 
    "/xyz/openbmc_project/led/groups/power_on", 
    "/xyz/openbmc_project/inventory", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard", 
    "/xyz/openbmc_project/software/18867d68", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core3", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm31", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core1", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm8", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm9", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core5", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core4", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm4", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm5", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core9", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core8", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm1", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm2", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm3", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core8", 
    "/xyz/openbmc_project/led/groups/bmc_booted", 
    "/xyz/openbmc_project/led/groups/enclosure_identify", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf1", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf3", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf2", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf5", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf4", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf7", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/membuf6", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core10", 
    "/xyz/openbmc_project/led/groups/enclosure_fault", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm16", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm17", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm14", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm15", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm12", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm13", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm10", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm11", 
    "/xyz/openbmc_project/state/host0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm18", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm19", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core11", 
    "/xyz/openbmc_project/control/host0", 
    "/xyz/openbmc_project/state/chassis0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core9", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm23", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm22", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm21", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm20", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm27", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm26", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm25", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm24", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm29", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/dimm28", 
    "/xyz/openbmc_project/object_mapper", 
    "/xyz/openbmc_project/logging/internal/manager", 
    "/xyz/openbmc_project/led/groups", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core11", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu1/core10", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core6", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core7", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core4", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core5", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core2", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core3", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core0", 
    "/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0/core1"
  ], 
  "message": "200 OK", 
  "status": "ok"

Who know the reason? any configuration or code missing?

**Comment by jinneal** [comment]
In general a way, which service implements the Item.Board?  which service provide the objects of system inventory?

**Comment by mine260309** [comment]
If it's a fresh new system (or you did factory-reset), you need to power on the host once to get the inventories.

**Comment by jinneal** [comment]
Do you mean all the inventories are generated by inventory_items.py a which will read eeprom to create all the objects to inventory manager after host power on?
