### ISSUE TITLE
Failed to reboot BMC

### ISSUE THREAD

**Issue by henbin** [openbmc/openbmc#3399]
Hi,
I encountered some issue about 'BMC reboot.'

1. Clone the latest openbmc repo and build romulus machine.
2. Start up the QEMU
sudo ./qemu-system-arm -m 256 -M romulus-bmc -nographic -drive file=flash-romulus,format=raw,if=mtd -net nic,macaddr=C0:FF:EE:00:00:02,model=ftgmac100 -net bridge,id=net0,helper=../qemu-bridge-helper,br=br0

3. Login the shell and execute 'reboot' command.
![image](https://user-images.githubusercontent.com/21031064/46393809-55a84100-c719-11e8-9956-caf840198740.png)

4. Reboot process would be stopped.
![image](https://user-images.githubusercontent.com/21031064/46393846-7c667780-c719-11e8-8a5c-05db462dca4f.png)

Did anyone encounter the issue?

Thanks.

**Comment by nest1ing** [comment]
This problem is reproduced at our hardware.
It seems that all firmware with a static flash layout are subject to this problem.

I push our solution to the [gerrit](https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/13512).

**Comment by henbin** [comment]
> This problem is reproduced at our hardware.
> It seems that all firmware with a static flash layout are subject to this problem.
> 
> I push our solution to the [gerrit](https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/13512).

It does work. 
Thanks for your solution.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/13512> meta-phosphor: fix reboot of BMC
Resolves  #3399 Failed to reboot BMC
