### ISSUE TITLE
Design Error / Event Creation Mechanism

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#340]

**Comment by geissonator** [comment]
** Story Task Proposal **
- [ ] Create /test dir showing current code work, get it merged
- [ ] Throw exception on error creation, write test case demonstrating it’s use
- [ ] Update recipes to export header to clients and build generated error hpp during compile
- [ ] Investigate DBUS built in errors, if applicable create documentation for their usage
- [ ] Incorporate commit interface from errl server (Adriana sprint item)

Remaining work/design not covered here
- Handling DBUS errors (passing error from one process to another)
- Allowing users to do non-exception based errors (creating multiple error instances in function)
- Internal errors that user defines within their own repo (non phosphor-logging)
