### ISSUE TITLE
Support for AST2050

### ISSUE THREAD

**Issue by pkubaj** [openbmc/openbmc#3400]
Hello,

are you going to support AST2050 chip? Its advantage is that it's widely available with boards ASUS KCMA-D8 and KGPE-D16, along with coreboot, so it makes for a cheap and affordable board with FOSS firmware.

AST2050 is supported by Facebook's initial release of OpenBMC for Linux 2.6.28.9, it was just somehow abandoned later.

**Comment by amboar** [comment]
@pkubaj it requires someone with the motivation and skill to implement support, however it appears no-one in the community currently has an interest. Obviously we welcome you to join the community and contribute support! You'll need to get hold of the datasheet from ASPEED and either reverse-engineer or acquire the schematics for the KCMA-D8 and KGPE-D16 baseboards.

However, in general this kind of question is more appropriate for the mailing list. If you're interested, please sign yourself up:

https://lists.ozlabs.org/listinfo/openbmc

Finally, apologies for the late reply.
