### ISSUE TITLE
Remove pam_systemd.so from common-session pam file

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#3408]
The libpam recipe will add pam_systemd.so into /etc/pam.d/common-session if systemd is enabled.  However systemd only builds pam_systemd.so if the logind (systemd-logind) package is enabled, which openbmc doesn't use and we explicitly disable.

I plan on bbappending the libpam recipe in meta-phosphor to remove that entry.

**Comment by nest1ing** [comment]
Seems it was resolved by the commit b4103f45d957422337bd34e43776e086e4208593

**Comment by spinler** [comment]
I can't even remember if I ended up doing anything here, but it apparently isn't a problem anymore.
