### ISSUE TITLE
Nginx blocks websocket-based SOL connections

### ISSUE THREAD

**Issue by joseph-reynolds** [openbmc/openbmc#3409]
The recent security changes made to the meta-ibm  recipes-httpd/nginx/file/nginx.conf Content-Security-Policy (CSP) caused a regression in the phosphor-webui web application and blocked the Serial Over Lan (SOL) function.  The symptom is: ```The page's settings blocked the loading of a resource at
wss://${bmc}/console0 ("default-src https://${bmc} 'unsafe-eval' 'unsafe-inline'").```

The web-app's SOL function uses secure WebSockets (the wss protocol) to connect back to the BMC, but the CSP `default-src 'self'` didn't allow that.   The fix is to add CSP `connect-src wss://$host`.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/14268> Nginx allow secure websocket connections
Resolves:  #3409 Nginx blocks websocket-based SOL connections
