### ISSUE TITLE
Recording sensor reading in a log

### ISSUE THREAD

**Issue by mousumipaul** [openbmc/openbmc#3423]
Hi i am newbie to openbmc. Earlier i used ipmitool to read sensor data over remote ip. I am looking for some pythonic way to record sensor ipmi data on some interval and records those to some file. I do not know if it possible using openbmc to log the records and then later to read this info and erase. Is there any way to run some python programs over bmc to accomplish this..

**Comment by edtanous** [comment]
One thing that is on my list to-do is to support streaming sensor readings off the BMC using the Redfish server-sent events mechanism.  Essentially it allows you to use a Redfish EventService to fulfill exactly the use case you're wanting over a well specified REST API.

Unfortunately, this feature isn't available in the OpenBMC redfish implementation yet, but it is certainly on the list.  Initial infrastructure for enabling SSE is in review here: https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/13948/

Adding an EventService implementation would probably be next.   If you're interested in pursuing this, I'm happy to go deeper into what I think would need to be done to implement this feature in OpenBMC.

Another option would be the /subscribe api in the rest implementation, which allows attaching to all sensor reading changes.  This is available today, but as it isn't backed by a standard, might change behavior in the future.

If you are dead-set on using ipmi, there are half a dozen ipmi libraries for python that would do the job and allow you to get sensor readings without calling into ipmitool.
