### ISSUE TITLE
Custom HW compilation for AST2400

### ISSUE THREAD

**Issue by halidaltuner** [openbmc/openbmc#3425]
Hello,

We have an Advantech branded(FWA-5020, x86 CPU) custom network appliances. These devices have an AST2400 chip.
We want to use OpenBMC on our appliances. However, I couldn't find the local.conf.sample file in the meta-aspeed folder. Am I doing something wrong?

**Comment by horuby** [comment]
In the meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf ?

**Comment by halidaltuner** [comment]
> In the meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf ?

Thank you for reply. But we have an ast2400 chip. Does this folder(meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf) support ast2400 chip?

**Comment by Sugon-yangbo** [comment]
do you resolve ?
