### ISSUE TITLE
Power / Cooling - Power Limit / Capping

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#343]
Remaining work here is a DBUS interface and implementation in settingsd or hwmon for interacting with caps.  This is probably a setting and details will fall out of the design of openbmc/openbmc#778

Open questions are what caps (there are quite a few beyond a customer settable one) and associated properties need to be exposed via REST and how does the application get these numbers (MRW attribute?)

**Comment by rfrandse** [comment]
work is done for phase 4 with #1213

**Comment by bradbishop** [comment]
Open questions

Is a DCMI equivalent REST API sufficient or are additional levels of control / reporting needed? (Todd).
Is someone working on DCMI and if so how far down the stack are they going?

**Comment by geissonator** [comment]
BMC provides the user power cap to HTMGT via inband sensor during boot and HTMGT provides to occ when going active.  If customer sets power cap while OCC active, then BMC sends new power cap directly to master occ.

**Comment by geissonator** [comment]
Capability to set a power cap via sysfs already in place.
DCMI interface which retrieves power cap and enable status done in #948.
Reducing this from 8->3 points and closing out #936 and #947
