### ISSUE TITLE
ColdFire FSI causes boot fail on P8

### ISSUE THREAD

**Issue by artemsen** [openbmc/openbmc#3433]
OpenBMC: v2.3-1050-gb1b8f7705 (AST2400)
OpenPOWER: v2.1-208-g2251a24 (POWER8)

The ColdFire FSI implementation affects the host boot process on our VESNIN server.
In some cases a host works significantly slower with enabled ColdFire FSI, for example, a fully equipped server with 128 DIMM modules waste several minutes inside the boot step 6.5 (host_discover_targets), that causes host reboot by watchdog timeout.

Here are two logs of boot processes for the small server (24 DIMM modules only), pay attention to timing tags:

Boot log with enabled ColdFire FSI:
```
  6.01481|ISTEP  6. 5 - host_discover_targets
  6.40736|platPresenceDetect start
  6.41019|target 0x00020000: Physical:/Sys0/Node0
  6.86161|target 0x00030000: Physical:/Sys0/Node0/DIMM0
 14.31433|target 0x00030001: Physical:/Sys0/Node0/DIMM1
 18.80229|target 0x00030002: Physical:/Sys0/Node0/DIMM2
 23.29598|target 0x00030003: Physical:/Sys0/Node0/DIMM3
...
177.01487|target 0x00050002: Physical:/Sys0/Node0/Proc2
207.54487|target 0x00050003: Physical:/Sys0/Node0/Proc3
238.08477|platPresenceDetect end
```

Boot log with disabled ColdFire FSI (using old skeleton):
```
  4.38357|ISTEP  6. 5 - host_discover_targets
  4.43280|platPresenceDetect start
  4.43391|target 0x00020000: Physical:/Sys0/Node0
  4.56733|target 0x00030000: Physical:/Sys0/Node0/DIMM0
  4.84939|target 0x00030001: Physical:/Sys0/Node0/DIMM1
  5.09339|target 0x00030002: Physical:/Sys0/Node0/DIMM2
  5.33734|target 0x00030003: Physical:/Sys0/Node0/DIMM3
 ...
 13.52674|target 0x00050002: Physical:/Sys0/Node0/Proc2
 13.59691|target 0x00050003: Physical:/Sys0/Node0/Proc3
 13.66989|platPresenceDetect end
```

The main delay occurs inside deviceRead() function called from [platPresenceDetect](https://github.com/open-power/hostboot/blob/c35645e2d863e37a4356d141713e082505c51e94/src/usr/hwas/hwasPlat.C#L454)().

**Comment by mine260309** [comment]
@ozbenh May help on this.

**Comment by artemsen** [comment]
@ozbenh, can you help us with this issue?

**Comment by ozbenh** [comment]
On Wed, 2018-12-05 at 03:34 -0800, Artem Senichev wrote:
> @ozbenh, can you help us with this issue

I don't recommend using the CF FSI on P8 except for exceptional
debugging circumstances.

The P8 chip doesn't have an asynchronous design on the FSI lines, it's
to sensitive to clock fluctuations. It's better to leave the FSI clock
off after the initial boot and leave it at that.

Cheers,
Ben.

**Comment by artemsen** [comment]
@ozbenh, what do you mean? Should I use the old method to start the host's CPU or should I disable FSI after sending start command?

**Comment by ozbenh** [comment]
On Thu, 2018-12-06 at 08:01 -0800, Artem Senichev wrote:
> @ozbenh, what do you mean? Should I use the old method to start the
> host's CPU or should I disable FSI after sending start command

Try either, see what works, but I think the old method generally worked
so I don't see a big urge to go to the new stack on P8.

P9 is a different issue

Cheers,
Ben.

**Comment by shenki** [comment]
> Try either, see what works, but I think the old method generally worked so I don't see a big urge to go to the new stack on P8. P9 is a different issue Cheers, Ben.

The "old method" was some userspace bitbanging C that Norm wrote in 2015:

 https://github.com/openbmc/skeleton/commit/5da4f4fc1706ea5c12981e18778f42249591fe18

I moved openbmc to the FSI kernel stack on P8 when the CF driver arrived. Going back to the old skeleton code would not be recommended.

**Comment by nest1ing** [comment]
We have the working (on our VESNIN servers) solution based on the old method. It worked with the last upstream codebase but required the patching of the `control_host.exe`  to restore the old FSI functionality.

Is it interested for the `palmetto` or some other P8-based platforms?

**Comment by mdmillerii** [comment]
The reason the POWER8 systems boot is so much slower with the new fsi stack is that the sbe runs on the fsi clock when the fsi bus is enabled.  This directly controls the   The old bitbang method switched the interface so that the pll refclock in the 100 MHz range after sending in the start command via putscom.

It would seem an approach of switching back the fsi clock mux to the free running input when user space closes the scom driver might be a viable approach?

**Comment by shenki** [comment]
> It would seem an approach of switching back the fsi clock mux to the free running input when user space closes the scom driver might be a viable approach?

This is an idea I had considered too.

Looking at the old application, it did this after the SBE startup:
```
		rc |= gpio_write(fsi_clk,0); /* hold clk low for clock mux */
		rc |= gpio_write(fsi_enable,0);
		rc |= gpio_clock_cycle(fsi_clk,16);
		rc |= gpio_write(fsi_clk,0); /* Data standby state */
```
Is it the setting of `fsi_enable` low that switches the clock mux back to internal?

> The old bitbang method switched the interface so that the pll refclock in the 100 MHz range after sending in the start command via putscom.

I am not sure where the 100Mhz change is. Can you point it out? The old code can be seen here:

https://github.com/openbmc/skeleton/blob/517b35ed92ad2c0df5e048711c175bacb632f6d0/op-hostctl/control_host_obj.c#L113

**Comment by nest1ing** [comment]
The issue is semi solved.
On our hardware we are using patch, restoring old behaviour (FSI over GPIO from user space).
https://github.com/openbmc/meta-yadro/blob/master/meta-vesnin/recipes-phosphor/skeleton/obmc-op-control-host/0001-Replace-ColdFire-FSI-with-plain-FSI-over-GPIO.patch
