### ISSUE TITLE
phosphor-networkd does not fully started

### ISSUE THREAD

**Issue by nest1ing** [openbmc/openbmc#3437]
This happens when the BMC has clean `rw` partition (e.g. first time boot or after the resetting to the manufacture settings).

When the BMC reached the `BMC READY` state, there is no configurations of the network interfaces in the DBus.

It looks like this:
```
curl -c cjar -b cjar -k -H "Content-Type: application/json" https://malevich.dev.yadro.com/xyz/openbmc_project/network/enumerate
{
  "data": {
    "/xyz/openbmc_project/network/host0/intf": {
      "MACAddress": "00:00:00:00:00:00"
    }, 
    "/xyz/openbmc_project/network/host0/intf/addr": {
      "Address": "0.0.0.0", 
      "Gateway": "0.0.0.0", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static", 
      "PrefixLength": 0, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }, 
    "/xyz/openbmc_project/network/snmp/manager": {}
  }, 
  "message": "200 OK", 
  "status": "ok"
}
```

Logs do not contain any messages to make the reasons clear:
```
journalctl --no-pager --no-hostname  -u systemd-networkd.service -u xyz.openbmc_project.Network.service                
-- Logs begin at Mon 2018-11-26 13:53:42 UTC, end at Mon 2018-11-26 14:15:39 UTC. --
Nov 26 13:53:48 systemd[1]: Starting Network Service...
Nov 26 13:53:52 systemd-networkd[860]: Enumeration completed
Nov 26 13:53:52 systemd-networkd[860]: lo: Link is not managed by us
Nov 26 13:53:52 systemd-networkd[860]: sit0: Link is not managed by us
Nov 26 13:53:52 systemd-networkd[860]: eth0: IPv6 successfully enabled
Nov 26 13:53:52 systemd-networkd[860]: eth0: Gained carrier
Nov 26 13:53:53 systemd[1]: Started Network Service.
Nov 26 13:53:55 systemd-networkd[860]: eth0: Gained IPv6LL
Nov 26 13:53:57 systemd-networkd[860]: eth0: DHCPv4 address 172.17.26.43/23 via 172.17.26.1
Nov 26 13:53:57 systemd-networkd[860]: Not connected to system bus, not setting hostname.
Nov 26 13:54:07 systemd-networkd[860]: eth0: Configured
Nov 26 13:54:07 systemd-networkd[860]: Could not set hostname: Permission denied
Nov 26 13:54:37 systemd[1]: Starting Phosphor Network Manager...
Nov 26 13:54:40 phosphor-network-manager[965]: Created the default network file.
Nov 26 13:54:42 systemd[1]: Started Phosphor Network Manager.
Nov 26 13:54:42 systemd[1]: Stopping Network Service...
Nov 26 13:54:44 systemd[1]: Stopped Network Service.
Nov 26 13:54:45 systemd[1]: Starting Network Service...
Nov 26 13:54:46 systemd-networkd[1018]: eth0: Gained IPv6LL
Nov 26 13:54:46 systemd-networkd[1018]: Enumeration completed
Nov 26 13:54:46 systemd[1]: Started Network Service.
Nov 26 13:54:47 systemd-networkd[1018]: lo: Link is not managed by us
Nov 26 13:54:47 systemd-networkd[1018]: sit0: Link is not managed by us
Nov 26 13:54:47 systemd-networkd[1018]: eth0: DHCPv4 address 172.17.26.43/23 via 172.17.26.1
Nov 26 13:54:48 systemd-networkd[1018]: Could not set hostname: Permission denied
Nov 26 13:54:54 systemd-networkd[1018]: eth0: Configured
```

After restart this service or reboot the BMC everything goes fine.
And it looks like this:
```
curl -c cjar -b cjar -k -H "Content-Type: application/json"https://malevich.dev.yadro.com/xyz/openbmc_project/network/enumerate
{
  "data": {
    "/xyz/openbmc_project/network/config": {
      "DefaultGateway": "172.17.26.1", 
      "HostName": "malevich.dev.yadro.com"
    }, 
    "/xyz/openbmc_project/network/config/dhcp": {
      "DNSEnabled": true, 
      "HostNameEnabled": true, 
      "NTPEnabled": true, 
      "SendHostNameEnabled": true
    }, 
    "/xyz/openbmc_project/network/eth0": {
      "AutoNeg": false, 
      "DHCPEnabled": true, 
      "DomainName": [], 
      "InterfaceName": "eth0", 
      "MACAddress": "a0:c5:f2:10:00:03", 
      "NTPServers": [], 
      "Nameservers": [], 
      "Speed": 0
    }, 
    "/xyz/openbmc_project/network/eth0/ipv4/430efe41": {
      "Address": "169.254.67.136", 
      "Gateway": "0.0.0.0", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.DHCP", 
      "PrefixLength": 16, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }, 
    "/xyz/openbmc_project/network/eth0/ipv4/80216ac7": {
      "Address": "172.17.26.43", 
      "Gateway": "0.0.0.0", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.DHCP", 
      "PrefixLength": 23, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }, 
    "/xyz/openbmc_project/network/eth0/ipv6/3e028c57": {
      "Address": "fe80::a2c5:f2ff:fe10:3", 
      "Gateway": "", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.DHCP", 
      "PrefixLength": 64, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv6"
    }, 
    "/xyz/openbmc_project/network/host0/intf": {
      "MACAddress": "00:00:00:00:00:00"
    }, 
    "/xyz/openbmc_project/network/host0/intf/addr": {
      "Address": "0.0.0.0", 
      "Gateway": "0.0.0.0", 
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static", 
      "PrefixLength": 0, 
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    }, 
    "/xyz/openbmc_project/network/snmp/manager": {}
  }, 
  "message": "200 OK", 
  "status": "ok"
```

**Comment by nest1ing** [comment]
As a fast workaround I put the `/etc/systemd/network/00-bmc-eth0.network` created by `phosphor-network` at first start to the `ro` partition.
But it seems like half a solution.

Does anyone have other ideas?

**Comment by ratagupt** [comment]
@nest1ing It seems that in the /etc there was no network file then phosphor-networkd automatically generates it..
Nov 26 13:54:37 systemd[1]: Starting Phosphor Network Manager...
Nov 26 13:54:40 phosphor-network-manager[965]: Created the default network file.
How long did you wait after first boot to get the network objects populated?Normally it takes 10-15 secs to populate it.
I would check it it my env and update here.

**Comment by nest1ing** [comment]
> @nest1ing It seems that in the /etc there was no network file then phosphor-networkd automatically generates it..
Yes, it is so.


> How long did you wait after first boot to get the network objects populated?Normally it takes 10-15 secs to populate it
significantly more than 15 seconds.

**Comment by ratagupt** [comment]
@nest1ing I tried to reproduce it in our env and was not hitting this issue any time, we tried near about 3-4 times but didn't hit this issue.
what we did is
1) Delete the network conf file
2) Reboot the BMC
We always get the D-Bus object having the DHCP address.
@prkatti1 Can you also confirm the same?

**Comment by nest1ing** [comment]
At our VESNIN server, it reproduces even without reboot BMC (just by removing conf file and restarting `xyz.openbmc_project.Network.service`). 
The D-Bus does not contain the DHCP address.

The repeated restart of the service bring it to the norm.

Seems the partially problem is the settings of our network equipment.
But any case, it looks as a bug in the `phosphor-network`.

**Comment by prkatti1** [comment]
@ratagupt @nest1ing Today we have noticed this issue on latest build.
  "data": {
    "/xyz/openbmc_project/network/host0/intf": {
      "MACAddress": "00:00:00:00:00:00"
    },
    "/xyz/openbmc_project/network/host0/intf/addr": {
      "Address": "0.0.0.0",
      "Gateway": "0.0.0.0",
      "Origin": "xyz.openbmc_project.Network.IP.AddressOrigin.Static",
      "PrefixLength": 0,
      "Type": "xyz.openbmc_project.Network.IP.Protocol.IPv4"
    },
    "/xyz/openbmc_project/network/snmp/manager": {}
  },
  "message": "200 OK",
  "status": "ok"

**Comment by nest1ing** [comment]
I'm still not ready to give full diagnose, but seems the `Manager::createChildObjects()` is never called (the `refreshObjectTimer` is not started) after the default config files is created and the network is restarted.

**Comment by ratagupt** [comment]
Yes @nest1ing  seems to me following gerrit link introduced this.
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-networkd/+/13184/.

**Comment by nest1ing** [comment]
I found the problem and push solution: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/16297

**Comment by ratagupt** [comment]
+1
