### ISSUE TITLE
Does Nuvoton WPCM450 BMC use OpenBMC

### ISSUE THREAD

**Issue by ssbarnea** [openbmc/openbmc#3438]
I do have a supermicro [6026tt](http://www.supermicro.com/products/system/2U/6026/SYS-6026TT-HIBQRF.cfm?INF=) with 4 nodes which do have the [Nuvoton WPCM450](https://www.thomas-krenn.com/en/wiki/Nuvoton_WPCM450R_IPMI_Chip_with_AMI-Software) BMC. The hardware is now out of support and Supermicro has no plans to update its messy KVM-over-LAN which is java based.

I wonder if I could switch to OpenBMC instead.

Sorry if I used the bugtracker for raising what counts mainly as a question but I was not able to find a better place to raise it. I tried to find a hardware compatibility matrix but I was not able to find one.

**Comment by gtmills** [comment]
Hi @ssbarnea, this is a good question for the mailing list, as it's not a bug or feature request. You can sign yourself up at https://lists.ozlabs.org/listinfo/openbmc

Thanks,
Gunnar
