### ISSUE TITLE
Include the build date in OpenBMC os-release

### ISSUE THREAD

**Issue by apopple** [openbmc/openbmc#3439]
Currently there is no build date included in /etc/os-release which makes it difficult to determine how old an installed OpenBMC build is. It would be convenient if this information could be included in /etc/os-release as it isn't always possible to lookup the git tag to determine this.

**Comment by spinler** [comment]
@joseph-reynolds I think you had discussed doing this?

**Comment by joseph-reynolds** [comment]
Yeah, no.  I added "target machine" to /etc/os-release here: https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/16489.  I was unaware of this issue; thanks for bringing it to my attention.

I interpret this as a request to add the build system's date the the `BUILD_ID` OS identification parameter (see https://www.freedesktop.org/software/systemd/man/os-release.html).  We set the value of BUILD_ID in meta-phosphor/recipes-core/os-release/os-release.bbappend.  It would be easy to append the date.

**Comment by mdmillerii** [comment]
Please don't break [Reproducible builds](https://wiki.yoctoproject.org/wiki/Reproducible_Builds) when adding this feature.  Choose your date wisely.

**Comment by joseph-reynolds** [comment]
Yeah, agreed.  I don't see a reason to add a "build date" to the image, and breaking reproducible builds is a reason to not add this.

Going back to the original question, there are two separate items:
1. Knowing how old the source code is that was used to build the image.  See `git describe` in the os-release.bbappend file referenced above; that puts the git tag into the os-release file.  I am not aware of any mechanism in git describe or in the OpenBMC's tagging practices which would help add a calendar date to this information.  If we decide a calendar date is needed, it would have to be "added wisely".  For now, see the OpenBMC release notes: https://github.com/openbmc/docs/blob/master/release/release-notes.md to help map tags back to releases.
2. Knowing when the system was most recently installed.  (This requires the BMC clock to be correct.)  Would something like `ls -ld /` work?

Can we close this issue?
