### ISSUE TITLE
Implement debug data collection services (BMC Dump)

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#344]

**Comment by vishwabmc** [comment]
At the moment, thinking about sosreport and abrt solutions on this.

**Comment by rfrandse** [comment]
@dkodihal Please break down Epic 13pts estimate into stories for phase 4

**Comment by dkodihal** [comment]
Stories broken down and added to epic #868.

**Comment by dkodihal** [comment]
Just close this one now?

**Comment by rfrandse** [comment]
this is handled in #868
