### ISSUE TITLE
Newer SBEFIFO DD doesn't allow chipOps when in istep mode

### ISSUE THREAD

**Issue by sannerd** [openbmc/openbmc#3444]
During some prototyping on Witherspoon ran into the fact that newer BMC levels prevent chipOps to the SBEFIFO DD when in "istep mode".   Given that we use chipOps to istep the SBE... means that istep is broken.  @eddiejames found this in the SBEFIFO Driver:

sbefifo 00:00:00:06: SBE state=-16
    ```case SBE_STATE_IPLING:
    case SBE_STATE_ISTEP:
    case SBE_STATE_MPIPL:
    case SBE_STATE_DMT:
        return -EBUSY;```


Please fix ASAP?  I do know that a version from May works... not sure when this got changed.

**Comment by eddiejames** [comment]
I sent a patch to the linux kernel list several weeks ago. It hasn't been acknowledged.

**Comment by apopple** [comment]
@eddiejames which patch was it? Guessing this one https://lkml.org/lkml/2019/1/21/1212?

**Comment by eddiejames** [comment]
Thats correct @apopple

**Comment by shenki** [comment]
This patch has landed in the openbmc kernel tree, and is in openbmc master.
