### ISSUE TITLE
ipmitool raw 0x06 0x52 does not support on openbmc?

### ISSUE THREAD

**Issue by gx0128** [openbmc/openbmc#3457]
ipmitool raw 0x06 0x52 command is not an oem command,  but the callback function does not register. Anyone meet the same problem?

**Comment by yongli3** [comment]
@gx0128 This 0x52 is I2C master write-read command, I had submitted a change about it:
https://gerrit.openbmc-project.xyz/#/c/openbmc/phosphor-host-ipmid/+/13353/

Will refactor and re-submit it

**Comment by gx0128** [comment]
@yongli3 thanks!

**Comment by yongli3** [comment]
@gx0128 Will submit in next week. Currently I think you can test/use the old one

**Comment by gx0128** [comment]
@yongli3  OK. Please tell me after you resubmit it. Thanks a lot.
