### ISSUE TITLE
Error in bitbake kernel for Raspberry PI 3 

### ISSUE THREAD

**Issue by Rolyli** [openbmc/openbmc#3462]
Hi MyFriends
When I trying to build OpenBMC image for Raspberry PI 3 on deepin-15.8 / 64 bits machine.

I copy meta-raspberrypi/conf/machine/raspberrypi3-64.conf to meta-evb/meta-evb-raspberrypi/conf
export TEMPLATECONF=meta-evb/meta-evb-raspberrypi/conf
 . openbmc-env
bitbake -k  obmc-phosphor-image
![default](https://user-images.githubusercontent.com/44188528/51223067-48872900-197b-11e9-8b72-6c8c61c07a54.png)
![default](https://user-images.githubusercontent.com/44188528/51223077-55a41800-197b-11e9-8711-d71fac7b39f5.png)

![default](https://user-images.githubusercontent.com/44188528/51222651-9b5fe100-1979-11e9-8e84-53e602826fc2.png)
The following error appears:
![default](https://user-images.githubusercontent.com/44188528/51222685-c9ddbc00-1979-11e9-9d60-e4adcb0666a7.png)
below is my log
[log.tar.gz](https://github.com/openbmc/openbmc/files/2762409/log.tar.gz)
Thanks 
谢谢

**Comment by geissonator** [comment]
There are some changes out there to get Raspberry Pi going again, may want to try pulling those down. https://gerrit.openbmc-project.xyz/#/q/owner:%22M.+D.+Truong%22+status:open

**Comment by Rolyli** [comment]
> There are some changes out there to get Raspberry Pi going again, may want to try pulling those down. https://gerrit.openbmc-project.xyz/#/q/owner:%22M.+D.+Truong%22+status:open

Thanks you very much , i will try it later.

**Comment by Rolyli** [comment]
unfortunately it doesn`t work
![default](https://user-images.githubusercontent.com/44188528/51253280-d34a4100-19d8-11e9-810a-75f2583d4740.png)
it still has the same problem.

**Comment by Rolyli** [comment]
Update this iessue
I have solved this problem.
Because i didn't set the correct MACHINE in local.conf and when i set it to raspberrypi3-64.
This problem just gone.
![image](https://user-images.githubusercontent.com/44188528/51259428-14e1e880-19e7-11e9-9792-cfa9a95481f7.png)
But it still has a problem , this one looks like a lot of people have met, and I might be able to search for solutions in github.
![image](https://user-images.githubusercontent.com/44188528/51259457-2a571280-19e7-11e9-9197-e7c9b175475e.png)

In the end, my English is not very good. If my grammar have some problem ,please point it out.
Thanks
谢谢
