### ISSUE TITLE
GUI: IE able to login but circling icon getting displayed not able to use 

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#3470]

**Comment by sivassrr** [comment]
```root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.6.0-rc1"
VERSION_ID="2.6.0-rc1-77-g84748a7"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.6.0-rc1"
BUILD_ID="2.6.0-rc1"```

```root@witherspoon:/var/log/nginx# cat error.log
2019/01/09 06:26:54 [warn] 1143#1143: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
2019/01/09 06:27:03 [warn] 1209#1209: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
2019/01/09 06:36:09 [warn] 1140#1140: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
2019/01/09 06:36:09 [warn] 1141#1141: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
2019/01/16 04:53:12 [warn] 1147#1147: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
2019/01/16 04:53:12 [warn] 1154#1154: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
2019/01/22 04:10:02 [warn] 1149#1149: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
2019/01/22 04:10:02 [warn] 1150#1150: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:61
root@witherspoon:/var/log/nginx# date
Tue Jan 22 05:48:12 UTC 2019```

**Comment by sivassrr** [comment]
Below is the screen which we get even after 25 mins of login using IE browser. 

![image](https://user-images.githubusercontent.com/19144129/51515793-15d9a680-1e3b-11e9-8c87-fca16068c08f.png)

@gtmills aware of this issue and working on it.

**Comment by sunleaf2002** [comment]
![image](https://user-images.githubusercontent.com/9078163/53861550-799ce500-401f-11e9-9fb0-a86a1e8f7ab8.png)
me too , I use ie v11 , event-log page is also, i donot know why.
![image](https://user-images.githubusercontent.com/9078163/53861685-dbf5e580-401f-11e9-82f8-da522f4ff0a6.png)

**Comment by sivassrr** [comment]
@gtmills Is there a plan to support this?  Was told that IE wouldnt be supported. Could you pls confirm @gtmills. We can close it accordingly then. Thank you in advance.

**Comment by gtmills** [comment]
IBM has no plans to support IE. We plan to support Chrome, Firefox, Safari and Edge browsers and will work to maintain that support upstream. Those 4 all currently work with the webUI. 

I think @edtanous still uses Internet Explorer as his primary browser.  😁😂 Ed, do you have any requirement to support IE, if not, I will close.

**Comment by gtmills** [comment]
Closing issue. Thanks for submitting Sivas.
