### ISSUE TITLE
unable to reduce openbmc  rootfs image size

### ISSUE THREAD

**Issue by priyanka611** [openbmc/openbmc#3472]
I am trying to reduce openbmc rootfs image which i want to flash on ast2500 board.My current image size is 14 mb and I want less than 14 mb. I am unable to find proper documentation or steps to do this. so please can anyone give me solution for this issue.
Thanks in advance.

**Comment by gtmills** [comment]
Hi @priyanka611, this is a good question for the mailing list or IRC, as it's not a bug or feature request. You can sign yourself up for the mailing list at https://lists.ozlabs.org/listinfo/openbmc
There is https://github.com/openbmc/openbmc-tools/blob/master/edtanous/rootfs_size.py 
It does take quiet a while to run.
