### ISSUE TITLE
Fails to power on due to FSI error

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#3477]

**Comment by sivassrr** [comment]
BMC Details:
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.6.0-rc1"
VERSION_ID="2.6.0-rc1-135-g16e11aa"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.6.0-rc1"
BUILD_ID="2.6.0-rc1"
OPENBMC_TARGET_MACHINE="witherspoon"
root@witherspoon:~# cat /etc/timestamp
20190201202932```

**Comment by sivassrr** [comment]
BMC File system error details 
![image](https://user-images.githubusercontent.com/19144129/52214009-a9d55480-28b6-11e9-897e-8e60b7a1f29a.png)

**Comment by sivassrr** [comment]
Journalctl output 
[failed2iplbmcfilesystemerror.txt](https://github.com/openbmc/openbmc/files/2828425/failed2iplbmcfilesystemerror.txt)

**Comment by sivassrr** [comment]
@matt pointed this error is due to FSI error. So renamed the title accordingly.

**Comment by spinler** [comment]
"Something bad" happened to that system.  Could probably stand to get its AC cycled.

**Comment by spinler** [comment]
The journal is mostly filled with REST logging, so there isn't a lot of history, but I can see a power off is basically happening right on top of the power on, which causes this.
There is nothing further that can be debugged here with the attached journal.
