### ISSUE TITLE
openbmc/openbmc refactoring for reference platforms

### ISSUE THREAD

**Issue by krtaylor** [openbmc/openbmc#3486]
Split out platform meta from openbmc common and move to different repos

**Comment by amboar** [comment]
What does this mean? We already have separate repos for various manufacturers. Is this an issue to implement a different set of mechanics for integrating those repos to perform a build?

Also, what reference platforms? Do we have one (or more)?

**Comment by krtaylor** [comment]
Universal reference platforms would be a good thing for the project, this is also the potential process of modularizing the common and platform specific parts of the project.

For example:
IPMI refactoring was a very good thing, but it broke other platforms. This would help ensure that a set of platforms would work before code will merge.
