### ISSUE TITLE
KCS bridge daemon should not write to the device file when call times out

### ISSUE THREAD

**Issue by kunyi731** [openbmc/openbmc#3489]
In KCS bridge daemon, when the internal timer expires and some operation is still pending, it attempts to set (context->expired) and then return 0xce to the host system. See https://github.com/openbmc/kcsbridge/blob/master/kcsbridged.c#L324

However it violates the IPMI spec by doing so. KCS state machine has strict requirements that only when in phase WAIT_READ can a BMC write to the shared buffer. As a result, the timeout response would never reach the host. See https://elixir.bootlin.com/linux/latest/source/drivers/char/ipmi/kcs_bmc.c#L353 for the kernel driver handling for reference.

**Comment by vijaykhemka** [comment]
I am seeing these timeout for less than a second where as timeout value is set as 5 sec. I see continuously screen rolling with timeout log.

**Comment by kunyi731** [comment]
> I am seeing these timeout for less than a second where as timeout value is set as 5 sec. I see continuously screen rolling with timeout log.

Could you be more specific on how to reproduce the issue in your situation? Having screen rolling might be an artifact of chunked outputs getting flushed out, and should generally not be correlated with precise timing..
