### ISSUE TITLE
Set host boot source from disk, how does it work for multiple disks?

### ISSUE THREAD

**Issue by manjo-git** [openbmc/openbmc#3490]
Host boot source from disk can be set as follows as per documentation I have come across. What if the host has multiple drives how does this setting handle multiple disks? Same question applies to network, how does setting boot source to 'Network' handle hosts with multiple NICs ?

Set Host Boot Source from Disk
curl -c cjar -b cjar -k -H "Content-Type: application/json" -X PUT -d '{"data": "xyz.openbmc_project.Control.Boot.Source.Sources.Disk"}' https://${bmc_ip}/xyz/openbmc_project/control/host0/boot/attr/BootSource

**Comment by mdmillerii** [comment]
That would be up to the host firmware.

While the REST api is agnostic to the interface, the current options are based around what IPMI can transport and the host can ask of the setting via IPMI.

As support for richer communications is added the setting choices may be extended over time.
