### ISSUE TITLE
KVM over IP: webui, schema

### ISSUE THREAD

**Issue by krtaylor** [openbmc/openbmc#3491]
Finish up KVM over IP - webui and schema

**Comment by huanghai123456** [comment]
请问配置KVM才可以在WEB界面使用

**Comment by geissonator** [comment]
Last patch for this was https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/10268. I think we can close this one out, may need some documentation on where to go in web UI @gtmills ?

**Comment by gtmills** [comment]
Yeah working on the GUI. Closing.
