### ISSUE TITLE
Removal of Python

### ISSUE THREAD

**Issue by krtaylor** [openbmc/openbmc#3492]
Finish up migrating off and removing Python for footprint reduction

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/q/topic:%22rmpython%22+(status:open%20OR%20status:merged) was what did this in the end. Default is no python in systems like witherspoon and romulus.

**Comment by geissonator** [comment]
@mine260309 how we looking for Romulus?

**Comment by mine260309** [comment]
Just submitted https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/21208, with that, we do not have any python services.
But it's noticed that the python files in `/usr/lib/python2.7` are still there.

**Comment by geissonator** [comment]
This is complete, by default python is not required for the meta-phosphor layer and it's defaults. This is not a guarantee that all systems are python free, but the capability is now there and  has been done on all meta-ibm systems.
