### ISSUE TITLE
phosphor-ipmi-host: the DBus call timeout is too long in most cases

### ISSUE THREAD

**Issue by kunyi731** [openbmc/openbmc#3494]
There are a few DBus calls in phosphor-ipmi-host to various identities. e.g.

https://github.com/openbmc/phosphor-host-ipmid/blob/194375f2676715a0e0697bab63234a4efe39fb96/selutility.cpp#L56
https://github.com/openbmc/phosphor-host-ipmid/blob/583171207c4f9a091abe3f867cc415e7f9aa514b/utils.cpp#L51
https://github.com/openbmc/phosphor-host-ipmid/blob/4c0080287f2bb19ecfbe5cdd4a334f8769e7d0cd/settings.cpp#L32
https://github.com/openbmc/phosphor-host-ipmid/blob/118907ed5aff8ad5037f98bf8699c5105781e4dd/app/watchdog_service.cpp#L41
https://github.com/openbmc/phosphor-host-ipmid/blob/4c0080287f2bb19ecfbe5cdd4a334f8769e7d0cd/sensordatahandler.cpp#L59
https://github.com/openbmc/phosphor-host-ipmid/blob/4e1df0895e0664ca6f89321e6d600b8227b7475e/storagehandler.cpp#L373

Since the timeout param is not specified, they will use the default value, which is 25s if not configured in the systemd configuration file.

It turns out this timeout is too long than ideal, since the other pieces in the IPMI stack have much smaller timeout values. For example, the BTbridge/KCSbridge has a timeout of 5s https://github.com/openbmc/btbridge/blob/master/btbridged.c#L43. It is unnecessary to let IPMId getting blocked on waiting for DBus replies.

One failure case we observed on real hardware: when a hwmon kernel driver read() operation times out consistently, the long DBus call timeout in IPMId causes it to be always blocked on waiting for DBus replies, which makes all other IPMI requests to fail, including the essential watchdog commands.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/18928> utils: Use 5s timeout for DBus get/set property calls
Resolves:  #3494 phosphor-ipmi-host: the DBus call timeout is too long in most cases
