### ISSUE TITLE
Redfish configuration backup and restore function

### ISSUE THREAD

**Issue by krtaylor** [openbmc/openbmc#3500]
Design: 
https://gerrit.openbmc-project.xyz/#/c/openbmc/docs/+/18163/

**Comment by geissonator** [comment]
This has been queued up for discussion with DMTF but it will not be making the 2.7 release.

**Comment by krtaylor** [comment]
Moving to wiki, as per release planning

**Comment by AlexanderAmelkin** [comment]
Any progress on this?

**Comment by AlexanderAmelkin** [comment]
I dont' think it's ready to be closed.

**Comment by geissonator** [comment]
Any luck getting this defined with DMTF @gtmills ?

**Comment by gtmills** [comment]
> Any luck getting this defined with DMTF @gtmills ?

No super low on my priority of things to drive in. Not sure if I will ever get there so if someone needs will have to drive in.

**Comment by AlexanderAmelkin** [comment]
I'd prefer to keep this open

**Comment by edtanous** [comment]
Next steps on this still involve engaging with Redfish to add schema support for backup/restore.  Is anyone actively working on this to keep it open?

**Comment by AlexanderAmelkin** [comment]
We are actively working on this feature in general, but hasn't yet gotten to the Redfish schema part.

**Comment by williamspatrick** [comment]
Feature request for an abandoned design that hasn't been touched in a few years.  Closing.
