### ISSUE TITLE
Witherspoon: BMC kernel 5.0 Failed opening GPIO device

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#3508]
New BMC kernle 5.0 

Driver:

VERSION_ID="2.7.0-dev-135-gb0afcc1"
Linux witherspoon 5.0.3-b94b74e8b52db91fe4e99e0bb481ec8bf2b5b47c #1 Thu Mar 21 13:38:45 UTC 2019 armv6l GNU/Linux

```
Mar 21 19:24:27 witherspoon witherspoon-pseq-monitor[1798]: The operation failed internally.
Mar 21 19:24:28 witherspoon witherspoon-pseq-monitor[1798]: Failed opening GPIO device
Mar 21 19:24:28 witherspoon witherspoon-pseq-monitor[1798]: The operation failed internally.
Mar 21 19:24:28 witherspoon witherspoon-pseq-monitor[1798]: Failed opening GPIO device
Mar 21 19:24:28 witherspoon witherspoon-pseq-monitor[1798]: The operation failed internally.
```
Flooding the journald.. 

There are OCC related bugs too but that has already in review..
- [ ] https://gerrit.openbmc-project.xyz/c/openbmc/openpower-occ-control/+/19404

@spinler to fix  the ones that have to do with the i2c device paths.

**Comment by spinler** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/witherspoon-pfault-analysis/+/19548
