### ISSUE TITLE
Core - Migrate existing code to new Core infrastructure

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#351]

**Comment by geissonator** [comment]
Things to discuss
- Do any of the sub-epics need more points carved off from this?  @dkodihal #997 or #1465 maybe?
- Some point for the host ipmid refactor work?  Or maybe already covered in #779 
- Any remaining major areas that need points?
- Recommendation: Answer above questions, reduce this to 13 for misc function

**Comment by geissonator** [comment]
Meeting minutes
- Overall goal is eliminate gdbus, .exe applications
- Talk with Deepak on above questions, carve off points if needed
- Mapper in c++?  Make phase 6, 5 pts
- Put remaining 13 points in phase 6
