### ISSUE TITLE
Parse hostboot eSEL and convert to openbmc elog format

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#352]
Parse eSEL into OpenBMC native structure

**Comment by vishwabmc** [comment]
@anoo1 how are we consuming the parsed data ?. Do you have more info on this ?

**Comment by geissonator** [comment]
Take existing code which takes hostboot eSEL as input and parses into our own structure and generates our new event dbus object.
Convert to story, make 5 pts, put under error log epic

**Comment by anoo1** [comment]
Port existing functionality from phosphor-event to phosphor-logging and use sdbusplus bindings:
- [ ] Create new sdbusplus methods for IPMI to call to create and retrieve SEL information.
- [ ] Create associations using new association object(?)
- [ ] Create delete method using new object manager.
- [ ] Cache and retrieve logs using new property cacher.
- [ ] Port handling of SEL reservation id, store partial SELs, and create an event dbus object.
- [ ] Update IPMI to call new methods.

Export eSEL information:
- [ ] Gather requirements on what eSEL data and format would the user need access to.

**Comment by geissonator** [comment]
Notes from sprint planning:
- We have plans to provide SEL via IPMI, we should do this, not REST, ipmi get sel #443 is related
so we should move hostboot SEL/eSEL to new phosphor-logging
- We provide REST api to extract phosphor-logging events which contain the eSEL, then we run parsing tools to get eSEL info.
- How do we want to distinguish between host and bmc errors?  Unique name for host errors.
- New object manager to delete errors
- Need separate story for associations
- Focus on transferring what we have over to new stuff and using sdbusplus
