### ISSUE TITLE
cmake: Should not look for tooling in host system paths+

### ISSUE THREAD

**Issue by wak-google** [openbmc/openbmc#3523]
This behavior is hardcoded in cmake at https://github.com/Kitware/CMake/blob/v3.14.1/Modules/Platform/UnixPaths.cmake and breaks our libdnf-native builds if there is a local swig2.0 installed. It should never be looking at host tools.

**Comment by mdmillerii** [comment]
the changelog says they are prefixing sysroot variables, which would imply teaching bitbake to pass that ...

**Comment by wak-google** [comment]
Well, you actually can't do that because sysroot is the target platform and find_program is looking for host tools which are inherently not in the sysroot.
