### ISSUE TITLE
How to decide which NIC to set ntpservers on?

### ISSUE THREAD

**Issue by xuweibj** [openbmc/openbmc#3527]
The scenario is like this:
Have 2 NICs on openbmc
1. eth0: IP is 169.254.206.172
2. eth0_1: IP is 172.16.3.36 -- set

Now want to set ntpservers for openbmc, which NIC we should set on?
It seems that we set ntpservers on eth0_1, which we set our IP on, but it does not work. But set on eth0, it works.
@gurevichmark  @whowutwut @zet809

**Comment by gurevichmark** [comment]
@xuweibj Do you know how to verify that ntpservers are working ?

**Comment by gurevichmark** [comment]
I connected to one of Mark P machines to look at the web interface and NTP Server panels:

![image](https://user-images.githubusercontent.com/16106630/56315826-bf70c100-6126-11e9-9b7a-f6b1f07f2f69.png)

Clicking "Add NTP Server" button:

![image](https://user-images.githubusercontent.com/16106630/56315916-03fc5c80-6127-11e9-8eb8-912534960e3c.png)

**Comment by xuweibj** [comment]
@gurevichmark , I don't know, so hope could get exact message here.

**Comment by Obihoernchen** [comment]
Set some wrong time manually and switch back to NTP, then check if time changes after node reboot.

**Comment by gurevichmark** [comment]
Used BMC Web Interface for `mid05tor12cn05` which has `eth0` and `eth0_11` to set NTP servers attribute.
The Web interface sets it to `eth0`, but our `rspconfig ntpservers` command sets it to `eth0_11`.
