### ISSUE TITLE
Milestone: RAS / MFG - LEDS

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#353]
Better LED management daemon

**Comment by vishwabmc** [comment]
@anoo1 Are we looking at lighting up a LED based on the errorlog contents ( the location code etc ? ). 
Also, are we looking at creating a table based on the instance paths that we get from the MRW ?

**Comment by geissonator** [comment]
Create 2 remaining stories
2 pts - Power Supplies
5 pts - Callout to LED assertion
Then take the 21 points off this epic.
