### ISSUE TITLE
ipmid does not support getHostNetworkData

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#3539]
running openbmc master (2.7.0-dev-546-g46cd1bf70) on an openpower machine:

```
 ipmid[944]: Unsupported parameter
 ipmid[944]: getHostNetworkData failed for get_sys_boot_options.
```

This old issue may be related: https://github.com/openbmc/openbmc/issues/2415

**Comment by sammj** [comment]
Indeed this returns an error:
```
> ipmitool -I lanplus -H w8.aus.stglabs.ibm.com -P 0penBmc raw 0x00 0x09 0x61 0x80 0x00
Unable to send RAW command (channel=0x0 netfn=0x0 lun=0x0 cmd=0x9 rsp=0xff): Unspecified error
```

However setting a network override and then checking again works:
```
└> ipmitool -I lanplus -H w8.aus.stglabs.ibm.com -P 0penBmc raw 0x00 0x09 0x61 0x80 0x00
 01 61 80 21 70 62 21 00 01 06 04 f4 52 14 f3 01
 df 00 01 0a 3d a1 42 10 0a 3d 02 01 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00
```

Dredging this up from my memory I think @shenki is correct and this is similar to https://github.com/openbmc/openbmc/issues/2415 - OpenBMC returns an error when it _should_ return a normal response but with the override field marked invalid or empty
