### ISSUE TITLE
RAS / MFG - Manufacturing / Characterization

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#354]
Need definition on requirements.
- pass through work
- reset to factory

**Comment by geissonator** [comment]
Sized big due to a lot of unknowns.  There will be things cronus wont be able to do that openbmc will need to do.  Reducing to 40 based on current data.

**Comment by geissonator** [comment]
OCC interfaces tracked under #345 
Factory Reset under #865 
BMC Dump under #868 
Power/Cooling under #343 #346 and #347 

Open Questions (and only potential remaining work)
- SBEFIFO pass through work required by openbmc?
- Cronus access to i2c devices while system booted (hwmon has devices bound).

Reduce this epic to 8pts to account for the above open items.

**Comment by geissonator** [comment]
No additional SBEFIFO work, mfg should not have to unbind any devices.  Reduce from 8 to 3.
