### ISSUE TITLE
SNMP: BMC is allowing to configure SNMP with out-of-range port

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#3552]
BMC is allowing to configure SNMP with out of range port.
Valid port range for SNMP configuration is 1-65535.
When we try to configure port 66000 that is invalid, BMC does not do any validation and add it.

**Comment by 229024527** [comment]
Hi can you provide me some example about how to use snmp with openbmc？Thanks

**Comment by ratagupt** [comment]
Currently openBMC supports only the SNMP trap functionality, It doesn't have the SNMP agent functionality.
What functionality you are looking for?

**Comment by prkatti1** [comment]
It is not doing port validation, even if we configure invalid port like 66000 it accepts the input and configures.
Expected result is, t has to throw and error.
