### ISSUE TITLE
how to Enable WebUI on ast2500-evb

### ISSUE THREAD

**Issue by michealylj1** [openbmc/openbmc#3554]
Ok ,sivassrr
At first can not login webui because have no bmcweb.socket in obmc system.
The nodejs-native do_compile fail because my npm have some problem
At last to login web ui again,need to appoint port number883: https://10.0.15.177:883
Used the meta-x86/meta-intel/meta-s2600wf

_Originally posted by @FrankRenn in https://github.com/openbmc/openbmc/issues/3334#issuecomment-410411986_

**Comment by michealylj1** [comment]
Hi FrankRenn,
At first can not login webui because have no bmcweb.socket in obmc system.
The nodejs-native do_compile fail because my npm have some problem
At last to login web ui again,need to appoint port number883: https://10.0.15.177:883
Used the meta-x86/meta-intel/meta-s2600wf
I just meet the same issue with you when I run openbmc in the chip "meta-evb-ast2500", Please tell me
how to add nginx service in obmc system?
how to enable bmcweb.socket in obmc system?
If I need to install nodejs in obmc system, how to do ?
Thanks,
Michael

**Comment by amboar** [comment]
This seems like questions for the mailing list, this isn't really a bug report or a feature request unless it's rephrased along the lines of "Enable WebUI on ast2500-evb".

**Comment by michealylj1** [comment]
![image](https://user-images.githubusercontent.com/46735287/58857390-b7211500-86d7-11e9-9214-55aa4388d842.png)

![image](https://user-images.githubusercontent.com/46735287/58857499-0404eb80-86d8-11e9-8091-41e93fa2d3e5.png)

**Comment by michealylj1** [comment]
But I can't open web GUI by the URL  https://10.2.1.200/ or https://10.2.1.200:883/

**Comment by SBoylan-Ircona** [comment]
Have you included phosphor-webui in your build? 

The basic build configuration for the EVB 2500 doesn't include the phosphor-webui package, which adds the front end web-ui interface. Have a [look here at how the meta-romulus](https://github.com/openbmc/openbmc/blob/master/meta-ibm/meta-romulus/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend) build includes it.

**Comment by michealylj1** [comment]
It works well after I enable "phosphor-webui". Thanks.
