### ISSUE TITLE
Power-on hours command increases the counter incorrectly

### ISSUE THREAD

**Issue by yongli3** [openbmc/openbmc#3556]
Based on IPMI spec and https://github.com/openbmc/openbmc/issues/2979, the POH counter should be increased after host power on.
But the current implementation is based on chassis poweron status.
@dkodihal @geissonator is any plan to fix this issue?

**Comment by geissonator** [comment]
They're really aren't a lot of use cases where the chassis is on but the host isn't running so not something that's really on our radar. @dkodihal do you remember the reason for tracking chassis vs. host?

**Comment by yongli3** [comment]
@vmauery FYI
