### ISSUE TITLE
what is the default of  PowerState HostState and ChassisState

### ISSUE THREAD

**Issue by FrankRenn** [openbmc/openbmc#3560]
This three State make me confuse, what is the default , and The connection between them is what.

Thanks alot

**Comment by geissonator** [comment]
OpenBMC has 3 independent objects that represent the state of, BMC, Chassis, and Host.

https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/BMC.interface.yaml

https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Chassis.interface.yaml

https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/State/Host.interface.yaml

Each has a state it can be, and a state you can request of it.

https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22461/1/designs/extended-host-software-state.md and https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/22358/1/designs/ipmi_and_redfish_chassis_control.md provide some background on them and some coming enhancements.

systemd is used for the relationships among them, you can get more info in https://github.com/openbmc/docs/blob/master/openbmc-systemd.md

In general this question is best for the mailing list or IRC.

**Comment by FrankRenn** [comment]
OK ,thanks
