### ISSUE TITLE
Mount failed in dual flash chips design

### ISSUE THREAD

**Issue by MichaelWang2017** [openbmc/openbmc#3566]
Hi all,
We have a board that uses two BMC flash chips (flash0 uses CS0, flash1 uses CS1) and stores the same image. 
The dts partition configuration is as follows:
![dts](https://user-images.githubusercontent.com/34836465/60230126-ea1a8b00-98c8-11e9-8284-60ccc207650d.png)
openbmc-flash-layout-inspur-64MB.dtsi:
![flash0](https://user-images.githubusercontent.com/34836465/60230509-0caca400-98c9-11e9-9a0f-d25e88854a54.png)
alt-flash-layout-inspur-64MB.dtsi:
![flash1](https://user-images.githubusercontent.com/34836465/60230611-17ffcf80-98c9-11e9-8caf-5848f90aabda.png)
In addition, I modified _obmc-init.sh_ as follows:
![init1](https://user-images.githubusercontent.com/34836465/60230789-b68c3080-98c9-11e9-9230-df2a8a8ad6d2.png)
![init2](https://user-images.githubusercontent.com/34836465/60230794-bb50e480-98c9-11e9-8f2f-00ef0c1f3503.png)

The problem encountered is that if only one flash chip is placed, either flash0 or flash1, the following problems will be encountered:
![????_20190627104131](https://user-images.githubusercontent.com/34836465/60229497-ad4e9400-98c8-11e9-9297-2689208e8c7c.jpg)

**Comment by mine260309** [comment]
You should be able to enter the password (default `0penBmc`) and get a root shell, then you should be able to see what kind of mtd devices there are.

**Comment by MichaelWang2017** [comment]
Okay, Thank you @mine260309, I will check it later.
In addition, I tried to comment out the flash0 in the dts file as follows:
![dts1](https://user-images.githubusercontent.com/34836465/60232249-99a62c00-98ce-11e9-9bf3-5139d2090867.png)

My understanding is that at this time, regardless of whether mount is successful or not, aspeed-smc.c should at least correctly initialize flash1, but I found that flash1 was not properly initialized:
![sss](https://user-images.githubusercontent.com/34836465/60232272-b17db000-98ce-11e9-9598-38e1c99b90f3.png)

**Comment by mdmillerii** [comment]
The SMC has a configurable window for each chip select.  I'm sure the code has not been tested when skipping chip selects, and not sure what the hardware would do if chip select 0 and 1 had the same window.  I'd start by putting the first chip back in the device tree.

For some reason your JEDEC id read back as `00 00 00` (unless there are some off the right side of the picture) so the chip is not being found.

Note: be aware that the watchdog toggle will swap chipselect 0 and 1 each time it triggers, so be aware the label are dependent on the state of the watchdog.

**Comment by mdmillerii** [comment]
Upon review after others commented, the scenerio is not supported by the driver initialization but perhaps should be.

The current linux driver for the spi interface (`drivers/mtd/spi-nor/aspeed-smc.c`) requires each described flash chip to be present and respond with jedec id when probed or will return -ENODEV for the whole controller.  (The 2500 has 3 controllers - 1 for the SOC and two for the host; the 2400 has 1 host and 1 SOC).
