### ISSUE TITLE
sdcard detection fails in ast2520 with openbmc.

### ISSUE THREAD

**Issue by pranav-shivalingaiah** [openbmc/openbmc#3568]
Hi,

We are facing SD card detection issue in OpenBMC.
Please let us which SD card driver to be used and how to configure it.
Please help.

Regards,
Pranav

**Comment by amboar** [comment]
Hello @pranav-shivalingaiah - the SD card driver is in flux a bit, we're working to upstream it at the moment. I'll take a look at the code to see if there's anything obviously wrong with it.

**Comment by alandvbh** [comment]
Did you figure out how to do this.?
