### ISSUE TITLE
Unable to modifyonly specific entry from staticnameservers from BMC

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#3572]
Unable to keep old value when we try to modify any of the staticnameserver entry from BMC.
It is modifying all entries.

```curl -k -H "X-Auth-Token: $bmc_token" -X PATCH -D patch.txt -d '{"StaticNameServers": ["{}","3.3.3.7"]}' https://${bmc}/redfish/v1/Managers/bmc/EthernetInterfaces/eth0```
 
```curl -k -H "X-Auth-Token: $bmc_token" -X GET https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0```
```  "NameServers": [
    "{}",
    "3.3.3.7"
  ],
  "SpeedMbps": 0,
  "StaticNameServers": [
    "null",
    "3.3.3.7"
  ],
```

**Comment by ratagupt** [comment]
@prkatti1 Please open the issue under bmcweb repo.

**Comment by prkatti1** [comment]
@ratagupt closing this, will be tracked via https://github.com/openbmc/bmcweb/issues/93
