### ISSUE TITLE
Lenovo sr650 installation openbmc consulting

### ISSUE THREAD

**Issue by HLDYZ** [openbmc/openbmc#3580]
How to set up openbmc on Lenovo server SR650, bmc chip model (ASPEED PILOT 4) has a guiding process, thank you!

**Comment by bradbishop** [comment]
hi @HLDYZ 

Please send questions to the project mailing list:
https://lists.ozlabs.org/listinfo/openbmc/

The github issue tracker is for reporting bugs.  Thanks for understanding!

**Comment by chetan3061** [comment]
@HLDYZ can we install openbmc in SR655 server

**Comment by amboar** [comment]
@chetan3061 as @bradbishop mentioned above support questions are best asked in places other than github issues.
