### ISSUE TITLE
Move to new assocations interface and drop support for old interface

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3584]
We currently support both assocations interfaces.
New:
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Association/Definitions.interface.yaml
Old:
https://github.com/openbmc/phosphor-logging/blob/master/org/openbmc/Associations.interface.yaml

Would be nice to move everything to the new interface. 
See https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/23876
See https://github.com/openbmc/docs/blob/master/object-mapper.md#associations

**Comment by spinler** [comment]
@gtmills maybe put these in a ReadyForDev issue over in our repo and they may get done.  Otherwise, stalebot will probably get  this one.
