### ISSUE TITLE
x86-power-control not working with latest OpenBMC version

### ISSUE THREAD

**Issue by MaxPower2005** [openbmc/openbmc#3586]
This x86-power-control package uses the obsolete system manager (obmc-mgr-system) https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/18659/ to access GPIO.

Is there a version compatible with the latest OpenBMC software version?

**Comment by geissonator** [comment]
Issue moved to [openbmc/x86-power-control #2](https://github.com/openbmc/x86-power-control/issues/2) via [**ZenHub**](https://www.zenhub.com/)
