### ISSUE TITLE
How to add enable/disable ability to a sensor ?

### ISSUE THREAD

**Issue by hashtag-amar** [openbmc/openbmc#3592]
I am new to openBMC. I need to make PSU power sensor to work only when host is powered ON else not. In other words, i need to add some ability to the sensor (psu_pout) to be toggled as enable/disable.

PS: Please provide the solution with the path too (if possible).

Thanks in advance.

**Comment by geissonator** [comment]
We try to only report bugs in issues. Best to use mailing list or IRC for questions - https://github.com/openbmc/openbmc#contact

**Comment by hashtag-amar** [comment]
Okay. Thanks for the reply.

**Comment by ThuBaNguyen** [comment]
Any update in this issue?
