### ISSUE TITLE
Feature Request: Extend OpenBMC to allow NVRAM writes with tunable parameters for configuration of minimum fan PWM

### ISSUE THREAD

**Issue by ToxicDragon** [openbmc/openbmc#3595]
As is currently the problem with Raptor Computing Systems BLACKBIRD motherboard (c.f. https://www.raptorcs.com/content/BK1MB1/intro.html), certain fan parameters need to be specified before compilation of the BMC. See the following file for zones definitions: https://git.raptorcs.com/git/talos-openbmc/tree/meta-rcs/meta-talos/recipes-phosphor/fans/phosphor-fan-control-zone-config-native/zones.yaml

However, this situation is kind of unsatisfactory, because these settings may only apply to specific fans. As a test, I used different fans from Noctua which apparently responded differently to the specified default configuration of the BMC.

Therefore, I may request a feature to have some kind of "Controls" / tunable parameters that may be set while the BMC is running (so no need for recompilation).

I consider this request in general for the start of a discussion. Would be nice, if this feature were to be implemented in the not so far future :)

Best regards,
Christian

**Comment by ToxicDragon** [comment]
Even better would be some kind of auto-calibration that depending on the utilized fan (just dreaming ;) )...

**Comment by madscientist159** [comment]
I see this in several phases:
1.) Adding some kind of runtime-configurable persistent parameter store to OpenBMC (this may already be in place, but it's hard to tell in the tangle of DBUS services)
2.) Extending the IPMI interface to allow parameter discovery and authenticated parameter read/write (restrict write to IPMI superuser) along with a separate parameter reload IPMI command
3.) Adding a configuration menu to Petitboot to expose these controls in a user-friendly manner

**Comment by bradbishop** [comment]
at 1:59 PM, Timothy Pearson <notifications@github.com> wrote:

> I see this in several phases:
> 1.) Adding some kind of runtime-configurable persistent parameter store  
> to OpenBMC

phosphor-settings-manager probably works for this.  That gets you the  
parameter on dbus, persisted, but you'd still need to wire up a user  
interface (OEM IPMI or redfish).

> (this may already be in place, but it's hard to tell in the tangle of  
> DBUS services)

We definitely need some kind of map to help navigate all the code out there  
:-)

**Comment by msbarth** [comment]
There are a few ways that I've considered to enable tuning/overriding parameters within fan control on a live BMC such as converting the yaml over to json and having that as input to the executable, implementing fan control to host even parameters on a set of dbus interfaces for each zone, etc.. 

I'd be interested to see your design proposal on how to handle this.

An initial issue was opened awhile ago for tracking something similar to what you describe with a few general requirements I noted.  https://github.com/ibm-openbmc/dev/issues/115

**Comment by ToxicDragon** [comment]
Still needed :)

**Comment by ToxicDragon** [comment]
Still needed :)

**Comment by msbarth** [comment]
FWIW, phosphor-fan-control is in the works of being converted to use runtime JSON configuration files. This would allow them to be changed/overridden directly on the BMC without recompiling. https://github.com/ibm-openbmc/dev/issues/1363

**Comment by em-winterschon** [comment]
Looking forward to this being implemented. Is there an approximate ETA?

**Comment by msbarth** [comment]
I've been working on this as time permits, but it should all be in review by June

**Comment by edtanous** [comment]
This was heavily discussed on the mailing list at the time, and runtime support of fan control configuration parameters has been supported by phosphor-pid-control for quite a while.  They are writable through bmcwebs Redfish OpenBMC manager schema.

Closing as this is already supported.

**Comment by williamspatrick** [comment]
> runtime support of fan control configuration parameters has been supported by phosphor-pid-control for quite a while

Does phosphor-pid-control persist those?

(Not that I think we should reopen this in either case.)

**Comment by edtanous** [comment]
Entity-manager persists the settings.
