### ISSUE TITLE
about webui for ast2500

### ISSUE THREAD

**Issue by linuxchien** [openbmc/openbmc#3597]
How to add webui in ast2500 project?

**Comment by JesusPhish** [comment]
You need to include it as part of your packagegroups. You can include if via a bbappend file, similar to this [one for Romulus](https://github.com/openbmc/openbmc/blob/master/meta-ibm/meta-romulus/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend).

**Comment by geissonator** [comment]
Please use the mailing list of IRC for questions like this - https://github.com/openbmc/openbmc#contact
