### ISSUE TITLE
How to build it via ZYNQ

### ISSUE THREAD

**Issue by onjustgo** [openbmc/openbmc#3603]
I get an error when I set the 'TEMPLATECONF' to 'meta-evb/meta-evb-enclustra/meta-evb-zx3-pm3/conf'.
1.Branch of master:
ERROR: Layer xilinx is not compatible with the core layer which only supports these series: warrior (layer is compatible with sumo thud)
2.branch of thud:
ERROR: Layer evb-enclustra is not compatible with the core layer which only supports these series: thud (layer is compatible with sumo)
3.branch of warrior
ERROR: Layer xilinx is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud sumo)

**Comment by amboar** [comment]
@bradbishop and @pstrinkle are probably the best people to help out here.
