### ISSUE TITLE
How I can read the FRU info of the server card.

### ISSUE THREAD

**Issue by KumarThangavel** [openbmc/openbmc#3618]
Hi All,

I am new to openbmc. I am started porting openbmc features to new hardware. 
So, I want to add support for FRUID EEPROM.  FRUID contents should be available as dbus objects. What changes needs to done in the application side. 

Please provide the steps or suggestions to follow.  

Thanks,
Kumar.

**Comment by geissonator** [comment]
Welcome. This seems more like a IRC or mailing list question then github issue. Please see https://github.com/openbmc/openbmc#contact for contact info.
