### ISSUE TITLE
Without the lpc interface, can the CPU communicate with bmc via the i2c interface for ipmi communication?

### ISSUE THREAD

**Issue by grace414385621** [openbmc/openbmc#3620]
Hello everyone! Our project currently has a tough problem. Due to hardware reasons, ast2400 cannot communicate with the cpu through the LPC interface. However, the current cpu has an i2c interface directly connected to the ast2400 i2c interface. According to the current version of the openbmc code, can Cpu and ast2400 communicate with ipmi via i2c bus?  I only found the solution for LPC and BT.

**Comment by geissonator** [comment]
Welcome. This seems more like a IRC or mailing list question then github issue. Please see https://github.com/openbmc/openbmc#contact for contact info.
