### ISSUE TITLE
Unable to start bitbake server with "meta-evb-zx3-pm3"

### ISSUE THREAD

**Issue by onjustgo** [openbmc/openbmc#3623]
**Note on Bugs**
I get an error when I set the 'TEMPLATECONF' to 'meta-evb/meta-evb-enclustra/meta-evb-zx3-pm3/conf' in branch master.

**Unexpected behavior you saw**
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/ubu/openbmc-master/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 6244 at 2019-10-23 11:18:49.590029 ---
ERROR: Layer xilinx is not compatible with the core layer which only supports these series: zeus (layer is compatible with warrior)

**Comment by geissonator** [comment]
@bradbishop looks like both meta-xilinx and meta-evb probably need an update to zeus?

**Comment by bradbishop** [comment]
Yes.  I would accept patches that do that.

**Comment by dilraj-n** [comment]
When I tried to build. I got the following error
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session openbmc/xilinx-build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 15393 at 2020-06-03 14:40:39.829943 ---
ERROR: Layer xilinx is not compatible with the core layer which only supports these series: dunfell gatesgarth (layer is compatible with warrior)
