### ISSUE TITLE
How to enable the net-snmp service feature in the project construction?

### ISSUE THREAD

**Issue by ddfb2004** [openbmc/openbmc#3637]
Hi，I want to use the snmpd service to receive the snmp package from the client. After the construction,  although the net-snmp package has been  builded, the snmpd service and the related files (e.g. snmpd.conf, snmpd) have not been included in the image file.
How to enable the net-snmp service feature in the project construction? Could you give me a configuration method to deal with this?

**To Reproduce**
1. Follow the READM.md instructions
2. export TEMPLATECONF=meta-ibm/meta-palmetto/conf
    . openbmc-env
    bitbake obmc-phosphor-image
3. there is not any relating files about snmpd service, in the directory of rootfs
myproject name\obmc-phosphor-image\1.0-r0\rootfs\

**Screenshots**
1. the net-snmp directory
![图片](https://user-images.githubusercontent.com/9268792/70421011-e3ad5380-1aa3-11ea-98eb-d38d88867761.png)
2. the builded net-snmp directory
![图片](https://user-images.githubusercontent.com/9268792/70421225-5fa79b80-1aa4-11ea-89a8-f31cc1715e16.png)
3. there is not any relating files about snmpd service, in the directory of rootfs
![图片](https://user-images.githubusercontent.com/9268792/70421376-b0b78f80-1aa4-11ea-9664-b6244d043239.png)

**OpenBMC Information:**
 - /etc/os-release:
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 - uname -a:
Linux zd-tech-xa 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Any additional patches or changes:
using the latest version of openbmc

**Comment by geissonator** [comment]
@ratagupt any advice? I doubt we packaged snmp into palmetto? Is it in Romulus?

**Comment by nest1ing** [comment]
You could add `net-snmp-server-snmpd` package to your firmware image.
E.g. for palmetto it might be done by editing the `meta-ibm/meta-palmetto/reciepes-phosphor/images/obmc-phosphor-image.bbappend`:
```
OBMC_IMAGE_EXTRA_INSTALL_append_palmetto = " mbox net-snmp-server-snmpd"
```

**Comment by ddfb2004** [comment]
Thanks for your suggestions, it worked well, I found the snmpd in the rootfs. Now I will close the issue.
