### ISSUE TITLE
IP-KVM not working

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#3642]
The IP-KVM is not working on master, that it shows a blank page on OpenBMC WebUI.

The known good version is 90a837f71a2a8e4ad3ab8d626605d9204705a5ca
But I do not know which revision starts to fail, and not sure which component breaks it.

**Comment by geissonator** [comment]
@eddiejames can you take a look?

**Comment by eddiejames** [comment]
obmc-ikvm can't seem to connect to the systemd socket. @gtmills may want to look

**Comment by gtmills** [comment]
@mine260309 I think https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/29541 should have fixed this

**Comment by mdmillerii** [comment]
That fix changes from IPv6 loopback to IPv4 loopback address.

**Comment by XiaochaoMa** [comment]
Test:
Take the above patch. Use the Chrome browser to link the BMC and successfully start the KVM function. The boot process shows normal.
