### ISSUE TITLE
Boot on AST2500 EVB

### ISSUE THREAD

**Issue by kc8apf** [openbmc/openbmc#366]
An image built with TEMPLATECONF=meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf should successfully boot to a login shell on an AST2500 EVB.

**Comment by kc8apf** [comment]
openbmc/u-boot#7 sets the u-boot default boot args so console goes to ttyS4 (debug UART)
openbmc/linux#93 adds the flash layout to aspeed-ast2500-evb.dts so the rootfs can be found

With those merged, an image built from openbmc/openbmc master should boot to a login shell.

**Comment by williamspatrick** [comment]
This is a tracker issue so not assigning a size estimate.

**Comment by legoater** [comment]
It does boot correctly but we need the n/w driver fixes regarding the ring buffer bits in the 4.6 kernel.

**Comment by legoater** [comment]
Here is the branch I use https://github.com/legoater/linux/commits/openbmc-4.6. Network works fine.

**Comment by legoater** [comment]
I just updated the g5 defconfig in my linux branch. Some more configs are required to boot an evb-ast2500 image. With these, you should be able to flash and successfully boot the board.

**Comment by GHF** [comment]
@legoater if you build with bitbake, it overrides the defconfig with its own. I haven't tried this one verbatim but it should work. https://github.com/openbmc/openbmc/blob/master/meta-openbmc-bsp/meta-aspeed/meta-ast2500/recipes-kernel/linux/linux-obmc/defconfig

**Comment by legoater** [comment]
@GHF yes. I tend to put everything in the linux tree but it is not the way to go. The defconfig is correct under meta-ast2500.

**Comment by shenki** [comment]
The device tree changes are made with the dev-4.7 kernel. Please reopen if you still experience issues.
