### ISSUE TITLE
power control by web

### ISSUE THREAD

**Issue by kjh-lk** [openbmc/openbmc#3673]
How can I control the server on and off from a web page

**Comment by qthangnp** [comment]
You can control by accessing WebUI -> Control -> Server power operations.
In that page, you can control the Host server On/Off/Reboot.

**Comment by feitiantutu** [comment]
how to config code

**Comment by mdmillerii** [comment]
Please review our documentation repository.  Development tutorials folder linked below.

https://github.com/openbmc/docs/blob/master/development/README.md

Please consider using our mailing list described in that repository to ask questions.
