### ISSUE TITLE
How to use SPI1 ?

### ISSUE THREAD

**Issue by AlooGS** [openbmc/openbmc#3681]
Where is set 0x2 on barreleye and palmetto ? The FMC is used for BMC, so I want to use the  the SPI Flash contoller is 0x1E630000 on BMC system to update the host BIOS, but set SCU70[13:12] = 1 on uboot flash_init(), uboot will hang :-(

**Comment by AlooGS** [comment]
![1595990328(1)](https://user-images.githubusercontent.com/13912225/88750387-018d0d00-d188-11ea-95a9-c789d8595abf.jpg)
 

I want to use th blue.

**Comment by solonfan** [comment]
Hi,AlooGS!

1.Check the HW schematic first,which type are your board is using.
<img width="467" alt="BIOSFLASHCON" src="https://user-images.githubusercontent.com/15608567/89369492-d323aa80-d710-11ea-9e14-94ec9a411f34.PNG">

2. Switching to Blue(Master SPI mode) from Red( SPI bypass mode) should later than flash_init,BMC need init&booting finished at bypass mode.

3.You can make BMC run into uboot cmdline mode,there is memory etc cmd to r/w register for test your purpose.

4.Or run into kernel.modify the flash device file-/dev/host_spi_flash0.Modify it to MASTER_MODE.Then acess the mtd device to flash your BIOS image.

Thanks,
SolonFan
