### ISSUE TITLE
OpenBMC supported operating systems and browsers.

### ISSUE THREAD

**Issue by Pavan-0** [openbmc/openbmc#3688]
Hi,
Is there a list of Operating systems and minimal version that can be used for openbmc webui and also the same thing for the Browser / minimal version that are qualified?

**Comment by solonfan** [comment]
Hi,Bro!

There is a test toaster for your reference!
https://github.com/openbmc/openbmc/tree/4feb727cd6b77a68bdaca63e121b378d814f5eaf/poky/bitbake/lib/toaster/tests/browser

It mentioned some browser info list
Available drivers:

* chrome (default)
* firefox
* marionette (for newer Firefoxes)
* ie
* phantomjs (deprecated)
* remote

Thanks,
SolonFan
