### ISSUE TITLE
wrong offset in openbmc-flash-layout.dtsi

### ISSUE THREAD

**Issue by zkxz** [openbmc/openbmc#3689]
**Unexpected behavior you saw**
When I try to change the flash layout for my system, I see this section below in the flash layout device tree file openbmc/linux/arch/arm/boot/dts/openbmc-flash-layout.dtsi (sorry for I can't find the file link here because github limits 1000 files for a folder to be shown on this website),
```
        rofs@c0000 {
                reg = <0x4c0000 0x1740000>;
                label = "rofs";
        };

```
It should be "rofs@**4c0000**" based on the device tree definition. Was it a typo or on purpose?

**Expected behavior**
It should be "rofs@**4c0000**" based on the device tree definition.

**To Reproduce**
just open that file and you will see it.

**Screenshots**
none

**OpenBMC Information:**
common problem

**Additional context**
none

**Comment by zkxz** [comment]
@mdmillerii Thank you for the hint about the link and confirm of the typo. I'm new here, do I need to follow any special procedure to submit the patch to openbmc kernel repo? I can't find it on https://gerrit.openbmc-project.xyz.

**Comment by shenki** [comment]
The file is upstream. If you would like to fix it, please send a patch according to the Linux kernel patch submission rules:

https://www.kernel.org/doc/html/latest/process/submitting-patches.html

Use `git format-patch` to turn your commit into a patch, `scripts/get_maintainer.pl` to discover who to send it to, and `git send-email` to send that patch.

**Comment by zkxz** [comment]
@shenki Thank you for the instructions. Will update here once I done it.

**Comment by zkxz** [comment]
The kernel patch have been emailed for review: https://lkml.org/lkml/2020/8/28/61
