### ISSUE TITLE
Feature 'xyz' not found, but KERNEL_DANGLING_FEATURES_WARN_ONLY

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#3692]
With #3690 we set a warning flag to handle a new upstream poky "feature" in the kernel-yocto.bbclass. This issue is to track the needed refactor to get these kernel features out of the meta-phosphor layer and into the appropriate meta-aspeed and/or meta-nuvoton layers.

You get warnings like this when building now:
```
WARNING: linux-aspeed-5.8.5+gitAUTOINC+0dd0c8c492-r0 do_kernel_configme: Feature 'phosphor-gpio-keys' not found, but KERNEL_DANGLING_FEATURES_WARN_ONLY is set
WARNING: linux-aspeed-5.8.5+gitAUTOINC+0dd0c8c492-r0 do_kernel_configme: This may cause runtime issues, dropping feature and allowing configuration to continue
WARNING: linux-aspeed-5.8.5+gitAUTOINC+0dd0c8c492-r0 do_kernel_configme: Feature 'phosphor-vlan' not found, but KERNEL_DANGLING_FEATURES_WARN_ONLY is set
WARNING: linux-aspeed-5.8.5+gitAUTOINC+0dd0c8c492-r0 do_kernel_configme: This may cause runtime issues, dropping feature and allowing configuration to continue
```

**Comment by geissonator** [comment]
@amboar @shenki

**Comment by geissonator** [comment]
The features in question come from the meta-phosphor/aspeed-layer/ and meta-phosphor/nuvoton-layer/ sub directories.

**Comment by shenki** [comment]
AIUI, these features should have been placed in meta-aspeed and then the various machines can enable them from their layers.

We should make sure that this is the case, and put up reviews with each of the features. I suspect some are no longer required.
