### ISSUE TITLE
Fan control - Air cool vs Water cool policies.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#370]
Need to ensure we support different fan policies for air cooled vs water cooled.  On Witherspoon this will be controlled via a jumper.  Other systems may want a static MRW setting or a backplane VPD setting.

**Comment by msbarth** [comment]
- [ ] Thermal team define water cooled zone & floor values(tables)
- [ ] Add water cooled zone & floor values(tables)
- [ ] Interface/read jumper(GPIO?)
- [ ] Initialize/set zone & floor application data to water cooled values when jumper set

**Comment by bjwyman** [comment]
- [ ] Move zone, table, definitions and values to a new story.
- [ ] Define new interface for CoolingType
- [ ] Code to read jumper GPIO for water cooled or not.
- [ ] Update CoolingType property to indicate if water cooled or not

**Comment by bjwyman** [comment]
Created openbmc/openbmc#1371 for the cooling zone tables and values.

**Comment by bjwyman** [comment]
Needs #1387

**Comment by bjwyman** [comment]
Recipes:
https://gerrit.openbmc-project.xyz/#/c/3990/

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/3991 Create recipe files for phosphor-cooling-type
Resolves #370 Fan control - Air cool vs Water cool policies.
