### ISSUE TITLE
restapi factory reset "description": "org.freedesktop.DBus.Error.NoReply"

### ISSUE THREAD

**Issue by kingzmm** [openbmc/openbmc#3708]
factory reset error
{
  "data": {
    "description": "org.freedesktop.DBus.Error.NoReply"
  },
  "message": "Remote peer disconnected",
  "status": "error"
}

**Comment by mdmillerii** [comment]
Are you noting that you are getting this error?

Note that getting a reply to a reset is inherently racy because performing the reset involves loosing all state.  There have been hacks to insert a short delay for the ack to make it back to the client in some cases (possibly reboot BMC vs this factory reset activation).

**Comment by kingzmm** [comment]
How to solve this problem

**Comment by kingzmm** [comment]
@mdmillerii How to solve this problem

**Comment by mdmillerii** [comment]
You can add a delay and hope or accept the system will disappear when you ask it to loose its current state and accept that in the client, looking for a clean state after an appropriate delay.

**Comment by kingzmm** [comment]
@mdmillerii Could you please tell me the specific location of the modified file? I did not find the file

**Comment by mdmillerii** [comment]
I don't know offhand.

**Comment by mdmillerii** [comment]
Actually since it looks like a web server reply look at the journal for a crashed process when dbus communication occurred.

**Comment by kingzmm** [comment]
@mdmillerii Do you know the approximate location,Please tell me,Thank you very much

**Comment by kingzmm** [comment]
@mdmillerii Do you know restapi factory reset Where is the call

**Comment by kingzmm** [comment]
@mdmillerii Could you help me? The simulation can pass, but the actual measurement still reports the same problem

**Comment by anoo1** [comment]
@kingzmm can you post the REST call you're using to issue the factory reset? Also do other REST calls return success or error?

**Comment by kingzmm** [comment]
@anoo1 I don't know if any other reset will work

**Comment by anoo1** [comment]
Just asking if you'd paste here the command you're using to issue the factory reset. The second question was if you've tried any other commands like doing a GET to just read the contents of an interface, to check that the error is only seen on a factory reset command and not on any REST call.

Some additional data that would be useful would be the version of openbmc (cat /etc/os-release), and the journal output when the factory reset was issued, before issuing the factory reset: journalctl -f &

**Comment by kingzmm** [comment]
@anoo1 journalctl :
openpower-update-manager[1046]:Failed to read VERSION
openpower-update-manager[1046]:Unable to read from version
openpower-update-manager[1046]:Error version is empty

**Comment by kingzmm** [comment]
@anoo1 I suspect it was caused by an error in pnor

**Comment by kingzmm** [comment]
@anoo1 Do you think pnor may cause factory reset to report errors?

**Comment by kingzmm** [comment]
Resolved: shield void ItemUpdaterStatic::reset() in openpower-software-manager/static/ item_updater_static.cpp，add one return Skip this function
