### ISSUE TITLE
devtool modify returning : Exception: ModuleNotFoundError: No module named '_sysconfigdata'

### ISSUE THREAD

**Issue by MarkAEvans** [openbmc/openbmc#3713]
Attempting to modify entity-manager. I'm getting the following error:
:
Exception: ModuleNotFoundError: No module named '_sysconfigdata'

Attached is the complete log.
[devtool.log](https://github.com/openbmc/openbmc/files/5334409/devtool.log)

**Comment by anoo1** [comment]
Yeah, @geissonator has reported this upstream: https://lists.yoctoproject.org/g/yocto/topic/74637733

```
A quick hack was to modify sysconfig.py _get_sysconfigdata_name() function and change _PYTHON_SYSCONFIGDATA_NAME to _PYTHON_SYSCONFIGDATA_NAME_INVALID so the python function will use the alternative _sysconfigdata_{abi}_{platform}_{multiarch}'.format
```

Another workaround that seems to work is to symlink `/usr/lib64/python3.8/_sysconfigdata.py` to `/usr/lib64/python3.8/_sysconfigdata__linux_x86_64-linux-gnu.py` for example
