### ISSUE TITLE
How to restart xyz.openbmc_project.Hwmon@.service

### ISSUE THREAD

**Issue by kingzmm** [openbmc/openbmc#3719]
How to restart xyz.openbmc_project.Hwmon@-ahb-apb-bus\x401e78a000-i2c\x2dbus\x4040-w83795adg\x402c.service
I modify /etc/default/obmc/hwmon/ahb/apb/bus@1e78a000/i2c-bus@40/w83795adg@2c.conf,I want restart sensor list

**Comment by spinler** [comment]
I'm not sure if that service can be restarted with systemctl, but there are at least 2 other options - kill the process with a signal, or unbind and rebind the device driver behind it.

**Comment by kingzmm** [comment]
@spinler Thank you very much for your answer, systemctl cannot close this service, and I don’t know the parent process of this process, so I can’t close the process, so do you have any other way?
