### ISSUE TITLE
Latest release is not latest release

### ISSUE THREAD

**Issue by stewartsmith** [openbmc/openbmc#3734]
On the front page of GitHub, it has Latest Release listed for OpenBMC:
![Screenshot from 2020-11-29 13-18-20](https://user-images.githubusercontent.com/611883/100553902-c7bb3880-3245-11eb-96e9-0a5c5e24cbf5.png)

I am pretty sure that releases have been made since then.

**Comment by geissonator** [comment]
We've got our next release coming this month, lets be sure to make it official in github this time.

**Comment by stewartsmith** [comment]
This does appear to be fixed now, thanks!
