### ISSUE TITLE
ipmiSetFrontPanelButtonEnables always tries to set power and reset button states

### ISSUE THREAD

**Issue by singhscp** [openbmc/openbmc#3737]
This IPMI command handler to first check if the system has the capability of disabling of power and reset buttons before trying to set the states. Else IPMI chassis netfn 0x00 command 0x0a will return an error when one or both buttons aren't implemented. The capability information is return in Get Chassis Status command response byte 5.

**Comment by edtanous** [comment]
What machine are you on?  What SHA1 did you build from?
