### ISSUE TITLE
Please tell me how to use the "bb" config  change  uboot from 2016 to 2019 in myself sys

### ISSUE THREAD

**Issue by Anleven** [openbmc/openbmc#3739]
**Note on Bugs**
Please note that questions or feature requests should be discussed on the
mailing list or Discord. Please see https://github.com/openbmc/openbmc#contact
for info on how to contact us. Github Issues in openbmc/openbmc are for bugs
only. Please remove this section when opening a bug.

**Unexpected behavior you saw**

i want to use uboot-2019  but my sys only can build with uboot-2016 .

anyone  help me

**Comment by edtanous** [comment]
I'm slightly confused.  You literally quoted the answer to this in your bug, this needs to be mailed to the mailing list, not opened as a github bug.

To those that have the right permissions, I suspect this can be closed.
