### ISSUE TITLE
General parsing framework for MRW-XML

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#374]

**Comment by williamspatrick** [comment]
Maybe look at what is available from open-power/hostboot and open-power/serverwiz .

**Comment by agangidi53** [comment]
so is the thought behind this to generate https://github.com/openbmc/skeleton/blob/5213a991a5a3bd107636f1b2cc3bbca560843462/configs/Barreleye.py  from  https://github.com/open-power/barreleye-xml/blob/master/barreleye.xml ? or just reuse the XML ?

**Comment by williamspatrick** [comment]
@agangidi53 - I plan to change how we specify the machine information in openbmc (Barreleye.py today).  Some of the content in the system.py files today Brad is in the process of moving over to systemd service files.  Some of the content in there is also duplicated in the kernel device tree, for instance for the i2c devices.  I'd like to use the barreleye-xml as the prime source and then generate content from it as needed in openbmc.  Eventually, I hope we do not generate a single big file like Barreleye.py that describes the whole machine but generate smaller portions that are tailored to the consuming application.
