### ISSUE TITLE
How to build ldap service

### ISSUE THREAD

**Issue by kingzmm** [openbmc/openbmc#3751]
I want to set up an ldap service to manage my users. I have successfully set up an ldap server on centos7. I tried to connect to ldap on the web interface of openbmc. It shows that the connection is successful, but when I log in, I cannot log in through the user in the ldap server. , Does anyone know why this is, please tell me, thank you very much

**Comment by edtanous** [comment]
Please ask this question to the mailing list, not in a github bug.
