### ISSUE TITLE
how to change the thresh of sensors through the web and ipmitool?

### ISSUE THREAD

**Issue by MTZHANGXIANG** [openbmc/openbmc#3757]
I am the new developer of OpenBmc. Now i want to change the thresh of sensors through the web and ipmitool. But i see the redfish  don't provide the function. i want to know how to implement this function,Thank u very much.

**Comment by solonfan** [comment]
![image](https://user-images.githubusercontent.com/15608567/106848916-d235fa80-66ec-11eb-9e5d-53abb541451a.png)
IPMI SPEC 35.8 Set sensor thresholds command for your reference.But it should be the sensor to be setabble .

Thanks,
SolonFan
