### ISSUE TITLE
Encounter WARNINGs while building the meta-intel/meta-s2600wf

### ISSUE THREAD

**Issue by Tommy-git2033** [openbmc/openbmc#3768]
**Unexpected behavior you saw**
Hi，guys，when i build the meta-intel/meta-s2600wf, I encounter Warnings, look the picture:
![image](https://user-images.githubusercontent.com/80077923/110051928-a6f90680-7d91-11eb-924b-f53d0db5ad9c.png)

Can anyone answer me my doubts, why these warnings are produced and how they will affect it? thanks so much！
In addition, My compilation operation is as follows ：
export TEMPLATECONF=meta-intel/meta-s2600sf/conf
. openbmc-env
bitbake obmc-phosphor-iamge

**Comment by mdmillerii** [comment]
The OpenBMC project mantains a kernel tree based off of mainline and works to upstream its patches.   The warnings you see are generated from the yocto config system, using additional metadata in their kernel tree.

Some of the above features do require specific config items to be enabled and you will need to check the layers when combined will result in a usable config.  Specifically gpio based input keyboard, polled and or interrupt driven, and vlans in the network layer.


The following is a link to some content in our documentation repository
https://github.com/openbmc/docs/blob/master/kernel-development.md.  There are discussions in our mailing list from when yocto made this change last year.

In general the community prefers to use our email list and irc and discord forums for general questions but some of us still scan at least selected repository github issues.  You will generally find a broader group there.

**Comment by Tommy-git2033** [comment]
thanks for your reply!
I will get a further look at the kernel-development.md file. 
By the way ,as i am a newcomer to openbmc ,I would think that I caused you troubles the way i ask question. Could you please tell me more about the mailing list？

**Comment by mdmillerii** [comment]
On the front page of the docs repository :-)

https://github.com/openbmc/docs.

Please consider closing this issue.  Thanks.

**Comment by Tommy-git2033** [comment]
Ok, thanks so much ,i will close this issue soon.
