### ISSUE TITLE
Set Boot Mode from dbus is not working

### ISSUE THREAD

**Issue by tejas-patil20** [openbmc/openbmc#3774]
- Hi, I am trying to set the host boot mode to BIOS setup with the help of dbus paths available.

- Tried setting the BIOS setup mode and source with below commands.

# curl -k -H "X-Auth-Token: $token" -X PUT https://${bmc}/xyz/openbmc_project/control/host0/boot/attr/SetInProgress -d '{"data":"xyz.openbmc_project.Control.Boot.SetInProgress.Statuses.SetInProgress"}'
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

# curl -k -H "X-Auth-Token: $token" -X PUT https://${bmc}/xyz/openbmc_project/control/host0/boot/attr/BIOSAck -d '{"data":true}'
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

# curl -k -H "X-Auth-Token: $token" -X PUT https://${bmc}/xyz/openbmc_project/control/host0/boot/attr/BootFlagsValid -d '{"data":true}'
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

# curl -k -H "X-Auth-Token: $token" -X PUT https://${bmc}/xyz/openbmc_project/control/host0/boot/one_time/attr/BootSource -d '{"data":"xyz.openbmc_project.ControlBoot.Source.Sources.BIOS"}'
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

#  curl -k -H "X-Auth-Token: $token" -X PUT https://${bmc}/xyz/openbmc_project/control/host0/boot/one_time/attr/BootMode -d '{"data":xyz.openbmc_project.Control.Boot.Mode.Modes.Setup"}'
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

# curl -k -H "X-Auth-Token: $token" -X PUT https://${bmc}/xyz/openbmc_project/control/host0/boot/attr/SetInProgress -d '{"data":"xyz.openbmc_project.Control.Boot.SetInProgress.Statuses.SetComplete"}'
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}

curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/xyz/openbmc_project/control/host0/boot/one_time
{
  "data": {
    "BootMode": "xyz.openbmc_project.Control.Boot.Mode.Modes.Setup",
    "BootSource": "xyz.openbmc_project.Control.Boot.Source.Sources.BIOS",
    "CMOSClear": false,
    "ConsoleRedirection": "xyz.openbmc_project.Control.Boot.ConsoleRedirection.Redirections.Default",
    "DeviceInstance": 0,
    "Enabled": true,
    "FirmwareVerbosity": "xyz.openbmc_project.Control.Boot.FirmwareVerbosity.Levels.Default",
    "ForceProgressEventTraps": false,
    "LockKeyboard": false,
    "LockPower": false,
    "LockSleep": false,
    "MuxOverride": "xyz.openbmc_project.Control.Boot.MuxOverride.Modes.Default",
    "PasswordBypass": false,
    "ResetLockout": false,
    "ScreenBlank": false,
    "SharedModeOverride": false
  },
  "message": "200 OK",
  "status": "ok"
}

# curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/xyz/openbmc_project/control/host0/boot
{
  "data": {
    "BIOSAck": true,
    "BlockSelector": 0,
    "BootFlagValidClearingValid": false,
    "BootFlagsParamValid": false,
    "BootFlagsValid": true,
    "BootInfoAckValid": false,
    "BootInitiatorInfoValid": false,
    "BootInitiatorMailboxValid": false,
    "BootMode": "xyz.openbmc_project.Control.Boot.Mode.Modes.Regular",
    "BootServicePartitionScanValid": false,
    "BootServicePartitionSelectorValid": false,
    "BootSetInProgressValid": false,
    "BootSource": "xyz.openbmc_project.Control.Boot.Source.Sources.Default",
    "Channel": 0,
    "ConsoleRedirection": "xyz.openbmc_project.Control.Boot.ConsoleRedirection.Redirections.Default",
    "DeviceInstance": 0,
    "FirmwareVerbosity": "xyz.openbmc_project.Control.Boot.FirmwareVerbosity.Levels.Default",
    "ForceProgressEventTraps": false,
    "LockPower": false,
    "LockSleep": false,
    "Mailbox0L": 0,
    "Mailbox0U": 0,
    "Mailbox1L": 0,
    "Mailbox1U": 0,
    "Mailbox2L": 0,
    "Mailbox2U": 0,
    "Mailbox3L": 0,
    "Mailbox3U": 0,
    "Mailbox4L": 0,
    "Mailbox4U": 0,
    "NoClearOnPEFReset": false,
    "NoClearOnPowerup": false,
    "NoClearOnPushbuttonReset": false,
    "NoClearOnTimeout": false,
    "NoClearOnWatchdogReset": false,
    "OEMAck": false,
    "OSAck": false,
    "OSLoaderAck": false,
    "PartitionDiscovered": false,
    "PasswordBypass": false,
    "RequestScan": false,
    "ResetLockout": false,
    "SMSAck": false,
    "ServicePartition": 0,
    "SessionID": 0,
    "SetInProgress": "xyz.openbmc_project.Control.Boot.SetInProgress.Statuses.SetComplete",
    "Timestamp": 0,
    "Type": "xyz.openbmc_project.Control.Boot.BootType.Types.Legacy"
  },
  "message": "200 OK",
  "status": "ok"
}

- The properties are getting set, but whenever I do Host power cycle operation, then host is not stopping in BIOS setup.

- If I set above properties and do power cycle then host won't stop in BIOS setup.
- But if I repeat the same steps second time, then onwards its working and stopping in BIOS setup.

- Even I tried setting it from Redfish side like below:
# curl -k -H "X-Auth-Token: $token" -X PATCH https://${bmc}/redfish/v1/Systems/system -d '{"Boot":{"BootSourceOverrideEnabled": "Continuous","BootSourceOverrideTarget": "BiosSetup"}}'

- But its not working. 

- Am I missing something, that's why its not working on first boot?
- I want to set Boot Mode to BIOS Setup with the help of dbus only.
- Is there anything, which I left or missing?

- Please Help me on this.

- @williamspatrick 
- @dkodihal 
Please comment on this

**Comment by edtanous** [comment]
Closing due to staleness, and lack of mentioning which platform this is targeting.  Please reopen if this is still an issue.
