### ISSUE TITLE
events directory gets duplicated causing 

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#378]
root@barreleye:/var/lib/obmc/events# ls -l
-rw-r--r--    1 root     root           183 Jun 15 07:33 253
drwxr-xr-x    3 root     root             0 Jun 14 06:44 events
root@barreleye:/var/lib/obmc/events# ls -l events/
-rw-r--r--    1 root     root           109 Jun 13 08:52 131
-rw-r--r--    1 root     root           183 Jun 13 08:52 132
-rw-r--r--    1 root     root          1726 Jun 13 08:59 133
-rw-r--r--    1 root     root           183 Jun 13 13:12 134
-rw-r--r--    1 root     root          1817 Jun 13 17:42 135
-rw-r--r--    1 root     root          2191 Jun 13 18:19 136
-rw-r--r--    1 root     root          2203 Jun 13 18:19 137
-rw-r--r--    1 root     root          2203 Jun 13 18:19 138
-rw-r--r--    1 root     root          2203 Jun 13 18:19 139
-rw-r--r--    1 root     root          1821 Jun 13 19:05 140
-rw-r--r--    1 root     root          2191 Jun 13 19:26 141
-rw-r--r--    1 root     root          2203 Jun 13 19:26 142
-rw-r--r--    1 root     root          2203 Jun 13 19:26 143
-rw-r--r--    1 root     root          2203 Jun 13 19:26 144
-rw-r--r--    1 root     root          1821 Jun 13 19:47 145
-rw-r--r--    1 root     root          2191 Jun 13 20:11 146
-rw-r--r--    1 root     root          2203 Jun 13 20:11 147
-rw-r--r--    1 root     root          2203 Jun 13 20:11 148
-rw-r--r--    1 root     root          2203 Jun 13 20:11 149
-rw-r--r--    1 root     root          1821 Jun 13 20:25 150
-rw-r--r--    1 root     root           183 Jun 14 06:44 23
drwxr-xr-x    3 root     root             0 Jun 13 20:25 events
root@barreleye:/var/lib/obmc/events# ls -l events/events
-rw-r--r--    1 root     root           109 Jun 13 08:52 131
-rw-r--r--    1 root     root           183 Jun 13 08:52 132
-rw-r--r--    1 root     root          1726 Jun 13 08:59 133
-rw-r--r--    1 root     root           183 Jun 13 13:12 134
-rw-r--r--    1 root     root          1817 Jun 13 17:42 135
-rw-r--r--    1 root     root          2191 Jun 13 18:19 136
-rw-r--r--    1 root     root          2203 Jun 13 18:19 137
-rw-r--r--    1 root     root          2203 Jun 13 18:19 138
-rw-r--r--    1 root     root          2203 Jun 13 18:19 139
-rw-r--r--    1 root     root          1821 Jun 13 19:05 140
-rw-r--r--    1 root     root          2191 Jun 13 19:26 141
-rw-r--r--    1 root     root          2203 Jun 13 19:26 142
-rw-r--r--    1 root     root          2203 Jun 13 19:26 143
-rw-r--r--    1 root     root          2203 Jun 13 19:26 144
-rw-r--r--    1 root     root          1821 Jun 13 19:47 145
-rw-r--r--    1 root     root          2191 Jun 13 20:11 146
-rw-r--r--    1 root     root          2203 Jun 13 20:11 147
-rw-r--r--    1 root     root          2203 Jun 13 20:11 148
-rw-r--r--    1 root     root          2203 Jun 13 20:11 149
-rw-r--r--    1 root     root          1821 Jun 13 20:25 150
-rw-r--r--    1 root     root           183 Jun 13 06:23 25
-rw-r--r--    1 root     root           183 Jun 13 07:01 49
drwxr-xr-x    3 root     root             0 Jun 13 07:01 events
root@barreleye:/var/lib/obmc/events# ls -l events/events/events
-rw-r--r--    1 root     root           183 Jun 13 06:23 25
-rw-r--r--    1 root     root           183 Jun 13 07:01 49
drwxr-xr-x    2 root     root             0 Jun 13 06:23 events
root@barreleye:/var/lib/obmc/events# ls -l events/events/events/events
-rw-r--r--    1 root     root           183 Jun 13 06:23 25

root@barreleye:~# cat /etc/os-release 
ID=openbmc-phosphor
NAME=Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)
VERSION=0.1.0 (jethro)
VERSION_ID=v0.8.1-32-g9f1d336-dirty
PRETTY_NAME=Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 0.1.0 (jethro)
BUILD_ID=v0.8.1
root@barreleye:~# 

While debugging https://github.com/openbmc/openbmc/issues/257 I saw this problem.  I do not believe is the cause of the 257 issue hence me opening a new issue...

Somehow the events directory is getting duplicated.  Not sure how but there are 5 levels deep of 'events'.  The event manager code does not do any copies so it can't be coming from there.  This is pretty serious because there is no way via REST to delete these logs.  They consume flash space with no way (without logging in as root) to free up the space.  

Command to see what logs the event service sees (notice only 1)...
$ curl -c cjar -b cjar -k https://x.x.x.x/org/openbmc/records/events/
{
  "data": [
    "/org/openbmc/records/events/253"
  ], 
  "message": "200 OK", 
  "status": "ok"
}

**Comment by mdmillerii** [comment]
Because the `whitelist` entry has a trailing `/` , the code in the `obmc-phosphor-initfs` `update` script that strips off the directory name fails to effectively do so.   This also means that over a flash update the files are restored to `/var/lib/obmc/events/events` and are effectively lost but take space.

I will address the issue.  To recover the lost space is it okay to remove the recursive directory or do we need to write code to recover the files from the recursive save?
