### ISSUE TITLE
Can openbmc support ikvm for ast2400 soc?

### ISSUE THREAD

**Issue by gooaler** [openbmc/openbmc#3780]
The IP-KVM is not working on master, that it shows a blank page on OpenBMC WebUI. 
The video0 device node is not generated under the system.

**Comment by leonli2002** [comment]
> The IP-KVM is not working on master, that it shows a blank page on OpenBMC WebUI. The video0 device node is not generated under the system.

It still does not work for ast2400 , no video0 node in /dev

**Comment by mdmillerii** [comment]
Make sure your device tree [enables](https://github.com/openbmc/linux/blob/0f9b4c3ca5fdf3e177266ef994071b1a03f07318/arch/arm/boot/dts/aspeed/aspeed-g4.dtsi#L249) the hardware, includes a [buffer](https://github.com/openbmc/linux/blob/0f9b4c3ca5fdf3e177266ef994071b1a03f07318/Documentation/devicetree/bindings/media/aspeed-video.txt#L19) , and the driver is [enabled](https://github.com/openbmc/linux/blob/0f9b4c3ca5fdf3e177266ef994071b1a03f07318/drivers/media/platform/aspeed/Kconfig#L5)
