### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by recha0** [openbmc/openbmc#3781]
When
export TEMPLATECONF=meta-evb/meta-evb-enclustra/meta-evb-zx3-pm3/conf

time bitbake obmc-phosphor-image   . openbmc-env

there is a bug:
ERROR: Layer xilinx is not compatible with the core layer which only supports these series: hardknott (layer is compatible with gatesgarth dunfell)

**Comment by 229024527** [comment]
I've met the question as you too.

**Comment by williamspatrick** [comment]
I don't know anyone active on the project that regularly uses `meta-evb-enclustra`, so it is maintained at a best effort and doesn't have any CI behind it.

This layer is picking up another meta layer from elsewhere ("Layer xilinx is not compatible") and that layer doesn't work with the latest Yocto revision, it appears.  This should be reported to https://github.com/Xilinx/meta-xilinx .  Once they have a fix that supports hardknott, we can sync their subtree here.

**Comment by verilogzhou** [comment]
Xilinx已有支持Hardnott的补丁，麻烦更新一下。

**Comment by williamspatrick** [comment]
I've emailed Xilinx to get some clarification on a few items.  github and yocto are now diverged for meta-xilinx and I'm not sure which is official.

**Comment by williamspatrick** [comment]
>> 1. I see that https://github.com/Xilinx/meta-xilinx is now different from                                                    
>>     http://git.yoctoproject.org/cgit/cgit.cgi/meta-xilinx/.  Is that intentional?                                            
>>     Which one should we be pointing to?                                                                                      

> It is temporary.  We're working on the Xilinx version first, once it's working then we merge it to git.yoctoproject.org.
> The github version will also contain petalinux branches that won't appear on the git.yoctoproject.org.

I got this from one of the Xilinx maintainers.  While they have hardknott supported in their github repository, that's not what we are pointing at as we tend to only pick up Yocto meta-layers.  Once they've completed this work we can pick up the updated tree from git.yoctoproject.org.

**Comment by recha0** [comment]
Thinks to much for your replay! I understand. Now I use the history version of openbmc/meta-xilinx.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openbmc/openbmc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 晚上11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openbmc/openbmc] New bug (#3781)





    
I see that https://github.com/Xilinx/meta-xilinx is now different from
 http://git.yoctoproject.org/cgit/cgit.cgi/meta-xilinx/.  Is that intentional?
 Which one should we be pointing to?
     
It is temporary.  We're working on the Xilinx version first, once it's working then we merge it to git.yoctoproject.org.
 The github version will also contain petalinux branches that won't appear on the git.yoctoproject.org.
  
I got this from one of the Xilinx maintainers.  While they have hardknott supported in their github repository, that's not what we are pointing at as we tend to only pick up Yocto meta-layers.  Once they've completed this work we can pick up the updated tree from git.yoctoproject.org.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by edtanous** [comment]
The xilinx layer was removed due to lack of maintainers keeping it up to date, so this bug no longer exists.  If the machines are re-added, they will need to compile against current yocto.

Closing.
