### ISSUE TITLE
It seem like a incorrect code snippet existed in the aspeed video drive

### ISSUE THREAD

**Issue by wangmin239** [openbmc/openbmc#3783]
Hi folks,
It seems like that the code is wrong at the line number 1098 in the below code snippet.  The below code snippet is extracted from the source [file](https://github.com/torvalds/linux/blob/master/drivers/media/platform/aspeed-video.c)(https://github.com/torvalds/linux/blob/master/drivers/media/platform/aspeed-video.c).  The variable named "frame_rate" may be setted to MAX_FRAME_RATE.

 `1097	if (!frame_rate || frame_rate > MAX_FRAME_RATE) {`
 `    1098		    frame_rate = 0;`
 `1099		    a->parm.capture.timeperframe.denominator = MAX_FRAME_RATE;`
 `1100		    a->parm.capture.timeperframe.numerator = 1;`
 `1101	}`

**Comment by williamspatrick** [comment]
You should probably post a fix to the LKML then. This driver is in the upstream kernel.
