### ISSUE TITLE
corrupted while trying to fetch the dbus property

### ISSUE THREAD

**Issue by sushmitha894** [openbmc/openbmc#3787]
ConfigPath is getting corrupted. I'm getting below error

terminate called after throwing an instance of 'sdbusplus::exception::SdBusError'
what():  sd_bus_process discard: org.freedesktop.DBus.Error.Disconnected: Connection reset by peer

**Comment by edtanous** [comment]
Suspect this was fixed on master a while back, but difficult to determine based on what was put in the description.   Please reopen if this is still an issue.
