### ISSUE TITLE
Support for ASMB7-iKVM

### ISSUE THREAD

**Issue by albertofustinoni** [openbmc/openbmc#3790]
I know someone asked for supporting Asus's ASMB6-iKVM and the limiting factor seemed to be RAM in #3478

Is there any chance the ASMB7-iKVM could be supported then? According to the [spec sheet](https://www.asus.com/Commercial-Servers-Workstations/ASMB7IKVM/specifications/) it's still an AST2300 but with 224MB RAM.

**Comment by williamspatrick** [comment]
Ast2300 is not supported by the Linux kernel. Someone would need to do all the work to enable that chip.

**Comment by edtanous** [comment]
Over a year old, and question was answered.  Closing.
