### ISSUE TITLE
BMC watchdog status

### ISSUE THREAD

**Issue by NKV-obmc** [openbmc/openbmc#3791]
How can we identify a watchdog reset happened in openBMC Board.

Inside the /dev directory its loaded watchdog, watchdog0, Watchdog1.
For testing used cat >> /dev/watchdog, cat >> /dev/watchdog0, cat >> /dev/watchdog1

In all the mentioned cases AST2500 board is getting restarted.
But in next boot reading system reset register will not set the watchdog reset bit.

**Comment by solonfan** [comment]
Check uboot code,firmware identify watchdog if happened by WDT **timeout status register**.

**Comment by mdmillerii** [comment]
On Aspeed we export the status but I don't remember the file

**Comment by williamspatrick** [comment]
Support request.  Appears to be answered?
