### ISSUE TITLE
KVM  Super Keys (XK_Super_L & XK_Super_R) are not working

### ISSUE THREAD

**Issue by tejas-patil20** [openbmc/openbmc#3796]
## Description:

- If I try to send the super keys then there is no response coming for it.
- As I can see, super keys (XK_Super_L & XK_Super_R) are not configured with obmc-ikvm server.
- Only for below modifiers the key codes has been added:

![image](https://user-images.githubusercontent.com/51698666/118967488-666c5a80-b988-11eb-8f0b-6e5270c8d2e5.png)

- And additionally if I use "XK_Meta_L" key instead of "XK_Super_L", then once i used Super key, then other keys will not work.

- Can anyone help me out on this?
- I need to add Super Keys  with obmc-ikvm.
- What are the scan codes for the Super keys? 

- @yoojae
- @williamspatrick 
- @geissonator 
- @eddiejames 
- @gtmills 
- @mdmillerii 

- Anybody please reply on this!

**Comment by williamspatrick** [comment]
Why am I @‘d on this?

**Comment by williamspatrick** [comment]
Please feel free to contribute changes to obmc-ikvm.  This is not an openbmc/openbmc issue but a feature request on a sub-component.
