### ISSUE TITLE
DT-bindings directory

### ISSUE THREAD

**Issue by kthoru01** [openbmc/openbmc#3799]
Hello,

I apologize for asking such a novice question, but I saw that one of the .dts files references a dt-bindings directory. Where could I find that? I would like to take a look at the definitions to understand the requirements for building a DT for a BMC. Thank you very much!

**Comment by mdmillerii** [comment]
We ask that questions be directed to email or discord.
The device tree bindings are in the Linux kernel repository.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings
https://www.kernel.org/doc/html/latest/devicetree/index.html
https://www.devicetree.org/

**Comment by edtanous** [comment]
Per the first response, please ask your questions to the relevant communities forums, per mdmilleriis response.

Closing.
