### ISSUE TITLE
Convert packages to autotools.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#380]

**Comment by williamspatrick** [comment]
Assign to Matt Barth.

**Comment by msbarth** [comment]
Preview of autotool source created for the openbmc/phosphor-host-ipmid repo
[autotools_phosphor-host-ipmid.tar.bz2.zip](https://github.com/openbmc/openbmc/files/369940/autotools_phosphor-host-ipmid.tar.bz2.zip)

**Comment by msbarth** [comment]
Outline of steps to generate autotool config files & scripts:

autoscan
Rename configure.scan to configure.ac
Update configure.ac
   Add "AM_INIT_AUTOMAKE"
   Modify AC_INIT with proper field values
aclocal
autoheader
Create required automake files
   NEWS (`touch NEWS`)
   README (`touch README`)
   AUTHORS (`touch AUTHORS`)
   ChangeLog (`touch ChangeLog`)
   COPYING (`touch COPYING`)
automake --add-missing
autoconf

./configure --host=arm-openbmc-linux-gnueabi
./config.status
make

**Comment by shenki** [comment]
Please submit the changes for review at gerrit. We do not share code by uploading zip files to bug trackers.

**Comment by williamspatrick** [comment]
Split the work completed off into #544.  Changing the estimate of this story to 1pt.

**Comment by msbarth** [comment]
- [ ] Convert phosphor-event

- [ ] Convert phosphor-objmgr

- [ ] Convert phosphor-hwmon

- [ ] Convert ipmi-fru-parser

- [ ] Convert inarp

- [ ] Convert btbridge
