### ISSUE TITLE
Add CI tests for all packages.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#382]

**Comment by williamspatrick** [comment]
This is to ensure we have Jenkins running.  Requires #380 to give us a consistent test case invocation and #381 to give us the unit test framework.

**Comment by williamspatrick** [comment]
Assign to Matt Barth.

**Comment by williamspatrick** [comment]
The outcome of this should be a jenkins job for every C++ / autotools repository (hopefully templated for all the repositories) that compiles and runs the gtests.  #561 was opened to convert existing test cases to gtest.

**Comment by geissonator** [comment]
- [ ] Create script which can run in docker container to do simple dependency item
- [ ] Script can handle complex dependencies accross repos
- [ ] Create template jenkins jobs that allows new repos to easily be added
- [ ] Automatically run jenkins job against gerrit changes

**Comment by msbarth** [comment]
- [ ] Create script which can run in docker container to do simple dependency item

- [ ] Script can handle complex dependencies accross repos

- [ ] Create template jenkins jobs that allows new repos to easily be added

- [ ] Automatically run jenkins job against gerrit changes
