### ISSUE TITLE
Is openbmc able to dectect the host's cpus are present and running?

### ISSUE THREAD

**Issue by wangmin239** [openbmc/openbmc#3821]
Hi folks,
Is there a recipe to detect the host's cpus are present and running? Does openBmc support to monitor the host's cpus are running?
Thanks.

**Comment by geissonator** [comment]
Hi @wangmin239 please refer to https://github.com/openbmc/openbmc#questions for asking questions.

**Comment by mdmillerii** [comment]
Short answer is there's an interface to store it for the rest of the code, but detection depends on the host including it's processor architecture.

**Comment by mdmillerii** [comment]
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/yaml/xyz/openbmc_project/State/Host.interface.yaml

**Comment by wangmin239** [comment]
@mdmillerii  Thanks your responder. I checked out the source codes from phosphor-dbus-interface and phoshor-state-manger. I wish to get a solution from the codes. Thanks again.
