### ISSUE TITLE
 ipmitool  is unable to set and get  watchdog

### ISSUE THREAD

**Issue by wangmin239** [openbmc/openbmc#3825]
**Unexpected behavior you saw**
Type the command 'ipmitool mc watchdog get' into a BMC  terminal console, the command windows printed the below message.

> Get Watchdag Timer command failed: Unspecified error

**Expected behavior**

> $ ipmitool mc watchdog get
> Watchdog Timer Use:     BIOS FRB2 (0x81)
> Watchdog Timer Is:      Stopped
> Watchdog Timer Actions: Power Cycle (0x03)
> Pre-timeout interval:   1 seconds
> Timer Expiration Flags: 0x00
> Initial Countdown:      10 sec
> Present Countdown:      10 sec

**To Reproduce**
1.  Type the command 'ipmitool mc watchdog get' into a bmc serial console.
2.  wait to the output of the upper command.

**Screenshots**

**OpenBMC Information:**
 - /etc/os-release: VERSION="2.9.0-43"
 - uname -a: Linux s2500 5.8.17-7ee2d5b
 - Any additional patches or changes:

**Additional context**
using the command 'journalctl -f'  to get the below log.

> Oct 09 17:35:32 s2500 ipmid[296]: wd_get: sd_bus_call: xyz.openbmc_project.Common.Error.ResourceNotFound: path or object not found.

busctl introspect xyz.openbmc_project.State.Watchdog /xyz/openbmc_project/watchdog/host0

> Failed to introspect object /xyz/openbmc_project/watchdog/host0 of service   xyz.openbmc_project.State.Watchdog:
> The name is not activatable

Any help will be appreciated.

**Comment by wangmin239** [comment]
@mdmillerii  Thanks for your reply. The command 'ipmitool -I dbus mc watchdog' was also tried, however, the command windows printed 'unspecified error'.  Could you tell me  what is the name  of another parsers？

**Comment by mdmillerii** [comment]
Glad you figured it out.   `systemctl` doesn't care what directory it's invoked from.

**Comment by wangmin239** [comment]
@mdmillerii  Thanks you to point out my misuse of the 'systemctl' command.
