### ISSUE TITLE
The postinstall intercept hook 'update_gtk_icon_cache' failed 

### ISSUE THREAD

**Issue by zoeynihao** [openbmc/openbmc#3826]
I tried to build an openbmc image according to the  https://github.com/openbmc/openbmc.git  README.md . But I got the mistake in this layer. I am very new to openbmc so I don't have much experience.
system :
ubuntu 18.04
Python 3.6.9
git version 2.17.1
tar (GNU tar) 1.29
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

the build log as below picture:
![image](https://user-images.githubusercontent.com/92415803/137424705-69fe57c5-3f75-4868-8996-368de98985ea.png)
[openbmc_build_fail.log](https://github.com/openbmc/openbmc/files/7350561/openbmc_build_fail.log)
 the detail log is as the following attachment
[detail_build.log](https://github.com/openbmc/openbmc/files/7350574/detail_build.log)

**Comment by edtanous** [comment]
The machine being built in the example (qemuarm) has been building correctly for some time now;  Suspect this was fixed in a subtree update.  Resolving.
