### ISSUE TITLE
obmc-control-chassis failed to be built

### ISSUE THREAD

**Issue by wangmin239** [openbmc/openbmc#3835]
**Note on Bugs**
Please note that questions or feature requests should be discussed on the
mailing list or Discord. Please see https://github.com/openbmc/openbmc#contact
for info on how to contact us. Github Issues in openbmc/openbmc are for bugs
only. Please remove this section when opening a bug.

**Unexpected behavior you saw**
The below command failed to be executed at the tag 2.9.0 of openBmc.
'bitbake -c compile obmc-control-chassis'

**Expected behavior**
obmc-control-chassis is able to be successfully built.

**To Reproduce**
1. type the command 'bitbake -c compile obmc-control-chassis' to command terminal
2. the command window will print the following text snippets

> phytium@ubuntu:s2500$ bitbake -c compile obmc-control-chassis
Loading cache: 100% |###############################################################################################| Time: 0:00:01
Loaded 3786 entries from dependency cache.
Parsing recipes: 100% |#############################################################################################| Time: 0:00:01
Parsing of 2499 .bb files complete (2497 cached, 2 parsed). 3787 targets, 370 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'python' (but /home/wangmin/openbmc/meta-phosphor/recipes-phosphor/chassis/obmc-control-chassis_git.bb DEPENDS on or otherwise requires it). Close matches:
  python3
  python3-py
  python3-sh
ERROR: Required build target 'obmc-control-chassis' has no buildable providers.
Missing or unbuildable dependency chain was: ['obmc-control-chassis', 'python']

> Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

> 2.9.0

Screenshots

OpenBMC Information:

/etc/os-release: VERSION="2.9.0-43"
uname -a: Linux s2500 5.8.17-7ee2d5b
Any additional patches or changes: NA

The issue seems like to be related to python. Any help will be appreciated, thanks in advance.

**Comment by williamspatrick** [comment]
2.9 is far too old.  This was likely before the python2 to python3 migration was done and that appears to be the complaint.
