### ISSUE TITLE
Build failed with honister branch

### ISSUE THREAD

**Issue by KunLuffy** [openbmc/openbmc#3841]
Using honister branch, executed command:
. setup romulus
bitbake obmc-phosphor-image

Then report error log:
ERROR: No recipes in default available for:
  /home/baikun/zd-tech/openbmc-v211/openbmc-v211-next/meta-phosphor/recipes-core/systemd/systemd_249.3.bbappend

Maybe need to delete this file? Because systemd upgrade to 249.7 in poky project.

**Comment by williamspatrick** [comment]
I'll fix this.  I probably pulled the upstream security fixes from Yocto that updated the underlying systemd recipe.  

I need to confirm if the patches we have are all fixed in 249.7 or if we need to rename the bbappend.

**Comment by KunLuffy** [comment]
Hi Williams, 
According your message, I checked the patch which 249.3 bbappend include and confirmed 249.7 doesn't fixed. Then I rename bbappend file to 249.7, it can build passed.

**Comment by williamspatrick** [comment]
A fix is pending in Gerrit. https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/51228

**Comment by williamspatrick** [comment]
Fixed via 1a38de9b8a6a9532f1de9ff4648037b20edbf16a

**Comment by KunLuffy** [comment]
Problem resolved. Thanks a lot.
