### ISSUE TITLE
Always fail when i fetch linux kernel, master code have same error

### ISSUE THREAD

**Issue by YangYunLong1988** [openbmc/openbmc#3849]
Reproduce:
1. download openBMC 2.11.0 stable package
2.  . setup romulus
3.  bitbake -b linux-aspeed --no-setscene
![error](https://user-images.githubusercontent.com/13655604/163594131-aae49b32-93b0-4428-93cd-9861f28df12c.jpg)

**Comment by williamspatrick** [comment]
Why are you adding -b and —no-setscene?

**Comment by YangYunLong1988** [comment]
Today, I tried again, Linux kernel can download.
