### ISSUE TITLE
Get System Guid Issue

### ISSUE THREAD

**Issue by shamim-ali** [openbmc/openbmc#3854]
Hi,
The current implementation for get system guid is from phosphor-host-ipmid which getting the UUID property using the BMC Interface and UUID interface , but no service is providing these interfaces and the command return as unspecified error message.

From System Guid Code:

 static constexpr auto bmcInterface =
        "xyz.openbmc_project.Inventory.Item.Bmc";
    static constexpr auto uuidInterface = "xyz.openbmc_project.Common.UUID";
    static constexpr auto uuidProperty = "UUID";

Is Entiy Manager is the right place to add these Interfaces if not what are the other options?  
We are having a case where we are not having UUID property in EEPROM and using  systemd's machine-id.

Please give your suggestions on it.

Thanks,
Shamim Ali

**Comment by williamspatrick** [comment]
I do not have any opinions on this.

**Comment by mine260309** [comment]
On our system, we define the related interface in settingsd, and have a service to read the UUID from EEPROM/FRU, and write to the DBus.
And we have another service that is part of "dbus-monitor" to monitor the change of the DBus property, re-calculate the checksum and write the UUID changes back to EEPROM.

**Comment by zevweiss** [comment]
Having just stumbled across the same problem, I'd also be interested in getting this fixed...

> Is Entiy Manager is the right place to add these Interfaces if not what are the other options?

@edtanous, any thoughts here?

**Comment by edtanous** [comment]
The bmc doesn’t “own” the system guid. Generally your bios does, so whichever daemon implements your bios->bmc interface would need to manage the transfer of the UUID.  In a lot of cases that’s probably smbios-mdr, but I can really say without knowing the system.

this definitely doesn’t go in entity manager, given that EM has no real concept of the host system at this point.

**Comment by williamspatrick** [comment]
Hmm. Our system designs have the GUID stored in the eeprom of the compute card holding the host. It definitely doesn’t come from the bios in every system design.

**Comment by zevweiss** [comment]
Yeah, in my case the BIOS queries the BMC for data to use for the UUID it provides to the host OS (and if the command fails the host just ends up seeing a hard-coded 1234578-style value); it doesn't seem to think it's responsible for it itself.

**Comment by edtanous** [comment]
Gotcha.  Good to know there’s lots of designs out there.

**Comment by williamspatrick** [comment]
If you want the BMC to persist this information in its local file system, you probably want to look into configuring phosphor-settingsd to hold this interface for you.  If you want it persisted in an EEPROM, this would be a new feature.  You would need to propose a design to the affected components and contribute.
