### ISSUE TITLE
[Add Sensor] phosphor-hwmon is running，but web /hardware-status/sensors is null.

### ISSUE THREAD

**Issue by qkpidan** [openbmc/openbmc#3858]
**Note on Bugs**
I cant see anything in  #/hardware-status/sensors

**Unexpected behavior you saw**
phosphor-hwmon is running，but web /hardware-status/sensors is null.
![image](https://user-images.githubusercontent.com/44697380/169188627-5df48f83-2f13-4034-8461-01aaf3ca7209.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/44697380/169190212-3b52a6f3-d304-4b86-97f8-f398e4e24eea.png)

**To Reproduce**
1. Modify  opbmc - qemu/hw/arm/aspeed.c  line 540.
![image](https://user-images.githubusercontent.com/44697380/169189351-b4b42767-0670-4c29-9921-1412254e8c93.png)

2. Add phosphor-hwmon_%.bbappend
```bash
FILESEXTRAPATHS:prepend:hkzy-ast2500 := "${THISDIR}/${PN}:"
EXTRA_OECONF:append:hkzy-ast2500 = " --enable-negative-errno-on-fail"

CHIPS = " \
        bus@1e78a000/i2c-bus@80/tmp105@48 \
        bus@1e78a000/i2c-bus@80/tmp105@49 \
        bus@1e78a000/i2c-bus@80/tmp105@4a \
        bus@1e78a000/i2c-bus@80/tmp105@4b \
        "
ITEMSFMT = "ahb/apb/{0}.conf"

ITEMS = "${@compose_list(d, 'ITEMSFMT', 'CHIPS')}"
ENVS = "obmc/hwmon/{0}"

SYSTEMD_ENVIRONMENT_FILE:${PN}:append:hkzy-ast2500 = " ${@compose_list(d, 'ENVS', 'ITEMS')}"
```

3. Modify  dtsi
![image](https://user-images.githubusercontent.com/44697380/169189561-ebf0fbec-7e09-44c5-8f65-a862734a13fb.png)

4. See web-ui
![image](https://user-images.githubusercontent.com/44697380/169188627-5df48f83-2f13-4034-8461-01aaf3ca7209.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/44697380/169189082-7b8137b7-c6e6-401f-a246-054e71f7b62b.png)

![image](https://user-images.githubusercontent.com/44697380/169189184-b13db0c6-1ee2-4021-93ec-734b1efcbcdd.png)

![image](https://user-images.githubusercontent.com/44697380/169189202-1c624bee-e7f1-4a43-a871-0bbbe9fffe8a.png)

![image](https://user-images.githubusercontent.com/44697380/169188559-e209ffe7-c68d-4e63-89f7-c2588cba7ed5.png)

![image](https://user-images.githubusercontent.com/44697380/169188627-5df48f83-2f13-4034-8461-01aaf3ca7209.png)

**OpenBMC Information:**
 - /etc/os-release:
![image](https://user-images.githubusercontent.com/44697380/169188803-6e864d8c-0d29-4b1c-afa4-943f64a5398a.png)

 - uname -a:
![image](https://user-images.githubusercontent.com/44697380/169188846-cfb50609-bfb9-4a02-9ebe-3a48a5105c02.png)

**Comment by williamspatrick** [comment]
Please don't send screenshots of text and logs.  The synopsis of this issue is "I made some changes and things don't work as I expected".  I'm not sure how you expect others to debug this for you.

Are there sensor objects being created by the phosphor-hwmon processes on dbus?  Do they contain the values you expect?  If so, do the Redfish APIs give the sensor values you expect?  If so, does the webui console have any errors?

**Comment by qkpidan** [comment]
> 

Got it. 
I am sorry about that. It wont happen again.

xyz.openbmc_project.Sensor is not processes on dbus, how can i fix it?

Thanks!

**Comment by williamspatrick** [comment]
> xyz.openbmc_project.Sensor is not processes on dbus, how can i fix it?

I'm not sure what you mean by this or what you're expecting to see or what you're running to determine this.

`phosphor-hwmon` has a number of processes and you showed them running in your screenshot.  Each one of those will have its own dbus-service.  Running `busctl` by itself will show you all the current connections.  Pick the ones that are related to the `phosphor-hwmon` process (hopefully it is obvious) and run `busctl tree <service>`.  That will hopefully show you the path to the sensor object(s).  You can then run `busctl introspect <service> <path>` to get the interfaces and values at those object paths.

**Comment by spinler** [comment]
Are you using phosphor-inventory-manager or entity-manager to manage your inventory?  I would suggest entity-manager, and then you can follow https://github.com/openbmc/entity-manager/blob/master/docs/my_first_sensors.md.  If you want to use phosphor-hwmon with phosphor-inventory-manager, then you need to manually add associations to the chassis so that redfish can find them.  https://github.com/openbmc/phosphor-inventory-manager#creating-associations describes that (though as mentioned above you'd need to check that phosphor-hwmon is actually hosting those sensors on D-Bus first)

**Comment by AloneWarrior11011** [comment]
> **Note on Bugs** I cant see anything in #/hardware-status/sensors
> 
> **Unexpected behavior you saw** phosphor-hwmon is running，but web /hardware-status/sensors is null. ![image](https://user-images.githubusercontent.com/44697380/169188627-5df48f83-2f13-4034-8461-01aaf3ca7209.png)
> 
> **Expected behavior** ![image](https://user-images.githubusercontent.com/44697380/169190212-3b52a6f3-d304-4b86-97f8-f398e4e24eea.png)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Modify  opbmc - qemu/hw/arm/aspeed.c  line 540.
>        ![image](https://user-images.githubusercontent.com/44697380/169189351-b4b42767-0670-4c29-9921-1412254e8c93.png)
> 
>     2. Add phosphor-hwmon_%.bbappend
> 
> 
> FILESEXTRAPATHS:prepend:hkzy-ast2500 := "${THISDIR}/${PN}:"
> EXTRA_OECONF:append:hkzy-ast2500 = " --enable-negative-errno-on-fail"
> 
> CHIPS = " \
>         bus@1e78a000/i2c-bus@80/tmp105@48 \
>         bus@1e78a000/i2c-bus@80/tmp105@49 \
>         bus@1e78a000/i2c-bus@80/tmp105@4a \
>         bus@1e78a000/i2c-bus@80/tmp105@4b \
>         "
> ITEMSFMT = "ahb/apb/{0}.conf"
> 
> ITEMS = "${@compose_list(d, 'ITEMSFMT', 'CHIPS')}"
> ENVS = "obmc/hwmon/{0}"
> 
> SYSTEMD_ENVIRONMENT_FILE:${PN}:append:hkzy-ast2500 = " ${@compose_list(d, 'ENVS', 'ITEMS')}"
> 
>     3. Modify  dtsi
>        ![image](https://user-images.githubusercontent.com/44697380/169189561-ebf0fbec-7e09-44c5-8f65-a862734a13fb.png)
> 
>     4. See web-ui
>        ![image](https://user-images.githubusercontent.com/44697380/169188627-5df48f83-2f13-4034-8461-01aaf3ca7209.png)
> 
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/44697380/169189082-7b8137b7-c6e6-401f-a246-054e71f7b62b.png)
> 
> ![image](https://user-images.githubusercontent.com/44697380/169189184-b13db0c6-1ee2-4021-93ec-734b1efcbcdd.png)
> 
> ![image](https://user-images.githubusercontent.com/44697380/169189202-1c624bee-e7f1-4a43-a871-0bbbe9fffe8a.png)
> 
> ![image](https://user-images.githubusercontent.com/44697380/169188559-e209ffe7-c68d-4e63-89f7-c2588cba7ed5.png)
> 
> ![image](https://user-images.githubusercontent.com/44697380/169188627-5df48f83-2f13-4034-8461-01aaf3ca7209.png)
> 
> **OpenBMC Information:**
> 
>     * /etc/os-release:
>       ![image](https://user-images.githubusercontent.com/44697380/169188803-6e864d8c-0d29-4b1c-afa4-943f64a5398a.png)
> 
>     * uname -a:
>       ![image](https://user-images.githubusercontent.com/44697380/169188846-cfb50609-bfb9-4a02-9ebe-3a48a5105c02.png)

Hey where do you have modify dtsi file to specify your sensor, could you provide the exact path on where I can add my tmp75 sensor data like you have add like : 
&i2c1{
   ....
   ....
};

in my case I have used tmp75 sensor which are found at bus number 1 on i2c address 0x4d.  on Raspberrypi 3
