### ISSUE TITLE
Build error with glibc recipe

### ISSUE THREAD

**Issue by edineshkumar** [openbmc/openbmc#3867]
I have cloned and started the new build today and faced the error with glibc recipe in do_fetch / do_unpack function.

**Build Configuration Details:**

Build Configuration:
BB_VERSION           = "2.0.1"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "arm-openbmc-linux-gnueabi"
MACHINE              = "evb-ast2600"
DISTRO               = "openbmc-phosphor"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "arm armv7a vfp vfpv4d16 callconvention-hard"
TARGET_FPU           = "hard"
meta
meta-poky
meta-oe
meta-networking
meta-python
meta-phosphor
meta-aspeed
meta-evb-ast2600     = "master:0ee49ef1a8bf8cf874b32c1897a49fcdb2faee30"

**Note on Bugs**

`DEBUG: Executing python function do_unpack
DEBUG: Executing python function base_do_unpack
DEBUG: Running 'export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/0/bus"; `

`ERROR: Bitbake Fetcher Error: FetchError('Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/0/bus";`

**To Reproduce**
1. Cloned Latest source 'git clone https://github.com/openbmc/openbmc'
2. Specified the target machine
3. Executed bitbake obmc-phosphor-image
4. See error on glibc 

**Screenshots**

<img width="599" alt="image" src="https://user-images.githubusercontent.com/41941042/176853902-9c119388-103d-42f0-a08e-9abdde4c8ed0.png">

<img width="804" alt="image" src="https://user-images.githubusercontent.com/41941042/176854060-c87640ad-0704-4922-af0c-028ddda377a0.png">

Appreciate, if I get some help..!
Thanks in Advance.

**Comment by williamspatrick** [comment]
So the suggestion is that a fresh clone is broken for evb-ast2600?  @geissonator, can you glance at this?  I’m not in a place I can easily recreate for a bit.

**Comment by geissonator** [comment]
Built fine for me:
```
Build Configuration:
BB_VERSION           = "2.0.1"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "arm-openbmc-linux-gnueabi"
MACHINE              = "evb-ast2600"
DISTRO               = "openbmc-phosphor"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "arm armv7a vfp vfpv4d16 callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-oe              
meta-networking      
meta-python          
meta-phosphor        
meta-aspeed          
meta-evb-ast2600     = "master:06be640dc87caf845170f209ff5305f9911eca1a"

Initialising tasks: 100% |#############################################################################################################################| Time: 0:00:01
Checking sstate mirror object availability: 100% |#####################################################################################################| Time: 0:00:33
Sstate summary: Wanted 1640 Local 0 Mirrors 0 Missed 1640 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
Using an insecure image signing key!
NOTE: Tasks Summary: Attempted 4059 tasks of which 0 didn't need to be rerun and all succeeded.

Summary: There were 2 WARNING messages.
```

**Comment by dhineshkumar256** [comment]
Adding `--no-same-owner` in the `tar -xzf` command fixed this error for me.

**Comment by williamspatrick** [comment]
> 

Which tar command is this referring to?  If this is something needed, should it be perused upstream with Yocto to get it added?
