### ISSUE TITLE
Does linux-libc-headers version need update in honister branch?

### ISSUE THREAD

**Issue by KunLuffy** [openbmc/openbmc#3868]
In honister branch, the kernel version(in linux-aspeed.bb) has updated 5.15.5, but the linux-libc-headers is still using 5.14. Does it need update to 5.15?

**Comment by williamspatrick** [comment]
Generally, it is ok to have an older headers with a newer kernel.  These provide the APIs that are available to userspace from the kernel.  We've typically not worried about deviating from whatever is in upstream Yocto w.r.t. the kernel headers.
