### ISSUE TITLE
devtool modify fails on systemd

### ISSUE THREAD

**Issue by kriegeraa** [openbmc/openbmc#3870]
**Unexpected behavior you saw**
On the current master branch (d347aa868de275799011b3c577b42d76b0f6c64f) doing a _devtool modify_ on systemd fails because 0005-src-basic-missing.h-check-for-missing-strndupa.patch cannot be applied. (It does work fine for a normal build, it is only the modify that does not work.)

> ERROR: Applying patch '0005-src-basic-missing.h-check-for-missing-strndupa.patch' on target directory '/---/openbmc/build/evb-
> ast2500/tmp/work/arm1176jzs-openbmc-linux-gnueabi/systemd/1_251.2-r0/devtooltmp-b2t_s6cy/workdir/git'
> BBHandledException("Applying '0005-src-basic-missing.h-check-for-missing-strndupa.patch' failed:
> stdout: checking file meson.build
> Hunk #1 succeeded at 512 (offset 5 lines).
> checking file src/backlight/backlight.c
> Hunk #1 succeeded at 20 with fuzz 2 (offset 1 line).
> checking file src/basic/cgroup-util.c
> checking file src/basic/env-util.c
> checking file src/basic/log.c
> checking file src/basic/missing_stdlib.h
> checking file src/basic/mkdir.c
> checking file src/basic/mountpoint-util.c
> checking file src/basic/parse-util.c
> checking file src/basic/path-lookup.c
> checking file src/basic/percent-util.c
> checking file src/basic/proc-cmdline.c
> checking file src/basic/procfs-util.c
> checking file src/basic/time-util.c
> checking file src/boot/bless-boot.c
> Hunk #1 succeeded at 22 (offset 3 lines).
> checking file src/core/dbus-cgroup.c
> checking file src/core/dbus-execute.c
> checking file src/core/dbus-util.c
> checking file src/core/execute.c
> Hunk #1 succeeded at 103 (offset 1 line).
> checking file src/core/kmod-setup.c
> Hunk #1 FAILED at 10.
> 1 out of 1 hunk FAILED
> checking file src/core/service.c
> Hunk #1 succeeded at 42 with fuzz 2.
> checking file src/coredump/coredump-vacuum.c
> Hunk #1 succeeded at 17 (offset 1 line).
> checking file src/fstab-generator/fstab-generator.c
> checking file src/journal-remote/journal-remote-main.c
> checking file src/journal/journalctl.c
> Hunk #1 succeeded at 74 (offset 1 line).
> checking file src/libsystemd/sd-bus/bus-message.c
> checking file src/libsystemd/sd-bus/bus-objects.c
> Hunk #1 succeeded at 11 with fuzz 1 (offset -1 lines).
> checking file src/libsystemd/sd-bus/bus-socket.c
> checking file src/libsystemd/sd-bus/sd-bus.c
> checking file src/libsystemd/sd-bus/test-bus-benchmark.c
> checking file src/libsystemd/sd-journal/sd-journal.c
> checking file src/locale/keymap-util.c
> checking file src/login/pam_systemd.c
> checking file src/network/generator/network-generator.c
> checking file src/nspawn/nspawn-settings.c
> checking file src/nss-mymachines/nss-mymachines.c
> checking file src/portable/portable.c
> checking file src/resolve/resolvectl.c
> checking file src/shared/bus-get-properties.c
> checking file src/shared/bus-unit-procs.c
> checking file src/shared/bus-unit-util.c
> checking file src/shared/bus-util.c
> checking file src/shared/dns-domain.c
> checking file src/shared/journal-importer.c
> checking file src/shared/logs-show.c
> checking file src/shared/pager.c
> checking file src/shared/uid-range.c
> Hunk #1 succeeded at 14 with fuzz 1 (offset 5 lines).
> checking file src/socket-proxy/socket-proxyd.c
> checking file src/test/test-hexdecoct.c
> checking file src/udev/udev-builtin-path_id.c
> checking file src/udev/udev-event.c
> checking file src/udev/udev-rules.c
> 
> stderr: ")
> ERROR: Logfile of failure stored in: /---/openbmc/build/evb-ast2500/tmp/work/arm1176jzs-openbmc-linux-gnueabi/systemd/1_251.2-r0/devtooltmp-b2t_s6cy/temp/log.do_patch.3695014

**To Reproduce**
1. Clone openbmc
2. `. setup evb-ast2500`
3. `devtool modify systemd`

**Comment by williamspatrick** [comment]
@geissonator - Looks like we've not done a Yocto rebase in a while?  I see some upstream commits to rebase the patch files for systemd, which might resolve this.

**Comment by geissonator** [comment]
ok, I got https://gerrit.openbmc.org/c/openbmc/openbmc/+/55403/ up. We hit some new issues that need some work though.
