### ISSUE TITLE
reserving fdt memory region failed when booting in the real machine

### ISSUE THREAD

**Issue by zip123zip** [openbmc/openbmc#3871]
ERROR: reserving fdt memory region failed (addr=98000000 size=4000000), I don't know how to fix this issue when booting in the real machine. The log data as follows:

DRAM Init-V12-DDR4
0abc1-4Gb-Done
Read margin-DL:0.3960/DH:0.4137 CK (min:0.30)

U-Boot 2019.04 (Jun 16 2022 - 12:41:16 +0000)

SOC : AST2500-A2 
RST : WDT3 - Boot
RST : Power On 
eSPI Mode : SIO:Enable : SuperIO-2e
Eth : MAC0: RMII/NCSI, , MAC1: RGMII, 
Model: AST2500 EVB
DRAM:  448 MiB (capacity:512 MiB, VGA:64 MiB, ECC:off)
MMC:   sdhci_slot0@100: 0, sdhci_slot1@200: 1
Loading Environment from SPI Flash... SF: Detected mx66l1g45g with page size 256 Bytes, erase size 4 KiB, total 128 MiB
*** Warning - bad CRC, using default environment

In:    serial@1e784000
Out:   serial@1e784000
Err:   serial@1e784000
Net:   
Warning: ethernet@1e660000 (eth0) using random MAC address - 2e:fd:c0:86:ea:2a
eth0: ethernet@1e660000
Warning: ethernet@1e680000 (eth1) using random MAC address - ea:97:27:2b:a0:7c
, eth1: ethernet@1e680000
Hit any key to stop autoboot:  0 
## Loading kernel from FIT Image at 20100000 ...
   Using 'conf-aspeed-bmc-inspur-fp5280g10.dtb' configuration
   Trying 'kernel-1' kernel subimage
     Description:  Linux kernel
     Type:         Kernel Image
     Compression:  uncompressed
     Data Start:   0x20100128
     Data Size:    3158672 Bytes = 3 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: 0x80001000
     Entry Point:  0x80001000
     Hash algo:    sha256
     Hash value:   33f46dab2c21576fbd0f2969bd9376b4f4ccf04caab71c2ca1f5bf5d6cd88f99
   Verifying Hash Integrity ... sha256+ OK
## Loading ramdisk from FIT Image at 20100000 ...
   Using 'conf-aspeed-bmc-inspur-fp5280g10.dtb' configuration
   Trying 'ramdisk-1' ramdisk subimage
     Description:  obmc-phosphor-initramfs
     Type:         RAMDisk Image
     Compression:  uncompressed
     Data Start:   0x2040d328
     Data Size:    1098684 Bytes = 1 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: unavailable
     Entry Point:  unavailable
     Hash algo:    sha256
     Hash value:   78712b00a4a77155c3ae153213e917c7e4dff68a503147d277400b3fa21d9632
   Verifying Hash Integrity ... sha256+ OK
## Loading fdt from FIT Image at 20100000 ...
   Using 'conf-aspeed-bmc-inspur-fp5280g10.dtb' configuration
   Trying 'fdt-aspeed-bmc-inspur-fp5280g10.dtb' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x204034d4
     Data Size:    40326 Bytes = 39.4 KiB
     Architecture: ARM
     Hash algo:    sha256
     Hash value:   412ab6f31e594646b52382bbafed81a2ccc70b0b36029746d8797a3f6dd35666
   Verifying Hash Integrity ... sha256+ OK
   Booting using the fdt blob at 0x204034d4
   Loading Kernel Image ... OK
   Loading Ramdisk to 8fef3000, end 8ffff3bc ... OK
ERROR: reserving fdt memory region failed (addr=98000000 size=4000000)
   Loading Device Tree to 8fee6000, end 8fef2d85 ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.15.50-27b1fcc (oe-user@oe-host) (arm-openbmc-linux-gnueabi-gcc (GCC) 12.1.0, GNU ld (GNU Binutils) 2.38.20220516) #1 Mon Jun 27 06:53:35 UTC 2022
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: FP5280G2 BMC
[    0.000000] Memory policy: Data cache writeback
[    0.000000] Reserved memory: created CMA memory pool at 0x97000000, size 16 MiB
[    0.000000] OF: reserved mem: initialized node framebuffer, compatible id shared-dma-pool
[    0.000000] Reserved memory: created CMA memory pool at 0x95000000, size 32 MiB
[    0.000000] OF: reserved mem: initialized node jpegbuffer, compatible id shared-dma-pool
[    0.000000] cma: Reserved 16 MiB at 0x94000000
[    0.000000] Ignoring RAM at 0x98000000-0x9c000000
[    0.000000] Consider using a HIGHMEM enabled kernel.
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080000000-0x0000000097ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080000000-0x0000000097ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080000000-0x0000000097ffffff]
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 97536
[    0.000000] Kernel command line: console=ttyS4,115200n8 root=/dev/ram rw
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:all(zero), heap alloc:off, heap free:off
[    0.000000] Memory: 311704K/393216K available (7168K kernel code, 663K rwdata, 1556K rodata, 1024K init, 155K bss, 15976K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 23776 entries in 47 pages
[    0.000000] ftrace: allocated 47 pages with 5 groups
[    0.000000] trace event string verifier disabled
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] i2c controller registered, irq 17
[    0.000000] clocksource: FTTMR010-TIMER2: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 77222644334 ns
[    0.000004] sched_clock: 32 bits at 24MHz, resolution 40ns, wraps every 86767015915ns
[    0.000103] Switching to timer-based delay loop, resolution 40ns
[    0.001292] Calibrating delay loop (skipped), value calculated using timer frequency.. 49.50 BogoMIPS (lpj=247500)
[    0.001379] pid_max: default: 32768 minimum: 301
[    0.003595] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.003692] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.007113] CPU: Testing write buffer coherency: ok
[    0.010698] Setting up static identity map for 0x80100000 - 0x80100038
[    0.012271] ASPEED AST2500 rev A2 (04030303)
[    0.013752] devtmpfs: initialized
[    0.044452] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.044561] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.056827] pinctrl core: initialized pinctrl subsystem
[    0.060277] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.062913] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.065945] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.066021] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.161306] mc: Linux media interface: v0.10
[    0.161502] videodev: Linux video capture interface: v2.00
[    0.161680] pps_core: LinuxPPS API ver. 1 registered
[    0.161726] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.161823] PTP clock support registered
[    0.166204] clocksource: Switched to clocksource FTTMR010-TIMER2
[    0.265592] NET: Registered PF_INET protocol family
[    0.266133] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.268213] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.268345] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.268436] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.268544] TCP bind hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.268635] TCP: Hash tables configured (established 4096 bind 4096)
[    0.268976] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.269123] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.269953] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.273751] Unpacking initramfs...
[    0.286415] workingset: timestamp_bits=30 max_order=17 bucket_order=0
[    0.301471] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.301544] jffs2: version 2.2. (SUMMARY)  © 2001-2006 Red Hat, Inc.
[    0.318567] NET: Registered PF_ALG protocol family
[    0.323347] ipmi-bt-host 1e789140.ibt: Found bt bmc device
[    0.324383] ipmi-bt-host 1e789140.ibt: Using IRQ 35
[    0.326287] ast-kcs-bmc 1e78902c.kcs: Initialised raw client for channel 3
[    0.336869] ast-kcs-bmc 1e78902c.kcs: Initialised IPMI client for channel 3
[    0.336950] ast-kcs-bmc 1e78902c.kcs: Initialised channel 3 at 0xca2
[    0.343826] Serial: 8250/16550 driver, 6 ports, IRQ sharing enabled
[    0.357441] 1e787000.serial: ttyS5 at MMIO 0x1e787000 (irq = 35, base_baud = 1546875) is a ASPEED VUART
[    0.360330] 1e783000.serial: ttyS0 at MMIO 0x1e783000 (irq = 33, base_baud = 1500000) is a 16550A
[    0.362062] 1e784000.serial: ttyS4 at MMIO 0x1e784000 (irq = 34, base_baud = 1500000) is a 16550A
[    1.406701] printk: console [ttyS4] enabled
[    1.413035] 1e78d000.serial: ttyS1 at MMIO 0x1e78d000 (irq = 36, base_baud = 1500000) is a 16550A
[    1.439018] 1e78e000.serial: ttyS2 at MMIO 0x1e78e000 (irq = 37, base_baud = 1500000) is a 16550A
[    1.458387] timeriomem_rng 1e6e2078.hwrng: 32bits from 0x(ptrval) @ 1us
[    1.466316] aspeed_gfx 1e6e6000.display: assigned reserved memory node framebuffer
[    1.507295] random: crng init done
[    1.527394] [drm] Initialized aspeed-gfx-drm 1.0.0 20180319 for 1e6e6000.display on minor 0
[    1.550485] aspeed_gfx 1e6e6000.display: [drm] fb0: aspeed-gfx-drmd frame buffer device
[    1.598022] loop: module loaded
[    1.662223] spi-nor spi0.0: mx66l1g45g (131072 Kbytes)
[    1.797746] spi-aspeed-smc 1e620000.spi: CE0 read buswidth:2 [0x203c0641]
[    1.949253] 5 fixed-partitions partitions found on MTD device bmc
[    1.955405] Creating 5 MTD partitions on "bmc":
[    1.960068] 0x000000000000-0x0000000e0000 : "u-boot"
[    1.990024] 0x0000000e0000-0x000000100000 : "u-boot-env"
[    2.009560] 0x000000100000-0x000000a00000 : "kernel"
[    2.017578] 0x000000a00000-0x000002a00000 : "rofs"
[    2.038851] 0x000002a00000-0x000004000000 : "rwfs"
[    2.049568] spi-nor spi1.0: unrecognized JEDEC id bytes: ff ff ff ff ff ff
[    2.056611] spi-nor: probe of spi1.0 failed with error -2
[    2.067195] ftgmac100 1e660000.ethernet: Read MAC address 2e:fd:c0:86:ea:2a from chip
[    2.075110] ftgmac100 1e660000.ethernet: Using NCSI interface
[    2.082224] ftgmac100 1e660000.ethernet eth0: irq 20, mapped at 897d79c1
[    2.089798] ftgmac100 1e680000.ethernet: Read MAC address ea:97:27:2b:a0:7c from chip
[    2.208587] Freeing initrd memory: 1076K
[    2.276329] RTL8211F Gigabit Ethernet 1e680000.ethernet--1:00: attached PHY driver (mii_bus:phy_addr=1e680000.ethernet--1:00, irq=POLL)
[    2.289843] ftgmac100 1e680000.ethernet eth1: irq 21, mapped at 92d50135
[    2.310617] aspeed_vhub 1e6a0000.usb-vhub: Initialized virtual hub in USB2 mode
[    2.318705] Mass Storage Function, version: 2009/09/11
[    2.323899] LUN: removable file: (no medium)
[    2.328356] no file given for LUN0
[    2.331864] udc 1e6a0000.usb-vhub:p1: failed to start g_mass_storage: -22
[    2.339943] i2c_dev: i2c /dev entries driver
[    2.345791] aspeed-i2c-bus 1e78a040.i2c-bus: i2c bus 0 registered, irq 38
[    2.353957] aspeed-i2c-bus 1e78a080.i2c-bus: i2c bus 1 registered, irq 39
[    2.363240] aspeed-i2c-bus 1e78a0c0.i2c-bus: i2c bus 2 registered, irq 40
[    2.373599] at24 3-0055: 256 byte 24c02 EEPROM, writable, 1 bytes/write
[    2.380584] aspeed-i2c-bus 1e78a100.i2c-bus: i2c bus 3 registered, irq 41
[    2.390134] aspeed-i2c-bus 1e78a140.i2c-bus: i2c bus 4 registered, irq 42
[    2.399426] aspeed-i2c-bus 1e78a180.i2c-bus: i2c bus 5 registered, irq 43
[    2.407769] aspeed-i2c-bus 1e78a1c0.i2c-bus: i2c bus 6 registered, irq 44
[    2.416642] aspeed-i2c-bus 1e78a300.i2c-bus: i2c bus 7 registered, irq 45
[    2.425492] pca953x 8-0020: using no AI
[    2.429782] pca953x 8-0020: failed writing register
[    2.435777] pca953x 8-0021: using no AI
[    2.440066] pca953x 8-0021: failed writing register
[    2.445741] pca953x 8-0022: using no AI
[    2.450017] pca953x 8-0022: failed writing register
[    2.455688] pca953x 8-0023: using no AI
[    2.459960] pca953x 8-0023: failed writing register
[    2.465645] pca953x 8-0024: using no AI
[    2.469942] pca953x 8-0024: failed writing register
[    2.475661] pca953x 8-0025: using no AI
[    2.479946] pca953x 8-0025: failed writing register
[    2.485089] aspeed-i2c-bus 1e78a340.i2c-bus: i2c bus 8 registered, irq 46
[    2.493475] aspeed-i2c-bus 1e78a380.i2c-bus: i2c bus 9 registered, irq 47
[    2.501904] aspeed-i2c-bus 1e78a3c0.i2c-bus: i2c bus 10 registered, irq 48
[    2.510374] aspeed-i2c-bus 1e78a400.i2c-bus: i2c bus 11 registered, irq 49
[    2.518812] aspeed-i2c-bus 1e78a440.i2c-bus: i2c bus 12 registered, irq 50
[    2.526922] pca954x 2-0070: probe failed
[    2.531465] pca954x 7-0070: probe failed
[    2.536708] aspeed-video 1e700000.video: assigned reserved memory node jpegbuffer
[    2.547005] Driver for 1-wire Dallas network protocol.
[    2.558429] lm75 3-0048: hwmon1: sensor 'tmp112'
[    2.711829] SPI driver bmp280 has no spi_device_id for bosch,bmp085
[    2.720661] fsi-master-acf gpio-fsi: ColdFire initialized, firmware v4 API v2.1 (trace disabled)
[    2.762397] NET: Registered PF_INET6 protocol family
[    2.770915] Segment Routing with IPv6
[    2.774733] In-situ OAM (IOAM) with IPv6
[    2.779205] NET: Registered PF_PACKET protocol family
[    2.784363] 8021q: 802.1Q VLAN Support v1.8
[    2.803081] printk: console [netcon0] enabled
[    2.807597] netconsole: network logging started
[    2.814064] input: gpio-keys as /devices/platform/gpio-keys/input/input4
[    2.829331] Freeing unused kernel image (initmem) memory: 1024K
[    2.839974] Checked W+X mappings: passed, no W+X pages found
[    2.845714] Run /init as init process
rofs = mtd4 squashfs rwfs = mtd5 jffs2
[    3.839446] jffs2: notice: (102) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[    4.196325] overlayfs: upper fs does not support tmpfile.
[    4.202530] overlayfs: upper fs does not support RENAME_WHITEOUT.
[   11.571391] systemd[1]: Failed to look up module alias 'autofs4': Function not implemented
[   11.893053] systemd[1]: systemd 251.2+ running in system mode (+PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL -ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON -UTMP +SYSVINIT default-hierarchy=hybrid)

my dts about flash memory:
flash_memory: region@98000000 {
			no-map;
			reg = <0x98000000 0x04000000>; /* 64M */
		};

&fmc {
	status = "okay";

	flash@0 {
		status = "okay";
		label = "bmc";
		m25p,fast-read;
		spi-max-frequency = <50000000>;
#include "openbmc-flash-layout-64.dtsi"
	};
};

**Comment by williamspatrick** [comment]
There is too much noise in this report and not enough information.  What code are you running?  What hardware are you running it on?  What changes did you make?

You pointed out a u-boot error but then showed the kernel booting.  Is there really a problem here?

If you tried to change the flash size, there are multiple steps involved and not just a simple Yocto variable tweak.  U-boot needs to be informed about your layout as well.
