### ISSUE TITLE
ftgmac100 : NCSI    No channel found to configure!

### ISSUE THREAD

**Issue by ghp971021** [openbmc/openbmc#3872]
I made my ast2400/palmetto openbmc image and then let it run on my board. But NCSI LAN doesn't work.
BMC prints like this:

ftgmac100 1e660000.ethernet eth0: NCSI: No channel found to configure!
ftgmac100 1e660000.ethernet eth0: Wrong NCSI state 0x100 in workqueue

How can I link-up the NCSI network?

**Comment by OguzhanCaglarPavo** [comment]
Hello, Did u solve this issue?

**Comment by williamspatrick** [comment]
Running a palmetto image on something that is not a palmetto board is not going to work.  There should be multiple examples now for NCSI and non-NCSI NIC configurations.  What have you tried?  What hardware are you using?  Does the kernel support your NIC?
