### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by laoshaw** [openbmc/openbmc#3875]
based on https://www.linuxfoundation.org/blog/openbmc-project-community-comes-together-at-the-linux-foundation-to-define-open-source-implementation-of-bmc-firmware-stack/ , IBM provides base code for openBMC, but IBM then launched LibreBMC for its Power arch, then there is RunBMC for OCP project, what are the difference? why IBM donated the code then write its own?

We need a BMC and I am confused by the 3 projects. Thanks for any help.

**Comment by williamspatrick** [comment]
Those all serve 3 different purposes.

1. OpenBMC - An open source software stack for managing servers.
2. LibreBMC - A chip for BMCs using open source RTL and IBM's Microwatt CPU core.
3. RunBMC - A board design for a pluggable BMC module ( I believe there is work like DC-SCM that has supplanted RunBMC at this point ).

You could make a RunBMC module board, with a LibreBMC chip, running OpenBMC (not likely).  You could have a BMC chip from Aspeed or Nuvoton (two common vendors) embedded in your motherboard running OpenBMC.  You could make a RunBMC module with an Aspeed chip running AMI's proprietary BMC codebase.  They are all 3 different aspects of the total BMC design for your system.
