### ISSUE TITLE
Documents for enabling NC-SI in  Intel openBMC

### ISSUE THREAD

**Issue by Rushikesh3499** [openbmc/openbmc#3879]
Hi,
          I have to use the NC-SI for meta-egs, so any document for how it is enabled in Intel openbmc or what changes i have to do in intel openbmc source code? so that the NC-SI support is enabled for BMC.
          If there is any document or procedure please send me.

**Comment by williamspatrick** [comment]
Why are you asking a question here for Intel’s BMC?
