### ISSUE TITLE
Does latest openBMC code support chain of trust?

### ISSUE THREAD

**Issue by shaokong1137** [openbmc/openbmc#3883]
AST2600 provides HW root of trust that verifies u-boot-spl.bin. Can I build an openBMC secure image such that u-boot-spl.bin verifies u-boot.bin which in turn verifies kernel image (and read only root file system)? If so, please provide a pointer to any file/info. Thanks.

**Comment by williamspatrick** [comment]
Our issue template says don't open issues to ask questions.  Please don't disregard this.  You had to have actively deleted this code or ignored using an issue template.

```
# STOP! READ BELOW.

We do not field questions or feature requests by Github Issues!

Questions or feature requests should be discussed on the mailing list or
Discord. Please see https://github.com/openbmc/openbmc#contact for info
on how to contact us.

Github Issues in openbmc/openbmc are for bugs only!
```
