### ISSUE TITLE
[quanta-q71l  build failed] on ubuntu 1804 system

### ISSUE THREAD

**Issue by hptsf** [openbmc/openbmc#3885]
Branch： master
using command:
      . setup quanta-q71l 
      bitbake obmc-phosphor-image
and build failed, error msg:

bitbake obmc-phosphor-image
WARNING: Host distribution "ubuntu-18.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Fetcher failure for URL: 'https://yoctoproject.org/connectivity.html'. URL https://yoctoproject.org/connectivity.html doesn't work.
    Please ensure your host's network is configured correctly.
    Please ensure CONNECTIVITY_CHECK_URIS is correct and specified URIs are available.
    If your ISP or network is blocking the above URL,
    try with another domain name, for example by setting:
    CONNECTIVITY_CHECK_URIS = "https://www.example.com/"    You could also set BB_NO_NETWORK = "1" to disable network
    access if all required sources are on local disk.

Summary: There was 1 WARNING message.
Summary: There was 1 ERROR message, returning a non-zero exit code.

**Comment by amboar** [comment]
Please check that you can reach example.com from your network. If your DNS isn't resolving it or you have some other filtering preventing access, please follow the advice in the error message.

**Comment by hptsf** [comment]
![image](https://user-images.githubusercontent.com/6884036/191900181-8a2765ac-763d-49a2-b7f0-54024720aadc.png)

**Comment by hptsf** [comment]
the network to example.com is ok

**Comment by hptsf** [comment]
![image](https://user-images.githubusercontent.com/6884036/191900479-2be3d339-5f8c-4a85-a3f0-59c048d31dfa.png)

and “https://yoctoproject.org/connectivity.html” is ok too.
