### ISSUE TITLE
About BIOS

### ISSUE THREAD

**Issue by OguzhanCaglar** [openbmc/openbmc#3886]
I successfully got the SMBIOS table over the BT interface by using the smbios_transfer.go command that LinuxBoot provides. I want to ask some things about BIOS:

1) I see an option whose name is "BMC Network Configuration" in BIOS but I can't enter it. Do I have to do any configuration in my BMC build system? How can I access it?

2) I get the SMBIOS table from HOST OS but this process depends on OS. How can I get this information when BIOS is booting? I mean Is there any mechanism that BIOS sends the SMBIOS table to BMC when it is booting?

**Comment by williamspatrick** [comment]
Issue ms are not for questions. See the big templates.
