### ISSUE TITLE
 E:Package 'lz4' has no installion candidate

### ISSUE THREAD

**Issue by Ethan-hsieh-im** [openbmc/openbmc#3893]
I try to sudo apt install git python3-distutils gcc g++ make file wget   gawk diffstat bzip2 cpio chrpath zstd lz4 bzip2
but  it produced E:Package 'lz4' has no installion candidate.
I try to sudo apt update but no use,
How can i do?

**Comment by amboar** [comment]
Hi @Ethan-hsieh-im - github issues aren't the best forum for help, we prefer you to ask either on the [mailing list](https://lists.ozlabs.org/listinfo/openbmc) or Discord ([invite link](https://discord.gg/69Km47zH98)).

If this is an issue with the OpenBMC documentation, you need to tell us where you got that command line from.

It's also not clear what environment (Linux distro and release) you're using to run that command, which is essential to understand why it's not working for you.

Please ask for help in either of the locations above, or provide more info so we can fix any broken documentation.
