### ISSUE TITLE
How to set Fans information on web?

### ISSUE THREAD

**Issue by abyssbrige** [openbmc/openbmc#3895]
Hi, I am a beginner on openbmc
I add a fan sensor and see rpm on sensor page，
![image](https://user-images.githubusercontent.com/37022993/199385252-63031b2f-34b9-4ad2-8b6e-b1a38fe184b6.png)
but  I want to show fans information on this page, how to do that.
![image](https://user-images.githubusercontent.com/37022993/199385481-8038772a-214d-4cf0-a0df-949579555da7.png)

**Comment by williamspatrick** [comment]
GitHub issues is not for questions and it says so right in our issue template.
