### ISSUE TITLE
How to get bin file for flash programming

### ISSUE THREAD

**Issue by Evanfan007** [openbmc/openbmc#3899]
Hi,
  I'm NEW to openbmc. I have finished image building for evb-ast2600 and run in qemu successfully. I would have a try on board but now I met a problem that the flash programmer only support bin file to write whlile the image file, that openbmc project generates, is mtd file.  It may seem stupid but really troubles me. Could you help me?
### MORE INFO ###
```
1.SPI Flash programmer: SF700
2.BOARD: evb-ast2600
3.flash: MX25L25735F
```

**Comment by LeeTroy** [comment]
image-bmc is the file for flash programming.
