### ISSUE TITLE
how to increase mtd partition

### ISSUE THREAD

**Issue by jiaqueforgithub** [openbmc/openbmc#3900]
![image](https://user-images.githubusercontent.com/70046408/210704595-8be5223e-0a19-4541-83fe-c9b9ed3e017b.png)
how to change partitions，i want to incarease a partition named rwfs_2

**Comment by jiaqueforgithub** [comment]
ok，but what are openbmc discord channel and openbmc mailing list

**Comment by mdmillerii** [comment]
See the README.md in this repository. Click the Code tab in GitHub and it will be displayed.
