### ISSUE TITLE
Build failure for evb-ast2600

### ISSUE THREAD

**Issue by abirami-sekar-3** [openbmc/openbmc#3919]
Hi,
I am taking build for evb-ast2600, and it is failing with the message 
`ERROR: Task (/home/vvdn/abiramis/2600/openbmc/meta-openembedded/meta-networking/recipes-protocols/net-snmp/net-snmp_5.9.3.bb:do_compile) failed with exit code '1'
` 
but, when on trying with another machine, it is successful,
I am not sure what was the problem with this configuration, can anyone guide me to build the image in my machine.

Please find my machine details,
`uname -a                                                                                                      
Linux 16222--IOT--POY 5.14.0-1059-oem #67-Ubuntu SMP Mon Mar 13 14:22:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

`python --version
Python 2.7.18`

`lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
`
Please let me know the steps to build the image in this machine.

Thanks in Advance.

**Comment by williamspatrick** [comment]
Just clear out the package and try again. I believe that recipe has had a race for years that nobody has fixed. 

bitbake net-snmp -C clean

**Comment by abirami-sekar-3** [comment]
@williamspatrick ,
I have given clean command, still i am getting error as below

![Screenshot from 2023-04-11 18-15-06](https://user-images.githubusercontent.com/81425094/231166860-41c1dd61-cd44-42ec-9718-e126cbfe2e08.png)

Thanks,
Abirami S

**Comment by williamspatrick** [comment]
Sorry, it should be lower case c.  `bitbake net-snmp -c clean`

**Comment by abirami-sekar-3** [comment]
@williamspatrick ,
I tried the step you have given, eventhough i am getting same error,
![Screenshot from 2023-04-12 12-28-09](https://user-images.githubusercontent.com/81425094/231376890-570fb5ad-91ee-4161-afc6-67d2730ea448.png)

Please suggest any alternative way to build.
Thanks.

**Comment by williamspatrick** [comment]
I don’t have any alternatives except for disabling snmp support if that is something you don’t need anyhow.

**Comment by williamspatrick** [comment]
I'm not sure there is anything to address here.
