### ISSUE TITLE
How to make rootfs in OpenBMC?

### ISSUE THREAD

**Issue by Metso68** [openbmc/openbmc#3934]
Hi all,

I've built FIT Linux image and can see obmc-phosphor-initramfs-ast2500-default.rootfs.cpio.xz as well. But the last file doesn't have root, mnt , proc, sys.

How can I make my own rootfs build in OpenBMC?

Thank you in advance,

Andy

I used the standard build procedure:

.setup evb-25000 bitbake obmc-phosphor-image

**Comment by williamspatrick** [comment]
As the templates say, please don’t use GitHub for support questions. This isn’t a bug. 


What you ran would have created a rootfs. Look in /tmp/deploy/images/
