### ISSUE TITLE
Support for SEL list in ipmitool

### ISSUE THREAD

**Issue by Manikandanrama** [openbmc/openbmc#3935]
I have shown the bmc temperature in webui,and redfish. For that sensor, if it crosses the threshold, it should be generated in the SEL (system event log).

I have generated it in Redfish and WebUI. but it doesn't show in ipmitool when I give it the sel list. It shows the "SEL has no entries" message. Please support how to show the sel value in ipmitool.

**Comment by williamspatrick** [comment]
The bug templates explicitly say we do not provide support via GitHub issues.
