### ISSUE TITLE
openBMC AST2500-EVB auto reboot

### ISSUE THREAD

**Issue by AmirRMoezi** [openbmc/openbmc#3938]
I have built openBMC for AST2500-EVB and when I run the .mtd image by qemu, the u-boot runs successfully but during the linux kernel boot, it stops automatically and u-boot runs again. This loops continuous infinitely. does any body know what is the problem? the terminal output is shown here. This happens even when running the FITimage on the real board.

root@osboxes:/home/osboxes/Desktop/openbmc/build/evb-ast2500/tmp/deploy/images/evb-ast2500# qemu-system-arm -M ast2500-evb -nic user -drive file=obmc-phosphor-image-evb-ast2500-20230612144736.static.mtd,format=raw,if=mtd -nographic

U-Boot 2019.04 (May 30 2023 - 06:05:47 +0000)

SOC : AST2500-A1 
RST : Power On 
LPC Mode : SIO:Enable : SuperIO-2e
Eth : MAC0: RGMII, , MAC1: RGMII, 
Model: AST2500 EVB
DRAM:  448 MiB (capacity:512 MiB, VGA:64 MiB, ECC:off)
MMC:   sdhci_slot0@100: 0, sdhci_slot1@200: 1
Loading Environment from SPI Flash... SF: Detected w25q256 with page size 256 Bytes, erase size 4 KiB, total 32 MiB
OK
In:    serial@1e784000
Out:   serial@1e784000
Err:   serial@1e784000
Net:   eth0: ethernet@1e660000
Warning: ethernet@1e680000 (eth1) using random MAC address - 92:c2:88:7d:f4:79
, eth1: ethernet@1e680000
Hit any key to stop autoboot:  0 
## Loading kernel from FIT Image at 20080000 ...
   Using 'conf-aspeed-ast2500-evb.dtb' configuration
   Trying 'kernel-1' kernel subimage
     Description:  Linux kernel
     Type:         Kernel Image
     Compression:  uncompressed
     Data Start:   0x2008012c
     Data Size:    3083360 Bytes = 2.9 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: 0x80001000
     Entry Point:  0x80001000
     Hash algo:    sha256
     Hash value:   c1ed2b6ee1b997739ffd46f80e73f2a65a01389a571c2afad28632a2d11cf29c
   Verifying Hash Integrity ... sha256+ OK
## Loading ramdisk from FIT Image at 20080000 ...
   Using 'conf-aspeed-ast2500-evb.dtb' configuration
   Trying 'ramdisk-1' ramdisk subimage
     Description:  obmc-phosphor-initramfs
     Type:         RAMDisk Image
     Compression:  uncompressed
     Data Start:   0x20377a1c
     Data Size:    1082032 Bytes = 1 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: unavailable
     Entry Point:  unavailable
     Hash algo:    sha256
     Hash value:   01a609ad06481fc8ea58318f4c1115d3ac339a9ba3fa73786d6092280b47b915
   Verifying Hash Integrity ... sha256+ OK
## Loading fdt from FIT Image at 20080000 ...
   Using 'conf-aspeed-ast2500-evb.dtb' configuration
   Trying 'fdt-aspeed-ast2500-evb.dtb' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x20370ea0
     Data Size:    27311 Bytes = 26.7 KiB
     Architecture: ARM
     Hash algo:    sha256
     Hash value:   dd954d39662a2217b3b1b835554d5e22d8e8729174f8c53532327f425eb55a7e
   Verifying Hash Integrity ... sha256+ OK
   Booting using the fdt blob at 0x20370ea0
   Loading Kernel Image ... OK
   Loading Ramdisk to 8fef7000, end 8ffff2b0 ... OK
   Loading Device Tree to 8feed000, end 8fef6aae ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.1.29-1ac953d (oe-user@oe-host) (arm-openbmc-linux-gnueabi-gcc (GCC) 13.1.1 20230520, GNU ld (GNU Binutils) 2.40.0.20230419) #1 Mon May 22 00:13:30 UTC 2023
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: VIPT aliasing data cache, unknown instruction cache
[    0.000000] OF: fdt: Machine model: AST2500 EVB
[    0.000000] Memory policy: Data cache writeback
[    0.000000] Reserved memory: created CMA memory pool at 0x9b000000, size 16 MiB
[    0.000000] OF: reserved mem: initialized node framebuffer, compatible id shared-dma-pool
[    0.000000] cma: Reserved 16 MiB at 0x9a000000
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000080000000-0x000000009bffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080000000-0x000000009bffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080000000-0x000000009bffffff]
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 113792
[    0.000000] Kernel command line: console=ttyS4,115200n8 root=/dev/ram rw
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:all(zero), heap alloc:off, heap free:off
[    0.000000] Memory: 409628K/458752K available (7168K kernel code, 669K rwdata, 1504K rodata, 1024K init, 150K bss, 16356K reserved, 32768K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 23708 entries in 47 pages
[    0.000000] ftrace: allocated 47 pages with 5 groups
[    0.000000] trace event string verifier disabled
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] i2c controller registered, irq 17
[    0.000000] clocksource: FTTMR010-TIMER2: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 77222644334 ns
[    0.000214] sched_clock: 32 bits at 25MHz, resolution 40ns, wraps every 86767015915ns
[    0.002174] Switching to timer-based delay loop, resolution 40ns
[    0.006945] Calibrating delay loop (skipped), value calculated using timer frequency.. 49.50 BogoMIPS (lpj=247500)
[    0.007246] pid_max: default: 32768 minimum: 301
[    0.011712] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.011797] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.046027] CPU: Testing write buffer coherency: ok
[    0.062450] cblist_init_generic: Setting adjustable number of callback queues.
[    0.062695] cblist_init_generic: Setting shift to 0 and lim to 1.
[    0.063208] cblist_init_generic: Setting shift to 0 and lim to 1.
[    0.064688] Setting up static identity map for 0x80100000 - 0x80100038
[    0.067889] ASPEED AST2500 rev A1 (04010303)
[    0.077892] devtmpfs: initialized
[    0.101303] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.101474] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.105301] pinctrl core: initialized pinctrl subsystem
[    0.129594] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.138982] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.144018] hw-breakpoint: debug architecture 0x0 unsupported.
[    0.236740] mc: Linux media interface: v0.10
[    0.236931] videodev: Linux video capture interface: v2.00
[    0.237122] pps_core: LinuxPPS API ver. 1 registered
[    0.237171] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.237294] PTP clock support registered
[    0.270647] clocksource: Switched to clocksource FTTMR010-TIMER2
[    0.320654] NET: Registered PF_INET protocol family
[    0.322369] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.327788] tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.327999] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.328085] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.328232] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.328395] TCP: Hash tables configured (established 4096 bind 4096)
[    0.329501] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.329716] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.331284] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.338628] Unpacking initramfs...
[    0.366921] workingset: timestamp_bits=30 max_order=17 bucket_order=0
[    0.372882] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.372932] jffs2: version 2.2. (SUMMARY)  © 2001-2006 Red Hat, Inc.
[    0.401253] Serial: 8250/16550 driver, 6 ports, IRQ sharing enabled
[    0.412299] printk: console [ttyS4] disabled
[    0.414084] 1e784000.serial: ttyS4 at MMIO 0x1e784000 (irq = 20, base_baud = 1500000) is a 16550A
[    0.458806] printk: console [ttyS4] enabled
[    0.476634] timeriomem_rng 1e6e2078.hwrng: 32bits from 0x(ptrval) @ 1us
[    0.483621] aspeed_gfx 1e6e6000.display: assigned reserved memory node framebuffer
[    0.605387] [drm] Initialized aspeed-gfx-drm 1.0.0 20180319 for 1e6e6000.display on minor 0
[    0.646741] aspeed_gfx 1e6e6000.display: [drm] fb0: aspeed-gfx-drmd frame buffer device
[    0.738211] loop: module loaded
[    0.747445] random: crng init done
[    0.858234] spi-nor spi0.0: w25q256 (32768 Kbytes)
[    1.054518] spi-aspeed-smc 1e620000.spi: CE0 read buswidth:2 [0x203b0641]
[    1.335301] 5 fixed-partitions partitions found on MTD device bmc
[    1.335900] Creating 5 MTD partitions on "bmc":
[    1.336461] 0x000000000000-0x000000060000 : "u-boot"
[    1.353370] 0x000000060000-0x000000080000 : "u-boot-env"
[    1.356717] 0x000000080000-0x0000004c0000 : "kernel"
[    1.359362] 0x0000004c0000-0x000001c00000 : "rofs"
[    1.362251] 0x000001c00000-0x000002000000 : "rwfs"
[    1.397819] spi-nor spi1.0: mx25l25635e (32768 Kbytes)
[    1.403114] spi-aspeed-smc 1e630000.spi: Calibration area too uniform, using low speed
[    1.403423] spi-aspeed-smc 1e630000.spi: CE0 read buswidth:2 [0x203b0041]
[    1.457521] ftgmac100 1e660000.ethernet: Read MAC address c0:ff:ee:00:00:02 from chip
[    1.466379] RTL8211E Gigabit Ethernet 1e660000.ethernet--1:00: attached PHY driver (mii_bus:phy_addr=1e660000.ethernet--1:00, irq=POLL)
[    1.472401] ftgmac100 1e660000.ethernet eth0: irq 22, mapped at (ptrval)
[    1.473997] ftgmac100 1e680000.ethernet: Generated random MAC address b6:17:d5:1b:f7:76
[    1.488370] Generic PHY 1e680000.ethernet--1:00: attached PHY driver (mii_bus:phy_addr=1e680000.ethernet--1:00, irq=POLL)
[    1.492921] ftgmac100 1e680000.ethernet eth1: irq 23, mapped at (ptrval)
[    1.594809] aspeed_vhub 1e6a0000.usb-vhub: Initialized virtual hub in USB2 mode
[    1.597399] Mass Storage Function, version: 2009/09/11
[    1.597876] LUN: removable file: (no medium)
[    1.599190] no file given for LUN0
[    1.600094] udc 1e6a0000.usb-vhub:p1: failed to start g_mass_storage: -22
[    1.601069] g_mass_storage: probe of gadget.0 failed with error -22
[    1.601487] Mass Storage Function, version: 2009/09/11
[    1.601649] LUN: removable file: (no medium)
[    1.601848] no file given for LUN0
[    1.602033] udc 1e6a0000.usb-vhub:p2: failed to start g_mass_storage: -22
[    1.602238] g_mass_storage: probe of gadget.1 failed with error -22
[    1.602490] Mass Storage Function, version: 2009/09/11
[    1.602627] LUN: removable file: (no medium)
[    1.602733] no file given for LUN0
[    1.602815] udc 1e6a0000.usb-vhub:p3: failed to start g_mass_storage: -22
[    1.602931] g_mass_storage: probe of gadget.2 failed with error -22
[    1.603183] Mass Storage Function, version: 2009/09/11
[    1.603299] LUN: removable file: (no medium)
[    1.603493] no file given for LUN0
[    1.603620] udc 1e6a0000.usb-vhub:p4: failed to start g_mass_storage: -22
[    1.603762] g_mass_storage: probe of gadget.3 failed with error -22
[    1.603936] Mass Storage Function, version: 2009/09/11
[    1.604028] LUN: removable file: (no medium)
[    1.604226] no file given for LUN0
[    1.604394] udc 1e6a0000.usb-vhub:p5: failed to start g_mass_storage: -22
[    1.604595] g_mass_storage: probe of gadget.4 failed with error -22
[    1.604945] UDC core: g_mass_storage: couldn't find an available UDC
[    1.605600] i2c_dev: i2c /dev entries driver
[    1.639668] at24 3-0050: 1024 byte 24c08 EEPROM, writable, 16 bytes/write
[    1.641306] aspeed-i2c-bus 1e78a100.i2c-bus: i2c bus 3 registered, irq 25
[    1.651877] aspeed-i2c-bus 1e78a300.i2c-bus: i2c bus 7 registered, irq 26
[    1.653070] Driver for 1-wire Dallas network protocol.
[    1.657000] lm75 7-004d: hwmon0: sensor 'lm75'
[    1.659472] SPI driver bmp280 has no spi_device_id for bosch,bmp085
[    1.666632] NET: Registered PF_INET6 protocol family
[    1.737896] Segment Routing with IPv6
[    1.738727] In-situ OAM (IOAM) with IPv6
[    1.741272] NET: Registered PF_PACKET protocol family
[    1.741766] 8021q: 802.1Q VLAN Support v1.8
[    1.832268] printk: console [netcon0] enabled
[    1.832709] netconsole: network logging started
[    2.018386] Freeing initrd memory: 1060K
[    2.058697] Freeing unused kernel image (initmem) memory: 1024K
[    2.068793] Checked W+X mappings: passed, no W+X pages found
[    2.069811] Run /init as init process
rofs = mtd4 squashfs   rwfs = mtd5 jffs2
[    4.834311] jffs2: Empty flash at 0x00339930 ends at 0x00339a00
[    4.834766] jffs2: jffs2_scan_eraseblock(): Magic bitmask 0x1985 not found at 0x00339a0c: 0xd89b instead
[    4.855768] jffs2: notice: (84) jffs2_build_xattr_subsystem: complete building xattr subsystem, 379 of xdatum (3 unchecked, 376 orphan) and 380 of xref (376 dead, 0 orphan) found.
find: run/initramfs/rw/cow/var/lib/systemd/random-seed: No such file or directory
Fri Mar  9 12:35:01 UTC 2018
[    5.302613] overlayfs: upper fs does not support tmpfile.
[    5.305641] overlayfs: upper fs does not support RENAME_WHITEOUT.
[    8.235268] systemd[1]: System time before build time, advancing clock.
[    8.602802] systemd[1]: systemd 253.3^ running in system mode (+PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL -ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC -KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON -UTMP -SYSVINIT default-hierarchy=unified)
[    8.615061] systemd[1]: Detected architecture arm.

Welcome to Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.15.0-dev!

[    8.694330] systemd[1]: Hostname set to <evb-ast2500>.
[    9.039562] systemd[1]: Using hardware watchdog 'aspeed_wdt', version 0, device /dev/watchdog0
[    9.071766] systemd[1]: Watchdog running with a timeout of 2min.
[    9.073320] systemd[1]: Watchdog: reading from /sys/dev/char/247:0/pretimeout_governor
[    9.075897] systemd[1]: Watchdog: failed to read pretimeout governor: No such file or directory
[    9.077442] systemd[1]: Watchdog: setting pretimeout_governor to 'panic' via '/sys/dev/char/247:0/pretimeout_governor'
[    9.078702] systemd[1]: Failed to set pretimeout_governor to 'panic': No such file or directory
[    9.079269] systemd[1]: Failed to set watchdog pretimeout governor to 'panic', ignoring: No such file or directory

U-Boot 2019.04 (May 30 2023 - 06:05:47 +0000)

SOC : AST2500-A1 
RST : Power On 
LPC Mode : SIO:Enable : SuperIO-2e
Eth : MAC0: RGMII, , MAC1: RGMII, 
Model: AST2500 EVB
DRAM:  448 MiB (capacity:512 MiB, VGA:64 MiB, ECC:off)
MMC:   sdhci_slot0@100: 0, sdhci_slot1@200: 1
Loading Environment from SPI Flash... SF: Detected w25q256 with page size 256 Bytes, erase size 4 KiB, total 32 MiB
OK
In:    serial@1e784000
Out:   serial@1e784000
Err:   serial@1e784000
Net:   eth0: ethernet@1e660000
Warning: ethernet@1e680000 (eth1) using random MAC address - fa:c9:e6:4e:b3:86
, eth1: ethernet@1e680000
Hit any key to stop autoboot:  0 
## Loading kernel from FIT Image at 20080000 ...
   Using 'conf-aspeed-ast2500-evb.dtb' configuration
   Trying 'kernel-1' kernel subimage
     Description:  Linux kernel
     Type:         Kernel Image
     Compression:  uncompressed
     Data Start:   0x2008012c
     Data Size:    3083360 Bytes = 2.9 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: 0x80001000
     Entry Point:  0x80001000
     Hash algo:    sha256
     Hash value:   c1ed2b6ee1b997739ffd46f80e73f2a65a01389a571c2afad28632a2d11cf29c
   Verifying Hash Integrity ... sha256+ OK
## Loading ramdisk from FIT Image at 20080000 ...
   Using 'conf-aspeed-ast2500-evb.dtb' configuration
   Trying 'ramdisk-1' ramdisk subimage
     Description:  obmc-phosphor-initramfs
     Type:         RAMDisk Image
     Compression:  uncompressed
     Data Start:   0x20377a1c
     Data Size:    1082032 Bytes = 1 MiB
     Architecture: ARM
     OS:           Linux
     Load Address: unavailable
     Entry Point:  unavailable
     Hash algo:    sha256
     Hash value:   01a609ad06481fc8ea58318f4c1115d3ac339a9ba3fa73786d6092280b47b915
   Verifying Hash Integrity ... sha256+ OK
## Loading fdt from FIT Image at 20080000 ...
   Using 'conf-aspeed-ast2500-evb.dtb' configuration
   Trying 'fdt-aspeed-ast2500-evb.dtb' fdt subimage
     Description:  Flattened Device Tree blob
     Type:         Flat Device Tree
     Compression:  uncompressed
     Data Start:   0x20370ea0
     Data Size:    27311 Bytes = 26.7 KiB
     Architecture: ARM
     Hash algo:    sha256
     Hash value:   dd954d39662a2217b3b1b835554d5e22d8e8729174f8c53532327f425eb55a7e
   Verifying Hash Integrity ... sha256+ OK
   Booting using the fdt blob at 0x20370ea0
   Loading Kernel Image ... OK
   Loading Ramdisk to 8fef7000, end 8ffff2b0 ... OK
   Loading Device Tree to 8feed000, end 8fef6aae ... OK

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.1.29-1ac953d (oe-user@oe-host) (arm-openbmc-linux-gnueabi-gcc (GCC) 13.1.1 20230520, GNU ld (GNU Binutils) 2.40.0.20230419) #1 Mon May 22 00:13:30 UTC 2023
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: VIPT aliasing data cache, unknown instruction cache
[    0.000000] OF: fdt: Machine model: AST2500 EVB

**Comment by williamspatrick** [comment]
What code version did you build from and how did you select the build?

**Comment by AmirRMoezi** [comment]
> What code version did you build from and how did you select the build?

Sorry I do not know what you mean. How can I find that? I built from the current openbmc source code and followed the exact tutorial on https://github.com/openbmc/openbmc. I selected obmc-phosphor-image for evb-ast2500 target.

**Comment by williamspatrick** [comment]
`git describe --dirty && git diff` would be useful for us to confirm which commit you are building from.

I assume by "selected obmc-phosphor-image for evb-ast2500 target" you mean you did:

`source setup evb-ast2500 && bitbake obmc-phosphor-image`?

> obmc-phosphor-image-evb-ast2500-20230612144736.static.mtd

The numbers at the end are just a timestamp when the image was built, so that isn't very useful for knowing what is present in it.

**Comment by williamspatrick** [comment]
I suspect you also asked this question on Discord today?

This was my response there: https://discord.com/channels/775381525260664832/775694683589574659/1124813137531641917

**Comment by AmirRMoezi** [comment]
This is the output of "git describe --dirty":
2.15.0-dev-345-g15c7c77bf-dirty

and this is a part of the output of "git diff" :

diff --git a/.eslintrc.json b/.eslintrc.json
old mode 100644
new mode 100755
diff --git a/.github/ISSUE_TEMPLATE/bug_report.md b/.github/ISSUE_TEMPLATE/bug_report.md
old mode 100644
new mode 100755
diff --git a/.github/ISSUE_TEMPLATE/question.md b/.github/ISSUE_TEMPLATE/question.md
old mode 100644
new mode 100755
diff --git a/.github/pull_request_template.md b/.github/pull_request_template.md
old mode 100644
new mode 100755
diff --git a/.github/stale.yml b/.github/stale.yml
old mode 100644
new mode 100755
diff --git a/.gitignore b/.gitignore
old mode 100644
new mode 100755
diff --git a/.gitreview b/.gitreview
old mode 100644
new mode 100755
diff --git a/OWNERS b/OWNERS
old mode 100644
new mode 100755
diff --git a/README.md b/README.md
old mode 100644
new mode 100755
diff --git a/meta-amd/COPYING.MIT b/meta-amd/COPYING.MIT
old mode 100644
new mode 100755
diff --git a/meta-amd/COPYING.apache-2.0 b/meta-amd/COPYING.apache-2.0
old mode 100644
new mode 100755
diff --git a/meta-amd/LICENSE b/meta-amd/LICENSE
old mode 100644
new mode 100755
diff --git a/meta-amd/OWNERS b/meta-amd/OWNERS
old mode 100644
new mode 100755
diff --git a/meta-amd/README.md b/meta-amd/README.md
old mode 100644
new mode 100755
...


---------------------------------------------------------------------------------
and about the next question: Yes. I did "source setup evb-ast2500 && bitbake obmc-phosphor-image"

**Comment by AmirRMoezi** [comment]
> I suspect you also asked this question on Discord today?
> 
> This was my response there: https://discord.com/channels/775381525260664832/775694683589574659/1124813137531641917

Yes. I also asked the question on Discord. I am going to answer your question there

**Comment by williamspatrick** [comment]
```
diff --git a/meta-amd/README.md b/meta-amd/README.md
old mode 100644
new mode 100755
```

Any idea what is the deal with all of these permission changes?  What kind of OS are you building on?  If this is WSL, it wouldn't surprise me if it doesn't work as I'm not sure anyone has actively worked on testing it there.

**Comment by AmirRMoezi** [comment]
> ```
> diff --git a/meta-amd/README.md b/meta-amd/README.md
> old mode 100644
> new mode 100755
> ```
> 
> Any idea what is the deal with all of these permission changes? What kind of OS are you building on? If this is WSL, it wouldn't surprise me if it doesn't work as I'm not sure anyone has actively worked on testing it there.

I remember I had encountered an error during openbmc building process. The error description was nearly "The postinstall intercept hook 'update_gio_module_cache' failed" as far as I remember. So, after googling it, I found a solution which was running the command "git restore poky" in openbmc root directory. After running the command, the problem solved and there was no error again. I remember from my searches that this command relates to permissions. can it be the cause of "all of these permission changes"?

**Comment by williamspatrick** [comment]
I don't know what `git restore poky` would have done in this context.  Probably nothing good, because we don't use a raw poky tree.  I'd suggest resetting your image back to non-dirty and showing what the issues are you're finding.

You might as well do a git fetch / git rebase to ensure your repository is up to date.  It appears to almost be a month old based on the commit number you listed.

```
$ git rev-list origin/master "^15c7c77bfe" | wc -l
116
$ git log 15c7c77bfe -n1 | grep Date  
Date:   Fri Jun 9 14:20:28 2023 -0500
```

**Comment by AmirRMoezi** [comment]
Finally, I found the solution of my problem. It relates to permission of files located in this path: 
openbmc/poky/scripts/postinst-intercepts
Their permission should be changed to 644. Then, after executing bitbake command again, OpenBMC will be simulated successfully and without any error.
