### ISSUE TITLE
Only show Unauthorized in WebUI for OpenBMC evb-ast2600

### ISSUE THREAD

**Issue by MinzChan** [openbmc/openbmc#3939]
Hi，
 I have just completed the compilation of evb-ast2600 and qemu. When I run qemu, the webpage only displays Unauthorized. What is the problem?
![image](https://github.com/openbmc/openbmc/assets/38336434/24b4d11d-f2ff-48f2-990d-2c0bc0917bb5)

**Comment by williamspatrick** [comment]
Usually this means that the webui package was not included in the image.  I don’t think it is enabled by default on EVBs because they have pretty limited function to begin with so much of the webui won’t even do anything.
