### ISSUE TITLE
Boot failure with evb-ast2600

### ISSUE THREAD

**Issue by Ma5300408** [openbmc/openbmc#3941]
I have built a image with  u-boot version **Aspeed-v2019.04** and Linux version **Linux-dev6.1.29** , demo board nor-flash using macronix **mx25l51245g** . 
First, I show the board information in the first paragraph. Then I show the problem I met , can anyone tell me some information to fix this situation ? Log said Squashfs have some issue , but the filesystem type in **rofs = mtd4 squashfs**   rwfs = mtd5 jffs2 Is auto generated by Yocto project bitbake , I didn't touch this part after image built . 

> U-Boot SPL 2019.04 (May 15 2023 - 08:09:51 +0000)
> Trying to boot from RAM
> 
> U-Boot 2019.04 (May 15 2023 - 08:09:51 +0000)
> 
> SOC: AST2620-A3 
> RST: Power On 
> eSPI Mode: SIO:Enable : SuperIO-2e
> Eth: MAC0: RMII/NCSI, MAC1: RMII/NCSI, MAC2: RMII/NCSI, MAC3: RMII/NCSI
> Model: AST2600 EVB
> DRAM:  already initialized, 1 GiB (capacity:1024 MiB, VGA:0 MiB, ECC:off)
> MMC:   
> sdhci_slot0@100: 1, sdhci_slot1@200: 2, emmc_slot0@100: 0
> Loading Environment from SPI Flash... SF: Detected mx66l51235l with page size 256 Bytes, erase size 64 KiB, total 64 MiB
>  ***Warning - bad CRC, using default environment
> In:    serial@1e784000
> Out:   serial@1e784000
> Err:   serial@1e784000
> Model: AST2600 EVB
> Net:   Could not get PHY for eth0: addr 0
> Failed to initialize PHY: -19
> eth-1: ftgmac@1e670000Could not get PHY for eth1: addr 0
> Failed to initialize PHY: -19
> , eth-1: ftgmac@1e690000
> Hit any key to stop autoboot:  2  1  0 
>  Loading kernel from FIT Image at 83000000 ...
>    Using 'conf-aspeed-ast2600-evb.dtb' configuration
>    Verifying Hash Integrity ... OK
>    Trying 'kernel-1' kernel subimage
>      Description:  Linux kernel
>      Type:         Kernel Image
>      Compression:  uncompressed
>      Data Start:   0x8300012c
>      Data Size:    3826752 Bytes = 3.6 MiB
>      Architecture: ARM
>      OS:           Linux
>      Load Address: 0x80001000
>      Entry Point:  0x80001000
>      Hash algo:    sha256
>      Hash value:   185b2a38840f05216e81b7650e1f9ee4dfb6eb76e114bfc78cc391e7efc230f7
>    Verifying Hash Integrity ... sha256+ OK
>  Loading ramdisk from FIT Image at 83000000 ...
>    Using 'conf-aspeed-ast2600-evb.dtb' configuration
>    Verifying Hash Integrity ... OK
>    Trying 'ramdisk-1' ramdisk subimage
>      Description:  obmc-phosphor-initramfs
>      Type:         RAMDisk Image
>      Compression:  uncompressed
>      Data Start:   0x833b0504
>      Data Size:    1039504 Bytes = 1015.1 KiB
>      Architecture: ARM
>      OS:           Linux
>      Load Address: unavailable
>      Entry Point:  unavailable
>      Hash algo:    sha256
>      Hash value:   5e1a3fd9d769b8f6a240ca792926612e39a3a5383016d45f7b2979252bae066f
>    Verifying Hash Integrity ... sha256+ OK
>  Loading fdt from FIT Image at 83000000 ...
>    Using 'conf-aspeed-ast2600-evb.dtb' configuration
>    Verifying Hash Integrity ... OK
>    Trying 'fdt-aspeed-ast2600-evb.dtb' fdt subimage
>      Description:  Flattened Device Tree blob
>      Type:         Flat Device Tree
>      Compression:  uncompressed
>      Data Start:   0x833a6680
>      Data Size:    40376 Bytes = 39.4 KiB
>      Architecture: ARM
>      Hash algo:    sha256
>      Hash value:   d5b2851a886a4d2fd626fcb352a64b5edd66a66bf95219f8a6c621af697df2b9
>    Verifying Hash Integrity ... sha256+ OK
>    Booting using the fdt blob at 0x833a6680
>    Loading Kernel Image ... OK
>    Loading Ramdisk to 8ff02000, end 8ffffc90 ... OK
>    Loading Device Tree to 8fef5000, end 8ff01db7 ... OK

---------------------------------------------------------------------------------------------------------------------------------------------------
Welcome to Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.15.0-dev!

[   62.115139] systemd[1]: Hostname set to <evb-ast2600>.
[   62.153313] systemd[1]: Initializing machine ID from random generator.
[   62.271251] systemd[1]: Using hardware watchdog 'aspeed_wdt', version 0, device /dev/watchdog0
[   62.314090] systemd[1]: Watchdog running with a timeout of 2min.
[   62.320962] systemd[1]: Watchdog: reading from /sys/dev/char/247:0/pretimeout_governor
[   62.330023] systemd[1]: Watchdog: failed to read pretimeout governor: No such file or directory
[   62.339887] systemd[1]: Watchdog: setting pretimeout_governor to 'panic' via '/sys/dev/char/247:0/pretimeout_governor'
[   62.352002] systemd[1]: Failed to set pretimeout_governor to 'panic': No such file or directory
[   62.361807] systemd[1]: Failed to set watchdog pretimeout governor to 'panic', ignoring: No such file or directory
[   63.702795] systemd[1]: /lib/systemd/system/phosphor-ipmi-net@.socket:6: Invalid interface name, ignoring: sys-subsystem-net-devices-%i.device
[   63.782260] systemd[1]: Queued start job for default target Multi-User System.
[   63.798000] systemd[1]: Created slice Slice /system/getty.
[  OK  ] Created slice Slice /system/getty.
[   63.839347] systemd[1]: Created slice Slice /system/mapper-wait.
[  OK  ] Created slice Slice /system/mapper-wait.
[   63.879309] systemd[1]: Created slice Slice /system/modprobe.
[  OK  ] Created slice Slice /system/modprobe.
[   63.919350] systemd[1]: Created slice Slice /system/obmc-led-group-start.
[  OK  ] Created slice Slice /system/obmc-led-group-start.
[   63.959367] systemd[1]: Created slice Slice /system/phosphor-certificate-manager.
[  OK  ] Created slice Slice /system/phosphor-certificate-manager.
[   63.999379] systemd[1]: Created slice Slice /system/phosphor-discover-system-state.
[  OK  ] Created slice Slice /syste…hosphor-discover-system-state.
[   64.039398] systemd[1]: Created slice Slice /system/phosphor-ipmi-net.
[  OK  ] Created slice Slice /system/phosphor-ipmi-net.
[   64.079461] systemd[1]: Created slice Slice /system/phosphor-reset-chassis-on.
[  OK  ] Created slice Slice /system/phosphor-reset-chassis-on.
[   64.119449] systemd[1]: Created slice Slice /system/phosphor-reset-chassis-running.
[  OK  ] Created slice Slice /syste…hosphor-reset-chassis-running.
[   64.159509] systemd[1]: Created slice Slice /system/phosphor-reset-host-running.
[  OK  ] Created slice Slice /system/phosphor-reset-host-running.
[   64.199425] systemd[1]: Created slice Slice /system/serial-getty.
[  OK  ] Created slice Slice /system/serial-getty.
[   64.239457] systemd[1]: Created slice Slice /system/xyz.openbmc_project.State.Chassis.
[  OK  ] Created slice Slice /syste…openbmc_project.State.Chassis.
[   64.279460] systemd[1]: Created slice Slice /system/xyz.openbmc_project.State.Host.
[  OK  ] Created slice Slice /syste…yz.openbmc_project.State.Host.
[   64.317762] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Started Dispatch Password …ts to Console Directory Watch.
[   64.357683] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Started Forward Password R…uests to Wall Directory Watch.
[   64.398252] systemd[1]: Reached target Host0 running after reset.
[  OK  ] Reached target Host0 running after reset.
[   64.437465] systemd[1]: Reached target Path Units.
[  OK  ] Reached target Path Units.
[   64.477431] systemd[1]: Reached target Remote File Systems.
[  OK  ] Reached target Remote File Systems.
[   64.517345] systemd[1]: Reached target Slice Units.
[  OK  ] Reached target Slice Units.
[   64.557555] systemd[1]: Reached target Swaps.
[  OK  ] Reached target Swaps.
[   64.601954] systemd[1]: Listening on Syslog Socket.
[  OK  ] Listening on Syslog Socket.
[   64.652361] systemd[1]: Listening on Process Core Dump Socket.
[  OK  ] Listening on Process Core Dump Socket.
[   64.687837] systemd[1]: Journal Audit Socket was skipped because of an unmet condition check (ConditionSecurity=audit).
[   64.701020] systemd[1]: Listening on Journal Socket (/dev/log).
[  OK  ] Listening on Journal Socket (/dev/log).
[   64.738256] systemd[1]: Listening on Journal Socket.
[  OK  ] Listening on Journal Socket.
[   64.778447] systemd[1]: Listening on Network Service Netlink Socket.
[  OK  ] Listening on Network Service Netlink Socket.
[   64.819844] systemd[1]: Listening on udev Control Socket.
[  OK  ] Listening on udev Control Socket.
[   64.858171] systemd[1]: Listening on udev Kernel Socket.
[  OK  ] Listening on udev Kernel Socket.
[   64.898138] systemd[1]: Huge Pages File System was skipped because of an unmet condition check (ConditionPathExists=/sys/kernel/mm/hugepages).
[   64.913201] systemd[1]: POSIX Message Queue File System was skipped because of an unmet condition check (ConditionPathExists=/proc/sys/fs/mqueue).
[   64.977493] systemd[1]: Mounting Kernel Debug File System...
         Mounting Kernel Debug File System...
[   65.020841] systemd[1]: Mounting Kernel Trace File System...
         Mounting Kernel Trace File System...
[   65.061756] systemd[1]: Mounting Temporary Directory /tmp...
         Mounting Temporary Directory /tmp...
[   65.104377] systemd[1]: Starting Load Kernel Module configfs...
         Starting Load Kernel Module configfs...
[   65.187872] systemd[1]: Starting Load Kernel Module efi_pstore...
         Starting Load Kernel Module efi_pstore...
[   65.243884] systemd[1]: Starting Load Kernel Module fuse...
         Starting Load Kernel Module fuse...
[   65.294241] systemd[1]: File System Check on Root Device was skipped because of an unmet condition check (ConditionPathIsReadWrite=!/).
[   65.447963] systemd[1]: Starting Journal Service...
         Starting Journal Service...
[   65.492158] systemd[1]: Starting Generate network units from Kernel command line...
         Starting Generate network …ts from Kernel command line...
[   65.573965] systemd[1]: Starting Remount Root and Kernel File Systems...
[   65.581922] systemd-journald[142]: Collecting audit messages is disabled.
         Starting Remount Root and Kernel File Systems...
[   65.632619] systemd[1]: Starting Apply Kernel Variables...
         Starting Apply Kernel Variables...
[   65.674710] systemd[1]: Starting Coldplug All udev Devices...
         Starting Coldplug All udev Devices...
[   65.769690] systemd[1]: Mounted Kernel Debug File System.
[  OK  ] Mounted Kernel Debug File System.
[   65.798267] systemd[1]: Mounted Kernel Trace File System.
[  OK  ] Mounted Kernel Trace File System.
[   65.822123] systemd[1]: Mounted Temporary Directory /tmp.
[  OK  ] Mounted Temporary Directory /tmp.
[   65.878483] systemd[1]: Started Journal Service.
[  OK  ] Started Journal Service.
[  OK  ] Finished Load Kernel Module configfs.
[  OK  ] Finished Load Kernel Module efi_pstore.
[  OK  ] Finished Load Kernel Module fuse.
[  OK  ] Finished Generate network units from Kernel command line.
[  OK  ] Finished Remount Root and Kernel File Systems.
[  OK  ] Finished Apply Kernel Variables.
[  OK  ] Reached target Preparation for Network.
         Mounting Kernel Configuration File System...
         Starting Rebuild Hardware Database...
         Starting Flush Journal to Persistent Storage...
         Starting Create System Users...
[   66.343303] systemd-journald[142]: Received client request to flush runtime journal.
[  OK  ] Finished Coldplug All udev Devices.
[  OK  ] Mounted Kernel Configuration File System.
[  OK  ] Finished Rebuild Hardware Database.
[  OK  ] Finished Flush Journal to Persistent Storage.
[  OK  ] Finished Create System Users.
         Starting Create Static Device Nodes in /dev...
[  OK  ] Finished Create Static Device Nodes in /dev.
[  OK  ] Reached target Preparation for Local File Systems.
         Mounting /var/volatile...
         Starting Rule-based Manage…for Device Events and Files...
[  OK  ] Mounted /var/volatile.
         Starting Load/Save OS Random Seed...
[  OK  ] Reached target Local File Systems.
         Starting Create Volatile Files and Directories...
[  OK  ] Finished Load/Save OS Random Seed.
[  OK  ] Started Rule-based Manager for Device Events and Files.
         Starting Network Configuration...
[  OK  ] Finished Create Volatile Files and Directories.
[  OK  ] Started Network Configuration.
[  OK  ] Created slice Slice /system/obmc-console.
[  OK  ] Created slice Slice /system/xyz.openbmc_project.Hwmon.
[  OK  ] Created slice Slice /syste…penbmc_project.led.controller.
[  OK  ] Reached target Hardware activated USB gadget.
         Starting Load Kernel Module efi_pstore...
         Starting Load Kernel Module fuse...
         Starting Rebuild Journal Catalog...
         Starting Wait for Network to be Configured...
         Starting Network Name Resolution...
         Starting Network Time Synchronization...
[  OK  ] Finished Load Kernel Module efi_pstore.
[  OK  ] Finished Load Kernel Module fuse.
[  OK  ] Finished Rebuild Journal Catalog.
[  OK  ] Finished Wait for Network to be Configured.
         Starting Update is Completed...
[  OK  ] Finished Update is Completed.
[  OK  ] Started Network Time Synchronization.
[  OK  ] Reached target System Time Set.
[  OK  ] Started Network Name Resolution.
[  OK  ] Reached target Network.
[  OK  ] Reached target Network is Online.
[  OK  ] Reached target Host and Network Name Lookups.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Daily rotation of log files.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Timer Units.
[  OK  ] Listening on Avahi mDNS/DNS-SD Stack Activation Socket.
[  OK  ] Listening on BMC Webserver socket.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Listening on dropbear.socket.
[  OK  ] Listening on Phosphor Host…ole SSH Per-Connection socket.
[  OK  ] Reached target Socket Units.
         Starting D-Bus System Message Bus...
[  OK  ] Started D-Bus System Message Bus.
[  OK  ] Reached target Basic System.
         Starting Avahi mDNS/DNS-SD Stack...
[  OK  ] Started Start bmcweb server.
         Starting Clear one time boot overrides...
         Starting Convert PAM config files...
         Starting SSH Key Generation...
         Starting Name Service Cache Daemon...
[  OK  ] Started Phosphor Dump core monitor..
[  OK  ] Started Phosphor certificate manager for authority.
[  OK  ] Started Phosphor certificate manager for bmcweb.
[  OK  ] Started Phosphor certificate manager for nslcd.
         Starting BMC health monitoring...
         Starting System Logging Service...
[  OK  ] Started Lightweight SLP Server.
         Starting OpenBMC ipKVM daemon...
         Starting Permit User Sessions...
         Starting Enable Linux trace events in the boot loader...
         Starting Phosphor Dump Manager...
[  OK  ] Started Fru Device.
**[   72.381031] SQUASHFS error: xz decompression failed, data probably corrupt
[   72.388886] SQUASHFS error: Failed to read block 0x622f28: -5**
         Starting Phosphor Inventory Manager...
         Starting Phosphor LED Group Management Daemon...
         Starting Phosphor Log Manager...
**[   72.687812] SQUASHFS error: xz decompression failed, data probably corrupt
[   72.695809] SQUASHFS error: Failed to read block 0x62e7ec: -5**
         Starting Phosphor Network Manager...
         Starting Phosphor DBus Service Discovery Manager...
         Starting Phosphor Settings Daemon...
         Starting OpenBMC Software Update Manager...
         Starting Phosphor Download Manager...
         Starting Phosphor Chassis0 State Manager...
         Starting Rsyslog config updater...
         Starting Telemetry...
         Starting Phosphor User Manager...
[  OK  ] Started Phosphor sysfs LED controller.
[  OK  ] Finished Convert PAM config files.
**[   73.359851] SQUASHFS error: xz decompression failed, data probably corrupt
[   73.367609] SQUASHFS error: Failed to read block 0x62e7ec: -5
[   73.374035] SQUASHFS error: Unable to read data cache entry [62e7ec]
[   73.381229] SQUASHFS error: Unable to read page, block 62e7ec, size b310
[   73.389620] SQUASHFS error: Unable to read data cache entry [62e7ec]
[   73.389636] SQUASHFS error: Unable to read page, block 62e7ec, size b310**
[  OK  ] Started Name Service Cache Daemon.
[  OK  ] Started OpenBMC ipKVM daemon.
[  OK  ] Finished Permit User Sessions.
[  OK  ] Finished Enable Linux trace events in the boot loader.
[  OK  ] Started BMC health monitoring.
[  OK  ] Started Phosphor Download Manager.
[  OK  ] Finished Clear one time boot overrides.
[  OK  ] Started Phosphor Log Manager.
[  OK  ] Started Avahi mDNS/DNS-SD Stack.
[  OK  ] Started Serial Getty on ttyS4.
[  OK  ] Reached target Login Prompts.
         Starting Phosphor Ldap config updater...
[  OK  ] Started Rsyslog config updater.
[  OK  ] Started System Logging Service.
[  OK  ] Started Phosphor DBus Service Discovery Manager.
[   75.122926] SQUASHFS error: xz decompression failed, data probably corrupt
[   75.130745] SQUASHFS error: Failed to read block 0x86a948: -5
[  OK  ] Started Phosphor Settings Daemon.
[  OK  ] Started Phosphor Dump Manager.
**[   75.315530] SQUASHFS error: xz decompression failed, data probably corrupt
[   75.323324] SQUASHFS error: Failed to read block 0x87f930: -5
[   75.391061] SQUASHFS error: xz decompression failed, data probably corrupt
[   75.398950] SQUASHFS error: Failed to read block 0x886fbc: -5
[   75.491517] SQUASHFS error: xz decompression failed, data probably corrupt
[   75.499346] SQUASHFS error: Failed to read block 0x886fbc: -5
[   75.505825] SQUASHFS error: Unable to read data cache entry [886fbc]
[   75.512973] SQUASHFS error: Unable to read page, block 886fbc, size 6cbc
[   75.520552] SQUASHFS error: Unable to read data cache entry [886fbc]
[   75.527707] SQUASHFS error: Unable to read page, block 886fbc, size 6cbc**

**Comment by williamspatrick** [comment]
What image did you flash onto the module?  The log is that the image is corrupted. Either:

- Something went wrong in the build process. 
- You flashed on the wrong image and left partial data from a previous image. 
- Something went wrong in your flashing process. 
- Your NOR chip is bad. 
- Your board is having bad signal integrity between the BMC and NOR chip.

**Comment by IgorLinux1990** [comment]
How you solved this problem, thnaks?
