### ISSUE TITLE
Inconsistency in MAC address persistency

### ISSUE THREAD

**Issue by cm-jishnu** [openbmc/openbmc#3942]
**Unexpected behaviour you saw**
Though the "persist-mac" is enabled by default, Updated MAC address
is not persisted across reboot on all interfaces.

**Expected behaviour**
Consistent behaviour on all ethernet interfaces.
If "persist-mac" doesn't promise persistency across reboot then the
behaviour should be the same for all interfaces.

**To Reproduce**
Steps to reproduce the behaviour:
1. Update the MAC address through redfish or bustle command
2. Verify the MAC address is updated in d-bus and network config file
3. Reboot the system
4. Check the MAC address value of all interfaces

**Screenshots**

**OpenBMC Information:**
 - /etc/os-release:
 - uname -a:
 - Any additional patches or changes:

**Additional context**

**Comment by cm-jishnu** [comment]
@sunharis

**Comment by williamspatrick** [comment]
You didn’t fill out half the information in this template, like what version you are running. 


Which interfaces are working and which aren’t?  Is it only eth0 that works?

Isn’t there a config file in phosphor-networkd that controls which interfaces this is enabled for (and where/how to obtain the data for them)?

**Comment by williamspatrick** [comment]
No response from originator.
