### ISSUE TITLE
Update image using Redfish curl - TFTP

### ISSUE THREAD

**Issue by Saravanans2001** [openbmc/openbmc#3949]
Hi all,
   To upgrade the firmware, I am using Redfish and the following curl command over TFTP.

curl -b cjar -k -u root:0penBmc -H "Content-Type: application/json" -X POST -d '{"TransferProtocol":"TFTP","ImageURI":"192.168.1.80/obmc-phosphor-image-evb-ast2600-20230824064748.static.mtd.tar"}' [172.20.48.110/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate](https://172.20.48.110/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate)

In postman tool ,I initially encounter the 503 service unavailable error before encountering the 500 internal server error.
![Screenshot from 2023-08-28 12-30-31](https://github.com/openbmc/openbmc/assets/139228548/dddc1210-c85e-4440-ab41-6ed633e8350f)
![Screenshot from 2023-08-28 18-00-05](https://github.com/openbmc/openbmc/assets/139228548/de85c97d-7a14-484a-ba7d-83bcab8410c2)

1.How to overcome the internal service error for tftp?
2.Kindly help me,If i am done wrong .
3.And also ,I have check in journalctl also.

**Comment by williamspatrick** [comment]
Have you tried adding `tftp://` to the ImageURI?

**Comment by Saravanans2001** [comment]
@williamspatrick
Yes It is working
