### ISSUE TITLE
how to realize IPMI command send from KCS to IPMB bridge

### ISSUE THREAD

**Issue by dufan89** [openbmc/openbmc#3950]
Now , my platform has a BMC node and a CPU node  , I send ipmi cmd from SMS side to another BMC node on the other platform to get some info , I send the command as follow:

ipmitool -t 0x7e -b 0 raw 6 4

but, it failed, it reports "Timeout", so why ?? is my send command wrong??

**Comment by williamspatrick** [comment]
Please don’t use GitHub issues for support requests. Email the mailing list. (The issue template says exactly this before you created this issue).
