### ISSUE TITLE
Deprecated-Power-Thermal

### ISSUE THREAD

**Issue by Manikandanrama** [openbmc/openbmc#3953]
Recently we are using  new power thermal subsystem.but i would like to use deprecated-power-thermal.how can i configure that?
i have enable the deprecated thermal in meson_option.txt
i have configure like 
   **-Dredfish-new-powersubsystem-thermalsubsystem=disabled \                
   -Dredfish-allow-deprecated-power-thermal=enabled \**     
in .bb file.  but it not showing anything

**Comment by williamspatrick** [comment]
This is not a bug. Please pay attention to the details in the issue template for further assistance.
