### ISSUE TITLE
BMC  2.14 no inventory

### ISSUE THREAD

**Issue by no-ttn** [openbmc/openbmc#3954]
Hello there,
 
I have installed BMC 2.14 on my ASUS server. RS700A-E11-RS12U 
BIOS MB Model: KMPP-D32. 
BIOS Version:	1401
CPU: AMD EPYC 7313 16-Core Processor 

But when I navigate to system inventory there is no inventory displayed on the page. 
CPU, RAM and HD are not being displayed. So, I can neither gather information nor make a capacity plan or locate my disk (so shall a disk become corrupt there is no way for me to determine which particular disk or DIMM is failing.) 
whereas the sensors can detect the components. the claim that there is a hard drive detected. 

![image](https://github.com/openbmc/openbmc/assets/144731787/0e3abc98-4824-4c10-be81-1e4368a918e4)
![image](https://github.com/openbmc/openbmc/assets/144731787/90eb623f-79f0-4c06-a209-3174ac928176)

**Comment by williamspatrick** [comment]
There are no Asus systems currently supported.  How did you install OpenBMC onto this system?
