### ISSUE TITLE
Firmware update using curl command

### ISSUE THREAD

**Issue by Saravanans2001** [openbmc/openbmc#3955]
Hi All,

Our current board is the evb-ast2600.The "update firmware" option in the OpenBmc webUI is what I used to properly upload my image (obmc-phosphor-*.static.mtd.tar). 

The firmware can be updated in another way.That is the curl approach.
I tried referring to the website below. 
https://www.ibm.com/docs/en/power9?topic=systems-managing-system-by-using-dmtf-redfish-apis
![Screenshot from 2023-09-12 12-44-39](https://github.com/openbmc/openbmc/assets/139228548/aefb2cdd-5941-44df-8ffe-ce1a0d23ad01)

1.This is my curl command 
curl -k -X POST -H "Content-Type: application/json" -d '{ "ImageURI": "tftp://192.168.1.50/obmc-phosph-ast2600-20230827120243.static.mtd.tar"}' -u root:0penBmc https://192.168.1.60/redfish/v1/UpdateService/Actions/UpdateService.SimpleUpdate.
2.This is the error facing
"@Message.ExtendedInfo": [    {      "@odata.type": "#Message.v1_1_1.Message",      "Message": "The request completed successfully.",      "MessageArgs": [],      "MessageId": "Base.1.13.0.Success",      "MessageSeverity": "OK",      "Resolution": "None"    }  ],  "error": {    "@Message.ExtendedInfo": [      {        "@odata.type": "#Message.v1_1_1.Message",        "Message": "The request failed due to an internal service error.  The service is still operational.",        "MessageArgs": [],        "MessageId": "Base.1.13.0.InternalError",        "MessageSeverity": "Critical",        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."      }    ],    "code": "Base.1.13.0.InternalError",    "message": "The request failed due to an internal service error.  The service is still operational."  }

![image](https://github.com/openbmc/openbmc/assets/139228548/cc04d0cc-587e-449a-b5c4-dde591ab720b)

Kindly help me If I done anything wrong.

**Comment by williamspatrick** [comment]
This is a support question and not a bug. See the issue template you deleted for advice on how to obtain support.
