### ISSUE TITLE
qemu-system-arm: device requires 33554432 bytes, block backend provides 23100416 bytes

### ISSUE THREAD

**Issue by AswathSrinivasan** [openbmc/openbmc#3958]
I have builded a new yosemitev2 image but the .mtd provides 23mb file size only which is not running in QEMU.
Error msg : qemu-system-arm: device requires 33554432 bytes, block backend provides 23100416 bytes 
kindly resolve this issue

**Comment by williamspatrick** [comment]
Use a tool like `truncate` to pad out the image to a full 32MB.
