### ISSUE TITLE
Does this OpenBMC fork support Supermicro X10DRU-i+ ?

### ISSUE THREAD

**Issue by GermanAizek** [openbmc/openbmc#3968]
Fork:
https://github.com/openbmc-x10dri/openbmc 

Diff:
https://www.supermicro.com/en/products/motherboard/X10DRU-i+

https://www.supermicro.com/en/products/motherboard/X10DRi

**Comment by williamspatrick** [comment]
We are not a fork.  It appears there has only been the X11SPI system contributed to our tree. 

https://github.com/openbmc/openbmc/tree/master/meta-supermicro

**Comment by GermanAizek** [comment]
@Linux4, What do you say about this? Is your fork ready for merge and is there x10DRU support?
