### ISSUE TITLE
ERROR: petalinux-user-image-1.0-r0 do_rootfs: The postinstall intercept hook 'update_gio_module_cache' failed

### ISSUE THREAD

**Issue by QM1412** [openbmc/openbmc#3973]
ERROR: petalinux-user-image-1.0-r0 do_rootfs: The postinstall intercept hook 'update_gio_module_cache' failed, details in /home/qm1412/petalinux/petalinux_sys/Petalinux_qspi_flash/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/petalinux-user-image/1.0-r0/temp/log.do_rootfs ERROR: petalinux-user-image-1.0-r0 do_rootfs: Function failed: do_rootfs ERROR: Logfile of failure stored in: /home/qm1412/petalinux/petalinux_sys/Petalinux_qspi_flash/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/petalinux-user-image/1.0-r0/temp/log.do_rootfs.114374 ERROR: Task (/home/qm1412/petalinux/petalinux_sys/Petalinux_qspi_flash/project-spec/meta-plnx-generated/recipes-core/images/petalinux-user-image.bb:do_rootfs) failed with exit code '1'

who can tell me how to solve this problem?i don't know how to do it?

**Comment by williamspatrick** [comment]
What is pentalinux?  I don’t see how this is related to OpenBMC except that both are using Yocto?

https://github.com/openbmc/openbmc/blob/713863613bae0280d09adbeb21a326401b4de8ed/meta-phosphor/recipes-core/glib-2.0/glib-2.0%25.bbappend#L4

**Comment by QM1412** [comment]
emmm，I am using zynq7010. I want to build a petalinux environment on the board. I just use the official toolkit to build it and play around.
