### ISSUE TITLE
MCTP over PCIe VDM

### ISSUE THREAD

**Issue by Kendidi** [openbmc/openbmc#3974]
I wonder from Linux host OS, how to send **SPDM via MCTP over PCIe VDM** messages to PCIe device (plugged to a PCIe slot on motherboard) through BMC?  Thanks.

**Comment by mdmillerii** [comment]
Do you have documentation how to send and receive VDM packets from the host bridge?   This will be the first step.

**Comment by williamspatrick** [comment]
This is not a support channel. Please honor the hints in the issue templates.

**Comment by Kendidi** [comment]
> Do you have documentation how to send and receive VDM packets from the host bridge? This will be the first step.

@mdmillerii I do not.   Where can I find those documentation?  Thanks.

**Comment by williamspatrick** [comment]
> > This is not a support channel. Please honor the hints in the issue templates.
> 
> @williamspatrick Where should I post similar question then? Thanks.

please read the following:
https://github.com/openbmc/openbmc/issues/new?assignees=&labels=&projects=&template=question.md&title=
