### ISSUE TITLE
How to enable openssh by default and disable dropbear in OpenBMC?

### ISSUE THREAD

**Issue by leeeening** [openbmc/openbmc#3979]
I currently want to use OpenSSH as the SSH server on OpenBMC and disable Dropbear because OpenSSH can dynamically switch cipher suites and support more algorithm suites.

How should I configure OpenBMC to meet my requirements？

**Comment by williamspatrick** [comment]
Please don't open issues for support / questions.

**Comment by leeeening** [comment]
> Please don't open issues for support / questions.

Got it, thanks.
