### ISSUE TITLE
my browser connect to bmcweb

### ISSUE THREAD

**Issue by DandanXu1007** [openbmc/openbmc#4001]
Why can't my browser connect to bmcweb?

Deploy openbmc image to  raspberrypi 4B successfully , but the browser cannot connect to bmcweb.
![1](https://github.com/openbmc/openbmc/assets/33384437/f1f8d585-8b32-4059-991b-b1d3b30cba8a)
![2](https://github.com/openbmc/openbmc/assets/33384437/9c1f2e3d-686a-4962-87bb-39135b91abae)

the status of bmcweb is running:
<img width="559" alt="3" src="https://github.com/openbmc/openbmc/assets/33384437/bfbccd00-0b6d-465c-b8ba-da7b434905fa">

The log information is as follows:
root@raspberrypi4-64:/etc/default/obmc/watchdog# journalctl -u bmcweb
-- Logs begin at Thu 1970-01-01 00:00:05 UTC, end at Thu 1970-01-01 00:36:37 UTC. --
Jan 01 00:00:06 raspberrypi4-64 systemd[1]: Started Start bmcweb server.
Jan 01 00:00:07 raspberrypi4-64 bmcweb[194]: Checking certs in file /etc/ssl/certs/https/server.pem
Jan 01 00:00:07 raspberrypi4-64 bmcweb[194]: Error in verifying signature, regenerating
Jan 01 00:00:07 raspberrypi4-64 bmcweb[194]: Generating new keys
Jan 01 00:00:07 raspberrypi4-64 bmcweb[194]: Generating EC key
Jan 01 00:00:07 raspberrypi4-64 bmcweb[194]: Generating x509 Certificate

**Comment by williamspatrick** [comment]
Why did you ignore the issue template?

Are you using http or https?  Did the webui get installed in your image?
