### ISSUE TITLE
openbmc 2.14 can cnot use BMCWEB with HTTP？

### ISSUE THREAD

**Issue by jack206** [openbmc/openbmc#4007]
Hi,I want to know is openbmc 2.14 can use BMCWEB with both HTTP and HTTPS or not?

**Comment by williamspatrick** [comment]
Please don't ignore issue templates.  This is not the appropriate forum for questions.

**Comment by jack206** [comment]
> Please don't ignore issue templates. This is not the appropriate forum for questions.
I asked about it in the email and got no reply, so I brought up the bug.
