### ISSUE TITLE
AST2600 MiniDP display issue

### ISSUE THREAD

**Issue by venukovelamudi** [openbmc/openbmc#4008]
Hi Team,

I'm facing AST2600 MiniDP display issue
I have added video node in device tree and created the memory region for video and jpegbuffer
I have checked cat /dev/video0 and it seems getting data
Able to see UEFI shell at debug console logs, but display not working
Can anyone please explain how server communicates with DC-SCM and BMC to send video information to MiniDP

Thanks.

**Comment by williamspatrick** [comment]
Please don't ignore the issue templates.  Github issues are not for support / questions.

I sympathize that you're having an issue that you can't figure out.  You're probably going to need support direct from Aspeed.  Very few people use graphics interfaces and those that do often use the hardware KVM support.

Some of this may be dependent on the specific hardware design you are working from.
