### ISSUE TITLE
AST2500 Fan Tacho Values

### ISSUE THREAD

**Issue by Fnl4Shr** [openbmc/openbmc#4021]
I have 2 fans on my system. When these fans are working at same speed or diferent speed, the receiving tacho values are read correctly. However, when i stop a fan , the tacho value (fanX_input) of this fan is set to tacho value of the other fan. 

My DTS file:

&pwm_tacho {
	status = "okay";
	pinctrl-names = "default";
	pinctrl-0 = <&pinctrl_pwm0_default &pinctrl_pwm1_default>;

	fan@0 {
		reg = <0x00>;
		aspeed,fan-tach-ch = /bits/ 8 <0x00>;
	};
	
	fan@1 {
		reg = <0x01>;
		aspeed,fan-tach-ch = /bits/ 8 <0x01>;
	};
};

**Comment by williamspatrick** [comment]
This is not the correct forum for support.
