### ISSUE TITLE
`source oe-init-build-env` searches user's `$PATH`

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [openbmc/openbmc#4022]
**Unexpected behavior you saw**

Attempting to execute `source setup` from another script resulted in errors when sourcing `oe-init-build-env`.

**Expected behavior**

The `source` command uses `$PATH` to locate the filename, so the same named file from elsewhere on the user's `PATH` can be unexpectedly sourced. If POSIX mode is enabled, then the file is not found, since POSIX mode does not search the CWD.

The code that leads to this error is: [openbmc/setup](https://github.com/openbmc/openbmc/blob/1493fa599fab02a53351d1ac5d291cbaec675771/setup#L78).  Here's an extract of the relevant lines:
``` 
                TEMPLATECONF="${tmpl}/templates/default" source \
                        oe-init-build-env "${build_dir}"
```

To fix this, change it to be:

``` 
                TEMPLATECONF="${tmpl}/templates/default" source \
                        ./oe-init-build-env "${build_dir}"
```

For reference, the bash man page has this to say about it...
```
source filename [arguments]
    ... If filename does not contain a slash, filenames in PATH are used to find the directory containing
    filename. The file searched for in PATH need not be executable.  When bash is not in posix mode, the
    current directory is searched if no file is found in PATH.  If  the  sourcepath  option  to  the  shopt
    builtin  command  is  turned off, the PATH is not searched.
```

**To Reproduce**

Let's assume your PATH contains: `~/bin`,
```
$ cat > ~/bin/oe-init-build-env <<EOF
echo +++ SOURCED FROM THE WRONG DIRECTORY +++
EOF
$ source setup h3
Machine h3 found in meta-abc/meta-h3
+++ SOURCED FROM THE WRONG DIRECTORY +++
```

Now modify the line as described above and rerun `source setup h3`, it behaves as expected.

```
$ source setup h3
Machine h3 found in meta-abc/meta-h3
Common targets are:
     image-h3
```

**OpenBMC Information:**
 - Kirkstone

**Comment by williamspatrick** [comment]
Potential fix here: 

remote:   https://gerrit.openbmc.org/c/openbmc/openbmc/+/76207 setup: prevent PATH based sourcing [NEW]

(When you know what the change is, you can also just submit the fix rather than opening an issue.  That would require you to be part of a CLA for the project though.)
