### ISSUE TITLE
Add kernel config to board layers

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#41]
We should be keeping the Linux kernel configuration in the board specific layers.

We will leave the `aspeed_defconfig` for Kernel developers to customise to their needs, and ensure that the systems have a minimal, secure, configuration.

I'm unsure on the poky bits that need to be done here. If @bradbishop could move the `aspeed_defconfig` config into the tree, I will then follow up with any configuration changes I think we need.

**Comment by bradbishop** [comment]
Done.  https://github.com/openbmc/openbmc/pull/50

**Comment by bradbishop** [comment]
@shenki can this get closed?

**Comment by shenki** [comment]
Have we checked that the config only enables the bits that we need? I can take a look if you want.

I think it would make sense to put the configs in the one file instead of having the hwmon chunk separate.

**Comment by williamspatrick** [comment]
Any idea how this is different from #56 ?

**Comment by bradbishop** [comment]
The concept is the same but the mechanics of doing it in recipes is different.

**Comment by williamspatrick** [comment]
From a design stand-point, Brad and I would prefer config snippets that are based on function being enabled and not always strictly board or SoC specific.  We have ran into an issue recently where the systemd config options were not correctly enabled and it would make more sense to automatically include those config options whenever we enable systemd.

We understand that there is a desire by the kernel developers to be able to quickly see what the config is being used.  A compromise there might be to generate the config and publish it along with our reference flash images.

**Comment by williamspatrick** [comment]
@bradbishop suggested we should close this because it is done and create a new story for a minimal defconfig.  @shenki - any issues with that?

**Comment by shenki** [comment]
Ok. Please assign me to the new issue.
