### ISSUE TITLE
adm1278 sensor scale should not be a float

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#412]
We should handle floats in json/rest, and I have opened https://github.com/openbmc/openbmc/issues/411 for that, but in this case:
https://github.com/openbmc/skeleton/commit/a8260c83d6566fc46832c627ae32c996cfb76ea4

it probably doesn't make much sense to use a float for the scale here.

**Comment by williamspatrick** [comment]
The sensor scale factor should be a +/- 10^N.

**Comment by williamspatrick** [comment]
As in, scale = 2 means (value*10^2)
