### ISSUE TITLE
Cannot reproduce v1.0 tag

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#420]
I was attempting to rebuild v1.0 on openpower.xyz as we had discarded the build.

The barreleye build is failing with the same error I see in #419.  Are we not correctly versioning one of our packages?

```
08:07:43 Computing transaction...error: Can't install skeleton-1.0-r1@armv5e: no package provides libopenbmc_intf.so
```

https://openpower.xyz/job/openbmc-build/131/

**Comment by williamspatrick** [comment]
Effectively a duplicate of #419 .  This is fixed with the 1.0.1 tag, but I don't know why we never saw it before with 1.0 and now we do.
