### ISSUE TITLE
Store device tree in separate partition

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#421]
We want to move to storing the device tree separately from the kernel in the flash. This enables u-boot to perform modifications to the device tree before handing it off to Linux, such as setting the amount of RAM or even NC-SI vs PHY.

Changes required:
- stop building cuImage
- modify flash layout to set aside space for board.dtb
- adjust u-boot environment so it loads the dtb

**Comment by williamspatrick** [comment]
Do we actually need a new partition for this or can we put it into the u-boot image directly?  Can we make a single EXT? fs for the dtb and kernel image?

**Comment by shenki** [comment]
This was before we moved to FIT. Given we're using FIT in the system, we will no longer plan to store the device tree separately.
