### ISSUE TITLE
Implement an RMCP server that handles session handshake.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#429]

**Comment by williamspatrick** [comment]
This should handle encrypted sessions.  Unencrypted, if required by IPMI 2.0, will be done with another story.

**Comment by tomjoseph83** [comment]
- Message Handler
- Message
- Socket Channel
- Sessions Manager
- Session
- Command Table

**Comment by shenki** [comment]
I can't see any commits that add the tests for this code

**Comment by sivassrr** [comment]
@shenki Partially implemented using https://gerrit.openbmc-project.xyz/#/c/395/

**Comment by shenki** [comment]
@sivassrr those are integration tests, which is good

I expect to see unit tests too.
