### ISSUE TITLE
Design and Implement framework for IPMI backend.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#430]
The purpose of this is to come up with a mechanism to share providers between the host-ipmid and the rmcp-ipmid.  Also, update existing providers and host-ipmid to fit this framework.  Demo of this story should be to use an existing host-ipmid provider via the rmcp path.

**Comment by tomjoseph83** [comment]
- [ ]  Separate the commands from the libapphandler that should be executed only from host-ipmid path(For example Read Event Message Buffer, Set BMC Global Enables)
- [ ]  Modify the Command Table to add infrastructure for provider functions
- [ ]  Add code in netipmid to read the libraries and register the provider functions in the /usr/lib/phosphor-net-ipmid
- [ ]   Modify the registration functions in phosphor-host-ipmid to suit netipmid (add privilege levels for the command)
- [ ] Modify the registration functions in ipmi-fru-parser
- [ ] Modify the registration functions in ibm-oem
- [ ] Modify the recipe file/makefile to place the libraries in a common path in install image and create necessary softlinks for phosphor-net-ipmid and phosphor-host-ipmid
- [ ] Create a recipe for phosphor-net-ipmid

**Comment by tomjoseph83** [comment]
phosphor-host-ipmid(5 patches) - https://gerrit.openbmc-project.xyz/#/c/1365
phosphor-host-ipmid(4 patches) - https://gerrit.openbmc-project.xyz/#/c/1020
ipmi-fru-parser - https://gerrit.openbmc-project.xyz/#/c/399/
openpower-host-ipmi-oem - https://gerrit.openbmc-project.xyz/#/c/511/
