### ISSUE TITLE
Framework for SDR conversion to/from dbus objects.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#433]

**Comment by williamspatrick** [comment]
This should be hard coded data structures to express the SDR definition and how they map to something like { type , dbus path }.  Also want to implement a few 'types' so we can see this is a good definition.

**Comment by dkodihal** [comment]
Given #434, I would say this is just a policy to map a sensor id to a d-bus object. This is sounding like 2 points, @tomjoseph83 agrees. Are we missing something here?

Once we have #434 and this one, the next step would be #441, and maybe that should be more like 4 points given all the backend is getting ready in these stories.
