### ISSUE TITLE
IBM Milestone 2 : IPMI 2.0 : Generate SDR definition from MRW.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#434]
"I think the net of this issue (434) was to implement whatever the numbering scheme is from the MRW and make sure we map it to appropriate data structures to implement get / set sensors."  - Patrick

We may need some initial work for just the FRU fault.

**Comment by dkodihal** [comment]
Notes from @tomjoseph83 and my discussion. Following would be the potential list of activities

- Investigate which sensors we're interested in, and what we get from the MRW for those sensors.
- MRW is unlikely to provide all fields that an SDR record requires, so some policy might have to be hand-coded for sensors of interest.
- A parser that combines MRW input and the policy files above to generate the SDR.

Given these, the estimate of 5 points seems to be in the right ballpark.
