### ISSUE TITLE
Implement 'Get Self Test Results' command

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#436]

**Comment by williamli80** [comment]
Do we have a "self test" in openbmc? Or do we have "self test" in each app of openbmc?

**Comment by williamli80** [comment]
My plan:
Find out fault property sequentially from  dbus;
Return error message when I meet a "true" of fault property.

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/#/c/1097/

**Comment by williamli80** [comment]
[https://github.com/openbmc/openbmc/issues/840](url)
