### ISSUE TITLE
Confirm 'Cold Reset' and "Warm Reset' meet IPMI 2.0 requirements

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#437]

**Comment by williamli80** [comment]
Made 2 PR for coldReset IPMI command:
One is the ipmi receive and response: https://gerrit.openbmc-project.xyz/#/c/267/
Two is issuing the coldReset (reboot) https://gerrit.openbmc-project.xyz/#/c/268/

**Comment by williamli80** [comment]
Hi team, would the patch on skeleton repo be merged?'cold reset' will not work now. Or should I revise this patch?
https://gerrit.openbmc-project.xyz/#/c/268
