### ISSUE TITLE
Implement 'Get Chassis Capabilities'

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#438]

**Comment by williamli80** [comment]
Made a PR: https://gerrit.openbmc-project.xyz/#/c/216/

**Comment by williamli80** [comment]
Update https://gerrit.openbmc-project.xyz/#/c/216/.
Some parameters are hard coded, can be refactored when we can get them.
TODO: https://github.com/openbmc/openbmc/issues/620
