### ISSUE TITLE
Implement FRU device commands

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#442]

**Comment by vishwabmc** [comment]
so we have the ipmi-fru-parser that does the FRU cmd implementation.. Do you have more info to this ?

**Comment by dkodihal** [comment]
Tom and I had a discussion on this today. We think we need two stories here -

1) Write an MRW parser (could be tweaking an existing parser) to help map the IPMI FRU id and FRU properties to an inventory path and and d-bus properties. This would be a 1 pt.
2) Implementation of the FRU command - this would involve a python script to consume the output from 1) and C++ code to implement the FRU commands. This is a 2 pt story.

I'll create stories based on the above and add to this epic.
