### ISSUE TITLE
Implement SEL commands

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#443]

**Comment by vishwabmc** [comment]
Is it about beyond what is already  in storahehandler ?

**Comment by ongchris** [comment]
Is the plan to support an IPMI-compliant System Event Log?

**Comment by williamspatrick** [comment]
Yes.  There will be a translation between the internal openbmc error structures and SELs.

**Comment by ongchris** [comment]
Thanks Patrick.

**Comment by dkodihal** [comment]
Tom split this into #1514, #1515, #1516. Closing this.
