### ISSUE TITLE
Non-supported IPMI commands return success

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#469]
The openbmc IPMI implementation forwards non-supported commands to a 'wildcard' function that is a no-op and returns success, making it look to the caller that their request was handled successfully.
For a hypervisor or host that supports multiple BMC distros, it is not currently possible to dynamically determine if an IPMI cmd is supported in openbmc because of the success return code instead of getting an equivalent to 'non supported command' return code.

**Comment by williamli80** [comment]
Hi, Change complete code from 00h to C1h(Invalid command).
PR: https://gerrit.openbmc-project.xyz/#/c/307/
Please review it.
