### ISSUE TITLE
Common / standard sd-bus interfaces (ex. org.freedesktop, org.openbmc interfaces)

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#476]

**Comment by williamspatrick** [comment]
org.openbmc.delete and Associations are good candidates for this.

**Comment by williamspatrick** [comment]
also org.openbmc.setmultiple

**Comment by geissonator** [comment]
Per Patrick, could create the yaml for the org.freedesktop interfaces we use so that the dbus client bindings would work with them.

**Comment by geissonator** [comment]
Seems like a nice to have, but not required for GA.  Also should not affect testing so phase 6 or beyond candidate.  Move out to 2.1 or 3.0?
