### ISSUE TITLE
Sync u-boot uuid to /etc/machine-id

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#479]
In order to be able to keep the system uuid in sync between the vpd value and the fw value, a script is needed to copy the uuid u-boot value to /etc/machine-id. @mdmillerii has the details.

**Comment by whowutwut** [comment]
Is this UUID going to be exposed in the ReST commands? Which endpoint and what would it look like? (@zet809 FYI)

**Comment by anoo1** [comment]
> Is this UUID going to be exposed in the ReST commands?

@chinaridinesh is working on syncing the uuid and seems he's using xyz.openbmc_project.Inventory.Decorator.UUID. I don't see this interface yet in the phosphor-dbus-interfaces yet, so @chinaridinesh do you know who's adding it?

**Comment by whowutwut** [comment]
@williamspatrick  Is this the unique identifier for each node that you had mentioned in the slack conversation?

**Comment by hughsie** [comment]
I'm also trying to get fwupd running on the BMC -- and we also need `/etc/machine-id` -- could this issue be revived perhaps?

**Comment by mdmillerii** [comment]
I am not sure what the design should be, @hughsie but my understanding of machine id has changed in the last 6 years.   Let's not discuss here.

Please state your requirements and reasoning in an email to the openbmc development list . You could also use a issue on openbmc/openbmc but the community prefers email to raise issues and gerrit to submit a design to docs to discuss specific proposals.
