### ISSUE TITLE
Feature request: Need to populate basic details on PCIe card via BMC inventory 

### ISSUE THREAD

**Issue by agangidi53** [openbmc/openbmc#480]
For ironic usage in onMetal kind of use-case, I thought it will be good to have a feature where we can query the PCIe devices via the BMC to figure out what exact PCIe device is in the said PCIe slot . Currently we have only have the ability to know present / not present.

**Comment by willenlee** [comment]
**Insert the PCIe riser and PCIe cards then checking SLOT present via REST.**

![1470038992378](https://cloud.githubusercontent.com/assets/20331199/17289815/f356843e-580d-11e6-8fa6-326d3c3ab030.jpg)
![1470038961095](https://cloud.githubusercontent.com/assets/20331199/17289828/0177ba42-580e-11e6-95ba-3b8719d17df0.jpg)

**Comment by agangidi53** [comment]
Hi @willenlee 

I am not looking for what you have suggested. I need the DETAILS of what SPECIFIC card is present in the slot.

**Comment by amboar** [comment]
@willenlee As a general note it's probably more useful to everybody if you copy/paste the text out of the console rather than attaching screenshots. There are also some [nice formatting options ](https://guides.github.com/features/mastering-markdown/) for github issues to help make the output readable.

**Comment by willenlee** [comment]
At present, BMC can access PCIE through I2C bus to get below information.
Or BIOS can get these information then writing fru into BMC.

1. Vendor ID
2. Device ID
3. Revision ID
4. Class Code
![1470619420128](https://cloud.githubusercontent.com/assets/20331199/17466857/f1fb7f40-5d49-11e6-8243-a4eb0f3e6631.jpg)
