### ISSUE TITLE
Correction need in Dbus interface document

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#489]
Brief Description: 
org.openbmc.HostIpmi interface signal method should be ReceivedMessage instead of ReceivedMsg as in currently mentioned in https://github.com/openbmc/docs/blob/master/dbus-interfaces.md

See the attachment please
[DbusInterfaceCorrection489.docx](https://github.com/openbmc/openbmc/files/388789/DbusInterfaceCorrection489.docx)

**Comment by williamspatrick** [comment]
@sivassrr - Please just make a pull request against the docs repository to update.

**Comment by sivassrr** [comment]
https://github.com/openbmc/docs/pull/35 - Done.
