### ISSUE TITLE
Implement the Product ID setting for ipmi GET-DEVICE-ID command

### ISSUE THREAD

**Issue by williamli80** [openbmc/openbmc#495]
Need a setting for Product ID from where Get-Device-Id command can fetch Product ID per IPMI Spec 2.0, 
Ref to: openbmc/openbmc#435

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/7951> Added IPMI Device ID command related hardcoded yaml file
Resolves:  #495 Implement the Product ID setting for ipmi GET-DEVICE-ID command

**Comment by rfrandse** [comment]
handled in another place. Code in.
