### ISSUE TITLE
System dts update for APSS UART.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#502]
Pass2 of the board is adding a dedicated UART connection between the ast2500 and the APSS.  We need to make sure this is in the device-tree correctly in case we need to use it for debug purposes.  The main purpose of it would be, if we need in the lab, to push a code update into the APSS.

**Comment by williamspatrick** [comment]
Would like to have this by mid-September.

**Comment by shenki** [comment]
This is a 30 second job. It requires two bits of information:

1. Which UART pints are being used?
2. What is the desired baud rate?

It would be good to document the firmware update process, or at least perform some kind of handshake with APSS so we can test the change.

**Comment by williamspatrick** [comment]
We aren't going to be responsible for implementing a code update at this point.  Jordan implied they have some scripting that can turn an image into a bunch of 'echo' commands onto a UART.  We can get the baud rate from him (copied you via email).

**Comment by amboar** [comment]
> ... UART pints ...

Untappd doesn't even list this beer, must be exclusive!
