### ISSUE TITLE
Should enable CONFIG_SYN_COOKIES on ARM kernels?

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#504]
See openbmc/phosphor-rest-server#24 for full context.

@shenki - We are still investigating overall, but do you think we should CONFIG_SYN_COOKIES=y in the kernels?

**Comment by amboar** [comment]
Here is an interesting drawback to syn cookies:

> A problem arises when the connection-finalizing ACK packet sent by the client is lost, and the application layer protocol requires the server to speak first (SMTP and SSH are two examples). In this case, the client assumes that the connection was established successfully and waits for the server to send its protocol banner, or resend the SYN+ACK packet; however, the server is not aware of the session and will not resend the SYN+ACK because it discarded the backlog queue entry that would enable it to do so. Eventually, the client will abort the connection due to an application layer timeout, but this may take a relatively long time.

SSH would be the main concern.

https://en.wikipedia.org/wiki/SYN_cookies#Drawbacks
