### ISSUE TITLE
[System - Barreleye/Palmetto ] REST methods are failing due to ConnectionError after network configuration

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#524]
REST method are failing with below "ConnectionError: HTTPSConnectionPool after network configuration.  

ConnectionError: HTTPSConnectionPool(host='9.3.164.153', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff22bf5d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by gkeishin** [comment]
@rahulmah I see it working in today test run on

BMC Version: 20160824194547
BUILD_ID="v1.0"

which is a latter version .. so i think you can close this one..

Create and delete user group :: ***GOOD PATH***                       URI:https://9.3.164.153/org/openbmc/UserManager/Groups/action/GroupAddUsr, method:Post, args:{u'data': {u'data': ['jHswPAnw']}, u'headers': {u'Content-Type': u'application/json'}}
Response code:200, Content:{
  "data": 0,
  "message": "200 OK",
  "status": "ok"
}
URI:https://9.3.164.153/org/openbmc/UserManager/Groups/action/GroupListUsr, method:Post, args:{u'data': {u'data': []}, u'headers': {u'Content-Type': u'application/json'}}
Response code:200, Content:{
  "data": [
    "fhMoWDpa",
    "IYcqs4qo",
    "ZPK27mag",
    "aPkRbJCb",
    "b4dqE6U3",
    "g0wSkdhY",
    "5y7FZgAu",
    "4WhINzIZ",
    "x9bwbGDe",
    "B6khBnFw",
    "iEX0CwMg",
    "ppZIKxXC",
    "Fr28IeR3",
    "mQJ9Bn5B",
    "dEDA2tBi",
    "O3V9iosG",
    "ukVSZuyF",
    "toDaLQM4",
    "mGPAQHpY",
    "aZ5i5GAp",
    "vV5eOK0v",
    "I7nYw3iH",
    "VgJYXvlz",
    "E9SClSh3",
    "tJRx8Be0",
    "hSkoGSmr",
    "raroSI7b",
    "JnKa9cNE",
    "I3aKqHFe",
    "1d3TSa3w",
    "jaFUfqrs",
    "RZpv0HnP",
    "uhIL7g3U",
    "xwJVcGPd",
    "1FTQyFCa",
    "RNrTn19D",
    "5tHpVKTM",
    "PPRgjKtn",
    "jHswPAnw"
  ],
  "message": "200 OK",
  "status": "ok"
}
URI:https://9.3.164.153/org/openbmc/UserManager/Group/action/GroupDel, method:Post, args:{u'data': {u'data': ['jHswPAnw']}, u'headers': {u'Content-Type': u'application/json'}}
Response code:200, Content:{
  "data": 0,
  "message": "200 OK",
  "status": "ok"
}
| PASS |

**Comment by rahulmah** [comment]
Opened issue in openbmc-test-automation - https://github.com/openbmc/openbmc-test-automation/issues/83

**Comment by gkeishin** [comment]
@bradbishop If there is anything on this we need to know for REST .. From test perspective, we are pumping those REST request back to back.. so if one fails, rest seems to fail..

**Comment by rahulmah** [comment]
@bradbishop : This is what might be causing rest commands to fail.
In both Barreleye and Palmetto system, after applying set current IP address, we try to check if the set ip is pinging .. There it passes. But then I am seeing that rest command are failing due to ConnectionError. So it seem like configuring IP is leading to ConnectionError: HTTPSConnectionPool (due to rest login problem).

**Comment by bradbishop** [comment]
this is a known issue: https://github.com/openbmc/phosphor-rest-server/issues/24

can you verify you have the fix?

**Comment by bradbishop** [comment]
could also be this one:

https://github.com/openbmc/openbmc/issues/514

**Comment by rahulmah** [comment]
@bradbishop The issue (RestAPI curl couldn't connect) which you have pointed is same but it has already been closed. I have tested with latest OpenBMC v1.0 build - 20160824194547 and this issue is still seen. Other defect which you pointed does not seem to related to network change.

**Comment by hweaving** [comment]
rahulmah, can you ssh to the BMC (or VNC if you are using qemu) and check journalctl for Python errors?  Also, can you run "ps | grep rest" to check whether the REST service is running on the BMC?

**Comment by rahulmah** [comment]
@hweaving : Sure I will checking that

**Comment by hweaving** [comment]
@bradbishop @rahulmah That looks different than #514.  In your case, obmc-rest is using 100% CPU rather than crashing.

**Comment by williamspatrick** [comment]
Discussed this on a call with @rahulmah and @sivassrr.

1. We believe the test framework is attempting to access the rest server too quickly after changing the IP address.  Due to the server restarting as part of the ip address change, the test framework needs to wait 10-30 seconds.

2. There is a pending change to move from Rocket to gevent.  #147.  This is scheduled for this month or early next month.
