### ISSUE TITLE
boot_flags documentation missing on barreleye at customer site

### ISSUE THREAD

**Issue by basuv** [openbmc/openbmc#529]
Customer was unable to set the boot order due to missing documentation. 

![x1234](https://cloud.githubusercontent.com/assets/21249557/17985928/d5745ac6-6add-11e6-86d8-6072a5e20164.jpg)

**Comment by anoo1** [comment]
Expanding on the issue reported, the 'docs/host-management.md' is out of date, the 'BIOS boot options' describes the original supported values which were the hex values described in the ipmi spec, but since then the ipmi code changed to accept strings from dbus:

    {"Network"},
    {"Disk"},
    {"Safe"},
    {"CDROM"},
    {"Setup"},
    {"Default"},

**Comment by basuv** [comment]
I

**Comment by basuv** [comment]
I would like the customer to be able to see the list of boot flags to set from, on the openbmc documentation, and not to go to IPMI spec

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/11039> Add links to boot interfaces
Resolves  #529 boot_flags documentation missing on barreleye at customer site
