### ISSUE TITLE
filesystem package needed?

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#537]
Do we need a package that creates shared paths like:

/var/lib/obmc

so that applications don't have to worry about creating the directory?

**Comment by vishwabmc** [comment]
I like this idea.

**Comment by williamspatrick** [comment]
Two points of discussion:

1.  I don't think all applications should be writing to the same directory. /var/lib/phosphor/<app> seems more appropriate. As it stands we have possibility for file name collisions. 

2. Isn't it fairly standard practice to 'install' something like a .empty or .keep file. Should this be owned by each application in their source code or should this be owned by the distro recipes?
