### ISSUE TITLE
Remove down-level libflash from skeleton and link against upstream package.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#542]

**Comment by shenki** [comment]
This should include consideration for using /dev/mtd over the direct mmio interface we currently use

**Comment by williamspatrick** [comment]
@shenki - While entirely reasonable as a better implementation, that is well outside the scope of this story and not feasible to complete before Witherspoon power on.  I will open an issue to come up with a firm design for managing the host flash and, subsequently, a real implementation.

**Comment by williamspatrick** [comment]
Oops.  Auto-closed by @bradbishop doing development push to his own repo.
