### ISSUE TITLE
Generate device tree from MRW.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#559]
Split from device tree part from #375.

**Comment by geissonator** [comment]
This story specifically tracks the following now:

- [ ] memory, mac, vuart - https://gerrit.openbmc-project.xyz/#/c/637/
- [ ] UART, SPI, and LED nodes - https://gerrit.openbmc-project.xyz/#/c/664/

The remaining device tree work will be tracked in new stories.
