### ISSUE TITLE
Add device trees to correct phosphor layer.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#56]
openbmc/linux#10 added device trees to the Linux tree.  These should be in the meta-phosphor-machines layer instead.

**Comment by nkskjames** [comment]
I think you mean meta-openbmc-machines layer

**Comment by bradbishop** [comment]
Did this here: https://github.com/openbmc/openbmc/pull/62

**Comment by shenki** [comment]
I think this can be closed now that we are back to using in-tree device trees

**Comment by williamspatrick** [comment]
Long-term we should move back to openbmc device trees.  That was the previous discussion we had.

**Comment by bradbishop** [comment]
I'm removing myself as the owner of this.  The plumbing is there, its just a matter of using it.  @spinler here is something for you to consider as you work through MRW.

**Comment by spinler** [comment]
not doing this
