### ISSUE TITLE
Convert phosphor-event tests to gtest.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#561]

**Comment by msbarth** [comment]
- [ ] Add gtest build framework

- [ ] Breakdown current unit tests into gtest functions

- [ ] Implement each unit test as gtest

**Comment by JoshDKing** [comment]
- [ ] Create the gtest framework
- [ ] Breakdown our unit tests into the gtest functions
- [ ] Implement the unit tests in the gtest functions
