### ISSUE TITLE
Bump kernel to enable new GPIOs

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#575]
There have been some failures requesting GPIOs from userspace as the pins are not defined in pinmux. @amboar has added them to the table and the patch has been applied to dev-4.7.

We must now rev the kernel version in the openbmc tree.

**Comment by amboar** [comment]
Patch bumping the kernel pushed to gerrit: https://gerrit.openbmc-project.xyz/#/c/510/

**Comment by amboar** [comment]
@shenki @williamspatrick this issue can be closed.

**Comment by amboar** [comment]
@rfrandse this ship sailed long ago, @williamspatrick or @shenki should close the issue

**Comment by shenki** [comment]
🚢
