### ISSUE TITLE
No getty with openbmc master on Firestone

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#576]
@adamliyi reported that his firestone did not have a login prompt in #569

**Comment by madscientist159** [comment]
Works on Firestone UART5 using the kernel tree here:
https://github.com/madscientist159/linux-openbmc/tree/dev-4.7-firestone-fixes

**Comment by shenki** [comment]
@madscientist159 I would be happy to review and integrate your changes. Please submit them with git-send-email to openbmc@lists.ozlabs.org

**Comment by gtmills** [comment]
@shenki Still an issue? If not, can you close? Firestone is also no longer a supported machine.
