### ISSUE TITLE
[Palmetto VERSION_ID="v1.99.0-85-g0d2bd6a-dirty"] System inventory is missing from latest build on palmetto

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#580]
In Palmetto, system inventory is missing from openbmc's latest build. Same issue is not seen on Barreleye with same build.

rahulmah@rackspace:~$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET -d "{\"data\":[]}" https://BMC_IP/org/openbmc/inventory/enumerate
{
  "data": {
    "description": "org.openbmc.ObjectMapper.Error.NotFound: path or object not found: /org/openbmc/inventory"
  },
  "message": "404 Not Found",
  "status": "error"
}rahulmah@rackspace:~$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET -d "{\"data\":[]}" https://BMC_IP/org/openbmc/
{
  "data": [
    "/org/openbmc/control",
    "/org/openbmc/managers",
    "/org/openbmc/settings",
    "/org/openbmc/UserManager",
    "/org/openbmc/buttons",
    "/org/openbmc/records",    <--- /org/openbmc/inventory is missing
    "/org/openbmc/watchdog",
    "/org/openbmc/NetworkManager",
    "/org/openbmc/sensors",
    "/org/openbmc/HostIpmi"
  ],
  "message": "200 OK",
  "status": "ok"
}rahulmah@rackspace:~$

03:34:24 System inventory                                                      URI:https://9.3.164.177/org/openbmc/inventory/enumerate, method:Get, args:{u'timeout': u'10'}
03:34:25 Response code:404, Content:{
03:34:25   "data": {
03:34:25     "description": "org.openbmc.ObjectMapper.Error.NotFound: path or object not found: /org/openbmc/inventory"
03:34:25   }, 
03:34:25   "message": "404 Not Found", 
03:34:25   "status": "error"
03:34:25 }
03:34:25 
03:34:25 FFDC Collection Started 	: 20160916033425118063
03:35:18 FFDC Collection Completed 	: 20160916033518255470

------------------------------------------------------------------------ 
DRIVER INFO : FW Level	Executed : cat /etc/os-release
------------------------------------------------------------------------ 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-85"
VERSION_ID="v1.99.0-85-g0d2bd6a-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-85"
BUILD_ID="v1.99.0"

------------------------------------------------------------------------ 
DRIVER INFO : Build Info	Executed : cat /etc/version
------------------------------------------------------------------------ 
20160914203259

**FFDC Logs:**
[20160916033425118063_BMC_proc_list.txt](https://github.com/openbmc/openbmc/files/476463/20160916033425118063_BMC_proc_list.txt)
[20160916033425118063_BMC_journalctl.txt](https://github.com/openbmc/openbmc/files/476467/20160916033425118063_BMC_journalctl.txt)
[20160916033425118063_ffdc_report.txt](https://github.com/openbmc/openbmc/files/476469/20160916033425118063_ffdc_report.txt)

**Comment by bradbishop** [comment]
I fixed this here: https://github.com/openbmc/skeleton/commit/f327ddd83f9627a152f6af48b95057d7805b4abe

and pulled into openbmc here:
https://github.com/openbmc/openbmc/commit/675540ecb832839b0c375a986b4f1bc7041a144a
