### ISSUE TITLE
[Barreleye VERSION_ID=v1.99.0-85-g0d2bd6a-dirty]  Service restarted when the Policy is set as "no"

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#582]
For example: 

obmc-phosphor-userd    Restart=no

if we kill this service, it just bounce back , isn't this something wrong inherent design to work like this when the policy is set to "no".. 

root@barreleye:~# ps -aef | grep userd | grep -v grep
 3566 root       0:03 python /usr/sbin/obmc-phosphor-userd
root@barreleye:~# kill -9 3566
root@barreleye:~# ps -aef | grep userd | grep -v grep
 3573 root       0:01 python /usr/sbin/obmc-phosphor-userd
root@barreleye:~# systemctl -p Restart show obmc-phosphor-userd | cut -d = -f2
no
root@barreleye:~#

**Comment by williamspatrick** [comment]
Are you sure you're looking at the right thing?

$ git describe
v1.99.0-85-g0d2bd6a
$ pwd
.../openbmc/meta-phosphor/common/recipes-phosphor/users/obmc-phosphor-user
$ cat org.openbmc.UserManager.service 
[Unit]
Description=Phosphor User Manager

[Service]
ExecStart={sbindir}/obmc-phosphor-userd
Environment="PYTHONUNBUFFERED=1"
Restart=always
Type=dbus
BusName={BUSNAME}

[Install]
WantedBy={SYSTEMD_DEFAULT_TARGET}
```

There is no obmc-phosphor-userd service.  It is a service based on the dbus name it claims.

As you see from this file, the service file lists Restart=Always.
