### ISSUE TITLE
Eliminate startup_hacks in skeleton.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#586]
Skeleton currently has a file called "startup_hacks.sh" with the following:
```
systemctl stop serial-getty@ttyS0

# Setup VUART
VUART=/sys/devices/platform/ahb/ahb:apb/1e787000.vuart
echo 4 > $VUART/sirq
echo 0x3f8 > $VUART/lpc_address
```

I don't believe there is any reason for the UART pieces at this point.  Need to confirm with @shenki that this is taken care of either by the kernel or by obmc-console on startup.

The serial-getty stop is a build problem.  There is a CONSOLES variable in yocto that probably needs to be corrected in ast2400.inc / ast2500.inc in order that the serial-getty@ttyS0 service is not automatically started.

**Comment by shenki** [comment]
The console server sets the sysfs properties, so that can certainly be removed from this script
