### ISSUE TITLE
openbmc password reset on barreleye

### ISSUE THREAD

**Issue by kachini** [openbmc/openbmc#588]
Hi folks, 

is there any way to reset openbmc password on barreleye (can't login via ssh)?
I've got only access to petitboot via vga/keyboard. 

thanks in advance, 

regards,
Sergey

**Comment by williamspatrick** [comment]
@kachini - In the reference openbmc code-base there is no possibility of doing a password reset short of pulling the NOR chip and reflashing it.  Having said that, I don't know who provides support for your system and what enhancements they might have done on top of the base code we provided them.  It is possible that your vendor added a user interface for performing a password reset of the BMC users.
