### ISSUE TITLE
[master] Power button LED remains off at all times

### ISSUE THREAD

**Issue by madscientist159** [openbmc/openbmc#590]
On Firestone, the power button LED remains off at all times.  It should start blinking when the BMC enters READY state and it should turn solid on when the system power is on.

The underlying hardware drivers work correctly; the LED can be turned on with e.g.:
echo 255 > /sys/class/leds/power/brightness

**Comment by gtmills** [comment]
@madscientist159 This issue hasn't been updated in over a year. Still a problem or can this be closed? Thanks!

**Comment by gtmills** [comment]
firestone was removed here: https://gerrit.openbmc-project.xyz/#/c/10957/. Can we close?

**Comment by madscientist159** [comment]
Yeah, Firestone never worked right.
