### ISSUE TITLE
ast2500.conf still references sample.inc

### ISSUE THREAD

**Issue by jaghu** [openbmc/openbmc#595]
openbmc/meta-openbmc-machines/meta-evb/meta-evb-aspeed/meta-evb-ast2500/conf/machine/evb-ast2500.conf still references the line "require conf/machine/include/sample.inc" (which has been removed)

**Comment by jaghu** [comment]
@bradbishop

**Comment by bradbishop** [comment]
https://gerrit.openbmc-project.xyz/#/c/620/.  Thanks @kc8apf.
