### ISSUE TITLE
Create location to store "misc" VPD data.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#597]
There is currently a "virtual" inventory object `.../inventory/system/misc` that we believe is populated from certain EEPROM reads.  We want to eliminate all "virtual" inventory objects and instead ensure they all represent physical devices.  So, we need to move this data either into a proper inventory object or find another way to represent the data contained within.

**Comment by rfrandse** [comment]
Part of IPMI work?

**Comment by dkodihal** [comment]
This is not IPMI. It could mean inventory work, but I need to check if this is already covered by our existing inventory.

**Comment by dkodihal** [comment]
What comprises this 'misc' inventory object are various firmware revisions, which are now already under the software namespace.
