### ISSUE TITLE
[master] Palmetto: Fans not powered when host is booted

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#598]
@textaddict claims in a https://github.com/openbmc/openbmc/issues/513#issuecomment-248358947 that the host fans do not spin up at host power-on, and in a folloup https://github.com/openbmc/openbmc/issues/513#issuecomment-248971305 that this was working in the past.

**Comment by textaddict** [comment]
The fans fail to start only if the palmetto has the Fan CTRL cable plugged into the connector along the left hand side of the planar.  Some Tyan Palmettos shipped with this connector unplugged so would not see the problem unless the connector is plugged in.  If the Fan CTRL cable is left unplugged the fan controller defaults the fans to full speed.  

This will need to be fixed for active fan control with OpenBMC on Palmetto.
