### ISSUE TITLE
Unsupported Ubuntu-16.04 and No recipe available for python-gevent_%.bbappend

### ISSUE THREAD

**Issue by hamzy** [openbmc/openbmc#623]
ubuntu@oscloud3:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
ubuntu@oscloud3:~$ cd openbmc/
ubuntu@oscloud3:~/openbmc$ git remote update; git checkout master; git pull --ff-only origin master
ubuntu@oscloud3:~/openbmc$ TEMPLATECONF=meta-openbmc-machines/meta-openpower/meta-ibm/meta-firestone/conf . oe-init-build-env
...
You can now run 'bitbake <target>'

Common targets are:
     obmc-phosphor-image
ubuntu@oscloud3:~/openbmc/build$ bitbake obmc-phosphor-image
WARNING: Host distribution "Ubuntu-16.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Parsing recipes: 100% |#############################################################################################| Time: 00:00:07
Parsing of 948 .bb files complete (0 cached, 948 parsed). 1392 targets, 231 skipped, 0 masked, 0 errors.
ERROR: No recipes available for:
  /home/ubuntu/openbmc/meta-phosphor/common/recipes-devtools/python/python-gevent_%.bbappend

Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by gtmills** [comment]
Firestone is no longer supported and has been removed. 
@hamzy Can we close?
