### ISSUE TITLE
Get P8 OCC driver up-streamable and refactored for P9

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#624]

**Comment by eddiejames** [comment]
Tasks:

Separate bus transfer code from the hwmon interface
General clean-up with LTC team's guidance

**Comment by geissonator** [comment]
Eddie out until after Thanksgiving so moving into next sprint.

**Comment by geissonator** [comment]
Upstream review still ongoing.

**Comment by geissonator** [comment]
Pulling out of committed since we can't commit to when upstream will merge this.

**Comment by rfrandse** [comment]
Tracking effort to upstream in https://github.com/openbmc/openbmc/issues/1585
