### ISSUE TITLE
Test P9 OCC data against OpenBMC OCC driver

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#625]

**Comment by amboar** [comment]
@geissonator can you add a description here? Is the P8 OCC driver expected to work without modification for P9? The OCC driver could do with some love regardless, it's a bit of a maze.

**Comment by geissonator** [comment]
This sprint will focus on #624 so we'll move this to backlog for now.  Needs to be broken down further.

**Comment by eddiejames** [comment]
Task list:

- [ ] implement the different P9 data structures in the OCC driver (different sensor formats, etc)
- [ ] mock up or obtain P9 OCC poll response data
- [ ] create quick test framework to read in and parse P9 OCC poll response data

**Comment by eddiejames** [comment]
[p9_occ_results.txt](https://github.com/openbmc/openbmc/files/565042/p9_occ_results.txt)

Tested with a chunk of poll response data from Martha. Everything appears to be in order.

**Comment by geissonator** [comment]
Still under merge review so moved to relevant sprint.

**Comment by geissonator** [comment]
Upstream review still ongoing.

**Comment by geissonator** [comment]
Pulling out of committed since we can't commit to when upstream will merge this.
