### ISSUE TITLE
Integrate new generated device tree files into kernel

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#629]

**Comment by spinler** [comment]
- [ ] Create recipe to fetch gen_devtree.pl, run it against the XML, run the dtc against that output, and then put the output of that somewhere

**Comment by amboar** [comment]
@spinler My gut feeling is that you'd then need to patch [kernel-cuimage.bbclass](https://github.com/openbmc/openbmc/blob/master/meta-phosphor/classes/kernel-cuimage.bbclass#L23) to look in the right place for your generated dtb, where-ever it ends up living.

**Comment by geissonator** [comment]
Moving from 11.2 into 11.16 - blocked on hostboot support of new MRW data (coming soon)

**Comment by geissonator** [comment]
Open design issues here, Matt may just check in a diff of his generated file directly to kernel until we get things resolved.

**Comment by rfrandse** [comment]
Putting this in the backlog for later.

**Comment by spinler** [comment]
Definitely not doing this for GA.  Moving out.

**Comment by spinler** [comment]
Abandoned this feature
