### ISSUE TITLE
Mapper interface enhancements

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#632]
As of today the mapper provides:

GetObject
GetSubtree
GetSubtreePaths

For the latter two, it would help applications to be able to specify an interface filter, and to allow applications to specify the format of the dictionary that is returned ( with either path, interface or service as the key).

I haven't considered if the latter ends up having any utility or not.  Its certainly possible - the out signature could simply be a{sv}..but I'm not sure if that is consumable by statically typed code.

**Comment by geissonator** [comment]
Maybe tie into #1661 ?

**Comment by gtmills** [comment]
@edtanous Interested in adding these to the C++ mapper?
