### ISSUE TITLE
Inventory Manager reimplementation

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#633]
Moving to sdbus.

The new inventory manager (PIM or phosphor inventory manager) would use this to mark inventory items as cached or not present as ipmi channels go up and down, etc...
- [ ] bbclass for inventory providing apps with example
- [x] code generator for inventory data aggregate
- [x] signal callback filter functor - wait for property to change to a value
- [x] trigger - wait for unit to be starting/started/stopping/stopped
- [x] trigger - wait for a dbus signal match
- [ ] action - set a property to a value
- [x] action - delete an object
- [x] associate triggers with actions
- [x] "PIM" xyz.openbmc-project.Inventory.Manager.Notify implementation
- [x] Find an existing or implement an IPMI up/down signaling mechanism
- [x] Find an existing or implement a "Hostboot done" signaling mechanism
- [x] Find an existing or implement a coldplug finished signaling mechanism

**Comment by bradbishop** [comment]
'find an existing or implement  'hostboot done' signaling mechanism:

```   @dbus.service.method(
       SensorValue.IFACE_NAME,
       in_signature='v', out_signature='')
   def setValue(self, value):
       SensorValue.setValue(self, value)
       if (value == "FW Progress, Starting OS"):
           self.GotoSystemState("HOST_BOOTED")```

I'm sure there is something usable here.

**Comment by bradbishop** [comment]
'find an existing or implement IPMI up/down signaling mechanism'

Just going to use a power off signal for now.  Marking task as done.

**Comment by mdmillerii** [comment]
One thing to be aware of, `HOST_BOOTED` is issued by both hostboot handing off control to skiboot and skiboot handing off control to the petitboot linux kernel.

Also, should this be moved elsewhere when/if the signal for this sensor is added for the [pci reset handling](https://gerrit.openbmc-project.xyz/#/c/415/)?

**Comment by bradbishop** [comment]
Thanks for the heads up @mdmillerii.

Sure.  At this point I just wanted to establish that there was in fact something usable as a first-pass attempt making this work.  If I've done it correctly..moving to a different signaling mechanism later should be easy.

**Comment by bradbishop** [comment]
'Find an existing or implement a coldplug finished signaling mechanism'

systemd emits plenty of signals for this.  the trick is at least one client has to have called 'subscribe' (and that client has to stay connected).

Marking task as done.

**Comment by bradbishop** [comment]
I opened issues for remaining unchecked tasks:
https://github.com/openbmc/openbmc/issues/726
https://github.com/openbmc/openbmc/issues/757
