### ISSUE TITLE
Create settingsd first-level categories dynamically based on inventory object.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#638]
Presently, the settingsd code will statically create 'host0' and 'bmc0'.  There should be a mapping between the category (host) and an inventory query (.../inventory/systemN) so that there is a 1-to-1 mapping between real inventory objects and real settingsd holders.  This will likely also require the file format to change so that a setting (/host/foo) is not simply in a single file (.../foo), but incorporates the inventory item number.  (ex. .../host0-foo).

**Comment by geissonator** [comment]
### Proposed task list
- [ ] Look at files and scope based on category, handle duplicate names across categories
- [ ] Define a mapping between 1st level query and inventory item (work with Brad)
- [ ] Use mapping, call mapper object to find inventory object and create 1st level objects

**Comment by geissonator** [comment]
Sergey, can we cross off some of the above tasks?  Can you provide links within the tasks to the corresponding gerrit code reviews?  Thanks!

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/#/c/719/
