### ISSUE TITLE
Ensure power on code works with Witherspoon

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#647]
Initially this was just going to be a GPIO but maybe it changed?  This issue is to investigate if the openbmc code will work as-is to power on Witherspoon, and if not, to make the code work.

**Comment by geissonator** [comment]
Uma to verify there's a way via fsp debug box to do this for initial power on.

**Comment by geissonator** [comment]
Actually, there's a gpio command line tool they run on the BMC to do the power on, so we need to have that function working.

**Comment by geissonator** [comment]
This will include any workarounds required for power on.

**Comment by shenki** [comment]
> pdbg is currently only in the debug tarball, we're going to bring it into the main
> image with that issue and run the appropriate scripts to get power on working.

We will want to move to the latest pdbg.

@apopple will also be making a new tagged release soon, so ideally that will be the version we use

**Comment by SS-IBM** [comment]
- Recipe update: Create .bb / .bbappend to reference the script
- Write a script to toggle power on GPIO, turn VCS on and off, run SBE and 'putcfam' commands

**Comment by williamspatrick** [comment]
This work is not complete so it should not be closed.

**Comment by geissonator** [comment]
Moving to current sprint then since reopened.
