### ISSUE TITLE
Need device driver for RX8900CE RTC

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#654]
For witherspoon.

**Comment by shenki** [comment]
* http://www5.epsondevice.com/en/products/i2c/
 * https://support.epson.biz/td/api/doc_check.php?dl=app_RX8900CE&lang=en

Has an out of tree driver. May be less hassle to write our own.

**Comment by csmart** [comment]
I'll take a crack at this.

**Comment by shenki** [comment]
There is upstream support in 4.9:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=eff6675b5cc191308c0144dcd5dd2b49257e83d7

```
	rtc: rtc@32 {
		compatible = "epson,rx8900"
		reg = <0x32>;
		epson,vdet-disable;
		trickle-diode-disable;
	};
```

We need to pull this into dev-4.7 so we can use it on Witherspoon, as well as adding it to the kernel configuration and device tree.

@csmart, we will need to find you a different driver to hack on

**Comment by csmart** [comment]
\o/

**Comment by shenki** [comment]
@spinler What's the i2c address of this part?

**Comment by spinler** [comment]
0x32 (7 bit)

**Comment by csmart** [comment]
https://patchwork.ozlabs.org/patch/686883/

**Comment by shenki** [comment]
@spinler, @csmart had some questions:

This commit adds the relevant device tree entry for the Epson RX8900CE
RTC module on the I2C bus.

> Note that there are two options that we may need to set.
> 
> If there is no connected battery:
>  epson,vdet-disable;
> 
> If there is no trickle charge diode:
>  epson,vdet-disable;
>

Do you know what the battery backup configuration is for the rtc?

**Comment by csmart** [comment]
@spinler looks like the circuitry is there, but it's broken out into a connector. So if there is a battery, it appears to be offboard?

**Comment by csmart** [comment]
Also, v2 https://patchwork.ozlabs.org/patch/686891/

**Comment by spinler** [comment]
The  battery is on a riser card, the card that either the left or right power supply plugs into (I forget which).
There is also wiring present to use a BMC ADC pin to read the  remaining battery voltage so we can generate low battery warnings.  Not sure if the driver supports that or not?  I think that would be extra credit.

**Comment by csmart** [comment]
ok, thanks @spinler

**Comment by shenki** [comment]
This is in the kernel and the device tree.
