### ISSUE TITLE
Feature: Fan speed toggling based on the need

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#660]
Use Case Scenario 1:  One fan fails, then BMC should detect and increase other fans speed - Counter Rotating
Use Case Scenario 2:  Provision to set fan speed 
Use Case Scenario 3:  Based on the temperature reading, Fan Speed should be adjusted

**Comment by williamspatrick** [comment]
I'm not sure I understand why you opened this.  We have a whole epic for fan control.

**Comment by bradbishop** [comment]
These suggestions are covered by the power thermal fan requirements coming from the Witherspoon platform.
