### ISSUE TITLE
getvpd: FRU VPD into new inventory structures

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#665]
phosphor-vpd-eeprom update
- MRW points to an eeprom and gives purpose - @spinler needs to have required info in place
  -- Could potentially hard code the data into the system layer until MRW data is available
- Basically calling a new method in inventory.  
- Create some new .yaml files to tell new inventory manager required info

**Comment by adamliyi** [comment]
@geissonator , I think for `FRU VPD` you mentioned here, is the FRU managed by BMC (that is, BMC read the FRU info from EEPROM)?

**Comment by adamliyi** [comment]
- [ ] Map IPMI FRU info read from eeprom to dbus objects (inventory object). The object should use the interface defined in phosphor-dbus-interface
- [ ] Ask phosphor-inventory-manager to manage the objects by callying Notify().

**Comment by adamliyi** [comment]
Committed patch: https://gerrit.openbmc-project.xyz/#/c/1701/ based on Ratan's patch for issue openbmc/openbmc#666
