### ISSUE TITLE
getvpd: IPMI VPD into new inventory structures

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#666]
Requires a list of affected inventory from the MRW (will create separate issue for MRW work).
- This could use hard coded data in system layer until MRW is ready if needed

**Comment by Youngzhong** [comment]
Do you need help?

**Comment by geissonator** [comment]
Please work closely with Deepak and Yi on these stories.  Interfaces for this work being defined by Deepak in 11.2 sprint.

**Comment by geissonator** [comment]
Nan has a lot on his plate this sprint so Ratan is going to take this one up.

**Comment by ratagupt** [comment]
- [ ] Get the understanding of how write fru command works.

- [ ] Get the understanding of IPMI fru paser

- [ ] Come up with the design for creation of object path.

- [ ] Write the parser for read the data which is to be generated by MRW.

- [ ] Create the application specific conf

- [ ] Write the logic in the ipmi fru parser to get the instance path.

**Comment by ratagupt** [comment]
-
