### ISSUE TITLE
getvpd: OpenPower VPD into new inventory structures

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#667]
- Just like #665 except we also need to create a parser for the IBM VPD.
- Use hostboot code as reference?

**Comment by dkodihal** [comment]
- [ ] readvpd : write an executable (which can be called by a udev rule) which reads vpd from a source such as eeprom. Invokes parser.
- [ ] parsevpd : write openpower VPD parser.
- [ ] writevpd : write code to fill inventory (by calling the inventory manager) in to the inventory.
- [ ] recipe updates
- [ ] Unit tests

**Comment by geissonator** [comment]
Last commit in the chain merged - https://gerrit.openbmc-project.xyz/#/c/1371/
