### ISSUE TITLE
rtc: Implement real time clock interfaces in new format

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#668]
- Implement the approved interface(s) from #719

**Comment by geissonator** [comment]
Reduced from 2 to 1 point because definition of interface is now in #719

**Comment by williamli80** [comment]
- use yaml defined in phosphor-dbus-interface to generate sdbusplus binding(new APIs);
- use the new API to replace APIs in phosphor-time-manager repo

**Comment by williamli80** [comment]
PR: https://gerrit.openbmc-project.xyz/#/c/1533/

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/#/c/1942/ is the base commit for this

**Comment by mine260309** [comment]
With the patch series to be merged, remains tasks:

- [ ] Update `phosphor-time-manager.bb` to use new service name and executable
- [ ] Update `phosphor-host-ipmid/storagehandler.cpp` to use the new service and interface

**Comment by geissonator** [comment]
@mine260309 - please also remove the old service so the old application no longer gets put in the flash image?  That may be already implied with your task 1 above.

**Comment by mine260309** [comment]
Yup, it should be part of the task 1

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5087> phosphor-time-manager.bb: Use new service name
Resolves  #668 rtc: Implement real time clock interfaces in new format
