### ISSUE TITLE
fw version: Implement get firmware version interface to conform to new design for BMC

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#670]
- Implement the approved interface(s) from #722 
- Need to tie in with code update vision

Need 2 repos from Patrick, 1 for BMC, 1 for OpenPower.
This story will just track doing BMC for now
MFG can use cronus to dump version partition until we get code update in place.

**Comment by JoshDKing** [comment]
- [ ] Initial set up of structure
- [ ] Implement Level Purposes
- [ ] Test code written

**Comment by geissonator** [comment]
Reduce to 1 point since this will now just track getting the BMC version.  The PNOR code version will need to wait until after we get the code update design done.  People can use cronus/pflash to get PNOR version until then.

**Comment by geissonator** [comment]
Redistributing in prep for next sprint.

**Comment by geissonator** [comment]
Implement https://gerrit.openbmc-project.xyz/#/c/1291/1/xyz/openbmc_project/Software/Level.interface.yaml for openbmc code version.

**Comment by geissonator** [comment]
Final piece - https://gerrit.openbmc-project.xyz/#/c/2474
