### ISSUE TITLE
phosphor-dbus-interfaces: Provide interface for dbus object

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#675]
See Brad's comment under: https://gerrit.openbmc-project.xyz/#/c/733/1/log_manager.c

**Comment by williamspatrick** [comment]
This should effectively be done as part of that original work (certainly for all new interfaces going forward), but we could also do this at the point that we do the refactoring to the sdbus interfaces.

**Comment by geissonator** [comment]
Seems like already tracked with current story, @anoo1 to verify.

**Comment by anoo1** [comment]
Done, no need to hardcode the path object with the sdbus bindings.
