### ISSUE TITLE
getvpd: Define dbus interface for IPMI vpd inventory

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#683]
This is a pre-req to #666 
The goal is a documented and approved interface for IPMI vpd inventory.

**Comment by dkodihal** [comment]
- [ ] foo

**Comment by dkodihal** [comment]
- [x] Go through IPMI FRU information storage specification
- [x] Go through hostboot code to understand what VPD is sent down
- [ ] Write YAML files to describe VPD properties for various FRU types
