### ISSUE TITLE
Updating BIOS via REST API wipes out the Boot options (NVRam) not UBI

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#709]
@agangidi53 commented on [Tue Oct 25 2016](https://github.com/openbmc/skeleton/issues/132)

The current update BIOS via BMC TFTP REST API feature does not persist boot options (stored in NVRAM partition of BIOS). It would nice to provide a flag to persist or clear the host boot options before doing the update.

**Comment by anoo1** [comment]
The non-UBI PNOR update is done via pflash which wipes out the whole PNOR when updating. There may be an option to preserve nvram that could be implemented.

**Comment by anoo1** [comment]
An issue is probably better to be opened for https://github.com/open-power/skiboot or their mailing list if this is still desired.
