### ISSUE TITLE
Run CI images under Aspeed Qemu model

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#723]
The following machines should boot on openbmc/qemu master:

 * Witherspoon `-M witherspoon-bmc`
 * Palmetto `-M palmetto-bmc`
 * ast2500-evb `-M ast2500-evb`

We should take the artefacts from these CI builds and boot them

@geissonator may already have an issue for this

**Comment by geissonator** [comment]
Should just need a tweak to https://github.com/openbmc/openbmc-build-scripts/blob/master/scripts/boot-qemu.sh to support an optional machine param and then set it up in the main script - https://github.com/openbmc/openbmc-build-scripts/blob/master/run-qemu-robot-test.sh 
Then just a change to the jenkins job to call it appropriately.  Unfortunately though I've been chasing an intermittent CI failure for quite some time on openpower.xyz (example https://openpower.xyz/job/openbmc-test-qemu-ci/926/console).  I need to spend some time looking into it.

**Comment by geissonator** [comment]
#2272 and #1057 are similar

**Comment by amboar** [comment]
We now also have `-M witherspoon-bmc`.

**Comment by geissonator** [comment]
I'm working on this in #2272 so just going to close this out since I have more details in that one.
