### ISSUE TITLE
Use new dbusplus vtable interfaces and move to generated bindings for event log server

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#727]
Story #338 defined a event log server, it used the older dbus bindings since the new bindings were not available yet.  This story tracks moving to the new one's.

**Comment by geissonator** [comment]
The DBUS yaml interface for this will be defined within the logging repo since it is not a public interface (users call the client commit, under the covers that calls the DBUS interface)

**Comment by anoo1** [comment]
- [ ] Update the log server to use the vtable interfaces and generated bindings.

**Comment by geissonator** [comment]
Still under review, moving - https://gerrit.openbmc-project.xyz/#/c/1023/

**Comment by geissonator** [comment]
Need this one too - https://gerrit.openbmc-project.xyz/#/c/1168/
