### ISSUE TITLE
Match error log metadata with error log commits

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#733]
Sprint planning discussion: 
Start with transaction id of 0 or update sdbusplus to support a transaction id and put in a thread local variable.  There's some "cookie" that gets assigned to a message when it's created, we can do some sort of hash.

**Comment by anoo1** [comment]
Also use elog-gen.hpp to get the required metadata fields.

**Comment by anoo1** [comment]
- [ ] Create a transaction id on the sdbusplus server bindings by hashing the dbus sender and cookie information.
- [ ] Save the transaction id on the server as a thread local variable.
- [ ] Create a random transaction id from the log interface if a transaction id does not exist.
- [ ] Add the transaction id from the log interface as a metadata field to all journal entries.
