### ISSUE TITLE
Support the callout of a logical entity within an error log (design)

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#734]

**Comment by geissonator** [comment]
We probably should break this into 2 stories.  1 where we figure out the design and define the yaml to do the callouts and update the python code to handle them, then another where we write the code to implement the callouts in the elog server.

**Comment by dkodihal** [comment]
@geissonator : how about getting the requirements and design (put into YAML) with the first story?

**Comment by dkodihal** [comment]
- [ ] Requirements : what should be contained in a callout section.
- [ ] Design : Specify a callout section in errorlog YAML.
- [ ] Design : Specify errorlog server behavior upon identifying a callout.

**Comment by geissonator** [comment]
Opened up #854 to track implementation.

**Comment by geissonator** [comment]
Deepak out next sprint so just putting in actual, not committed so we don't lose track of it.

**Comment by dkodihal** [comment]
Code up for review @ https://gerrit.openbmc-project.xyz/#/c/1752
