### ISSUE TITLE
led: Define dbus interface to interact with LED's

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#736]
The goal is a documented and approved interface for LED functionality using the new dbusplus yaml architecture.

**Comment by geissonator** [comment]
#737 implements what we define with this story.

**Comment by vishwabmc** [comment]
Task list breakdown.

- [ ] Identifying the interface names
- [ ] Identifying properties
- [ ] Documenting them in yaml file

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/#/c/1073/
