### ISSUE TITLE
Witherspoon: UCD driver is claiming device but raw access required for workarounds

### ISSUE THREAD

**Issue by yadlapati** [openbmc/openbmc#751]
Paul Robertson is seeing this issue:

Having problems with some devices on I2C12 after loading latest BMC image.  Being unable to talk to UCD chip, dev 0x64, causing problems with power on script.

```
root@witherspoon:~# i2cdetect -y 11
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- 0c -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- UU -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- UU -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: 60 -- -- -- UU -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

```
root@witherspoon:~# uname -r
4.7.10-c5682cbc3542add705e35152329436067bb1f94a

root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-216"
VERSION_ID="v1.99.0-216-gcecba5f-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-216"
BUILD_ID="v1.99.0"
```

Following is the output (correct one) with older driver:
```
root@w3:~# i2cdetect -y 11
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- 0c -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- 32 -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- 51 -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 -- -- -- 64 -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
root@w3:~# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="0.1.0 (krogoth)"
VERSION_ID="v0.6-188-g2ad67f6-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 0.1.0 (krogoth)"
BUILD_ID="v0.6"
```

**Comment by adamliyi** [comment]
This may not be an bug. May be related with https://github.com/openbmc/openbmc/issues/653
@mine260309 , what do you think?

**Comment by shenki** [comment]
This is normal system behaviour when a driver is loaded and bound to the address on the bus. As the kernel driver is in control of the device, you see UU at the address when using i2cdetect.

We need to provide Paul with documentation on how to use the pmbus sysfs files to perform the tests that he is doing. What are these tests? Which bits of information is he looking for?

**Comment by paulgrobertson** [comment]
Here is the UCD script containing i2c commands that are failing.   How do we do this with UCD driver installed?

#!/bin/sh
# #############################################################
# script to disable UCD VCS rails. 
echo Disable UCD control of VCS
i2cset -y 11 0x64 0xF7 0x00 i
i2cset -y 11 0x64 0xF8 0x15 0x6E 0x80 0x0A 0x00 0x00 0x10 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 i
i2cset -y 11 0x64 0xF7 0x01 i
i2cset -y 11 0x64 0xF8 0x15 0x16 0x80 0x14 0x00 0x00 0x20 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 i
i2cset -y 11 0x64 0xD2 0x09 0x3F 0xFF 0x2F 0x0A 0x00 0x06 0x00 0x00 0x02 i
i2cset -y 11 0x64 0x00 0x0E i
i2cset -y 11 0x64 0x02 0x1A i
i2cset -y 11 0x64 0x00 0x0F i
i2cset -y 11 0x64 0x02 0x1A i

**Comment by mine260309** [comment]
@paulgrobertson I know a way to do the test, but it could be a bit complicated: remove `ucd90160@64` part from `arch/arm/boot/dts/aspeed-bmc-opp-witherspoon.dts`, rebuild the kernel, and then do the above test.
Maybe @shenki have better ways.

**Comment by shenki** [comment]
I think you're correct that the driver does not provide the functionality we need.

While I work through the issue, you can unbind the driver from the device. This allows you to use your i2cset command again. I assume once the host has been brought up you could re-bind the driver.


To unbind:
```
cd /sys/bus/i2c/drivers/ucd9000/
echo 0-0064 > unbind
```

To re-bind once you're finished with the sequence:
```
cd /sys/bus/i2c/drivers/ucd9000/
echo 0-0064 > bind
```

I could not test this, so I am guessing at the `0-0064` name. You should see a directory inside `/sys/bus/i2c/drivers/ucd9000/` with the correct name; use that if it's not `0-0064`.

**Comment by shenki** [comment]
I emailed @paulgrobertson with these details

**Comment by paulgrobertson** [comment]
unbind/bind work around verified successfully.

**Comment by geissonator** [comment]
Once we provide official power on support in the code, will this i2c command be required anymore (i.e. is there anything to do with this bug or do we just need to get official power on support in)?

**Comment by paulgrobertson** [comment]
Yes.  VCS problem not fixed until dd2.0

**Comment by shenki** [comment]
A solution has been in place for the past several months
