### ISSUE TITLE
BMC state management and control

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#772]
Originally chassisctl refactor of skeleton.
Breaking this into 2 stories.  1 for BMC state mgmt and control (this one), 1 for Host state mgmt and control ( #783 ).

So this will take the existing interfaces in skeleton for BMC state management and control and provide the ability to get the BMC state and reboot it.  This should be in different objects from the host but in the same process and openbmc repository.

**Comment by JoshDKing** [comment]
- [ ] Determine the necessary requirements & send out email
- [ ] Define yaml for properties and their functions
- [ ] Implement the defined functions & properties

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/#/c/2227/
