### ISSUE TITLE
systemmgr refactor and removal

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#774]
This story tracks the removal of the current_state property in pysystemmgr/system_manager.py.  All code should be moved over to using the new bmc, host, and chassis states.

The persistent storage of state done within this component also needs to be figured out.
The gpio_init code should be moved somewhere as well.
The object/fru lookup interfaces also needs to be moved.
Need to also track catching when services fail and maybe going to some sort of termination state(?)

**Comment by williamspatrick** [comment]
Is this done?
