### ISSUE TITLE
Network refactor

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#780]
Refactor the sub-par interfaces

**Comment by geissonator** [comment]
@ratagupt - I believe you'll be working this one.

**Comment by geissonator** [comment]
@ratagupt and @dkodihal - Need some VLAN stories and then reduce 8pts on this epic to 0.

**Comment by ratagupt** [comment]
#1685

**Comment by geissonator** [comment]
All points assigned

**Comment by geissonator** [comment]
@dkodihal - please push whatever we can out to phase 8
