### ISSUE TITLE
Map functional IPMI sensors to appropriate inventory objects

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#781]
Per #774 this story will be used to implement legacy function from the systemmgr skeleton process.
This specifically tracks what is needed for mfg, the mapping of hostboot functional/present information to the appropriate inventory object.

**Comment by geissonator** [comment]
This needs to at least support the hostboot sensor information (i.e. core functional).
This will just be functional state sensors (Andrew create new story for rest of work)

**Comment by geissonator** [comment]
This has a dependency on some work from Brad to allow state to be tracked in inventory.  Only putting this in actual (vs. committed) for now due to this.

**Comment by spinler** [comment]
At a high level, this will need to map the 'present' and 'disabled' sensor assertions for the DIMM and core functional sensors to inventory operations:
* when a core functional sensor has the Present bit asserted, offset 7 = 0x0080, the core needs to be created in the inventory
* when a core functional sensor has the Disabled bit asserted, offset 8 = 0x0100, the functional property on the inventory object should be set to false.  I'm not sure if this interface/property already exists. 
* the present property should be True if the disabled bit isn't set (maybe default to true?)
* DIMM inventory objects are created by the FRU data hostboot sends down, so this code doesn't need to create DIMM inventory objects ever.  It just needs to set the Functional Property to false if the Disabled bit is set in the sensor (offset 4 = 0x0010)

**Comment by vishwabmc** [comment]
Please reassign this as per discussion in scrum

**Comment by ratagupt** [comment]
- [ ]  Fetching the data from MRW.

- [ ] YAML design.

- [ ] IPMI sensor handler changes.

- [ ] Recipe changes

**Comment by ratagupt** [comment]
- [ ] Generate the cpp from YAML.

**Comment by ratagupt** [comment]
code is up for review for the checked task.
