### ISSUE TITLE
led: Generate required LED information from the MRW

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#803]
Ties in with #737 and #736 - this is to make the LED config determination data driven from the MRW.

@spinler will want to provide some input.

**Comment by vishwabmc** [comment]
- [ ] Understand basic PERL
- [ ] Understand how MRW is structured
- [ ] Understand Norm's Target.pm
- [ ] Work with Matt to get Witherspoon XML having LED targets in it.
- [ ] Write the perl script to generate the YAML file 

Note : I am not very sure if we have all the information available. If something is missing, we need to add that into MRW.

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/1488

**Comment by geissonator** [comment]
Need recipe for this script and a recipe to feed the MRW data to the script
