### ISSUE TITLE
http://www.openbmc-project.xyz/ returns 404

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#805]
We should probably do something a bit better than that. It's already pointing to some github infrastructure so hopefully there's not much effort involved:
![screenshot from 2016-11-11 08-39-49](https://cloud.githubusercontent.com/assets/526481/20251778/f2bea88e-aa6b-11e6-8e95-31d748ee7cce.png)

**Comment by williamspatrick** [comment]
It requires making a repository called 'openbmc.github.io' with what we want as the webpage.

**Comment by amboar** [comment]
Here's a recent update on website publishing: https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3

**Comment by amboar** [comment]
Still 404s.
