### ISSUE TITLE
2-chip P9 vcs support

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#807]
This one tracks the required code to do the vcs work done by Sergey in #647 on a 2 chip configuration.  Alistair needs a little time to verify pdbg on a 2 chip.

**Comment by williamspatrick** [comment]
Should this really be another story?  It is like 2 lines in a script to do a loop and maybe a systemd service file update.

**Comment by geissonator** [comment]
Gotta track it somehow, we can not associate any points with it though.
FYI @spinler

**Comment by spinler** [comment]
We must not be getting a 2 chip system for a while?

**Comment by spinler** [comment]
This is complete with https://gerrit.openbmc-project.xyz/#/c/1704/
