### ISSUE TITLE
Host watchdog gets enabled on debug mode

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#809]
We've regressed and the host watchdog is now enabled when the BMC is set to debug (cronus) mode, the watchdog should not be enabled in this mode. This hampers P9 debug as the system powers off automatically due to the watchdog timer expiring.
Since the skeleton repo is planned to be refactor, maybe fixing the watchdog can be done as part of the state management (power on/off) interface refactoring.

**Comment by anoo1** [comment]
This was seen on firestone on an 'older' (~2 months back) build, need to check the latest master on a supported platform like barreleye.

**Comment by bradbishop** [comment]
For debug mode I was thinking we could just start the power on target:

systemctl start obmc-power-on@0.service

That might not be the right unit name.

**Comment by anoo1** [comment]
As Brad mentioned, just need to start the power on target, it may be called "chassis on" nowadays. Closing.
