### ISSUE TITLE
[Barreleye v1.99.0-291-g7a6b0ba] The base /org listing pruned off ?

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#830]
rango@ubuntu:~/openbmc-test-automation$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X  GET https://xx.xx.xx.xx/
{
 "data": [], 
 "message": "200 OK", 
 "status": "ok"
}

This is suppose to return /org in the data listing.. so the base seems to start with /org/openbmc

rango@ubuntu:~/openbmc-test-automation$ curl -c cjar -b cjar -k -H "Content-Type: application/json" -X  GET https://xx.xx.xx.xx/org/
{
"data": [
    "/org/openbmc"
  ], 
  "message": "200 OK", 
  "status": "ok"

``` What changed which made to behave like this to prune off the base /org listing. ```

There are test case which validates this and are broken because of this..

**Comment by bradbishop** [comment]
This has the same cause as https://github.com/openbmc/openbmc/issues/828

**Comment by gkeishin** [comment]
We still continue to see this in latest build v1.99.0-293-g2feb3ec - ( https://openpower.xyz/job/openbmc-build/386/ )
- [x] Journal log - 
[barreleye_v1.99.0-293-g2feb3ec_Poweron_journal.txt](https://github.com/openbmc/openbmc/files/610526/barreleye_v1.99.0-293-g2feb3ec_Poweron_journal.txt)

**Comment by rahulmah** [comment]
@bradbishop : The issue which you had mention earlier is already closed and fixed. But this issue is still seen with the latest build v1.99.0-309. Please try to look at this issue and provide update.

**Comment by gkeishin** [comment]
This behavior is also seen with the new URI xyz path as well

**Comment by bradbishop** [comment]
I think this was fixed here: openbmc/openbmc#1544
