### ISSUE TITLE
Change the mapper path to the correct one..

### ISSUE THREAD

**Issue by ratagupt** [openbmc/openbmc#837]
Following two files pointing the old mapper path.

1)  skeleton/pciedetect/pcie_slot_present_obj.c 
2)  skeleton/fanctl/fan_control.c

org.openbmc.ObjectMapper should be changed to xyz.openbmc_project.ObjectMapper.

**Comment by amboar** [comment]
See #835

**Comment by ratagupt** [comment]
Closing,Seems it is fixed now.
