### ISSUE TITLE
Witherspoon: BMC Self test result ipmi throwing error

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#840]
root@witherspoon:/tmp# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-295"
VERSION_ID="v1.99.0-295-g3e20a3d-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-295"
BUILD_ID="v1.99.0"

Tried to add automated test case for ipmi self test result  - Related to https://github.com/openbmc/openbmc/issues/436

ipmitool bmc selftest is the generic command, I believe. 

root@witherspoon:/tmp# ./ipmitool bmc selftest  
Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory

root@witherspoon:/tmp# ./ipmitool chassis selftest
Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory

**Comment by sivassrr** [comment]
root@witherspoon:/tmp# ./ipmitool -I dbus bmc selftest
Selftest: not implemented

**Comment by sivassrr** [comment]
Looks like it is not implemented and based on the discussion, It seems down the line , it will be get implemented seems.

**Comment by sivassrr** [comment]
root@witherspoon:/tmp# ./ipmitool -I dbus chassis selftest
Self Test Results    : not implemented

**Comment by williamspatrick** [comment]
We implemented a response to the IPMI command of "not supported". We have no plan of actually doing a self-test. If the BMC is up far enough to respond to IPMI requests then any sort of self-test has passed.

**Comment by sivassrr** [comment]
@williamspatrick - ok then it is not going to add any value to do automation. Will remove it from our automation schedule.

**Comment by cvam0000** [comment]
hey @williamspatrick still mc-selftest is in the planning phase or do we have something for it now ?

**Comment by williamspatrick** [comment]
> hey @williamspatrick still mc-selftest is in the planning phase or do we have something for it now ?

I don't know of any plans to implement an `mc selftest`.
