### ISSUE TITLE
Move to Linux 4.9

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#845]
The 4.7 kernel no longer receives security updates, so we need to move to a kernel that is supported upstream.

4.9 is a LTS kernel and will be used by OpenPower firmware, so we will switch to that once it is released.

4.9 has more upstream drivers for the Apseed SoCs compared to 4.7:

- Pinmux and GPIO (Andrew)
- ftgmac100 ast2500 support (Joel)
- NCSI (Gavin)
- BT (Cedric)
- IRQ controller (Joel/Ben)
- Watchdog (Joel)
- Clocksource (Joel/Ben)

 See https://github.com/openbmc/linux/wiki for more details.

We will need to backport these drivers that are currently staged for 4.10, or out for upstream review:

- I2C (Brendan)
- spi-nor (Cedric)
- adm1275 driver fix (Joel/Yi)

These drivers are still out of tree. The kernel team will focus on getting them cleaned up and reviewed for the 4.11 cycle. For our 4.9 tree the latest versions will be applied:

- clk driver (Joel)
- LPC driver (Joel, Andrew)
- FSI driver (Chris B)
- AHB driver
- PWM driver (Jaghu)
- arch/arm/mach-aspeed changes (Joel)
- devicetree changes (Joel)
- defconfig changes (Joel)

The 4.9 kernel will be released on the 4th or the 10th of December. At that point a dev-4.9 tree will be created and an image built to go through regression testing on hardware. Once we have signoff from Palmetto, Barreleye, Witherspoon and Zaius maintainers we will merge it into the tree.

No userspace changes are anticipated. We have been tracking the upstream changes to the mtd and ipmi-bt drivers in dev-4.7, so that should be fine.

**Comment by williamspatrick** [comment]
We are at 4.10 now, so I assume this is done.
