### ISSUE TITLE
Generate client proxy bindings in sdbusplus

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#851]
Split from #478.

Remaining tasks:

- [ ] Generate client binding for methods.
- [ ] Generate client binding for properties.
- [ ] Add support for dbus-error -> exception mapping on client bindings.
- [ ] Add methods for reading multiple properties at once for client.
- [ ] Generate server binding to unpack object / properties from message (a{sv}).

**Comment by milindur** [comment]
Are there any news on the client code generator?

**Comment by geissonator** [comment]
Pushing this out to 3.0, we've made due without it.
