### ISSUE TITLE
Implement the callout of a logical entity within an error log

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#854]
This one comes after #734

**Comment by geissonator** [comment]
Basic function required for MFG stage 2.

**Comment by dkodihal** [comment]
- [ ] Update phosphor-logging/elog-gen.py to be able to read errors from multiple error YAMLs in one run
- [ ] Update phosphor-logging/elog-gen.py to generate elog API for errors that inherit other errors. The error metadata should be inherited.
- [ ] unit-test : ensure error inheritance works as expected by verifying journal entries
