### ISSUE TITLE
Need Default Witherspoon fan speeds

### ISSUE THREAD

**Issue by spinler** [openbmc/openbmc#855]
There is no fan control code yet, and the fans aren't defaulting to high enough speeds and things are melting.
As a workaround until the fan code is done, we can either
1. figure out the watchdog so it defaults to max (but that may take WDT inits), or
2. pull in the fan script that is floating around the lab

2 is quicker, and though we'll eventually have to figure out the watchdog we can do it later when there's more time

**Comment by amboar** [comment]
@spinler What watchdog are you talking about here?

**Comment by spinler** [comment]
@amboar The one that drives WDTRST1 (pin T22)

**Comment by spinler** [comment]
https://gerrit.openbmc-project.xyz/#/c/1400/
https://gerrit.openbmc-project.xyz/#/c/1401/
https://gerrit.openbmc-project.xyz/#/c/1402/
