### ISSUE TITLE
Jenkins real hardware test failures do not provide sufficient information to debug the issue

### ISSUE THREAD

**Issue by kc8apf** [openbmc/openbmc#877]
https://gerrit.openbmc-project.xyz/#/c/1445/ triggered a real hardware test run which failed.  The link provided for logs (https://jenkins-openbmc.github.io/openbmc-logs/change-1445/patchset-1/) provides a view of what commands were sent to the REST API but not the console logs or anything showing machine-side errors.  I know that it failed to do the code update but I have no idea why.

**Comment by anoo1** [comment]
This is done, Charlie will post an example of data collected and close it.

**Comment by charleshofer** [comment]
Here's an example: https://jenkins-openbmc.github.io/openbmc-logs/change-7000/patchset-1/. You can click FFDC logs and see things from the BMC and OS side.

**Comment by amboar** [comment]
This looks quite useful. Are these URLs provided in the comments on patches in Gerrit?

**Comment by geissonator** [comment]
Yep, you'll get the link directly in your gerrit commit, but only if the job fails.
