### ISSUE TITLE
MRW Common VPD

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#886]
Some notes from sprint planning:

All code required to generate YAML content for inband IPMI format
- Fetch data from mrw
-- Break down into parts (do processors, do memory, ...)
- Write script to generate yaml
- bitbake recipe

Depends on Matt Spinler providing some required MRW data.  Ratan to email Matt with details.

**Comment by ratagupt** [comment]
Need data in the format like ..
Fru
     Associated Device
                 Required Attributes(for each device)
Need to make a list of the required attributes for Associated Non Fru device which is required from MRW.
May Need to make the changes in the Inventory DBUS interfaces also depends on the attribute.

**Comment by ratagupt** [comment]
- [ ] write a perl script to fetch the data from MRW.

- [ ] Write a function which generate YAML file.

- [ ] Write a bitbake file.

**Comment by ratagupt** [comment]
Currently we are interested in following  IPMI FRU types
Proc,Core,Dimm,Membuff,System,NODE(Chassis),MotherBoard.
@williamspatrick :- Do we need to extract something else which I missed?
