### ISSUE TITLE
AVSBus/PMBus for boot-time voltage adjustment for witherspoon

### ISSUE THREAD

**Issue by austinwrx** [openbmc/openbmc#891]
From Jordan's note:

1) Set OPERATION to 0x80
2) Set VOUT_COMMAND voltage per whatever was set in XML - if no voltage is needing to be set this is valid and OK...then it would use whatever the VRM HW set in manufacturing.
3) Set OPERATION to 0xB0 - transfer control immediately over to AVSBus and per HW settings this propagates the whatever is currently in VOUT_COMMAND over to the AVSBus voltage.

To ensure we get a clean power-on and hand control over to AVSBus.  For BMC platforms we'd do this for VDD/VCS/VDN.  This way we don't need to interlock any of this to a particular IPL step.

**Comment by williamspatrick** [comment]
I'm going to close this in favor of the combined Witherspoon / Zaius issue we already have open.  openbmc/openbmc#887.
