### ISSUE TITLE
obmc-console-client escape character "~." is same with ssh connection escape character.

### ISSUE THREAD

**Issue by willenlee** [openbmc/openbmc#898]
When we use ssh to connect to BMC and executing obmc-console-client then entering escape character "~." to  escape obmc-console-client. that will cause ssh session terminated.
Our questions are :
1. ssh and obmc-console-client escape character should not be the same by default setting,right?
2. Have any method to set escape character of obmc-console-client dynamically?

**Comment by mine260309** [comment]
I don't think this is an issue.
* The command to exit from ssh session is `<Return>~.`
* The command to exit from ssh sesseion's ssh session is `<Return>~~.`

So to exit from obmc-console-client, simply type `<Return>~~.`.

**Comment by staneyshen** [comment]
According to the info from below link, user will use ~. to exit obmc-console-client, therfore user will encounter the ssh session terminate problem.

https://github.com/openbmc/docs/blob/master/console.md

Local console connections
If you're already logged into an OpenBMC machine, you can start a console session directly, using:
**$ obmc-console-client**
To exit from a console, type:
**return ~ .**

**Comment by mine260309** [comment]
* If you're using serial console and run `obmc-console-client`, you should type `return ~ .` to quit;
* If you're using ssh to login to OpenBMC, and then run `obmc-console-client`, it is actually running ssh on ssh, so you need to type `return ~~.` to quit `obmc-console-client` and stays in ssh session.

**Comment by staneyshen** [comment]
I agree with your explanation but user doesn't know obmc-console-client is running ssh, they think it likes SOL function.

May I know that will obmc-console-client support -e parameter(like ssh -e "escape char")? Thanks.

**Comment by amboar** [comment]
@mine260309's approach is the normal approach. We just need to document in an obvious place that the double-escape sequence is required. I think that's better than using a non-standard escape sequence.

**Comment by gtmills** [comment]
I will document and then close this issue.

**Comment by amboar** [comment]
How's that documentation going @gtmills ?

**Comment by gtmills** [comment]
Apologies for forgetting about this. 
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/20943

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/20943> Console: Added escaping console while inside ssh
Resolves  #898 obmc-console-client escape character "~." is same with ssh connection escape character.
