### ISSUE TITLE
No REST API available to check NTP server address

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#899]
REST API to set NTP server address for clock is as below. But there is no REST API available to check this NTP server details. This API is required for user to check existing NTP setting from the system.

```
curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\": [\"eth0\", \"xx.xx.xx.xx\"]}" -X POST https://xx.xx.xx.xx/rg/openbmc/NetworkManager/Interface/action/SetNtpServer
```

**BMC Firmware info**
Build #419
root@barreleye:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-338"
VERSION_ID="v1.99.0-338-gd6d3ef3-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-338"
BUILD_ID="v1.99.0"
root@barreleye:~#

**Comment by williamspatrick** [comment]
This is against old, deprecated REST APIs.  We have no plan to enhance.
