### ISSUE TITLE
Barreleye: Unable to set NTP server address for clock correctly

### ISSUE THREAD

**Issue by rahulmah** [openbmc/openbmc#900]
If we try to set NTP address for clock using REST API, then we will see that the server address is set with space between each character. See below step to reproduce for more details. 

Due to this incorrect address, clock is unable to sync with NTP server.

Step to reproduce:

1. Try to set NTP server to 123.108.200.124 using below REST request. Here we will see Empty reply. 
```
curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\": [\"eth0\", \"123.108.200.124\"]}" -X POST https://xx.xx.xx.xx/rg/openbmc/NetworkManager/Interface/action/SetNtpServer
curl: (52) Empty reply from server
```

2. Now try to see what setting is set for NTP by using below command. Here we will given NTP server address is set but with spaces(1 2 3 . 1 0 8 . 2 0 0 . 1 2 4).
```
root@barreleye:~# cat /etc/systemd/network/00-bmc-eth0.network
[Match]
Name = eth0

[Network]
Address = xx.xx.xx.xx/24
Gateway = xx.xx.xx.xx
NTP = 1 2 3 . 1 0 8 . 2 0 0 . 1 2 4
```
**BMC Firmware info**
Build #419
root@barreleye:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-338"
VERSION_ID="v1.99.0-338-gd6d3ef3-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-338"
BUILD_ID="v1.99.0"
root@barreleye:~#

Journal logs are attached below: 
[Journal log for setting NTP server.txt](https://github.com/openbmc/openbmc/files/665875/Journal.log.for.setting.NTP.server.txt)

Let me know if any additional logs are required from this failure.

**Comment by williamspatrick** [comment]
This was testing using old, deprecated REST interfaces.  This will not be fixed as is.
