### ISSUE TITLE
Review Centaur VPD for accuracy 

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#91]
"/org/openbmc/inventory/system/chassis/motherboard/centaur4": {
      "Custom Field 1": "ECID:019A007000185718110D0000004401E1", 
      "Custom Field 2": [], 
      "Custom Field 3": [], 
      "Custom Field 4": [], 
      "Custom Field 5": [], 
      "Custom Field 6": [], 
      "Custom Field 7": [], 
      "Custom Field 8": [], 
      "FRU File ID": [], 
      "Manufacturer": "0000000000000000", 
      "Name": "0000000000000000", 
      "Part Number": "0000000000000000", 
      "Serial Number": "0000000000000000", 
      "fault": "", 
      "fru_type": "MEMORY_BUFFER", 
      "is_fru": 0, 
      "present": "True", 
      "version": "None"
    }

are the values really suppose to be zeros?

**Comment by nkskjames** [comment]
reviewed.  ECID is all we have.
