### ISSUE TITLE
EPOW - Enable OS communication

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#911]
- [ ] Determine standard format/data accepted by OS(use IPMI format?)
- [ ] Setup ipmi data and interfaces to notify OS(thru OPAL?)
- [ ] Create function to populate EPOW data
- [ ] Create function to set/clear EPOW events(timers)

**Comment by msbarth** [comment]
#346

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/141
