### ISSUE TITLE
Every core and dimm not populated shows fault

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#92]
"/org/openbmc/inventory/system/chassis/motherboard/cpu0/core8": {
      "fault": "True", 
      "fru_type": "CORE", 
      "is_fru": 0, 
      "present": "False", 
      "version": "None"
    },

The core is not present nor will it ever.  Why set the Fault value to True?

**Comment by williamspatrick** [comment]
The open-power/hostboot code sends it down that way from IPMI.

**Comment by dcrowell77** [comment]
Can you be more specific about where you are detecting the 'fault' setting?  What bit(s) are you looking at?  Which sensor type are you looking at (we have both functional and fault sensors)?  For a non-present part, we deassert the present offset and assert the disabled offset.  Is the disabled offset the problem?

**Comment by causten** [comment]
Looks promising, just need to get this version on to a system

**Comment by nkskjames** [comment]
This is fixed.
