### ISSUE TITLE
Map remaining IPMI sensors to inventory objects

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#921]
ref: openbmc/skeleton/configs/Witherspoon.py
occ active, fault sensors, system event sensor, boot count, boot progress
Propose how we maintain this info on the BMC, the implement it for each of them
occ active maps to functional state?

1 story - boot count functionality - take the count, apply to reboot policy in state code - 2pts
1 story - boot progress and inventory states - 2pts
1 story - occ functional state and data (power cap, limit) - Should be story coming for this - 2pts

functional dimms first
    - 02/23: Make 921 in an epic and break into stories
        - breakout story for dimms. take 1 pt off boot progress and inventory state for this work.

**Comment by dkodihal** [comment]
Via https://github.com/openbmc/openbmc/issues/781, we're doing core sensors. DIMM sensor is another that is remaining.

**Comment by tomjoseph83** [comment]
- [ ] IPMI sensor handler changes

**Comment by ratagupt** [comment]
The scope of this story is the functional state for the DIMM.

**Comment by rfrandse** [comment]
Made this an Epic and Broke out Stories. 
#1212 was made for the functional state for the DIMM.

**Comment by tomjoseph83** [comment]
@rfrandse Can you make this as an Epic and assign issue for functional dimm to this sprint.
