### ISSUE TITLE
led: Support power supply LED's

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#922]
Power supplies tend to light up their LED's on fail automatically, seems like we can push this one out.

**Comment by sivassrr** [comment]
Is it going to come by phase5?

**Comment by geissonator** [comment]
BMC will still  log error, and it will have appropriate callout, just not LED lit without this story.

**Comment by spinler** [comment]
So far, all LEDs must show up in /sys/class/leds.  If that were to happen for this LED, the PS device driver would need to handle converting that into the I2C Commands to set/clear the LED.  Then, we'd just need to model that LED in the MRW with the appropriate LED attributes, and everything else would just work after that.

**Comment by geissonator** [comment]
Per @spinler - Eddie has some driver changes coming to make the PS faule LED show up in /sys/class/leds, then we'll just need an MRW update.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/9037> Witherspoon XML revision bump
Resolves  #922 led: Support power supply LED's

**Comment by spinler** [comment]
For the sake of completeness, the MRW change I made here also adds in the I2C connections for the power supplies which means we'll get real inventory callouts on I2C fails now, instead of just device path callouts.
