### ISSUE TITLE
Integrating GUI nginx into the image

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#925]

**Comment by spinler** [comment]
Stole a point from here for #2821

**Comment by geissonator** [comment]
This one will track bringing in NGINX (i.e. https://gerrit.openbmc-project.xyz/#/c/6969/).  For current milestone, #2821 will get in with existing web server.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/10045> Allow web socket over nginx https connection
Resolves  #925 Integrating GUI nginx into the image
