### ISSUE TITLE
Resolve error events after hw replacement

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#929]
When an error is created with a hw callout, there will be an association created between the error and the FRU in the callout.  This association will cause the LED manager to potentially light up an LED on that FRU.  Once the issue has been resolved, and the user clears the error, we need to remove this error to inventory item association so things like the LED software will know to turn off.

**Comment by geissonator** [comment]
Think this one is already done @dkodihal ?

**Comment by dkodihal** [comment]
Deleting an error automatically destroys associations that error had.

We also have an interface for a user to mark an error as "Resolved". This will retain the error but will clear associations such as callouts. This was implemented via issue #1379. So closing this one.
