### ISSUE TITLE
EPOW - EPOW 3 enablement

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#933]
- [ ] Create EPOW 3 interface
- [ ] Populate EPOW data for OS to know EPOW 3 event
- [ ] Add 15min timer function including set/reset EPOW 3 event
- [ ] Add ability to shutdown(orderly) after 15min timer expires

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/142
