### ISSUE TITLE
EPOW - EPOW 4 enablement

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#934]
- [ ] Create EPOW 4 interface
- [ ] Populate EPOW 4 data for OS to know of event
- [ ] Add 23sec timer(non-modifiable) function including setting of EPOW 4 event (can not be modified/reset)
- [ ] Add ability to shutdown(hard) after timer expires

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/143
