### ISSUE TITLE
Fan control - Data-driven model

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#935]
- [ ] Create list of necessary fan control/monitoring modifiable variables
(Cooling zones, fan info/specs, zone mgmt, etc..)
- [ ] Determine/format data variables into a consumable structure
(Needs to take into account ability to override any/all of these variables by thermal team testing)
- [ ] Create application that consumes & stores data to be available for fan control/monitoring application

**Comment by bradbishop** [comment]
Data driven is being used but distributed across all the components of the OpenBMC Fan control implementation.  Will track with stories against those components.
