### ISSUE TITLE
log.hpp does not show up in phosphor-logging/log.hpp when included

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#938]
Vishwa brought this up in a code review, we don't seem to be exporting the log.hpp correctly.  It's just showing up in the base include dir but it should be phosphor-logging/log.hpp

Here's the check in a configure.ac for it.
AC_CHECK_HEADER(log.hpp, ,[AC_MSG_ERROR([Could not find log.hpp...openbmc/phosphor-logging package required])])

**Comment by msbarth** [comment]
When this is corrected in phosphor-logging and the AC_CHECK_HEADER is updated in the configure.ac file(s) the openbmc-build-scripts/scripts/unit-test.py DEPENDENCIES will need to be updated also to pull in the phosphor-logging package
