### ISSUE TITLE
ps from petitboot has over 4000 processes

### ISSUE THREAD

**Issue by causten** [openbmc/openbmc#94]
not sure it this is a problem but does seem odd.

**Comment by williamspatrick** [comment]
How is this an openbmc problem?  Isn't it a open-power/skiboot or open-power/buildroot problem?

**Comment by shenki** [comment]
This is normal, as you will see all of the kernel threads in `ps`. For many parts of the kernel create a kthread for each online CPU, and this is how the list grows so large.

Please close.
