### ISSUE TITLE
Fan Control - Setting/adjusting fan floor

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#940]
The fan floor is the lowest allowed speed for fans within a zone based on ambient temperature. Given a list of speeds to ambient temperatures for a zone, this is set that at anytime the ambient sensor temperature value is below the given value, the fan speeds should not drop below that speed but should also increase to that speed if already below it.

- [x] Add/parse a list of temperature-to-RPM within the zone yaml for each zone
- [x] Include a default fan floor speed that is used when no list is provided or when the ambient temp sensor reading is above the highest temperature given
- [x] Add the ambient sensors to a group for an event handler to update each property value
- [x] Add an event action function that calculates & sets the fan floor RPM attribute on the zone
- [x] Each time a new target speed is to be set, the zone's fan floor RPM attribute value should be checked and the speed updated accordingly

**Comment by bradbishop** [comment]
Initial swag guess at 5 pts for this.

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/4762> Allow generation of map types in events
Resolves  #940 Fan Control - Setting/adjusting fan floor
