### ISSUE TITLE
Assert fault LED's when association is set and cleared

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#941]
The error logging component will eventually start associating errors with inventory items.  The LED code needs to monitor for this and assert the appropriate fault LED groups when this happens.  The association will also get cleared at some point, and the fault LED's need to be turned off.

#854 and #352 and #929 are all in this area.

**Comment by vishwabmc** [comment]
This will be done after the callout section is implemented

**Comment by vishwabmc** [comment]
@rfrandse Backend support ( the callout ) is still being developed and hence this should not be marked for current sprints

**Comment by dhruvibm** [comment]
- [ ] Understand LED and inventory

- [ ] Assert LED when a callout is created

- [ ] DeAssert LED when callout is resolved

- [ ] Integration testing.

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/3938 Adding fru fault monitor service
Resolves #941 Assert fault LED's when association is set and cleared
