### ISSUE TITLE
Provide option to disable automatic reboots of host

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#942]
MFG and lab require the ability to disable the automated reboot that happens on a checkstop detection.  This feature will enable that function.  Need to define a property (host?) that can be set/cleared for this function.

**Comment by sivassrr** [comment]
@geissonator This will be only applicable to MFG and lab setup, right. Customer would not see this.  Because Andrea was working/worked on reboot the host on detecting checkstop.

**Comment by geissonator** [comment]
Per a technical discussion today, we're just going to make one generic setting that people can set which will disable any type of automatic reboot.  Re-titling and closing out #943

**Comment by mtritz** [comment]
- [ ] Add new "Enable/disable automatic reboot" element to settingsd
- [ ] New app in host repo to enable or disable reboot based on that element - more details later
- [ ] Recipe/service file to get new app into the right place

**Comment by spinler** [comment]
So how do I disable automatic reboots?

**Comment by mtritz** [comment]
Set the auto_reboot settingsd parameter to "no" - as in
`busctl call org.openbmc.settings.Host /org/openbmc/settings/host0 org.freedesktop.DBus.Properties Set sss org.openbmc.settings.Host auto_reboot no`
