### ISSUE TITLE
Fan control - Degraded mode

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#944]
The following tasks are being handled under other issues previously assigned:
- Issue #1346 : Read tach feedback and compare to allowed hysteresis
- Issue #1493 / #1303 : Add determination for logging error and/or starting power off countdown based on provided fan  parameters(fails before error, fails before shutdown, shutdown delay)

This issue will cover the remaining task of setting the fans to a defined speed upon a certain number of fans become marked as not present or non-functional in inventory. This is a continuation on the fan control application since it is only concerned with setting fans to a target speed.
- [x] Add 'fans missing before zone speed to target' to fan control yaml
- [x] Add 'fans non-functional before zone speed to target' to fan control yaml
- [x] Parse 'fans missing...' and 'fans non-functional...' and add to current zone class
- [x] Add callback function to increment/decrement count of fans missing
- [x] Add callback function to increment/decrement count of fans non-functional
- [x] Set zone fan speed target to defined target when either missing or non-functional count reached
- [ ] Add fan control 'active' attribute for setting when algorithm is active or not
- [x] Update fan control recipe to include events yaml

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/4378 Install events yaml for fan control
Resolves #944 Fan control - Degraded mode
