### ISSUE TITLE
Fan control - Parameter override ability

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#946]
- [ ] Add fan parameter override according to parameter input structure defined
- [ ] Add status msg to journal (or elsewhere) to denote when using override values
- [ ] Lock down ability to override fan parameters?

**Comment by geissonator** [comment]
Phase 7 since this is internal thermal team type test function.

**Comment by rfrandse** [comment]
moved to https://github.com/ibm-openbmc/dev/issues/115
