### ISSUE TITLE
Power Limit - User Power Limit

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#948]

**Comment by geissonator** [comment]
- [ ] Define settings dbus property for this cap
- [ ] Incorporate new dbus object into master occ object (possible or is each occ object the same?)
- [ ] Implement code to write power cap to occ sysfs entry
- [ ] Implement code that ties this new setting to appropriate host ipmid sensor (for reading by htmgt) (is this ipmi sensor already defined?)

**Comment by anoo1** [comment]
https://gerrit.openbmc-project.xyz/#/c/5192/ Notify OCC of pcap setting changes
Resolves openbmc/openbmc#948 Power Limit - User Power Limit
