### ISSUE TITLE
Cache inventory in filesystem

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#957]
Persist phosphor inventory manager inventory through BMC reboot.

**Comment by dkodihal** [comment]
- [ ] Update pimgen.py to generate code to do the load()/save() that Cereal required. This needs to be generated for every inventory interface that we're interested in. The load()/save() can work with the underlying sdbusplus type.
- [ ] When PIM Notify() creates inventory objects, serialize them to a persistent location by calling save().
- [ ] When PIM starts, deserialize persisted objects and do a Notify()? How will we know which interfaces to apply on the object? Store the input to Notify()?

**Comment by dkodihal** [comment]
# **STATUS**

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/5877> pimgen: ignore xyz.openbmc_project.Assocation
Resolves  #957 Cache inventory in filesystem
