### ISSUE TITLE
Fan control - Poweron presence detection

### ISSUE THREAD

**Issue by msbarth** [openbmc/openbmc#959]
Need to get the basic fan application framework in place, which includes creating a new repo, recipe for including into BMC image, and starting at power on. In addition, to keep the system thermally safe at poweron, inventory objects for fan presence detection(3 apps; GPIO, tach feedback, GPIO w/ tach feedback fallback) should be done at poweron. Log any errors for fans found missing at poweron and shutdown the system.

**Comment by msbarth** [comment]
- [ ] Create fan control/monitoring repository
- [ ] Get fan monitoring application framework in place
- [ ] Determine number of fans and locations within the system
- [ ] Check for fan presence(by tach feedback = 0) at poweron
- [ ] Log error for any fans missing and shutdown system(assuming this doesnt break lab systems)
- [ ] Create recipe to include into BMC image and start at power on

**Comment by geissonator** [comment]
Sprint planning notes
- Use Brad's new dbus objects to read fans
- Need meeting tomorrow with Brad/Patrick/Matt to discuss.

**Comment by msbarth** [comment]
Determine, for the time being, how to shutdown the system due to any fans missing when inventory objects created when no tach is found after task list items complete.
