### ISSUE TITLE
[palmetto v1.99.0-377-ge4c152a] FRU presence field is not set 

### ISSUE THREAD

**Issue by SrideviRamesh** [openbmc/openbmc#960]
Expected Behavior:
presence detect should be True on things that exist system, chassis

Actual Behavior:
Presence Detect failing for system, chassis

Log Info:
```

bash-4.1$ curl -c cjar -b cjar -khttps://XX.XX.XX.XX//org/openbmc/inventory/system"
{
  "data": {
    "Asset Tag": "",
    "Custom Field 1": "\tbuildroot-211bd05",
    "Custom Field 2": "\tskiboot-5.3.6",
    "Custom Field 3": "\thostboot-3ed4df7",
    "Custom Field 4": "\tlinux-4.4.21-openpower1-d43e553",
    "Custom Field 5": "\tpetitboot-v1.3.0-d1ee745",
    "Custom Field 6": "\tpalmetto-xml-c6f5639-d76d973",
    "Custom Field 7": "\tocc-bb092e9",
    "Custom Field 8": "\thostboot-binaries-7f593a3",
    "FRU File ID": "",
    "Manufacturer": "",
    "Model Number": "",
    "Name": "OpenPOWER Firmware",
    "Serial Number": "",
    "Version": "open-power-palmetto-922a1c1",
    "fault": "False",
    "fru_type": "SYSTEM",
    "is_fru": 1,
    "present": "False",
    "version": ""
  },
  "message": "200 OK",
  "status": "ok"
}-bash-4.1$ curl -c cjar -b cjar -k https://XX.XX.XX.XX//org/openbmc/inventory/system/chassis
{
  "data": {
    "Custom Field 1": "",
    "Custom Field 2": "",
    "Custom Field 3": "",
    "Custom Field 4": "",
    "Custom Field 5": "",
    "Custom Field 6": "",
    "Custom Field 7": "",
    "Custom Field 8": "",
    "Part Number": "TN71-BP012      ",
    "Serial Number": "0000000000000000",
    "Type": 2,
    "fault": "False",
    "fru_type": "SYSTEM",
    "is_fru": 1,
    "present": "False",
    "version": ""
  },
  "message": "200 OK",
  "status": "ok"
}-bash-4.1$

```

Specifications:

cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-377"
VERSION_ID="v1.99.0-377-ge4c152a-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-377"
BUILD_ID="v1.99.0"

FFDC & journal logs attached
[20170112030018170484_SystemPresent.zip](https://github.com/openbmc/openbmc/files/701165/20170112030018170484_SystemPresent.zip)
[20170112025823681253_ChassisPresent.zip](https://github.com/openbmc/openbmc/files/701168/20170112025823681253_ChassisPresent.zip)
[test_chassis_journal.txt](https://github.com/openbmc/openbmc/files/701170/test_chassis_journal.txt)
[test_sensor_journal.txt](https://github.com/openbmc/openbmc/files/701172/test_sensor_journal.txt)

**Comment by vishwabmc** [comment]
@SrideviRamesh Have you tried this on the same build level ?

**Comment by SrideviRamesh** [comment]
@vishwabmc i have tried on the build level mentioned in the log

**Comment by vishwabmc** [comment]
@SrideviRamesh In your first post, it just had : 

-bash-4.1$ curl -c cjar -b cjar -k https://xx.xx.xx.xx//org/openbmc/inventory/system
{
  "data": {
    "fault": "False",
    "fru_type": "SYSTEM",
    "is_fru": 1,
    "present": "True",
    "version": ""
  },
  "message": "200 OK",
  "status": "ok"
}

and what I see now is different. Which is the right one ?

**Comment by vishwabmc** [comment]
@williamspatrick Looking at the original issue : openbmc/openbmc#93, you have this quote there

`Palmetto doesn't have a VPD chip on the backplane that the BMC can access. That is why it is missing the call you mentioned.`

So should we just ignore this testcase for good on Palmetto ?. @SrideviRamesh told me that she ran this testcase today and saw the failure.  Its an independent testcase and does not cause any issues to rest of their tests

**Comment by gkeishin** [comment]
Inventory are now in xyz. no further action needed on this..
