### ISSUE TITLE
Add support for fanx_target hwmons

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#962]
Add function to control fan speeds via hwmon fann_target sysfs entries.
A new interface will be required.
Put objects in control or sensor namespace?

**Comment by msbarth** [comment]
- [ ] Discuss design layout of changes with Brad
- [ ] Add new interface in 'control' namespace
- [ ] Create function to update hwmon fan_target sysfs entries
- [ ] Manually test fan speed changes
