### ISSUE TITLE
Add constructor with properties to generated server interface bindings

### ISSUE THREAD

**Issue by bradbishop** [openbmc/openbmc#970]
Generate a server interface binding constructor that takes a map of property name/values such that when the org.freedesktop.DBus.InterfacesAdded signal is emitted, all the properties are fully populated with the values passed to the constructor.

**Comment by williamspatrick** [comment]
remote:   https://gerrit.openbmc-project.xyz/2216 sdbus++: add server method for set-property
remote:   https://gerrit.openbmc-project.xyz/2217 sdbus++: Add server constructor from property-map
