### ISSUE TITLE
Remove P9 host watchdog workaround.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc#993]
Hostboot currently has IPMI support disabled.  When open-power/op-build#828 is closed we can remove the workarounds we have in place.

**Comment by spinler** [comment]
Removed for Zaius.

**Comment by williamspatrick** [comment]
Only romulus is left.  Assigning to Lei to finish it out.

**Comment by mine260309** [comment]
Romulus PNOR now has IPMI enabled, so the watchdog workaround is removed on Romulus:
https://gerrit.openbmc-project.xyz/#/c/3885/
