### ISSUE TITLE
Create error if BMC EERPOM device is not found

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#995]
Need to ensure we generate an error if the BMC EEPROM doesn't show up by the time we hit systemd standby target.
Could work into the inventory rules, or just have an app that looks for the inventory item and logs an error if not found.

**Comment by geissonator** [comment]
Non critical so moving into backlog for now

**Comment by williamspatrick** [comment]
Based on today's design discussion this might fit nicely into what @msbarth proposed today.

**Comment by msbarth** [comment]
Brad is assigned issue #1303 which should be able to handle this change as described.

**Comment by geissonator** [comment]
Sounds good to me, handled in #1303
