### ISSUE TITLE
mboxd: 'Unknown lvalue' warnings for Wants and After directives

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#999]
Discovered in the logs by @spinler:

```
Jan 20 22:11:29 zaius systemd[1]: Reloading.
Jan 20 22:11:30 zaius systemd[1]: [/lib/systemd/system/mboxd.service:7] Unknown lvalue 'Wants' in section 'Service'
Jan 20 22:11:30 zaius systemd[1]: [/lib/systemd/system/mboxd.service:8] Unknown lvalue 'After' in section 'Service'
```

This could be caused by the directives appearing in the wrong section of the unit file.

**Comment by vishwabmc** [comment]
Wants=op-wait-power-off@%i.service
After=op-wait-power-off@%i.service

Should those be mapper-wait instead ?.

**Comment by spinler** [comment]
@vishwabmc What are you referring to?

**Comment by spinler** [comment]
@amboar Are you planning on fixing this yourself?

**Comment by amboar** [comment]
@spinler yes, I'll clean it up today

**Comment by amboar** [comment]
Patches are in gerrit: https://gerrit.openbmc-project.xyz/#/q/topic:mboxd-service
